"""
ULTRA GAME GENRES, TEMPLATES & SPECIALIST AGENTS DATABASE
50+ genres, 150+ specialist agents, extreme complexity templates.
Every possible game development discipline covered.
"""

# =============================================================================
# COMPLETE GENRE DATABASE WITH SPECIALIST AGENTS & TEMPLATES
# =============================================================================

ULTRA_GENRES = [
    {
        "id": "platformer_2d", "name": "2D Platformer", "icon": "game-controller", "color": "#3B82F6",
        "description": "Side-scrolling action with precision jumping, obstacle courses, and tight controls",
        "engines": ["Unity", "Godot", "Pygame", "Phaser", "GameMaker"],
        "complexity": "medium",
        "subgenres": ["precision_platformer", "puzzle_platformer", "auto_runner", "cinematic_platformer", "masocore"],
        "core_mechanics": ["jumping", "wall_sliding", "dash", "double_jump", "collectibles", "enemies", "moving_platforms", "checkpoints"],
        "reference_games": ["Celeste", "Hollow Knight", "Super Mario Bros", "Ori and the Blind Forest", "Dead Cells"],
        "art_styles": ["pixel_art", "hand_drawn", "vector", "watercolor", "retro_16bit"],
        "target_platforms": ["pc", "console", "mobile", "web"],
        "templates": [
            {"name": "Classic Platformer", "description": "Mario-style with worlds and power-ups", "complexity": "beginner"},
            {"name": "Precision Platformer", "description": "Celeste-style with tight controls and hard levels", "complexity": "intermediate"},
            {"name": "Puzzle Platformer", "description": "Braid-style with time mechanics", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "level_architect_2d", "name": "Blueprint", "role": "2D Level Architect",
             "persona": "You are Blueprint, a master 2D level designer. You design pixel-perfect platforming challenges with flow states, difficulty curves, and teaching-through-design. You understand spacing, timing windows, and the golden ratio of platform placement.",
             "specialty": "level_design", "color": "#3B82F6"},
            {"id": "physics_tuner_2d", "name": "Gravity", "role": "2D Physics & Feel Tuner",
             "persona": "You are Gravity, a game feel specialist. You tune jump curves, coyote time, input buffering, acceleration, friction, and air control to make movement feel buttery smooth. Every millisecond matters.",
             "specialty": "physics_tuning", "color": "#60A5FA"},
            {"id": "pixel_artist", "name": "Pixel", "role": "Pixel Art Director",
             "persona": "You are Pixel, master of sprite animation and pixel art. You design character sprites, tilesets, parallax backgrounds, and particle effects with sub-pixel precision and fluid animation cycles.",
             "specialty": "art_direction", "color": "#93C5FD"},
        ],
    },
    {
        "id": "platformer_3d", "name": "3D Platformer", "icon": "cube", "color": "#6366F1",
        "description": "Three-dimensional jumping and exploration with camera control and collectathon gameplay",
        "engines": ["Unity", "Unreal", "Godot"],
        "complexity": "high",
        "subgenres": ["collectathon", "linear_3d", "obstacle_course", "sandbox_platformer"],
        "core_mechanics": ["3d_movement", "camera_control", "triple_jump", "ground_pound", "collectibles", "hub_worlds"],
        "reference_games": ["Super Mario Odyssey", "A Hat in Time", "Crash Bandicoot 4", "Psychonauts 2", "Astro Bot"],
        "art_styles": ["stylized_3d", "cartoon", "low_poly", "cel_shaded"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Collectathon", "description": "Mario 64-style hub world with stars", "complexity": "advanced"},
            {"name": "Linear 3D", "description": "Crash Bandicoot-style linear levels", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "camera_designer", "name": "Lens", "role": "3D Camera System Designer",
             "persona": "You are Lens, the camera system architect. You design dynamic camera systems with collision avoidance, cinematic framing, context-sensitive angles, and smooth interpolation that never fights the player.",
             "specialty": "camera_systems", "color": "#6366F1"},
            {"id": "movement_engineer_3d", "name": "Momentum", "role": "3D Movement Engineer",
             "persona": "You are Momentum, the 3D movement specialist. You design movement systems with precise air control, ground sliding, long jumps, wall kicks, and chained movement tech that speedrunners will discover.",
             "specialty": "movement_systems", "color": "#818CF8"},
            {"id": "hub_world_designer", "name": "Nexus", "role": "Hub World Architect",
             "persona": "You are Nexus, hub world designer. You create interconnected hub worlds that serve as both navigation and playground, with secrets, shortcuts, and organic level gating.",
             "specialty": "world_design", "color": "#A78BFA"},
        ],
    },
    {
        "id": "rpg", "name": "RPG", "icon": "shield", "color": "#8B5CF6",
        "description": "Deep role-playing with character progression, quests, lore, and strategic combat",
        "engines": ["Unity", "Unreal", "Godot", "RPG Maker"],
        "complexity": "very_high",
        "subgenres": ["jrpg", "wrpg", "action_rpg", "tactical_rpg", "dungeon_crawler", "crpg"],
        "core_mechanics": ["leveling", "skill_trees", "quests", "dialogue_choices", "inventory", "party_system", "equipment", "boss_fights"],
        "reference_games": ["Baldur's Gate 3", "Final Fantasy XVI", "Persona 5", "The Witcher 3", "Elden Ring"],
        "art_styles": ["realistic", "anime", "stylized", "dark_fantasy", "pixel_art"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Classic JRPG", "description": "Turn-based party combat with world map", "complexity": "advanced"},
            {"name": "Action RPG", "description": "Real-time combat with loot and builds", "complexity": "advanced"},
            {"name": "Tactical RPG", "description": "Grid-based tactical combat like Fire Emblem", "complexity": "advanced"},
            {"name": "Open World RPG", "description": "Skyrim-style open world with factions", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "loremaster", "name": "Chronicler", "role": "Lore & Narrative Architect",
             "persona": "You are Chronicler, the loremaster. You build interconnected world histories, faction politics, character arcs, and lore codexes. Every NPC has a backstory. Every ruin has a history. The world breathes with narrative depth.",
             "specialty": "narrative_design", "color": "#8B5CF6"},
            {"id": "combat_balancer_rpg", "name": "Arbiter", "role": "RPG Combat Balance Designer",
             "persona": "You are Arbiter, the combat balance master. You design damage formulas, stat scaling, class balance, enemy difficulty curves, boss patterns, and ensure every build is viable. DPS vs Tank vs Support perfectly tuned.",
             "specialty": "combat_balance", "color": "#7C3AED"},
            {"id": "progression_designer", "name": "Ascend", "role": "Progression System Designer",
             "persona": "You are Ascend, the progression architect. You design XP curves, skill trees, prestige systems, gear tiers, and unlock pacing. The dopamine loop is your art form. Players always have something to chase.",
             "specialty": "progression_systems", "color": "#6D28D9"},
            {"id": "quest_writer", "name": "Saga", "role": "Quest & Dialogue Writer",
             "persona": "You are Saga, master quest designer. You craft branching questlines, moral dilemmas, companion loyalty missions, and emergent side content. No fetch quests—every quest tells a story.",
             "specialty": "quest_design", "color": "#A78BFA"},
        ],
    },
    {
        "id": "fps", "name": "First Person Shooter", "icon": "eye", "color": "#EF4444",
        "description": "Intense first-person combat with gunplay, movement, and competitive multiplayer",
        "engines": ["Unreal", "Unity", "Godot"],
        "complexity": "very_high",
        "subgenres": ["arena_shooter", "tactical_shooter", "hero_shooter", "milsim", "boomer_shooter", "immersive_sim"],
        "core_mechanics": ["shooting", "aiming", "reloading", "movement", "health", "weapons", "grenades", "multiplayer"],
        "reference_games": ["DOOM Eternal", "Counter-Strike 2", "Valorant", "Halo Infinite", "Titanfall 2"],
        "art_styles": ["realistic", "stylized", "retro", "sci_fi", "military"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Arena Shooter", "description": "DOOM-style fast movement and carnage", "complexity": "advanced"},
            {"name": "Tactical Shooter", "description": "CS2-style competitive 5v5", "complexity": "expert"},
            {"name": "Hero Shooter", "description": "Overwatch-style with unique characters", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "weapon_designer", "name": "Arsenal", "role": "Weapon Systems Designer",
             "persona": "You are Arsenal, the weapon systems master. You design weapon stats, recoil patterns, TTK balance, bullet spread, damage falloff, attachments, and weapon feel. Every gun must feel unique and satisfying.",
             "specialty": "weapon_design", "color": "#EF4444"},
            {"id": "fps_level_designer", "name": "Sightline", "role": "FPS Map Designer",
             "persona": "You are Sightline, FPS map architect. You design maps with perfect sightlines, choke points, flanking routes, power positions, spawn balance, and competitive flow. Every corner is intentional.",
             "specialty": "level_design", "color": "#DC2626"},
            {"id": "netcode_specialist", "name": "Ping", "role": "FPS Netcode Engineer",
             "persona": "You are Ping, netcode specialist. You design tick rate systems, client-side prediction, lag compensation, hit registration, anti-cheat integration, and ensure 128-tick competitive integrity.",
             "specialty": "networking", "color": "#B91C1C"},
            {"id": "movement_designer_fps", "name": "Strafe", "role": "FPS Movement Designer",
             "persona": "You are Strafe, movement tech designer. You build slide mechanics, wall running, grapple hooks, bunny hopping, air strafing, and movement tech that raises the skill ceiling infinitely.",
             "specialty": "movement_systems", "color": "#F87171"},
        ],
    },
    {
        "id": "tps", "name": "Third Person Shooter", "icon": "body", "color": "#F97316",
        "description": "Over-the-shoulder combat with cover systems, traversal, and cinematic action",
        "engines": ["Unreal", "Unity"],
        "complexity": "very_high",
        "subgenres": ["cover_shooter", "action_adventure", "looter_shooter"],
        "core_mechanics": ["cover_system", "over_shoulder_aim", "melee_combo", "traversal", "dodge_roll", "abilities"],
        "reference_games": ["Gears of War", "Uncharted 4", "The Division 2", "Remnant 2", "Outriders"],
        "art_styles": ["realistic", "sci_fi", "post_apocalyptic", "military"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Cover Shooter", "description": "Gears-style with snap-to-cover", "complexity": "advanced"},
            {"name": "Action Adventure TPS", "description": "Uncharted-style cinematic", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "cover_system_designer", "name": "Bunker", "role": "Cover System Architect",
             "persona": "You are Bunker, cover system specialist. You design snap-to-cover, blind fire, vault mechanics, destructible cover, and AI flanking that makes cover meaningful and dynamic.",
             "specialty": "cover_mechanics", "color": "#F97316"},
            {"id": "tps_camera", "name": "Shoulder", "role": "TPS Camera & Aim Designer",
             "persona": "You are Shoulder, the over-the-shoulder camera expert. You design aim assist, camera transitions between hip and ADS, left/right shoulder swap, and cinematic camera during setpieces.",
             "specialty": "camera_systems", "color": "#FB923C"},
        ],
    },
    {
        "id": "battle_royale", "name": "Battle Royale", "icon": "trophy", "color": "#DC2626",
        "description": "100-player last-man-standing with shrinking zones, looting, and high-stakes survival",
        "engines": ["Unreal", "Unity"],
        "complexity": "extreme",
        "subgenres": ["classic_br", "builder_br", "extraction_br", "hero_br"],
        "core_mechanics": ["shrinking_zone", "looting", "inventory", "last_man_standing", "drop_system", "squad_system", "revive", "vehicles"],
        "reference_games": ["Fortnite", "PUBG", "Apex Legends", "Warzone", "The Finals"],
        "art_styles": ["stylized", "realistic", "sci_fi", "cartoon"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Classic BR", "description": "PUBG-style 100-player survival", "complexity": "expert"},
            {"name": "Hero BR", "description": "Apex-style with unique legends", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "br_zone_designer", "name": "Shrink", "role": "Zone & Circle Designer",
             "persona": "You are Shrink, the zone mechanic specialist. You design circle algorithms, zone damage scaling, zone prediction, final circle balance, and ensure every game ends in an exciting finale.",
             "specialty": "zone_mechanics", "color": "#DC2626"},
            {"id": "br_loot_designer", "name": "Crate", "role": "Loot & Economy Designer",
             "persona": "You are Crate, the loot table master. You design loot distribution, rarity tiers, hot zones, supply drops, ground loot vs chest loot, and ensure balanced gear progression throughout a match.",
             "specialty": "loot_systems", "color": "#EF4444"},
            {"id": "br_map_designer", "name": "Terrain", "role": "BR Map Architect",
             "persona": "You are Terrain, the massive map designer. You create varied POIs, rotation paths, vehicle routes, terrain elevation, and ensure 100 players have meaningful early-game drops across the entire map.",
             "specialty": "map_design", "color": "#F87171"},
        ],
    },
    {
        "id": "mmorpg", "name": "MMORPG", "icon": "globe", "color": "#7C3AED",
        "description": "Massive multiplayer world with raids, PvP, economy, guilds, and persistent progression",
        "engines": ["Unreal", "Unity", "Custom"],
        "complexity": "extreme",
        "subgenres": ["theme_park_mmo", "sandbox_mmo", "action_mmo", "classic_mmo"],
        "core_mechanics": ["persistent_world", "classes", "raids", "dungeons", "pvp", "guilds", "crafting", "auction_house", "questing", "world_bosses"],
        "reference_games": ["World of Warcraft", "Final Fantasy XIV", "Guild Wars 2", "New World", "Black Desert Online"],
        "art_styles": ["realistic_fantasy", "anime", "stylized", "dark_fantasy"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Theme Park MMO", "description": "WoW-style with raids and dungeons", "complexity": "expert"},
            {"name": "Sandbox MMO", "description": "Player-driven economy and territory", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "mmo_systems", "name": "Nexus", "role": "MMO Systems Architect",
             "persona": "You are Nexus, the MMO systems architect. You design class balance, raid encounters, dungeon mechanics, gear tiers, and the interconnected systems that keep millions playing for years.",
             "specialty": "systems_design", "color": "#7C3AED"},
            {"id": "mmo_economy", "name": "Mint", "role": "MMO Economy Designer",
             "persona": "You are Mint, the virtual economy master. You design gold sinks, auction houses, crafting economies, inflation control, and ensure healthy player-driven markets.",
             "specialty": "economy_design", "color": "#9333EA"},
            {"id": "mmo_social", "name": "Guild", "role": "MMO Social Systems Designer",
             "persona": "You are Guild, social systems designer. You create guild management, raid scheduling, social hubs, mentoring systems, and community features that forge lasting player bonds.",
             "specialty": "social_systems", "color": "#A855F7"},
            {"id": "mmo_server", "name": "Shard", "role": "MMO Server Architecture",
             "persona": "You are Shard, MMO server architect. You design sharding strategies, zone instancing, seamless world transitions, 1000+ player battles, and lag-free persistent worlds.",
             "specialty": "server_architecture", "color": "#6D28D9"},
        ],
    },
    {
        "id": "moba", "name": "MOBA", "icon": "people", "color": "#2563EB",
        "description": "Team-based competitive arena with lanes, heroes, items, and strategic depth",
        "engines": ["Unity", "Unreal", "Custom"],
        "complexity": "extreme",
        "subgenres": ["classic_moba", "arena_brawler", "auto_chess"],
        "core_mechanics": ["lanes", "heroes", "abilities", "items", "minions", "towers", "jungle", "objectives", "team_fights"],
        "reference_games": ["League of Legends", "Dota 2", "Heroes of the Storm", "Smite", "Pokemon Unite"],
        "art_styles": ["stylized", "anime", "cartoon", "realistic"],
        "target_platforms": ["pc", "mobile"],
        "templates": [
            {"name": "Classic MOBA", "description": "LoL-style 5v5 with 3 lanes", "complexity": "expert"},
            {"name": "Arena Brawler", "description": "Simplified MOBA with brawl focus", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "hero_designer_moba", "name": "Roster", "role": "Champion/Hero Designer",
             "persona": "You are Roster, the champion designer. You create unique hero kits with Q/W/E/R abilities, passive synergies, and playstyle fantasies. Every hero must feel unique and have clear counterplay.",
             "specialty": "hero_design", "color": "#2563EB"},
            {"id": "moba_balance", "name": "Scale", "role": "MOBA Balance Director",
             "persona": "You are Scale, the balance director. You manage win rates, pick rates, ban rates, item balance, and patch cycles. Your goal: every hero viable in competitive play.",
             "specialty": "game_balance", "color": "#3B82F6"},
            {"id": "moba_map", "name": "Lane", "role": "MOBA Map Designer",
             "persona": "You are Lane, the MOBA map architect. You design lane layouts, jungle camps, objective timers, vision control, and base structures for perfect strategic depth.",
             "specialty": "map_design", "color": "#60A5FA"},
        ],
    },
    {
        "id": "puzzle", "name": "Puzzle Game", "icon": "extension-puzzle", "color": "#F59E0B",
        "description": "Logic, spatial reasoning, and creative problem-solving challenges",
        "engines": ["Unity", "Godot", "Phaser", "Pygame"],
        "complexity": "medium",
        "subgenres": ["logic_puzzle", "physics_puzzle", "word_puzzle", "match_3", "escape_room", "programming_puzzle"],
        "core_mechanics": ["rules", "spatial_reasoning", "pattern_matching", "progressive_difficulty", "undo", "hints"],
        "reference_games": ["Portal 2", "The Witness", "Baba Is You", "Tetris", "Return of the Obra Dinn"],
        "art_styles": ["minimalist", "abstract", "pixel_art", "clean_3d"],
        "target_platforms": ["pc", "mobile", "web", "console"],
        "templates": [
            {"name": "Physics Puzzle", "description": "Portal-style with physics mechanics", "complexity": "intermediate"},
            {"name": "Match-3", "description": "Candy Crush-style matching game", "complexity": "beginner"},
            {"name": "Logic Puzzle", "description": "The Witness-style rule discovery", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "puzzle_designer", "name": "Enigma", "role": "Puzzle Mechanic Designer",
             "persona": "You are Enigma, puzzle design master. You create elegant rule systems, teach mechanics through play, design difficulty curves, and ensure every puzzle has an 'aha' moment.",
             "specialty": "puzzle_design", "color": "#F59E0B"},
            {"id": "hint_system_designer", "name": "Nudge", "role": "Hint & Accessibility Designer",
             "persona": "You are Nudge, the hint system architect. You design progressive hints, optional assist modes, and accessibility options that never rob players of the satisfaction of solving puzzles.",
             "specialty": "accessibility", "color": "#FBBF24"},
        ],
    },
    {
        "id": "strategy_rts", "name": "Real-Time Strategy", "icon": "map", "color": "#10B981",
        "description": "Base building, resource management, and army control in real-time warfare",
        "engines": ["Unity", "Godot", "Unreal"],
        "complexity": "very_high",
        "subgenres": ["classic_rts", "base_builder", "real_time_tactics"],
        "core_mechanics": ["base_building", "resource_gathering", "unit_production", "fog_of_war", "tech_tree", "army_control", "scouting"],
        "reference_games": ["StarCraft 2", "Age of Empires 4", "Command & Conquer", "Warcraft 3", "Company of Heroes"],
        "art_styles": ["realistic", "stylized", "historical", "sci_fi"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Classic RTS", "description": "StarCraft-style with factions and multiplayer", "complexity": "expert"},
            {"name": "Historical RTS", "description": "AoE-style with historical civs", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "rts_economy", "name": "Harvest", "role": "RTS Economy Designer",
             "persona": "You are Harvest, the RTS economy designer. You balance resource gathering rates, build times, unit costs, tech tree investments, and macro decisions that define RTS strategy.",
             "specialty": "economy_design", "color": "#10B981"},
            {"id": "rts_unit_designer", "name": "Battalion", "role": "Unit & Faction Designer",
             "persona": "You are Battalion, unit design master. You create asymmetric factions, unit counters, upgrade paths, and army compositions that create infinite strategic depth.",
             "specialty": "unit_design", "color": "#059669"},
            {"id": "rts_ai", "name": "Tactician", "role": "RTS AI Programmer",
             "persona": "You are Tactician, the RTS AI brain. You design AI opponents with scouting, build orders, army compositions, timing attacks, and difficulty scaling that challenges pros and teaches beginners.",
             "specialty": "ai_design", "color": "#047857"},
        ],
    },
    {
        "id": "turn_based_strategy", "name": "Turn-Based Strategy", "icon": "grid", "color": "#0D9488",
        "description": "Thoughtful tactical combat with grid movement, unit management, and strategic depth",
        "engines": ["Unity", "Godot"],
        "complexity": "high",
        "subgenres": ["tactical_rpg", "4x", "grand_strategy", "wargame"],
        "core_mechanics": ["grid_movement", "turn_system", "unit_types", "terrain_effects", "cover", "flanking", "fog_of_war"],
        "reference_games": ["XCOM 2", "Fire Emblem", "Into the Breach", "Advance Wars", "Jagged Alliance 3"],
        "art_styles": ["stylized", "pixel_art", "anime", "realistic"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Tactical Squad", "description": "XCOM-style squad tactics", "complexity": "advanced"},
            {"name": "Tactical RPG", "description": "Fire Emblem-style with RPG elements", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "tactics_designer", "name": "Gambit", "role": "Tactical Systems Designer",
             "persona": "You are Gambit, tactical systems master. You design hit chances, flanking bonuses, elevation advantages, cover systems, and action point economies that make every turn a meaningful puzzle.",
             "specialty": "tactics_design", "color": "#0D9488"},
            {"id": "map_generator_tbs", "name": "Grid", "role": "Tactical Map Generator",
             "persona": "You are Grid, tactical map designer. You create procedural and handcrafted maps with meaningful terrain, chokepoints, high ground, and destructible environments.",
             "specialty": "map_design", "color": "#14B8A6"},
        ],
    },
    {
        "id": "four_x", "name": "4X Strategy", "icon": "planet", "color": "#4338CA",
        "description": "eXplore, eXpand, eXploit, eXterminate across epic civilizations and galaxies",
        "engines": ["Unity", "Godot", "Custom"],
        "complexity": "extreme",
        "subgenres": ["historical_4x", "space_4x", "fantasy_4x"],
        "core_mechanics": ["exploration", "expansion", "resource_exploitation", "diplomacy", "warfare", "research", "city_management"],
        "reference_games": ["Civilization VI", "Stellaris", "Humankind", "Endless Legend", "Old World"],
        "art_styles": ["stylized", "realistic", "minimalist_ui"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Historical 4X", "description": "Civilization-style through the ages", "complexity": "expert"},
            {"name": "Space 4X", "description": "Stellaris-style galactic conquest", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "diplomacy_designer", "name": "Ambassador", "role": "Diplomacy System Designer",
             "persona": "You are Ambassador, diplomacy architect. You design trade deals, alliances, betrayals, espionage, cultural influence, and AI leaders with distinct personalities and agendas.",
             "specialty": "diplomacy_systems", "color": "#4338CA"},
            {"id": "tech_tree_designer", "name": "Eureka", "role": "Tech Tree Architect",
             "persona": "You are Eureka, the tech tree master. You design branching research paths, eureka moments, era progression, and technology that fundamentally changes gameplay strategies.",
             "specialty": "tech_systems", "color": "#6366F1"},
        ],
    },
    {
        "id": "grand_strategy", "name": "Grand Strategy", "icon": "earth", "color": "#1E293B",
        "description": "Rule empires across centuries with politics, warfare, dynasties, and geopolitics",
        "engines": ["Unity", "Custom"],
        "complexity": "extreme",
        "subgenres": ["historical_gs", "fantasy_gs", "political_sim"],
        "core_mechanics": ["map_painting", "dynastic_politics", "warfare", "economy", "laws", "religion", "culture", "succession"],
        "reference_games": ["Crusader Kings 3", "Europa Universalis IV", "Hearts of Iron IV", "Victoria 3"],
        "art_styles": ["map_based", "portrait_driven", "minimalist"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Medieval Dynasty", "description": "CK3-style character-driven strategy", "complexity": "expert"},
            {"name": "World War", "description": "HOI4-style WWII grand strategy", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "dynasty_designer", "name": "Lineage", "role": "Dynasty & Character Designer",
             "persona": "You are Lineage, dynasty system designer. You create inheritance laws, marriage alliances, trait systems, character education, and generational storytelling through mechanics.",
             "specialty": "dynasty_systems", "color": "#1E293B"},
            {"id": "geopolitics_designer", "name": "Sovereign", "role": "Geopolitics Designer",
             "persona": "You are Sovereign, geopolitics master. You design casus belli, peace treaties, vassal management, colonization, and the complex web of international relations.",
             "specialty": "political_systems", "color": "#334155"},
        ],
    },
    {
        "id": "colony_sim", "name": "Colony Sim", "icon": "business", "color": "#059669",
        "description": "Manage colonists, resources, and survival in procedurally generated worlds",
        "engines": ["Unity", "Godot"],
        "complexity": "very_high",
        "subgenres": ["space_colony", "medieval_colony", "post_apocalyptic_colony"],
        "core_mechanics": ["colonist_management", "base_building", "resource_management", "mood_system", "research", "defense", "seasons"],
        "reference_games": ["RimWorld", "Dwarf Fortress", "Oxygen Not Included", "Going Medieval", "Frostpunk"],
        "art_styles": ["top_down", "isometric", "pixel_art", "stylized"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Space Colony", "description": "RimWorld-style storyteller colony", "complexity": "expert"},
            {"name": "Medieval Colony", "description": "Going Medieval-style survival", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "colonist_ai", "name": "Pawn", "role": "Colonist AI Designer",
             "persona": "You are Pawn, colonist AI master. You design colonist needs, skills, relationships, mental breaks, job priorities, and the emergent stories that arise from interacting systems.",
             "specialty": "ai_systems", "color": "#059669"},
            {"id": "storyteller_designer", "name": "Narrator", "role": "AI Storyteller Designer",
             "persona": "You are Narrator, the AI storyteller. You design event systems, raid scaling, random events, and dramatic pacing that creates memorable emergent narratives.",
             "specialty": "narrative_systems", "color": "#10B981"},
        ],
    },
    {
        "id": "automation", "name": "Automation / Factory", "icon": "cog", "color": "#F97316",
        "description": "Design conveyor belts, production chains, and optimize complex factory systems",
        "engines": ["Unity", "Godot"],
        "complexity": "very_high",
        "subgenres": ["factory_builder", "logistics_puzzler", "space_factory"],
        "core_mechanics": ["conveyor_belts", "production_chains", "logistics", "resource_processing", "research", "optimization", "pollution"],
        "reference_games": ["Factorio", "Satisfactory", "Dyson Sphere Program", "Shapez", "Captain of Industry"],
        "art_styles": ["isometric", "3d", "minimalist", "pixel_art"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Factory Builder", "description": "Factorio-style with enemies and research", "complexity": "expert"},
            {"name": "Logistics Puzzle", "description": "Shapez-style pure optimization", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "logistics_designer", "name": "Conveyor", "role": "Logistics System Designer",
             "persona": "You are Conveyor, logistics guru. You design belt systems, splitters, mergers, priority queues, train networks, and the satisfying flow of perfectly optimized production lines.",
             "specialty": "logistics_systems", "color": "#F97316"},
            {"id": "recipe_designer", "name": "Forge", "role": "Production Recipe Designer",
             "persona": "You are Forge, production chain designer. You create interconnected recipe trees, byproducts, multi-step processing, and resource ratios that challenge players to optimize.",
             "specialty": "production_systems", "color": "#EA580C"},
        ],
    },
    {
        "id": "survival", "name": "Survival / Crafting", "icon": "leaf", "color": "#059669",
        "description": "Gather resources, craft tools, build shelter, and survive hostile environments",
        "engines": ["Unity", "Unreal", "Godot"],
        "complexity": "high",
        "subgenres": ["survival_craft", "zombie_survival", "space_survival", "underwater_survival"],
        "core_mechanics": ["gathering", "crafting", "building", "hunger", "thirst", "combat", "exploration", "base_defense"],
        "reference_games": ["Valheim", "Subnautica", "The Forest", "Rust", "Grounded"],
        "art_styles": ["realistic", "stylized", "low_poly", "voxel"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Wilderness Survival", "description": "Forest survival with building", "complexity": "advanced"},
            {"name": "Zombie Survival", "description": "7 Days to Die-style horde survival", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "crafting_designer", "name": "Smith", "role": "Crafting System Designer",
             "persona": "You are Smith, crafting system master. You design recipe trees, workstations, material tiers, tool progression, and the satisfying loop of gather-craft-upgrade that keeps players engaged.",
             "specialty": "crafting_systems", "color": "#059669"},
            {"id": "base_builder_designer", "name": "Foundation", "role": "Base Building Designer",
             "persona": "You are Foundation, base building architect. You design snap-based building, structural integrity, decorating, lighting, and base defense systems.",
             "specialty": "building_systems", "color": "#10B981"},
            {"id": "biome_designer", "name": "Wilds", "role": "Biome & Environment Designer",
             "persona": "You are Wilds, biome designer. You create diverse biomes with unique resources, creatures, hazards, and progression gating. Each biome is a new frontier.",
             "specialty": "environment_design", "color": "#34D399"},
        ],
    },
    {
        "id": "soulslike", "name": "Soulslike", "icon": "skull", "color": "#1C1917",
        "description": "Punishing action-RPG with precise combat, stamina management, and interconnected worlds",
        "engines": ["Unreal", "Unity"],
        "complexity": "extreme",
        "subgenres": ["dark_fantasy_souls", "sci_fi_souls", "2d_souls"],
        "core_mechanics": ["stamina_combat", "dodge_roll", "bonfires", "estus", "souls_currency", "boss_fights", "shortcuts", "weapon_arts"],
        "reference_games": ["Elden Ring", "Dark Souls III", "Bloodborne", "Lies of P", "Sekiro"],
        "art_styles": ["dark_fantasy", "gothic", "cosmic_horror", "medieval"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Dark Fantasy Souls", "description": "Classic Souls with interconnected world", "complexity": "expert"},
            {"name": "2D Soulslike", "description": "Hollow Knight-style 2D souls", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "boss_designer", "name": "Colossus", "role": "Boss Fight Designer",
             "persona": "You are Colossus, boss design master. You create multi-phase boss fights with readable tells, punish windows, phase transitions, and that euphoric victory feeling. Every boss is a memorable duel.",
             "specialty": "boss_design", "color": "#1C1917"},
            {"id": "souls_combat", "name": "Parry", "role": "Souls Combat Designer",
             "persona": "You are Parry, precision combat designer. You tune i-frames, stamina costs, poise, weapon scaling, magic systems, and build variety. Every weapon must feel distinct.",
             "specialty": "combat_design", "color": "#44403C"},
            {"id": "world_interconnect", "name": "Shortcut", "role": "Interconnected World Designer",
             "persona": "You are Shortcut, world connectivity master. You design looping levels, elevator shortcuts, hidden paths, and the moment of realization when players discover the world folds back on itself.",
             "specialty": "world_design", "color": "#78716C"},
        ],
    },
    {
        "id": "metroidvania", "name": "Metroidvania", "icon": "git-network", "color": "#7C2D12",
        "description": "Interconnected 2D worlds with ability-gated exploration and backtracking",
        "engines": ["Unity", "Godot", "GameMaker"],
        "complexity": "high",
        "subgenres": ["action_metroidvania", "puzzle_metroidvania", "horror_metroidvania"],
        "core_mechanics": ["ability_gating", "backtracking", "map_exploration", "upgrades", "boss_fights", "hidden_areas", "fast_travel"],
        "reference_games": ["Hollow Knight", "Metroid Dread", "Ori and the Will of the Wisps", "Blasphemous 2", "Dead Cells"],
        "art_styles": ["hand_drawn", "pixel_art", "dark_fantasy", "watercolor"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Action Metroidvania", "description": "Hollow Knight-style with combat focus", "complexity": "advanced"},
            {"name": "Exploration MV", "description": "Metroid-style with ability focus", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "mv_map_designer", "name": "Cartographer", "role": "Metroidvania Map Architect",
             "persona": "You are Cartographer, the metroidvania map master. You design interconnected room layouts, ability gates, secret passages, and the satisfaction of opening new paths with every upgrade.",
             "specialty": "map_design", "color": "#7C2D12"},
            {"id": "ability_designer", "name": "Unlock", "role": "Ability & Upgrade Designer",
             "persona": "You are Unlock, ability progression designer. You create double jumps, wall climbs, dashes, and grapple hooks that each transform how players interact with the entire map.",
             "specialty": "ability_design", "color": "#9A3412"},
        ],
    },
    {
        "id": "roguelike", "name": "Roguelike / Roguelite", "icon": "shuffle", "color": "#475569",
        "description": "Procedural generation, permadeath, and run-based progression with endless replayability",
        "engines": ["Unity", "Godot", "Pygame"],
        "complexity": "high",
        "subgenres": ["traditional_roguelike", "action_roguelite", "deckbuilder_roguelike", "auto_battler_rl"],
        "core_mechanics": ["procedural_generation", "permadeath", "run_based", "meta_progression", "synergies", "random_items", "risk_reward"],
        "reference_games": ["Hades", "Slay the Spire", "Dead Cells", "Risk of Rain 2", "Balatro"],
        "art_styles": ["pixel_art", "stylized", "hand_drawn", "retro"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Action Roguelite", "description": "Hades-style with permanent upgrades", "complexity": "advanced"},
            {"name": "Deckbuilder Roguelike", "description": "Slay the Spire-style card runs", "complexity": "advanced"},
            {"name": "Traditional Roguelike", "description": "ASCII-style turn-based dungeon crawl", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "procgen_designer", "name": "Seed", "role": "Procedural Generation Designer",
             "persona": "You are Seed, the procedural generation master. You design dungeon generators, room templates, encounter placement, and ensure every run feels handcrafted despite being random.",
             "specialty": "procgen", "color": "#475569"},
            {"id": "synergy_designer", "name": "Combo", "role": "Synergy & Build Designer",
             "persona": "You are Combo, synergy architect. You create item interactions, skill combos, build archetypes, and those broken-feeling power spikes that make players say 'just one more run'.",
             "specialty": "synergy_design", "color": "#64748B"},
            {"id": "meta_prog_designer", "name": "Legacy", "role": "Meta-Progression Designer",
             "persona": "You are Legacy, meta-progression designer. You balance permanent upgrades, unlock paths, achievement rewards, and the 'mirror' upgrades that make failed runs feel like progress.",
             "specialty": "progression_systems", "color": "#94A3B8"},
        ],
    },
    {
        "id": "deckbuilder", "name": "Deckbuilder", "icon": "copy", "color": "#F97316",
        "description": "Collectible card strategy with deck construction, synergies, and tactical card play",
        "engines": ["Unity", "Godot", "Phaser"],
        "complexity": "high",
        "subgenres": ["ccg", "roguelike_deckbuilder", "lcg", "auto_battler"],
        "core_mechanics": ["deck_construction", "card_draw", "mana_system", "synergies", "combos", "card_rarity", "booster_packs"],
        "reference_games": ["Slay the Spire", "Hearthstone", "Magic: The Gathering Arena", "Marvel Snap", "Balatro"],
        "art_styles": ["card_art", "stylized", "fantasy", "anime"],
        "target_platforms": ["pc", "mobile", "web"],
        "templates": [
            {"name": "CCG", "description": "Hearthstone-style competitive card game", "complexity": "advanced"},
            {"name": "Roguelike Deckbuilder", "description": "StS-style run-based card game", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "card_designer", "name": "Dealer", "role": "Card Design Specialist",
             "persona": "You are Dealer, card design master. You create card mechanics, keywords, rarities, and ensure every card has clear purpose and synergy potential. No dead cards in your sets.",
             "specialty": "card_design", "color": "#F97316"},
            {"id": "meta_balancer", "name": "Meta", "role": "Metagame Balancer",
             "persona": "You are Meta, the metagame balancer. You monitor win rates, craft nerfs and buffs, design counter-strategies, and ensure a healthy, diverse competitive metagame.",
             "specialty": "balance", "color": "#EA580C"},
        ],
    },
    {
        "id": "fighting", "name": "Fighting Game", "icon": "flash", "color": "#DC2626",
        "description": "Competitive 1v1 combat with combos, frame data, and deep mechanical mastery",
        "engines": ["Unity", "Godot", "Unreal"],
        "complexity": "very_high",
        "subgenres": ["2d_fighter", "3d_fighter", "platform_fighter", "anime_fighter", "arena_fighter"],
        "core_mechanics": ["combos", "special_moves", "blocking", "meters", "frame_data", "footsies", "mixups", "wake_up"],
        "reference_games": ["Street Fighter 6", "Tekken 8", "Guilty Gear Strive", "Smash Bros Ultimate", "Mortal Kombat 1"],
        "art_styles": ["anime", "realistic", "stylized", "comic_book"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "2D Fighter", "description": "SF6-style with drive system", "complexity": "expert"},
            {"name": "Platform Fighter", "description": "Smash-style with percentages", "complexity": "advanced"},
            {"name": "3D Fighter", "description": "Tekken-style with sidestepping", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "frame_data_designer", "name": "Frame", "role": "Frame Data Designer",
             "persona": "You are Frame, the frame data architect. You design startup frames, recovery frames, hit advantage, blockstun, and the mathematical backbone that competitive fighters master.",
             "specialty": "frame_systems", "color": "#DC2626"},
            {"id": "character_designer_fg", "name": "Archetype", "role": "Fighter Character Designer",
             "persona": "You are Archetype, fighting game character designer. You create rushdown, zoner, grappler, and hybrid archetypes with unique movesets, command inputs, and playstyle identity.",
             "specialty": "character_design", "color": "#EF4444"},
            {"id": "rollback_engineer", "name": "Rollback", "role": "Rollback Netcode Engineer",
             "persona": "You are Rollback, netcode engineer. You implement rollback netcode, GGPO integration, input delay settings, and ensure silky-smooth online matches even across continents.",
             "specialty": "networking", "color": "#B91C1C"},
        ],
    },
    {
        "id": "racing", "name": "Racing Game", "icon": "speedometer", "color": "#06B6D4",
        "description": "High-speed vehicle racing with physics, tracks, and competitive multiplayer",
        "engines": ["Unity", "Unreal", "Godot"],
        "complexity": "high",
        "subgenres": ["arcade_racing", "sim_racing", "kart_racing", "street_racing", "off_road"],
        "core_mechanics": ["acceleration", "braking", "drifting", "boost", "vehicle_physics", "track_design", "leaderboards"],
        "reference_games": ["Forza Horizon 5", "Gran Turismo 7", "Mario Kart 8", "Need for Speed Unbound", "Art of Rally"],
        "art_styles": ["realistic", "stylized", "cartoon", "retro"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Arcade Racer", "description": "NFS-style with nitro and drifting", "complexity": "intermediate"},
            {"name": "Sim Racer", "description": "GT-style with realistic physics", "complexity": "expert"},
            {"name": "Kart Racer", "description": "Mario Kart-style with items", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "vehicle_physics", "name": "Torque", "role": "Vehicle Physics Engineer",
             "persona": "You are Torque, vehicle physics master. You tune suspension, tire grip, weight transfer, downforce, and gear ratios. Your cars feel real whether arcade or simulation.",
             "specialty": "physics", "color": "#06B6D4"},
            {"id": "track_designer", "name": "Circuit", "role": "Track & Course Designer",
             "persona": "You are Circuit, track designer. You create flowing track layouts, elevation changes, chicanes, hairpins, and scenic vistas that make every lap exciting.",
             "specialty": "track_design", "color": "#0891B2"},
        ],
    },
    {
        "id": "horror", "name": "Horror", "icon": "moon", "color": "#1E1B4B",
        "description": "Atmospheric terror with psychological horror, survival tension, and fear mechanics",
        "engines": ["Unreal", "Unity", "Godot"],
        "complexity": "high",
        "subgenres": ["survival_horror", "psychological_horror", "action_horror", "cosmic_horror", "found_footage"],
        "core_mechanics": ["tension", "limited_resources", "darkness", "sound_design", "jump_scares", "sanity", "stealth", "investigation"],
        "reference_games": ["Resident Evil Village", "Silent Hill 2 Remake", "Amnesia", "Phasmophobia", "Alan Wake 2"],
        "art_styles": ["photorealistic", "ps1_retro", "cel_shaded_horror", "found_footage"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Survival Horror", "description": "RE-style with item management", "complexity": "advanced"},
            {"name": "Psychological Horror", "description": "Silent Hill-style mind games", "complexity": "advanced"},
            {"name": "Found Footage", "description": "Camera-based horror exploration", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "fear_designer", "name": "Dread", "role": "Fear & Tension Designer",
             "persona": "You are Dread, the fear architect. You design tension curves, jumpscare timing, audio stingers, safe room pacing, and the delicate art of making players too scared to open the next door.",
             "specialty": "fear_design", "color": "#1E1B4B"},
            {"id": "monster_designer", "name": "Aberration", "role": "Monster & Enemy Designer",
             "persona": "You are Aberration, monster designer. You create terrifying enemy AI with patrol patterns, detection mechanics, chase sequences, and designs that haunt players' nightmares.",
             "specialty": "enemy_design", "color": "#312E81"},
            {"id": "atmosphere_designer", "name": "Fog", "role": "Atmosphere & Lighting Designer",
             "persona": "You are Fog, atmosphere master. You design lighting, fog volumes, particle effects, dynamic shadows, and environmental storytelling that creates dread without a single enemy.",
             "specialty": "atmosphere", "color": "#3730A3"},
        ],
    },
    {
        "id": "stealth", "name": "Stealth Game", "icon": "eye-off", "color": "#334155",
        "description": "Infiltration, espionage, and tactical stealth with detection and evasion mechanics",
        "engines": ["Unreal", "Unity"],
        "complexity": "very_high",
        "subgenres": ["immersive_sim", "tactical_stealth", "social_stealth", "stealth_action"],
        "core_mechanics": ["detection_meter", "noise_system", "line_of_sight", "disguises", "distractions", "takedowns", "hiding_spots"],
        "reference_games": ["Hitman 3", "Metal Gear Solid V", "Dishonored 2", "Thief", "Splinter Cell"],
        "art_styles": ["realistic", "noir", "stylized", "cyberpunk"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Sandbox Stealth", "description": "Hitman-style with creative solutions", "complexity": "expert"},
            {"name": "Stealth Action", "description": "MGS-style with stealth and combat", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "ai_guard_designer", "name": "Patrol", "role": "Guard AI Designer",
             "persona": "You are Patrol, guard AI specialist. You design patrol routes, alert states, investigation behavior, communication between guards, and the satisfaction of outsmarting smart enemies.",
             "specialty": "ai_design", "color": "#334155"},
            {"id": "stealth_systems", "name": "Shadow", "role": "Stealth Mechanics Designer",
             "persona": "You are Shadow, stealth systems designer. You create light/dark detection, noise propagation, alert levels, last known position tracking, and the toolkit of stealth abilities.",
             "specialty": "stealth_systems", "color": "#475569"},
        ],
    },
    {
        "id": "simulation", "name": "Life Simulation", "icon": "home", "color": "#0EA5E9",
        "description": "Virtual life, relationships, home building, and daily activity simulation",
        "engines": ["Unity", "Godot", "Unreal"],
        "complexity": "high",
        "subgenres": ["life_sim", "dating_sim", "pet_sim", "god_game"],
        "core_mechanics": ["needs_management", "relationships", "customization", "scheduling", "career", "home_building"],
        "reference_games": ["The Sims 4", "Animal Crossing", "Stardew Valley", "Tomodachi Life", "Palia"],
        "art_styles": ["cartoon", "stylized", "anime", "chibi"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Life Sim", "description": "Sims-style with needs and careers", "complexity": "advanced"},
            {"name": "Cozy Farm", "description": "Stardew-style farming and community", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "social_sim_designer", "name": "Bond", "role": "Social Simulation Designer",
             "persona": "You are Bond, social simulation master. You design relationship systems, friendship/romance meters, NPC schedules, personality traits, and meaningful social interactions.",
             "specialty": "social_systems", "color": "#0EA5E9"},
            {"id": "home_builder_designer", "name": "Decor", "role": "Home Building Designer",
             "persona": "You are Decor, home building specialist. You design room editors, furniture placement, wall/floor customization, and the creative expression tools players love.",
             "specialty": "building_systems", "color": "#38BDF8"},
        ],
    },
    {
        "id": "city_builder", "name": "City Builder", "icon": "business", "color": "#0369A1",
        "description": "Urban planning, infrastructure, and city management simulation",
        "engines": ["Unity", "Unreal"],
        "complexity": "very_high",
        "subgenres": ["modern_city", "historical_city", "space_colony_builder", "post_apocalyptic_city"],
        "core_mechanics": ["zoning", "road_building", "utilities", "economy", "citizen_happiness", "traffic", "pollution", "education"],
        "reference_games": ["Cities Skylines 2", "SimCity", "Frostpunk", "Anno 1800", "Tropico 6"],
        "art_styles": ["realistic", "stylized", "isometric", "voxel"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Modern City", "description": "Cities Skylines-style urban management", "complexity": "expert"},
            {"name": "Survival City", "description": "Frostpunk-style with hard choices", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "traffic_designer", "name": "Flow", "role": "Traffic & Infrastructure Designer",
             "persona": "You are Flow, traffic system designer. You create road networks, public transit, traffic simulation, roundabouts, and the satisfying optimization of city infrastructure.",
             "specialty": "traffic_systems", "color": "#0369A1"},
            {"id": "economy_sim_designer", "name": "Treasury", "role": "City Economy Designer",
             "persona": "You are Treasury, city economy designer. You balance taxes, services, commercial zones, industrial output, and the delicate budget that keeps cities thriving.",
             "specialty": "economy_systems", "color": "#0284C7"},
        ],
    },
    {
        "id": "farming_sim", "name": "Farming Sim", "icon": "leaf", "color": "#15803D",
        "description": "Plant crops, raise animals, build your farm, and become part of a charming community",
        "engines": ["Unity", "Godot"],
        "complexity": "medium",
        "subgenres": ["classic_farm", "fantasy_farm", "space_farm", "cozy_farm"],
        "core_mechanics": ["planting", "harvesting", "animal_care", "seasons", "relationships", "fishing", "mining", "cooking"],
        "reference_games": ["Stardew Valley", "Story of Seasons", "Coral Island", "Roots of Pacha", "Harvestella"],
        "art_styles": ["pixel_art", "anime", "watercolor", "chibi"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Classic Farm", "description": "Stardew-style with seasons and romance", "complexity": "intermediate"},
            {"name": "Fantasy Farm", "description": "Farm with magic creatures and spells", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "crop_designer", "name": "Harvest", "role": "Crop & Season Designer",
             "persona": "You are Harvest, crop system designer. You design seasonal crop calendars, growth stages, quality tiers, fertilizer effects, and the satisfying rhythm of farm life.",
             "specialty": "farming_systems", "color": "#15803D"},
            {"id": "community_designer", "name": "Village", "role": "Town & NPC Designer",
             "persona": "You are Village, community designer. You create charming NPCs with schedules, gift preferences, heart events, festivals, and the warm feeling of belonging to a small town.",
             "specialty": "social_design", "color": "#22C55E"},
        ],
    },
    {
        "id": "sandbox", "name": "Sandbox / Open World", "icon": "globe", "color": "#14B8A6",
        "description": "Open-ended exploration, creativity, and emergent gameplay in vast worlds",
        "engines": ["Unreal", "Unity"],
        "complexity": "extreme",
        "subgenres": ["creative_sandbox", "survival_sandbox", "physics_sandbox"],
        "core_mechanics": ["exploration", "building", "voxel_terrain", "multiplayer", "modding", "procedural_world"],
        "reference_games": ["Minecraft", "Terraria", "No Man's Sky", "Garry's Mod", "Roblox"],
        "art_styles": ["voxel", "stylized", "low_poly", "procedural"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Voxel Sandbox", "description": "Minecraft-style with infinite worlds", "complexity": "expert"},
            {"name": "Physics Sandbox", "description": "Garry's Mod-style experimentation", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "voxel_engineer", "name": "Block", "role": "Voxel Engine Engineer",
             "persona": "You are Block, voxel engine specialist. You design chunk loading, meshing algorithms, infinite terrain, biome generation, and the creative tools that let players build anything.",
             "specialty": "voxel_systems", "color": "#14B8A6"},
            {"id": "modding_designer", "name": "Mod", "role": "Modding API Designer",
             "persona": "You are Mod, modding system designer. You create scripting APIs, asset pipelines, Steam Workshop integration, and the tools that let communities extend the game infinitely.",
             "specialty": "modding_systems", "color": "#2DD4BF"},
        ],
    },
    {
        "id": "visual_novel", "name": "Visual Novel", "icon": "book", "color": "#EC4899",
        "description": "Story-driven interactive fiction with branching narratives and character relationships",
        "engines": ["Ren'Py", "Unity", "Godot"],
        "complexity": "low",
        "subgenres": ["romance_vn", "mystery_vn", "horror_vn", "otome", "kinetic_novel"],
        "core_mechanics": ["branching_dialogue", "choices", "character_routes", "save_system", "gallery", "affection_tracking"],
        "reference_games": ["Doki Doki Literature Club", "Steins;Gate", "Ace Attorney", "Danganronpa", "VA-11 Hall-A"],
        "art_styles": ["anime", "realistic_portraits", "chibi", "painterly"],
        "target_platforms": ["pc", "mobile", "console"],
        "templates": [
            {"name": "Romance VN", "description": "Dating sim with multiple routes", "complexity": "beginner"},
            {"name": "Mystery VN", "description": "Ace Attorney-style investigation", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "vn_writer", "name": "Author", "role": "Visual Novel Writer",
             "persona": "You are Author, visual novel writer. You craft compelling dialogue, branching paths, multiple endings, character voice consistency, and emotional beats that make players cry.",
             "specialty": "narrative_writing", "color": "#EC4899"},
            {"id": "vn_character_artist", "name": "Portrait", "role": "Character Portrait Designer",
             "persona": "You are Portrait, character expression designer. You create emotion sprites, CG scene compositions, UI design, and the visual language that brings VN characters to life.",
             "specialty": "character_art", "color": "#F472B6"},
        ],
    },
    {
        "id": "rhythm", "name": "Rhythm Game", "icon": "musical-notes", "color": "#D946EF",
        "description": "Music-synchronized gameplay with timing, combos, and audio-visual spectacle",
        "engines": ["Unity", "Godot"],
        "complexity": "medium",
        "subgenres": ["note_highway", "taiko_style", "dance", "music_creation"],
        "core_mechanics": ["timing", "note_patterns", "scoring", "combos", "difficulty_levels", "beatmapping", "music_sync"],
        "reference_games": ["Beat Saber", "Guitar Hero", "Osu!", "Hi-Fi Rush", "Rhythm Heaven"],
        "art_styles": ["neon", "abstract", "anime", "retro"],
        "target_platforms": ["pc", "console", "mobile", "vr"],
        "templates": [
            {"name": "Note Highway", "description": "Guitar Hero-style scrolling notes", "complexity": "intermediate"},
            {"name": "Action Rhythm", "description": "Hi-Fi Rush-style rhythm combat", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "beatmap_designer", "name": "Tempo", "role": "Beatmap & Chart Designer",
             "persona": "You are Tempo, beatmap designer. You create note patterns, difficulty curves, BPM detection, audio sync precision, and charts that feel like playing the music.",
             "specialty": "beatmapping", "color": "#D946EF"},
            {"id": "audio_sync_engineer", "name": "Sync", "role": "Audio Sync Engineer",
             "persona": "You are Sync, audio synchronization specialist. You handle audio latency calibration, offset compensation, visual sync, and the millisecond-perfect timing that rhythm games demand.",
             "specialty": "audio_engineering", "color": "#E879F9"},
        ],
    },
    {
        "id": "tower_defense", "name": "Tower Defense", "icon": "construct", "color": "#7C3AED",
        "description": "Strategic tower placement to defend against waves of enemies on fixed paths",
        "engines": ["Unity", "Godot", "Phaser"],
        "complexity": "medium",
        "subgenres": ["classic_td", "hero_td", "rts_td_hybrid"],
        "core_mechanics": ["tower_placement", "waves", "upgrades", "paths", "targeting_priority", "special_abilities", "economy"],
        "reference_games": ["Bloons TD 6", "Kingdom Rush", "Plants vs Zombies", "Dungeon Defenders", "Arknights"],
        "art_styles": ["cartoon", "stylized", "pixel_art", "fantasy"],
        "target_platforms": ["pc", "mobile", "web"],
        "templates": [
            {"name": "Classic TD", "description": "Bloons-style with tower variety", "complexity": "beginner"},
            {"name": "Hero TD", "description": "Kingdom Rush-style with hero unit", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "td_balance", "name": "Turret", "role": "Tower Balance Designer",
             "persona": "You are Turret, tower balance master. You design tower DPS, range, fire rate, upgrade trees, and ensure every tower has a unique strategic role worth building.",
             "specialty": "balance", "color": "#7C3AED"},
            {"id": "wave_designer", "name": "Swarm", "role": "Wave & Enemy Designer",
             "persona": "You are Swarm, wave designer. You create enemy types, wave compositions, difficulty curves, boss waves, and the satisfying challenge of barely surviving each wave.",
             "specialty": "wave_design", "color": "#8B5CF6"},
        ],
    },
    {
        "id": "sports", "name": "Sports Game", "icon": "football", "color": "#16A34A",
        "description": "Real-world sports simulation with teams, seasons, and competitive play",
        "engines": ["Unity", "Unreal"],
        "complexity": "high",
        "subgenres": ["soccer", "basketball", "baseball", "american_football", "golf", "tennis", "extreme_sports"],
        "core_mechanics": ["physics_ball", "player_control", "team_management", "season_mode", "multiplayer", "commentary"],
        "reference_games": ["FIFA/EA FC", "NBA 2K", "MLB The Show", "Rocket League", "Tony Hawk's"],
        "art_styles": ["realistic", "stylized", "arcade"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Arcade Sports", "description": "Rocket League-style arcade sport", "complexity": "intermediate"},
            {"name": "Sim Sports", "description": "FIFA-style realistic simulation", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "sports_physics", "name": "Ball", "role": "Sports Physics Designer",
             "persona": "You are Ball, sports physics specialist. You tune ball trajectories, player momentum, collision detection, and the precise physics that make sports games feel authentic.",
             "specialty": "physics", "color": "#16A34A"},
            {"id": "commentary_designer", "name": "Announcer", "role": "Commentary & Presentation",
             "persona": "You are Announcer, commentary system designer. You create dynamic commentary, replay cameras, crowd reactions, and broadcast-quality presentation.",
             "specialty": "presentation", "color": "#22C55E"},
        ],
    },
    {
        "id": "extraction_shooter", "name": "Extraction Shooter", "icon": "exit", "color": "#92400E",
        "description": "High-stakes raids where death means losing everything you brought and found",
        "engines": ["Unreal", "Unity"],
        "complexity": "extreme",
        "subgenres": ["tactical_extraction", "fantasy_extraction", "horror_extraction"],
        "core_mechanics": ["extraction_points", "loot_risk", "insurance", "hideout", "flea_market", "healing_system", "ammo_types", "armor_pen"],
        "reference_games": ["Escape from Tarkov", "Hunt: Showdown", "Dark and Darker", "The Cycle", "DMZ"],
        "art_styles": ["realistic", "mil_sim", "dark_fantasy"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Tactical Extraction", "description": "Tarkov-style with realistic ballistics", "complexity": "expert"},
            {"name": "Fantasy Extraction", "description": "Dark and Darker-style dungeon raids", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "extraction_economy", "name": "Stash", "role": "Extraction Economy Designer",
             "persona": "You are Stash, extraction economy master. You design insurance, flea market pricing, gear fear balance, risk vs reward curves, and the adrenaline of extracting with precious loot.",
             "specialty": "economy_design", "color": "#92400E"},
            {"id": "ballistics_designer", "name": "Caliber", "role": "Ballistics & Armor Designer",
             "persona": "You are Caliber, ballistics expert. You design ammo penetration values, armor classes, fragmentation chance, blunt damage, and the hardcore shooting model.",
             "specialty": "ballistics", "color": "#A16207"},
        ],
    },
    {
        "id": "social_deduction", "name": "Social Deduction", "icon": "help-circle", "color": "#E11D48",
        "description": "Deception, trust, and social manipulation in multiplayer party games",
        "engines": ["Unity", "Godot", "Phaser"],
        "complexity": "medium",
        "subgenres": ["impostor", "werewolf", "hidden_role", "murder_mystery"],
        "core_mechanics": ["hidden_roles", "voting", "discussion", "tasks", "sabotage", "evidence", "accusation"],
        "reference_games": ["Among Us", "Town of Salem", "Project Winter", "Goose Goose Duck", "Werewolf"],
        "art_styles": ["cartoon", "stylized", "minimalist"],
        "target_platforms": ["pc", "mobile", "web"],
        "templates": [
            {"name": "Impostor Game", "description": "Among Us-style with tasks and sabotage", "complexity": "intermediate"},
            {"name": "Murder Mystery", "description": "Clue-style investigation party game", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "deception_designer", "name": "Bluff", "role": "Deception Mechanics Designer",
             "persona": "You are Bluff, deception mechanics master. You design role distributions, information asymmetry, evidence planting, and the social dynamics that create paranoia and excitement.",
             "specialty": "social_mechanics", "color": "#E11D48"},
        ],
    },
    {
        "id": "idle_clicker", "name": "Idle / Clicker", "icon": "trending-up", "color": "#CA8A04",
        "description": "Incremental progression with exponential numbers, prestige, and idle gains",
        "engines": ["Unity", "Godot", "Phaser", "React"],
        "complexity": "medium",
        "subgenres": ["clicker", "idle_rpg", "incremental", "management_idle"],
        "core_mechanics": ["clicking", "automation", "prestige", "exponential_growth", "offline_progress", "upgrades", "achievements"],
        "reference_games": ["Cookie Clicker", "Clicker Heroes", "Melvor Idle", "NGU Idle", "Realm Grinder"],
        "art_styles": ["minimalist", "cartoon", "pixel_art", "ui_focused"],
        "target_platforms": ["pc", "mobile", "web"],
        "templates": [
            {"name": "Classic Clicker", "description": "Cookie Clicker-style with prestige", "complexity": "beginner"},
            {"name": "Idle RPG", "description": "Auto-battler with idle progression", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "idle_math", "name": "Exponential", "role": "Idle Math & Scaling Designer",
             "persona": "You are Exponential, idle math specialist. You design prestige formulas, big number scaling, diminishing returns, optimal resets, and the mathematical hooks that keep players resetting.",
             "specialty": "math_design", "color": "#CA8A04"},
        ],
    },
    {
        "id": "gacha", "name": "Gacha / Live Service", "icon": "diamond", "color": "#9333EA",
        "description": "Character collection, banners, pity systems, and live-service content",
        "engines": ["Unity", "Unreal"],
        "complexity": "very_high",
        "subgenres": ["gacha_rpg", "gacha_action", "gacha_strategy"],
        "core_mechanics": ["banner_system", "pity_system", "daily_login", "events", "guilds", "pvp", "character_collection", "stamina"],
        "reference_games": ["Genshin Impact", "Honkai Star Rail", "Arknights", "Blue Archive", "Fate/Grand Order"],
        "art_styles": ["anime", "stylized", "chibi"],
        "target_platforms": ["mobile", "pc"],
        "templates": [
            {"name": "Gacha RPG", "description": "Genshin-style open world gacha", "complexity": "expert"},
            {"name": "Gacha Strategy", "description": "Arknights-style tactical gacha", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "gacha_economy", "name": "Banner", "role": "Gacha Economy Designer",
             "persona": "You are Banner, gacha economy designer. You create pity systems, banner rotations, currency balance, spark mechanics, and ethical monetization that respects players while generating revenue.",
             "specialty": "monetization", "color": "#9333EA"},
            {"id": "live_ops_designer", "name": "Season", "role": "Live Ops & Events Designer",
             "persona": "You are Season, live ops master. You design battle passes, seasonal events, limited-time content, collaboration events, and the content calendar that keeps players engaged year-round.",
             "specialty": "live_ops", "color": "#A855F7"},
        ],
    },
    {
        "id": "space_sim", "name": "Space Simulation", "icon": "rocket", "color": "#1E40AF",
        "description": "Space exploration, ship combat, trading, and interstellar adventure",
        "engines": ["Unreal", "Unity", "Custom"],
        "complexity": "extreme",
        "subgenres": ["space_combat", "space_trading", "space_exploration", "space_sandbox"],
        "core_mechanics": ["ship_control", "space_combat", "trading", "exploration", "ship_customization", "warp_travel", "scanning"],
        "reference_games": ["Elite Dangerous", "Star Citizen", "No Man's Sky", "Eve Online", "Kerbal Space Program"],
        "art_styles": ["realistic", "stylized", "retro_sci_fi"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Space Explorer", "description": "NMS-style procedural space exploration", "complexity": "expert"},
            {"name": "Space Trader", "description": "Elite-style trading and combat", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "orbital_designer", "name": "Orbit", "role": "Orbital Mechanics Designer",
             "persona": "You are Orbit, space physics designer. You create Newtonian flight, orbital mechanics, gravity assists, warp systems, and the awe of space navigation.",
             "specialty": "space_physics", "color": "#1E40AF"},
            {"id": "ship_designer", "name": "Hull", "role": "Ship Design & Customization",
             "persona": "You are Hull, ship designer. You create modular ship building, hardpoint systems, power management, shield configurations, and the identity of each spacecraft.",
             "specialty": "ship_design", "color": "#2563EB"},
        ],
    },
    {
        "id": "flight_sim", "name": "Flight Simulation", "icon": "airplane", "color": "#0284C7",
        "description": "Realistic aircraft simulation with authentic cockpits and flight physics",
        "engines": ["Unreal", "Unity", "Custom"],
        "complexity": "extreme",
        "subgenres": ["civilian_flight", "combat_flight", "helicopter_sim"],
        "core_mechanics": ["flight_physics", "cockpit_instruments", "navigation", "weather", "atc_communication", "landing"],
        "reference_games": ["Microsoft Flight Simulator", "DCS World", "IL-2 Sturmovik", "X-Plane"],
        "art_styles": ["photorealistic", "stylized"],
        "target_platforms": ["pc"],
        "templates": [
            {"name": "Civilian Flight", "description": "MSFS-style world exploration", "complexity": "expert"},
            {"name": "Combat Flight", "description": "DCS-style military aviation", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "aerodynamics_designer", "name": "Aileron", "role": "Aerodynamics Engineer",
             "persona": "You are Aileron, aerodynamics specialist. You model lift, drag, stall behavior, control surfaces, and the authentic flight model that satisfies real pilots.",
             "specialty": "flight_physics", "color": "#0284C7"},
        ],
    },
    {
        "id": "naval_pirate", "name": "Naval / Pirate", "icon": "boat", "color": "#0E7490",
        "description": "Sail the seas with ship combat, exploration, crew management, and piracy",
        "engines": ["Unreal", "Unity"],
        "complexity": "very_high",
        "subgenres": ["pirate_adventure", "naval_warfare", "sailing_sim"],
        "core_mechanics": ["sailing", "ship_combat", "crew_management", "trading", "exploration", "boarding", "treasure_hunting"],
        "reference_games": ["Sea of Thieves", "Skull and Bones", "Assassin's Creed Black Flag", "Sid Meier's Pirates"],
        "art_styles": ["stylized", "realistic", "cartoon"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Pirate Adventure", "description": "Sea of Thieves-style co-op piracy", "complexity": "advanced"},
            {"name": "Naval Warfare", "description": "Historical naval battles", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "ocean_designer", "name": "Tide", "role": "Ocean & Water Physics Designer",
             "persona": "You are Tide, ocean physics designer. You create wave simulation, buoyancy, wind effects on sails, ship rocking, and the beautiful, terrifying power of the sea.",
             "specialty": "water_physics", "color": "#0E7490"},
            {"id": "ship_combat_designer", "name": "Broadside", "role": "Naval Combat Designer",
             "persona": "You are Broadside, naval combat master. You design cannon aiming, ship damage models, boarding combat, fleet formations, and the thunderous clash of wooden warships.",
             "specialty": "combat_design", "color": "#155E75"},
        ],
    },
    {
        "id": "party_game", "name": "Party Game", "icon": "happy", "color": "#F43F5E",
        "description": "Casual multiplayer fun with mini-games, chaos, and social entertainment",
        "engines": ["Unity", "Godot"],
        "complexity": "low",
        "subgenres": ["minigame_collection", "trivia", "physics_party", "board_game_digital"],
        "core_mechanics": ["mini_games", "scoring", "turn_rotation", "randomness", "handicaps", "local_multiplayer"],
        "reference_games": ["Mario Party", "Fall Guys", "Jackbox", "Pummel Party", "Gang Beasts"],
        "art_styles": ["cartoon", "goofy", "minimalist", "colorful"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Mini-Game Party", "description": "Mario Party-style board + minigames", "complexity": "intermediate"},
            {"name": "Physics Party", "description": "Gang Beasts-style physics chaos", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "minigame_designer", "name": "Fun", "role": "Mini-Game Designer",
             "persona": "You are Fun, mini-game designer. You create quick, intuitive, hilarious mini-games that anyone can play within seconds of seeing the rules. Joy is your metric.",
             "specialty": "minigame_design", "color": "#F43F5E"},
        ],
    },
    {
        "id": "educational", "name": "Educational Game", "icon": "school", "color": "#2563EB",
        "description": "Learning through play with adaptive difficulty and educational standards",
        "engines": ["Unity", "Godot", "Phaser"],
        "complexity": "medium",
        "subgenres": ["math_game", "language_game", "science_game", "coding_game", "history_game"],
        "core_mechanics": ["adaptive_difficulty", "progress_tracking", "rewards", "quizzes", "interactive_lessons", "gamification"],
        "reference_games": ["Duolingo", "Kerbal Space Program", "Human Resource Machine", "Civilization (educational)", "CodeCombat"],
        "art_styles": ["colorful", "cartoon", "minimalist", "friendly"],
        "target_platforms": ["pc", "mobile", "web"],
        "templates": [
            {"name": "Math Adventure", "description": "Math learning with game progression", "complexity": "beginner"},
            {"name": "Coding Game", "description": "Learn programming through puzzles", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "learning_designer", "name": "Teach", "role": "Learning Design Specialist",
             "persona": "You are Teach, learning design expert. You align gameplay with educational standards, design adaptive difficulty, measure learning outcomes, and make education genuinely fun.",
             "specialty": "learning_design", "color": "#2563EB"},
        ],
    },
    {
        "id": "cozy_game", "name": "Cozy Game", "icon": "heart", "color": "#FB923C",
        "description": "Relaxing, stress-free experiences with gentle mechanics and warm aesthetics",
        "engines": ["Unity", "Godot"],
        "complexity": "low",
        "subgenres": ["cozy_craft", "cozy_explore", "cozy_management", "cozy_puzzle"],
        "core_mechanics": ["no_fail_state", "collection", "decoration", "gentle_progression", "relaxation", "customization"],
        "reference_games": ["Unpacking", "A Short Hike", "Spiritfarer", "Cozy Grove", "Lil Gator Game"],
        "art_styles": ["watercolor", "pastel", "chibi", "hand_drawn"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Cozy Explorer", "description": "A Short Hike-style gentle exploration", "complexity": "beginner"},
            {"name": "Cozy Decorator", "description": "Unpacking-style satisfying organization", "complexity": "beginner"},
        ],
        "specialists": [
            {"id": "cozy_designer", "name": "Warm", "role": "Cozy Experience Designer",
             "persona": "You are Warm, cozy game specialist. You design gentle mechanics, calming progression, no-stress gameplay, and the warm fuzzy feeling that makes players smile.",
             "specialty": "cozy_design", "color": "#FB923C"},
        ],
    },
    {
        "id": "hunting", "name": "Hunting Game", "icon": "leaf", "color": "#4D7C0F",
        "description": "Realistic or arcade hunting with animal AI, tracking, and wilderness immersion",
        "engines": ["Unreal", "Unity"],
        "complexity": "high",
        "subgenres": ["realistic_hunting", "arcade_hunting", "monster_hunting"],
        "core_mechanics": ["tracking", "animal_ai", "weapon_selection", "scent_wind", "patience", "trophy_system"],
        "reference_games": ["theHunter: Call of the Wild", "Monster Hunter World", "Cabela's", "Way of the Hunter"],
        "art_styles": ["photorealistic", "stylized", "anime"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Realistic Hunt", "description": "theHunter-style simulation", "complexity": "advanced"},
            {"name": "Monster Hunter", "description": "MH-style action hunting RPG", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "animal_ai_designer", "name": "Tracker", "role": "Animal AI & Behavior Designer",
             "persona": "You are Tracker, animal AI specialist. You create realistic animal behaviors, migration patterns, fear responses, herd dynamics, and the patient art of the hunt.",
             "specialty": "animal_ai", "color": "#4D7C0F"},
        ],
    },
    {
        "id": "fishing", "name": "Fishing Game", "icon": "water", "color": "#0891B2",
        "description": "Relaxing or competitive fishing with rod mechanics, fish species, and aquatic worlds",
        "engines": ["Unity", "Godot"],
        "complexity": "low",
        "subgenres": ["relaxing_fishing", "competitive_fishing", "fishing_rpg"],
        "core_mechanics": ["casting", "reeling", "fish_ai", "bait_selection", "rod_tension", "fish_encyclopedia"],
        "reference_games": ["Fishing Planet", "Dave the Diver", "Moonglow Bay", "Dredge"],
        "art_styles": ["stylized", "realistic", "pixel_art", "cartoon"],
        "target_platforms": ["pc", "mobile", "console"],
        "templates": [
            {"name": "Cozy Fishing", "description": "Relaxing lakeside fishing", "complexity": "beginner"},
            {"name": "Fishing RPG", "description": "Dave the Diver-style with progression", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "fish_designer", "name": "Angler", "role": "Fish & Aquatic Designer",
             "persona": "You are Angler, aquatic specialist. You design fish species, habitats, behavior patterns, rarity tiers, and the satisfying tug of a big catch.",
             "specialty": "aquatic_design", "color": "#0891B2"},
        ],
    },
    {
        "id": "mech_robot", "name": "Mech / Robot Combat", "icon": "hardware-chip", "color": "#4B5563",
        "description": "Pilot massive mechs in combat with customization, loadouts, and warfare",
        "engines": ["Unreal", "Unity"],
        "complexity": "very_high",
        "subgenres": ["mech_action", "mech_sim", "mech_strategy"],
        "core_mechanics": ["mech_customization", "loadouts", "heat_management", "boost_system", "weapon_systems", "part_damage"],
        "reference_games": ["Armored Core VI", "MechWarrior 5", "Titanfall 2", "Front Mission", "Gundam Breaker"],
        "art_styles": ["realistic_mech", "anime_mech", "sci_fi"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Mech Action", "description": "Armored Core-style fast mech combat", "complexity": "expert"},
            {"name": "Mech Sim", "description": "MechWarrior-style heavy simulation", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "mech_designer", "name": "Chassis", "role": "Mech Design & Customization",
             "persona": "You are Chassis, mech design master. You create modular mech parts, weight/speed tradeoffs, weapon hardpoints, energy management, and the fantasy of piloting a war machine.",
             "specialty": "mech_design", "color": "#4B5563"},
        ],
    },
    {
        "id": "bullet_hell", "name": "Bullet Hell / Shmup", "icon": "flash", "color": "#BE123C",
        "description": "Intense scrolling shooters with elaborate bullet patterns and dodging mastery",
        "engines": ["Unity", "Godot", "Pygame"],
        "complexity": "medium",
        "subgenres": ["vertical_shmup", "horizontal_shmup", "twin_stick", "bullet_heaven"],
        "core_mechanics": ["bullet_patterns", "hitbox", "scoring", "bombs", "power_ups", "graze_system", "boss_battles"],
        "reference_games": ["Touhou", "Ikaruga", "Gradius", "Enter the Gungeon", "Vampire Survivors"],
        "art_styles": ["pixel_art", "anime", "neon", "retro"],
        "target_platforms": ["pc", "console", "mobile"],
        "templates": [
            {"name": "Classic Shmup", "description": "Vertical scrolling with patterns", "complexity": "intermediate"},
            {"name": "Bullet Heaven", "description": "Vampire Survivors-style horde shooter", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "pattern_designer", "name": "Danmaku", "role": "Bullet Pattern Designer",
             "persona": "You are Danmaku, bullet pattern artist. You choreograph beautiful, deadly bullet patterns that are visually stunning and precisely dodgeable. Bullet hell is your art form.",
             "specialty": "pattern_design", "color": "#BE123C"},
        ],
    },
    {
        "id": "walking_sim", "name": "Walking Simulator", "icon": "walk", "color": "#6D28D9",
        "description": "Narrative exploration focused on story, atmosphere, and environmental discovery",
        "engines": ["Unreal", "Unity", "Godot"],
        "complexity": "medium",
        "subgenres": ["narrative_explore", "environmental_storytelling", "photographic"],
        "core_mechanics": ["exploration", "environmental_storytelling", "voice_acting", "collectible_notes", "atmosphere"],
        "reference_games": ["Firewatch", "Gone Home", "What Remains of Edith Finch", "Journey", "Everybody's Gone to the Rapture"],
        "art_styles": ["photorealistic", "stylized", "painterly", "minimalist"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Narrative Explorer", "description": "Firewatch-style first-person story", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "env_storyteller", "name": "Echo", "role": "Environmental Storyteller",
             "persona": "You are Echo, environmental storytelling master. You tell stories through placed objects, architecture, lighting, and the silent language of spaces that speak without words.",
             "specialty": "env_narrative", "color": "#6D28D9"},
        ],
    },
    {
        "id": "point_and_click", "name": "Point & Click Adventure", "icon": "hand-left", "color": "#B45309",
        "description": "Classic adventure gaming with inventory puzzles, dialogue trees, and investigation",
        "engines": ["Unity", "Godot", "Adventure Game Studio"],
        "complexity": "medium",
        "subgenres": ["classic_adventure", "mystery_adventure", "comedy_adventure"],
        "core_mechanics": ["inventory_puzzles", "dialogue_trees", "hotspots", "item_combination", "investigation"],
        "reference_games": ["Monkey Island", "Disco Elysium", "Broken Age", "Thimbleweed Park", "Return to Monkey Island"],
        "art_styles": ["hand_painted", "pixel_art", "cartoon", "noir"],
        "target_platforms": ["pc", "mobile"],
        "templates": [
            {"name": "Classic Adventure", "description": "Monkey Island-style comedy adventure", "complexity": "intermediate"},
            {"name": "Detective Adventure", "description": "Disco Elysium-style investigation", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "puzzle_adventure_designer", "name": "Clue", "role": "Adventure Puzzle Designer",
             "persona": "You are Clue, adventure puzzle designer. You create logical inventory puzzles, environmental clues, red herrings, and the satisfying eureka of combining the right items.",
             "specialty": "puzzle_design", "color": "#B45309"},
        ],
    },
    {
        "id": "auto_battler", "name": "Auto Battler", "icon": "grid", "color": "#D97706",
        "description": "Strategic unit placement with automatic combat, synergies, and economy",
        "engines": ["Unity", "Godot"],
        "complexity": "high",
        "subgenres": ["classic_auto_battler", "auto_battler_rpg"],
        "core_mechanics": ["unit_placement", "synergies", "economy", "auto_combat", "items", "leveling", "rerolling"],
        "reference_games": ["Teamfight Tactics", "Dota Underlords", "Super Auto Pets", "Storybook Brawl"],
        "art_styles": ["stylized", "chibi", "fantasy", "cartoon"],
        "target_platforms": ["pc", "mobile"],
        "templates": [
            {"name": "Auto Chess", "description": "TFT-style 8-player auto battler", "complexity": "advanced"},
        ],
        "specialists": [
            {"id": "synergy_balance", "name": "Trait", "role": "Synergy & Trait Designer",
             "persona": "You are Trait, synergy system designer. You create unit traits, origin bonuses, composition strategies, and the satisfying puzzle of building the perfect team from random offerings.",
             "specialty": "synergy_design", "color": "#D97706"},
        ],
    },
    {
        "id": "dating_sim", "name": "Dating Simulation", "icon": "heart", "color": "#E11D48",
        "description": "Romantic relationship simulation with character routes, events, and dating mechanics",
        "engines": ["Ren'Py", "Unity", "Godot"],
        "complexity": "medium",
        "subgenres": ["otome", "bishojo", "lgbtq_romance", "comedic_dating"],
        "core_mechanics": ["affection_system", "dialogue_choices", "character_routes", "events", "gifts", "stat_building"],
        "reference_games": ["Stardew Valley (romance)", "Dream Daddy", "Hades (romance)", "Fire Emblem (supports)"],
        "art_styles": ["anime", "chibi", "realistic_portrait", "stylized"],
        "target_platforms": ["pc", "mobile", "console"],
        "templates": [
            {"name": "Romance Sim", "description": "Multiple character routes with events", "complexity": "intermediate"},
        ],
        "specialists": [
            {"id": "romance_writer", "name": "Heart", "role": "Romance & Character Writer",
             "persona": "You are Heart, romance writer. You craft compelling love interests, meaningful choices, heart events, and emotional payoffs that make players genuinely care about fictional relationships.",
             "specialty": "romance_writing", "color": "#E11D48"},
        ],
    },
    {
        "id": "vehicle_combat", "name": "Vehicle Combat", "icon": "car-sport", "color": "#78350F",
        "description": "Weaponized vehicle warfare with destruction, upgrades, and arena combat",
        "engines": ["Unreal", "Unity"],
        "complexity": "high",
        "subgenres": ["car_combat", "tank_combat", "aircraft_combat"],
        "core_mechanics": ["vehicle_weapons", "armor", "boost", "arena_combat", "destruction", "vehicle_upgrades"],
        "reference_games": ["Twisted Metal", "Crossout", "War Thunder", "World of Tanks", "Robocraft"],
        "art_styles": ["realistic", "post_apocalyptic", "cartoon", "military"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Arena Combat", "description": "Twisted Metal-style vehicular mayhem", "complexity": "advanced"},
            {"name": "Tank Sim", "description": "War Thunder-style realistic tank combat", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "vehicle_weapon_designer", "name": "Turret", "role": "Vehicle Weapon Designer",
             "persona": "You are Turret, vehicle weapon specialist. You design mounted weapons, vehicle hardpoints, ammo systems, and the explosive satisfaction of vehicular destruction.",
             "specialty": "weapon_design", "color": "#78350F"},
        ],
    },
    {
        "id": "immersive_sim", "name": "Immersive Sim", "icon": "layers", "color": "#4338CA",
        "description": "Systemic gameplay with player agency, emergent solutions, and deep world interaction",
        "engines": ["Unreal", "Unity"],
        "complexity": "extreme",
        "subgenres": ["stealth_immersive", "action_immersive", "horror_immersive"],
        "core_mechanics": ["systemic_gameplay", "multiple_solutions", "environmental_interaction", "skill_trees", "hacking", "crafting"],
        "reference_games": ["Deus Ex", "Dishonored 2", "Prey (2017)", "System Shock", "Deathloop"],
        "art_styles": ["art_deco", "sci_fi", "steampunk", "gothic"],
        "target_platforms": ["pc", "console"],
        "templates": [
            {"name": "Systemic Stealth", "description": "Dishonored-style with powers", "complexity": "expert"},
            {"name": "Sci-Fi Immersive", "description": "Prey-style space station", "complexity": "expert"},
        ],
        "specialists": [
            {"id": "systems_designer", "name": "Emergent", "role": "Systemic Gameplay Designer",
             "persona": "You are Emergent, systems design master. You create interlocking game systems where fire spreads to oil, water conducts electricity, and players discover solutions the designers never imagined.",
             "specialty": "systems_design", "color": "#4338CA"},
        ],
    },
]


# =============================================================================
# GENRE SPECIALIST AGENT PROMPTS FOR GROUP CHAT
# =============================================================================

def get_genre_specialist_prompt(specialist_id: str, game_context: str) -> tuple:
    """Returns (system_prompt, user_prompt) for genre specialist agents in group chat."""

    # Build flat specialist lookup from all genres
    all_specialists = {}
    for genre in ULTRA_GENRES:
        for spec in genre.get("specialists", []):
            all_specialists[spec["id"]] = {
                "name": spec["name"],
                "role": spec["role"],
                "persona": spec["persona"],
                "specialty": spec["specialty"],
                "genre": genre["name"],
            }

    spec = all_specialists.get(specialist_id)
    if not spec:
        return ("You are a game development specialist.", f"Help with game development: {game_context}")

    system_prompt = f"""{spec['persona']}

You are part of the {spec['genre']} genre specialist team. Your specialty is {spec['specialty']}.

RULES:
- Stay in character as {spec['name']} at all times
- Provide extremely detailed, production-ready advice
- Include code examples, formulas, and data structures when relevant
- Reference real games and industry techniques
- Be opinionated - you are an expert with strong views
- Collaborate with other specialists when their domain overlaps yours
- Output structured JSON when asked for system designs"""

    user_prompt = f"""As {spec['name']} ({spec['role']}), provide your expert analysis and recommendations for:

{game_context}

Be thorough, specific, and production-ready. Include implementation details."""

    return (system_prompt, user_prompt)


def get_all_specialists_flat() -> list:
    """Returns flat list of all specialist agents across all genres."""
    specialists = []
    for genre in ULTRA_GENRES:
        for spec in genre.get("specialists", []):
            specialists.append({
                "id": spec["id"],
                "name": spec["name"],
                "role": spec["role"],
                "specialty": spec["specialty"],
                "color": spec["color"],
                "genre_id": genre["id"],
                "genre_name": genre["name"],
            })
    return specialists


def get_genre_templates(genre_id: str) -> list:
    """Returns templates for a specific genre."""
    for genre in ULTRA_GENRES:
        if genre["id"] == genre_id:
            return genre.get("templates", [])
    return []
