use std::collections::HashMap;use std::sync::atomic::{AtomicU64,Ordering};use chrono::{DateTime,Utc};use serde::{Deserialize,Serialize};use tokio::sync::RwLock;use uuid::Uuid;
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct Member{pub id:String,pub rank:u32,pub capability:String,pub sworn_at:DateTime<Utc>,pub last_heartbeat:DateTime<Utc>,pub tasks_done:u64,pub traitor:bool}
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct Cohort{pub id:String,pub capability:String,pub members:Vec<Member>}
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct Legion{pub id:String,pub name:String,pub motto:String,pub cohorts:Vec<Cohort>,pub founded:DateTime<Utc>}
pub struct LegionRegistry{legions:RwLock<HashMap<String,Legion>>,pub enlisted_total:AtomicU64,pub cashiered_total:AtomicU64}
impl Default for LegionRegistry{fn default()->Self{Self::new()}}
impl LegionRegistry{pub fn new()->Self{Self{legions:RwLock::new(HashMap::new()),enlisted_total:AtomicU64::new(0),cashiered_total:AtomicU64::new(0)}}
 pub async fn found(&self,name:&str,motto:&str)->Legion{let l=Legion{id:Uuid::new_v4().to_string(),name:name.to_string(),motto:motto.to_string(),cohorts:Vec::new(),founded:Utc::now()};self.legions.write().await.insert(l.name.clone(),l.clone());l}
 pub async fn enlist(&self,ln:&str,cap:&str)->Option<String>{let mut ls=self.legions.write().await;let l=ls.get_mut(ln)?;if !l.cohorts.iter().any(|c|c.capability==cap){l.cohorts.push(Cohort{id:Uuid::new_v4().to_string(),capability:cap.to_string(),members:Vec::new()});}let c=l.cohorts.iter_mut().find(|c|c.capability==cap)?;let m=Member{id:Uuid::new_v4().to_string(),rank:1,capability:cap.to_string(),sworn_at:Utc::now(),last_heartbeat:Utc::now(),tasks_done:0,traitor:false};let id=m.id.clone();c.members.push(m);self.enlisted_total.fetch_add(1,Ordering::Relaxed);Some(id)}
 pub async fn heartbeat(&self,ln:&str,id:&str)->bool{let mut ls=self.legions.write().await;let Some(l)=ls.get_mut(ln)else{return false};for c in &mut l.cohorts{for m in &mut c.members{if m.id==id{m.last_heartbeat=Utc::now();return true}}}false}
 pub async fn cashier(&self,ln:&str,id:&str)->bool{let mut ls=self.legions.write().await;let Some(l)=ls.get_mut(ln)else{return false};for c in &mut l.cohorts{for m in &mut c.members{if m.id==id&&!m.traitor{m.traitor=true;self.cashiered_total.fetch_add(1,Ordering::Relaxed);return true}}}false}
 pub async fn promote(&self,ln:&str,id:&str)->bool{let mut ls=self.legions.write().await;let Some(l)=ls.get_mut(ln)else{return false};for c in &mut l.cohorts{for m in &mut c.members{if m.id==id&&!m.traitor{m.rank+=1;return true}}}false}
 pub async fn degrade_silent(&self,max:i64)->u64{let now=Utc::now();let mut d=0;let mut ls=self.legions.write().await;for l in ls.values_mut(){for c in &mut l.cohorts{for m in &mut c.members{if !m.traitor&&m.rank>1&&(now-m.last_heartbeat).num_seconds()>max{m.rank-=1;d+=1}}}}d}
 pub async fn get(&self,name:&str)->Option<Legion>{self.legions.read().await.get(name).cloned()}pub async fn list(&self)->Vec<Legion>{self.legions.read().await.values().cloned().collect()}
 pub async fn fit_for(&self,cap:&str)->Vec<(String,Member)>{let ls=self.legions.read().await;let mut out=Vec::new();for l in ls.values(){for c in &l.cohorts{if c.capability!=cap{continue}for m in &c.members{if !m.traitor{out.push((l.name.clone(),m.clone()))}}}}out.sort_by(|a,b|b.1.rank.cmp(&a.1.rank));out}
}
