use std::collections::HashMap;use std::sync::Arc;use chrono::{DateTime,Utc};use serde::{Deserialize,Serialize};use tokio::sync::RwLock;use uuid::Uuid;
pub mod boardroom;pub mod cognition;pub mod economy;pub mod governance;pub mod lafs;pub mod legions;pub mod media_studio;pub mod reputation;pub mod swarm;pub mod voting;

pub mod fabric{use super::*;use gf_core::digest::sha256_hex;
 #[derive(Debug,Clone,Serialize,Deserialize)]pub struct FabricEvent{pub id:String,pub ledger:String,pub kind:String,pub payload:serde_json::Value,pub ts:DateTime<Utc>,pub seq:u64,pub quorum:Vec<String>,pub prev_hash:String,pub hash:String}
 impl FabricEvent{fn canonical(&self)->String{format!("{}|{}|{}|{}|{}|{}|{}",self.seq,self.ledger,self.kind,self.payload,self.ts.to_rfc3339(),self.quorum.join(","),self.prev_hash)}pub fn compute_hash(&self)->String{sha256_hex(self.canonical().as_bytes())}}
 pub struct OmniFabric{hot_tail:RwLock<Vec<FabricEvent>>,seq:RwLock<u64>,head_hash:RwLock<String>,outbox:Arc<gf_core::outbox::Outbox>,hot_cap:usize}
 impl Default for OmniFabric{fn default()->Self{Self::new(2048)}}impl OmniFabric{pub fn new(hot_cap:usize)->Self{Self{hot_tail:RwLock::new(Vec::with_capacity(hot_cap.min(1024))),seq:RwLock::new(0),head_hash:RwLock::new("genesis".to_string()),outbox:Arc::new(gf_core::outbox::Outbox::default()),hot_cap}}
 pub fn outbox(&self)->Arc<gf_core::outbox::Outbox>{self.outbox.clone()}
 pub async fn append(&self,ledger:&str,kind:&str,payload:serde_json::Value,quorum:Vec<String>)->FabricEvent{let mut seq=self.seq.write().await;*seq+=1;let prev_hash=self.head_hash.read().await.clone();let mut ev=FabricEvent{id:Uuid::new_v4().to_string(),ledger:ledger.to_string(),kind:kind.to_string(),payload,ts:Utc::now(),seq:*seq,quorum,prev_hash,hash:String::new()};ev.hash=ev.compute_hash();*self.head_hash.write().await=ev.hash.clone();drop(seq);if let Err(e)=self.outbox.journal("omega_fabric",&ev).await{tracing::error!(error=%e,"outbox journal failed — refusing append");let mut seq=self.seq.write().await;*seq-=1;*self.head_hash.write().await=ev.prev_hash.clone();panic!("outbox backpressure: {e}")}let mut tail=self.hot_tail.write().await;if tail.len()>=self.hot_cap{let drain=self.hot_cap/4;tail.drain(0..drain);}tail.push(ev.clone());drop(tail);let outbox=self.outbox.clone();let jseq=self.outbox.journaled_total.load(std::sync::atomic::Ordering::Relaxed);tokio::spawn(async move{let _=outbox.confirm_one(jseq).await;});ev}
 pub async fn verify_chain(&self)->Result<(),(u64,String)>{let tail=self.hot_tail.read().await;let mut prev="genesis".to_string();for ev in tail.iter(){if ev.prev_hash!=prev{return Err((ev.seq,format!("prev_hash mismatch: expected {prev}, got {}",ev.prev_hash)))}if ev.hash!=ev.compute_hash(){return Err((ev.seq,"event hash does not match its content".into()))}prev=ev.hash.clone()}Ok(())}
 pub async fn tail(&self,ledger:&str,limit:usize)->Vec<FabricEvent>{self.hot_tail.read().await.iter().filter(|e|e.ledger==ledger).rev().take(limit).cloned().collect()}pub async fn current_seq(&self)->u64{*self.seq.read().await}pub async fn head_hash(&self)->String{self.head_hash.read().await.clone()}}
}

pub mod delta_memory{use super::*;pub struct DeltaMemory{window:RwLock<Vec<(String,serde_json::Value)>>,snapshot:RwLock<HashMap<String,serde_json::Value>>,window_cap:usize,pub compactions:std::sync::atomic::AtomicU64}impl DeltaMemory{pub fn new(window_cap:usize)->Self{Self{window:RwLock::new(Vec::with_capacity(window_cap)),snapshot:RwLock::new(HashMap::new()),window_cap,compactions:std::sync::atomic::AtomicU64::new(0)}}pub async fn write(&self,key:String,value:serde_json::Value){let mut w=self.window.write().await;w.push((key,value));if w.len()>=self.window_cap{let mut s=self.snapshot.write().await;for(k,v)in w.drain(..){s.insert(k,v);}self.compactions.fetch_add(1,std::sync::atomic::Ordering::Relaxed);}}pub async fn read(&self,key:&str)->Option<serde_json::Value>{let w=self.window.read().await;for(k,v)in w.iter().rev(){if k==key{return Some(v.clone())}}drop(w);self.snapshot.read().await.get(key).cloned()}pub async fn stats(&self)->serde_json::Value{serde_json::json!({"window_len":self.window.read().await.len(),"snapshot_keys":self.snapshot.read().await.len(),"compactions":self.compactions.load(std::sync::atomic::Ordering::Relaxed)})}}}

pub mod quorum{use super::*;use gf_core::digest::sha256_hex;pub struct Court{pub name:String,pub f:usize,attestations:RwLock<HashMap<String,Vec<(String,String)>>>,suspects:RwLock<HashMap<String,u64>>}#[derive(Debug,Clone,Copy,PartialEq,Eq,Serialize)]pub enum Verdict{Pending,Decided,Deadlocked}impl Court{pub fn new(name:impl Into<String>,f:usize)->Self{Self{name:name.into(),f,attestations:RwLock::new(HashMap::new()),suspects:RwLock::new(HashMap::new())}}pub fn quorum_size(&self)->usize{2*self.f+1}pub fn value_hash(v:&serde_json::Value)->String{sha256_hex(v.to_string().as_bytes())}pub async fn attest(&self,pid:&str,attester:&str,value:&serde_json::Value)->Verdict{let hash=Self::value_hash(value);let mut all=self.attestations.write().await;let entry=all.entry(pid.to_string()).or_default();if entry.iter().any(|(a,_)|a==attester){return Verdict::Pending}entry.push((attester.to_string(),hash.clone()));let mut counts:HashMap<&str,usize>=HashMap::new();for(_,h)in entry.iter(){*counts.entry(h.as_str()).or_default()+=1}let decided=counts.iter().find(|(_,n)|**n>=self.quorum_size()).map(|(h,_)|h.to_string());if let Some(winning)=decided{let mut suspects=self.suspects.write().await;for(a,h)in entry.iter(){if *h!=winning{*suspects.entry(a.clone()).or_insert(0)+=1}}all.remove(pid);return Verdict::Decided}let electorate=3*self.f+1;let cast=entry.len();let remaining=electorate.saturating_sub(cast);if counts.values().all(|n|*n+remaining<self.quorum_size()){all.remove(pid);return Verdict::Deadlocked}Verdict::Pending}pub async fn suspects(&self)->serde_json::Value{serde_json::json!(self.suspects.read().await.clone())}}}

pub mod saga{use super::*;#[derive(Debug,Clone,Serialize,Deserialize)]pub struct Step{pub name:String,pub status:StepStatus}#[derive(Debug,Clone,Copy,PartialEq,Eq,Serialize,Deserialize)]pub enum StepStatus{Pending,Done,Compensated,Failed}#[derive(Debug,Clone,Serialize,Deserialize)]pub struct Saga{pub id:String,pub name:String,pub steps:Vec<Step>,pub cursor:usize,pub finished:bool,pub failed:bool,pub created:DateTime<Utc>}pub struct SagaRegistry{sagas:RwLock<HashMap<String,Saga>>}impl Default for SagaRegistry{fn default()->Self{Self::new()}}impl SagaRegistry{pub fn new()->Self{Self{sagas:RwLock::new(HashMap::new())}}pub async fn begin(&self,name:&str,steps:Vec<&str>)->String{let id=Uuid::new_v4().to_string();let saga=Saga{id:id.clone(),name:name.to_string(),steps:steps.into_iter().map(|s|Step{name:s.to_string(),status:StepStatus::Pending}).collect(),cursor:0,finished:false,failed:false,created:Utc::now()};self.sagas.write().await.insert(id.clone(),saga);id}pub async fn complete_step(&self,id:&str)->Option<bool>{let mut ss=self.sagas.write().await;let s=ss.get_mut(id)?;if s.cursor<s.steps.len(){s.steps[s.cursor].status=StepStatus::Done;s.cursor+=1}if s.cursor>=s.steps.len(){s.finished=true}Some(s.finished)}pub async fn fail(&self,id:&str)->Option<()>{let mut ss=self.sagas.write().await;let s=ss.get_mut(id)?;s.failed=true;if s.cursor<s.steps.len(){s.steps[s.cursor].status=StepStatus::Failed}for i in(0..s.cursor).rev(){s.steps[i].status=StepStatus::Compensated}s.finished=true;Some(())}pub async fn get(&self,id:&str)->Option<Saga>{self.sagas.read().await.get(id).cloned()}pub async fn list(&self)->Vec<Saga>{self.sagas.read().await.values().cloned().collect()}}}

pub struct Zaibatsu{pub fabric:fabric::OmniFabric,pub delta:delta_memory::DeltaMemory,pub court:quorum::Court,pub sagas:saga::SagaRegistry,pub legions:legions::LegionRegistry,pub swarm:swarm::SwarmDag,pub governance:governance::Governance,pub cognition:cognition::Cognition,pub lafs:lafs::Lafs,pub studio:media_studio::Studio,pub boardroom:boardroom::Boardroom,pub economy:economy::Treasury,pub reputation:reputation::Reputation,pub voting:voting::Diet}
impl Default for Zaibatsu{fn default()->Self{Self::new()}}impl Zaibatsu{pub fn new()->Self{Self{fabric:fabric::OmniFabric::default(),delta:delta_memory::DeltaMemory::new(512),court:quorum::Court::new("high-court",1),sagas:saga::SagaRegistry::new(),legions:legions::LegionRegistry::new(),swarm:swarm::SwarmDag::new(),governance:governance::Governance::new(),cognition:cognition::Cognition::new(),lafs:lafs::Lafs::new(),studio:media_studio::Studio::new(),boardroom:boardroom::Boardroom::new(),economy:economy::Treasury::new(),reputation:reputation::Reputation::new(),voting:voting::Diet::new()}}pub async fn propose(&self,ledger:&str,kind:&str,pid:&str,attester:&str,value:serde_json::Value)->(quorum::Verdict,Option<fabric::FabricEvent>){match self.court.attest(pid,attester,&value).await{quorum::Verdict::Decided=>{let ev=self.fabric.append(ledger,kind,value,vec![attester.to_string()]).await;self.delta.write(ev.id.clone(),serde_json::json!({"ledger":ledger,"kind":kind})).await;(quorum::Verdict::Decided,Some(ev))},v=>(v,None)}}}
pub type SharedZaibatsu=Arc<Zaibatsu>;
