use std::collections::{HashMap,HashSet};use serde::{Deserialize,Serialize};use tokio::sync::RwLock;
#[derive(Debug,Clone,Copy,PartialEq,Eq,Serialize,Deserialize)]pub enum TaskStatus{Pending,Ready,Running,Done,Failed}
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct TaskNode{pub id:String,pub capability:String,pub payload:serde_json::Value,pub deps:Vec<String>,pub status:TaskStatus,pub executor:Option<String>,pub result:Option<serde_json::Value>}
pub struct SwarmDag{nodes:RwLock<HashMap<String,TaskNode>>}impl Default for SwarmDag{fn default()->Self{Self::new()}}
#[derive(Debug,Clone,PartialEq,Eq)]pub enum SubmitError{UnknownDependency(String),Cycle(String),Duplicate(String)}
impl SwarmDag{pub fn new()->Self{Self{nodes:RwLock::new(HashMap::new())}}
 pub async fn submit(&self,id:&str,cap:&str,payload:serde_json::Value,deps:Vec<String>)->Result<(),SubmitError>{let mut ns=self.nodes.write().await;if ns.contains_key(id){return Err(SubmitError::Duplicate(id.to_string()))}for d in &deps{if !ns.contains_key(d){return Err(SubmitError::UnknownDependency(d.clone()))}}if deps.iter().any(|d|d==id){return Err(SubmitError::Cycle(id.to_string()))}ns.insert(id.to_string(),TaskNode{id:id.to_string(),capability:cap.to_string(),payload,deps,status:TaskStatus::Pending,executor:None,result:None});Ok(())}
 pub async fn ready_wave(&self)->Vec<TaskNode>{let mut ns=self.nodes.write().await;let done:HashSet<String>=ns.values().filter(|n|n.status==TaskStatus::Done).map(|n|n.id.clone()).collect();let mut w=Vec::new();for n in ns.values_mut(){if n.status==TaskStatus::Pending&&n.deps.iter().all(|d|done.contains(d)){n.status=TaskStatus::Ready;w.push(n.clone())}}w}
 pub async fn claim(&self,id:&str,e:&str)->Option<TaskNode>{let mut ns=self.nodes.write().await;let n=ns.get_mut(id)?;if n.status!=TaskStatus::Ready{return None}n.status=TaskStatus::Running;n.executor=Some(e.to_string());Some(n.clone())}
 pub async fn complete(&self,id:&str,r:serde_json::Value)->Option<()>{let mut ns=self.nodes.write().await;let n=ns.get_mut(id)?;if n.status!=TaskStatus::Running{return None}n.status=TaskStatus::Done;n.result=Some(r);Some(())}
 pub async fn fail(&self,id:&str)->Option<()>{let mut ns=self.nodes.write().await;let n=ns.get_mut(id)?;if n.status!=TaskStatus::Running{return None}n.status=TaskStatus::Failed;Some(())}
 pub async fn get(&self,id:&str)->Option<TaskNode>{self.nodes.read().await.get(id).cloned()}pub async fn stats(&self)->serde_json::Value{let ns=self.nodes.read().await;let mut c:HashMap<&str,usize>=HashMap::new();for n in ns.values(){let l=match n.status{TaskStatus::Pending=>"pending",TaskStatus::Ready=>"ready",TaskStatus::Running=>"running",TaskStatus::Done=>"done",TaskStatus::Failed=>"failed"};*c.entry(l).or_default()+=1}serde_json::json!({"tasks":ns.len(),"by_status":c})}}
