use std::collections::HashMap;use chrono::{DateTime,Utc};use serde::{Deserialize,Serialize};use tokio::sync::RwLock;use uuid::Uuid;
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct Ballot{pub voter:String,pub option:String,pub cast_at:DateTime<Utc>}
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct Measure{pub id:String,pub title:String,pub options:Vec<String>,pub proposer:String,pub opened:DateTime<Utc>,pub closes:DateTime<Utc>,pub closed:bool}
pub struct Diet{measures:RwLock<HashMap<String,Measure>>,ballots:RwLock<HashMap<String,Vec<Ballot>>>}impl Default for Diet{fn default()->Self{Self::new()}}
impl Diet{pub fn new()->Self{Self{measures:RwLock::new(HashMap::new()),ballots:RwLock::new(HashMap::new())}}
 pub async fn propose(&self,title:&str,options:Vec<String>,proposer:&str,open_secs:i64)->Result<Measure,String>{if options.len()<2{return Err("a measure needs at least two options".into())}let m=Measure{id:Uuid::new_v4().to_string(),title:title.to_string(),options,proposer:proposer.to_string(),opened:Utc::now(),closes:Utc::now()+chrono::Duration::seconds(open_secs.max(60)),closed:false};self.measures.write().await.insert(m.id.clone(),m.clone());Ok(m)}
 pub async fn cast(&self,id:&str,voter:&str,option:&str)->Result<(),String>{let ms=self.measures.read().await;let m=ms.get(id).ok_or("no such measure")?;if m.closed||Utc::now()>m.closes{return Err("the measure is closed".into())}if !m.options.iter().any(|o|o==option){return Err("no such option on this measure".into())}drop(ms);let mut bs=self.ballots.write().await;let roll=bs.entry(id.to_string()).or_default();if roll.iter().any(|b|b.voter==voter){return Err("one voice per measure — you have already spoken".into())}roll.push(Ballot{voter:voter.to_string(),option:option.to_string(),cast_at:Utc::now()});Ok(())}
 pub async fn tally(&self,id:&str)->Option<serde_json::Value>{let m=self.measures.read().await.get(id)?.clone();let roll=self.ballots.read().await.get(id).cloned().unwrap_or_default();let mut counts:HashMap<&str,usize>=HashMap::new();for o in &m.options{counts.insert(o.as_str(),0);}for b in &roll{*counts.entry(b.option.as_str()).or_insert(0)+=1;}let winner=m.options.iter().max_by_key(|o|(counts.get(o.as_str()).copied().unwrap_or(0),std::cmp::Reverse(m.options.iter().position(|x|x==*o).unwrap()))).cloned();Some(serde_json::json!({"measure":m.title,"closed":m.closed||Utc::now()>m.closes,"ballots":roll.len(),"counts":counts,"leading":winner}))}
 pub async fn close(&self,id:&str)->Option<Measure>{let mut ms=self.measures.write().await;let m=ms.get_mut(id)?;m.closed=true;Some(m.clone())}pub async fn measures(&self)->Vec<Measure>{self.measures.read().await.values().cloned().collect()}}
