"""P3 deferred-frontier runtime extensions."""

from .multimodal import (
    AudioAsset,
    AudioResult,
    AudioSegment,
    CrossModalEvidence,
    DocumentPage,
    FrameSample,
    ImageAsset,
    ImageRegion,
    LayoutRegion,
    MediaTransform,
    MultimodalAsset,
    MultimodalHit,
    MultimodalQuery,
    MultimodalRegistry,
    OCRSpan,
    ResourceLimits,
    SpeechFrame,
    SpeechSession,
    TranscriptSegment,
    VideoAsset,
    VideoSegment,
    VisionResult,
    digest_bytes,
    fuse_scores,
)

__all__ = [
    "AudioAsset",
    "AudioResult",
    "AudioSegment",
    "CrossModalEvidence",
    "DocumentPage",
    "FrameSample",
    "ImageAsset",
    "ImageRegion",
    "LayoutRegion",
    "MediaTransform",
    "MultimodalAsset",
    "MultimodalHit",
    "MultimodalQuery",
    "MultimodalRegistry",
    "OCRSpan",
    "ResourceLimits",
    "SpeechFrame",
    "SpeechSession",
    "TranscriptSegment",
    "VideoAsset",
    "VideoSegment",
    "VisionResult",
    "digest_bytes",
    "fuse_scores",
]
