"""Engine-neutral networking contracts for Skeleton.

This package holds replication and rollback primitives that later transport,
session, and engine adapters can consume. It does not open sockets.
"""

from skeleton.distributed.network.internal_protocol import (
    INTERNAL_PROTOCOL_SCHEMA_VERSION,
    VOL_131_ID,
    DeliverySemantics,
    ProtocolEnvelope,
    ProtocolError,
    ProtocolOutcome,
    ProtocolReceipt,
    TraceContext,
    UnknownOutcomePolicy,
    canonical_digest as protocol_canonical_digest,
    canonical_json_bytes as protocol_canonical_json_bytes,
    canonical_payload_digest,
    validate_receipt,
)

from skeleton.distributed.network.model_placement import (
    MODEL_PLACEMENT_ACCOUNTABILITY_ID,
    MODEL_PLACEMENT_SCHEMA_VERSION,
    MODEL_PLACEMENT_TASK_ID,
    ModelPlacementDecision,
    ModelPlacementError,
    ModelPlacementRequest,
    ModelWarmAuthorizationDecision,
    ModelWarmObservation,
    WarmReadiness,
    qualify_model_placement,
    qualify_model_warmup,
)

from skeleton.distributed.network.remote_execution import (
    REMOTE_EXECUTION_ACCOUNTABILITY_ID,
    REMOTE_EXECUTION_SCHEMA_VERSION,
    REMOTE_EXECUTION_TASK_ID,
    RemoteExecutionCommitDecision,
    RemoteExecutionError,
    RemoteExecutionFence,
    RemoteExecutionGrantDecision,
    RemoteExecutionRequest,
    RemoteExecutionResult,
    RemoteResultStatus,
    WorkerAttestation,
    issue_remote_execution_fence,
    lease_digest,
    qualify_remote_execution,
    qualify_remote_execution_commit,
    worker_identity_digest,
)

from skeleton.distributed.network.replication import (
    SCHEMA_VERSION,
    Ack,
    Authority,
    DeliveryOutcome,
    HistoryExhaustedError,
    IngestResult,
    OfflineChannel,
    Patch,
    PatchOp,
    ReconciliationEvidence,
    Replica,
    ReplicationError,
    RollbackEvidence,
    SchemaCompatibilityError,
    SequenceError,
    SerializationError,
    canonical_dumps,
    frame_digest,
    state_digest,
)

__all__ = [
    "SCHEMA_VERSION",
    "Ack",
    "Authority",
    "DeliveryOutcome",
    "HistoryExhaustedError",
    "IngestResult",
    "OfflineChannel",
    "Patch",
    "PatchOp",
    "ReconciliationEvidence",
    "Replica",
    "ReplicationError",
    "RollbackEvidence",
    "SchemaCompatibilityError",
    "SequenceError",
    "SerializationError",
    "canonical_dumps",
    "frame_digest",
    "state_digest",
    "REMOTE_EXECUTION_ACCOUNTABILITY_ID",
    "REMOTE_EXECUTION_SCHEMA_VERSION",
    "REMOTE_EXECUTION_TASK_ID",
    "RemoteExecutionCommitDecision",
    "RemoteExecutionError",
    "RemoteExecutionFence",
    "RemoteExecutionGrantDecision",
    "RemoteExecutionRequest",
    "RemoteExecutionResult",
    "RemoteResultStatus",
    "WorkerAttestation",
    "issue_remote_execution_fence",
    "lease_digest",
    "qualify_remote_execution",
    "qualify_remote_execution_commit",
    "worker_identity_digest",
    "MODEL_PLACEMENT_ACCOUNTABILITY_ID",
    "MODEL_PLACEMENT_SCHEMA_VERSION",
    "MODEL_PLACEMENT_TASK_ID",
    "ModelPlacementDecision",
    "ModelPlacementError",
    "ModelPlacementRequest",
    "ModelWarmAuthorizationDecision",
    "ModelWarmObservation",
    "WarmReadiness",
    "qualify_model_placement",
    "qualify_model_warmup",
    "INTERNAL_PROTOCOL_SCHEMA_VERSION",
    "VOL_131_ID",
    "DeliverySemantics",
    "ProtocolEnvelope",
    "ProtocolError",
    "ProtocolOutcome",
    "ProtocolReceipt",
    "TraceContext",
    "UnknownOutcomePolicy",
    "protocol_canonical_digest",
    "protocol_canonical_json_bytes",
    "canonical_payload_digest",
    "validate_receipt",
]
