"""Deterministic engine-neutral ECS/simulation core.

The package exposes versioned state, deterministic execution, rollback/replay,
and bounded inspection contracts without depending on a renderer, transport,
provider SDK, or engine runtime.
"""

from .core import (
    Archetype,
    ArchetypeRegistry,
    BoundsError,
    CompareOp,
    ComponentError,
    ComponentExistsError,
    ComponentIndex,
    ComponentNotFoundError,
    ComponentSchema,
    ComponentTemplate,
    ComponentValue,
    DeltaError,
    ECSError,
    EncodedDocument,
    EntityAllocator,
    EntityError,
    EntityExistsError,
    EntityId,
    EntityNotFoundError,
    EntityRecord,
    EntityStore,
    EntityTombstonedError,
    EventError,
    EventOverflowError,
    FieldKind,
    FieldPredicate,
    FieldSpec,
    FindingSeverity,
    IdentifierError,
    IndexSnapshot,
    InvariantFinding,
    InvariantInspector,
    InvariantReport,
    MigrationEvidence,
    MigrationRegistry,
    MigrationStep,
    PlanMetrics,
    QueryEngine,
    QueryError,
    QueryRow,
    QuerySpec,
    ReplayDivergenceError,
    ReplayError,
    ResourceError,
    ResourceNotFoundError,
    ResourceValue,
    ScheduleCycleError,
    ScheduleError,
    SchemaConflictError,
    SchemaError,
    SchemaNotFoundError,
    SchemaRegistry,
    SchemaVersionError,
    SnapshotDigestError,
    SnapshotError,
    SnapshotVersionError,
    StoreMetrics,
    SystemConflictError,
    SystemNotFoundError,
    Tombstone,
    TransactionError,
    ValidationError,
    canonical_bytes,
    canonical_json,
    canonical_node,
    chained_digest,
    decode_document,
    digest,
    encode_document,
    make_schema,
    plan_metrics,
    store_metrics,
    validate_entity_id,
    validate_field,
    validate_namespace,
)
from .execution import (
    ClockError,
    ClockSnapshot,
    Command,
    CommandBuffer,
    CommandError,
    CommandKind,
    CommandOverflowError,
    CommandResult,
    CommitReceipt,
    DeltaOperation,
    Event,
    EventQueue,
    EventReceipt,
    ExecutionBatch,
    ExecutionPlan,
    SimulationClock,
    SnapshotHistory,
    StoreDelta,
    StoreSnapshot,
    SystemGraph,
    SystemPhase,
    SystemSpec,
    apply_delta,
    capture_snapshot,
    conflicts,
    diff_snapshots,
    restore_snapshot,
)
from .runtime import (
    ReplayFrame,
    ReplayRecorder,
    ReplayTape,
    ReplayVerification,
    RuntimeCheckpoint,
    RuntimeMetrics,
    SimulationRuntime,
    SystemContext,
    SystemExecutionReceipt,
    TickReceipt,
    capture_checkpoint,
    checkpoint_matches_runtime,
    replay,
    restore_checkpoint,
)
from .scenario import (
    ScenarioDefinition,
    ScenarioResult,
    build_reference_runtime,
    build_reference_store,
    compare_reference_runs,
    reference_registry,
    run_reference_scenario,
)

__all__ = [
    "Archetype", "ArchetypeRegistry", "BoundsError", "ClockError", "ClockSnapshot",
    "Command", "CommandBuffer", "CommandError", "CommandKind", "CommandOverflowError",
    "CommandResult", "CommitReceipt", "CompareOp", "ComponentError", "ComponentExistsError",
    "ComponentIndex", "ComponentNotFoundError", "ComponentSchema", "ComponentTemplate",
    "ComponentValue", "DeltaError", "DeltaOperation", "ECSError", "EncodedDocument",
    "EntityAllocator", "EntityError", "EntityExistsError", "EntityId", "EntityNotFoundError",
    "EntityRecord", "EntityStore", "EntityTombstonedError", "Event", "EventError",
    "EventOverflowError", "EventQueue", "EventReceipt", "ExecutionBatch", "ExecutionPlan",
    "FieldKind", "FieldPredicate", "FieldSpec", "FindingSeverity", "IdentifierError",
    "IndexSnapshot", "InvariantFinding", "InvariantInspector", "InvariantReport",
    "MigrationEvidence", "MigrationRegistry", "MigrationStep", "PlanMetrics", "QueryEngine",
    "QueryError", "QueryRow", "QuerySpec", "ReplayDivergenceError", "ReplayError",
    "ReplayFrame", "ReplayRecorder", "ReplayTape", "ReplayVerification", "ResourceError",
    "ResourceNotFoundError", "ResourceValue", "RuntimeCheckpoint", "RuntimeMetrics",
    "ScenarioDefinition", "ScenarioResult", "ScheduleCycleError", "ScheduleError",
    "SchemaConflictError", "SchemaError", "SchemaNotFoundError", "SchemaRegistry",
    "SchemaVersionError", "SimulationClock", "SimulationRuntime", "SnapshotDigestError",
    "SnapshotError", "SnapshotHistory", "SnapshotVersionError", "StoreDelta", "StoreMetrics",
    "StoreSnapshot", "SystemConflictError", "SystemContext", "SystemExecutionReceipt",
    "SystemGraph", "SystemNotFoundError", "SystemPhase", "SystemSpec", "TickReceipt",
    "Tombstone", "TransactionError", "ValidationError", "apply_delta", "build_reference_runtime",
    "build_reference_store", "canonical_bytes", "canonical_json", "canonical_node",
    "capture_checkpoint", "capture_snapshot", "chained_digest", "checkpoint_matches_runtime",
    "compare_reference_runs", "conflicts", "decode_document", "diff_snapshots", "digest",
    "encode_document", "make_schema", "plan_metrics", "reference_registry", "replay",
    "restore_checkpoint", "restore_snapshot", "run_reference_scenario", "store_metrics",
    "validate_entity_id", "validate_field", "validate_namespace",
]
