"""Jeeves evidence-first cognitive agent runtime.

Public imports are explicit enough for application code to assemble the runtime
without reaching through implementation paths.  The package surface now exposes
both the original bounded runtime and the newer scientific layers: cue-first
context, typed probability/uncertainty, semantic nuance and calibrated
prediction, perpendicular tangent continuity, and factorized causal control.
"""

from .action_model import (
    ActionEpisode,
    ActionModelError,
    BetaPosterior,
    CompositeSkillPlan,
    CompositeStep,
    ContextPerformance,
    ContextSignature,
    OutcomeKind,
    RunningStats,
    SelectionWeights,
    SkillComposer,
    SkillKind,
    SkillLibrary,
    SkillProfile,
    SkillScore,
    SkillSelection,
    SkillSpec,
)
from .cognition import (
    CognitionError,
    ContextBudget,
    ContextCompiler,
    ContextPacket,
    ContextSection,
    EvidenceContextPolicy,
    FINAL_RESPONSE_SCHEMA,
    FinalDraft,
    FinalDraftDecoder,
    MemoryContextPolicy,
    PromptCompiler,
    RunScratchpad,
    ScratchEntry,
    approximate_tokens,
)
from .context_pipeline import (
    ContextResolution,
    ContextSourceAdapter,
    ContextSourceKind,
    ContextTier,
    LayeredContextCompiler,
    LayeredContextResolver,
    ResolutionPolicy,
    ResolutionStage,
    ResolvedItem,
    SourceRecord,
)
from .cortex import (
    CortexCheckpointAssessment,
    CortexConfig,
    CortexError,
    CortexRunReport,
    JeevesCortex,
    RunCognitiveState,
)
from .epistemic_planning import (
    ActionCandidate,
    BeliefContribution,
    BeliefRequirement,
    CandidateAssessment,
    DecisionDisposition,
    DecisionPolicy,
    EpistemicDecision,
    EpistemicDecisionBridge,
    EpistemicDecisionError,
    ObservationOpportunity,
    RegretRow,
    StressKind,
    StressResult,
    UtilityInterval,
)
from .evidence import (
    Contradiction,
    EvidenceArtifact,
    EvidenceLedger,
    GroundingGate,
    GroundingPolicy,
    GroundingReport,
    LearningEvidenceBridge,
    evidence_from_payload,
)
from .evaluation import (
    AgentInvariantChecker,
    CalibrationEvaluator,
    CalibrationReport,
    CalibrationSample,
    EvalCase,
    EvalExpectation,
    EvalResult,
    EvaluationSuite,
    RunEvaluator,
)
from .frontier_control_plane import FrontierCognitiveControlPlane
from .memory import (
    ConsolidationCandidate,
    InMemoryStore,
    MemoryConsolidator,
    MemoryHit,
    MemoryManager,
    MemoryNamespace,
    MemoryPromotionPolicy,
    MemoryRecord,
    MemoryRetriever,
    RetrievalWeights,
)
from .memory_game import (
    CardHit as MemoryGameCardHit,
    IndexCardStore,
    InteractionCard,
    MemoryGameError,
    MemoryGameIndex,
    MemoryGamePolicy,
    RecallFeedback,
)
from .metacognition import (
    ActionSignals,
    BudgetPressure,
    CognitiveMode,
    EpistemicSignals,
    LoopDetector,
    LoopSignals,
    MetaController,
    MetaCognitionError,
    MetaDecision,
    MetaPolicy,
    MetaReason,
    MetaState,
    MetaStateBuilder,
    ModeScore,
    ProgressSignals,
    RiskSignals,
    action_signals,
    budget_pressure,
    epistemic_signals,
    progress_signals,
)
from .planning import (
    ModelPlanParser,
    PlanScheduler,
    PlanValidationReport,
    PlanValidator,
    ReplanDecision,
    ReplanPolicy,
)
from .policy import (
    CompositePolicy,
    ConfidencePolicy,
    ExecutionPolicy,
    PolicyContext,
    PolicyDecision,
)
from .probability_lenses import (
    AssessmentShape,
    ProbabilityAssessment,
    ProbabilityError,
    ProbabilityLens,
    ProbabilityWorkbench,
    calibrated_forecast_probability,
    dempster_shafer_support,
    empirical_game_probability,
    fair_dice_sum_probability,
    hazard_survival_probability,
    imprecise_probability,
    memory_retrieval_probability,
    possibility_necessity_support,
    transition_probability,
)
from .provider import (
    CircuitBreaker,
    CircuitState,
    DeterministicProvider,
    LegacyProviderAdapter,
    ModelCapabilities,
    ProviderRouter,
    RecordingProvider,
    RetryPolicy,
)
from .runtime import (
    AgentConfig,
    InMemoryCheckpointer,
    JeevesAgentRuntime,
    RunCheckpoint,
    RunInputs,
)
from .semantic_frontier import (
    FrontierLensRouter,
    FrontierSemanticRegistry,
    LensCompositionEngine,
    LensInteraction,
    LensInteractionKind,
    LensInteractionRule,
    SemanticComposition,
    default_interaction_rules,
    frontier_semantic_lenses,
)
from .semantic_lenses import (
    JuxtapositionAnalyzer,
    JuxtapositionSignal,
    LensFamily,
    LensSelection,
    ReadingStatus,
    SemanticFinding,
    SemanticLensRegistry,
    SemanticLensRouter,
    SemanticLensSpec,
    SemanticObservation,
    SemanticRole,
    TangentSeed,
)
from .semantic_prediction import (
    PredictionEvaluation,
    PredictionPolicy,
    PredictionStatus,
    SemanticForecast,
    SemanticPredictionLedger,
    SemanticPredictiveModel,
    log_odds_pool,
)
from .semantic_tangent_bridge import (
    SemanticRestartPacket,
    SemanticTangentBridge,
    TangentBridgePolicy,
)
from .tangent_graph import (
    ExplorationAxis,
    FrontierSelection,
    RestartContinuityBundle,
    TangentGraph,
    TangentNode,
    TangentState,
)
from .telemetry import MetricsRegistry, SpanRecord, TraceEvent, TraceLedger, Tracer
from .tools import (
    ArgumentRule,
    ToolExecutionContext,
    ToolExecutor,
    ToolGrant,
    ToolRegistry,
    ToolSpec,
    function_tool,
)
from .types import (
    AgentContractError,
    AgentPhase,
    AgentResult,
    Budget,
    Claim,
    Decision,
    EvidenceKind,
    EvidenceRef,
    Goal,
    MemoryKind,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    Plan,
    PlanStep,
    RiskTier,
    StepStatus,
    TerminationReason,
    ToolCall,
    ToolObservation,
    Usage,
    canonical_json,
    stable_fingerprint,
    stable_id,
)
from .uncertainty_frontier import (
    BayesianCategorical,
    DecisionCalibration,
    DependenceDiagnostics,
    FrontierLens,
    FrontierLensContract,
    FrontierLensRegistry,
    FrontierMeasurement,
    FrontierUncertaintyError,
    GameProbability,
    IdentificationDiagnostics,
    ImplementationStatus,
    InfluenceDiagnostics,
    MemoryUncertainty,
    MonteCarloDiagnostics,
    QuantityKind,
    SequentialInference,
    frontier_lens_contracts,
)
from .verification import (
    CheckSeverity,
    PredicateRegistry,
    PredicateRequest,
    PredicateSpec,
    StepVerifier,
    VerificationCheck,
    VerificationDirectiveParser,
    VerificationError,
    VerificationPolicy,
    VerificationReport,
    parse_advisory_json,
)
from .world_model import (
    BeliefConflict,
    BeliefEdge,
    BeliefGraph,
    BeliefRevision,
    BeliefState,
    BeliefUpdate,
    ContradictionGroup,
    CounterfactualProbe,
    EdgeKind,
    Hypothesis,
    HypothesisStatus,
    Proposition,
    RevisionKind,
    TransactionResult,
    WorldModel,
    WorldModelError,
    WorldSnapshot,
    binary_entropy,
    clamp_probability,
    proposition_from_artifact,
    reliability_to_likelihood_ratio,
)

__all__ = [name for name in globals() if not name.startswith("_")]
