"""Second-order cross-lens interaction rules for the Jeeves semantic plane.

These rules connect depth lenses to first-order and cross-plane lenses. They
encode how two readings reinforce, condition, conflict, reframe, or generate a
new tangent without converting either reading into evidence.
"""

from __future__ import annotations

from .semantic_frontier import LensInteractionKind, LensInteractionRule


def depth_interaction_rules() -> tuple[LensInteractionRule, ...]:
    return (
        LensInteractionRule(
            "continuity_space_graph", "observability_gap", LensInteractionKind.CONDITIONS,
            "Inferred scene geometry depends on which spatial states are actually observable across viewpoints.",
            "Which spatial relation is directly constrained, and which remains hidden behind presentation changes?",
            "Additional independent viewpoints should reduce the set of viable continuity-space graphs.",
            tangent_axis_hint="cinematic",
        ),
        LensInteractionRule(
            "color_motif_transition", "regime_switch_forecast", LensInteractionKind.REINFORCES,
            "A recurring visual motif can be treated as a candidate observable of an independently modeled latent regime.",
            "Does the motif predict regime membership out of sample rather than merely co-occur retrospectively?",
            "If the relation is stable, motif transitions should improve regime-state inference on later sequences.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "occlusion_reveal", "observability_gap", LensInteractionKind.REINFORCES,
            "Both lenses separate world state from temporary access to that state.",
            "Did the state change, or did only the observation function change?",
            "A pure access change predicts continuity in the hidden state across the reveal.",
            tangent_axis_hint="semantic",
        ),
        LensInteractionRule(
            "narrative_distance", "source_monitoring", LensInteractionKind.CONDITIONS,
            "Narrative closeness can alter apparent access without resolving the provenance of represented thoughts or memories.",
            "Which details are source-attributed, and which only feel immediate because discourse distance narrowed?",
            "Source errors should remain possible even in passages with high experiential immediacy.",
            tangent_axis_hint="literary",
        ),
        LensInteractionRule(
            "intertextual_dependency", "codebook_ambiguity", LensInteractionKind.REFRAMES,
            "An external text can act as one candidate decoding convention among several possible codebooks.",
            "Does the proposed source uniquely constrain the sign mapping, or are alternative codebooks equally supported?",
            "Removing access to the source should selectively degrade readings that genuinely depend on it.",
            tangent_axis_hint="semantic",
        ),
        LensInteractionRule(
            "motif_state_machine", "event_boundary_segmentation", LensInteractionKind.CONDITIONS,
            "Motif-state transitions may align with event boundaries rather than each recurrence constituting a new state.",
            "Do motif transitions coincide with independently detected event boundaries?",
            "State changes aligned to boundaries should generalize better than recurrence-only segmentation.",
            tangent_axis_hint="literary",
        ),
        LensInteractionRule(
            "economy_sink_source", "feedback_oscillation", LensInteractionKind.REINFORCES,
            "Adaptive sources and sinks can form a control loop that oscillates around a target economy state.",
            "Are source/sink adjustments reacting to lagged economy measurements strongly enough to overshoot?",
            "Reducing controller gain or delay should reduce oscillation if economy balancing is the mechanism.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "counterplay_window", "deadline_pressure", LensInteractionKind.CONDITIONS,
            "The practical value of counterplay depends on the remaining decision horizon.",
            "Does the nominal response window remain executable under the actor's actual time pressure?",
            "Shorter horizons should reduce successful counters even when the formal action remains available.",
            tangent_axis_hint="ludic",
        ),
        LensInteractionRule(
            "progression_gate", "path_dependence", LensInteractionKind.REINFORCES,
            "Hard prerequisites can convert earlier choices into later reachability constraints.",
            "Which prior branch created the prerequisite that now gates progression?",
            "Removing the prerequisite should erase the corresponding path dependence while preserving unrelated history effects.",
            tangent_axis_hint="ludic",
        ),
        LensInteractionRule(
            "causal_story_gap", "causal_direction_reversal", LensInteractionKind.REINFORCES,
            "Narrative coherence can hide the fact that reverse or common-cause models fit the same event order.",
            "What observation would distinguish the narrated causal direction from its reversal?",
            "A discriminating temporal or interventional observation should break the narrative equivalence.",
            tangent_axis_hint="causal",
        ),
        LensInteractionRule(
            "setup_payoff_latency", "forecast_horizon_decay", LensInteractionKind.CONDITIONS,
            "Long setup-payoff distances create a prediction horizon over which uncertainty about payoff should grow.",
            "How does payoff predictability decay as unresolved setups persist across more intervening events?",
            "Longer unresolved latency should widen the distribution over plausible payoff forms.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "branch_merge", "path_dependence", LensInteractionKind.CONFLICTS,
            "A declared narrative merge and persistent path dependence make competing claims about which branch state survives.",
            "Which branch-specific variables remain causally or narratively active after the merge point?",
            "True reconvergence predicts disappearance of branch-conditioned downstream differences.",
            tangent_axis_hint="temporal",
        ),
        LensInteractionRule(
            "sign_chain_drift", "representation_invariance", LensInteractionKind.CONFLICTS,
            "Sign-chain drift predicts semantic change while representation invariance predicts preserved meaning.",
            "Is the transformation certified semantics-preserving, or is interpretation actually changing across links?",
            "Verified equivalence should suppress drift on the preserved distinctions.",
            tangent_axis_hint="semantic",
        ),
        LensInteractionRule(
            "codebook_ambiguity", "scope_ambiguity", LensInteractionKind.ORTHOGONAL,
            "Lexical/symbolic decoding ambiguity and logical-scope ambiguity can coexist independently.",
            "Does fixing the codebook resolve the scope, or do multiple logical parses remain?",
            "Independent ambiguity sources should require separate disambiguating observations.",
            tangent_axis_hint="semantic",
        ),
        LensInteractionRule(
            "multimodal_conflict", "redundancy_synergy", LensInteractionKind.CONDITIONS,
            "Cross-modal disagreement changes whether combined channels are redundant, synergistic, or incompatible.",
            "Does joint access add information, duplicate it, or reveal a contradiction between channels?",
            "Ablation should distinguish unique, redundant, and conflicting modal contributions.",
            tangent_axis_hint="information",
        ),
        LensInteractionRule(
            "working_memory_load", "lossy_summary_budget", LensInteractionKind.CONDITIONS,
            "Compression can reduce active cognitive load while introducing downstream information loss.",
            "Which distinctions can be summarized away without harming the next reasoning operation?",
            "Task-aware compression should improve short-horizon performance until lost distinctions become decision-relevant.",
            tangent_axis_hint="memory",
        ),
        LensInteractionRule(
            "retrieval_competition", "memory_confidence_dissociation", LensInteractionKind.CONDITIONS,
            "Competitive retrieval can lower or distort recall without a proportional change in subjective confidence.",
            "Does cue-specific competition predict accuracy independently of confidence?",
            "More diagnostic cues should improve accuracy even when confidence changes little.",
            tangent_axis_hint="memory",
        ),
        LensInteractionRule(
            "belief_perseverance", "confirmation_search_bias", LensInteractionKind.REINFORCES,
            "Persistent beliefs and confirmatory search can form a self-maintaining epistemic loop.",
            "Does biased search reduce exposure to the evidence needed to revise the persistent belief?",
            "Forcing discriminating queries should increase revision when the loop is active.",
            tangent_axis_hint="adversarial",
        ),
        LensInteractionRule(
            "implicature_cancellation", "scalar_implicature", LensInteractionKind.CONDITIONS,
            "Cancellation is a discriminating test for whether a scalar inference is pragmatic rather than entailed.",
            "Can the stronger alternative be explicitly restored without contradiction?",
            "A defeasible scalar implicature should permit coherent cancellation in suitable contexts.",
            tangent_axis_hint="semantic",
        ),
        LensInteractionRule(
            "presupposition_failure", "common_knowledge_gap", LensInteractionKind.REINFORCES,
            "A presupposition can fail because a proposition is not mutually established at the required epistemic level.",
            "Is the missing background merely privately known, mutually known, or actually common knowledge?",
            "Public grounding should repair failures caused specifically by missing shared background.",
            tangent_axis_hint="social",
        ),
        LensInteractionRule(
            "framing_baseline_shift", "base_rate_neglect", LensInteractionKind.ORTHOGONAL,
            "Reference-point framing and prior-prevalence neglect alter judgments through different mechanisms.",
            "Does restoring the prior fix the judgment, or does changing the comparison baseline still shift evaluation?",
            "If both operate, correcting either alone leaves a residual bias signature.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "common_knowledge_gap", "coordination_threshold", LensInteractionKind.CONDITIONS,
            "Threshold coordination depends not only on participation beliefs but on what actors know about one another's beliefs.",
            "Would the same expected participation coordinate action if it were privately rather than publicly known?",
            "Public signals should trigger sharper threshold transitions when common knowledge is required.",
            tangent_axis_hint="social",
        ),
        LensInteractionRule(
            "network_diffusion", "causal_direction_reversal", LensInteractionKind.CONDITIONS,
            "Network clustering can make peer similarity look like contagion even when selection or reverse influence explains it.",
            "Does exposure precede adoption after controlling for network formation and shared environment?",
            "Exogenous exposure variation should strengthen a genuine diffusion interpretation.",
            tangent_axis_hint="causal",
        ),
        LensInteractionRule(
            "reputation_feedback", "status_cascade", LensInteractionKind.REINFORCES,
            "Status can amplify reputation, while reputation can recursively alter future status and exposure.",
            "Which direction of the status-reputation loop changes first under an external perturbation?",
            "Breaking visibility or status exposure should weaken cascade amplification if the feedback loop is active.",
            tangent_axis_hint="social",
        ),
        LensInteractionRule(
            "lag_structure", "leading_indicator", LensInteractionKind.CONDITIONS,
            "A leading indicator claim requires a stable lag structure rather than mere earlier timestamps.",
            "At which positive lag does out-of-sample predictive gain persist?",
            "A true leading relation should retain predictive value around a stable lag window.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "seasonality_alias", "residual_autocorrelation", LensInteractionKind.CONDITIONS,
            "Residual autocorrelation may reflect unmodeled seasonality rather than a new dynamic mechanism.",
            "Does seasonal adjustment remove the residual lag structure?",
            "If shared periodicity is responsible, residual autocorrelation should weaken after valid seasonal modeling.",
            tangent_axis_hint="temporal",
        ),
        LensInteractionRule(
            "retry_storm", "queue_backpressure", LensInteractionKind.REINFORCES,
            "Retries can amplify arrival rate precisely when service capacity is already constrained.",
            "What fraction of queue growth comes from original demand versus retry-generated demand?",
            "Backoff or retry budgets should reduce queue growth disproportionately if retries drive overload.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "cascading_failure_path", "fault_containment_boundary", LensInteractionKind.CONDITIONS,
            "A containment boundary is meaningful only relative to the propagation paths it is expected to block.",
            "Which candidate cascade edge crosses the claimed containment boundary?",
            "A real containment boundary should truncate matched injected failures at or before that edge.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "frontdoor_identification", "mediator_chain", LensInteractionKind.REINFORCES,
            "Front-door identification is a special mediated structure with stronger assumptions than generic mediation.",
            "Does the mediator satisfy full interception and the required confounding restrictions?",
            "When assumptions fail, generic mediation may remain descriptive while front-door identification fails.",
            tangent_axis_hint="causal",
        ),
        LensInteractionRule(
            "instrumental_variable_probe", "backdoor_confounding", LensInteractionKind.ORTHOGONAL,
            "An instrument and an adjustment set address confounding through different identifying strategies.",
            "Do both strategies target the same estimand under defensible but distinct assumptions?",
            "Agreement across valid strategies should improve robustness without making their assumptions interchangeable.",
            tangent_axis_hint="causal",
        ),
        LensInteractionRule(
            "interference_spillover", "network_diffusion", LensInteractionKind.CONDITIONS,
            "Network diffusion can be an interference mechanism when one unit's treatment changes another unit's exposure.",
            "Is the network edge transmitting treatment exposure, outcome behavior, or both?",
            "Cluster-aware exposure definitions should improve fit when spillovers are treatment-mediated.",
            tangent_axis_hint="causal",
        ),
        LensInteractionRule(
            "active_query_value", "value_of_information", LensInteractionKind.REINFORCES,
            "Active query selection operationalizes value-of-information reasoning over available probes.",
            "Does the ranked query change a decision-relevant posterior enough to justify its acquisition cost?",
            "Higher-ranked probes should yield larger realized decision value on average under a calibrated model.",
            tangent_axis_hint="information",
        ),
        LensInteractionRule(
            "lossy_summary_budget", "entropy_bottleneck", LensInteractionKind.REINFORCES,
            "A bounded summary is an explicit information bottleneck whose quality depends on which distinctions it preserves.",
            "Which task-relevant distinctions are collapsed by the summary representation?",
            "Increasing summary capacity should recover errors attributable to bottleneck loss.",
            tangent_axis_hint="information",
        ),
        LensInteractionRule(
            "uncertainty_budget", "epistemic_debt", LensInteractionKind.REINFORCES,
            "Epistemic debt identifies deferred uncertainty while an uncertainty budget prioritizes which debt to retire first.",
            "Which unresolved assumption has the highest decision sensitivity per verification cost?",
            "Targeted verification should reduce future revision cost more than uniform checking.",
            tangent_axis_hint="metacognitive",
        ),
        LensInteractionRule(
            "memoization_tradeoff", "cache_coherence_semantics", LensInteractionKind.CONDITIONS,
            "Memoization benefits depend on whether cached semantics remain valid under mutation and replication.",
            "Which key or invalidation event distinguishes reusable computation from stale cached state?",
            "Correct invalidation should retain latency gains while eliminating semantic stale-read failures.",
            tangent_axis_hint="computational",
        ),
        LensInteractionRule(
            "consistency_latency_tradeoff", "event_time_processing_time", LensInteractionKind.ORTHOGONAL,
            "Coordination latency and event/processing-time separation are distinct temporal sources of observed delay.",
            "Is the apparent lateness caused by coordination, ingestion order, or both?",
            "Instrumented clocks should separate coordination delay from late event arrival.",
            tangent_axis_hint="computational",
        ),
        LensInteractionRule(
            "scheduler_fairness", "queue_backpressure", LensInteractionKind.CONDITIONS,
            "Queue growth can coexist with fair scheduling, while unfair service allocation can concentrate latency in one class.",
            "Is service deficit global or concentrated in one runnable class relative to policy?",
            "Class-level service measurements should distinguish overload from starvation.",
            tangent_axis_hint="computational",
        ),
        LensInteractionRule(
            "confidence_resolution_curve", "calibration_gap_monitor", LensInteractionKind.CONDITIONS,
            "Good probability quality requires both reliable frequencies and useful separation between confidence levels.",
            "Are confidence bins calibrated, and do they meaningfully differ in empirical outcome rate?",
            "A system can improve resolution without worsening calibration when confidence ranking becomes more informative.",
            tangent_axis_hint="metacognitive",
        ),
        LensInteractionRule(
            "search_diversity_audit", "hypothesis_lockin", LensInteractionKind.CONFLICTS,
            "Structural hypothesis diversity is a direct countermeasure to premature single-model lock-in.",
            "Do proposed alternatives imply different mechanisms, evidence and falsifiers?",
            "Increasing structural diversity should expose new discriminating tests when lock-in was present.",
            tangent_axis_hint="adversarial",
        ),
        LensInteractionRule(
            "evidence_saturation", "mutual_information_gain", LensInteractionKind.REINFORCES,
            "Evidence saturation is the operational signature of declining marginal information gain from redundant observations.",
            "How much uncertainty does the next source remove conditional on evidence already collected?",
            "Redundant evidence should contribute diminishing conditional information gain.",
            tangent_axis_hint="information",
        ),
        LensInteractionRule(
            "calibration_drift", "concept_drift", LensInteractionKind.CONDITIONS,
            "Calibration can drift because the conditional target relation changed, but it can also drift without broad concept change.",
            "Did reliability degrade within stable predictor regions, or did the predictor-target mapping itself move?",
            "Recalibration alone should fix pure calibration drift but not structural concept drift.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "exchangeability_break", "prediction_interval_failure", LensInteractionKind.CONDITIONS,
            "Coverage failure may arise when the sampling symmetry required by the predictive interval is violated.",
            "Does coverage recover within approximately exchangeable strata or valid time blocks?",
            "Restoring the method's sampling assumptions should improve nominal coverage if exchangeability failure is causal.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "partial_identification_bounds", "dependence_structure", LensInteractionKind.REINFORCES,
            "Unknown dependence often turns a point probability into an identified set bounded by admissible joint structures.",
            "Which joint distributions remain compatible with the observed marginals and stated dependence constraints?",
            "Adding valid dependence restrictions should monotonically narrow the identified interval.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "target_leakage", "calibration_drift", LensInteractionKind.CONDITIONS,
            "Leakage can create apparently excellent historical calibration that collapses when the leaked feature disappears in deployment.",
            "Is the calibration change synchronized with loss of post-target or future-derived features?",
            "Removing leakage in retrospective evaluation should reproduce part of the deployment calibration degradation.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "temporal_validation_leak", "concept_drift", LensInteractionKind.CONFLICTS,
            "Future-to-past leakage can mimic robustness and hide genuine drift.",
            "Does the drift conclusion survive strict forward-only validation?",
            "If apparent stability came from leakage, forward validation should reveal stronger temporal degradation.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "residual_autocorrelation", "forecast_horizon_decay", LensInteractionKind.REINFORCES,
            "Unmodeled temporal dependence often compounds as forecast horizon grows.",
            "Does residual lag structure predict which horizons degrade fastest?",
            "Adding the missing temporal structure should reduce both residual autocorrelation and horizon-specific error growth.",
            tangent_axis_hint="predictive",
        ),
    )


def depth_interaction_keys() -> tuple[tuple[str, str], ...]:
    return tuple(rule.key for rule in depth_interaction_rules())
