"""Deep cross-plane semantic lenses for Jeeves.

This catalog fills reasoning families that were previously represented only by
other Jeeves subsystems (probability, causal inference, information, predictive
control, computation, and metacognition) but not by the unified semantic lens
registry.

Every lens here is an interpretive/query operator. It can organize observations,
generate hypotheses, propose discriminating tests, and emit forecasts. It cannot
create evidence, increase source trust, or establish causation on its own.
"""

from __future__ import annotations

from typing import Iterable, Sequence

from .semantic_extreme_lenses import LensMaturity, RareLensDefinition
from .semantic_lenses import LensFamily, SemanticLensRegistry, SemanticLensSpec, SemanticRole
from .types import AgentContractError, stable_fingerprint


PLANE_CATALOG_VERSION = "plane-v1"


def _p(
    key: str,
    family: LensFamily,
    role: SemanticRole,
    year: int,
    description: str,
    cues: Sequence[str],
    asks: Sequence[str],
    predicts: str,
    failure: str,
    lineage: Sequence[str],
    maturity: LensMaturity,
    warning: str,
    *,
    minimum: int = 1,
    pairwise: bool = False,
    sequential: bool = False,
) -> RareLensDefinition:
    return RareLensDefinition(
        SemanticLensSpec(
            key=key,
            family=family,
            role=role,
            lineage_year=year,
            description=description,
            activation_cues=tuple(cues),
            asks=tuple(asks),
            predicts=predicts,
            failure_mode=failure,
            minimum_observations=minimum,
            pairwise=pairwise,
            sequential=sequential,
            rare=True,
        ),
        tuple(lineage),
        maturity,
        warning,
    )


def plane_semantic_definitions() -> tuple[RareLensDefinition, ...]:
    """Return deep lenses spanning causal, information, computational,
    metacognitive, probability, and predictive reasoning planes.
    """

    return (
        # CAUSAL -----------------------------------------------------------------
        _p(
            "backdoor_confounding",
            LensFamily.CAUSAL,
            SemanticRole.CAUSAL_HINT,
            1935,
            "Ask whether a common cause can explain an observed association without a direct causal effect.",
            ("confound", "common cause", "association", "control", "adjust", "covariate"),
            ("Which variable could causally precede both the putative cause and outcome?",),
            "Conditioning on a valid sufficient adjustment set should materially change a confounded association.",
            "Treating any third variable as a confounder without temporal and causal justification.",
            ("causal inference", "back-door criterion"),
            LensMaturity.FORMAL,
            "Requires a defensible causal graph or equivalent assumptions; statistical adjustment alone does not prove sufficiency.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "collider_selection_bias",
            LensFamily.CAUSAL,
            SemanticRole.ADVERSARIAL_READING,
            1980,
            "Test whether conditioning on a shared effect can induce an association between otherwise independent causes.",
            ("collider", "selection", "conditioned", "admitted", "sample", "selected"),
            ("Was the sample or analysis restricted using a variable affected by both candidate causes?",),
            "Removing collider-based selection should weaken an induced association when the collider explanation is correct.",
            "Calling every selection mechanism collider bias.",
            ("causal graphs", "selection bias"),
            LensMaturity.FORMAL,
            "Needs explicit directionality assumptions; do not infer collider structure from correlation alone.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "mediator_chain",
            LensFamily.CAUSAL,
            SemanticRole.STRUCTURE,
            1980,
            "Separate total, direct, and mediated pathways through an intermediate state.",
            ("mediator", "through", "pathway", "intermediate", "direct effect", "indirect"),
            ("What intermediate variable carries part of the proposed effect?",),
            "Intervening on a genuine mediator should change part of the cause-outcome relation under the assumed model.",
            "Conditioning on a mediator and then describing the remaining association as the total effect.",
            ("mediation analysis", "causal inference"),
            LensMaturity.FORMAL,
            "Natural direct/indirect effects require strong counterfactual assumptions; keep them explicit.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "intervention_invariance",
            LensFamily.CAUSAL,
            SemanticRole.PREDICTION,
            1995,
            "Prefer mechanisms whose conditional behavior remains stable under relevant interventions or environments.",
            ("intervention", "invariant", "environment", "stable", "mechanism", "do"),
            ("Which conditional relation should remain stable if it reflects a mechanism rather than a spurious correlation?",),
            "A mechanistic relation should transfer more stably across targeted interventions than a spurious proxy relation.",
            "Assuming invariance across environments that alter the mechanism itself.",
            ("structural causal models", "invariant prediction"),
            LensMaturity.FORMAL,
            "Define the intervention class and mechanism boundary before treating stability as causal evidence.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "counterfactual_consistency",
            LensFamily.CAUSAL,
            SemanticRole.ADVERSARIAL_READING,
            1970,
            "Check whether counterfactual claims are compatible with observed treatment and outcome under consistency assumptions.",
            ("counterfactual", "would have", "if", "treatment", "consistency", "potential outcome"),
            ("When observed treatment matches the counterfactual treatment, does the claimed potential outcome agree with observation?",),
            "Violations of consistency should surface as contradictions between observed and asserted same-treatment potential outcomes.",
            "Treating consistency as empirically verified rather than an identification assumption.",
            ("potential outcomes", "causal consistency"),
            LensMaturity.FORMAL,
            "Consistency links notation to observed outcomes under assumptions; it does not identify missing counterfactuals.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "causal_direction_reversal",
            LensFamily.CAUSAL,
            SemanticRole.ADVERSARIAL_READING,
            1960,
            "Actively test the reversed causal direction instead of accepting the first directional story.",
            ("reverse causality", "direction", "cause", "effect", "leads to", "drives"),
            ("Could the proposed outcome plausibly precede and influence the proposed cause?",),
            "Temporal or interventional evidence should discriminate the forward and reverse models.",
            "Treating temporal order alone as sufficient proof of direction.",
            ("causal discovery", "reverse causation"),
            LensMaturity.MIXED,
            "Use as a competing model generator; direction requires independent temporal, interventional, or structural support.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "mechanism_transport",
            LensFamily.CAUSAL,
            SemanticRole.PREDICTION,
            2010,
            "Separate a mechanism that may transport across domains from population-specific distributions that may not.",
            ("transport", "domain", "population", "mechanism", "generalize", "external validity"),
            ("Which parts of the causal system are invariant across source and target populations?",),
            "Predictions based on transported invariant mechanisms should degrade less than predictions tied to shifted population marginals.",
            "Assuming a mechanism is invariant simply because variables share names.",
            ("transportability", "external validity"),
            LensMaturity.FORMAL,
            "Transport requires explicit selection or invariance assumptions; never infer it from source performance alone.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "selection_on_treatment_effect",
            LensFamily.CAUSAL,
            SemanticRole.ADVERSARIAL_READING,
            2000,
            "Check whether enrollment, exposure, or retention depends on expected or realized treatment response.",
            ("retention", "dropout", "responder", "selection", "treated", "survivor"),
            ("Could inclusion in the analyzed sample depend on treatment response or its predictors?",),
            "Correcting response-dependent selection should shift estimated effects when selective retention is material.",
            "Assuming all dropout is outcome-dependent.",
            ("missing data", "causal selection", "survivorship bias"),
            LensMaturity.MIXED,
            "Requires a model of the selection process; sensitivity analysis is preferable to unsupported correction.",
            minimum=3,
            sequential=True,
        ),

        # INFORMATION -------------------------------------------------------------
        _p(
            "mutual_information_gain",
            LensFamily.INFORMATION,
            SemanticRole.PREDICTION,
            1948,
            "Ask how much an observation is expected to reduce uncertainty about a target rather than whether it is merely correlated.",
            ("information", "mutual information", "entropy", "uncertainty", "observe", "signal"),
            ("Which candidate observation most reduces uncertainty about the target state?",),
            "Higher-information observations should reduce posterior uncertainty more on average than lower-information alternatives.",
            "Treating mutual information as causal relevance or practical value.",
            ("information theory", "Bayesian experimental design"),
            LensMaturity.FORMAL,
            "Information depends on the modeled joint distribution and does not by itself encode utility or causality.",
        ),
        _p(
            "entropy_bottleneck",
            LensFamily.INFORMATION,
            SemanticRole.STRUCTURE,
            1948,
            "Locate a representation or channel that compresses many upstream distinctions into too few downstream states.",
            ("bottleneck", "entropy", "compress", "channel", "state", "loss"),
            ("Which distinctions are collapsed at this representation boundary?",),
            "Increasing representational capacity should recover distinctions that were systematically lost at the bottleneck.",
            "Calling every small representation a harmful bottleneck.",
            ("information theory", "representation learning"),
            LensMaturity.MIXED,
            "Compression can be desirable; evaluate task-relevant loss rather than raw dimensionality.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "redundancy_synergy",
            LensFamily.INFORMATION,
            SemanticRole.STRUCTURE,
            2010,
            "Distinguish duplicated information from information available only through combining multiple signals.",
            ("redundant", "synergy", "joint", "combined", "signals", "together"),
            ("Does the pair reveal target information unavailable from either signal alone?",),
            "A synergistic pair should outperform the best single signal beyond what redundant overlap predicts.",
            "Equating non-additive model performance with formal information synergy.",
            ("partial information decomposition", "multivariate information"),
            LensMaturity.MIXED,
            "Formal synergy depends on a chosen decomposition; report the convention and compare alternatives.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "rate_distortion_tradeoff",
            LensFamily.INFORMATION,
            SemanticRole.META,
            1959,
            "Model compression as a tradeoff between representation rate and task-relevant distortion.",
            ("rate", "distortion", "compression", "lossy", "quality", "bandwidth"),
            ("Which errors are acceptable at a given representation or communication budget?",),
            "Tighter rate budgets should increase distortion unless the representation contains avoidable redundancy.",
            "Treating one scalar distortion function as universally meaningful.",
            ("rate-distortion theory", "lossy compression"),
            LensMaturity.FORMAL,
            "The result is conditional on the distortion measure; make task costs explicit.",
        ),
        _p(
            "minimum_description_length",
            LensFamily.INFORMATION,
            SemanticRole.META,
            1978,
            "Compare explanations by combined model complexity and residual data description length.",
            ("description length", "mdl", "compress", "complexity", "residual", "simple"),
            ("Does a more complex explanation reduce residual complexity enough to justify itself?",),
            "A genuinely better compact model should reduce total code length on held-out or future data.",
            "Equating shortest description under one coding scheme with truth.",
            ("minimum description length", "algorithmic information"),
            LensMaturity.FORMAL,
            "Coding choices matter; MDL is a model-selection principle, not a truth oracle.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "surprisal_shift",
            LensFamily.INFORMATION,
            SemanticRole.PREDICTION,
            1948,
            "Track abrupt increases in negative log probability as potential regime, model, or context shifts.",
            ("surprisal", "unexpected", "unlikely", "shock", "probability", "shift"),
            ("Did the observation become surprising under a previously adequate predictive distribution?",),
            "Persistent surprisal elevation predicts model mismatch or regime change more strongly than isolated outliers.",
            "Treating every low-probability event as evidence that the model is wrong.",
            ("information theory", "change detection"),
            LensMaturity.MIXED,
            "Rare events occur under correct models; use sequences and calibration, not one surprise.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "channel_capacity_constraint",
            LensFamily.INFORMATION,
            SemanticRole.STRUCTURE,
            1948,
            "Treat communication failure as potentially arising from finite channel capacity relative to source rate.",
            ("capacity", "bandwidth", "throughput", "channel", "rate", "noise"),
            ("Is the effective information rate exceeding what the channel can reliably carry?",),
            "Sustained source rate above effective capacity predicts rising loss, delay, or decoding error.",
            "Conflating raw transport throughput with information-theoretic capacity.",
            ("channel coding theorem", "communications"),
            LensMaturity.FORMAL,
            "Capacity claims require a channel model; operational throughput is only a proxy.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "value_of_information",
            LensFamily.INFORMATION,
            SemanticRole.PLAYER_MODEL,
            1950,
            "Measure an observation by expected decision improvement, not information volume alone.",
            ("value of information", "observe", "decision", "worth knowing", "probe", "test"),
            ("Would the decision change often enough, and by enough utility, to justify acquiring this information?",),
            "High-value probes should improve expected decision utility after accounting for acquisition cost.",
            "Assuming more information is always beneficial.",
            ("decision theory", "Bayesian value of information"),
            LensMaturity.FORMAL,
            "Requires explicit decisions, utilities, and observation costs.",
        ),

        # COMPUTATIONAL -----------------------------------------------------------
        _p(
            "state_space_explosion",
            LensFamily.COMPUTATIONAL,
            SemanticRole.STRUCTURE,
            1970,
            "Identify combinatorial growth in reachable or candidate states as the primary computational pressure.",
            ("state space", "combinatorial", "explode", "branching", "search", "exponential"),
            ("Which independent dimensions multiply the number of states or branches?",),
            "Constraining a dominant branching dimension should reduce search cost superlinearly when it drives combinatorial growth.",
            "Calling any slow search state-space explosion.",
            ("complexity theory", "search"),
            LensMaturity.FORMAL,
            "Establish growth with input size; runtime on one instance is not complexity.",
        ),
        _p(
            "algorithmic_complexity_budget",
            LensFamily.COMPUTATIONAL,
            SemanticRole.META,
            1965,
            "Relate reasoning depth to asymptotic time, space, and approximation tradeoffs.",
            ("complexity", "big o", "runtime", "memory", "polynomial", "exponential"),
            ("Which resource grows fastest with problem size, and what approximation changes that scaling?",),
            "Increasing input size should reveal the predicted growth regime if the complexity model is appropriate.",
            "Inferring asymptotic complexity from a few benchmark points.",
            ("computational complexity", "algorithm analysis"),
            LensMaturity.FORMAL,
            "Separate asymptotic statements from hardware-dependent constant factors.",
        ),
        _p(
            "concurrency_interleaving",
            LensFamily.COMPUTATIONAL,
            SemanticRole.ADVERSARIAL_READING,
            1965,
            "Treat concurrent behavior as a set of possible interleavings rather than one observed order.",
            ("race", "concurrent", "thread", "interleave", "async", "ordering"),
            ("Which alternative scheduling order could expose a different visible state?",),
            "A race-dependent defect should reproduce under at least one admissible interleaving and disappear when ordering is constrained.",
            "Inventing impossible schedules that violate happens-before constraints.",
            ("concurrency theory", "happens-before"),
            LensMaturity.FORMAL,
            "Respect synchronization and memory-model constraints when constructing counterexamples.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "idempotence_boundary",
            LensFamily.COMPUTATIONAL,
            SemanticRole.STRUCTURE,
            1970,
            "Check whether repeated execution is guaranteed to preserve the same externally visible state.",
            ("idempotent", "retry", "duplicate", "repeat", "side effect", "exactly once"),
            ("What state changes on the second identical application?",),
            "A truly idempotent operation should converge after the first successful application under the stated preconditions.",
            "Calling an operation idempotent because duplicate effects are usually hidden.",
            ("algebraic semantics", "distributed systems"),
            LensMaturity.FORMAL,
            "Define the observable state and failure model; retries across partial failures may not be idempotent.",
            minimum=2,
            sequential=True,
        ),
        _p(
            "transactional_atomicity",
            LensFamily.COMPUTATIONAL,
            SemanticRole.ADVERSARIAL_READING,
            1980,
            "Test whether a multi-step update exposes partial state when atomicity is assumed.",
            ("transaction", "atomic", "partial", "commit", "rollback", "half"),
            ("Can any observer see a state corresponding to only a strict subset of the intended update?",),
            "Injected interruption should reveal either full rollback or complete commit if atomicity is real.",
            "Confusing atomicity with isolation, durability, or consistency.",
            ("transaction processing", "ACID"),
            LensMaturity.FORMAL,
            "State which transactional property is being tested; ACID dimensions are distinct.",
            minimum=2,
            sequential=True,
        ),
        _p(
            "representation_invariance",
            LensFamily.COMPUTATIONAL,
            SemanticRole.META,
            1950,
            "Prefer conclusions that survive semantics-preserving changes in representation.",
            ("representation", "encoding", "serialization", "rename", "equivalent", "invariant"),
            ("Would the conclusion remain if the same structure were encoded differently?",),
            "A semantics-level conclusion should remain stable under verified representation-preserving transforms.",
            "Assuming two representations are semantics-preserving without validation.",
            ("formal semantics", "compiler correctness"),
            LensMaturity.FORMAL,
            "Requires an explicit equivalence relation between representations.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "abstraction_leak",
            LensFamily.COMPUTATIONAL,
            SemanticRole.ADVERSARIAL_READING,
            2000,
            "Look for lower-layer constraints that surface through an abstraction advertised as hiding them.",
            ("abstraction", "leak", "underlying", "implementation detail", "layer", "hidden"),
            ("Which lower-layer property unexpectedly changes behavior visible at the higher layer?",),
            "Changing the implicated lower-layer property should change supposedly abstracted behavior if the leak is real.",
            "Treating any performance difference as a semantic abstraction leak.",
            ("software abstraction", "systems design"),
            LensMaturity.HEURISTIC,
            "Separate semantic leaks from expected performance sensitivity.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "cache_coherence_semantics",
            LensFamily.COMPUTATIONAL,
            SemanticRole.STRUCTURE,
            1970,
            "Treat divergent cached views as a state-consistency problem rather than independent facts.",
            ("cache", "stale", "coherence", "invalidate", "replica", "fresh"),
            ("Which reader can observe which version, and what invalidation or consistency rule connects them?",),
            "Tightening coherence or invalidation should reduce stale-read anomalies at a measurable coordination cost.",
            "Treating every disagreement as cache staleness.",
            ("cache coherence", "distributed consistency"),
            LensMaturity.FORMAL,
            "Name the consistency model and version relation before classifying a stale read.",
            minimum=2,
            pairwise=True,
        ),

        # METACOGNITIVE -----------------------------------------------------------
        _p(
            "calibration_gap_monitor",
            LensFamily.METACOGNITIVE,
            SemanticRole.META,
            1980,
            "Compare stated confidence with observed accuracy rather than treating confidence as self-validating.",
            ("confidence", "calibration", "accuracy", "overconfident", "underconfident", "probability"),
            ("Across comparable cases, does predicted confidence match empirical success frequency?",),
            "A persistent calibration gap should recur across enough cases to exceed sampling variation.",
            "Diagnosing miscalibration from a handful of outcomes.",
            ("forecast calibration", "metacognition"),
            LensMaturity.EMPIRICAL,
            "Calibration is population- and task-specific; do not transfer blindly.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "hypothesis_lockin",
            LensFamily.METACOGNITIVE,
            SemanticRole.ADVERSARIAL_READING,
            1960,
            "Detect search that keeps elaborating one hypothesis while failing to generate serious alternatives.",
            ("lock in", "same theory", "alternative", "hypothesis", "stuck", "assume"),
            ("How many genuinely distinct explanations have survived explicit comparison?",),
            "Forcing generation of structurally different alternatives should expose omitted discriminating tests when lock-in is present.",
            "Calling stable convergence lock-in after alternatives were already eliminated by evidence.",
            ("confirmation bias", "scientific reasoning"),
            LensMaturity.EMPIRICAL,
            "Use only when alternatives were not adequately tested.",
        ),
        _p(
            "confirmation_search_bias",
            LensFamily.METACOGNITIVE,
            SemanticRole.ADVERSARIAL_READING,
            1960,
            "Check whether information search disproportionately seeks expected confirmations over discriminating falsifiers.",
            ("confirm", "support", "evidence for", "falsify", "search", "test"),
            ("Would this query return useful information if the favored hypothesis were false?",),
            "Replacing confirmatory queries with discriminating queries should increase the rate of hypothesis revision when bias is present.",
            "Assuming every supportive test is biased.",
            ("confirmation bias", "hypothesis testing"),
            LensMaturity.EMPIRICAL,
            "A good test can support a hypothesis; the issue is asymmetric search design.",
        ),
        _p(
            "stopping_rule_sensitivity",
            LensFamily.METACOGNITIVE,
            SemanticRole.META,
            1940,
            "Ask whether the conclusion depends on when evidence collection was stopped.",
            ("stop", "until", "enough", "optional stopping", "continue", "threshold"),
            ("Would a different admissible stopping rule materially change the inferential interpretation?",),
            "Methods sensitive to optional stopping should show changed error behavior under adaptive continuation.",
            "Assuming all sequential analysis is invalid.",
            ("sequential analysis", "optional stopping"),
            LensMaturity.FORMAL,
            "Some methods are designed for optional stopping; evaluate the actual inferential contract.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "epistemic_debt",
            LensFamily.METACOGNITIVE,
            SemanticRole.META,
            2020,
            "Track accumulated unresolved assumptions, weak validations, and deferred falsification work as a reasoning liability.",
            ("assumption", "todo", "unverified", "later", "debt", "uncertain"),
            ("Which current conclusions rely on deferred validation that has not been discharged?",),
            "Systems with rising epistemic debt should show increasing revision cost or contradiction rate when deferred assumptions are finally tested.",
            "Turning every uncertainty into blocking debt.",
            ("technical debt analogy", "epistemic risk management"),
            LensMaturity.HEURISTIC,
            "Use as a bookkeeping heuristic; debt magnitude is not a scientific quantity without an explicit metric.",
            minimum=2,
            sequential=True,
        ),
        _p(
            "reasoning_loop_detection",
            LensFamily.METACOGNITIVE,
            SemanticRole.META,
            2020,
            "Detect repeated reasoning states that add little new evidence, hypotheses, or discrimination.",
            ("loop", "repeat", "again", "same", "no progress", "cycling"),
            ("What materially new state was produced by the last reasoning cycle?",),
            "A genuine loop should show high state similarity with low information gain across successive cycles.",
            "Calling deliberate iterative refinement a loop merely because topics recur.",
            ("metareasoning", "loop detection"),
            LensMaturity.HEURISTIC,
            "Measure novelty and progress; repetition alone is insufficient.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "search_satisficing",
            LensFamily.METACOGNITIVE,
            SemanticRole.PLAYER_MODEL,
            1956,
            "Model search that stops after finding an option above an aspiration threshold rather than a global optimum.",
            ("good enough", "satisfice", "first acceptable", "search", "threshold", "stop"),
            ("What aspiration threshold explains the point at which search stopped?",),
            "Raising the aspiration threshold should lengthen search and improve selected quality until search costs dominate.",
            "Calling any non-optimal choice satisficing.",
            ("bounded rationality", "satisficing"),
            LensMaturity.MIXED,
            "Infer thresholds from repeated behavior or explicit constraints, not from one choice.",
            minimum=2,
            sequential=True,
        ),
        _p(
            "model_uncertainty_separation",
            LensFamily.METACOGNITIVE,
            SemanticRole.META,
            2000,
            "Separate uncertainty inside a model from uncertainty about which model class should be trusted.",
            ("model uncertainty", "epistemic", "aleatoric", "which model", "structural", "uncertain"),
            ("How much uncertainty remains if the model class were known, versus uncertainty over model structure itself?",),
            "Model-class averaging or alternative-model stress tests should widen uncertainty when structural uncertainty is material.",
            "Relabeling every residual error as model uncertainty.",
            ("Bayesian model uncertainty", "uncertainty decomposition"),
            LensMaturity.FORMAL,
            "The decomposition depends on the model set under consideration; omitted models remain unrepresented.",
        ),

        # PROBABILITY -------------------------------------------------------------
        _p(
            "base_rate_neglect",
            LensFamily.PROBABILITY,
            SemanticRole.ADVERSARIAL_READING,
            1974,
            "Check whether a diagnostic signal is being interpreted without the prior prevalence of the target condition.",
            ("base rate", "prevalence", "prior", "diagnostic", "positive", "rare"),
            ("What posterior follows when the actual prior prevalence is included?",),
            "In low-prevalence settings, including the base rate should often reduce posterior probability relative to likelihood-only intuition.",
            "Assuming every high posterior is base-rate neglect.",
            ("Bayes theorem", "judgment under uncertainty"),
            LensMaturity.FORMAL,
            "Needs valid likelihoods and prevalence estimates; the lens detects a missing prior, not a correct posterior by itself.",
        ),
        _p(
            "tail_risk_mass",
            LensFamily.PROBABILITY,
            SemanticRole.PREDICTION,
            1920,
            "Inspect probability mass and consequence in the tail rather than relying on mean behavior.",
            ("tail", "extreme", "rare", "worst case", "quantile", "cvar"),
            ("How much probability and loss lie beyond the decision-relevant threshold?",),
            "Heavy-tail regimes should produce more threshold exceedances than light-tail models with similar means.",
            "Treating any large loss as evidence of a heavy tail.",
            ("extreme value theory", "risk measures"),
            LensMaturity.FORMAL,
            "Tail inference is data-hungry; distinguish empirical exceedance from extrapolated tail models.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "dependence_structure",
            LensFamily.PROBABILITY,
            SemanticRole.STRUCTURE,
            1950,
            "Model joint risk through dependence rather than multiplying marginal probabilities as if independent.",
            ("dependent", "correlated", "joint", "copula", "together", "independent"),
            ("What dependence assumptions connect the marginal events?",),
            "Joint-event frequency should deviate systematically from the independence product when dependence is material.",
            "Equating linear correlation with complete dependence structure.",
            ("joint probability", "copulas"),
            LensMaturity.FORMAL,
            "Specify or bound dependence; marginals alone generally do not identify joint risk.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "sequential_evidence_accumulation",
            LensFamily.PROBABILITY,
            SemanticRole.PREDICTION,
            1940,
            "Treat evidence gathered over time as a sequential process with explicit error control.",
            ("sequential", "evidence", "update", "likelihood", "e-value", "monitor"),
            ("What quantity remains valid under repeated peeking or continuation?",),
            "A valid sequential evidence process should preserve its stated error or martingale guarantees under the allowed stopping rule.",
            "Applying fixed-sample significance thresholds repeatedly.",
            ("sequential analysis", "martingales", "e-values"),
            LensMaturity.FORMAL,
            "Validity depends on the exact process and filtration assumptions.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "posterior_predictive_check",
            LensFamily.PROBABILITY,
            SemanticRole.ADVERSARIAL_READING,
            1980,
            "Test whether data simulated from the fitted model reproduce important observed features.",
            ("posterior predictive", "simulate", "replicate", "model check", "fit", "residual"),
            ("Which discrepancy statistic exposes behavior the fitted model fails to reproduce?",),
            "A misspecified model should repeatedly fail to reproduce at least one targeted observed feature.",
            "Treating posterior predictive p-values like ordinary frequentist p-values or proof of model truth.",
            ("Bayesian model checking", "posterior predictive"),
            LensMaturity.FORMAL,
            "Model checks diagnose chosen discrepancies; passing them does not validate untested structure.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "model_mixture_uncertainty",
            LensFamily.PROBABILITY,
            SemanticRole.META,
            1990,
            "Represent uncertainty across several plausible probabilistic models instead of selecting one silently.",
            ("mixture", "ensemble", "models", "weights", "average", "uncertainty"),
            ("How sensitive is the target probability to plausible model weights or model choice?",),
            "Mixture uncertainty should widen when plausible component models disagree strongly.",
            "Averaging incompatible models into false consensus.",
            ("Bayesian model averaging", "mixture models"),
            LensMaturity.FORMAL,
            "Keep component predictions visible; a pooled number does not erase structural disagreement.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "rare_event_denominator",
            LensFamily.PROBABILITY,
            SemanticRole.ADVERSARIAL_READING,
            1900,
            "Check whether dramatic counts are interpreted without the exposure denominator needed for a rate.",
            ("rate", "denominator", "per", "exposure", "count", "rare event"),
            ("What population-time or opportunity denominator generated this count?",),
            "Normalizing by exposure should change comparisons when groups differ materially in opportunity count.",
            "Assuming a denominator resolves all selection and reporting biases.",
            ("epidemiology", "rate estimation"),
            LensMaturity.FORMAL,
            "Choose the denominator that matches the causal or descriptive estimand.",
        ),
        _p(
            "aleatoric_epistemic_split",
            LensFamily.PROBABILITY,
            SemanticRole.META,
            2010,
            "Separate irreducible outcome variability from reducible uncertainty about parameters, mechanisms, or models.",
            ("aleatoric", "epistemic", "noise", "uncertainty", "model", "data"),
            ("What uncertainty would remain with unlimited data under the same data-generating process?",),
            "Additional informative data should primarily reduce epistemic, not irreducible aleatoric, uncertainty.",
            "Treating residual error after training as purely aleatoric.",
            ("Bayesian uncertainty", "machine learning uncertainty"),
            LensMaturity.MIXED,
            "The decomposition is model-dependent and can misclassify omitted structure as noise.",
        ),

        # PREDICTIVE --------------------------------------------------------------
        _p(
            "concept_drift",
            LensFamily.PREDICTIVE,
            SemanticRole.PREDICTION,
            2000,
            "Detect change in the relationship between predictors and target rather than only a change in predictor frequency.",
            ("concept drift", "relationship changed", "mapping", "target", "degrade", "drift"),
            ("Did the conditional target relation change after controlling for predictor distribution?",),
            "A concept-drift model predicts degraded conditional accuracy even when covariate coverage is maintained.",
            "Calling any performance decline concept drift.",
            ("online learning", "dataset shift"),
            LensMaturity.MIXED,
            "Separate target relation drift from covariate, label, and measurement shift.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "covariate_shift",
            LensFamily.PREDICTIVE,
            SemanticRole.STRUCTURE,
            1990,
            "Model predictor-distribution shift while the conditional target mechanism is approximately stable.",
            ("covariate shift", "distribution", "input", "population", "shift", "domain"),
            ("Did input frequencies change while the conditional outcome model remain approximately invariant?",),
            "Reweighting to the target covariate distribution should improve target estimates when covariate shift assumptions hold.",
            "Assuming conditional invariance without testing available overlap and labels.",
            ("domain adaptation", "covariate shift"),
            LensMaturity.FORMAL,
            "Importance weighting fails under poor support overlap or conditional drift.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "forecast_horizon_decay",
            LensFamily.PREDICTIVE,
            SemanticRole.PREDICTION,
            1950,
            "Model predictive information as decaying with horizon rather than treating near and far forecasts equally.",
            ("horizon", "long term", "short term", "forecast", "ahead", "decay"),
            ("How does error or calibration change as forecast horizon increases?",),
            "Forecast accuracy should generally degrade or uncertainty widen with horizon in partially observed dynamic systems.",
            "Assuming monotonic degradation in deterministic or strongly seasonal systems.",
            ("time-series forecasting", "predictability horizon"),
            LensMaturity.EMPIRICAL,
            "Estimate horizon effects in the actual process; do not impose them mechanically.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "leading_indicator",
            LensFamily.PREDICTIVE,
            SemanticRole.PREDICTION,
            1950,
            "Treat a variable as useful when it systematically changes before a target, while preserving noncausal alternatives.",
            ("leading", "indicator", "before", "predicts", "advance", "signal"),
            ("Does the indicator improve out-of-sample forecasts beyond target history and plausible confounders?",),
            "A genuine leading indicator should improve future-target prediction at a stable positive lag.",
            "Calling temporal precedence a causal mechanism.",
            ("forecasting", "leading indicators"),
            LensMaturity.EMPIRICAL,
            "Out-of-sample lagged predictive gain is required; causality remains separate.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "lagging_indicator",
            LensFamily.PREDICTIVE,
            SemanticRole.CONTEXTUALIZATION,
            1950,
            "Recognize variables that confirm a regime after it has changed rather than predict the change itself.",
            ("lagging", "after", "confirm", "indicator", "delayed", "rear view"),
            ("Does this signal mostly move after the target transition?",),
            "A lagging indicator should have stronger explanatory alignment at positive target-to-indicator lags than predictive alignment in reverse.",
            "Dismissing useful confirmation signals because they are not leading predictors.",
            ("economic indicators", "time-series analysis"),
            LensMaturity.EMPIRICAL,
            "Use lagging indicators for state confirmation, not anticipatory claims.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "regime_switch_forecast",
            LensFamily.PREDICTIVE,
            SemanticRole.STRUCTURE,
            1989,
            "Model forecasts as conditional on latent regimes with different dynamics.",
            ("regime", "switch", "state", "bull", "bear", "phase", "hidden"),
            ("Do observations cluster into persistent states with materially different transition or emission behavior?",),
            "A valid regime model should improve held-out likelihood or forecast calibration and show persistent state occupancy.",
            "Overfitting noise with too many latent regimes.",
            ("Markov switching", "hidden-state forecasting"),
            LensMaturity.FORMAL,
            "Regime labels are model states, not objective named realities unless externally validated.",
            minimum=3,
            sequential=True,
        ),
        _p(
            "forecast_reconciliation",
            LensFamily.PREDICTIVE,
            SemanticRole.STRUCTURE,
            2010,
            "Reconcile forecasts that must obey aggregation or accounting constraints across a hierarchy.",
            ("reconcile", "hierarchy", "aggregate", "total", "subgroup", "coherent forecast"),
            ("Which linear or accounting constraints must all component forecasts satisfy simultaneously?",),
            "Reconciled forecasts should satisfy hierarchy constraints and can improve aggregate consistency without hiding component error.",
            "Treating coherence as predictive accuracy.",
            ("hierarchical forecasting", "forecast reconciliation"),
            LensMaturity.FORMAL,
            "Constraint satisfaction is not evidence that the underlying forecasts are well calibrated.",
            minimum=2,
            pairwise=True,
        ),
        _p(
            "prediction_interval_failure",
            LensFamily.PREDICTIVE,
            SemanticRole.ADVERSARIAL_READING,
            1950,
            "Audit whether empirical coverage of predictive intervals matches their nominal coverage.",
            ("interval", "coverage", "prediction band", "outside", "uncertainty", "confidence"),
            ("Across exchangeable or otherwise valid cases, what fraction of outcomes fall inside the advertised interval?",),
            "Persistent undercoverage or overcoverage should appear as a systematic empirical coverage gap.",
            "Evaluating coverage on a selectively reported subset.",
            ("predictive inference", "conformal prediction", "forecast calibration"),
            LensMaturity.EMPIRICAL,
            "Coverage guarantees depend on sampling assumptions and the evaluation population.",
            minimum=3,
            sequential=True,
        ),
    )


def plane_semantic_specs() -> tuple[SemanticLensSpec, ...]:
    return tuple(item.spec for item in plane_semantic_definitions())


def register_plane_lenses(
    registry: SemanticLensRegistry,
    *,
    ignore_existing: bool = True,
) -> SemanticLensRegistry:
    if not isinstance(registry, SemanticLensRegistry):
        raise TypeError("registry must be SemanticLensRegistry")
    existing = {item.key for item in registry.all()}
    for definition in plane_semantic_definitions():
        if definition.spec.key in existing:
            if ignore_existing:
                continue
            raise AgentContractError(f"duplicate plane semantic lens: {definition.spec.key}")
        registry.register(definition.spec)
        existing.add(definition.spec.key)
    return registry


def plane_definitions_by_family(
    definitions: Iterable[RareLensDefinition] | None = None,
) -> dict[LensFamily, tuple[RareLensDefinition, ...]]:
    items = tuple(definitions or plane_semantic_definitions())
    grouped: dict[LensFamily, list[RareLensDefinition]] = {}
    for item in items:
        grouped.setdefault(item.spec.family, []).append(item)
    return {
        family: tuple(sorted(values, key=lambda item: (item.spec.lineage_year, item.spec.key)))
        for family, values in grouped.items()
    }


def plane_catalog_fingerprint() -> str:
    return stable_fingerprint(
        {
            "version": PLANE_CATALOG_VERSION,
            "definitions": [
                {
                    "key": item.spec.key,
                    "family": item.spec.family.value,
                    "role": item.spec.role.value,
                    "year": item.spec.lineage_year,
                    "lineage": item.lineage,
                    "maturity": item.maturity.value,
                    "warning": item.transfer_warning,
                }
                for item in plane_semantic_definitions()
            ],
        }
    )
