"""Extreme semantic lenses for perpendicular Jeeves reasoning.

This module expands the semantic catalog with rare operators drawn from film
editing/cognition, narratology/pragmatics, game studies/game theory, and memory
science. Lenses are hypothesis generators, never evidence generators.

Every definition carries intellectual lineage, epistemic maturity, a transfer
warning, a falsifiable prediction, and a named failure mode. This deliberately
does not pretend that film/literary/game studies form one canonical taxonomy.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Iterable, Sequence

from .semantic_lenses import LensFamily, SemanticLensRegistry, SemanticLensSpec, SemanticRole
from .types import AgentContractError, bounded_text


class LensMaturity(str, Enum):
    FORMAL = "formal"
    EMPIRICAL = "empirical"
    MIXED = "mixed"
    CONCEPTUAL = "conceptual"
    HEURISTIC = "heuristic"


@dataclass(frozen=True, slots=True)
class RareLensDefinition:
    spec: SemanticLensSpec
    lineage: tuple[str, ...]
    maturity: LensMaturity
    transfer_warning: str

    def __post_init__(self) -> None:
        if not isinstance(self.spec, SemanticLensSpec):
            raise AgentContractError("spec must be SemanticLensSpec")
        lineage = tuple(str(item).strip() for item in self.lineage if str(item).strip())
        if not lineage:
            raise AgentContractError("rare lens requires lineage")
        object.__setattr__(self, "lineage", lineage)
        if not isinstance(self.maturity, LensMaturity):
            object.__setattr__(self, "maturity", LensMaturity(str(self.maturity)))
        object.__setattr__(self, "transfer_warning", bounded_text("transfer_warning", self.transfer_warning, maximum=4096))


def _d(
    key: str, family: LensFamily, role: SemanticRole, year: int, description: str,
    cues: Sequence[str], asks: Sequence[str], predicts: str, failure: str,
    lineage: Sequence[str], maturity: LensMaturity, warning: str, *,
    minimum: int = 1, pairwise: bool = False, sequential: bool = False,
) -> RareLensDefinition:
    spec = SemanticLensSpec(
        key=key, family=family, role=role, lineage_year=year, description=description,
        activation_cues=tuple(cues), asks=tuple(asks), predicts=predicts, failure_mode=failure,
        minimum_observations=minimum, pairwise=pairwise, sequential=sequential, rare=True,
    )
    return RareLensDefinition(spec, tuple(lineage), maturity, warning)


def rare_semantic_definitions() -> tuple[RareLensDefinition, ...]:
    """Return rare, orthogonal semantic operators with explicit scientific limits."""
    return (
        # Film/editing/cognition.
        _d("shot_reverse_shot_suture", LensFamily.FILM, SemanticRole.PERSPECTIVE, 1910,
           "Alternating viewpoints can construct an inferred relational space and observer position.",
           ("shot","reverse","look","dialogue","view","cut"),
           ("What relation is inferred only from alternation?",),
           "Stable alternation predicts a persistent relation between represented viewpoints.",
           "Inferring literal geometry from editing convention alone.",
           ("continuity editing","suture theory","film cognition"), LensMaturity.MIXED,
           "Viewer construction is not proof of physical layout.", minimum=2, pairwise=True),
        _d("graphic_match", LensFamily.FILM, SemanticRole.CONTRAST, 1920,
           "A cut can bind scenes through shared shape, composition, movement, or texture.",
           ("match","shape","composition","similar","cut","graphic"),
           ("Which visual invariant survives the cut?",),
           "Repeated graphic invariants predict a learned association across otherwise separate contexts.",
           "Treating accidental resemblance as authored semantic linkage.",
           ("match editing","visual similarity"), LensMaturity.CONCEPTUAL,
           "Require repetition or independent support before assigning intent.", minimum=2, pairwise=True),
        _d("jump_cut_discontinuity", LensFamily.FILM, SemanticRole.STRUCTURE, 1960,
           "A discontinuous cut within a similar setup can expose omitted time or instability.",
           ("jump","cut","discontinuous","skip","same","sudden"),
           ("Which state changed without an explicit transition?",),
           "A verified jump predicts a hidden temporal/state transition or deliberate continuity violation.",
           "Calling ordinary temporal compression a meaningful rupture.",
           ("New Wave editing","continuity violation"), LensMaturity.CONCEPTUAL,
           "Separate measurable discontinuity from claims about artistic intention.", minimum=2, pairwise=True),
        _d("crosscut_parallel_action", LensFamily.FILM, SemanticRole.STRUCTURE, 1908,
           "Alternation between event streams can imply simultaneity, comparison, or convergence.",
           ("meanwhile","crosscut","parallel","alternating","simultaneous","scene"),
           ("Are the streams simultaneous, compared, or causally converging?",),
           "Converging crosscut streams predict a later shared event or explicit temporal relation.",
           "Assuming simultaneity whenever scenes alternate.",
           ("parallel editing","narrative time"), LensMaturity.MIXED,
           "Temporal linkage stays uncertain until independently anchored.", minimum=3, sequential=True),
        _d("screen_direction_violation", LensFamily.FILM, SemanticRole.ADVERSARIAL_READING, 1915,
           "A reversal of established screen direction may signal viewpoint change or continuity break.",
           ("direction","left","right","axis","reverse","orientation"),
           ("Did the reference frame change, or did continuity break?",),
           "Repeated reversal predicts either a new reference frame or sustained disorientation.",
           "Assuming the 180-degree convention is universal or intentional.",
           ("continuity editing","180-degree system"), LensMaturity.HEURISTIC,
           "Do not infer world geometry without reference-frame evidence.", minimum=2, sequential=True),
        _d("point_of_audition", LensFamily.FILM, SemanticRole.PERSPECTIVE, 1970,
           "Sound may be filtered through a character-relative listening position.",
           ("muffled","hears","audio","sound","subjective","listening"),
           ("Whose auditory access best explains the sound transformation?",),
           "A character-relative mix predicts later divergence from independently presented sound.",
           "Treating stylistic sound design as literal hearing state.",
           ("film sound theory","auditory perspective"), LensMaturity.CONCEPTUAL,
           "Require independent cues before treating audio as character perception."),
        _d("diegetic_nondiegetic_bleed", LensFamily.FILM, SemanticRole.META, 1980,
           "Sound can cross the boundary between represented-world source and external score.",
           ("diegetic","music","score","radio","source","transition"),
           ("Did the sound ontology change, or only the mix?",),
           "Boundary-crossing sound predicts a reframing of who can hear or act on the information.",
           "Assuming every musical transition changes diegetic status.",
           ("diegesis","film sound"), LensMaturity.CONCEPTUAL,
           "Keep world-audible and audience-only information separate.", minimum=2, sequential=True),
        _d("unreliable_image", LensFamily.FILM, SemanticRole.ADVERSARIAL_READING, 1940,
           "The image may be memory-, dream-, hallucination-, or viewpoint-conditioned.",
           ("dream","memory","vision","hallucination","subjective","unreliable"),
           ("What independent observation distinguishes world state from presented mental state?",),
           "Viewpoint-conditioned imagery predicts systematic divergence from independent observations.",
           "Explaining contradictions away by declaring inconvenient images subjective.",
           ("subjective cinema","unreliable narration"), LensMaturity.MIXED,
           "Preserve both world-state and presentation-state hypotheses.", minimum=2),
        _d("rashomon_variance", LensFamily.FILM, SemanticRole.PERSPECTIVE, 1950,
           "Conflicting accounts of one event can be source-conditioned reconstructions rather than one average story.",
           ("versions","accounts","different","remember","witness","same event"),
           ("Which observations are shared, and which vary by source?",),
           "Stable source-specific differences predict future disagreement along similar latent dimensions.",
           "Assuming disagreement implies deliberate deception.",
           ("Rashomon effect","source memory","testimony"), LensMaturity.MIXED,
           "Model source and retrieval conditions; never average testimony into false consensus.", minimum=2, pairwise=True),
        _d("suspense_surprise_information_gap", LensFamily.FILM, SemanticRole.PREDICTION, 1940,
           "Tension structure differs when an observer knows a hazard before a character.",
           ("suspense","surprise","knows","hazard","secret","danger"),
           ("Who knows the critical state, and when?",),
           "Observer-character information asymmetry predicts different attention and action expectations.",
           "Treating a storytelling heuristic as a universal psychological law.",
           ("suspense theory","information asymmetry"), LensMaturity.HEURISTIC,
           "Use for information-state modeling, not guaranteed affect."),
        _d("macguffin_goal_displacement", LensFamily.FILM, SemanticRole.META, 1930,
           "A pursued object may organize behavior while its intrinsic properties matter little to structure.",
           ("object","pursue","secret","package","goal","want"),
           ("Would the interaction graph remain similar if the object were replaced?",),
           "If it is mainly a goal token, substitution preserves much of the action structure.",
           "Dismissing an actually causal object as interchangeable.",
           ("thriller construction","goal tokens"), LensMaturity.HEURISTIC,
           "Test substitution invariance before applying the lens."),
        _d("split_screen_parallelism", LensFamily.FILM, SemanticRole.STRUCTURE, 1960,
           "Simultaneous frames expose relations without relying on sequential montage.",
           ("split","screen","simultaneous","parallel","multiple","frame"),
           ("What relation becomes visible because states are co-present?",),
           "Co-present streams predict comparison or coordination effects that survive reorderings.",
           "Assuming simultaneous display implies simultaneous world time.",
           ("split-screen cinema","parallel presentation"), LensMaturity.CONCEPTUAL,
           "Separate presentation simultaneity from event simultaneity.", minimum=2),

        # Narratology, pragmatics, rhetoric, semiotics.
        _d("narratee_model", LensFamily.NARRATIVE, SemanticRole.PERSPECTIVE, 1970,
           "Narration can imply an addressee with knowledge distinct from the real reader.",
           ("dear","reader","you know","as you","tell","address"),
           ("What does the discourse assume its addressee already knows?",),
           "Repeated assumptions predict an implicit addressee model that constrains omitted explanation.",
           "Equating the narratee with the actual audience.",
           ("narratology","narratee"), LensMaturity.CONCEPTUAL,
           "Treat implied audience state as a discourse hypothesis."),
        _d("implied_author_distance", LensFamily.LITERATURE, SemanticRole.META, 1961,
           "Separate narrator commitments from a higher-order organizing stance inferred across a work.",
           ("narrator","irony","author","distance","contradiction","stance"),
           ("Does the work systematically undermine the narrator evaluation?",),
           "Persistent narrator/work divergence predicts stable higher-order ironic distance.",
           "Attributing a precise real-author belief to textual structure.",
           ("Booth","unreliable narration","implied author"), LensMaturity.CONCEPTUAL,
           "Never identify inferred textual stance with the historical author psychology.", minimum=2),
        _d("paratext_frame", LensFamily.LITERATURE, SemanticRole.CONTEXTUALIZATION, 1987,
           "Titles, epigraphs, prefaces, menus, covers, and metadata can alter priors before primary content.",
           ("title","preface","epigraph","menu","cover","metadata"),
           ("What expectation was introduced outside the primary content?",),
           "Changing paratext predicts a shift in interpretation while primary content stays fixed.",
           "Treating framing metadata as authoritative evidence about content.",
           ("Genette","paratext"), LensMaturity.MIXED,
           "Model framing influence separately from truth of the framed claim.", pairwise=True),
        _d("heteroglossia_register", LensFamily.LITERATURE, SemanticRole.PERSPECTIVE, 1934,
           "Distinct social registers can carry partially independent value systems.",
           ("voice","register","dialect","jargon","formal","slang"),
           ("Which assumptions travel with this register rather than the proposition alone?",),
           "Register changes predict shifts in stance, audience alignment, or social positioning.",
           "Essentializing a social group from stylized language.",
           ("Bakhtin","heteroglossia","sociolinguistics"), LensMaturity.MIXED,
           "Do not infer protected identity or stable personality from register alone."),
        _d("presupposition_projection", LensFamily.RHETORIC, SemanticRole.INTERPRETATION, 1970,
           "Some propositions are backgrounded as accepted and can survive negation or questions.",
           ("again","stop","realize","even","still","regret"),
           ("What proposition is being treated as common ground?",),
           "If a presupposition projects, reformulations alter foreground content while retaining the background assumption.",
           "Treating every implication as a linguistic presupposition.",
           ("formal pragmatics","presupposition"), LensMaturity.FORMAL,
           "Validate trigger behavior before updating discourse state."),
        _d("scalar_implicature", LensFamily.RHETORIC, SemanticRole.INTERPRETATION, 1975,
           "A weaker expression can pragmatically suggest that a stronger alternative was not warranted.",
           ("some","many","possible","or","sometimes","may"),
           ("Which stronger alternative was available but not asserted?",),
           "In cooperative contexts, weaker scalar terms predict rejection or uncertainty about stronger alternatives.",
           "Turning defeasible pragmatic inference into logical entailment.",
           ("Grice","scalar implicature"), LensMaturity.EMPIRICAL,
           "Keep implicatures defeasible and context-sensitive."),
        _d("deictic_anchor", LensFamily.RHETORIC, SemanticRole.PERSPECTIVE, 1930,
           "Here, now, this, that, I, and you depend on an anchoring context.",
           ("here","there","now","then","this","that","you","i"),
           ("Whose location, time, and discourse center resolves the expression?",),
           "A correct deictic anchor predicts consistent referents across nearby utterances.",
           "Resolving indexicals from model-local context when speaker context differs.",
           ("deixis","indexical semantics"), LensMaturity.FORMAL,
           "Require explicit speaker/time/place anchors when consequences matter."),
        _d("scope_ambiguity", LensFamily.RHETORIC, SemanticRole.ADVERSARIAL_READING, 1950,
           "Quantifiers, negation, modality, and coordination can admit multiple logical scopes.",
           ("all","every","some","not","must","may","or"),
           ("Which scope readings produce different truth conditions?",),
           "A discriminating continuation should support one scope structure over alternatives.",
           "Choosing the convenient parse while hiding ambiguity.",
           ("formal semantics","quantifier scope"), LensMaturity.FORMAL,
           "Preserve multiple parses until context resolves them."),
        _d("conceptual_blending", LensFamily.COGNITIVE, SemanticRole.INTERPRETATION, 1990,
           "Features from distinct mental spaces can combine into an emergent blended representation.",
           ("blend","like","as if","hybrid","metaphor","mix"),
           ("Which properties come from each input, and which emerge only in the blend?",),
           "Successful blends predict constrained relation transfer rather than all source properties.",
           "Allowing metaphorical transfer to import arbitrary facts.",
           ("conceptual blending","cognitive semantics"), LensMaturity.CONCEPTUAL,
           "Audit every projected property; metaphor is not entailment.", minimum=2, pairwise=True),
        _d("metonymic_contiguity", LensFamily.SEMIOTIC, SemanticRole.INTERPRETATION, 1890,
           "A related entity can stand for another through contextual association rather than resemblance.",
           ("stands for","associated","place","institution","container","maker"),
           ("Is the relation similarity, causal trace, part-whole, or contiguity?",),
           "Repeated substitutions predict a stable contextual mapping within a discourse community.",
           "Reading arbitrary association as conventional metonymy.",
           ("rhetoric","cognitive linguistics","metonymy"), LensMaturity.MIXED,
           "Treat mapping as context- and community-dependent."),
        _d("synecdoche_part_whole", LensFamily.SEMIOTIC, SemanticRole.STRUCTURE, 350,
           "A part can stand for a whole, or a whole for a relevant part.",
           ("part","whole","hands","wheels","faces","body"),
           ("Which mereological relation licenses the substitution?",),
           "Stable part-whole mapping predicts consistent substitution in later references.",
           "Confusing correlation with part-whole structure.",
           ("classical rhetoric","mereology"), LensMaturity.CONCEPTUAL,
           "Verify the part-whole relation independently."),
        _d("chiasmus_reversal", LensFamily.RHETORIC, SemanticRole.STRUCTURE, 350,
           "AB/BA reversal can make symmetry, inversion, or contrast structurally salient.",
           ("reverse","inverted","again","but","from","to"),
           ("Does reversed order change the relation or merely decorate it?",),
           "Repeated structural reversal predicts emphasis on reciprocity, inversion, or contrast.",
           "Forcing chiastic structure onto coincidental word order.",
           ("classical rhetoric","chiasmus"), LensMaturity.HEURISTIC,
           "Require a clear structural mapping.", minimum=2, pairwise=True),
        _d("reader_horizon_of_expectation", LensFamily.LITERATURE, SemanticRole.CONTEXTUALIZATION, 1967,
           "Interpretation depends partly on genre and historical expectations available to a reader community.",
           ("expected","genre","audience","convention","historical","surprise"),
           ("Which prior convention makes this expected or transgressive?",),
           "Convention-aware models predict different interpretations across reader populations or eras.",
           "Inventing a homogeneous audience or projecting current norms backward.",
           ("reception theory","horizon of expectations"), LensMaturity.CONCEPTUAL,
           "Population and period must be explicit before predictive use."),
        _d("palimpsest_layering", LensFamily.LITERATURE, SemanticRole.CONTEXTUALIZATION, 1980,
           "Later texts or states can overwrite while retaining traces of earlier structures.",
           ("layer","rewrite","overwrite","trace","version","older"),
           ("Which older structure remains recoverable under the new one?",),
           "Residual distinctive patterns predict provenance from prior versions.",
           "Hallucinating ancestry from generic similarity.",
           ("intertextuality","palimpsest","version history"), LensMaturity.HEURISTIC,
           "Require version, citation, or distinctive structural evidence.", minimum=2),

        # Games and interactive systems.
        _d("possibility_space", LensFamily.GAME, SemanticRole.SYSTEM, 2000,
           "A rule system defines reachable states and actions, not merely a scripted sequence.",
           ("possible","reachable","rule","state","action","space"),
           ("Which states are reachable, forbidden, irreversible, or only theoretical?",),
           "Rule changes predict topology changes in the reachable state space before preference is modeled.",
           "Confusing designed possibility with empirically likely play.",
           ("game design","state-space search"), LensMaturity.FORMAL,
           "Keep reachability separate from policy likelihood."),
        _d("procedural_rhetoric", LensFamily.GAME, SemanticRole.INTERPRETATION, 2007,
           "Rules can make an argument by constraining and rewarding modeled processes.",
           ("rule","system","argument","reward","simulate","procedure"),
           ("What claim is implied by what the system makes easy, hard, rewarded, or impossible?",),
           "If a procedural claim is stable, altering the relevant rule should alter the inferred argument.",
           "Treating every mechanic as an intentional moral or political claim.",
           ("procedural rhetoric","simulation studies"), LensMaturity.CONCEPTUAL,
           "Use as an interpretive hypothesis and test rule dependence."),
        _d("information_set", LensFamily.GAME, SemanticRole.PERSPECTIVE, 1944,
           "Decision quality must be evaluated from states an actor cannot distinguish at decision time.",
           ("hidden","information","knows","observe","private","state"),
           ("Which world states are indistinguishable to the acting player?",),
           "Policies should be invariant inside an information set unless extra information is available.",
           "Judging a move using hidden information revealed later.",
           ("game theory","extensive-form games"), LensMaturity.FORMAL,
           "Explicitly separate true state from information set."),
        _d("signaling_bluff", LensFamily.GAME, SemanticRole.PLAYER_MODEL, 1944,
           "Actions can be chosen partly for what they cause others to believe about hidden type or state.",
           ("signal","bluff","tell","represent","believe","hidden"),
           ("What belief update is this action trying to induce?",),
           "Costly or type-dependent signals predict different posterior shifts than cheap talk.",
           "Assuming every surprising action is strategic deception.",
           ("signaling games","Bayesian games"), LensMaturity.FORMAL,
           "Require incentives and type-dependent action models before inferring bluffing."),
        _d("mixed_strategy_randomization", LensFamily.GAME, SemanticRole.PLAYER_MODEL, 1944,
           "Intentional randomization can make an actor harder to exploit when pure strategies are predictable.",
           ("random","mix","unpredictable","strategy","frequency","counter"),
           ("Would a deterministic policy be exploitable by a best response?",),
           "Action frequencies near a valid equilibrium mix predict reduced exploitability versus a fixed pure action.",
           "Reading noisy or inconsistent behavior as optimal randomization.",
           ("minimax","mixed strategies","Nash equilibrium"), LensMaturity.FORMAL,
           "Estimate incentives and best responses before labeling equilibrium play.", minimum=3, sequential=True),
        _d("regret_matching", LensFamily.GAME, SemanticRole.PREDICTION, 2000,
           "Action probabilities can adapt according to accumulated counterfactual regret.",
           ("regret","missed","counterfactual","strategy","adapt","switch"),
           ("Which unchosen action would have performed better under observed history?",),
           "Persistent positive regret predicts increased probability of the regretted action in later rounds.",
           "Computing regret with outcomes the player could not observe or estimate.",
           ("regret minimization","counterfactual regret minimization"), LensMaturity.FORMAL,
           "Define available information for counterfactual value estimation.", minimum=3, sequential=True),
        _d("tempo_initiative", LensFamily.GAME, SemanticRole.PREDICTION, 1950,
           "Some actions trade immediate value for control over the timing and response structure of later actions.",
           ("tempo","initiative","force","respond","turn","pressure"),
           ("Who chooses questions, and who spends actions answering them?",),
           "Initiative-retaining actions predict constrained opponent response sets in the near horizon.",
           "Treating speed or aggression as initiative without response constraints.",
           ("chess strategy","turn-based analysis"), LensMaturity.HEURISTIC,
           "Operationalize initiative through reachable responses.", minimum=2, sequential=True),
        _d("cooldown_window", LensFamily.GAME, SemanticRole.PREDICTION, 1990,
           "Temporary action unavailability creates periodic vulnerability and opportunity windows.",
           ("cooldown","ready","seconds","window","ability","unavailable"),
           ("Which actions become conditionally optimal before versus after readiness resets?",),
           "Known cooldown state predicts local shifts in action and counter-action probabilities.",
           "Assuming nominal cooldown equals actual availability under resets or resource constraints.",
           ("real-time game design","temporal control"), LensMaturity.FORMAL,
           "Track actual state transitions rather than UI labels.", sequential=True),
        _d("telegraph_readability", LensFamily.GAME, SemanticRole.PREDICTION, 1980,
           "Pre-action cues can expose a future state early enough for response.",
           ("telegraph","windup","cue","animation","warning","read"),
           ("How much predictive information does the cue provide before commitment?",),
           "Reliable telegraphs predict improved anticipatory response accuracy with experience.",
           "Confusing post-hoc recognition with usable pre-action information.",
           ("combat readability","signal detection"), LensMaturity.EMPIRICAL,
           "Measure cue lead time and discriminability.", minimum=3, sequential=True),
        _d("combo_synergy", LensFamily.GAME, SemanticRole.CAUSAL_HINT, 1990,
           "A sequence or set of mechanics can have value beyond the sum of isolated components.",
           ("combo","synergy","together","sequence","chain","interaction"),
           ("Does joint performance exceed an additive baseline under controlled state?",),
           "True synergy predicts a positive interaction term across repeated paired trials.",
           "Calling ordinary additive accumulation synergy.",
           ("combinatorial design","interaction effects"), LensMaturity.FORMAL,
           "Compare against an explicit additive or independent baseline.", minimum=2, pairwise=True),
        _d("sequence_break", LensFamily.GAME, SemanticRole.ADVERSARIAL_READING, 1980,
           "Players may reach later states without satisfying an intended prerequisite chain.",
           ("skip","sequence","break","shortcut","bypass","early"),
           ("Which prerequisite invariant was bypassed while reachability remained valid?",),
           "A reproducible sequence break predicts alternate reachable paths or missing state guards.",
           "Calling an intended alternate route an exploit.",
           ("speedrunning","state machines"), LensMaturity.EMPIRICAL,
           "Verify intended constraints separately from observed reachability.", minimum=2, sequential=True),
        _d("permadeath_irreversibility", LensFamily.GAME, SemanticRole.PREDICTION, 1980,
           "Irreversible loss changes rational value of information and downside-risk controls.",
           ("permadeath","irreversible","one life","cannot undo","loss","reset"),
           ("Which transitions remove future states permanently?",),
           "Higher irreversibility predicts greater decision value for information under fixed utility.",
           "Assuming all players are equally risk-averse.",
           ("decision theory","roguelike design"), LensMaturity.FORMAL,
           "Utility and reset cost must be explicit."),
        _d("roguelike_meta_learning", LensFamily.GAME, SemanticRole.PREDICTION, 1980,
           "Repeated runs can improve policy even when each run resets world state.",
           ("run","reset","seed","learn","again","roguelike"),
           ("What knowledge transfers across resets even when world state does not?",),
           "Across-run experience predicts faster recognition and policy adaptation despite reset.",
           "Attributing progression unlocks to player learning or vice versa.",
           ("procedural generation","meta-learning","roguelikes"), LensMaturity.MIXED,
           "Separate learner state, account progression, and random-seed effects.", minimum=3, sequential=True),
        _d("deckbuilding_interaction_graph", LensFamily.GAME, SemanticRole.SYSTEM, 1993,
           "Card value depends on an interaction graph, draw probabilities, and opportunity cost.",
           ("deck","card","draw","synergy","combo","curve"),
           ("Which cards alter the marginal value or availability of which others?",),
           "A learned interaction graph predicts context-dependent card value and non-additive deck performance.",
           "Ranking cards independently of composition and draw process.",
           ("collectible card games","hypergeometric probability","synergy graphs"), LensMaturity.FORMAL,
           "Model draw distribution and deck constraints explicitly.", minimum=2),
        _d("hidden_role_belief", LensFamily.GAME, SemanticRole.PLAYER_MODEL, 1986,
           "Social-deduction actions update a posterior over hidden roles under strategic observation generation.",
           ("role","traitor","hidden","vote","suspect","claim"),
           ("Which observations discriminate role hypotheses after accounting for strategy?",),
           "Role-consistent evidence predicts posterior shifts while cheap talk receives lower weight.",
           "Treating accusation frequency or confidence as role evidence by itself.",
           ("Bayesian games","social deduction"), LensMaturity.MIXED,
           "Model strategic evidence generation; naive independence assumptions are unsafe.", minimum=2, sequential=True),
        _d("mechanic_as_verb", LensFamily.GAME, SemanticRole.SYSTEM, 2000,
           "Represent a mechanic by the state-transforming verb it affords rather than theme or asset.",
           ("jump","trade","build","shoot","talk","craft","verb"),
           ("What typed state transformation does the player enact?",),
           "Shared verb-level transition structure predicts similar tactical affordances across themes.",
           "Collapsing superficially similar verbs with different transition rules.",
           ("game design grammar","affordances"), LensMaturity.HEURISTIC,
           "Ground verbs in explicit preconditions and effects."),
        _d("reward_hacking_gap", LensFamily.GAME, SemanticRole.ADVERSARIAL_READING, 2010,
           "Optimizing implemented reward can diverge from the intended objective.",
           ("reward","score","exploit","objective","metric","cheese"),
           ("Which action raises the metric while degrading intended outcome?",),
           "A proxy gap predicts increasingly extreme proxy optimization under stronger optimization pressure.",
           "Labeling legitimate unexpected strategy as reward hacking.",
           ("specification gaming","Goodhart effects"), LensMaturity.EMPIRICAL,
           "Define intended objective independently before diagnosing proxy failure.", minimum=2, sequential=True),

        # Memory science as semantic/retrieval lenses.
        _d("encoding_specificity", LensFamily.COGNITIVE, SemanticRole.PREDICTION, 1973,
           "Retrieval improves when cues overlap with information encoded during acquisition.",
           ("cue","context","remember","same","encoded","recall"),
           ("Which acquisition-time cues are present at retrieval?",),
           "Cue reinstatement predicts higher retrieval probability for otherwise matched traces.",
           "Assuming every shared token is an effective retrieval cue.",
           ("encoding specificity","cue-dependent memory"), LensMaturity.EMPIRICAL,
           "Retrieval probability is not factual truth."),
        _d("context_reinstatement", LensFamily.COGNITIVE, SemanticRole.PREDICTION, 1970,
           "Reinstating environmental or mental context can improve access to context-bound memories.",
           ("context","same place","state","recreate","return","remember"),
           ("Which context features can be reinstated without contaminating the target?",),
           "Diagnostic context reinstatement predicts improved recall versus mismatched context.",
           "Confusing accessibility with factual accuracy.",
           ("context-dependent memory","retrieval cues"), LensMaturity.EMPIRICAL,
           "Score accessibility and correctness separately."),
        _d("retrieval_induced_forgetting", LensFamily.COGNITIVE, SemanticRole.META, 1994,
           "Selective retrieval practice can reduce later access to competing related items.",
           ("practice","recall","compete","forget","related","retrieval"),
           ("Which competitors share the cue but are repeatedly not selected?",),
           "Selective practice predicts reduced later accessibility of competing traces.",
           "Treating low retrieval strength as erasure or falsity.",
           ("retrieval-induced forgetting","memory competition"), LensMaturity.EMPIRICAL,
           "Never delete durable context solely because retrieval strength falls.", minimum=3, sequential=True),
        _d("proactive_retroactive_interference", LensFamily.COGNITIVE, SemanticRole.ADVERSARIAL_READING, 1890,
           "Old learning can interfere with new retrieval and new learning with old retrieval.",
           ("old","new","interfere","confuse","similar","overwrite"),
           ("Is failure better explained by weak storage or competition from similar traces?",),
           "Increasing similarity and competition predicts more retrieval error without requiring trace loss.",
           "Assuming any memory error is interference.",
           ("interference theory","memory competition"), LensMaturity.EMPIRICAL,
           "Require evidence of competing traces.", minimum=2),
        _d("source_monitoring", LensFamily.COGNITIVE, SemanticRole.ADVERSARIAL_READING, 1993,
           "Remembered content and remembered source are separable judgments.",
           ("where","source","heard","read","remember","who said"),
           ("Is the proposition recalled more strongly than its provenance?",),
           "Low source confidence predicts provenance substitution even when content recognition stays high.",
           "Treating vividness or familiarity as provenance evidence.",
           ("source-monitoring framework","metamemory"), LensMaturity.EMPIRICAL,
           "Preserve source confidence independently from content confidence."),
        _d("event_boundary_segmentation", LensFamily.COGNITIVE, SemanticRole.STRUCTURE, 2000,
           "Prediction error and context changes can segment continuous experience into events.",
           ("event","boundary","suddenly","changed","transition","new scene"),
           ("Which latent state changed enough to justify a new event representation?",),
           "Persistent multi-feature context shifts predict chunk boundaries and altered cross-boundary recall.",
           "Segmenting on every surprise and destroying long-range continuity.",
           ("event segmentation theory","predictive processing"), LensMaturity.EMPIRICAL,
           "Require persistent multi-feature change.", minimum=2, sequential=True),
        _d("chunking_compression", LensFamily.COGNITIVE, SemanticRole.STRUCTURE, 1956,
           "Frequently co-occurring elements can become a higher-level chunk for faster retrieval.",
           ("chunk","group","pattern","together","sequence","compress"),
           ("Does grouping improve prediction or retrieval without hiding important variance?",),
           "Stable chunks predict faster retrieval and better next-item prediction for learned sequences.",
           "Premature compression that masks exceptions or causal structure.",
           ("chunking","working memory","compression"), LensMaturity.EMPIRICAL,
           "Retain reversible links to constituent cards.", minimum=3, sequential=True),
        _d("desirable_difficulty", LensFamily.COGNITIVE, SemanticRole.META, 1994,
           "Harder but successful retrieval can improve later retention more than effortless restudy.",
           ("difficult","effort","test","practice","recall","spacing"),
           ("Was retrieval effortful yet successful, and did later retention improve?",),
           "Moderately difficult successful retrieval predicts stronger later access than immediate passive re-exposure.",
           "Making tasks arbitrarily hard or treating failure as beneficial.",
           ("desirable difficulties","testing effect","spacing"), LensMaturity.EMPIRICAL,
           "Optimize later retention under bounded error, not difficulty itself.", minimum=3, sequential=True),
        _d("prediction_error_reconsolidation", LensFamily.COGNITIVE, SemanticRole.META, 2000,
           "Retrieved memory followed by discrepancy can become update-sensitive under some conditions.",
           ("prediction error","update","memory","changed","surprise","reconsolidation"),
           ("Was the old trace reactivated, contradicted, and then updated rather than supplemented?",),
           "Reactivated traces plus discrepancy predict later integration of new information in suitable regimes.",
           "Assuming every correction literally rewrites a biological memory trace.",
           ("memory reconsolidation","prediction error"), LensMaturity.MIXED,
           "In software, implement as versioned revision with prior provenance retained.", minimum=2, sequential=True),
    )


def rare_semantic_specs() -> tuple[SemanticLensSpec, ...]:
    return tuple(item.spec for item in rare_semantic_definitions())


def register_rare_lenses(registry: SemanticLensRegistry, *, ignore_existing: bool = True) -> SemanticLensRegistry:
    if not isinstance(registry, SemanticLensRegistry):
        raise TypeError("registry must be SemanticLensRegistry")
    existing = {item.key for item in registry.all()}
    for definition in rare_semantic_definitions():
        if definition.spec.key in existing:
            if ignore_existing:
                continue
            raise AgentContractError(f"duplicate rare semantic lens: {definition.spec.key}")
        registry.register(definition.spec)
        existing.add(definition.spec.key)
    return registry


def definitions_by_family(definitions: Iterable[RareLensDefinition] | None = None) -> dict[LensFamily, tuple[RareLensDefinition, ...]]:
    items = tuple(definitions or rare_semantic_definitions())
    grouped: dict[LensFamily, list[RareLensDefinition]] = {}
    for item in items:
        grouped.setdefault(item.spec.family, []).append(item)
    return {family: tuple(sorted(values, key=lambda x: (x.spec.lineage_year, x.spec.key))) for family, values in grouped.items()}