"""Canonical game-domain contracts for Skeleton."""

from .composition import (
    CANONICAL_KIND_ORDER,
    COMPOSITION_CONTRACT_VERSION,
    MECHANICS_SURFACE_VERSION,
    BoundMechanic,
    CompositionDiagnostic,
    CompositionEvent,
    CompositionEventKind,
    CompositionReplayEvidence,
    CompositionState,
    GameCompositionError,
    GameplayComposer,
    GameplayComposition,
    MechanicComponent,
    MechanicComponentRef,
    apply_composition_events,
    compose_gameplay,
    initial_composition_state,
)
from .mechanics import (
    AIBehaviorSpec,
    CombatStyle,
    CombatSystemSpec,
    EconomySystemSpec,
    GameMechanicsError,
    GameMechanicsGenerator,
    MechanicType,
    ProgressionStyle,
    ProgressionSystemSpec,
)

from .replay import (
    REPLAY_SCHEMA,
    REPLAY_SCHEMA_VERSION,
    GameReplayError,
    MechanicsReplay,
    ReplayComparison,
    ReplayMismatch,
    ReplayStep,
    ReplayTrace,
)

__all__ = [
    "ReplayTrace",
    "ReplayStep",
    "ReplayMismatch",
    "ReplayComparison",
    "MechanicsReplay",
    "GameReplayError",
    "REPLAY_SCHEMA_VERSION",
    "REPLAY_SCHEMA",
    "AIBehaviorSpec",
    "BoundMechanic",
    "CANONICAL_KIND_ORDER",
    "COMPOSITION_CONTRACT_VERSION",
    "CombatStyle",
    "CombatSystemSpec",
    "CompositionDiagnostic",
    "CompositionEvent",
    "CompositionEventKind",
    "CompositionReplayEvidence",
    "CompositionState",
    "EconomySystemSpec",
    "GameCompositionError",
    "GameMechanicsError",
    "GameMechanicsGenerator",
    "GameplayComposer",
    "GameplayComposition",
    "MECHANICS_SURFACE_VERSION",
    "MechanicComponent",
    "MechanicComponentRef",
    "MechanicType",
    "ProgressionStyle",
    "ProgressionSystemSpec",
    "apply_composition_events",
    "compose_gameplay",
    "initial_composition_state",
]
