"""In-memory Godot 4 emit tree. Text files only. No binary. No vendor dump."""

from __future__ import annotations

import hashlib
import json
from typing import Any

from skeleton.game.catalog_data import pack as catalog_pack
from skeleton.game.emit_pack import REQUIRED, validate_emit
from skeleton.game.nexus_sim import simulate
from skeleton.game.provenance import meta
from skeleton.game.spec import compile_spec
from skeleton.game.world_graph import place


PROJECT_GODOT = """; Engine configuration file.
; Generated by Skeleton GameForge. Do not vendor a Godot binary.
config_version=5

[application]
config/name="NEXUS-EXTRACT"
run/main_scene="res://world.tscn"
config/features=PackedStringArray("4.3")

[autoload]
Jeeves="res://jeeves/jeeves.gd"
Heat="res://heat/heat.gd"
Forge="res://forge/forge.gd"
Extract="res://extract/extract.gd"

[display]
window/size/viewport_width=1280
window/size/viewport_height=720
"""

WORLD_GD = """extends Node2D
# NEXUS-EXTRACT world. Numbers live in data/spec.json.

@export var seed: int = 8847291
@export var rooms: int = 5
@export var extract_once: bool = true

func _ready() -> void:
    pass
"""

PLAYER_GD = """extends CharacterBody2D
# Player pawn. Heat and extract are autoloads.

@export var speed: float = 180.0
@export var heat_gain: int = 6

func _physics_process(_delta: float) -> void:
    pass
"""

WORLD_TSCN = """[gd_scene load_steps=3 format=3]

[ext_resource type="Script" path="res://world.gd" id="1_world"]
[ext_resource type="Script" path="res://player.gd" id="2_player"]

[node name="World" type="Node2D"]
script = ExtResource("1_world")

[node name="Player" type="CharacterBody2D" parent="."]
script = ExtResource("2_player")
"""

JEEVES_GD = """extends Node
# Jeeves organ autoload. Plan lives in data/spec.json.

@export var organ: String = "jeeves"
"""

HEAT_GD = """extends Node
# Heat organ. Tokens do not tick every frame.

@export var period: int = 4
@export var heat: int = 0
"""

FORGE_GD = """extends Node
# Forge organ. Mass is clipped. G is not stamped.

@export var mass0: float = 1.0
"""

EXTRACT_GD = """extends Node
# Extract organ. Warp extracts once.

@export var extract_count: int = 0
@export var warp_count: int = 0
"""


class EmitTreeError(ValueError):
    """Emit tree contract violation."""


def _dumps(payload: Any) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def build(*, seed: int = 8847291, vision: str = "NEXUS-EXTRACT heat extract #807") -> dict[str, Any]:
    spec = compile_spec(vision)
    graph = place(seed=int(seed), rooms=5)
    catalogs = catalog_pack(int(seed))
    run = simulate(seed=int(seed), ticks=32)
    files: dict[str, str] = {
        "project.godot": PROJECT_GODOT,
        "world.json": _dumps(graph),
        "world.gd": WORLD_GD,
        "world.tscn": WORLD_TSCN,
        "player.gd": PLAYER_GD,
        "jeeves/jeeves.gd": JEEVES_GD,
        "jeeves/": "",
        "heat/heat.gd": HEAT_GD,
        "heat/": "",
        "forge/forge.gd": FORGE_GD,
        "forge/": "",
        "extract/extract.gd": EXTRACT_GD,
        "extract/": "",
        "data/spec.json": _dumps({"fields": spec["fields"], "conflicts": spec["conflicts"], "seed": int(seed)}),
        "data/catalog/items.json": _dumps(catalogs["items"]),
        "data/catalog/quests.json": _dumps(catalogs["quests"]),
        "data/catalog/encounters.json": _dumps(catalogs["encounters"]),
        "reports/build_report.md": "# build_report\nseed={0}\nextracted={1}\nsota_ready=0\n".format(seed, run["extracted"]),
    }
    companions = []
    for path in ("world.json", "data/spec.json", "data/catalog/items.json", "reports/build_report.md"):
        card = meta(path=path, seed=int(seed), step="export", rotor="emit")
        files[card["meta_path"]] = _dumps(card)
        companions.append(card["meta_path"])
    check = validate_emit(list(REQUIRED))
    body = {
        "kind": "emit_tree",
        "seed": int(seed),
        "files": sorted(files),
        "n": len(files),
        "bytes": sum(len(blob.encode("utf-8")) for blob in files.values()),
        "valid": check["valid"],
        "godot_binary": 0,
        "meta": companions,
        "sim_digest": run["digest"],
        "sota_ready": False,
        "stored_prose": 0,
        "contents": files,
    }
    body["digest"] = hashlib.sha256(_dumps({k: v for k, v in body.items() if k != "digest"}).encode("utf-8")).hexdigest()
    body["ok"] = True
    return body


def public_card(tree: dict[str, Any]) -> dict[str, Any]:
    return {
        "ok": True,
        "kind": tree["kind"],
        "n": tree["n"],
        "bytes": tree["bytes"],
        "valid": tree["valid"],
        "godot_binary": tree["godot_binary"],
        "digest": tree["digest"],
        "sota_ready": False,
        "stored_prose": 0,
    }
