"""controllers.py — ready-to-play GDScript controllers per template.

Pure text generators; no I/O. Each returns a complete .gd file.
"""
from __future__ import annotations

PLATFORMER_GD = '''## Platformer player — generated by Tutolage godot_engine.
extends CharacterBody2D

@export var speed: float = 220.0
@export var jump_velocity: float = -420.0
@export var gravity: float = 1200.0
@export var coyote_time: float = 0.12
@export var jump_buffer: float = 0.12

var _coyote: float = 0.0
var _buffer: float = 0.0


func _physics_process(delta: float) -> void:
    if not is_on_floor():
        velocity.y += gravity * delta
        _coyote -= delta
    else:
        _coyote = coyote_time

    if Input.is_action_just_pressed("jump"):
        _buffer = jump_buffer
    else:
        _buffer -= delta

    if _buffer > 0.0 and _coyote > 0.0:
        velocity.y = jump_velocity
        _buffer = 0.0
        _coyote = 0.0

    var direction := Input.get_axis("move_left", "move_right")
    velocity.x = direction * speed
    move_and_slide()
'''

TOPDOWN_GD = '''## Top-down player — generated by Tutolage godot_engine.
extends CharacterBody2D

@export var speed: float = 180.0
@export var acceleration: float = 1200.0
@export var friction: float = 900.0


func _physics_process(delta: float) -> void:
    var input_dir := Input.get_vector(
        "move_left", "move_right", "move_up", "move_down"
    )
    if input_dir != Vector2.ZERO:
        velocity = velocity.move_toward(input_dir * speed, acceleration * delta)
    else:
        velocity = velocity.move_toward(Vector2.ZERO, friction * delta)
    move_and_slide()
'''

MAIN_GD = '''## Entry script — generated by Tutolage godot_engine.
extends Node2D


func _ready() -> void:
    print("{title}: ready")
'''

DEFAULT_INPUT_ACTIONS = {
    "move_left": ["KEY_A", "KEY_LEFT"],
    "move_right": ["KEY_D", "KEY_RIGHT"],
    "move_up": ["KEY_W", "KEY_UP"],
    "move_down": ["KEY_S", "KEY_DOWN"],
    "jump": ["KEY_SPACE"],
}


def controller_for(template: str, title: str = "Game") -> tuple[str, str]:
    """Return (filename, content) for the template's main script."""
    if template == "platformer":
        return "player.gd", PLATFORMER_GD
    if template == "topdown":
        return "player.gd", TOPDOWN_GD
    return "main.gd", MAIN_GD.format(title=title)
