"""Pure domain kernel — zero I/O, zero framework imports."""

from skeleton.kernel.errors import (
    AgentNotFoundError,
    BlueprintError,
    CapabilityNotFoundError,
    ConfigurationError,
    ConsensusError,
    DuplicateCapabilityError,
    EventBusError,
    GenerationError,
    InvalidIdentifierError,
    MaterialisationError,
    NoCapableAgentError,
    RagQueryError,
    RegistryError,
    SchedulingError,
    SessionError,
    SkeletonError,
    TaskDeadLetteredError,
    ValidationError,
    http_status_for,
)
from skeleton.kernel.events import DomainEvent, EventBus
from skeleton.kernel.ids import AgentId, BlueprintId, MemoryId, PipelineRunId, SessionId, UserId
from skeleton.kernel.registry import CapabilityKind, CapabilityRegistry, bootstrap_registry

__all__ = [
    "SkeletonError",
    "RegistryError",
    "CapabilityNotFoundError",
    "DuplicateCapabilityError",
    "EventBusError",
    "InvalidIdentifierError",
    "ConfigurationError",
    "AgentNotFoundError",
    "NoCapableAgentError",
    "ConsensusError",
    "SchedulingError",
    "TaskDeadLetteredError",
    "GenerationError",
    "ValidationError",
    "SessionError",
    "RagQueryError",
    "BlueprintError",
    "MaterialisationError",
    "http_status_for",
    "DomainEvent",
    "EventBus",
    "AgentId",
    "SessionId",
    "PipelineRunId",
    "BlueprintId",
    "UserId",
    "MemoryId",
    "CapabilityKind",
    "CapabilityRegistry",
    "bootstrap_registry",
]
