"""Provider-neutral FLGB-02 model-runtime and native execution contracts."""
from .flgb_model_runtime import (
    ALLOWED_TRANSITIONS,
    BatchRequest,
    DeviceDescriptor,
    KVCacheEntry,
    LocalModelReceipt,
    LocalModelRequest,
    ModelIdentity,
    ModelLifecycle,
    ModelRegistry,
    ModelRuntimeError,
    Placement,
    QuantizationProfile,
    Replica,
    SpeculativeReceipt,
    TokenSequence,
    VocabularyManifest,
    WeightLoadPlan,
    WeightShard,
    plan_continuous_batches,
    plan_device_placement,
    plan_kv_admission,
    route_request,
)
from .runtime_contracts import (
    BatchGenerationRequest,
    DevicePolicy,
    DeviceReceipt,
    GenerationConfig,
    ReplayMismatch,
    ReplayReceipt,
    RuntimeArchitecture,
    RuntimeContractError,
    RuntimeEvent,
    RuntimeLimits,
    RuntimeUsage,
)

# Delay optional native transformer / Cortex imports until explicitly requested.
# Contract-only modules must load under the standard-library-only CI lane.
from importlib import import_module

_LAZY_EXPORTS = {
    "BatchGenerationResult": ".native_llm_runtime",
    "GenerationResult": ".native_llm_runtime",
    "GenerationStream": ".native_llm_runtime",
    "NativeLLMRuntime": ".native_llm_runtime",
    "CancellationToken": ".runtime_service",
    "NativeModelService": ".runtime_service",
    "NativeServiceError": ".runtime_service",
    "NativeServiceResult": ".runtime_service",
    "NativeTokenizer": ".tokenization",
    "StreamingTextFeed": ".tokenization",
    "TokenBatch": ".tokenization",
    "TokenWindow": ".tokenization",
    "TokenizerContractError": ".tokenization",
    "TokenizerLimits": ".tokenization",
    "batch_token_windows": ".tokenization",
    "deserialize_token_sequence": ".tokenization",
    "iter_context_windows": ".tokenization",
    "serialize_token_sequence": ".tokenization",
    "validate_model_snapshot": ".runtime_checkpoint",
    "restore_admission_scheduler": ".admission_checkpoint",
    "AdmissionDecision": ".admission_scheduler",
    "AdmissionLimits": ".admission_scheduler",
    "RuntimeAdmissionScheduler": ".admission_scheduler",
    "ScheduledRequest": ".admission_scheduler",
    "InferencePhase": ".iteration_scheduler",
    "IterationPlan": ".iteration_scheduler",
    "IterationScheduler": ".iteration_scheduler",
    "IterationSlice": ".iteration_scheduler",
    "IterationWork": ".iteration_scheduler",
    "DEFAULT_RUNTIME_EPOCHS": ".runtime_epochs",
    "EpochStatus": ".runtime_epochs",
    "RuntimeEpoch": ".runtime_epochs",
    "RuntimeEpochRegistry": ".runtime_epochs",
    "DEFAULT_RUNTIME_POLICY_COMPILER": ".runtime_policy",
    "RuntimePolicy": ".runtime_policy",
    "RuntimePolicyCompiler": ".runtime_policy",
    "DEFAULT_RUNTIME_SIGNALS": ".runtime_signals",
    "RuntimeSignal": ".runtime_signals",
    "RuntimeSignalRegistry": ".runtime_signals",
    "SignalMaturity": ".runtime_signals",
    "RequestTelemetry": ".serving_telemetry",
    "ServingTelemetryWindow": ".serving_telemetry",
    "ResourcePlan": ".slo_planner",
    "RuntimeEstimate": ".slo_planner",
    "SLOResourcePlanner": ".slo_planner",
    "SLOTarget": ".slo_planner",
    "DEFAULT_TEMPORAL_RUNTIME_POLICY_COMPILER": ".temporal_policy",
    "TemporalRuntimePolicy": ".temporal_policy",
    "TemporalRuntimePolicyCompiler": ".temporal_policy",
    "CausalTrainingBatch": ".text_pipeline",
    "CorpusTrainingReceipt": ".text_pipeline",
    "DecadeCorpusBucket": ".text_pipeline",
    "DecadeCoverageReceipt": ".text_pipeline",
    "DecadeSamplingPlan": ".text_pipeline",
    "DecadeSignalVector": ".text_pipeline",
    "DecadeTrainingSignal": ".text_pipeline",
    "GovernedTrainingInput": ".text_pipeline",
    "ModelInputBatch": ".text_pipeline",
    "PipelineReplayCheckpoint": ".text_pipeline",
    "PreparedCorpus": ".text_pipeline",
    "PreparedText": ".text_pipeline",
    "RoundTripReceipt": ".text_pipeline",
    "PromotionAuthorizationRequest": ".text_pipeline",
    "SourceProvenanceGraph": ".text_pipeline",
    "SourceProvenanceNode": ".text_pipeline",
    "SupervisedTextExample": ".text_pipeline",
    "TemporalContradiction": ".text_pipeline",
    "TemporalEvaluationGate": ".text_pipeline",
    "TemporalEvaluationResult": ".text_pipeline",
    "TemporalEvaluationSlice": ".text_pipeline",
    "TemporalRetrievalCandidate": ".text_pipeline",
    "TemporalRetrievalPlan": ".text_pipeline",
    "TemporalRetentionResult": ".text_pipeline",
    "TemporalRetentionGate": ".text_pipeline",
    "TemporalRetentionTrajectory": ".text_pipeline",
    "TemporalConflictCluster": ".text_pipeline",
    "TemporalEvidence": ".text_pipeline",
    "TemporalSourceEvidence": ".text_pipeline",
    "TemporalSupersession": ".text_pipeline",
    "WalkForwardSnapshot": ".text_pipeline",
    "TemporalTrainingSignal": ".text_pipeline",
    "TemporalInstant": ".text_pipeline",
    "TemporalInterval": ".text_pipeline",
    "TextPipelineConfig": ".text_pipeline",
    "TextTokenPipeline": ".text_pipeline",
    "TrainingInputReceipt": ".text_pipeline",
    "deserialize_causal_training_batch": ".text_pipeline",
    "arbitrate_temporal_evidence": ".text_pipeline",
    "decade_weight_ppm": ".text_pipeline",
    "independent_confidence_ppm": ".text_pipeline",
    "provenance_independence_group": ".text_pipeline",
    "source_evidence_from_provenance": ".text_pipeline",
    "walk_forward_snapshot": ".text_pipeline",
    "deserialize_model_input_batch": ".text_pipeline",
    "mask_causal_prefix": ".text_pipeline",
    "materialize_causal_training_batch": ".text_pipeline",
    "materialize_model_batch": ".text_pipeline",
    "serialize_causal_training_batch": ".text_pipeline",
    "serialize_model_input_batch": ".text_pipeline",
    "normalize_text": ".text_normalization",
}


def __getattr__(name: str):
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))

__all__ = [
    "CausalTrainingBatch",
    "CorpusTrainingReceipt",
    "DecadeCorpusBucket",
    "DecadeCoverageReceipt",
    "DecadeSamplingPlan",
    "DecadeSignalVector",
    "DecadeTrainingSignal",
    "GovernedTrainingInput",
    "ModelInputBatch",
    "PipelineReplayCheckpoint",
    "PreparedCorpus",
    "PreparedText",
    "RoundTripReceipt",
    "PromotionAuthorizationRequest",
    "SourceProvenanceGraph",
    "SourceProvenanceNode",
    "SupervisedTextExample",
    "TemporalContradiction",
    "TemporalEvaluationGate",
    "TemporalEvaluationResult",
    "TemporalEvaluationSlice",
    "TemporalRetrievalCandidate",
    "TemporalRetrievalPlan",
    "TemporalRetentionResult",
    "TemporalRetentionGate",
    "TemporalRetentionTrajectory",
    "TemporalConflictCluster",
    "TemporalEvidence",
    "TemporalSourceEvidence",
    "TemporalSupersession",
    "WalkForwardSnapshot",
    "TemporalTrainingSignal",
    "TemporalInstant",
    "TemporalInterval",
    "TextPipelineConfig",
    "TextTokenPipeline",
    "TrainingInputReceipt",
    "deserialize_causal_training_batch",
    "arbitrate_temporal_evidence",
    "decade_weight_ppm",
    "independent_confidence_ppm",
    "provenance_independence_group",
    "source_evidence_from_provenance",
    "walk_forward_snapshot",
    "deserialize_model_input_batch",
    "mask_causal_prefix",
    "materialize_causal_training_batch",
    "materialize_model_batch",
    "serialize_causal_training_batch",
    "serialize_model_input_batch",
    "normalize_text",
    "restore_admission_scheduler",
    "AdmissionDecision",
    "AdmissionLimits",
    "RuntimeAdmissionScheduler",
    "ScheduledRequest",
    "InferencePhase",
    "IterationPlan",
    "IterationScheduler",
    "IterationSlice",
    "IterationWork",
    "DEFAULT_RUNTIME_EPOCHS",
    "EpochStatus",
    "RuntimeEpoch",
    "RuntimeEpochRegistry",
    "DEFAULT_RUNTIME_POLICY_COMPILER",
    "RuntimePolicy",
    "RuntimePolicyCompiler",
    "DEFAULT_RUNTIME_SIGNALS",
    "RuntimeSignal",
    "RuntimeSignalRegistry",
    "SignalMaturity",
    "RequestTelemetry",
    "ServingTelemetryWindow",
    "ResourcePlan",
    "RuntimeEstimate",
    "SLOResourcePlanner",
    "SLOTarget",
    "DEFAULT_TEMPORAL_RUNTIME_POLICY_COMPILER",
    "TemporalRuntimePolicy",
    "TemporalRuntimePolicyCompiler",
    "ALLOWED_TRANSITIONS",
    "BatchGenerationRequest",
    "BatchGenerationResult",
    "CancellationToken",
    "BatchRequest",
    "DeviceDescriptor",
    "DevicePolicy",
    "DeviceReceipt",
    "GenerationConfig",
    "GenerationResult",
    "GenerationStream",
    "KVCacheEntry",
    "LocalModelReceipt",
    "LocalModelRequest",
    "ModelIdentity",
    "ModelLifecycle",
    "ModelRegistry",
    "ModelRuntimeError",
    "NativeLLMRuntime",
    "NativeModelService",
    "NativeServiceError",
    "NativeServiceResult",
    "NativeTokenizer",
    "Placement",
    "QuantizationProfile",
    "ReplayMismatch",
    "ReplayReceipt",
    "Replica",
    "RuntimeArchitecture",
    "RuntimeContractError",
    "RuntimeEvent",
    "RuntimeLimits",
    "RuntimeUsage",
    "SpeculativeReceipt",
    "StreamingTextFeed",
    "TokenBatch",
    "TokenSequence",
    "TokenWindow",
    "TokenizerContractError",
    "TokenizerLimits",
    "VocabularyManifest",
    "WeightLoadPlan",
    "WeightShard",
    "batch_token_windows",
    "deserialize_token_sequence",
    "iter_context_windows",
    "plan_continuous_batches",
    "plan_device_placement",
    "plan_kv_admission",
    "route_request",
    "serialize_token_sequence",
    "validate_model_snapshot",
]
