"""Provider-neutral FLGB-02 model-runtime and native execution contracts."""
from .admission_scheduler import AdmissionDecision, AdmissionLimits, RuntimeAdmissionScheduler, ScheduledRequest
from .runtime_signals import DEFAULT_RUNTIME_SIGNALS, RuntimeSignal, RuntimeSignalRegistry, SignalMaturity
from .runtime_policy import DEFAULT_RUNTIME_POLICY_COMPILER, RuntimePolicy, RuntimePolicyCompiler
from .runtime_epochs import DEFAULT_RUNTIME_EPOCHS, EpochStatus, RuntimeEpoch, RuntimeEpochRegistry
from .temporal_policy import DEFAULT_TEMPORAL_RUNTIME_POLICY_COMPILER, TemporalRuntimePolicy, TemporalRuntimePolicyCompiler
from .serving_policy import PolicyAwareServingPlanner, ServiceClass, ServingPlan, ServingRequest
from .slo_planner import ResourcePlan, RuntimeEstimate, SLOResourcePlanner, SLOTarget
from .serving_telemetry import RequestTelemetry, ServingTelemetryWindow
from .runtime_feedback import DeterministicRuntimeEstimator, FeedbackLimits, FeedbackReceipt
from .closed_loop_serving import ClosedLoopServingController, ControlDecision
from .iteration_scheduler import InferencePhase, IterationPlan, IterationScheduler, IterationSlice, IterationWork
from .execution_telemetry import ExecutionTiming
from .admission_checkpoint import restore_admission_scheduler
from .flgb_model_runtime import (
    ALLOWED_TRANSITIONS,
    BatchRequest,
    DeviceDescriptor,
    KVCacheEntry,
    LocalModelReceipt,
    LocalModelRequest,
    ModelIdentity,
    ModelLifecycle,
    ModelRegistry,
    ModelRuntimeError,
    Placement,
    QuantizationProfile,
    Replica,
    SpeculativeReceipt,
    TokenSequence,
    VocabularyManifest,
    WeightLoadPlan,
    WeightShard,
    plan_continuous_batches,
    plan_device_placement,
    plan_kv_admission,
    route_request,
)
from .native_llm_runtime import (
    BatchGenerationResult,
    GenerationResult,
    GenerationStream,
    InferenceResult,
    NativeLLMRuntime,
    NativeConversationSession,
)
from .runtime_checkpoint import validate_model_snapshot
from .runtime_service import (
    CancellationToken,
    NativeModelService,
    NativeServiceError,
    NativeServiceResult,
)
from .runtime_contracts import (
    BatchGenerationRequest,
    DevicePolicy,
    DeviceReceipt,
    GenerationConfig,
    ReplayMismatch,
    ReplayReceipt,
    RuntimeArchitecture,
    RuntimeContractError,
    RuntimeEvent,
    RuntimeLimits,
    RuntimeUsage,
)
from .tokenization import (
    NativeTokenizer,
    StreamingTextFeed,
    TokenBatch,
    TokenWindow,
    TokenizerContractError,
    TokenizerLimits,
    batch_token_windows,
    deserialize_token_sequence,
    iter_context_windows,
    serialize_token_sequence,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AdmissionDecision",
    "AdmissionLimits",
    "BatchGenerationRequest",
    "BatchGenerationResult",
    "CancellationToken",
    "BatchRequest",
    "ClosedLoopServingController",
    "ControlDecision",
    "DEFAULT_RUNTIME_EPOCHS",
    "DEFAULT_RUNTIME_POLICY_COMPILER",
    "DEFAULT_TEMPORAL_RUNTIME_POLICY_COMPILER",
    "DEFAULT_RUNTIME_SIGNALS",
    "DeterministicRuntimeEstimator",
    "DeviceDescriptor",
    "DevicePolicy",
    "DeviceReceipt",
    "EpochStatus",
    "ExecutionTiming",
    "FeedbackLimits",
    "FeedbackReceipt",
    "GenerationConfig",
    "GenerationResult",
    "GenerationStream",
    "InferenceResult",
    "InferencePhase",
    "IterationPlan",
    "IterationScheduler",
    "IterationSlice",
    "IterationWork",
    "KVCacheEntry",
    "LocalModelReceipt",
    "LocalModelRequest",
    "ModelIdentity",
    "ModelLifecycle",
    "ModelRegistry",
    "ModelRuntimeError",
    "NativeLLMRuntime",
    "NativeConversationSession",
    "NativeModelService",
    "NativeServiceError",
    "NativeServiceResult",
    "NativeTokenizer",
    "Placement",
    "PolicyAwareServingPlanner",
    "QuantizationProfile",
    "ReplayMismatch",
    "ReplayReceipt",
    "Replica",
    "RuntimeAdmissionScheduler",
    "RuntimeEpoch",
    "RuntimeEpochRegistry",
    "RequestTelemetry",
    "ResourcePlan",
    "RuntimeEstimate",
    "RuntimePolicy",
    "RuntimePolicyCompiler",
    "RuntimeSignal",
    "RuntimeSignalRegistry",
    "RuntimeArchitecture",
    "RuntimeContractError",
    "RuntimeEvent",
    "RuntimeLimits",
    "RuntimeUsage",
    "SLOResourcePlanner",
    "SLOTarget",
    "ScheduledRequest",
    "ServiceClass",
    "ServingPlan",
    "ServingRequest",
    "ServingTelemetryWindow",
    "SignalMaturity",
    "SpeculativeReceipt",
    "StreamingTextFeed",
    "TemporalRuntimePolicy",
    "TemporalRuntimePolicyCompiler",
    "TokenBatch",
    "TokenSequence",
    "TokenWindow",
    "TokenizerContractError",
    "TokenizerLimits",
    "VocabularyManifest",
    "WeightLoadPlan",
    "WeightShard",
    "batch_token_windows",
    "deserialize_token_sequence",
    "iter_context_windows",
    "plan_continuous_batches",
    "plan_device_placement",
    "plan_kv_admission",
    "route_request",
    "serialize_token_sequence",
    "validate_model_snapshot",
]
