"""Frontier consolidation contracts and program metadata."""

from skeleton.frontier.achievements import (
    AchievementRequirement,
    AchievementRewardPlan,
    AchievementSpec,
    AchievementState,
    DailyClaimPlan,
    DailyRewardSpec,
    DailyRewardStatus,
    achievement_from_record,
    achievement_summary,
    claim_achievement,
    claim_daily_reward,
    daily_reward_from_record,
    daily_reward_status,
    progress_percent as achievement_progress_percent,
    project_achievement,
    qualifies as achievement_qualifies,
    reward_plan as achievement_reward_plan,
    unlock_qualified,
    update_stat as update_achievement_stat,
)
from skeleton.frontier.agent_runtime import AgentRuntime, ExecutionResult
from skeleton.frontier.contracts import (
    AgentContract,
    MemoryContract,
    ProvenanceRecord,
    stable_content_digest,
)
from skeleton.frontier.events import (
    DomainEvent,
    EventBus,
    EventJournal,
    EventJournalCorruptionError,
    JournalEntry,
    SQLiteEventJournal,
)
from skeleton.frontier.logbook import (
    CaptainLogEntry,
    MILESTONE_IMPORTANCE,
    can_delete,
    log_entry_event,
    log_entry_from_record,
    log_entry_to_memory_item,
    log_statistics,
    milestone_entries,
    render_log_template,
    search_entries,
    timeline,
    toggle_pin,
)
from skeleton.frontier.memory import (
    InMemoryStore,
    MemoryItem,
    normalize_memory_filters,
    normalize_memory_metadata,
)
from skeleton.frontier.memory_adapters import (
    CollectionMemoryAdapter,
    MemoryStoreCorruptionError,
    SQLiteCollection,
)
from skeleton.frontier.npc import NPCGenerator, NPCSpec
from skeleton.frontier.npc_adapters import npc_spec_from_domain_record
from skeleton.frontier.npc_profiles import ArchetypeProfile, get_profile, infer_archetype
from skeleton.frontier.quests import (
    ObjectiveProgress,
    QuestProgressState,
    QuestSpec,
    RewardPlan,
    available_quests,
    initialize_progress,
    quest_from_record,
    reward_plan,
    select_quests_by_type,
    update_objective_progress,
)
from skeleton.frontier.reputation import (
    DEFAULT_REPUTATION_LEVELS,
    FactionSpec,
    ReputationChangeResult,
    ReputationDelta,
    ReputationLevel,
    apply_reputation_change,
    calculate_spillover,
    current_benefits,
    faction_from_record,
    next_reputation_level,
    reputation_level,
    standing_summary,
)
from skeleton.frontier.resilience import DegradationLevel, ResilienceController, ResilienceDecision
from skeleton.frontier.runtime_events import (
    execution_event_to_memory_item,
    execution_result_to_event,
)
from skeleton.frontier.ship import (
    CrewRoleSpec,
    PurchaseQuote,
    aggregate_crew,
    can_afford,
    can_hire,
    choose_crew_name,
    crew_role_from_record,
    generate_crew_dialogue,
    hiring_cost,
    quote_purchase,
    stores_for_location,
)
from skeleton.frontier.world import (
    IslandVocabulary,
    WorldBounds,
    WorldRegion,
    calculate_route,
    calculate_supplies_needed,
    find_region_at,
    find_region_by_id,
    generate_random_island,
    project_fog_of_war,
    region_from_record,
)

__all__ = [
    "AchievementRequirement",
    "AchievementRewardPlan",
    "AchievementSpec",
    "AchievementState",
    "AgentContract",
    "AgentRuntime",
    "ArchetypeProfile",
    "CaptainLogEntry",
    "CollectionMemoryAdapter",
    "CrewRoleSpec",
    "DEFAULT_REPUTATION_LEVELS",
    "DailyClaimPlan",
    "DailyRewardSpec",
    "DailyRewardStatus",
    "DegradationLevel",
    "DomainEvent",
    "EventBus",
    "EventJournal",
    "EventJournalCorruptionError",
    "ExecutionResult",
    "FactionSpec",
    "InMemoryStore",
    "IslandVocabulary",
    "JournalEntry",
    "MILESTONE_IMPORTANCE",
    "MemoryContract",
    "MemoryItem",
    "MemoryStoreCorruptionError",
    "NPCGenerator",
    "NPCSpec",
    "ObjectiveProgress",
    "ProvenanceRecord",
    "PurchaseQuote",
    "QuestProgressState",
    "QuestSpec",
    "ReputationChangeResult",
    "ReputationDelta",
    "ReputationLevel",
    "ResilienceController",
    "ResilienceDecision",
    "RewardPlan",
    "SQLiteCollection",
    "SQLiteEventJournal",
    "WorldBounds",
    "WorldRegion",
    "achievement_from_record",
    "achievement_progress_percent",
    "achievement_qualifies",
    "achievement_reward_plan",
    "achievement_summary",
    "aggregate_crew",
    "apply_reputation_change",
    "available_quests",
    "calculate_route",
    "calculate_spillover",
    "calculate_supplies_needed",
    "can_afford",
    "can_delete",
    "can_hire",
    "choose_crew_name",
    "claim_achievement",
    "claim_daily_reward",
    "crew_role_from_record",
    "current_benefits",
    "daily_reward_from_record",
    "daily_reward_status",
    "execution_event_to_memory_item",
    "execution_result_to_event",
    "faction_from_record",
    "find_region_at",
    "find_region_by_id",
    "generate_crew_dialogue",
    "generate_random_island",
    "get_profile",
    "hiring_cost",
    "infer_archetype",
    "initialize_progress",
    "log_entry_event",
    "log_entry_from_record",
    "log_entry_to_memory_item",
    "log_statistics",
    "milestone_entries",
    "next_reputation_level",
    "normalize_memory_filters",
    "normalize_memory_metadata",
    "npc_spec_from_domain_record",
    "project_achievement",
    "project_fog_of_war",
    "quest_from_record",
    "quote_purchase",
    "region_from_record",
    "render_log_template",
    "reputation_level",
    "reward_plan",
    "search_entries",
    "select_quests_by_type",
    "stable_content_digest",
    "standing_summary",
    "stores_for_location",
    "timeline",
    "toggle_pin",
    "unlock_qualified",
    "update_achievement_stat",
    "update_objective_progress",
]
