"""Stable gameplay policy facade for promoted frontier primitives.

This module provides a collision-free public import surface for the selectively
promoted gameplay policies. It intentionally composes existing primitives rather
than duplicating their job, economy, event or persistence responsibilities.
"""

from skeleton.frontier.bait import (
    BaitEquipPlan,
    BaitLoadout,
    BaitSpec,
    BaitUsePlan,
    CatchBonuses,
    FishingSpotSpec,
    bait_effective_for_fish,
    bait_from_record,
    bait_purchase_cost,
    calculate_catch_bonuses,
    can_afford_cost as can_afford_bait_cost,
    can_unlock_spot,
    combine_external_bonuses,
    equip_bait,
    select_spot,
    spot_from_record,
    spot_unlock_requirements,
    use_bait,
)
from skeleton.frontier.breeding import (
    BreedingJob,
    BreedingParent,
    BreedingProgress,
    FishSpeciesSpec,
    OffspringPlan,
    SlotUpgradePlan as BreedingSlotUpgradePlan,
    SpecialBreedSpec,
    apply_breeding_reward,
    breed_time_hours,
    calculate_fish_value,
    compatible_species,
    generate_traits,
    matching_special_breed,
    offspring_plan,
    parent_from_record,
    refresh_breeding,
    slot_upgrade_plan as breeding_slot_upgrade_plan,
    special_breed_from_record,
    species_from_record,
    speed_up_cost as breeding_speed_up_cost,
    start_breeding,
    trait_value_multiplier,
)
from skeleton.frontier.breeding_adapters import (
    achievement_signals_from_offspring,
    breeding_event_to_memory_item,
    breeding_offspring_digest,
    breeding_offspring_event,
    breeding_offspring_identity,
)
from skeleton.frontier.crafting import (
    CraftJob,
    CraftingRecipe,
    WorkshopState,
    collect_craft,
    refresh_workshop,
    start_craft,
)
from skeleton.frontier.energy import (
    EnergyBoosterSpec,
    EnergyPolicy,
    EnergyState,
    apply_booster,
    consume_energy,
    regenerate_energy,
    restore_energy,
)
from skeleton.frontier.equipment import (
    EquipmentBonuses,
    EquipmentLoadout,
    EquipmentSpec,
    calculate_equipment_bonuses,
    equip_item,
    quote_equipment_purchase,
)

__all__ = [
    "BaitEquipPlan",
    "BaitLoadout",
    "BaitSpec",
    "BaitUsePlan",
    "BreedingJob",
    "BreedingParent",
    "BreedingProgress",
    "BreedingSlotUpgradePlan",
    "CatchBonuses",
    "CraftJob",
    "CraftingRecipe",
    "EnergyBoosterSpec",
    "EnergyPolicy",
    "EnergyState",
    "EquipmentBonuses",
    "EquipmentLoadout",
    "EquipmentSpec",
    "FishSpeciesSpec",
    "FishingSpotSpec",
    "OffspringPlan",
    "SpecialBreedSpec",
    "WorkshopState",
    "achievement_signals_from_offspring",
    "apply_booster",
    "apply_breeding_reward",
    "bait_effective_for_fish",
    "bait_from_record",
    "bait_purchase_cost",
    "breed_time_hours",
    "breeding_event_to_memory_item",
    "breeding_offspring_digest",
    "breeding_offspring_event",
    "breeding_offspring_identity",
    "breeding_slot_upgrade_plan",
    "breeding_speed_up_cost",
    "calculate_catch_bonuses",
    "calculate_equipment_bonuses",
    "calculate_fish_value",
    "can_afford_bait_cost",
    "can_unlock_spot",
    "collect_craft",
    "combine_external_bonuses",
    "compatible_species",
    "consume_energy",
    "equip_bait",
    "equip_item",
    "generate_traits",
    "matching_special_breed",
    "offspring_plan",
    "parent_from_record",
    "quote_equipment_purchase",
    "refresh_breeding",
    "refresh_workshop",
    "regenerate_energy",
    "restore_energy",
    "select_spot",
    "special_breed_from_record",
    "species_from_record",
    "spot_from_record",
    "spot_unlock_requirements",
    "start_breeding",
    "start_craft",
    "trait_value_multiplier",
    "use_bait",
]
