"""Stable gameplay policy facade for promoted frontier primitives.

This module provides a collision-free public import surface for the selectively
promoted gameplay policies. It intentionally composes existing primitives rather
than duplicating their job, economy, event or persistence responsibilities.
"""

from skeleton.frontier.aquarium import (
    AquariumDecorationSpec,
    AquariumLikeLedger,
    AquariumPosition,
    AquariumPurchasePlan,
    AquariumState,
    AquariumTankSpec,
    AquariumTankState,
    AquariumThemeSpec,
    DecorationPlacementPlan,
    DisplayFish,
    FishMovePlan,
    PlacedDecoration,
    add_fish,
    affordability_shortfall as aquarium_affordability_shortfall,
    decoration_from_record,
    display_fish_from_record,
    initial_aquarium,
    place_decoration,
    purchase_decoration,
    purchase_tank,
    record_like,
    record_visit,
    remove_fish,
    set_theme,
    tank_from_record,
    theme_from_record,
)
from skeleton.frontier.aquarium_adapters import (
    aquarium_event,
    aquarium_event_to_memory_item,
    aquarium_identity,
    aquarium_state_digest,
    aquarium_state_memory_item,
    aquarium_state_payload,
)
from skeleton.frontier.biotope import (
    BiotopeBonus,
    BiotopeCatchPlan,
    BiotopeProgress,
    BiotopeSpec,
    BiotopeStageSpec,
    calculate_biotope_bonus,
    can_unlock_biotope,
    can_unlock_stage as can_unlock_biotope_stage,
    enter_stage as enter_biotope_stage,
    initial_progress as initial_biotope_progress,
    record_catch as record_biotope_catch,
    unlock_biotope,
    unlock_stage as unlock_biotope_stage,
    unlockable_biotopes,
    unlockable_stages as unlockable_biotope_stages,
)
from skeleton.frontier.biotope_adapters import (
    biotope_event,
    biotope_event_to_memory_item,
    biotope_identity,
    biotope_progress_digest,
    biotope_progress_memory_item,
    biotope_progress_payload,
)
from skeleton.frontier.bait import (
    BaitEquipPlan,
    BaitLoadout,
    BaitSpec,
    BaitUsePlan,
    CatchBonuses,
    FishingSpotSpec,
    bait_effective_for_fish,
    bait_from_record,
    bait_purchase_cost,
    calculate_catch_bonuses,
    can_afford_cost as can_afford_bait_cost,
    can_unlock_spot,
    combine_external_bonuses,
    equip_bait,
    select_spot,
    spot_from_record,
    spot_unlock_requirements,
    use_bait,
)
from skeleton.frontier.breeding import (
    BreedingJob,
    BreedingParent,
    BreedingProgress,
    FishSpeciesSpec,
    OffspringPlan,
    SlotUpgradePlan as BreedingSlotUpgradePlan,
    SpecialBreedSpec,
    apply_breeding_reward,
    breed_time_hours,
    calculate_fish_value,
    compatible_species,
    generate_traits,
    matching_special_breed,
    offspring_plan,
    parent_from_record,
    refresh_breeding,
    slot_upgrade_plan as breeding_slot_upgrade_plan,
    special_breed_from_record,
    species_from_record,
    speed_up_cost as breeding_speed_up_cost,
    start_breeding,
    trait_value_multiplier,
)
from skeleton.frontier.breeding_adapters import (
    achievement_signals_from_offspring,
    breeding_event_to_memory_item,
    breeding_offspring_digest,
    breeding_offspring_event,
    breeding_offspring_identity,
)
from skeleton.frontier.crafting import (
    CraftJob,
    CraftingRecipe,
    WorkshopState,
    collect_craft,
    refresh_workshop,
    start_craft,
)
from skeleton.frontier.energy import (
    EnergyBoosterSpec,
    EnergyPolicy,
    EnergyState,
    apply_booster,
    consume_energy,
    regenerate_energy,
    restore_energy,
)
from skeleton.frontier.equipment import (
    EquipmentBonuses,
    EquipmentLoadout,
    EquipmentSpec,
    calculate_equipment_bonuses,
    equip_item,
    quote_equipment_purchase,
)

__all__ = [
    "AquariumDecorationSpec",
    "AquariumLikeLedger",
    "AquariumPosition",
    "AquariumPurchasePlan",
    "AquariumState",
    "AquariumTankSpec",
    "AquariumTankState",
    "AquariumThemeSpec",
    "BaitEquipPlan",
    "BaitLoadout",
    "BaitSpec",
    "BaitUsePlan",
    "BiotopeBonus",
    "BiotopeCatchPlan",
    "BiotopeProgress",
    "BiotopeSpec",
    "BiotopeStageSpec",
    "BreedingJob",
    "BreedingParent",
    "BreedingProgress",
    "BreedingSlotUpgradePlan",
    "CatchBonuses",
    "CraftJob",
    "CraftingRecipe",
    "DecorationPlacementPlan",
    "DisplayFish",
    "EnergyBoosterSpec",
    "EnergyPolicy",
    "EnergyState",
    "EquipmentBonuses",
    "EquipmentLoadout",
    "EquipmentSpec",
    "FishMovePlan",
    "FishSpeciesSpec",
    "FishingSpotSpec",
    "OffspringPlan",
    "PlacedDecoration",
    "SpecialBreedSpec",
    "WorkshopState",
    "achievement_signals_from_offspring",
    "add_fish",
    "apply_booster",
    "apply_breeding_reward",
    "aquarium_affordability_shortfall",
    "aquarium_event",
    "aquarium_event_to_memory_item",
    "aquarium_identity",
    "aquarium_state_digest",
    "aquarium_state_memory_item",
    "aquarium_state_payload",
    "bait_effective_for_fish",
    "bait_from_record",
    "bait_purchase_cost",
    "biotope_event",
    "biotope_event_to_memory_item",
    "biotope_identity",
    "biotope_progress_digest",
    "biotope_progress_memory_item",
    "biotope_progress_payload",
    "breed_time_hours",
    "breeding_event_to_memory_item",
    "breeding_offspring_digest",
    "breeding_offspring_event",
    "breeding_offspring_identity",
    "breeding_slot_upgrade_plan",
    "breeding_speed_up_cost",
    "calculate_biotope_bonus",
    "calculate_catch_bonuses",
    "calculate_equipment_bonuses",
    "calculate_fish_value",
    "can_afford_bait_cost",
    "can_unlock_biotope",
    "can_unlock_biotope_stage",
    "can_unlock_spot",
    "collect_craft",
    "combine_external_bonuses",
    "compatible_species",
    "consume_energy",
    "decoration_from_record",
    "display_fish_from_record",
    "enter_biotope_stage",
    "equip_bait",
    "equip_item",
    "generate_traits",
    "initial_aquarium",
    "initial_biotope_progress",
    "matching_special_breed",
    "offspring_plan",
    "parent_from_record",
    "place_decoration",
    "purchase_decoration",
    "purchase_tank",
    "quote_equipment_purchase",
    "record_biotope_catch",
    "record_like",
    "record_visit",
    "refresh_breeding",
    "refresh_workshop",
    "regenerate_energy",
    "remove_fish",
    "restore_energy",
    "select_spot",
    "set_theme",
    "special_breed_from_record",
    "species_from_record",
    "spot_from_record",
    "spot_unlock_requirements",
    "start_breeding",
    "start_craft",
    "tank_from_record",
    "theme_from_record",
    "trait_value_multiplier",
    "unlock_biotope",
    "unlock_biotope_stage",
    "unlockable_biotope_stages",
    "unlockable_biotopes",
    "use_bait",
]
