"""Stable gameplay policy facade for promoted frontier primitives.

This module provides a collision-free public import surface for the selectively
promoted gameplay policies. It intentionally composes existing primitives rather
than duplicating their job, economy, event or persistence responsibilities.
"""

from skeleton.frontier.aquarium import (
    AquariumDecorationSpec,
    AquariumLikeLedger,
    AquariumPosition,
    AquariumPurchasePlan,
    AquariumState,
    AquariumTankSpec,
    AquariumTankState,
    AquariumThemeSpec,
    DecorationPlacementPlan,
    DisplayFish,
    FishMovePlan,
    PlacedDecoration,
    add_fish,
    affordability_shortfall as aquarium_affordability_shortfall,
    decoration_from_record,
    display_fish_from_record,
    initial_aquarium,
    place_decoration,
    purchase_decoration,
    purchase_tank,
    record_like,
    record_visit,
    remove_fish,
    set_theme,
    tank_from_record,
    theme_from_record,
)
from skeleton.frontier.aquarium_adapters import (
    aquarium_event,
    aquarium_event_to_memory_item,
    aquarium_identity,
    aquarium_state_digest,
    aquarium_state_memory_item,
    aquarium_state_payload,
)
from skeleton.frontier.biotope import (
    BiotopeBonus,
    BiotopeCatchPlan,
    BiotopeProgress,
    BiotopeSpec,
    BiotopeStageSpec,
    calculate_biotope_bonus,
    can_unlock_biotope,
    can_unlock_stage as can_unlock_biotope_stage,
    enter_stage as enter_biotope_stage,
    initial_progress as initial_biotope_progress,
    record_catch as record_biotope_catch,
    unlock_biotope,
    unlock_stage as unlock_biotope_stage,
    unlockable_biotopes,
    unlockable_stages as unlockable_biotope_stages,
)
from skeleton.frontier.biotope_adapters import (
    biotope_event,
    biotope_event_to_memory_item,
    biotope_identity,
    biotope_progress_digest,
    biotope_progress_memory_item,
    biotope_progress_payload,
)
from skeleton.frontier.biotope_achievement_adapters import (
    biotope_achievement_from_record,
    biotope_progress_achievement_signals,
    record_biotope_achievement_catch,
    requirement_signals_for_achievement as biotope_requirement_signals,
)
from skeleton.frontier.bait import (
    BaitEquipPlan,
    BaitLoadout,
    BaitSpec,
    BaitUsePlan,
    CatchBonuses,
    FishingSpotSpec,
    bait_effective_for_fish,
    bait_from_record,
    bait_purchase_cost,
    calculate_catch_bonuses,
    can_afford_cost as can_afford_bait_cost,
    can_unlock_spot,
    combine_external_bonuses,
    equip_bait,
    select_spot,
    spot_from_record,
    spot_unlock_requirements,
    use_bait,
)
from skeleton.frontier.breeding import (
    BreedingJob,
    BreedingParent,
    BreedingProgress,
    FishSpeciesSpec,
    OffspringPlan,
    SlotUpgradePlan as BreedingSlotUpgradePlan,
    SpecialBreedSpec,
    apply_breeding_reward,
    breed_time_hours,
    calculate_fish_value,
    compatible_species,
    generate_traits,
    matching_special_breed,
    offspring_plan,
    parent_from_record,
    refresh_breeding,
    slot_upgrade_plan as breeding_slot_upgrade_plan,
    special_breed_from_record,
    species_from_record,
    speed_up_cost as breeding_speed_up_cost,
    start_breeding,
    trait_value_multiplier,
)
from skeleton.frontier.breeding_adapters import (
    achievement_signals_from_offspring,
    breeding_event_to_memory_item,
    breeding_offspring_digest,
    breeding_offspring_event,
    breeding_offspring_identity,
)
from skeleton.frontier.crafting import (
    CraftJob,
    CraftingRecipe,
    WorkshopState,
    collect_craft,
    refresh_workshop,
    start_craft,
)
from skeleton.frontier.energy import (
    EnergyBoosterSpec,
    EnergyPolicy,
    EnergyState,
    apply_booster,
    consume_energy,
    regenerate_energy,
    restore_energy,
)
from skeleton.frontier.encyclopedia import (
    FishCatchPlan as EncyclopediaFishCatchPlan,
    FishCollectionState,
    FishCollectionSummary,
    FishDiscoveryStats,
    collection_completion_percent as encyclopedia_completion_percent,
    collection_summary as encyclopedia_collection_summary,
    empty_collection as empty_fish_collection,
    project_fish_entry,
    rarity_catch_counts,
    record_fish_catch,
)
from skeleton.frontier.encyclopedia_adapters import (
    collection_digest as encyclopedia_collection_digest,
    collection_event as encyclopedia_collection_event,
    collection_event_to_memory_item as encyclopedia_event_to_memory_item,
    collection_identity as encyclopedia_collection_identity,
    collection_memory_item as encyclopedia_collection_memory_item,
    collection_payload as encyclopedia_collection_payload,
)
from skeleton.frontier.equipment import (
    EquipmentBonuses,
    EquipmentLoadout,
    EquipmentSpec,
    calculate_equipment_bonuses,
    equip_item,
    quote_equipment_purchase,
)
from skeleton.frontier.gameplay_event_adapters import (
    gameplay_event_identity,
    gameplay_event_memory_item,
    gameplay_event_progress_digest,
    gameplay_event_progress_payload,
    gameplay_event_spec_digest,
    gameplay_event_spec_payload,
    gameplay_event_to_memory_item,
    gameplay_event_transition,
)
from skeleton.frontier.gameplay_events import (
    ChallengeCompletion,
    EventTimeRestriction,
    GameplayChallengeSpec,
    GameplayEventProgress,
    GameplayEventSpec,
    GameplayEventUpdatePlan,
    GameplayEventWindow,
    GameplayMilestoneClaimPlan,
    claim_event_milestone,
    event_spec_from_record as gameplay_event_from_record,
    event_time_restriction_active,
    event_window as gameplay_event_window,
    event_window_active as gameplay_event_window_active,
    initial_event_progress,
    next_event_milestone,
    season_for_date as gameplay_season_for_date,
    update_event_progress,
)

__all__ = [
    "AquariumDecorationSpec",
    "AquariumLikeLedger",
    "AquariumPosition",
    "AquariumPurchasePlan",
    "AquariumState",
    "AquariumTankSpec",
    "AquariumTankState",
    "AquariumThemeSpec",
    "BaitEquipPlan",
    "BaitLoadout",
    "BaitSpec",
    "BaitUsePlan",
    "BiotopeBonus",
    "BiotopeCatchPlan",
    "BiotopeProgress",
    "BiotopeSpec",
    "BiotopeStageSpec",
    "BreedingJob",
    "BreedingParent",
    "BreedingProgress",
    "BreedingSlotUpgradePlan",
    "CatchBonuses",
    "ChallengeCompletion",
    "CraftJob",
    "CraftingRecipe",
    "DecorationPlacementPlan",
    "DisplayFish",
    "EncyclopediaFishCatchPlan",
    "EnergyBoosterSpec",
    "EnergyPolicy",
    "EnergyState",
    "EquipmentBonuses",
    "EquipmentLoadout",
    "EquipmentSpec",
    "EventTimeRestriction",
    "FishCollectionState",
    "FishCollectionSummary",
    "FishDiscoveryStats",
    "FishMovePlan",
    "FishSpeciesSpec",
    "FishingSpotSpec",
    "GameplayChallengeSpec",
    "GameplayEventProgress",
    "GameplayEventSpec",
    "GameplayEventUpdatePlan",
    "GameplayEventWindow",
    "GameplayMilestoneClaimPlan",
    "OffspringPlan",
    "PlacedDecoration",
    "SpecialBreedSpec",
    "WorkshopState",
    "achievement_signals_from_offspring",
    "add_fish",
    "apply_booster",
    "apply_breeding_reward",
    "aquarium_affordability_shortfall",
    "aquarium_event",
    "aquarium_event_to_memory_item",
    "aquarium_identity",
    "aquarium_state_digest",
    "aquarium_state_memory_item",
    "aquarium_state_payload",
    "bait_effective_for_fish",
    "bait_from_record",
    "bait_purchase_cost",
    "biotope_achievement_from_record",
    "biotope_event",
    "biotope_event_to_memory_item",
    "biotope_identity",
    "biotope_progress_achievement_signals",
    "biotope_progress_digest",
    "biotope_progress_memory_item",
    "biotope_progress_payload",
    "biotope_requirement_signals",
    "breed_time_hours",
    "breeding_event_to_memory_item",
    "breeding_offspring_digest",
    "breeding_offspring_event",
    "breeding_offspring_identity",
    "breeding_slot_upgrade_plan",
    "breeding_speed_up_cost",
    "calculate_biotope_bonus",
    "calculate_catch_bonuses",
    "calculate_equipment_bonuses",
    "calculate_fish_value",
    "can_afford_bait_cost",
    "can_unlock_biotope",
    "can_unlock_biotope_stage",
    "can_unlock_spot",
    "claim_event_milestone",
    "collect_craft",
    "combine_external_bonuses",
    "compatible_species",
    "consume_energy",
    "decoration_from_record",
    "display_fish_from_record",
    "empty_fish_collection",
    "encyclopedia_collection_digest",
    "encyclopedia_collection_event",
    "encyclopedia_collection_identity",
    "encyclopedia_collection_memory_item",
    "encyclopedia_collection_payload",
    "encyclopedia_collection_summary",
    "encyclopedia_completion_percent",
    "encyclopedia_event_to_memory_item",
    "enter_biotope_stage",
    "equip_bait",
    "equip_item",
    "event_time_restriction_active",
    "gameplay_event_from_record",
    "gameplay_event_identity",
    "gameplay_event_memory_item",
    "gameplay_event_progress_digest",
    "gameplay_event_progress_payload",
    "gameplay_event_spec_digest",
    "gameplay_event_spec_payload",
    "gameplay_event_to_memory_item",
    "gameplay_event_transition",
    "gameplay_event_window",
    "gameplay_event_window_active",
    "gameplay_season_for_date",
    "generate_traits",
    "initial_aquarium",
    "initial_biotope_progress",
    "initial_event_progress",
    "matching_special_breed",
    "next_event_milestone",
    "offspring_plan",
    "parent_from_record",
    "place_decoration",
    "project_fish_entry",
    "purchase_decoration",
    "purchase_tank",
    "quote_equipment_purchase",
    "rarity_catch_counts",
    "record_biotope_achievement_catch",
    "record_biotope_catch",
    "record_fish_catch",
    "record_like",
    "record_visit",
    "refresh_breeding",
    "refresh_workshop",
    "regenerate_energy",
    "remove_fish",
    "restore_energy",
    "select_spot",
    "set_theme",
    "special_breed_from_record",
    "species_from_record",
    "spot_from_record",
    "spot_unlock_requirements",
    "start_breeding",
    "start_craft",
    "tank_from_record",
    "theme_from_record",
    "trait_value_multiplier",
    "unlock_biotope",
    "unlock_biotope_stage",
    "unlockable_biotope_stages",
    "unlockable_biotopes",
    "update_event_progress",
    "use_bait",
]
