"""Cross-plane interaction rules for deep Jeeves semantic reasoning.

The base composition engine only creates an interaction when a rule is explicit.
This module supplies rules for the causal/information/computational/
metacognitive/probability/predictive plane and selected research lenses.

Rules are hypotheses about how *reasoning operators* relate. They do not assert
that either underlying interpretation is true.
"""

from __future__ import annotations

from .semantic_frontier import LensInteractionKind, LensInteractionRule


def plane_interaction_rules() -> tuple[LensInteractionRule, ...]:
    return (
        LensInteractionRule(
            "backdoor_confounding",
            "covariate_shift",
            LensInteractionKind.CONDITIONS,
            "Distribution shift can change confounder balance, so predictive transport and causal adjustment must be evaluated together.",
            "Did the target-domain shift alter the distribution or support of variables required by the adjustment set?",
            "If adjustment remains valid and overlap is adequate, causal estimates should be more stable than unadjusted associations across the shift.",
            tangent_axis_hint="causal",
        ),
        LensInteractionRule(
            "collider_selection_bias",
            "rare_event_denominator",
            LensInteractionKind.REFRAMES,
            "A corrected denominator can still be biased when inclusion depends on a collider or outcome-related selection mechanism.",
            "Does the denominator describe all exposure opportunities, or only a selected subset created by downstream conditioning?",
            "Exposure normalization alone will not remove a selection-induced association when collider structure remains.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "mediator_chain",
            "intervention_invariance",
            LensInteractionKind.REINFORCES,
            "A proposed mediator becomes more credible when its conditional mechanism behaves stably under relevant interventions.",
            "Which mediator relation should remain invariant, and which relation is directly intervened upon?",
            "Interventions upstream of a real mediator should alter mediator distributions while preserving unaffected mechanism conditionals.",
            tangent_axis_hint="causal",
        ),
        LensInteractionRule(
            "causal_direction_reversal",
            "leading_indicator",
            LensInteractionKind.CONFLICTS,
            "A leading indicator can forecast an outcome without causing it, while reverse or common-cause explanations remain possible.",
            "What observation discriminates predictive precedence from actual causal direction?",
            "The indicator may retain out-of-sample predictive value even when intervention or structural evidence rejects the proposed causal direction.",
            tangent_axis_hint="causal",
        ),
        LensInteractionRule(
            "mechanism_transport",
            "covariate_shift",
            LensInteractionKind.CONDITIONS,
            "Transport can remain possible under covariate shift when the relevant conditional mechanism is invariant and support is sufficient.",
            "Is target support adequate for the source mechanism, and which mechanism components are assumed invariant?",
            "Appropriate reweighting should recover target performance only when the transported conditional mechanism remains stable.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "selection_on_treatment_effect",
            "prediction_interval_failure",
            LensInteractionKind.REFRAMES,
            "Coverage measured on selectively retained responders can look adequate while failing in the intended population.",
            "Is empirical interval coverage evaluated on a sample whose inclusion depends on response or outcome?",
            "Coverage should change after accounting for selection if the original evaluation population was response-dependent.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "mutual_information_gain",
            "value_of_information",
            LensInteractionKind.CONDITIONS,
            "Information gain is only decision value when it can change a consequential action enough to justify acquisition cost.",
            "Which posterior changes would actually alter the chosen action or expected utility?",
            "A high-information probe can have low decision value when it does not cross any action boundary.",
            tangent_axis_hint="semantic",
        ),
        LensInteractionRule(
            "entropy_bottleneck",
            "state_space_explosion",
            LensInteractionKind.REFRAMES,
            "Compression may be necessary to control combinatorial state growth, but an overly narrow bottleneck can erase decision-relevant distinctions.",
            "Which state distinctions can be safely merged without changing reachable decisions or predictions?",
            "A good abstraction should reduce search complexity while preserving task-relevant transition or value structure.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "redundancy_synergy",
            "model_mixture_uncertainty",
            LensInteractionKind.ORTHOGONAL,
            "Signal-level synergy and model-level disagreement are distinct: combined features can be synergistic even when models disagree structurally.",
            "Is uncertainty caused by missing joint signal information, competing model structures, or both?",
            "Adding a synergistic signal can improve each component model without eliminating between-model disagreement.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "minimum_description_length",
            "algorithmic_complexity_budget",
            LensInteractionKind.REINFORCES,
            "Compact explanatory structure and computational tractability often align, but model code length and execution complexity remain distinct costs.",
            "Does the shorter description also reduce computation, or merely encode a costly procedure compactly?",
            "Some MDL-favored models will remain computationally expensive; agreement should be tested rather than assumed.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "surprisal_shift",
            "concept_drift",
            LensInteractionKind.CONDITIONS,
            "Persistent predictive surprisal is a change signal, while concept drift is one specific explanation for that signal.",
            "Did surprisal rise because P(Y|X) changed, because P(X) changed, or because the model was always misspecified?",
            "Concept-drift adaptation should reduce persistent conditional surprisal when relationship change is the driver.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "channel_capacity_constraint",
            "queue_backpressure",
            LensInteractionKind.REINFORCES,
            "A rate-capacity mismatch can manifest operationally as queue growth and upstream backpressure.",
            "Is effective arrival information rate persistently above the service or channel capacity?",
            "When overload is causal, reducing source rate or increasing capacity should reduce both queue depth and backpressure.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "concurrency_interleaving",
            "transactional_atomicity",
            LensInteractionKind.REINFORCES,
            "Alternative interleavings are a primary way partial transactional state becomes observable.",
            "Which admissible schedule exposes a strict subset of the intended atomic update?",
            "Serializing or enforcing the missing atomic boundary should eliminate the interleaving-specific partial-state observation.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "idempotence_boundary",
            "interface_contract_drift",
            LensInteractionKind.CONDITIONS,
            "A retry contract can drift even when an operation retains the same API shape, turning previously safe repetition into duplicate effects.",
            "Did either side change what counts as the operation's externally visible effect or identity key?",
            "Contract-aware idempotency tests should fail at the same version boundary where duplicate side effects begin.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "representation_invariance",
            "abstraction_leak",
            LensInteractionKind.CONFLICTS,
            "A claimed semantics-preserving representation change conflicts with evidence that lower-layer representation details alter higher-layer meaning.",
            "Is the observed difference semantic, or only performance and timing sensitivity outside the equivalence contract?",
            "A true abstraction leak should survive controls for semantics-preserving behavior and remain tied to lower-layer representation details.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "calibration_gap_monitor",
            "prediction_interval_failure",
            LensInteractionKind.REINFORCES,
            "Probability calibration and interval coverage are complementary calibration views and can fail independently.",
            "Are point probabilities calibrated while interval coverage is wrong, or vice versa?",
            "A comprehensive calibration defect should appear in the corresponding point and/or interval diagnostics rather than a single aggregate score.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "hypothesis_lockin",
            "confirmation_search_bias",
            LensInteractionKind.REINFORCES,
            "Failure to generate alternatives and confirmatory query choice can mutually reinforce a self-sealing reasoning process.",
            "What discriminating query would be chosen if a serious alternative hypothesis were required?",
            "Introducing an explicit alternative set should increase falsifier-oriented queries and revision frequency when lock-in was present.",
            tangent_axis_hint="adversarial",
        ),
        LensInteractionRule(
            "stopping_rule_sensitivity",
            "sequential_evidence_accumulation",
            LensInteractionKind.CONDITIONS,
            "Sequential evidence is safe under optional continuation only when the chosen evidence process supports the stopping policy.",
            "What stopping behavior is permitted by the evidence process's validity guarantee?",
            "Stopping-rule effects should disappear or remain bounded when an anytime-valid sequential method is correctly applied.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "epistemic_debt",
            "reasoning_loop_detection",
            LensInteractionKind.GENERATES_TANGENT,
            "Repeated reasoning can accumulate deferred assumptions instead of resolving them, producing both loop behavior and epistemic debt.",
            "Which unresolved assumption can be converted into a concrete external test that breaks the loop?",
            "Executing a high-value discriminating test should reduce both repeated-state similarity and the unresolved-assumption inventory.",
            tangent_axis_hint="adversarial",
        ),
        LensInteractionRule(
            "model_uncertainty_separation",
            "aleatoric_epistemic_split",
            LensInteractionKind.REINFORCES,
            "Both lenses prevent irreducible randomness from being conflated with uncertainty that could shrink through data or model improvement.",
            "Which uncertainty component is reducible by more data, richer structure, or broader model classes?",
            "Additional informative evidence should reduce epistemic/model uncertainty more than irreducible outcome variation.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "dependence_structure",
            "forecast_reconciliation",
            LensInteractionKind.CONDITIONS,
            "Reconciled hierarchical forecasts inherit dependence across components; coherence constraints do not create independence.",
            "What covariance or dependence structure remains after enforcing aggregation constraints?",
            "Ignoring dependence will understate or distort aggregate uncertainty even when point forecasts reconcile exactly.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "posterior_predictive_check",
            "regime_switch_forecast",
            LensInteractionKind.REFRAMES,
            "A regime model should be judged by whether its fitted latent-state process reproduces relevant observed temporal features.",
            "Which posterior predictive discrepancy would expose an overfit or missing regime dynamic?",
            "A useful regime model should reproduce dwell times, transitions, and target discrepancies better than a simpler no-switch baseline.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "model_mixture_uncertainty",
            "forecast_horizon_decay",
            LensInteractionKind.CONDITIONS,
            "Longer horizons can amplify disagreement between plausible models even when near-term predictions are similar.",
            "How does between-model variance change with forecast horizon?",
            "Structural model disagreement should contribute an increasing share of predictive uncertainty at horizons where model dynamics diverge.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "base_rate_neglect",
            "rare_event_denominator",
            LensInteractionKind.REINFORCES,
            "Both lenses restore missing population context: one for priors and one for exposure rates.",
            "Are both prevalence and exposure opportunity represented in the probability being interpreted?",
            "Adding the appropriate prior and denominator should reduce exaggerated rare-event interpretations caused by raw counts or likelihood-only reasoning.",
            tangent_axis_hint="probabilistic",
        ),
        LensInteractionRule(
            "observability_gap",
            "model_uncertainty_separation",
            LensInteractionKind.REINFORCES,
            "Poor observability creates epistemic uncertainty that should not be mislabeled as irreducible process randomness.",
            "Which hidden state distinctions would become identifiable under an additional measurement?",
            "Adding an informative observable should shrink epistemic/model uncertainty if hidden-state ambiguity is the driver.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "event_time_processing_time",
            "concept_drift",
            LensInteractionKind.CONDITIONS,
            "Out-of-order processing can mimic drift if model evaluation compares predictions and labels on the wrong clock.",
            "Does the apparent performance change persist after reconstructing event-time order?",
            "Clock-correct evaluation should remove pseudo-drift caused by delayed arrival while preserving genuine conditional change.",
            tangent_axis_hint="temporal",
        ),
        LensInteractionRule(
            "interface_contract_drift",
            "prediction_interval_failure",
            LensInteractionKind.GENERATES_TANGENT,
            "A changed schema or unit contract can silently invalidate uncertainty estimates even when the predictor still executes.",
            "Did interval failures begin at the same interface or representation boundary where the input contract changed?",
            "Restoring the prior contract or adapting preprocessing should improve coverage if contract drift caused the failure.",
            tangent_axis_hint="system",
        ),
        LensInteractionRule(
            "queue_backpressure",
            "forecast_horizon_decay",
            LensInteractionKind.CONDITIONS,
            "Operational lag can age observations before they reach the predictor, effectively increasing forecast horizon.",
            "How much queue delay is added to the nominal prediction horizon?",
            "Reducing queue latency should improve short-horizon forecast quality when staleness rather than model structure is limiting performance.",
            tangent_axis_hint="predictive",
        ),
        LensInteractionRule(
            "pluralistic_ignorance",
            "value_of_information",
            LensInteractionKind.GENERATES_TANGENT,
            "Private elicitation can be valuable when public behavior poorly reveals the distribution of private beliefs.",
            "Would a confidential measurement change the coordination decision enough to justify collecting it?",
            "Private elicitation should have higher decision value when perceived consensus diverges strongly from actual private reports.",
            tangent_axis_hint="social",
        ),
        LensInteractionRule(
            "control_loop_delay",
            "reasoning_loop_detection",
            LensInteractionKind.REFRAMES,
            "Repeated corrective reasoning can be a delayed-feedback control problem rather than purely cognitive repetition.",
            "Is each corrective cycle responding to state produced before the previous correction took effect?",
            "Reducing feedback delay or waiting for state settlement should reduce oscillatory reasoning when stale feedback is the driver.",
            tangent_axis_hint="system",
        ),
    )


def plane_interaction_keys() -> tuple[tuple[str, str], ...]:
    return tuple(rule.key for rule in plane_interaction_rules())
