"""Governed dual-rival game-builder runtime contracts.

The package contains deterministic control-plane primitives only. Model/provider
execution remains outside the authority boundary and must enter through governed
candidate, canon, rights, atom-lineage, and evidence contracts.
"""

from .atomizer import ArtifactAtom, AtomGraph, AtomGraphError, AtomSourceBinding
from .canon import CanonAssertion, CanonError, CanonLedger, CharacterKnowledge
from .contracts import (
    ArtifactIdentity,
    Candidate,
    Challenge,
    EffortMode,
    EvaluatorProvenance,
    GateResult,
    PromotionReceipt,
    ProducerProvenance,
    Rival,
    Stage,
    canonical_digest,
)
from .dual_rival_forge import DualRivalForge, ForgeStateError
from .control_plane import ControlPlaneError, ControlledStatus, ForgeControlPlane
from .experience_eval import (
    EXPERIENCE_METRICS,
    ExperienceDefect,
    ExperienceEvaluationError,
    ExperienceObservation,
    ExperiencePromotionDecision,
    ExperienceReport,
    build_experience_report,
    evaluate_experience_promotion,
    normalize_experience_metrics,
)
from .evaluation import (
    EvaluationError,
    EvaluationPanel,
    JudgeVerdict,
    PanelDecision,
    blind_candidate_token,
)
from .quality_debt import (
    DebtItem,
    DebtSeverity,
    QualityDebtError,
    QualityDebtLedger,
)
from .resource_governor import (
    ResourceDelta,
    ResourceEnvelope,
    ResourceGovernor,
    ResourceLimitError,
    ResourceSnapshot,
)
from .resilience import (
    DissentLedger,
    ImpactCalibrationReceipt,
    ImpactGraph,
    Invariant,
    InvariantRegistry,
    InvariantRevisionReceipt,
    NoveltyRecord,
    NoveltyReservoir,
    Objection,
    ResilienceError,
)
from .release import (
    CriticalGateQualification,
    FamilyQualification,
    ForgeReleaseBinding,
    GoldMasterBundle,
    GoldMasterTribunal,
    GoldMasterVerdict,
    ReleaseArbitrationError,
    TribunalVote,
)
from .deep_assurance import (
    ClosureCertificate,
    ComplexityDecision,
    ComplexityGovernor,
    ComplexitySnapshot,
    ConstraintProofSet,
    ConstraintResult,
    DeepAssuranceError,
    EvidenceMerkleLedger,
    GranularityCoverage,
    HermeticTransformRegistry,
    IntentInvariant,
    IntentPreservationGate,
    InteractionMatrix,
    KnowledgeIngestionFirewall,
    KnowledgeSource,
    MentalModelProbe,
    PlayerMentalModelGate,
    ProjectResurrectionRegistry,
    RareEventObservation,
    RequirementClosureLedger,
    RequirementProof,
    ResurrectionPoint,
    ResurrectionVerification,
    TailRiskLab,
    TelemetryAggregate,
    TelemetryFeedbackGate,
    TransformReceipt,
)
from .evaluator_provenance import (
    EvaluatorProvenanceBindingError,
    evaluator_provenance_from_canonical_execution,
    gate_result_from_canonical_execution,
    judge_verdict_from_canonical_execution,
)
from .producer_provenance import (
    ProducerProvenanceBindingError,
    candidate_from_canonical_execution,
    producer_provenance_from_canonical_execution,
)
from .rights import (
    IncorporationDecision,
    RightsError,
    RightsLedger,
    RightsState,
    SimilarityFinding,
    SimilarityRisk,
    SourceRecord,
    UseKind,
)

__all__ = [
    "ArtifactAtom",
    "ArtifactIdentity",
    "AtomGraph",
    "AtomGraphError",
    "AtomSourceBinding",
    "Candidate",
    "CanonAssertion",
    "CanonError",
    "CanonLedger",
    "Challenge",
    "CharacterKnowledge",
    "DualRivalForge",
    "EffortMode",
    "EvaluatorProvenance",
    "EvaluatorProvenanceBindingError",
    "evaluator_provenance_from_canonical_execution",
    "gate_result_from_canonical_execution",
    "judge_verdict_from_canonical_execution",
    "ForgeStateError",
    "GateResult",
    "IncorporationDecision",
    "PromotionReceipt",
    "ProducerProvenance",
    "ProducerProvenanceBindingError",
    "candidate_from_canonical_execution",
    "producer_provenance_from_canonical_execution",
    "RightsError",
    "RightsLedger",
    "RightsState",
    "Rival",
    "SimilarityFinding",
    "SimilarityRisk",
    "SourceRecord",
    "Stage",
    "UseKind",
    "canonical_digest",
    "ControlPlaneError",
    "ControlledStatus",
    "DebtItem",
    "DebtSeverity",
    "EvaluationError",
    "normalize_experience_metrics",
    "evaluate_experience_promotion",
    "build_experience_report",
    "ExperienceReport",
    "ExperiencePromotionDecision",
    "ExperienceObservation",
    "ExperienceEvaluationError",
    "ExperienceDefect",
    "EXPERIENCE_METRICS",
    "EvaluationPanel",
    "ForgeControlPlane",
    "JudgeVerdict",
    "PanelDecision",
    "QualityDebtError",
    "QualityDebtLedger",
    "ResourceDelta",
    "ResourceEnvelope",
    "ResourceGovernor",
    "ResourceLimitError",
    "ResourceSnapshot",
    "blind_candidate_token",
    "DissentLedger",
    "ImpactCalibrationReceipt",
    "ImpactGraph",
    "Invariant",
    "InvariantRegistry",
    "InvariantRevisionReceipt",
    "NoveltyRecord",
    "NoveltyReservoir",
    "Objection",
    "ResilienceError",
    "FamilyQualification",
    "ForgeReleaseBinding",
    "GoldMasterBundle",
    "GoldMasterTribunal",
    "GoldMasterVerdict",
    "ReleaseArbitrationError",
    "TribunalVote",
    "CriticalGateQualification",
    "ClosureCertificate",
    "ComplexityDecision",
    "ComplexityGovernor",
    "ComplexitySnapshot",
    "ConstraintProofSet",
    "ConstraintResult",
    "DeepAssuranceError",
    "EvidenceMerkleLedger",
    "GranularityCoverage",
    "HermeticTransformRegistry",
    "IntentInvariant",
    "IntentPreservationGate",
    "InteractionMatrix",
    "KnowledgeIngestionFirewall",
    "KnowledgeSource",
    "MentalModelProbe",
    "PlayerMentalModelGate",
    "ProjectResurrectionRegistry",
    "RareEventObservation",
    "RequirementClosureLedger",
    "RequirementProof",
    "ResurrectionPoint",
    "ResurrectionVerification",
    "TailRiskLab",
    "TelemetryAggregate",
    "TelemetryFeedbackGate",
    "TransformReceipt",
]
