"""Governed dual-rival game-builder runtime contracts.

The package contains deterministic control-plane primitives only. Model/provider
execution remains outside the authority boundary and must enter through governed
candidate, canon, rights, atom-lineage, and evidence contracts.
"""

from .atomizer import ArtifactAtom, AtomGraph, AtomGraphError, AtomSourceBinding
from .canon import CanonAssertion, CanonError, CanonLedger, CharacterKnowledge
from .contracts import (
    ArtifactIdentity,
    Candidate,
    Challenge,
    EffortMode,
    EvaluatorProvenance,
    GateResult,
    PromotionReceipt,
    ProducerProvenance,
    Rival,
    Stage,
    canonical_digest,
)
from .dual_rival_forge import DualRivalForge, ForgeStateError
from .control_plane import ControlPlaneError, ControlledStatus, ForgeControlPlane
from .experience_eval import (
    EXPERIENCE_METRICS,
    ExperienceDefect,
    ExperienceEvaluationError,
    ExperienceObservation,
    ExperiencePromotionDecision,
    ExperienceReport,
    build_experience_report,
    evaluate_experience_promotion,
    normalize_experience_metrics,
)
from .evaluation import (
    EvaluationError,
    EvaluationPanel,
    JudgeVerdict,
    PanelDecision,
    blind_candidate_token,
)
from .quality_debt import (
    DebtItem,
    DebtSeverity,
    QualityDebtError,
    QualityDebtLedger,
)
from .resource_governor import (
    ResourceDelta,
    ResourceEnvelope,
    ResourceGovernor,
    ResourceLimitError,
    ResourceSnapshot,
)
from .resilience import (
    DissentLedger,
    ImpactCalibrationReceipt,
    ImpactGraph,
    Invariant,
    InvariantRegistry,
    InvariantRevisionReceipt,
    NoveltyRecord,
    NoveltyReservoir,
    Objection,
    ResilienceError,
)
from .release import (
    CriticalGateQualification,
    FamilyQualification,
    ForgeReleaseBinding,
    GoldMasterBundle,
    GoldMasterTribunal,
    GoldMasterVerdict,
    ReleaseArbitrationError,
    TribunalVote,
)
from .deep_assurance import (
    ClosureCertificate,
    ComplexityDecision,
    ComplexityGovernor,
    ComplexitySnapshot,
    ConstraintProofSet,
    ConstraintResult,
    DeepAssuranceError,
    EvidenceMerkleLedger,
    GranularityCoverage,
    HermeticTransformRegistry,
    IntentInvariant,
    IntentPreservationGate,
    InteractionMatrix,
    KnowledgeIngestionFirewall,
    KnowledgeSource,
    MentalModelProbe,
    PlayerMentalModelGate,
    ProjectResurrectionRegistry,
    RareEventObservation,
    RequirementClosureLedger,
    RequirementProof,
    ResurrectionPoint,
    ResurrectionVerification,
    TailRiskLab,
    TelemetryAggregate,
    TelemetryFeedbackGate,
    TransformReceipt,
)
from .evaluator_provenance import (
    EvaluatorProvenanceBindingError,
    evaluator_provenance_from_canonical_execution,
    gate_result_from_canonical_execution,
    judge_verdict_from_canonical_execution,
)
from .producer_provenance import (
    ProducerProvenanceBindingError,
    candidate_from_canonical_execution,
    producer_provenance_from_canonical_execution,
)
from .rights import (
    IncorporationDecision,
    RightsError,
    RightsLedger,
    RightsState,
    SimilarityFinding,
    SimilarityRisk,
    SourceRecord,
    UseKind,
)

__all__ = [
    "ArtifactAtom",
    "ArtifactIdentity",
    "AtomGraph",
    "AtomGraphError",
    "AtomSourceBinding",
    "Candidate",
    "CanonAssertion",
    "CanonError",
    "CanonLedger",
    "Challenge",
    "CharacterKnowledge",
    "DualRivalForge",
    "EffortMode",
    "EvaluatorProvenance",
    "EvaluatorProvenanceBindingError",
    "evaluator_provenance_from_canonical_execution",
    "gate_result_from_canonical_execution",
    "judge_verdict_from_canonical_execution",
    "ForgeStateError",
    "GateResult",
    "IncorporationDecision",
    "PromotionReceipt",
    "ProducerProvenance",
    "ProducerProvenanceBindingError",
    "candidate_from_canonical_execution",
    "producer_provenance_from_canonical_execution",
    "RightsError",
    "RightsLedger",
    "RightsState",
    "Rival",
    "SimilarityFinding",
    "SimilarityRisk",
    "SourceRecord",
    "Stage",
    "UseKind",
    "canonical_digest",
    "ControlPlaneError",
    "ControlledStatus",
    "DebtItem",
    "DebtSeverity",
    "EvaluationError",
    "normalize_experience_metrics",
    "evaluate_experience_promotion",
    "build_experience_report",
    "ExperienceReport",
    "ExperiencePromotionDecision",
    "ExperienceObservation",
    "ExperienceEvaluationError",
    "ExperienceDefect",
    "EXPERIENCE_METRICS",
    "EvaluationPanel",
    "ForgeControlPlane",
    "JudgeVerdict",
    "PanelDecision",
    "QualityDebtError",
    "QualityDebtLedger",
    "ResourceDelta",
    "ResourceEnvelope",
    "ResourceGovernor",
    "ResourceLimitError",
    "ResourceSnapshot",
    "blind_candidate_token",
    "DissentLedger",
    "ImpactCalibrationReceipt",
    "ImpactGraph",
    "Invariant",
    "InvariantRegistry",
    "InvariantRevisionReceipt",
    "NoveltyRecord",
    "NoveltyReservoir",
    "Objection",
    "ResilienceError",
    "FamilyQualification",
    "ForgeReleaseBinding",
    "GoldMasterBundle",
    "GoldMasterTribunal",
    "GoldMasterVerdict",
    "ReleaseArbitrationError",
    "TribunalVote",
    "CriticalGateQualification",
    "ClosureCertificate",
    "ComplexityDecision",
    "ComplexityGovernor",
    "ComplexitySnapshot",
    "ConstraintProofSet",
    "ConstraintResult",
    "DeepAssuranceError",
    "EvidenceMerkleLedger",
    "GranularityCoverage",
    "HermeticTransformRegistry",
    "IntentInvariant",
    "IntentPreservationGate",
    "InteractionMatrix",
    "KnowledgeIngestionFirewall",
    "KnowledgeSource",
    "MentalModelProbe",
    "PlayerMentalModelGate",
    "ProjectResurrectionRegistry",
    "RareEventObservation",
    "RequirementClosureLedger",
    "RequirementProof",
    "ResurrectionPoint",
    "ResurrectionVerification",
    "TailRiskLab",
    "TelemetryAggregate",
    "TelemetryFeedbackGate",
    "TransformReceipt",
]


# The persistent knowledge library is loaded only when requested. It never
# implicitly creates a database, crawls a URL, or promotes a game design.
from importlib import import_module as _game_builder_import_module

_KNOWLEDGE_EXPORTS = {
    "EvolutionPractice": ".evolution_practice",
    "EvolutionPracticePack": ".evolution_practice",
    "practice_evolution_games": ".evolution_practice",
    "CreditsError": ".asset_credits",
    "AttributionEntry": ".asset_credits",
    "CreditsBundle": ".asset_credits",
    "compile_game_credits": ".asset_credits",
    "export_game_credits": ".asset_credits",
    "NativeReleaseGateReport": ".release_pipeline",
    "run_native_release_gate": ".release_pipeline",
    "RetroArtifactError": ".native_retro_artifact",
    "RetroArtifactReceipt": ".native_retro_artifact",
    "inspect_original_retro_artifact": ".native_retro_artifact",
    "ExecutableFormatError": ".native_binary_structure",
    "ExecutableStructureReceipt": ".native_binary_structure",
    "verify_native_executable_structure": ".native_binary_structure",
    "StructurallyVerifiedNativeReleaseReport": ".release_pipeline",
    "run_structurally_verified_native_release_gate": ".release_pipeline",
    "NativeIntakeError": ".native_release_intake",
    "NativeIntakeReceipt": ".native_release_intake",
    "verify_native_release_intake": ".native_release_intake",
    "SignedReviewerRegistry": ".release_trust_anchor",
    "PinnedReviewerResult": ".release_trust_anchor",
    "evaluate_pinned_independent_review": ".release_trust_anchor",
    "PinnedNativeReleaseGateReport": ".release_pipeline",
    "run_pinned_native_release_gate": ".release_pipeline",
    "ReleaseReviewError": ".release_assurance",
    "ReleaseChannel": ".release_assurance",
    "ReviewRole": ".release_assurance",
    "ReviewDomain": ".release_assurance",
    "ReviewDecision": ".release_assurance",
    "ReleaseReadiness": ".release_assurance",
    "ReleaseCandidate": ".release_assurance",
    "TrustedReviewer": ".release_assurance",
    "ReviewAttestation": ".release_assurance",
    "ReleaseReviewReceipt": ".release_assurance",
    "evaluate_independent_review": ".release_assurance",
    "MediaScreenError": ".media_similarity",
    "MediaFingerprint": ".media_similarity",
    "MediaMatchEvidence": ".media_similarity",
    "fingerprint_image": ".media_similarity",
    "fingerprint_wav": ".media_similarity",
    "compare_media": ".media_similarity",
    "OriginalityError": ".plagiarism_guard",
    "AttributionStatus": ".plagiarism_guard",
    "UseBasis": ".plagiarism_guard",
    "AssetDisposition": ".plagiarism_guard",
    "OriginalityDisposition": ".plagiarism_guard",
    "AssetDeclaration": ".plagiarism_guard",
    "ExpressionSample": ".plagiarism_guard",
    "ExpressiveOverlap": ".plagiarism_guard",
    "OriginalityReport": ".plagiarism_guard",
    "find_expression_overlap": ".plagiarism_guard",
    "audit_game_originality": ".plagiarism_guard",
    "compile_originality_gated_desktop": ".legal_native_export",
    "ClearedSourceExportError": ".legal_native_export",
    "LegalNativeDesktopSource": ".legal_native_export",
    "compile_rights_aware_desktop": ".legal_native_export",
    "export_rights_aware_desktop": ".legal_native_export",
    "HistoricalRightsCandidate": ".legal_census",
    "HistoricalRightsCensus": ".legal_census",
    "catalog_rights_census": ".legal_census",
    "HomebrewPolicyError": ".legal_paths",
    "Jurisdiction": ".legal_paths",
    "CreativeMode": ".legal_paths",
    "LegalDisposition": ".legal_paths",
    "MaterialKind": ".legal_paths",
    "MaterialRecord": ".legal_paths",
    "HardwareAccessFacts": ".legal_paths",
    "InteroperabilityFacts": ".legal_paths",
    "HomebrewLegalRequest": ".legal_paths",
    "HomebrewLegalAssessment": ".legal_paths",
    "legal_authorities": ".legal_paths",
    "assess_homebrew": ".legal_paths",
    "hardware_rights_matrix": ".legal_paths",
    "RightsAwarePortProposal": ".legal_port_bridge",
    "propose_rights_aware_port": ".legal_port_bridge",
    "MachineArchiveError": ".archive_import",
    "MachineRecord": ".archive_import",
    "MachineSnapshot": ".archive_import",
    "import_mame_listxml": ".archive_import",
    "export_review_queue": ".archive_import",
    "GameEvolutionError": ".evolution_archive",
    "EvolutionNode": ".evolution_archive",
    "EvolutionArchive": ".evolution_archive",
    "EvolutionStage": ".evolution_archive",
    "EvolutionCampaign": ".evolution_archive",
    "parse_evolution_archive": ".evolution_archive",
    "default_evolution_archive": ".evolution_archive",
    "plan_evolution_campaign": ".evolution_archive",
    "archive_coverage_report": ".evolution_archive",
    "GameBoyColorSourceError": ".game_boy_color_native_export",
    "GameBoyColorSourceProject": ".game_boy_color_native_export",
    "compile_native_game_boy_color": ".game_boy_color_native_export",
    "export_native_game_boy_color": ".game_boy_color_native_export",
    "GameBoySourceError": ".game_boy_native_export",
    "GameBoySourceProject": ".game_boy_native_export",
    "compile_native_game_boy": ".game_boy_native_export",
    "export_native_game_boy": ".game_boy_native_export",
    "SMSNativeError": ".sms_native_export",
    "SMSSourceProject": ".sms_native_export",
    "compile_native_sms": ".sms_native_export",
    "export_native_sms": ".sms_native_export",
    "make_sms": ".sms_rom",
    "verify_sms": ".sms_rom",
    "MSX1NativeError": ".msx1_native_export",
    "MSX1SourceProject": ".msx1_native_export",
    "compile_native_msx1": ".msx1_native_export",
    "export_native_msx1": ".msx1_native_export",
    "make_msx1_rom": ".msx1_rom",
    "verify_msx1_rom": ".msx1_rom",
    "SpectrumNativeError": ".spectrum_native_export",
    "SpectrumSourceProject": ".spectrum_native_export",
    "compile_native_spectrum": ".spectrum_native_export",
    "export_native_spectrum": ".spectrum_native_export",
    "make_tape": ".spectrum_tap",
    "verify_tape": ".spectrum_tap",
    "Apple2NativeError": ".apple2_native_export",
    "Apple2SourceProject": ".apple2_native_export",
    "compile_native_apple2": ".apple2_native_export",
    "export_native_apple2": ".apple2_native_export",
    "Atari8BitNativeError": ".atari8_native_export",
    "Atari8BitSourceProject": ".atari8_native_export",
    "compile_native_atari8": ".atari8_native_export",
    "export_native_atari8": ".atari8_native_export",
    "NativeDOSError": ".dos_native_export",
    "NativeDOSSourceProject": ".dos_native_export",
    "compile_native_dos": ".dos_native_export",
    "export_native_dos": ".dos_native_export",
    "build_native_evolution": ".native_evolution_cli",
    "NativePortfolioError": ".native_portfolio_cli",
    "compile_native_portfolio": ".native_portfolio_cli",
    "NativeC64Error": ".c64_native_export",
    "NativeC64SourceProject": ".c64_native_export",
    "compile_native_c64": ".c64_native_export",
    "export_native_c64": ".c64_native_export",
    "GameBoyReplayError": ".game_boy_memory_replay",
    "plan_game_boy_memory_replay": ".game_boy_memory_replay",
    "export_game_boy_memory_replay": ".game_boy_memory_replay",
    "NativeNESError": ".nes_native_export",
    "NativeNESSourceProject": ".nes_native_export",
    "compile_native_nes": ".nes_native_export",
    "export_native_nes": ".nes_native_export",
    "EvolutionNativeStage": ".evolution_native_sources",
    "EvolutionNativeSourcePack": ".evolution_native_sources",
    "compile_evolution_native_sources": ".evolution_native_sources",
    "export_evolution_native_sources": ".evolution_native_sources",
    "NativeDesktopExportError": ".desktop_native_export",
    "NativeDesktopSourceProject": ".desktop_native_export",
    "compile_native_desktop": ".desktop_native_export",
    "export_native_desktop_source": ".desktop_native_export",
    "editor_platform_options": ".editor_platforms",
    "editor_portability_context": ".editor_platforms",
    "editor_platform_form": ".editor_platforms",
    "PlatformProfile": ".platform_registry",
    "PlatformRegistry": ".platform_registry",
    "PlatformRegistryError": ".platform_registry",
    "default_registry": ".platform_registry",
    "lookup_platform": ".platform_registry",
    "list_platforms": ".platform_registry",
    "parse_registry": ".platform_registry",
    "HomebrewSource": ".port_planner",
    "PortMode": ".port_planner",
    "PortRequest": ".port_planner",
    "PortAction": ".port_planner",
    "PortBlueprint": ".port_planner",
    "PortPlanningError": ".port_planner",
    "compile_port": ".port_planner",
    "compile_port_route": ".port_planner",
    "KnowledgeError": ".reviewed_knowledge",
    "KnowledgePolicy": ".reviewed_knowledge",
    "ReviewedNote": ".reviewed_knowledge",
    "ReviewedDocument": ".reviewed_knowledge",
    "RevisionReceipt": ".reviewed_knowledge",
    "KnowledgeHit": ".reviewed_knowledge",
    "KnowledgeBrief": ".reviewed_knowledge",
    "ReviewedKnowledgeStore": ".reviewed_knowledge",
    "ResearchHandoffError": ".knowledge_rights_bridge",
    "ClearedResearchSource": ".knowledge_rights_bridge",
    "ClearedResearchPacket": ".knowledge_rights_bridge",
    "clear_research_for_design": ".knowledge_rights_bridge",
    "require_cleared_research_current": ".knowledge_rights_bridge",
    "GameBuildIntent": ".playable_world",
    "TileLevel": ".playable_world",
    "PlayableWorld": ".playable_world",
    "PlayableWorldError": ".playable_world",
    "generate_playable_world": ".playable_world",
    "solve_safe_path": ".playable_world",
    "GameplayError": ".playable_simulation",
    "PlayState": ".playable_simulation",
    "ActionReceipt": ".playable_simulation",
    "GameReplay": ".playable_simulation",
    "initial_state": ".playable_simulation",
    "advance": ".playable_simulation",
    "play_actions": ".playable_simulation",
    "verify_replay": ".playable_simulation",
    "demonstrate_solvable": ".playable_simulation",
    "PlayableHTML": ".playable_export",
    "PlayableExportError": ".playable_export",
    "render_playable_world": ".playable_export",
    "write_playable_html": ".playable_export",
    "PlayableCompilationError": ".playable_compiler",
    "CompiledPlayableProject": ".playable_compiler",
    "compile_original_game": ".playable_compiler",
    "compile_game_from_reviewed_research": ".playable_compiler",
    "export_compiled_project": ".playable_compiler",
    "PlayabilityAnalysisError": ".playability_analysis",
    "LevelExperience": ".playability_analysis",
    "PlayabilityFinding": ".playability_analysis",
    "PlayabilityReport": ".playability_analysis",
    "CohortExperience": ".playability_analysis",
    "analyze_replay": ".playability_analysis",
    "aggregate_playability": ".playability_analysis",
}


def __getattr__(name: str):
    module = _KNOWLEDGE_EXPORTS.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(_game_builder_import_module(module, __name__), name)
    globals()[name] = value
    return value


__all__ += list(_KNOWLEDGE_EXPORTS)
