"""Verified semantic compilation and evidence-bearing decompilation for Jeeves."""

from .ir import (
    BasicBlock,
    ControlFlowGraph,
    Effect,
    FunctionIR,
    IRDiagnostic,
    IRModule,
    IRType,
    IRVerifier,
    Instruction,
    Severity,
    SourceProvenance,
    SSAValue,
    Terminator,
    TerminatorKind,
    VerificationReport,
)
from .pipeline import (
    AbstractState,
    AbstractValue,
    AbstractValueKind,
    CompilationPass,
    PassContract,
    PassManager,
    PassRecord,
    PassSemantics,
    TranslationValidation,
    TranslationValidator,
)
from .decompiler import (
    DecompilationArtifact,
    Decompiler,
    LossKind,
    LossRecord,
    RecoveredType,
    RecoveryConfidence,
)

__all__ = [
    "AbstractState",
    "AbstractValue",
    "AbstractValueKind",
    "BasicBlock",
    "CompilationPass",
    "ControlFlowGraph",
    "DecompilationArtifact",
    "Decompiler",
    "Effect",
    "FunctionIR",
    "IRDiagnostic",
    "IRModule",
    "IRType",
    "IRVerifier",
    "Instruction",
    "LossKind",
    "LossRecord",
    "PassContract",
    "PassManager",
    "PassRecord",
    "PassSemantics",
    "RecoveredType",
    "RecoveryConfidence",
    "Severity",
    "SourceProvenance",
    "SSAValue",
    "Terminator",
    "TerminatorKind",
    "TranslationValidation",
    "TranslationValidator",
    "VerificationReport",
]
