"""Deterministic asset manifest and provenance contracts for Skeleton.

This package catalogs identity, content digests, source/license metadata,
transformation lineage, target constraints, and bounded duplicate detection.
It does not generate assets, call models, upload releases, or import Godot
artifacts.
"""

from skeleton.assets.incremental_pipeline import (
    PIPELINE_SCHEMA,
    AssetPipelinePlan,
    AssetPipelineState,
    AssetRecipe,
    AssetSnapshot,
    IncrementalAssetError,
    PackageSnapshot,
    finalize_asset_pipeline,
    parse_asset_pipeline_state,
    plan_asset_pipeline,
)

from skeleton.assets.manifest import (
    SCHEMA_VERSION,
    AssetIdentity,
    AssetManifest,
    AssetManifestError,
    AssetRecord,
    AssetRightsError,
    ContentDescriptor,
    ContentFingerprint,
    DigestDriftError,
    DuplicateCluster,
    DuplicateIdentityError,
    DuplicateReport,
    DuplicateScanBoundError,
    LicenseMetadata,
    LineageError,
    LineageStep,
    NearDuplicatePair,
    SchemaCompatibilityError,
    SerializationError,
    SourceMetadata,
    TargetConstraints,
    canonical_content_identity,
    canonical_dumps,
    content_digest,
    content_fingerprint,
    detect_duplicates,
    fingerprint_hamming,
    fingerprint_similarity,
    migrate_manifest,
    parse_manifest,
    validate_lineage,
    validate_manifest,
    verify_content,
)

__all__ = [
    "PIPELINE_SCHEMA",
    "AssetPipelinePlan",
    "AssetPipelineState",
    "AssetRecipe",
    "AssetSnapshot",
    "IncrementalAssetError",
    "PackageSnapshot",
    "finalize_asset_pipeline",
    "parse_asset_pipeline_state",
    "plan_asset_pipeline",
    "SCHEMA_VERSION",
    "AssetIdentity",
    "AssetManifest",
    "AssetManifestError",
    "AssetRecord",
    "AssetRightsError",
    "ContentDescriptor",
    "ContentFingerprint",
    "DigestDriftError",
    "DuplicateCluster",
    "DuplicateIdentityError",
    "DuplicateReport",
    "DuplicateScanBoundError",
    "LicenseMetadata",
    "LineageError",
    "LineageStep",
    "NearDuplicatePair",
    "SchemaCompatibilityError",
    "SerializationError",
    "SourceMetadata",
    "TargetConstraints",
    "canonical_content_identity",
    "canonical_dumps",
    "content_digest",
    "content_fingerprint",
    "detect_duplicates",
    "fingerprint_hamming",
    "fingerprint_similarity",
    "migrate_manifest",
    "parse_manifest",
    "validate_lineage",
    "validate_manifest",
    "verify_content",
]
