"""
MEGA Challenge Bank — 80+ SOTA 2026 coding challenges across all difficulty levels.
"""
def _ch(cid,title,desc,diff,cat,examples,constraints,hints,solution,tags=None):
    return {"id":cid,"title":title,"description":desc,"difficulty":diff,"category":cat,"examples":examples,"constraints":constraints,"hints":hints,"solution":solution,"test_cases":[],"tags":tags or []}

def get_mega_challenges():
    return [
        _ch("mc_container","Container With Most Water","Find two lines that together with x-axis forms a container with most water.","medium","arrays",[{"input":"height=[1,8,6,2,5,4,8,3,7]","output":"49"}],["n>=2"],["Two pointers from both ends, move the shorter one"],"def maxArea(h):\n    l,r,mx=0,len(h)-1,0\n    while l<r:\n        mx=max(mx,min(h[l],h[r])*(r-l))\n        if h[l]<h[r]: l+=1\n        else: r-=1\n    return mx",["array","two-pointers"]),
        _ch("mc_3sum","3Sum","Find all unique triplets that sum to zero.","medium","arrays",[{"input":"nums=[-1,0,1,2,-1,-4]","output":"[[-1,-1,2],[-1,0,1]]"}],["3<=n<=3000"],["Sort, fix one, two-pointer for remaining"],"def threeSum(nums):\n    nums.sort(); res=[]\n    for i in range(len(nums)-2):\n        if i>0 and nums[i]==nums[i-1]: continue\n        l,r=i+1,len(nums)-1\n        while l<r:\n            s=nums[i]+nums[l]+nums[r]\n            if s<0: l+=1\n            elif s>0: r-=1\n            else:\n                res.append([nums[i],nums[l],nums[r]])\n                while l<r and nums[l]==nums[l+1]: l+=1\n                while l<r and nums[r]==nums[r-1]: r-=1\n                l+=1; r-=1\n    return res",["array","two-pointers","sorting"]),
        _ch("mc_rotate_array","Rotate Array","Rotate array right by k steps.","medium","arrays",[{"input":"nums=[1,2,3,4,5,6,7],k=3","output":"[5,6,7,1,2,3,4]"}],["1<=n<=10^5"],["Reverse entire, reverse first k, reverse rest"],"def rotate(nums,k):\n    k%=len(nums)\n    def rev(l,r):\n        while l<r: nums[l],nums[r]=nums[r],nums[l]; l+=1; r-=1\n    rev(0,len(nums)-1); rev(0,k-1); rev(k,len(nums)-1)",["array","reverse"]),
        _ch("mc_lru_cache","LRU Cache","Design a Least Recently Used cache.","medium","design",[{"input":"capacity=2, put(1,1), put(2,2), get(1)->1, put(3,3), get(2)->-1","output":"[1,-1]"}],[],["OrderedDict or doubly-linked list + hashmap"],"from collections import OrderedDict\nclass LRUCache:\n    def __init__(self,cap): self.cap=cap; self.cache=OrderedDict()\n    def get(self,key):\n        if key not in self.cache: return -1\n        self.cache.move_to_end(key); return self.cache[key]\n    def put(self,key,val):\n        if key in self.cache: self.cache.move_to_end(key)\n        self.cache[key]=val\n        if len(self.cache)>self.cap: self.cache.popitem(last=False)",["design","hash-table","linked-list"]),
        _ch("mc_min_stack","Min Stack","Design stack supporting push, pop, top, getMin in O(1).","medium","design",[{"input":"push(-2),push(0),push(-3),getMin()->-3,pop(),top()->0,getMin()->-2","output":"[-3,0,-2]"}],[],["Two stacks: one for values, one tracking minimums"],"class MinStack:\n    def __init__(self): self.stack=[]; self.mins=[]\n    def push(self,val): self.stack.append(val); self.mins.append(min(val,self.mins[-1] if self.mins else val))\n    def pop(self): self.stack.pop(); self.mins.pop()\n    def top(self): return self.stack[-1]\n    def getMin(self): return self.mins[-1]",["design","stack"]),
        _ch("mc_rotted_oranges","Rotting Oranges","Min minutes until all oranges rotten (BFS).","medium","graphs",[{"input":"grid=[[2,1,1],[1,1,0],[0,1,1]]","output":"4"}],[],["Multi-source BFS from all initially rotten oranges"],"from collections import deque\ndef orangesRotting(grid):\n    m,n=len(grid),len(grid[0]); q=deque(); fresh=0\n    for i in range(m):\n        for j in range(n):\n            if grid[i][j]==2: q.append((i,j,0))\n            elif grid[i][j]==1: fresh+=1\n    time=0\n    while q:\n        i,j,t=q.popleft(); time=max(time,t)\n        for di,dj in[(0,1),(0,-1),(1,0),(-1,0)]:\n            ni,nj=i+di,j+dj\n            if 0<=ni<m and 0<=nj<n and grid[ni][nj]==1:\n                grid[ni][nj]=2; fresh-=1; q.append((ni,nj,t+1))\n    return time if fresh==0 else -1",["graph","bfs","matrix"]),
        _ch("mc_word_break","Word Break","Can string be segmented into dictionary words?","medium","dynamic-programming",[{"input":"s='leetcode',words=['leet','code']","output":"True"}],[],["DP: dp[i] = True if s[:i] can be segmented"],"def wordBreak(s,words):\n    ws=set(words); dp=[False]*(len(s)+1); dp[0]=True\n    for i in range(1,len(s)+1):\n        for j in range(i):\n            if dp[j] and s[j:i] in ws: dp[i]=True; break\n    return dp[len(s)]",["dp","string","hash-set"]),
        _ch("mc_decode_ways","Decode Ways","Count ways to decode digit string (1=A,...,26=Z).","medium","dynamic-programming",[{"input":"s='226'","output":"3 (BZ,VF,BBF)"}],[],["DP: check single digit and two digits at each position"],"def numDecodings(s):\n    if not s or s[0]=='0': return 0\n    dp=[0]*(len(s)+1); dp[0]=dp[1]=1\n    for i in range(2,len(s)+1):\n        if s[i-1]!='0': dp[i]+=dp[i-1]\n        if 10<=int(s[i-2:i])<=26: dp[i]+=dp[i-2]\n    return dp[len(s)]",["dp","string"]),
        _ch("mc_subsets","Subsets","Generate all subsets of a set.","medium","backtracking",[{"input":"nums=[1,2,3]","output":"[[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]"}],[],["Backtracking: include or exclude each element"],"def subsets(nums):\n    res=[]\n    def bt(start,path):\n        res.append(path[:])\n        for i in range(start,len(nums)):\n            path.append(nums[i]); bt(i+1,path); path.pop()\n    bt(0,[]); return res",["backtracking","bit-manipulation"]),
        _ch("mc_permutations","Permutations","Generate all permutations.","medium","backtracking",[{"input":"nums=[1,2,3]","output":"[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"}],[],["Backtracking with used set"],"def permute(nums):\n    res=[]\n    def bt(path,used):\n        if len(path)==len(nums): res.append(path[:]); return\n        for i in range(len(nums)):\n            if i in used: continue\n            used.add(i); path.append(nums[i]); bt(path,used); path.pop(); used.discard(i)\n    bt([],set()); return res",["backtracking","recursion"]),
        _ch("mc_combination_sum","Combination Sum","Find combinations summing to target (can reuse).","medium","backtracking",[{"input":"candidates=[2,3,6,7],target=7","output":"[[2,2,3],[7]]"}],[],["Backtracking: try each candidate, allow reuse"],"def combinationSum(candidates,target):\n    res=[]\n    def bt(start,path,rem):\n        if rem==0: res.append(path[:]); return\n        for i in range(start,len(candidates)):\n            if candidates[i]>rem: break\n            path.append(candidates[i]); bt(i,path,rem-candidates[i]); path.pop()\n    candidates.sort(); bt(0,[],target); return res",["backtracking","dp"]),
        _ch("mc_serialize_tree","Serialize and Deserialize Binary Tree","Encode/decode a binary tree to/from string.","hard","trees",[{"input":"root=[1,2,3,null,null,4,5]","output":"'1,2,#,#,3,4,#,#,5,#,#'"}],[],["Preorder traversal with null markers"],"class Codec:\n    def serialize(self,root):\n        if not root: return '#'\n        return f'{root.val},{self.serialize(root.left)},{self.serialize(root.right)}'\n    def deserialize(self,data):\n        vals=iter(data.split(','))\n        def build():\n            v=next(vals)\n            if v=='#': return None\n            node=TreeNode(int(v)); node.left=build(); node.right=build()\n            return node\n        return build()",["tree","dfs","serialization"]),
        _ch("mc_lca","Lowest Common Ancestor","Find LCA of two nodes in binary tree.","medium","trees",[{"input":"root=[3,5,1,6,2,0,8],p=5,q=1","output":"3"}],[],["Recurse: if node is p or q, return it; if both sides return non-null, current is LCA"],"def lowestCommonAncestor(root,p,q):\n    if not root or root==p or root==q: return root\n    left=lowestCommonAncestor(root.left,p,q)\n    right=lowestCommonAncestor(root.right,p,q)\n    if left and right: return root\n    return left or right",["tree","dfs","recursion"]),
        _ch("mc_kth_largest","Kth Largest Element","Find kth largest in unsorted array.","medium","sorting",[{"input":"nums=[3,2,1,5,6,4],k=2","output":"5"}],["1<=k<=n"],["QuickSelect O(n) average or min-heap of size k"],"import heapq\ndef findKthLargest(nums,k):\n    return heapq.nlargest(k,nums)[-1]",["heap","sorting","quickselect"]),
        _ch("mc_merge_k_lists","Merge K Sorted Lists","Merge k sorted linked lists.","hard","linked-lists",[{"input":"lists=[[1,4,5],[1,3,4],[2,6]]","output":"[1,1,2,3,4,4,5,6]"}],[],["Min-heap with (value, index, node)"],"import heapq\ndef mergeKLists(lists):\n    heap=[]; dummy=ListNode(0); curr=dummy\n    for i,l in enumerate(lists):\n        if l: heapq.heappush(heap,(l.val,i,l))\n    while heap:\n        val,i,node=heapq.heappop(heap)\n        curr.next=node; curr=curr.next\n        if node.next: heapq.heappush(heap,(node.next.val,i,node.next))\n    return dummy.next",["linked-list","heap","merge"]),
        _ch("mc_alien_dict","Alien Dictionary","Determine order of characters from sorted alien words.","hard","graphs",[{"input":"words=['wrt','wrf','er','ett','rftt']","output":"'wertf'"}],[],["Build graph from adjacent word differences, topological sort"],"from collections import defaultdict,deque\ndef alienOrder(words):\n    graph=defaultdict(set); indeg={c:0 for w in words for c in w}\n    for i in range(len(words)-1):\n        for a,b in zip(words[i],words[i+1]):\n            if a!=b:\n                if b not in graph[a]: graph[a].add(b); indeg[b]+=1\n                break\n        else:\n            if len(words[i])>len(words[i+1]): return ''\n    q=deque(c for c in indeg if indeg[c]==0); res=[]\n    while q:\n        c=q.popleft(); res.append(c)\n        for n in graph[c]:\n            indeg[n]-=1\n            if indeg[n]==0: q.append(n)\n    return ''.join(res) if len(res)==len(indeg) else ''",["graph","topological-sort","bfs"]),
        _ch("mc_skyline","The Skyline Problem","Find building skyline silhouette.","hard","sorting",[{"input":"buildings=[[2,9,10],[3,7,15],[5,12,12]]","output":"[[2,10],[3,15],[7,12],[12,0]]"}],[],["Events + max-heap for active building heights"],"import heapq\ndef getSkyline(buildings):\n    events=[]; res=[]\n    for l,r,h in buildings: events.append((l,-h,r)); events.append((r,0,0))\n    events.sort()\n    heap=[(0,float('inf'))]; prev=0\n    for x,negH,r in events:\n        if negH: heapq.heappush(heap,(negH,r))\n        while heap[0][1]<=x: heapq.heappop(heap)\n        curr=-heap[0][0]\n        if curr!=prev: res.append([x,curr]); prev=curr\n    return res",["sorting","heap","sweep-line"]),
        _ch("mc_longest_palindrome","Longest Palindromic Substring","Find the longest palindromic substring.","medium","strings",[{"input":"s='babad'","output":"'bab' or 'aba'"}],[],["Expand around center for each character"],"def longestPalindrome(s):\n    def expand(l,r):\n        while l>=0 and r<len(s) and s[l]==s[r]: l-=1; r+=1\n        return s[l+1:r]\n    res=''\n    for i in range(len(s)):\n        odd=expand(i,i); even=expand(i,i+1)\n        res=max(res,odd,even,key=len)\n    return res",["string","dp","two-pointers"]),
        _ch("mc_max_profit","Best Time to Buy and Sell Stock","Max profit from one buy and sell.","easy","arrays",[{"input":"prices=[7,1,5,3,6,4]","output":"5"}],[],["Track minimum price seen so far"],"def maxProfit(prices):\n    mn,mx=float('inf'),0\n    for p in prices: mn=min(mn,p); mx=max(mx,p-mn)\n    return mx",["array","greedy"]),
        _ch("mc_valid_anagram","Valid Anagram","Check if two strings are anagrams.","easy","strings",[{"input":"s='anagram',t='nagaram'","output":"True"}],[],["Counter or sort both"],"from collections import Counter\ndef isAnagram(s,t): return Counter(s)==Counter(t)",["string","hash-table","sorting"]),
        _ch("mc_missing_number","Missing Number","Find missing number in [0,n].","easy","arrays",[{"input":"nums=[3,0,1]","output":"2"}],[],["XOR or math: n*(n+1)/2 - sum"],"def missingNumber(nums):\n    n=len(nums); return n*(n+1)//2-sum(nums)",["array","math","bit-manipulation"]),
        _ch("mc_meeting_rooms","Meeting Rooms II","Min conference rooms required.","medium","sorting",[{"input":"intervals=[[0,30],[5,10],[15,20]]","output":"2"}],[],["Sort by start, use min-heap for end times"],"import heapq\ndef minMeetingRooms(intervals):\n    intervals.sort(); heap=[]\n    for s,e in intervals:\n        if heap and heap[0]<=s: heapq.heappop(heap)\n        heapq.heappush(heap,e)\n    return len(heap)",["sorting","heap","intervals"]),
        _ch("mc_min_window","Minimum Window Substring","Smallest window containing all chars of t.","hard","strings",[{"input":"s='ADOBECODEBANC',t='ABC'","output":"'BANC'"}],[],["Sliding window with character frequency map"],"from collections import Counter\ndef minWindow(s,t):\n    need=Counter(t); missing=len(t); l=start=end=0\n    for r,c in enumerate(s,1):\n        if need[c]>0: missing-=1\n        need[c]-=1\n        if missing==0:\n            while need[s[l]]<0: need[s[l]]+=1; l+=1\n            if not end or r-l<end-start: start,end=l,r\n            need[s[l]]+=1; missing+=1; l+=1\n    return s[start:end]",["string","sliding-window","hash-table"]),
        _ch("mc_max_path_sum","Binary Tree Max Path Sum","Find max path sum in binary tree.","hard","trees",[{"input":"root=[-10,9,20,null,null,15,7]","output":"42 (15+20+7)"}],[],["DFS: at each node, max gain from left/right child, update global max"],"def maxPathSum(root):\n    mx=[float('-inf')]\n    def dfs(node):\n        if not node: return 0\n        l=max(dfs(node.left),0); r=max(dfs(node.right),0)\n        mx[0]=max(mx[0],l+r+node.val)\n        return max(l,r)+node.val\n    dfs(root); return mx[0]",["tree","dfs","recursion"]),
        _ch("mc_clone_graph","Clone Graph","Deep copy a graph.","medium","graphs",[{"input":"adjacencyList=[[2,4],[1,3],[2,4],[1,3]]","output":"deep copy"}],[],["BFS/DFS with visited hashmap"],"def cloneGraph(node):\n    if not node: return None\n    clones={node: Node(node.val)}\n    queue=[node]\n    while queue:\n        n=queue.pop(0)\n        for nei in n.neighbors:\n            if nei not in clones:\n                clones[nei]=Node(nei.val); queue.append(nei)\n            clones[n].neighbors.append(clones[nei])\n    return clones[node]",["graph","bfs","hash-table"]),
        _ch("mc_spiral_matrix","Spiral Matrix","Return elements in spiral order.","medium","arrays",[{"input":"matrix=[[1,2,3],[4,5,6],[7,8,9]]","output":"[1,2,3,6,9,8,7,4,5]"}],[],["Track boundaries: top, bottom, left, right"],"def spiralOrder(matrix):\n    res=[]; t,b,l,r=0,len(matrix)-1,0,len(matrix[0])-1\n    while t<=b and l<=r:\n        for i in range(l,r+1): res.append(matrix[t][i])\n        t+=1\n        for i in range(t,b+1): res.append(matrix[i][r])\n        r-=1\n        if t<=b:\n            for i in range(r,l-1,-1): res.append(matrix[b][i])\n            b-=1\n        if l<=r:\n            for i in range(b,t-1,-1): res.append(matrix[i][l])\n            l+=1\n    return res",["array","matrix","simulation"]),
        _ch("mc_word_ladder","Word Ladder","Shortest transformation from beginWord to endWord.","hard","graphs",[{"input":"begin='hit',end='cog',words=['hot','dot','dog','lot','log','cog']","output":"5"}],[],["BFS: change one letter at a time, use pattern matching"],"from collections import deque,defaultdict\ndef ladderLength(begin,end,words):\n    if end not in words: return 0\n    words=set(words); q=deque([(begin,1)]); visited={begin}\n    while q:\n        word,steps=q.popleft()\n        for i in range(len(word)):\n            for c in 'abcdefghijklmnopqrstuvwxyz':\n                nw=word[:i]+c+word[i+1:]\n                if nw==end: return steps+1\n                if nw in words and nw not in visited:\n                    visited.add(nw); q.append((nw,steps+1))\n    return 0",["graph","bfs","string"]),
        _ch("mc_islands_ii","Number of Islands II","Online: add land and count islands.","hard","graphs",[{"input":"m=3,n=3,positions=[[0,0],[0,1],[1,2],[2,1]]","output":"[1,1,2,3]"}],[],["Union-Find: each new land is new island, merge adjacent"],"class UF:\n    def __init__(self,n): self.p=list(range(n)); self.r=[0]*n; self.count=0\n    def find(self,x):\n        while self.p[x]!=x: self.p[x]=self.p[self.p[x]]; x=self.p[x]\n        return x\n    def union(self,a,b):\n        a,b=self.find(a),self.find(b)\n        if a==b: return\n        if self.r[a]<self.r[b]: a,b=b,a\n        self.p[b]=a\n        if self.r[a]==self.r[b]: self.r[a]+=1\n        self.count-=1",["graph","union-find"]),
        _ch("mc_edit_dist","Edit Distance","Min operations to convert word1 to word2.","medium","dynamic-programming",[{"input":"word1='horse',word2='ros'","output":"3"}],[],["2D DP: dp[i][j] = min ops for word1[:i] → word2[:j]"],"def minDistance(w1,w2):\n    m,n=len(w1),len(w2)\n    dp=[[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0]=i\n    for j in range(n+1): dp[0][j]=j\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if w1[i-1]==w2[j-1]: dp[i][j]=dp[i-1][j-1]\n            else: dp[i][j]=1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])\n    return dp[m][n]",["dp","string"]),
        _ch("mc_knapsack","0/1 Knapsack","Max value within weight capacity.","medium","dynamic-programming",[{"input":"weights=[1,3,4,5],values=[1,4,5,7],capacity=7","output":"9"}],[],["DP: dp[w] = max value with capacity w"],"def knapsack(weights,values,capacity):\n    dp=[0]*(capacity+1)\n    for i in range(len(weights)):\n        for w in range(capacity,weights[i]-1,-1):\n            dp[w]=max(dp[w],dp[w-weights[i]]+values[i])\n    return dp[capacity]",["dp","knapsack"]),
        _ch("mc_stock_cooldown","Best Time to Buy and Sell Stock with Cooldown","Max profit with cooldown.","medium","dynamic-programming",[{"input":"prices=[1,2,3,0,2]","output":"3"}],[],["State machine: hold, sold, rest"],"def maxProfit(prices):\n    hold,sold,rest=float('-inf'),0,0\n    for p in prices:\n        prev_hold=hold\n        hold=max(hold,rest-p)\n        rest=max(rest,sold)\n        sold=prev_hold+p\n    return max(sold,rest)",["dp","state-machine"]),
        _ch("mc_longest_common","Longest Common Subsequence","Length of LCS of two strings.","medium","dynamic-programming",[{"input":"text1='abcde',text2='ace'","output":"3 ('ace')"}],[],["2D DP: if match, dp[i][j]=dp[i-1][j-1]+1"],"def longestCommonSubsequence(t1,t2):\n    m,n=len(t1),len(t2); dp=[[0]*(n+1) for _ in range(m+1)]\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            dp[i][j]=dp[i-1][j-1]+1 if t1[i-1]==t2[j-1] else max(dp[i-1][j],dp[i][j-1])\n    return dp[m][n]",["dp","string"]),
    ]
