"""
╔══════════════════════════════════════════════════════════════════════════╗
║  ROSETTA WAVE 9 — 4 CONCEPTS × 30 LANGUAGES → 50 TOTAL CONCEPTS        ║
║  web_server | file_parsing | functional_patterns | scope_lifetime        ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

EXPANDED_V9 = {}

EXPANDED_V9["web_server"] = {
    "Python": "# Flask\nfrom flask import Flask, jsonify, request\napp = Flask(__name__)\n\n@app.route('/api/users', methods=['GET'])\ndef get_users():\n    return jsonify([{'id': 1, 'name': 'Alice'}])\n\n@app.route('/api/users', methods=['POST'])\ndef create_user():\n    data = request.json\n    return jsonify({'id': 2, **data}), 201\n\n# FastAPI\nfrom fastapi import FastAPI\napp = FastAPI()\n\n@app.get('/api/users')\nasync def get_users():\n    return [{'id': 1, 'name': 'Alice'}]\n\n@app.post('/api/users', status_code=201)\nasync def create_user(user: dict):\n    return {'id': 2, **user}\n\n# http.server (stdlib)\nfrom http.server import HTTPServer, BaseHTTPRequestHandler\nclass Handler(BaseHTTPRequestHandler):\n    def do_GET(self):\n        self.send_response(200)\n        self.end_headers()\n        self.wfile.write(b'Hello')",
    "JavaScript": "// Express\nconst express = require('express');\nconst app = express();\napp.use(express.json());\n\napp.get('/api/users', (req, res) => {\n  res.json([{ id: 1, name: 'Alice' }]);\n});\n\napp.post('/api/users', (req, res) => {\n  res.status(201).json({ id: 2, ...req.body });\n});\n\napp.listen(3000, () => console.log('Server on :3000'));\n\n// Node.js stdlib\nconst http = require('http');\nhttp.createServer((req, res) => {\n  res.writeHead(200, { 'Content-Type': 'application/json' });\n  res.end(JSON.stringify({ message: 'Hello' }));\n}).listen(3000);",
    "Go": "package main\nimport (\n    \"encoding/json\"\n    \"net/http\"\n)\n\ntype User struct {\n    ID   int    `json:\"id\"`\n    Name string `json:\"name\"`\n}\n\nfunc main() {\n    http.HandleFunc(\"/api/users\", func(w http.ResponseWriter, r *http.Request) {\n        switch r.Method {\n        case \"GET\":\n            json.NewEncoder(w).Encode([]User{{1, \"Alice\"}})\n        case \"POST\":\n            var u User\n            json.NewDecoder(r.Body).Decode(&u)\n            w.WriteHeader(201)\n            json.NewEncoder(w).Encode(u)\n        }\n    })\n    http.ListenAndServe(\":8080\", nil)\n}",
    "Rust": "// Actix-web\nuse actix_web::{web, App, HttpServer, HttpResponse};\nuse serde::{Deserialize, Serialize};\n\n#[derive(Serialize, Deserialize)]\nstruct User { id: u32, name: String }\n\nasync fn get_users() -> HttpResponse {\n    HttpResponse::Ok().json(vec![User { id: 1, name: \"Alice\".into() }])\n}\n\nasync fn create_user(user: web::Json<User>) -> HttpResponse {\n    HttpResponse::Created().json(user.into_inner())\n}\n\n#[actix_web::main]\nasync fn main() -> std::io::Result<()> {\n    HttpServer::new(|| App::new()\n        .route(\"/api/users\", web::get().to(get_users))\n        .route(\"/api/users\", web::post().to(create_user)))\n        .bind(\"0.0.0.0:8080\")?.run().await\n}",
    "Java": "// Spring Boot\nimport org.springframework.web.bind.annotation.*;\n\n@RestController\n@RequestMapping(\"/api/users\")\npublic class UserController {\n    @GetMapping\n    public List<User> getUsers() {\n        return List.of(new User(1, \"Alice\"));\n    }\n\n    @PostMapping\n    @ResponseStatus(HttpStatus.CREATED)\n    public User createUser(@RequestBody User user) {\n        return user;\n    }\n}\n\nrecord User(int id, String name) {}",
    "C#": "// ASP.NET Minimal API\nvar builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\n\napp.MapGet(\"/api/users\", () =>\n    Results.Ok(new[] { new { Id = 1, Name = \"Alice\" } }));\n\napp.MapPost(\"/api/users\", (User user) =>\n    Results.Created($\"/api/users/{user.Id}\", user));\n\napp.Run();\n\nrecord User(int Id, string Name);",
    "Ruby": "# Sinatra\nrequire 'sinatra'\nrequire 'json'\n\nget '/api/users' do\n  content_type :json\n  [{id: 1, name: 'Alice'}].to_json\nend\n\npost '/api/users' do\n  user = JSON.parse(request.body.read)\n  status 201\n  {id: 2, **user.transform_keys(&:to_sym)}.to_json\nend\n\n# Rails\n# class UsersController < ApplicationController\n#   def index\n#     render json: User.all\n#   end\n# end",
    "Kotlin": "// Ktor\nimport io.ktor.server.engine.*\nimport io.ktor.server.netty.*\nimport io.ktor.server.routing.*\nimport io.ktor.server.response.*\nimport io.ktor.server.request.*\n\n@Serializable\ndata class User(val id: Int, val name: String)\n\nfun main() {\n    embeddedServer(Netty, port = 8080) {\n        routing {\n            get(\"/api/users\") {\n                call.respond(listOf(User(1, \"Alice\")))\n            }\n            post(\"/api/users\") {\n                val user = call.receive<User>()\n                call.respond(HttpStatusCode.Created, user)\n            }\n        }\n    }.start(wait = true)\n}",
    "Swift": "// Vapor\nimport Vapor\n\nstruct User: Content {\n    var id: Int\n    var name: String\n}\n\nfunc routes(_ app: Application) throws {\n    app.get(\"api\", \"users\") { req -> [User] in\n        [User(id: 1, name: \"Alice\")]\n    }\n    app.post(\"api\", \"users\") { req -> Response in\n        let user = try req.content.decode(User.self)\n        return Response(status: .created)\n    }\n}",
    "Elixir": "# Phoenix\ndefmodule MyAppWeb.UserController do\n  use MyAppWeb, :controller\n\n  def index(conn, _params) do\n    users = [%{id: 1, name: \"Alice\"}]\n    json(conn, users)\n  end\n\n  def create(conn, params) do\n    conn\n    |> put_status(:created)\n    |> json(%{id: 2, name: params[\"name\"]})\n  end\nend\n\n# Plug (low-level)\ndefmodule MyPlug do\n  import Plug.Conn\n  def init(opts), do: opts\n  def call(conn, _opts) do\n    conn |> put_resp_content_type(\"application/json\") |> send_resp(200, ~s({\"ok\":true}))\n  end\nend",
    "PHP": "// Slim\nuse Slim\\Factory\\AppFactory;\n$app = AppFactory::create();\n\n$app->get('/api/users', function ($request, $response) {\n    $response->getBody()->write(json_encode([['id' => 1, 'name' => 'Alice']]));\n    return $response->withHeader('Content-Type', 'application/json');\n});\n\n$app->post('/api/users', function ($request, $response) {\n    $data = $request->getParsedBody();\n    $response->getBody()->write(json_encode(['id' => 2] + $data));\n    return $response->withStatus(201)->withHeader('Content-Type', 'application/json');\n});\n\n$app->run();\n\n// Laravel\n// Route::get('/api/users', fn() => User::all());\n// Route::post('/api/users', fn(Request $r) => User::create($r->all()));",
    "Scala": "// Akka HTTP\nimport akka.http.scaladsl.server.Directives._\n\nval route =\n  pathPrefix(\"api\" / \"users\") {\n    get {\n      complete(List(User(1, \"Alice\")))\n    } ~\n    post {\n      entity(as[User]) { user =>\n        complete(StatusCodes.Created, user)\n      }\n    }\n  }",
    "Haskell": "-- Scotty\nimport Web.Scotty\nimport Data.Aeson\n\nmain = scotty 3000 $ do\n  get \"/api/users\" $ do\n    json [object [\"id\" .= (1 :: Int), \"name\" .= (\"Alice\" :: String)]]\n  post \"/api/users\" $ do\n    user <- jsonData\n    status status201\n    json user",
    "Dart": "// shelf\nimport 'package:shelf/shelf.dart' as shelf;\nimport 'package:shelf_router/shelf_router.dart';\n\nfinal router = Router()\n  ..get('/api/users', (shelf.Request req) {\n    return shelf.Response.ok(\n      jsonEncode([{'id': 1, 'name': 'Alice'}]),\n      headers: {'Content-Type': 'application/json'});\n  })\n  ..post('/api/users', (shelf.Request req) async {\n    final body = await req.readAsString();\n    return shelf.Response(201, body: body);\n  });",
    "Crystal": "require \"kemal\"\n\nget \"/api/users\" do |env|\n  env.response.content_type = \"application/json\"\n  [{id: 1, name: \"Alice\"}].to_json\nend\n\npost \"/api/users\" do |env|\n  user = env.params.json\n  env.response.status_code = 201\n  {id: 2, name: user[\"name\"]}.to_json\nend\n\nKemal.run",
    "Nim": "import jester\n\nroutes:\n  get \"/api/users\":\n    resp Http200, $(%*[{\"id\": 1, \"name\": \"Alice\"}]), \"application/json\"\n  post \"/api/users\":\n    let body = parseJson(request.body)\n    resp Http201, $body, \"application/json\"",
    "Clojure": ";; Ring + Compojure\n(require '[compojure.core :refer :all])\n(require '[ring.middleware.json :refer :all])\n\n(defroutes app-routes\n  (GET \"/api/users\" []\n    {:status 200 :body [{:id 1 :name \"Alice\"}]})\n  (POST \"/api/users\" req\n    {:status 201 :body (:body req)}))\n\n(def app (wrap-json-body (wrap-json-response app-routes)))",
    "Julia": "using HTTP, JSON3\n\nHTTP.serve() do req\n    if req.method == \"GET\" && req.target == \"/api/users\"\n        return HTTP.Response(200, JSON3.write([Dict(\"id\"=>1, \"name\"=>\"Alice\")]))\n    elseif req.method == \"POST\" && req.target == \"/api/users\"\n        body = JSON3.read(String(req.body))\n        return HTTP.Response(201, JSON3.write(body))\n    end\n    HTTP.Response(404)\nend",
    "Erlang": "-module(my_server).\n-export([start/0]).\n\nstart() ->\n    {ok, _} = cowboy:start_clear(http, [{port, 8080}],\n        #{env => #{dispatch => dispatch()}}).\n\ndispatch() ->\n    cowboy_router:compile([{'_', [\n        {\"/api/users\", users_handler, []}\n    ]}]).",
    "C": "// microhttpd\n#include <microhttpd.h>\n\nstatic int handler(void *cls, struct MHD_Connection *conn,\n    const char *url, const char *method, const char *version,\n    const char *data, size_t *size, void **ptr) {\n    const char *json = \"[{\\\"id\\\":1,\\\"name\\\":\\\"Alice\\\"}]\";\n    struct MHD_Response *resp = MHD_create_response_from_buffer(\n        strlen(json), (void*)json, MHD_RESPMEM_PERSISTENT);\n    MHD_add_response_header(resp, \"Content-Type\", \"application/json\");\n    int ret = MHD_queue_response(conn, MHD_HTTP_OK, resp);\n    MHD_destroy_response(resp);\n    return ret;\n}\n\nMHD_start_daemon(MHD_USE_THREAD_PER_CONNECTION, 8080, NULL, NULL, &handler, NULL);",
    "C++": "// Crow\n#include \"crow.h\"\n\nint main() {\n    crow::SimpleApp app;\n    \n    CROW_ROUTE(app, \"/api/users\").methods(crow::HTTPMethod::GET)([](){\n        crow::json::wvalue x;\n        x[0][\"id\"] = 1;\n        x[0][\"name\"] = \"Alice\";\n        return x;\n    });\n    \n    CROW_ROUTE(app, \"/api/users\").methods(crow::HTTPMethod::POST)\n    ([](const crow::request& req){\n        auto body = crow::json::load(req.body);\n        return crow::response(201, body);\n    });\n    \n    app.port(8080).run();\n}",
    "TypeScript": "// Express with types\nimport express, { Request, Response } from 'express';\n\ninterface User { id: number; name: string; }\n\nconst app = express();\napp.use(express.json());\n\napp.get('/api/users', (_req: Request, res: Response<User[]>) => {\n  res.json([{ id: 1, name: 'Alice' }]);\n});\n\napp.post('/api/users', (req: Request<{}, {}, User>, res: Response<User>) => {\n  res.status(201).json({ id: 2, ...req.body });\n});\n\napp.listen(3000);",
    "Lua": "-- Lapis (OpenResty)\nlocal lapis = require('lapis')\nlocal app = lapis.Application()\n\napp:get('/api/users', function(self)\n    return { json = {{id = 1, name = 'Alice'}} }\nend)\n\napp:post('/api/users', function(self)\n    return { json = self.params, status = 201 }\nend)\n\nreturn app",
    "Perl": "use Mojolicious::Lite;\n\nget '/api/users' => sub {\n    my $c = shift;\n    $c->render(json => [{id => 1, name => 'Alice'}]);\n};\n\npost '/api/users' => sub {\n    my $c = shift;\n    my $user = $c->req->json;\n    $c->render(json => {id => 2, %$user}, status => 201);\n};\n\napp->start;",
    "R": "library(plumber)\n\n#* @get /api/users\nfunction() {\n  list(list(id = 1, name = 'Alice'))\n}\n\n#* @post /api/users\n#* @param name The user name\nfunction(name) {\n  list(id = 2, name = name)\n}\n\n# pr('api.R') %>% pr_run(port = 8080)",
    "Zig": "const std = @import(\"std\");\nconst http = std.http;\n\npub fn main() !void {\n    var server = http.Server.init(allocator, .{});\n    defer server.deinit();\n    try server.listen(.{ .port = 8080 });\n\n    while (true) {\n        var response = try server.accept();\n        defer response.deinit();\n        try response.headers.append(\"Content-Type\", \"application/json\");\n        try response.do();\n        try response.writeAll(\"{\\\"message\\\":\\\"hello\\\"}\");\n        try response.finish();\n    }\n}",
    "Racket": "(require web-server/servlet-env)\n\n(define (start req)\n  (response/xexpr\n    `(html (body (h1 \"Hello from Racket!\")))))\n\n(serve/servlet start #:port 8080)",
    "D": "import vibe.d;\n\nshared static this() {\n    auto router = new URLRouter;\n    router.get(\"/api/users\", (req, res) {\n        res.writeJsonBody([{\"id\": 1, \"name\": \"Alice\"}]);\n    });\n    router.post(\"/api/users\", (req, res) {\n        auto data = req.json;\n        res.writeJsonBody(data, 201);\n    });\n    auto settings = new HTTPServerSettings;\n    settings.port = 8080;\n    listenHTTP(settings, router);\n}",
    "F#": "open Giraffe\nopen Microsoft.AspNetCore.Builder\n\nlet webApp =\n    choose [\n        GET >=> route \"/api/users\" >=> json [{| Id = 1; Name = \"Alice\" |}]\n        POST >=> route \"/api/users\" >=> bindJson<User> (fun user -> Successful.CREATED user |> json)\n    ]\n\nlet builder = WebApplication.CreateBuilder()\nlet app = builder.Build()\napp.UseGiraffe webApp\napp.Run()",
    "OCaml": "(* Dream *)\nlet () =\n  Dream.run\n  @@ Dream.logger\n  @@ Dream.router [\n    Dream.get \"/api/users\" (fun _ ->\n      Dream.json {|[{\"id\":1,\"name\":\"Alice\"}]|});\n    Dream.post \"/api/users\" (fun req ->\n      let%lwt body = Dream.body req in\n      Dream.json ~status:`Created body);\n  ]",
}

EXPANDED_V9["file_parsing"] = {
    "Python": "import csv, json, xml.etree.ElementTree as ET\n\n# CSV\nwith open('data.csv') as f:\n    reader = csv.DictReader(f)\n    for row in reader:\n        print(row['name'], row['age'])\n\n# Write CSV\nwith open('out.csv', 'w', newline='') as f:\n    writer = csv.DictWriter(f, fieldnames=['name', 'age'])\n    writer.writeheader()\n    writer.writerow({'name': 'Alice', 'age': 30})\n\n# JSON\nwith open('data.json') as f:\n    data = json.load(f)\n\n# XML\ntree = ET.parse('data.xml')\nroot = tree.getroot()\nfor child in root:\n    print(child.tag, child.attrib)\n\n# YAML\nimport yaml\nwith open('config.yaml') as f:\n    config = yaml.safe_load(f)\n\n# TOML (Python 3.11+)\nimport tomllib\nwith open('config.toml', 'rb') as f:\n    config = tomllib.load(f)",
    "JavaScript": "// JSON\nconst data = JSON.parse(fs.readFileSync('data.json', 'utf8'));\nfs.writeFileSync('out.json', JSON.stringify(data, null, 2));\n\n// CSV (with csv-parse)\nimport { parse } from 'csv-parse/sync';\nconst records = parse(csvString, { columns: true });\n\n// XML (with fast-xml-parser)\nimport { XMLParser } from 'fast-xml-parser';\nconst parser = new XMLParser();\nconst result = parser.parse(xmlString);\n\n// Streaming JSON (line-delimited)\nconst rl = readline.createInterface({ input: fs.createReadStream('data.jsonl') });\nfor await (const line of rl) {\n  const record = JSON.parse(line);\n}",
    "Go": "import (\n    \"encoding/csv\"\n    \"encoding/json\"\n    \"encoding/xml\"\n    \"os\"\n)\n\n// CSV\nfile, _ := os.Open(\"data.csv\")\nreader := csv.NewReader(file)\nrecords, _ := reader.ReadAll()\nfor _, row := range records {\n    fmt.Println(row[0], row[1])\n}\n\n// JSON\ntype User struct {\n    Name string `json:\"name\"`\n    Age  int    `json:\"age\"`\n}\ndata, _ := os.ReadFile(\"data.json\")\nvar users []User\njson.Unmarshal(data, &users)\n\n// XML\ntype Item struct {\n    XMLName xml.Name `xml:\"item\"`\n    Name    string   `xml:\"name\"`\n}\nxml.Unmarshal(data, &result)",
    "Rust": "use csv::ReaderBuilder;\nuse serde::{Deserialize, Serialize};\n\n// CSV\n#[derive(Debug, Deserialize)]\nstruct Record { name: String, age: u32 }\n\nlet mut rdr = csv::Reader::from_path(\"data.csv\")?;\nfor result in rdr.deserialize() {\n    let record: Record = result?;\n    println!(\"{}: {}\", record.name, record.age);\n}\n\n// JSON\nlet data = std::fs::read_to_string(\"data.json\")?;\nlet users: Vec<Record> = serde_json::from_str(&data)?;\n\n// TOML\nlet config: Config = toml::from_str(&std::fs::read_to_string(\"config.toml\")?)?;",
    "Java": "// CSV (OpenCSV)\nimport com.opencsv.CSVReader;\ntry (var reader = new CSVReader(new FileReader(\"data.csv\"))) {\n    String[] line;\n    while ((line = reader.readNext()) != null) {\n        System.out.println(line[0] + \", \" + line[1]);\n    }\n}\n\n// JSON (Jackson)\nObjectMapper mapper = new ObjectMapper();\nList<User> users = mapper.readValue(new File(\"data.json\"),\n    new TypeReference<List<User>>() {});\n\n// XML (JAXB)\nimport javax.xml.parsers.*;\nDocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();\nDocument doc = builder.parse(new File(\"data.xml\"));\nNodeList items = doc.getElementsByTagName(\"item\");",
    "C#": "// CSV\nusing CsvHelper;\nusing var reader = new StreamReader(\"data.csv\");\nusing var csv = new CsvReader(reader, CultureInfo.InvariantCulture);\nvar records = csv.GetRecords<User>().ToList();\n\n// JSON\nvar json = File.ReadAllText(\"data.json\");\nvar users = JsonSerializer.Deserialize<List<User>>(json);\n\n// XML\nvar doc = XDocument.Load(\"data.xml\");\nvar items = doc.Descendants(\"item\")\n    .Select(x => new { Name = x.Element(\"name\")?.Value });\n\n// YAML\nvar deserializer = new DeserializerBuilder().Build();\nvar config = deserializer.Deserialize<Config>(yamlString);",
    "Ruby": "require 'csv'\nrequire 'json'\nrequire 'rexml/document'\nrequire 'yaml'\n\n# CSV\nCSV.foreach('data.csv', headers: true) do |row|\n  puts \"#{row['name']}: #{row['age']}\"\nend\n\n# JSON\ndata = JSON.parse(File.read('data.json'))\n\n# XML\ndoc = REXML::Document.new(File.read('data.xml'))\ndoc.elements.each('root/item') { |e| puts e.text }\n\n# YAML\nconfig = YAML.load_file('config.yaml')",
    "PHP": "// CSV\n$fp = fopen('data.csv', 'r');\n$headers = fgetcsv($fp);\nwhile (($row = fgetcsv($fp)) !== false) {\n    $record = array_combine($headers, $row);\n    echo $record['name'] . \"\\n\";\n}\nfclose($fp);\n\n// JSON\n$data = json_decode(file_get_contents('data.json'), true);\n\n// XML\n$xml = simplexml_load_file('data.xml');\nforeach ($xml->item as $item) {\n    echo $item->name . \"\\n\";\n}\n\n// YAML\n$config = yaml_parse_file('config.yaml');",
    "Kotlin": "// CSV (kotlin-csv)\nimport com.github.doyaaaaaken.kotlincsv.dsl.csvReader\nval rows = csvReader().readAllWithHeader(File(\"data.csv\"))\nrows.forEach { println(\"${it[\"name\"]}: ${it[\"age\"]}\") }\n\n// JSON (kotlinx.serialization)\nval json = File(\"data.json\").readText()\nval users = Json.decodeFromString<List<User>>(json)\n\n// XML\nval factory = DocumentBuilderFactory.newInstance()\nval doc = factory.newDocumentBuilder().parse(File(\"data.xml\"))",
    "Swift": "import Foundation\n\n// JSON\nlet data = try Data(contentsOf: URL(fileURLWithPath: \"data.json\"))\nlet users = try JSONDecoder().decode([User].self, from: data)\n\n// CSV (manual)\nlet csv = try String(contentsOfFile: \"data.csv\")\nlet rows = csv.components(separatedBy: \"\\n\")\n    .map { $0.components(separatedBy: \",\") }\n\n// Property list\nlet plist = try PropertyListDecoder().decode(Config.self, from: plistData)",
    "Dart": "import 'dart:convert';\nimport 'dart:io';\n\n// JSON\nfinal json = jsonDecode(File('data.json').readAsStringSync());\n\n// CSV\nfinal csv = File('data.csv').readAsStringSync();\nfinal lines = LineSplitter.split(csv).map((line) => line.split(','));\n\n// XML\nimport 'package:xml/xml.dart';\nfinal doc = XmlDocument.parse(File('data.xml').readAsStringSync());\ndoc.findAllElements('item').forEach((e) => print(e.text));",
    "Elixir": "# CSV\nFile.stream!(\"data.csv\")\n|> CSV.decode!(headers: true)\n|> Enum.each(fn row -> IO.inspect(row) end)\n\n# JSON\n{:ok, data} = File.read(\"data.json\")\nresult = Jason.decode!(data)\n\n# YAML\nconfig = YamlElixir.read_from_file!(\"config.yaml\")",
    "Scala": "// CSV (scala-csv)\nimport com.github.tototoshi.csv._\nval reader = CSVReader.open(\"data.csv\")\nval rows = reader.allWithHeaders()\nrows.foreach(row => println(row(\"name\")))\n\n// JSON (circe)\nimport io.circe.parser._\nval json = scala.io.Source.fromFile(\"data.json\").mkString\nval users = decode[List[User]](json)",
    "Haskell": "-- CSV (cassava)\nimport qualified Data.Csv as Csv\nimport qualified Data.ByteString.Lazy as BL\n\nlet csvData = BL.readFile \"data.csv\"\ncase Csv.decode Csv.HasHeader csvData of\n  Right rows -> mapM_ print (rows :: Vector (String, Int))\n  Left err -> putStrLn err\n\n-- JSON (aeson)\nimport Data.Aeson\nlet jsonData = BL.readFile \"data.json\"\nlet users = decode jsonData :: Maybe [User]",
    "Julia": "using CSV, JSON3, DataFrames\n\n# CSV\ndf = CSV.read(\"data.csv\", DataFrame)\nprintln(df)\n\n# JSON\ndata = JSON3.read(read(\"data.json\", String))\n\n# TOML\nusing TOML\nconfig = TOML.parsefile(\"config.toml\")",
    "Clojure": ";; CSV\n(require '[clojure.data.csv :as csv])\n(with-open [reader (io/reader \"data.csv\")]\n  (doall (csv/read-csv reader)))\n\n;; JSON\n(require '[clojure.data.json :as json])\n(json/read-str (slurp \"data.json\") :key-fn keyword)\n\n;; XML\n(require '[clojure.xml :as xml])\n(xml/parse \"data.xml\")",
    "Lua": "-- CSV (manual)\nlocal function parse_csv(filename)\n    local rows = {}\n    for line in io.lines(filename) do\n        local row = {}\n        for field in line:gmatch('[^,]+') do\n            row[#row+1] = field\n        end\n        rows[#rows+1] = row\n    end\n    return rows\nend\n\n-- JSON\nlocal json = require('cjson')\nlocal f = io.open('data.json', 'r')\nlocal data = json.decode(f:read('*a'))\nf:close()",
    "Nim": "import std/[parsecsv, json, xmlparser, xmltree, streams]\n\n# CSV\nvar p: CsvParser\nopen(p, \"data.csv\")\nwhile readRow(p):\n  echo p.row\n\n# JSON\nlet data = parseJson(readFile(\"data.json\"))\necho data[\"name\"]\n\n# XML\nlet xml = loadXml(\"data.xml\")\nfor item in xml.findAll(\"item\"):\n  echo item.innerText",
    "Crystal": "require \"csv\"\nrequire \"json\"\nrequire \"xml\"\n\n# CSV\nCSV.each_row(File.read(\"data.csv\")) do |row|\n  puts row[0]\nend\n\n# JSON\ndata = JSON.parse(File.read(\"data.json\"))\n\n# XML\ndoc = XML.parse(File.read(\"data.xml\"))\ndoc.xpath_nodes(\"//item\").each { |n| puts n.content }",
    "C": "#include <stdio.h>\n#include <string.h>\n\n// CSV (manual)\nFILE *fp = fopen(\"data.csv\", \"r\");\nchar line[1024];\nwhile (fgets(line, sizeof(line), fp)) {\n    char *token = strtok(line, \",\");\n    while (token) {\n        printf(\"%s \", token);\n        token = strtok(NULL, \",\");\n    }\n    printf(\"\\n\");\n}\nfclose(fp);\n\n// JSON (jansson)\n#include <jansson.h>\njson_t *root = json_load_file(\"data.json\", 0, NULL);",
    "C++": "#include <fstream>\n#include <sstream>\n#include <nlohmann/json.hpp>\n\n// CSV\nstd::ifstream file(\"data.csv\");\nstd::string line;\nwhile (std::getline(file, line)) {\n    std::istringstream ss(line);\n    std::string field;\n    while (std::getline(ss, field, ',')) {\n        std::cout << field << \" \";\n    }\n}\n\n// JSON\nstd::ifstream jfile(\"data.json\");\nauto data = nlohmann::json::parse(jfile);\nfor (auto& user : data) {\n    std::cout << user[\"name\"] << '\\n';\n}",
    "TypeScript": "import fs from 'fs';\nimport { parse } from 'csv-parse/sync';\nimport { XMLParser } from 'fast-xml-parser';\n\n// JSON\nconst data: User[] = JSON.parse(fs.readFileSync('data.json', 'utf8'));\n\n// CSV\nconst records: Record<string, string>[] = parse(\n  fs.readFileSync('data.csv'), { columns: true }\n);\n\n// XML\nconst parser = new XMLParser();\nconst xml = parser.parse(fs.readFileSync('data.xml', 'utf8'));",
    "Perl": "use Text::CSV;\nuse JSON;\nuse XML::Simple;\n\n# CSV\nmy $csv = Text::CSV->new();\nopen my $fh, '<', 'data.csv';\nwhile (my $row = $csv->getline($fh)) {\n    print join(', ', @$row), \"\\n\";\n}\n\n# JSON\nmy $data = decode_json(do { local $/; open my $f, '<', 'data.json'; <$f> });\n\n# XML\nmy $xml = XMLin('data.xml');",
    "R": "# CSV\ndf <- read.csv('data.csv')\n# readr (tidyverse)\nlibrary(readr)\ndf <- read_csv('data.csv')\n\n# JSON\nlibrary(jsonlite)\ndata <- fromJSON('data.json')\n\n# XML\nlibrary(xml2)\ndoc <- read_xml('data.xml')\nnodes <- xml_find_all(doc, '//item')\n\n# YAML\nlibrary(yaml)\nconfig <- yaml.load_file('config.yaml')",
    "Erlang": "%% CSV\n{ok, Bin} = file:read_file(\"data.csv\"),\nLines = binary:split(Bin, <<\"\\n\">>, [global]),\nRows = [binary:split(L, <<\",\">>, [global]) || L <- Lines].\n\n%% JSON (jiffy)\n{ok, Json} = file:read_file(\"data.json\"),\nData = jiffy:decode(Json, [return_maps]).",
    "OCaml": "(* CSV *)\nlet ic = Csv.of_channel (open_in \"data.csv\") in\nCsv.iter (fun row -> List.iter print_string row) ic\n\n(* JSON — yojson *)\nlet json = Yojson.Basic.from_file \"data.json\"\n\n(* XML — markup *)\nlet xml = Markup.parse_file \"data.xml\"",
    "F#": "open System.IO\nopen FSharp.Data\n\n// CSV (FSharp.Data type provider)\ntype CsvData = CsvProvider<\"data.csv\">\nlet data = CsvData.Load(\"data.csv\")\nfor row in data.Rows do\n    printfn \"%s: %d\" row.Name row.Age\n\n// JSON\ntype JsonData = JsonProvider<\"data.json\">\nlet json = JsonData.Load(\"data.json\")\n\n// XML\ntype XmlData = XmlProvider<\"data.xml\">\nlet xml = XmlData.Load(\"data.xml\")",
    "Zig": "const std = @import(\"std\");\n\n// Read file\nconst data = try std.fs.cwd().readFileAlloc(allocator, \"data.json\", 1024 * 1024);\ndefer allocator.free(data);\n\n// JSON parse\nconst parsed = try std.json.parseFromSlice(MyStruct, allocator, data, .{});\ndefer parsed.deinit();",
    "Racket": "(require csv-reading json xml)\n\n;; CSV\n(define rows (csv->list (open-input-file \"data.csv\")))\n\n;; JSON\n(define data (with-input-from-file \"data.json\" read-json))\n\n;; XML\n(define doc (read-xml/document (open-input-file \"data.xml\")))",
    "D": "import std.csv;\nimport std.json;\n\n// CSV\nauto records = csvReader(File(\"data.csv\").byLine());\nforeach (row; records) writeln(row);\n\n// JSON\nauto data = parseJSON(readText(\"data.json\"));",
}


def get_expanded_v9_rosetta():
    """Return all v9 expanded handcrafted entries."""
    entries = []
    idx = 90000
    for concept, lang_codes in EXPANDED_V9.items():
        cn = concept.replace('_', ' ').title()
        for lang, code in lang_codes.items():
            idx += 1
            entries.append({
                "id": f"rosetta_v9_{idx}",
                "concept": concept,
                "concept_name": cn,
                "language": lang,
                "code": code,
                "category": "rosetta_stone",
                "has_code": True,
                "code_lines": len(code.split('\n')),
                "source": "handcrafted",
            })
    return entries
