"""
Knowledge Vault — Frameworks & Infrastructure (React, Next.js, Vue, Angular, Django, Flask, Spring Boot,
Docker, K8s, Terraform, AWS, GCP, CI/CD, Monitoring, Security, Networking, CSS, HTML, GraphQL, gRPC, WebSocket)
"""

def _e(eid, topic, cat, content, tags=None):
    return {"id": eid, "topic": topic, "category": cat, "content": content, "tags": tags or []}

def get_vault_frameworks():
    return [
        # ═══ REACT ADVANCED ═══
        _e("kv_react_state", "React State Management", "react", "// Zustand — minimal\nimport { create } from 'zustand';\nconst useStore = create(set => ({\n  count: 0,\n  inc: () => set(s => ({ count: s.count + 1 })),\n  dec: () => set(s => ({ count: s.count - 1 })),\n}));\nfunction Counter() {\n  const { count, inc } = useStore();\n  return <button onClick={inc}>{count}</button>;\n}\n\n// React Context\nconst ThemeCtx = React.createContext('light');\nfunction App() {\n  return <ThemeCtx.Provider value='dark'><Child /></ThemeCtx.Provider>;\n}\nfunction Child() {\n  const theme = useContext(ThemeCtx);\n}\n\n// useReducer for complex state\nconst reducer = (state, action) => {\n  switch (action.type) {\n    case 'add': return { ...state, items: [...state.items, action.payload] };\n    case 'remove': return { ...state, items: state.items.filter(i => i.id !== action.id) };\n    default: return state;\n  }\n};\nconst [state, dispatch] = useReducer(reducer, { items: [] });", ["react","state","zustand","context","useReducer"]),
        _e("kv_react_perf", "React Performance", "react", "// React.memo — prevent re-renders\nconst Item = React.memo(({ title, onClick }) => (\n  <div onClick={onClick}>{title}</div>\n));\n\n// useMemo — cache expensive computation\nconst sorted = useMemo(() => items.sort((a,b) => a.score - b.score), [items]);\n\n// useCallback — stable function reference\nconst handleClick = useCallback((id) => {\n  setSelected(id);\n}, []);\n\n// Virtualization for long lists\nimport { FlashList } from '@shopify/flash-list';\n<FlashList\n  data={items}\n  renderItem={({ item }) => <Item {...item} />}\n  estimatedItemSize={80}\n  keyExtractor={item => item.id}\n/>\n\n// Code splitting\nconst HeavyComponent = React.lazy(() => import('./HeavyComponent'));\n<Suspense fallback={<Spinner />}><HeavyComponent /></Suspense>\n\n// Tips: avoid inline objects/functions in JSX, use keys properly, profile with React DevTools", ["react","performance","memo","useMemo","useCallback","virtualization"]),
        _e("kv_react_native_core", "React Native Core Patterns", "react-native", "// Navigation (Expo Router)\nimport { useRouter, useLocalSearchParams } from 'expo-router';\nconst router = useRouter();\nrouter.push('/profile/123');\nrouter.replace('/home');\nrouter.back();\n\n// Safe Area\nimport { useSafeAreaInsets } from 'react-native-safe-area-context';\nconst insets = useSafeAreaInsets();\n<View style={{ paddingTop: insets.top }}>\n\n// FlatList\n<FlatList\n  data={items}\n  renderItem={({ item }) => <ItemRow item={item} />}\n  keyExtractor={item => item.id}\n  removeClippedSubviews={true}\n  maxToRenderPerBatch={10}\n  windowSize={5}\n/>\n\n// Keyboard\n<KeyboardAvoidingView\n  behavior={Platform.OS === 'ios' ? 'padding' : 'height'}\n  style={{ flex: 1 }}\n>\n\n// AsyncStorage\nimport AsyncStorage from '@react-native-async-storage/async-storage';\nawait AsyncStorage.setItem('key', JSON.stringify(data));\nconst data = JSON.parse(await AsyncStorage.getItem('key'));\n\n// Animations\nimport Animated, { useSharedValue, withSpring } from 'react-native-reanimated';\nconst offset = useSharedValue(0);\noffset.value = withSpring(100);", ["react-native","expo","navigation","flatlist","keyboard","animation"]),

        # ═══ NEXT.JS ═══
        _e("kv_nextjs", "Next.js Essentials", "nextjs", "// App Router (Next.js 14+)\n// app/page.tsx — Server Component by default\nexport default async function Home() {\n  const data = await fetch('https://api.example.com/data');\n  return <div>{data.title}</div>;\n}\n\n// Client Component\n'use client';\nexport default function Counter() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c=>c+1)}>{count}</button>;\n}\n\n// API Routes\n// app/api/users/route.ts\nexport async function GET() {\n  const users = await db.users.findMany();\n  return Response.json(users);\n}\nexport async function POST(req: Request) {\n  const body = await req.json();\n  const user = await db.users.create({ data: body });\n  return Response.json(user, { status: 201 });\n}\n\n// Server Actions\n'use server';\nexport async function createPost(formData: FormData) {\n  await db.posts.create({ data: { title: formData.get('title') } });\n  revalidatePath('/posts');\n}\n\n// Metadata\nexport const metadata = { title: 'My App', description: '...' };", ["nextjs","react","ssr","server-components","api-routes"]),

        # ═══ VUE ═══
        _e("kv_vue", "Vue 3 Composition API", "vue", "<script setup>\nimport { ref, computed, watch, onMounted } from 'vue';\n\nconst count = ref(0);\nconst doubled = computed(() => count.value * 2);\n\nwatch(count, (newVal, oldVal) => {\n  console.log(`Changed: ${oldVal} -> ${newVal}`);\n});\n\nonMounted(() => { console.log('Mounted'); });\n\nfunction increment() { count.value++; }\n</script>\n\n<template>\n  <button @click=\"increment\">{{ count }} ({{ doubled }})</button>\n</template>\n\n// Pinia Store\nimport { defineStore } from 'pinia';\nexport const useCounterStore = defineStore('counter', () => {\n  const count = ref(0);\n  const doubleCount = computed(() => count.value * 2);\n  function increment() { count.value++; }\n  return { count, doubleCount, increment };\n});\n\n// Usage\nconst store = useCounterStore();\nstore.increment();", ["vue","composition-api","pinia","reactive","ref"]),

        # ═══ CSS ═══
        _e("kv_css_flexbox", "CSS Flexbox", "css", "/* Container */\n.flex-container {\n  display: flex;\n  flex-direction: row;        /* row | column | row-reverse | column-reverse */\n  justify-content: center;    /* flex-start | flex-end | center | space-between | space-around | space-evenly */\n  align-items: center;        /* stretch | flex-start | flex-end | center | baseline */\n  flex-wrap: wrap;            /* nowrap | wrap | wrap-reverse */\n  gap: 16px;                  /* row-gap column-gap */\n}\n\n/* Items */\n.flex-item {\n  flex: 1;                    /* flex-grow flex-shrink flex-basis */\n  flex-grow: 1;               /* How much to grow */\n  flex-shrink: 0;             /* How much to shrink */\n  flex-basis: 200px;          /* Initial size */\n  align-self: flex-end;       /* Override align-items */\n  order: -1;                  /* Reorder */\n}\n\n/* Common patterns */\n/* Centering */ .center { display:flex; justify-content:center; align-items:center; }\n/* Sticky footer */ .page { display:flex; flex-direction:column; min-height:100vh; } .content { flex:1; }\n/* Equal columns */ .cols { display:flex; gap:16px; } .col { flex:1; }", ["css","flexbox","layout","centering"]),
        _e("kv_css_grid", "CSS Grid", "css", "/* Container */\n.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);           /* 3 equal columns */\n  grid-template-columns: 200px 1fr 200px;          /* fixed-flex-fixed */\n  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));  /* responsive */\n  grid-template-rows: auto 1fr auto;\n  gap: 16px;\n  grid-template-areas:\n    'header header header'\n    'sidebar main aside'\n    'footer footer footer';\n}\n\n/* Items */\n.header { grid-area: header; }\n.sidebar { grid-area: sidebar; }\n.main { grid-area: main; }\n\n/* Spanning */\n.wide { grid-column: span 2; }\n.tall { grid-row: span 3; }\n.full { grid-column: 1 / -1; }  /* Full width */\n\n/* Alignment */\n.grid { justify-items: center; align-items: center; }\n.item { justify-self: end; align-self: start; }\n\n/* Subgrid (CSS Grid Level 2) */\n.nested { display: grid; grid-template-columns: subgrid; grid-column: span 3; }", ["css","grid","layout","responsive","template-areas"]),
        _e("kv_css_animations", "CSS Animations & Transitions", "css", "/* Transitions */\n.button {\n  transition: all 0.3s ease;\n  /* transition: property duration timing-function delay */\n}\n.button:hover {\n  transform: translateY(-2px);\n  box-shadow: 0 4px 12px rgba(0,0,0,0.15);\n}\n\n/* Keyframe Animations */\n@keyframes fadeIn {\n  from { opacity: 0; transform: translateY(20px); }\n  to { opacity: 1; transform: translateY(0); }\n}\n.animate-in {\n  animation: fadeIn 0.5s ease-out forwards;\n}\n\n@keyframes spin {\n  to { transform: rotate(360deg); }\n}\n.spinner { animation: spin 1s linear infinite; }\n\n@keyframes pulse {\n  0%, 100% { opacity: 1; }\n  50% { opacity: 0.5; }\n}\n\n/* Performance: use transform & opacity only */\n/* will-change: transform; — hint to browser */\n/* prefer: transform, opacity, filter */\n/* avoid animating: width, height, top, left, margin */", ["css","animation","transition","keyframe","transform"]),
        _e("kv_css_responsive", "CSS Responsive Design", "css", "/* Mobile-first media queries */\n.container { padding: 16px; }\n\n@media (min-width: 640px) {  /* sm */\n  .container { max-width: 640px; margin: 0 auto; }\n}\n@media (min-width: 768px) {  /* md */\n  .grid { grid-template-columns: repeat(2, 1fr); }\n}\n@media (min-width: 1024px) { /* lg */\n  .grid { grid-template-columns: repeat(3, 1fr); }\n}\n@media (min-width: 1280px) { /* xl */\n  .container { max-width: 1280px; }\n}\n\n/* Container queries (2024+) */\n.card-container { container-type: inline-size; }\n@container (min-width: 400px) {\n  .card { flex-direction: row; }\n}\n\n/* Fluid typography */\nhtml { font-size: clamp(14px, 2vw, 18px); }\nh1 { font-size: clamp(1.5rem, 4vw, 3rem); }\n\n/* Viewport units */\n.hero { height: 100dvh; }  /* dynamic viewport height */\nmin-height: 100svh;         /* small viewport */", ["css","responsive","media-query","mobile-first","clamp"]),

        # ═══ HTML5 ═══
        _e("kv_html5", "HTML5 Semantic Elements", "html", "<!-- Semantic structure -->\n<header>Navigation, logo</header>\n<nav>Main navigation links</nav>\n<main>Primary content (one per page)</main>\n<article>Self-contained content</article>\n<section>Thematic grouping</section>\n<aside>Sidebar, related content</aside>\n<footer>Footer info</footer>\n<figure><img><figcaption>Caption</figcaption></figure>\n<details><summary>Click to expand</summary>Hidden content</details>\n<dialog>Modal dialog</dialog>\n<time datetime='2024-12-25'>Dec 25, 2024</time>\n<mark>Highlighted text</mark>\n\n<!-- Forms -->\n<form method='post' action='/submit'>\n  <label for='email'>Email</label>\n  <input type='email' id='email' required placeholder='you@email.com'>\n  <input type='tel' pattern='[0-9]{3}-[0-9]{4}'>\n  <input type='date' min='2024-01-01'>\n  <input type='range' min='0' max='100' step='5'>\n  <textarea rows='4' maxlength='500'></textarea>\n  <select multiple>\n    <optgroup label='Group 1'><option>A</option></optgroup>\n  </select>\n  <button type='submit'>Submit</button>\n</form>\n\n<!-- Accessibility -->\n<img src='photo.jpg' alt='Descriptive text'>\n<button aria-label='Close menu'>X</button>\n<div role='alert'>Error message</div>", ["html","html5","semantic","forms","accessibility","a11y"]),

        # ═══ DOCKER & KUBERNETES ═══
        _e("kv_docker_advanced", "Docker Advanced", "docker", "# Multi-stage build\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY --from=builder /app/node_modules ./node_modules\nUSER node\nEXPOSE 3000\nHEALTHCHECK CMD curl -f http://localhost:3000/health || exit 1\nCMD [\"node\", \"dist/main.js\"]\n\n# Docker Compose\nservices:\n  web:\n    build: .\n    ports: ['3000:3000']\n    depends_on:\n      db: { condition: service_healthy }\n    environment:\n      DATABASE_URL: postgres://user:pass@db:5432/app\n    deploy:\n      resources:\n        limits: { cpus: '0.5', memory: 256M }\n  db:\n    image: postgres:16\n    volumes: [pgdata:/var/lib/postgresql/data]\n    healthcheck:\n      test: pg_isready -U user\n      interval: 5s\nvolumes:\n  pgdata:", ["docker","multi-stage","compose","container","healthcheck"]),
        _e("kv_kubernetes", "Kubernetes Essentials", "kubernetes", "# Deployment\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web-app\nspec:\n  replicas: 3\n  selector:\n    matchLabels: { app: web }\n  template:\n    metadata:\n      labels: { app: web }\n    spec:\n      containers:\n      - name: web\n        image: myapp:latest\n        ports: [{ containerPort: 8000 }]\n        resources:\n          requests: { cpu: 100m, memory: 128Mi }\n          limits: { cpu: 500m, memory: 256Mi }\n        livenessProbe:\n          httpGet: { path: /health, port: 8000 }\n          initialDelaySeconds: 10\n        readinessProbe:\n          httpGet: { path: /ready, port: 8000 }\n        env:\n        - name: DB_URL\n          valueFrom:\n            secretKeyRef: { name: db-secret, key: url }\n---\n# Service\napiVersion: v1\nkind: Service\nmetadata: { name: web-svc }\nspec:\n  selector: { app: web }\n  ports: [{ port: 80, targetPort: 8000 }]\n  type: ClusterIP\n---\n# Ingress\napiVersion: networking.k8s.io/v1\nkind: Ingress\nspec:\n  rules:\n  - host: app.example.com\n    http:\n      paths:\n      - path: /\n        pathType: Prefix\n        backend:\n          service: { name: web-svc, port: { number: 80 } }\n\n# kubectl: apply -f, get pods, logs, exec, scale, rollout", ["kubernetes","k8s","deployment","service","ingress","pods"]),

        # ═══ CI/CD ═══
        _e("kv_github_actions", "GitHub Actions CI/CD", "cicd", "name: CI/CD\non:\n  push: { branches: [main] }\n  pull_request: { branches: [main] }\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    services:\n      postgres:\n        image: postgres:16\n        env: { POSTGRES_PASSWORD: test }\n        ports: ['5432:5432']\n    steps:\n    - uses: actions/checkout@v4\n    - uses: actions/setup-python@v5\n      with: { python-version: '3.12' }\n    - run: pip install -r requirements.txt\n    - run: pytest --cov=app tests/ --junitxml=report.xml\n    - uses: codecov/codecov-action@v4\n\n  build:\n    needs: test\n    runs-on: ubuntu-latest\n    steps:\n    - uses: actions/checkout@v4\n    - uses: docker/login-action@v3\n      with:\n        registry: ghcr.io\n        username: ${{ github.actor }}\n        password: ${{ secrets.GITHUB_TOKEN }}\n    - uses: docker/build-push-action@v5\n      with:\n        push: true\n        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}\n\n  deploy:\n    needs: build\n    if: github.ref == 'refs/heads/main'\n    runs-on: ubuntu-latest\n    steps:\n    - run: kubectl set image deployment/app app=ghcr.io/${{ github.repository }}:${{ github.sha }}", ["cicd","github-actions","pipeline","deploy","test"]),

        # ═══ AWS ═══
        _e("kv_aws_services", "AWS Core Services", "aws", "Compute:\n  EC2: Virtual machines (t3.micro free tier)\n  Lambda: Serverless functions (pay per invocation)\n  ECS/Fargate: Container orchestration\n  Elastic Beanstalk: PaaS for web apps\n\nStorage:\n  S3: Object storage (11 9s durability)\n  EBS: Block storage for EC2\n  EFS: Shared file system\n  Glacier: Archive storage\n\nDatabase:\n  RDS: Managed SQL (Postgres, MySQL, Aurora)\n  DynamoDB: NoSQL key-value (single-digit ms latency)\n  ElastiCache: Redis/Memcached\n  DocumentDB: MongoDB-compatible\n\nNetworking:\n  VPC: Virtual private cloud\n  ALB: Application load balancer (L7)\n  NLB: Network load balancer (L4)\n  Route53: DNS\n  CloudFront: CDN\n  API Gateway: REST/WebSocket APIs\n\nMessaging:\n  SQS: Message queue\n  SNS: Pub/sub notifications\n  EventBridge: Event bus\n  Kinesis: Real-time streaming\n\nSecurity:\n  IAM: Identity & access management\n  KMS: Key management\n  Secrets Manager: Credentials\n  WAF: Web application firewall\n  CloudTrail: Audit logging", ["aws","cloud","services","ec2","s3","lambda","rds","dynamodb"]),

        # ═══ SECURITY ═══
        _e("kv_security_auth", "Authentication & Authorization", "security", "# JWT Authentication\nimport jwt\n\ndef create_token(user_id: str, secret: str) -> str:\n    payload = {\n        'sub': user_id,\n        'iat': datetime.utcnow(),\n        'exp': datetime.utcnow() + timedelta(hours=24)\n    }\n    return jwt.encode(payload, secret, algorithm='HS256')\n\ndef verify_token(token: str, secret: str) -> dict:\n    return jwt.decode(token, secret, algorithms=['HS256'])\n\n# Password hashing\nimport bcrypt\nhashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())\nis_valid = bcrypt.checkpw(password.encode(), hashed)\n\n# OAuth 2.0 Flow\n1. User clicks 'Login with Google'\n2. Redirect to Google's auth server\n3. User grants permission\n4. Google redirects back with authorization code\n5. Exchange code for access token (server-side)\n6. Use token to fetch user profile\n\n# RBAC (Role-Based Access Control)\nroles = {\n    'admin': ['read', 'write', 'delete', 'manage_users'],\n    'editor': ['read', 'write'],\n    'viewer': ['read'],\n}\ndef check_permission(user_role, action):\n    return action in roles.get(user_role, [])", ["security","auth","jwt","oauth","bcrypt","rbac"]),
        _e("kv_security_owasp", "OWASP Top 10 Prevention", "security", "1. Broken Access Control:\n   - Always verify user owns the resource\n   - Use RBAC/ABAC, deny by default\n   - Never trust client-side auth checks\n\n2. Injection (SQL, NoSQL, Command):\n   - Use parameterized queries ALWAYS\n   - cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,))\n   - Never: f'SELECT * FROM users WHERE id = {user_id}'\n\n3. XSS (Cross-Site Scripting):\n   - Escape output: textContent not innerHTML\n   - Use Content-Security-Policy header\n   - React auto-escapes by default (don't use dangerouslySetInnerHTML)\n\n4. Cryptographic Failures:\n   - Use bcrypt/argon2 for passwords (never MD5/SHA1)\n   - TLS everywhere (HTTPS)\n   - Don't store secrets in code/git\n\n5. CSRF:\n   - Use CSRF tokens for state-changing requests\n   - SameSite cookie attribute\n\n6. SSRF:\n   - Validate/whitelist URLs\n   - Block internal IP ranges\n\n7. Security Headers:\n   Content-Security-Policy: default-src 'self'\n   X-Content-Type-Options: nosniff\n   X-Frame-Options: DENY\n   Strict-Transport-Security: max-age=31536000", ["security","owasp","xss","injection","csrf","headers"]),

        # ═══ NETWORKING ═══
        _e("kv_http", "HTTP Protocol", "networking", "# HTTP Methods\nGET    — Read (idempotent, cacheable)\nPOST   — Create (not idempotent)\nPUT    — Replace (idempotent)\nPATCH  — Partial update\nDELETE — Remove (idempotent)\nHEAD   — GET without body\nOPTIONS — CORS preflight\n\n# Status Codes\n200 OK | 201 Created | 204 No Content\n301 Moved Permanently | 304 Not Modified\n400 Bad Request | 401 Unauthorized | 403 Forbidden\n404 Not Found | 409 Conflict | 422 Unprocessable | 429 Rate Limited\n500 Internal Error | 502 Bad Gateway | 503 Unavailable\n\n# Headers\nContent-Type: application/json\nAuthorization: Bearer <token>\nCache-Control: public, max-age=3600\nETag: \"abc123\"\nAccept: application/json\nX-Request-ID: uuid\n\n# HTTP/2: multiplexing, server push, header compression, binary protocol\n# HTTP/3: QUIC (UDP), 0-RTT, connection migration\n\n# CORS\nAccess-Control-Allow-Origin: https://myapp.com\nAccess-Control-Allow-Methods: GET, POST, PUT\nAccess-Control-Allow-Headers: Authorization, Content-Type", ["http","protocol","methods","status-codes","cors","headers"]),
        _e("kv_websocket", "WebSocket & Real-time", "networking", "// Client\nconst ws = new WebSocket('wss://api.example.com/ws');\nws.onopen = () => ws.send(JSON.stringify({ type: 'join', room: 'chat' }));\nws.onmessage = (event) => {\n  const data = JSON.parse(event.data);\n  handleMessage(data);\n};\nws.onclose = () => reconnect();\nws.onerror = (err) => console.error(err);\n\n// Server (FastAPI)\nfrom fastapi import WebSocket\n@app.websocket('/ws/{client_id}')\nasync def websocket_endpoint(ws: WebSocket, client_id: str):\n    await ws.accept()\n    connections[client_id] = ws\n    try:\n        while True:\n            data = await ws.receive_json()\n            # Broadcast to all\n            for conn in connections.values():\n                await conn.send_json(data)\n    except WebSocketDisconnect:\n        del connections[client_id]\n\n// Server-Sent Events (SSE) — one-way server→client\n@app.get('/events')\nasync def events():\n    async def generate():\n        while True:\n            data = await get_update()\n            yield f'data: {json.dumps(data)}\\n\\n'\n    return StreamingResponse(generate(), media_type='text/event-stream')", ["websocket","real-time","sse","streaming","socket"]),
        _e("kv_graphql", "GraphQL", "graphql", "# Schema\ntype User {\n  id: ID!\n  name: String!\n  email: String!\n  posts: [Post!]!\n}\ntype Post {\n  id: ID!\n  title: String!\n  content: String!\n  author: User!\n}\ntype Query {\n  users: [User!]!\n  user(id: ID!): User\n  posts(limit: Int): [Post!]!\n}\ntype Mutation {\n  createUser(name: String!, email: String!): User!\n  createPost(title: String!, content: String!, authorId: ID!): Post!\n}\n\n# Query\nquery {\n  user(id: \"1\") {\n    name\n    posts {\n      title\n    }\n  }\n}\n\n# Mutation\nmutation {\n  createUser(name: \"Alice\", email: \"alice@test.com\") {\n    id\n    name\n  }\n}\n\n# Benefits: no over-fetching, single endpoint, typed schema, introspection\n# Drawbacks: complexity, N+1 queries (use DataLoader), caching harder", ["graphql","api","query","mutation","schema"]),

        # ═══ REDIS ═══
        _e("kv_redis", "Redis Data Structures", "redis", "# Strings\nSET user:1:name \"Alice\"\nGET user:1:name\nSETEX session:abc 3600 \"data\"  # expires in 1hr\nINCR page:views  # atomic increment\n\n# Hash (object)\nHSET user:1 name \"Alice\" age 30 email \"alice@test.com\"\nHGET user:1 name\nHGETALL user:1\n\n# List (queue/stack)\nLPUSH queue:jobs '{\"type\":\"email\"}'\nRPOP queue:jobs\nLRANGE recent:items 0 9  # last 10\n\n# Set (unique values)\nSADD online:users \"user1\" \"user2\"\nSMEMBERS online:users\nSISMEMBER online:users \"user1\"\nSINTER set1 set2  # intersection\n\n# Sorted Set (leaderboard)\nZADD leaderboard 100 \"alice\" 95 \"bob\" 87 \"charlie\"\nZREVRANGE leaderboard 0 9 WITHSCORES  # top 10\nZRANK leaderboard \"alice\"  # rank\n\n# Pub/Sub\nSUBSCRIBE channel:notifications\nPUBLISH channel:notifications '{\"type\":\"alert\"}'\n\n# Patterns: caching, sessions, rate limiting, queues, pub/sub, leaderboards", ["redis","cache","data-structure","pub-sub","leaderboard"]),

        # ═══ DESIGN PATTERNS ═══
        _e("kv_patterns_solid", "SOLID Principles", "patterns", "S — Single Responsibility: One class = one reason to change\n  BAD: UserService handles auth + emails + database\n  GOOD: AuthService, EmailService, UserRepository\n\nO — Open/Closed: Open for extension, closed for modification\n  Use interfaces/abstract classes, strategy pattern\n  Add new behavior by adding new classes, not editing existing\n\nL — Liskov Substitution: Subtypes must be substitutable for base types\n  If Dog extends Animal, anywhere you use Animal, Dog should work\n  BAD: Square extends Rectangle but breaks setWidth/setHeight\n\nI — Interface Segregation: Many specific interfaces > one general\n  BAD: interface Worker { code(); test(); deploy(); manage(); }\n  GOOD: interface Coder { code(); } interface Tester { test(); }\n\nD — Dependency Inversion: Depend on abstractions, not concretions\n  BAD: class OrderService { private MySQLDatabase db; }\n  GOOD: class OrderService { private Database db; }  // interface", ["patterns","solid","design","principles","oop"]),
        _e("kv_patterns_gof", "GoF Design Patterns", "patterns", "Creational:\n  Singleton: One instance globally (db connection, config)\n  Factory: Create objects without specifying exact class\n  Builder: Step-by-step construction of complex objects\n  Prototype: Clone existing objects\n\nStructural:\n  Adapter: Convert interface to another (wrapper)\n  Decorator: Add behavior dynamically (middleware)\n  Facade: Simplified interface to complex subsystem\n  Proxy: Placeholder for another object (caching, lazy loading)\n  Composite: Tree structure (UI components)\n\nBehavioral:\n  Observer: Pub/sub, event listeners\n  Strategy: Swap algorithms at runtime\n  Command: Encapsulate action as object (undo/redo)\n  Iterator: Sequential access without exposing structure\n  State: Object behavior changes with internal state\n  Template Method: Define skeleton, let subclasses fill steps\n  Chain of Responsibility: Pass request through handler chain (middleware)\n\nMost used in web dev: Observer, Strategy, Factory, Decorator, Facade, Singleton", ["patterns","design-patterns","gof","creational","structural","behavioral"]),

        # ═══ LINUX/SHELL ═══
        _e("kv_linux", "Linux Essential Commands", "linux", "# File operations\nls -la          # List all with details\nfind . -name '*.py' -mtime -7  # Files modified in last 7 days\ngrep -rn 'pattern' .  # Recursive search with line numbers\nwc -l file.txt  # Count lines\ndu -sh */       # Directory sizes\ndf -h           # Disk usage\n\n# Process management\nps aux | grep python\ntop / htop      # Resource monitor\nkill -9 PID     # Force kill\nnohup cmd &     # Run in background\njobs / fg / bg  # Job control\n\n# Text processing\ncat file | sort | uniq -c | sort -rn  # Word frequency\nawk '{print $1, $3}' file  # Print columns 1 and 3\nsed 's/old/new/g' file     # Replace\ncut -d',' -f1,3 data.csv  # CSV columns\n\n# Networking\ncurl -s URL | jq .  # HTTP request + JSON parse\nwget URL            # Download\nss -tlnp            # Open ports\nping / traceroute   # Network diagnostics\n\n# Permissions\nchmod 755 script.sh  # rwxr-xr-x\nchown user:group file\nsudo command         # Run as root\n\n# Pipes & redirection\ncmd > file    # stdout to file\ncmd 2>&1      # stderr to stdout\ncmd1 | cmd2   # pipe", ["linux","shell","commands","bash","grep","awk","sed"]),

        # ═══ MONITORING ═══
        _e("kv_monitoring", "Application Monitoring", "devops", "# Key metrics (RED method)\nRate: Requests per second\nErrors: Error rate / percentage\nDuration: Latency (p50, p95, p99)\n\n# Prometheus metrics\nfrom prometheus_client import Counter, Histogram, Gauge\n\nREQUEST_COUNT = Counter('http_requests_total', 'Total requests', ['method', 'endpoint', 'status'])\nREQUEST_LATENCY = Histogram('http_request_duration_seconds', 'Request latency')\nACTIVE_USERS = Gauge('active_users', 'Currently active users')\n\n@app.middleware('http')\nasync def metrics_middleware(request, call_next):\n    start = time.time()\n    response = await call_next(request)\n    REQUEST_COUNT.labels(request.method, request.url.path, response.status_code).inc()\n    REQUEST_LATENCY.observe(time.time() - start)\n    return response\n\n# Logging best practices\nimport structlog\nlogger = structlog.get_logger()\nlogger.info('user_login', user_id='123', ip='1.2.3.4', duration_ms=45)\n\n# Stack: Prometheus + Grafana (metrics), ELK/Loki (logs), Jaeger (traces)\n# Alerts: PagerDuty, OpsGenie, Slack webhooks", ["monitoring","prometheus","grafana","logging","metrics","observability"]),
    ]
