"""Deterministic volume contracts. No stored prose. Bounds and fields only."""
from __future__ import annotations

FAMILIES = {
    "jvm": {"required": ("class_name", "bytecode_sha256", "signed"), "max_items": 64, "deny_default": True},
    "repo": {"required": ("path", "owner", "boundary"), "max_items": 128, "deny_default": True},
    "import": {"required": ("module", "allowed", "cycle_free"), "max_items": 256, "deny_default": True},
    "requirements": {"required": ("req_id", "owner", "acceptance"), "max_items": 200, "deny_default": True},
    "nfr": {"required": ("metric", "bound", "unit"), "max_items": 80, "deny_default": True},
    "taxonomy": {"required": ("cap_id", "parent", "maturity"), "max_items": 120, "deny_default": True},
    "behavior": {"required": ("spec_id", "pre", "post"), "max_items": 160, "deny_default": True},
    "state": {"required": ("machine", "state", "terminal"), "max_items": 100, "deny_default": True},
    "interface": {"required": ("name", "version", "errors"), "max_items": 80, "deny_default": True},
    "outbox": {"required": ("message_id", "inbox", "idempotency_key"), "max_items": 500, "deny_default": True},
    "security": {"required": ("principal", "action", "resource", "decision"), "max_items": 200, "deny_default": True},
    "privacy": {"required": ("subject", "purpose", "erasure_proof"), "max_items": 200, "deny_default": True},
    "sbom": {"required": ("component", "version", "license"), "max_items": 400, "deny_default": True},
    "slo": {"required": ("service", "objective", "burn"), "max_items": 60, "deny_default": True},
    "obs": {"required": ("signal", "cardinality", "budget"), "max_items": 100, "deny_default": True},
    "cost": {"required": ("meter", "units", "cap"), "max_items": 40, "deny_default": True},
    "research": {"required": ("source_id", "citation", "contaminated"), "max_items": 300, "deny_default": True},
    "eval": {"required": ("harness", "case_id", "score"), "max_items": 200, "deny_default": True},
    "card": {"required": ("card_id", "owner", "digest"), "max_items": 120, "deny_default": True},
    "policy": {"required": ("policy_id", "version", "deny_default"), "max_items": 80, "deny_default": True},
    "control": {"required": ("objective", "constraint", "decision"), "max_items": 80, "deny_default": True},
    "workflow": {"required": ("wf_id", "steps", "version"), "max_items": 150, "deny_default": True},
    "schedule": {"required": ("task", "critical", "deadline"), "max_items": 200, "deny_default": True},
    "human": {"required": ("actor", "intent", "approval"), "max_items": 80, "deny_default": True},
    "workspace": {"required": ("ns", "resource", "resolved"), "max_items": 200, "deny_default": True},
    "artifact": {"required": ("artifact", "deps", "digest"), "max_items": 300, "deny_default": True},
    "change": {"required": ("change_id", "risk", "plan"), "max_items": 100, "deny_default": True},
    "sdk": {"required": ("surface", "version", "contract"), "max_items": 40, "deny_default": True},
    "data": {"required": ("contract", "schema_sha", "fresh"), "max_items": 200, "deny_default": True},
    "claim": {"required": ("claim_id", "scope", "expires"), "max_items": 200, "deny_default": True},
    "strategy": {"required": ("strategy", "cost", "selected"), "max_items": 40, "deny_default": True},
    "plan": {"required": ("plan_id", "static_ok", "simulated"), "max_items": 80, "deny_default": True},
    "tool": {"required": ("tool", "health", "trust"), "max_items": 120, "deny_default": True},
    "saga": {"required": ("saga_id", "step", "compensation"), "max_items": 100, "deny_default": True},
    "gpu": {"required": ("device", "bytes", "evictable"), "max_items": 32, "deny_default": True},
    "cache": {"required": ("prefix", "hit", "bound"), "max_items": 64, "deny_default": True},
    "locality": {"required": ("node", "tier", "bytes"), "max_items": 64, "deny_default": True},
    "farm": {"required": ("queue", "job", "quota"), "max_items": 100, "deny_default": True},
    "rights": {"required": ("license", "usage", "allowed"), "max_items": 80, "deny_default": True},
    "lifecycle": {"required": ("model", "stage", "deprecated"), "max_items": 40, "deny_default": True},
    "sandbox": {"required": ("flag", "branch", "isolated"), "max_items": 40, "deny_default": True},
}

# key -> family. Every unsigned volume is named. Unknown keys are rejected by the engine.
BIND = {
    "VOL-033": "jvm", "VOL-051": "repo", "VOL-053": "import",
    "VOL-122": "requirements", "VOL-123": "nfr", "VOL-124": "taxonomy",
    "VOL-125": "taxonomy", "VOL-126": "behavior", "VOL-127": "state", "VOL-128": "interface",
    "VOL-134": "outbox", "VOL-166": "security", "VOL-167": "security", "VOL-169": "security",
    "VOL-172": "security", "VOL-173": "security", "VOL-174": "security", "VOL-175": "security",
    "VOL-176": "privacy", "VOL-177": "privacy", "VOL-178": "sbom",
    "VOL-180": "slo", "VOL-181": "slo", "VOL-182": "obs", "VOL-183": "obs", "VOL-184": "obs",
    "VOL-185": "slo", "VOL-186": "cost", "VOL-187": "cost", "VOL-195": "workspace",
    "VOL-210": "research", "VOL-211": "research", "VOL-212": "research", "VOL-213": "research",
    "VOL-214": "eval", "VOL-215": "eval", "VOL-216": "eval", "VOL-217": "eval",
    "VOL-218": "eval", "VOL-219": "research", "VOL-220": "eval",
    "VOL-221": "card", "VOL-222": "card", "VOL-223": "card", "VOL-224": "card", "VOL-225": "card",
    "VOL-226": "sbom", "VOL-227": "security", "VOL-228": "security",
    "VOL-243": "policy", "VOL-244": "policy", "VOL-245": "policy", "VOL-246": "data",
    "VOL-300": "control", "VOL-301": "control", "VOL-302": "control", "VOL-303": "control",
    "VOL-304": "control", "VOL-305": "control",
    "VOL-306": "workflow", "VOL-307": "workflow", "VOL-308": "workflow", "VOL-309": "workflow", "VOL-310": "workflow",
    "VOL-311": "schedule", "VOL-312": "schedule", "VOL-313": "schedule", "VOL-314": "schedule",
    "VOL-315": "schedule", "VOL-316": "schedule", "VOL-317": "control", "VOL-319": "human",
    "VOL-326": "human", "VOL-327": "human", "VOL-328": "human", "VOL-329": "human", "VOL-330": "workspace",
    "VOL-331": "workspace", "VOL-332": "workspace", "VOL-333": "workspace",
    "VOL-334": "artifact", "VOL-335": "artifact", "VOL-336": "change", "VOL-337": "change", "VOL-338": "change",
    "VOL-339": "sdk", "VOL-340": "sdk", "VOL-341": "sdk", "VOL-342": "sdk", "VOL-343": "sdk", "VOL-344": "sdk", "VOL-345": "sdk",
    "VOL-346": "eval", "VOL-347": "eval", "VOL-348": "data", "VOL-349": "slo", "VOL-350": "data",
    "VOL-351": "data", "VOL-352": "data", "VOL-353": "data", "VOL-354": "claim", "VOL-355": "claim",
    "VOL-356": "claim", "VOL-357": "claim", "VOL-358": "claim", "VOL-359": "claim", "VOL-360": "artifact",
    "VOL-366": "strategy", "VOL-367": "strategy", "VOL-368": "cost",
    "VOL-371": "plan", "VOL-372": "plan", "VOL-373": "tool", "VOL-374": "tool", "VOL-375": "tool",
    "VOL-376": "tool", "VOL-377": "tool", "VOL-378": "saga", "VOL-379": "saga", "VOL-380": "saga",
    "VOL-383": "gpu", "VOL-384": "gpu", "VOL-387": "cache", "VOL-388": "cache", "VOL-389": "cache",
    "VOL-393": "locality", "VOL-394": "locality", "VOL-395": "locality", "VOL-396": "locality",
    "VOL-400": "farm", "VOL-401": "farm", "VOL-402": "farm",
    "VOL-407": "rights", "VOL-408": "rights", "VOL-410": "research", "VOL-411": "lifecycle",
    "VOL-412": "lifecycle", "VOL-413": "lifecycle", "VOL-416": "sandbox", "VOL-417": "sandbox", "VOL-418": "lifecycle",
}

def contract(volume_id: str) -> dict:
    family = BIND[volume_id]
    spec = FAMILIES[family]
    return {"volume": volume_id, "family": family, **spec}
