"""
╔══════════════════════════════════════════════════════════════════════════╗
║  ROSETTA WAVE 11 — HYPERSCALE EXPANSION                                  ║
║  pointers_references | macros_preprocessing | command_line_args |        ║
║  reflection_introspection                                                ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

EXPANDED_V11 = {}

EXPANDED_V11["pointers_references"] = {
    "C": "int x = 42;\nint* ptr = &x;     // Pointer to x\n*ptr = 100;        // Dereference and modify\nprintf(\"%d\\n\", x); // 100\n\n// Pointer arithmetic\nint arr[] = {10, 20, 30};\nint* p = arr;\nprintf(\"%d\\n\", *(p + 1)); // 20\n\n// Void pointer\nvoid* vptr = &x;\nprintf(\"%d\\n\", *(int*)vptr);",
    "C++": "int x = 42;\nint* ptr = &x;     // Pointer\nint& ref = x;      // Reference\n\nref = 100;         // Modifies x\nprintf(\"%d\\n\", x); // 100\n\n// Smart pointers (C++11)\n#include <memory>\nstd::unique_ptr<int> uptr = std::make_unique<int>(42);\nstd::shared_ptr<int> sptr = std::make_shared<int>(42);",
    "Rust": "let mut x = 42;\n\n// References (borrowing)\nlet ref_x = &x;\nprintln!(\"{}\", ref_x);\n\n// Mutable reference\nlet mut_ref_x = &mut x;\n*mut_ref_x = 100;\n\n// Smart pointers\nuse std::rc::Rc;\nuse std::sync::Arc;\nlet b = Box::new(42);\nlet r = Rc::new(42);\nlet a = Arc::new(42);",
    "Go": "x := 42\nptr := &x          // Pointer to x\n*ptr = 100         // Dereference\nfmt.Println(x)     // 100\n\n// Go has pointers but no pointer arithmetic\n// new() allocates memory and returns a pointer\np := new(int)\n*p = 42",
    "C#": "// Safe references\nref int r = ref x;\n\n// Unsafe pointers\nunsafe {\n    int x = 42;\n    int* ptr = &x;\n    *ptr = 100;\n    \n    // Pointer arithmetic\n    int[] arr = {10, 20, 30};\n    fixed (int* p = arr) {\n        Console.WriteLine(*(p + 1)); // 20\n    }\n}",
    "Python": "# Python has names/labels bound to objects, not true pointers\n# id() gives memory address in CPython\nx = 42\nprint(hex(id(x)))\n\n# Simulating pointers with lists or ctypes\nval = [42]\ndef modify(ptr): ptr[0] = 100\nmodify(val)\n\nimport ctypes\nx_c = ctypes.c_int(42)\nptr = ctypes.pointer(x_c)\nptr.contents.value = 100",
    "JavaScript": "// JS uses references for objects, pass-by-value for primitives\nlet obj = { x: 42 };\nlet ref = obj;\nref.x = 100;       // Modifies original object\nconsole.log(obj.x); // 100\n\n// WebAssembly / SharedArrayBuffer for raw memory\nconst mem = new WebAssembly.Memory({ initial: 1 });\nconst view = new Uint32Array(mem.buffer);\nview[0] = 42;",
    "Java": "// Java has no explicit pointers, only object references\nclass Wrapper { int value; }\nWrapper w1 = new Wrapper();\nw1.value = 42;\nWrapper w2 = w1; // w2 references the same object\nw2.value = 100;\nSystem.out.println(w1.value); // 100",
    "Swift": "// Unsafe pointers in Swift\nvar x = 42\nwithUnsafePointer(to: &x) { ptr in\n    print(ptr.pointee)\n}\n\n// Mutable pointers\nwithUnsafeMutablePointer(to: &x) { ptr in\n    ptr.pointee = 100\n}\n\n// Unmanaged memory\nlet ptr = UnsafeMutablePointer<Int>.allocate(capacity: 1)\nptr.initialize(to: 42)\nptr.deallocate()",
    "Zig": "var x: i32 = 42;\n// Pointer to variable\nconst ptr = &x;\nptr.* = 100;\n\n// Optional pointers (nullable)\nvar opt_ptr: ?*i32 = &x;\nif (opt_ptr) |p| { p.* = 200; }\n\n// Many-item pointers (for arrays)\nvar arr = [_]i32{1, 2, 3};\nvar arr_ptr: [*]i32 = &arr;\narr_ptr[1] = 20;"
}

EXPANDED_V11["macros_preprocessing"] = {
    "C": "#define PI 3.14159\n#define MAX(a,b) ((a) > (b) ? (a) : (b))\n\n#ifdef DEBUG\n  printf(\"Debug mode\\n\");\n#endif\n\n// Token pasting\n#define CONCAT(a, b) a ## b\nint CONCAT(x, y) = 42; // int xy = 42;\n\n// Stringification\n#define STR(x) #x\nprintf(\"%s\\n\", STR(hello)); // \"hello\"",
    "C++": "// C++ supports C macros, but prefers constexpr and templates\nconstexpr double PI = 3.14159;\n\ntemplate<typename T>\nconstexpr T max(T a, T b) { return a > b ? a : b; }\n\n// C++20 consteval\nconsteval int sqr(int n) { return n * n; }\n\n// Feature testing macros\n#if __cplusplus >= 202002L\n  // C++20 code\n#endif",
    "Rust": "// Declarative macros\nmacro_rules! my_vec {\n    ( $( $x:expr ),* ) => {\n        {\n            let mut temp_vec = Vec::new();\n            $( temp_vec.push($x); )*\n            temp_vec\n        }\n    };\n}\nlet v = my_vec![1, 2, 3];\n\n// Procedural macros (Derive)\n#[derive(Debug, Clone)]\nstruct Point { x: i32, y: i32 }",
    "C#": "// C# has limited preprocessing, no macro expansion\n#define DEBUG\n\n#if DEBUG\n    Console.WriteLine(\"Debug\");\n#elif RELEASE\n    Console.WriteLine(\"Release\");\n#endif\n\n// Caller Info Attributes (Alternative to __FILE__, __LINE__)\nvoid Log(string msg, \n        [CallerFilePath] string file = \"\",\n        [CallerLineNumber] int line = 0) {\n    Console.WriteLine($\"{file}:{line} {msg}\");\n}",
    "Elixir": "# Macros are core to Elixir (AST transformation)\ndefmodule MyMacro do\n  defmacro unless(expr, do: block) do\n    quote do\n      if !unquote(expr), do: unquote(block)\n    end\n  end\nend\n\n# Usage\nrequire MyMacro\nMyMacro.unless 1 == 2 do\n  IO.puts(\"Math works\")\nend",
    "Lisp": ";; Common Lisp macros (code that writes code)\n(defmacro unless (condition &body body)\n  `(if (not ,condition)\n       (progn ,@body)))\n\n(unless (= 1 2)\n  (print \"Math works\"))\n\n;; Macroexpansion\n(macroexpand-1 '(unless (= 1 2) (print \"Math works\")))",
    "Nim": "# Nim templates (hygienic macros)\ntemplate times(n: int, body: untyped) =\n  for i in 0..<n:\n    body\n\n3.times:\n  echo \"Hello\"\n\n# AST Macros\nimport macros\nmacro debug(n: typed): untyped =\n  result = newCall(\"echo\", toStrLit(n), newStrLitNode(\" = \"), n)\n\nvar x = 42\ndebug(x) # echos: x = 42",
    "Julia": "# Julia macros operate on parsed expressions\nmacro timeit(ex)\n    quote\n        local t0 = time()\n        local val = $(esc(ex))\n        local t1 = time()\n        println(\"Elapsed time: \", t1-t0, \" seconds\")\n        val\n    end\nend\n\n@timeit sum(1:1000000)",
    "Zig": "// Zig uses comptime instead of macros\nfn max(comptime T: type, a: T, b: T) T {\n    return if (a > b) a else b;\n}\n\n// Comptime evaluation\nconst x = comptime max(i32, 10, 20);\n\n// Inline loops (loop unrolling)\ninline for ([_]i32{1, 2, 3}) |v| {\n    std.debug.print(\"{d}\\n\", .{v});\n}"
}

EXPANDED_V11["command_line_args"] = {
    "Python": "import sys\nimport argparse\n\n# Basic sys.argv\nprint(\"Args:\", sys.argv[1:])\n\n# Argparse\nparser = argparse.ArgumentParser(description='Process some integers.')\nparser.add_argument('integers', metavar='N', type=int, nargs='+')\nparser.add_argument('--sum', dest='accumulate', action='store_const',\n                    const=sum, default=max)\nargs = parser.parse_args()\nprint(args.accumulate(args.integers))",
    "JavaScript": "// Node.js\nconst args = process.argv.slice(2);\nconsole.log(\"Args:\", args);\n\n// Deno\n// const args = Deno.args;\n\n// Using popular library 'yargs' or 'commander'\n// const argv = require('yargs/yargs')(process.argv.slice(2)).argv;\n// console.log(argv);",
    "Go": "package main\nimport (\n    \"flag\"\n    \"fmt\"\n    \"os\"\n)\n\nfunc main() {\n    // Raw args\n    fmt.Println(\"Args:\", os.Args[1:])\n    \n    // Flag parsing\n    wordPtr := flag.String(\"word\", \"foo\", \"a string\")\n    numPtr := flag.Int(\"numb\", 42, \"an int\")\n    flag.Parse()\n    fmt.Println(\"word:\", *wordPtr)\n    fmt.Println(\"numb:\", *numPtr)\n}",
    "Rust": "use std::env;\n\n// Raw args\nlet args: Vec<String> = env::args().collect();\nprintln!(\"Args: {:?}\", &args[1..]);\n\n// Using 'clap' crate (standard in ecosystem)\n// use clap::Parser;\n// #[derive(Parser)]\n// struct Cli {\n//     #[arg(short, long)] name: String,\n//     #[arg(short, long, default_value_t = 1)] count: u8,\n// }",
    "C": "#include <stdio.h>\n\nint main(int argc, char *argv[]) {\n    printf(\"Program name: %s\\n\", argv[0]);\n    for (int i = 1; i < argc; i++) {\n        printf(\"Arg %d: %s\\n\", i, argv[i]);\n    }\n    return 0;\n}",
    "C++": "#include <iostream>\n\nint main(int argc, char *argv[]) {\n    std::cout << \"Program: \" << argv[0] << '\\n';\n    for (int i = 1; i < argc; i++) {\n        std::cout << \"Arg \" << i << \": \" << argv[i] << '\\n';\n    }\n    return 0;\n}",
    "Java": "public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Args count: \" + args.length);\n        for (int i = 0; i < args.length; i++) {\n            System.out.println(\"Arg \" + i + \": \" + args[i]);\n        }\n    }\n}",
    "C#": "class Program {\n    static void Main(string[] args) {\n        Console.WriteLine($\"Args count: {args.Length}\");\n        for (int i = 0; i < args.Length; i++) {\n            Console.WriteLine($\"Arg {i}: {args[i]}\");\n        }\n        \n        // Environment.GetCommandLineArgs() works anywhere\n    }\n}",
    "Ruby": "# Raw args\nputs \"Args: #{ARGV.inspect}\"\n\n# OptionParser (Standard Library)\nrequire 'optparse'\n\noptions = {}\nOptionParser.new do |opts|\n  opts.on('-n', '--name NAME', 'Name to say hello to') do |n|\n    options[:name] = n\n  end\nend.parse!\n\nputs options.inspect"
}

EXPANDED_V11["reflection_introspection"] = {
    "Python": "class Person:\n    def __init__(self): self.name = 'Alice'\n\np = Person()\n\n# Attributes and methods\nprint(dir(p))\nprint(hasattr(p, 'name'))\nprint(getattr(p, 'name'))\nsetattr(p, 'age', 30)\n\n# Type and class info\nprint(type(p))\nprint(isinstance(p, Person))\nprint(issubclass(Person, object))\n\n# inspect module for deep reflection\nimport inspect\nprint(inspect.getmembers(p))",
    "Java": "import java.lang.reflect.*;\n\nClass<?> clazz = Person.class;\nSystem.out.println(\"Name: \" + clazz.getName());\n\n// Get methods\nMethod[] methods = clazz.getDeclaredMethods();\nfor (Method m : methods) {\n    System.out.println(m.getName());\n}\n\n// Instantiate and invoke\nObject obj = clazz.getDeclaredConstructor().newInstance();\nMethod greet = clazz.getMethod(\"greet\", String.class);\ngreet.invoke(obj, \"Alice\");",
    "C#": "using System.Reflection;\n\nType t = typeof(Person);\nConsole.WriteLine($\"Name: {t.Name}\");\n\n// Get properties\nPropertyInfo[] props = t.GetProperties();\nforeach (var prop in props) {\n    Console.WriteLine(prop.Name);\n}\n\n// Instantiate dynamically\nobject obj = Activator.CreateInstance(t);\nMethodInfo method = t.GetMethod(\"Greet\");\nmethod.Invoke(obj, new object[] { \"Alice\" });",
    "JavaScript": "const obj = { name: 'Alice', greet() {} };\n\n// Keys and prototype\nconsole.log(Object.keys(obj));\nconsole.log(Object.getPrototypeOf(obj));\n\n// Property descriptors\nconsole.log(Object.getOwnPropertyDescriptor(obj, 'name'));\n\n// Reflect API (ES6)\nReflect.set(obj, 'age', 30);\nconsole.log(Reflect.has(obj, 'age'));\n\n// Type checking\nconsole.log(typeof obj);\nconsole.log(obj instanceof Object);",
    "Go": "import (\n    \"fmt\"\n    \"reflect\"\n)\n\ntype Person struct {\n    Name string\n    Age  int\n}\n\nfunc main() {\n    p := Person{\"Alice\", 30}\n    t := reflect.TypeOf(p)\n    v := reflect.ValueOf(p)\n    \n    fmt.Println(\"Type:\", t.Name())\n    for i := 0; i < t.NumField(); i++ {\n        field := t.Field(i)\n        val := v.Field(i).Interface()\n        fmt.Printf(\"%s: %v\\n\", field.Name, val)\n    }\n}",
    "Ruby": "class Person\n  def greet; end\nend\np = Person.new\n\n# Introspection\nputs p.class\nputs p.is_a?(Person)\nputs p.respond_to?(:greet)\n\n# Methods and variables\nputs p.methods - Object.methods\nputs p.instance_variables\n\n# Send (Dynamic invocation)\np.send(:greet)",
    "PHP": "class Person { public $name = 'Alice'; }\n\n$p = new Person();\n\n// Basic introspection\necho get_class($p);\nvar_dump(property_exists($p, 'name'));\nvar_dump(method_exists($p, 'greet'));\n\n// Reflection API\n$refClass = new ReflectionClass('Person');\n$properties = $refClass->getProperties();\nforeach ($properties as $prop) {\n    echo $prop->getName();\n}",
    "Rust": "// Rust has NO runtime reflection like Java/C#\n// Uses Any trait for basic type downcasting\nuse std::any::Any;\n\nfn print_if_string(s: &dyn Any) {\n    if let Some(string) = s.downcast_ref::<String>() {\n        println!(\"It's a string: {}\", string);\n    } else {\n        println!(\"Not a string\");\n    }\n}\n\nlet my_string = \"Hello\".to_string();\nprint_if_string(&my_string);",
    "C++": "// C++ lacks rich reflection (until maybe C++26)\n// RTTI (Run-Time Type Information)\n#include <typeinfo>\n#include <iostream>\n\nclass Base { virtual void dummy() {} };\nclass Derived : public Base {};\n\nBase* b = new Derived;\nstd::cout << typeid(*b).name() << '\\n';\n\n// dynamic_cast\nif (Derived* d = dynamic_cast<Derived*>(b)) {\n    std::cout << \"Successfully cast to Derived\\n\";\n}"
}
