"""
╔══════════════════════════════════════════════════════════════════════════╗
║  ROSETTA WAVE 10 — PAST 50 CONCEPTS                                     ║
║  functional_patterns | scope_lifetime | property_access |                ║
║  casting_conversion                                                      ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

EXPANDED_V10 = {}

EXPANDED_V10["functional_patterns"] = {
    "Python": "from functools import reduce, partial\nfrom itertools import chain, starmap\nfrom operator import add, mul\n\n# Pipe / compose\ndef pipe(value, *fns):\n    for fn in fns: value = fn(value)\n    return value\n\ndef compose(*fns):\n    return lambda x: reduce(lambda v, f: f(v), reversed(fns), x)\n\n# Usage\nresult = pipe([1,2,3,4,5],\n    lambda xs: filter(lambda x: x%2==0, xs),\n    lambda xs: map(lambda x: x**2, xs),\n    list, sum)\n\n# Partial application\nadd5 = partial(add, 5)\nmul3 = partial(mul, 3)\n\n# Currying\ndef curry(f):\n    import inspect\n    n = len(inspect.signature(f).parameters)\n    def inner(*args):\n        if len(args) >= n: return f(*args)\n        return lambda *more: inner(*args, *more)\n    return inner\n\n@curry\ndef add3(a, b, c): return a + b + c\nadd3(1)(2)(3)  # 6\n\n# Monadic pattern (Maybe)\nclass Maybe:\n    def __init__(self, val): self._val = val\n    def bind(self, f): return f(self._val) if self._val is not None else Maybe(None)\n    def value_or(self, default): return self._val if self._val is not None else default",
    "JavaScript": "// Pipe\nconst pipe = (...fns) => x => fns.reduce((v, f) => f(v), x);\nconst compose = (...fns) => x => fns.reduceRight((v, f) => f(v), x);\n\nconst process = pipe(\n  xs => xs.filter(x => x % 2 === 0),\n  xs => xs.map(x => x ** 2),\n  xs => xs.reduce((a, b) => a + b, 0)\n);\nprocess([1,2,3,4,5]);  // 20\n\n// Currying\nconst curry = fn => {\n  const arity = fn.length;\n  return function curried(...args) {\n    if (args.length >= arity) return fn(...args);\n    return (...more) => curried(...args, ...more);\n  };\n};\n\nconst add = curry((a, b, c) => a + b + c);\nadd(1)(2)(3);  // 6\n\n// Maybe monad\nclass Maybe {\n  constructor(val) { this._val = val; }\n  static of(val) { return new Maybe(val); }\n  map(fn) { return this._val != null ? Maybe.of(fn(this._val)) : this; }\n  flatMap(fn) { return this._val != null ? fn(this._val) : this; }\n  getOrElse(def) { return this._val ?? def; }\n}",
    "Haskell": "-- Haskell IS functional patterns\n\n-- Function composition\nprocess = sum . map (^2) . filter even\nprocess [1..5]  -- 20\n\n-- Point-free style\nincAll = map (+1)\ndoubleAll = map (*2)\nsumEvens = sum . filter even\n\n-- Currying (automatic)\nadd :: Int -> Int -> Int\nadd a b = a + b\nadd5 = add 5  -- Partial application\nadd5 3  -- 8\n\n-- Monad\n-- Maybe\nsafeDivide :: Int -> Int -> Maybe Int\nsafeDivide _ 0 = Nothing\nsafeDivide a b = Just (a `div` b)\n\nresult = do\n  x <- safeDivide 10 2\n  y <- safeDivide x 0\n  return y  -- Nothing\n\n-- Functor / Applicative\nfmap (*2) (Just 5)  -- Just 10\n(+) <$> Just 3 <*> Just 4  -- Just 7\n\n-- Folding\nfoldl' (+) 0 [1..100]  -- 5050\nfoldr (:) [] [1,2,3]  -- [1,2,3]",
    "Rust": "// Iterator chains (functional style)\nlet result: i32 = (1..=5)\n    .filter(|x| x % 2 == 0)\n    .map(|x| x * x)\n    .sum();\n\n// Option as monad\nfn safe_divide(a: f64, b: f64) -> Option<f64> {\n    if b == 0.0 { None } else { Some(a / b) }\n}\n\nlet result = safe_divide(10.0, 2.0)\n    .and_then(|x| safe_divide(x, 0.0))  // None\n    .unwrap_or(0.0);\n\n// Result chaining\nfn process(input: &str) -> Result<i32, String> {\n    input.parse::<i32>()\n        .map_err(|e| e.to_string())\n        .map(|n| n * 2)\n        .and_then(|n| if n > 100 { Err(\"too big\".into()) } else { Ok(n) })\n}\n\n// Closures as first-class\nfn apply_twice<F: Fn(i32) -> i32>(f: F, x: i32) -> i32 { f(f(x)) }\napply_twice(|x| x + 1, 5);  // 7",
    "Scala": "// Pipe (Scala 3)\nval result = (1 to 5)\n  .filter(_ % 2 == 0)\n  .map(x => x * x)\n  .sum  // 20\n\n// Currying\ndef add(a: Int)(b: Int)(c: Int): Int = a + b + c\nval add5 = add(5)_\nadd5(3)(2)  // 10\n\n// For comprehension (monadic)\nfor {\n  x <- Option(10)\n  y <- Option(x / 2)\n  z <- if (y > 0) Some(y) else None\n} yield z\n\n// Pattern matching with partial functions\nval pf: PartialFunction[Int, String] = {\n  case 1 => \"one\"\n  case 2 => \"two\"\n}\nList(1, 2, 3).collect(pf)  // List(\"one\", \"two\")",
    "Elixir": "# Pipe operator (core to Elixir)\n1..5\n|> Enum.filter(&(rem(&1, 2) == 0))\n|> Enum.map(&(&1 * &1))\n|> Enum.sum()  # 20\n\n# Currying with capture\nadd = fn a -> fn b -> a + b end end\nadd5 = add.(5)\nadd5.(3)  # 8\n\n# Pattern matching in functions\ndefmodule Math do\n  def factorial(0), do: 1\n  def factorial(n) when n > 0, do: n * factorial(n - 1)\nend\n\n# With clause (monadic)\nwith {:ok, a} <- fetch_a(),\n     {:ok, b} <- fetch_b(a),\n     {:ok, c} <- fetch_c(b) do\n  {:ok, c}\nelse\n  {:error, reason} -> {:error, reason}\nend\n\n# Reduce\nEnum.reduce([1,2,3,4], 0, &+/2)  # 10",
    "Clojure": ";; Threading macros (pipe)\n(->> (range 1 6)\n     (filter even?)\n     (map #(* % %))\n     (reduce +))  ;; 20\n\n;; Thread-first\n(-> {:name \"Alice\" :age 30}\n    (assoc :role \"admin\")\n    (update :age inc))\n\n;; Partial application\n(def add5 (partial + 5))\n(add5 3)  ;; 8\n\n;; Comp (compose)\n(def process (comp (partial reduce +)\n                   (partial map #(* % %))\n                   (partial filter even?)))\n(process (range 1 6))  ;; 20\n\n;; Monadic (cats library)\n;; (m/mlet [a (some-fn 1)\n;;          b (some-fn a)]\n;;   (m/return (+ a b)))",
    "F#": "// Pipe operator\n[1..5]\n|> List.filter (fun x -> x % 2 = 0)\n|> List.map (fun x -> x * x)\n|> List.sum  // 20\n\n// Composition\nlet process = List.filter (fun x -> x % 2 = 0)\n              >> List.map (fun x -> x * x)\n              >> List.sum\n\nprocess [1..5]  // 20\n\n// Currying (automatic)\nlet add a b c = a + b + c\nlet add5 = add 5\nadd5 3 2  // 10\n\n// Option as monad\nlet safeDivide a b = if b = 0 then None else Some (a / b)\n\nlet result =\n    safeDivide 10 2\n    |> Option.bind (fun x -> safeDivide x 0)\n    |> Option.defaultValue 0\n\n// Computation expressions\nlet maybe = MaybeBuilder()\nlet result = maybe {\n    let! x = Some 5\n    let! y = Some 3\n    return x + y\n}",
    "OCaml": "(* Pipe operator *)\nlet result =\n  [1;2;3;4;5]\n  |> List.filter (fun x -> x mod 2 = 0)\n  |> List.map (fun x -> x * x)\n  |> List.fold_left (+) 0  (* 20 *)\n\n(* Composition *)\nlet (>>) f g x = g (f x)\nlet process =\n  List.filter (fun x -> x mod 2 = 0)\n  >> List.map (fun x -> x * x)\n  >> List.fold_left (+) 0\n\n(* Currying (automatic) *)\nlet add a b c = a + b + c\nlet add5 = add 5\n\n(* Option monad *)\nlet (>>=) opt f = match opt with Some x -> f x | None -> None\nlet safe_div a b = if b = 0 then None else Some (a / b)\nlet result = safe_div 10 2 >>= fun x -> safe_div x 0",
    "Swift": "// Method chaining\nlet result = [1,2,3,4,5]\n    .filter { $0 % 2 == 0 }\n    .map { $0 * $0 }\n    .reduce(0, +)  // 20\n\n// Custom pipe operator\nprecedencegroup PipeRight { associativity: left }\ninfix operator |>: PipeRight\nfunc |><A, B>(value: A, fn: (A) -> B) -> B { fn(value) }\n\n5 |> { $0 * 2 } |> { $0 + 1 }  // 11\n\n// Result as monad\nfunc safeDivide(_ a: Double, _ b: Double) -> Result<Double, Error> {\n    b == 0 ? .failure(MathError.divisionByZero) : .success(a / b)\n}\n\nlet r = safeDivide(10, 2).flatMap { safeDivide($0, 0) }",
    "Kotlin": "// Extension functions as pipes\nval result = (1..5)\n    .filter { it % 2 == 0 }\n    .map { it * it }\n    .sum()  // 20\n\n// let/run/with/apply/also\nval len = \"hello\"\n    .let { it.uppercase() }\n    .let { it.length }  // 5\n\n// Arrow (functional library)\n// import arrow.core.*\n// val result = Some(5).flatMap { x -> Some(x * 2) }\n\n// Sealed class as Result monad\nsealed class Result<out T> {\n    data class Ok<T>(val value: T) : Result<T>()\n    data class Err(val error: String) : Result<Nothing>()\n    fun <R> map(f: (T) -> R): Result<R> = when (this) {\n        is Ok -> Ok(f(value))\n        is Err -> this\n    }\n}",
    "Go": "// Go is not traditionally functional but supports patterns\n\n// Map/Filter/Reduce with generics (Go 1.18+)\nfunc Map[T, U any](s []T, f func(T) U) []U {\n    r := make([]U, len(s))\n    for i, v := range s { r[i] = f(v) }\n    return r\n}\n\nfunc Filter[T any](s []T, f func(T) bool) []T {\n    var r []T\n    for _, v := range s { if f(v) { r = append(r, v) } }\n    return r\n}\n\nfunc Reduce[T, U any](s []T, init U, f func(U, T) U) U {\n    acc := init\n    for _, v := range s { acc = f(acc, v) }\n    return acc\n}\n\n// Pipe via chaining\nnums := []int{1,2,3,4,5}\nevens := Filter(nums, func(x int) bool { return x%2 == 0 })\nsquares := Map(evens, func(x int) int { return x*x })\nsum := Reduce(squares, 0, func(a, x int) int { return a+x })",
    "Java": "// Stream API (functional style)\nint result = IntStream.rangeClosed(1, 5)\n    .filter(x -> x % 2 == 0)\n    .map(x -> x * x)\n    .sum();  // 20\n\n// Function composition\nFunction<Integer, Integer> doubleIt = x -> x * 2;\nFunction<Integer, Integer> addOne = x -> x + 1;\nvar composed = doubleIt.andThen(addOne);\ncomposed.apply(5);  // 11\n\n// Optional as monad\nOptional.of(10)\n    .map(x -> x / 2)\n    .filter(x -> x > 0)\n    .flatMap(x -> x == 0 ? Optional.empty() : Optional.of(100 / x))\n    .orElse(0);",
    "C#": "// LINQ (functional)\nvar result = Enumerable.Range(1, 5)\n    .Where(x => x % 2 == 0)\n    .Select(x => x * x)\n    .Sum();  // 20\n\n// Pipe with extension methods\npublic static class FuncExt {\n    public static TOut Pipe<TIn, TOut>(this TIn x, Func<TIn, TOut> f) => f(x);\n}\n5.Pipe(x => x * 2).Pipe(x => x + 1);  // 11\n\n// LINQ query syntax\nvar q = from x in Enumerable.Range(1, 5)\n        where x % 2 == 0\n        select x * x;\nq.Sum();",
    "Ruby": "# Method chaining\nresult = (1..5)\n  .select(&:even?)\n  .map { |x| x ** 2 }\n  .sum  # 20\n\n# Proc composition (Ruby 2.6+)\ndouble = ->(x) { x * 2 }\nadd_one = ->(x) { x + 1 }\nprocess = double >> add_one\nprocess.call(5)  # 11\n\n# Curry\nadd = ->(a, b, c) { a + b + c }.curry\nadd.(1).(2).(3)  # 6\n\n# then (pipe)\n5.then { |x| x * 2 }.then { |x| x + 1 }  # 11",
    "TypeScript": "// Pipe\nconst pipe = <T>(...fns: ((x: T) => T)[]) => (x: T): T =>\n  fns.reduce((v, f) => f(v), x);\n\nconst process = (nums: number[]) =>\n  nums.filter(x => x % 2 === 0)\n      .map(x => x ** 2)\n      .reduce((a, b) => a + b, 0);\n\nprocess([1,2,3,4,5]);  // 20\n\n// fp-ts\nimport { pipe } from 'fp-ts/function';\nimport * as O from 'fp-ts/Option';\n\nconst result = pipe(\n  O.some(10),\n  O.map(x => x / 2),\n  O.filter(x => x > 0),\n  O.getOrElse(() => 0)\n);",
    "C++": "// Ranges (C++20) for functional style\n#include <ranges>\n\nauto result = std::views::iota(1, 6)\n    | std::views::filter([](int x) { return x % 2 == 0; })\n    | std::views::transform([](int x) { return x * x; });\n\nint sum = 0;\nfor (auto x : result) sum += x;  // 20\n\n// std::optional chaining\nstd::optional<int> safeDivide(int a, int b) {\n    return b == 0 ? std::nullopt : std::optional(a / b);\n}\nauto r = safeDivide(10, 2)\n    .and_then([](int x) { return safeDivide(x, 0); })\n    .value_or(0);",
    "Dart": "final result = [1,2,3,4,5]\n    .where((x) => x % 2 == 0)\n    .map((x) => x * x)\n    .reduce((a, b) => a + b);  // 20\n\n// Cascade for chaining\nfinal list = [3, 1, 4]\n  ..sort()\n  ..add(5);",
    "Julia": "# Pipe operator\nresult = 1:5 |>\n    x -> filter(iseven, x) |>\n    x -> map(y -> y^2, x) |>\n    sum  # 20\n\n# Composition\nf = iseven ∘ abs  # compose\nf(-4)  # true\n\n# Broadcasting (functional on arrays)\n(1:5) .^ 2  # [1, 4, 9, 16, 25]\nfilter(iseven, 1:10) .|> (x -> x^2) |> sum",
    "Lua": "-- Manual functional patterns\nlocal function pipe(val, ...)\n    for _, fn in ipairs({...}) do val = fn(val) end\n    return val\nend\n\nlocal function map(t, f)\n    local r = {}\n    for _, v in ipairs(t) do r[#r+1] = f(v) end\n    return r\nend\n\nlocal function filter(t, f)\n    local r = {}\n    for _, v in ipairs(t) do if f(v) then r[#r+1] = v end end\n    return r\nend\n\nlocal function reduce(t, init, f)\n    local acc = init\n    for _, v in ipairs(t) do acc = f(acc, v) end\n    return acc\nend\n\nlocal sum = reduce(map(filter({1,2,3,4,5},\n    function(x) return x%2==0 end),\n    function(x) return x*x end), 0,\n    function(a,b) return a+b end)  -- 20",
    "PHP": "// array functions as functional patterns\n$result = array_sum(\n    array_map(fn($x) => $x ** 2,\n        array_filter(range(1, 5), fn($x) => $x % 2 === 0)\n    )\n);  // 20\n\n// Pipe pattern\nfunction pipe($value, callable ...$fns) {\n    return array_reduce($fns, fn($v, $f) => $f($v), $value);\n}",
    "Nim": "import sequtils, sugar\n\nlet result = toSeq(1..5)\n  .filterIt(it mod 2 == 0)\n  .mapIt(it * it)\n  .foldl(a + b)  # 20\n\n# Pipe via method chaining\nlet r = @[1, 2, 3, 4, 5]\n  .filter(x => x mod 2 == 0)\n  .map(x => x * x)\n  .foldl(a + b)",
    "Crystal": "result = (1..5)\n  .select(&.even?)\n  .map { |x| x ** 2 }\n  .sum  # 20\n\n# Pipe via tap/try\n5.tap { |x| puts x }.to_s",
    "Erlang": "lists:sum(\n    lists:map(fun(X) -> X * X end,\n        lists:filter(fun(X) -> X rem 2 =:= 0 end,\n            lists:seq(1, 5)))).  %% 20\n\n%% Pipe via chaining\n%% R = lists:seq(1, 5),\n%% R1 = lists:filter(fun(X) -> X rem 2 =:= 0 end, R),\n%% R2 = lists:map(fun(X) -> X * X end, R1),\n%% lists:sum(R2).",
    "Perl": "use List::Util qw(sum reduce);\n\nmy @nums = (1..5);\nmy $result = sum map { $_ ** 2 } grep { $_ % 2 == 0 } @nums;  # 20\n\n# Currying\nsub curry {\n    my $f = shift;\n    sub { my @a = @_; sub { $f->(@a, @_) } }\n}",
    "R": "library(purrr)\nlibrary(magrittr)\n\n# Pipe\nresult <- 1:5 %>%\n  keep(~ .x %% 2 == 0) %>%\n  map_dbl(~ .x^2) %>%\n  reduce(`+`)  # 20\n\n# Base R pipe (4.1+)\n1:5 |> Filter(\\(x) x %% 2 == 0, x = _) |> sapply(\\(x) x^2) |> sum()",
    "Racket": "(require racket/list)\n\n(define result\n  (~>> (range 1 6)\n       (filter even?)\n       (map (lambda (x) (* x x)))\n       (foldl + 0)))  ;; 20\n\n;; Compose\n(define process\n  (compose (curry foldl + 0)\n           (curry map sqr)\n           (curry filter even?)))",
    "D": "import std.algorithm, std.range;\n\nauto result = iota(1, 6)\n    .filter!(x => x % 2 == 0)\n    .map!(x => x * x)\n    .sum;  // 20",
    "Zig": "// Zig is imperative, but supports functional-like patterns\nvar sum: i32 = 0;\nfor ([_]i32{1,2,3,4,5}) |x| {\n    if (x % 2 == 0) sum += x * x;\n}\n// sum = 20",
    "C": "// C is imperative; functional patterns require manual implementation\nint nums[] = {1, 2, 3, 4, 5};\nint sum = 0;\nfor (int i = 0; i < 5; i++) {\n    if (nums[i] % 2 == 0) sum += nums[i] * nums[i];\n}\n// sum = 20\n\n// Function pointers for HOF\ntypedef int (*IntFn)(int);\nint apply(IntFn f, int x) { return f(x); }",
}

EXPANDED_V10["scope_lifetime"] = {
    "Python": "# Function scope\nx = 'global'\ndef outer():\n    x = 'outer'\n    def inner():\n        x = 'inner'  # New local, doesn't modify outer\n        print(x)  # 'inner'\n    inner()\n    print(x)  # 'outer'\n\n# nonlocal\ndef counter():\n    count = 0\n    def increment():\n        nonlocal count\n        count += 1\n        return count\n    return increment\n\n# global\ndef modify_global():\n    global x\n    x = 'modified'\n\n# LEGB rule: Local → Enclosing → Global → Built-in\n\n# Context managers for resource lifetime\nclass ManagedResource:\n    def __enter__(self): return self\n    def __exit__(self, *args): self.cleanup()\n\nwith ManagedResource() as r:\n    pass  # r.cleanup() called automatically",
    "Rust": "// Ownership + Lifetimes = Memory safety without GC\n\n// Scope-based ownership\n{\n    let s = String::from(\"hello\");  // s owns the string\n    // s is valid here\n}  // s dropped here, memory freed\n\n// Borrowing within scope\nfn first_word(s: &str) -> &str {\n    &s[..s.find(' ').unwrap_or(s.len())]\n}\n\n// Lifetime annotations\nfn longest<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}\n\n// Struct with lifetime\nstruct Excerpt<'a> {\n    text: &'a str,\n}\n\n// Static lifetime\nlet s: &'static str = \"I live forever\";\n\n// Scope guard with Drop\nstruct Guard;\nimpl Drop for Guard {\n    fn drop(&mut self) { println!(\"Scope exited\"); }\n}\n{\n    let _g = Guard;\n    // ... work ...\n}  // \"Scope exited\" printed here",
    "JavaScript": "// Block scope (let/const)\n{\n  let x = 42;\n  const y = 'hello';\n}  // x, y not accessible here\n\n// var is function-scoped (hoisted)\nfunction foo() {\n  console.log(x);  // undefined (hoisted)\n  var x = 42;\n}\n\n// Closure captures\nfunction makeCounter() {\n  let count = 0;  // Enclosed in closure\n  return {\n    increment: () => ++count,\n    getCount: () => count,\n  };\n}\n\n// IIFE for scope isolation\n(function() {\n  var private = 'hidden';\n})();\n// private not accessible\n\n// Module scope\n// Each file has its own scope in ES modules\n\n// Temporal dead zone\n// console.log(x);  // ReferenceError\n// let x = 42;",
    "Go": "// Block scope\n{\n    x := 42\n    fmt.Println(x)\n}  // x not accessible\n\n// Function scope\nfunc foo() {\n    y := \"hello\"  // Local to foo\n}\n\n// Package scope (capitalization = visibility)\nvar PublicVar = 42   // Exported (accessible outside package)\nvar privateVar = 42  // Unexported (package-only)\n\n// Short variable declaration scope\nif x := compute(); x > 0 {\n    fmt.Println(x)  // x scoped to if block\n}\n\n// defer for cleanup (scope exit)\nfunc process() {\n    f, _ := os.Open(\"file.txt\")\n    defer f.Close()  // Called when function returns\n    // ... use f ...\n}",
    "C": "// Block scope\n{\n    int x = 42;\n}  // x no longer exists\n\n// Function scope\nvoid foo() {\n    int local = 42;  // Stack allocated, freed on return\n}\n\n// File scope (static)\nstatic int file_var = 42;  // Only accessible in this file\n\n// Global scope\nint global_var = 42;  // Accessible everywhere\n\n// Static local (persists across calls)\nvoid counter() {\n    static int count = 0;\n    count++;\n    printf(\"%d\\n\", count);\n}\ncounter();  // 1\ncounter();  // 2\n\n// Lifetime: stack vs heap\nvoid example() {\n    int stack = 42;          // Auto lifetime (function scope)\n    int* heap = malloc(4);   // Manual lifetime\n    free(heap);              // Must manually end lifetime\n}",
    "C++": "// Block scope + RAII\n{\n    std::string s = \"hello\";  // Constructed\n}  // Destructor called, memory freed\n\n// Scope guard pattern\nclass ScopeGuard {\n    std::function<void()> cleanup_;\npublic:\n    ScopeGuard(std::function<void()> fn) : cleanup_(fn) {}\n    ~ScopeGuard() { cleanup_(); }\n};\n\n{\n    auto guard = ScopeGuard([]{ std::cout << \"cleanup\\n\"; });\n    // ... work ...\n}  // \"cleanup\" printed\n\n// static local (initialized once)\nint& getCounter() {\n    static int count = 0;\n    return ++count;\n}\n\n// Namespace scope\nnamespace mylib {\n    int x = 42;\n}\nmylib::x;\n\n// Lifetime extension via const ref\nconst std::string& ref = std::string(\"temp\");  // Extended",
    "Java": "// Block scope\n{\n    int x = 42;\n}  // x gone\n\n// Method scope\nvoid foo() {\n    String local = \"hello\";  // GC-eligible after foo returns\n}\n\n// Instance scope\nclass MyClass {\n    private int instanceVar;  // Lives as long as the object\n    private static int classVar;  // Lives as long as the class\n}\n\n// try-with-resources (scope-based cleanup)\ntry (var stream = new FileInputStream(\"data.txt\")) {\n    // stream auto-closed when scope exits\n}\n\n// Effectively final (for lambdas)\nvoid process() {\n    int x = 42;  // Effectively final\n    Runnable r = () -> System.out.println(x);  // Captures x\n}",
    "TypeScript": "// Block scope\n{\n  let x: number = 42;\n  const y: string = 'hello';\n}  // x, y not accessible\n\n// Module scope (each file is a module)\nexport const publicVar = 42;\nconst privateVar = 42;  // Not exported\n\n// Closure\nfunction makeAdder(n: number): (x: number) => number {\n  return (x) => x + n;  // n captured from enclosing scope\n}\n\n// using (TC39 Stage 3 — explicit resource management)\n// using file = new FileHandle('data.txt');\n// ... file auto-disposed when scope exits",
    "Swift": "// Block scope\ndo {\n    let x = 42\n}  // x gone\n\n// Function scope\nfunc foo() {\n    let local = \"hello\"  // Freed when function returns (ARC)\n}\n\n// Closure capture\nfunc makeCounter() -> () -> Int {\n    var count = 0\n    return { count += 1; return count }  // Captures count\n}\n\n// Access control (scope visibility)\npublic class MyClass {\n    public var publicProp = 0\n    internal var internalProp = 0  // Module-scoped\n    fileprivate var fileProp = 0   // File-scoped\n    private var privateProp = 0    // Type-scoped\n}\n\n// defer\nfunc process() {\n    let file = openFile()\n    defer { file.close() }  // Called when scope exits\n}",
    "Kotlin": "// Block scope\nrun {\n    val x = 42\n}  // x gone\n\n// Visibility modifiers\nclass MyClass {\n    public val publicProp = 0\n    internal val internalProp = 0  // Module-scoped\n    protected val protectedProp = 0\n    private val privateProp = 0\n}\n\n// use (scope-based cleanup)\nFileInputStream(\"data.txt\").use { stream ->\n    // stream auto-closed\n}\n\n// Coroutine scope\ncoroutineScope {\n    launch { /* Cancelled if scope cancelled */ }\n}",
    "Ruby": "# Method scope\ndef foo\n  x = 42  # Local to foo\nend\n\n# Block scope\n[1,2,3].each do |x|\n  y = x * 2  # y is local to block\nend\n# y not accessible here\n\n# Closure\ndef make_counter\n  count = 0\n  increment = -> { count += 1; count }\n  increment\nend\n\n# Module/Class scope\nmodule MyModule\n  CONSTANT = 42  # Module-scoped constant\n  @@class_var = 0  # Class variable\n  @instance_var = 0  # Instance variable\nend\n\n# ensure (cleanup)\nbegin\n  file = File.open('data.txt')\nensure\n  file&.close\nend",
    "Haskell": "-- Haskell: All bindings are immutable, scope is lexical\n\n-- let bindings (local scope)\nlet x = 42 in x + 1  -- 43\n\n-- where clause\nresult = a + b\n  where\n    a = 10\n    b = 20\n\n-- Lambda scope\nlet add5 = \\x -> x + 5  -- x is scoped to lambda\n\n-- Module exports (visibility)\nmodule MyModule (publicFn, PublicType) where\npublicFn = 42\nprivateFn = 0  -- Not exported\n\n-- do notation scope\nmain = do\n  x <- getLine  -- x scoped to rest of do block\n  putStrLn x",
    "Elixir": "# Elixir has lexical scope\n\n# Function scope\ndef foo do\n  x = 42  # Local to foo\nend\n\n# Block scope (with/case/if DON'T create new scope!)\nx = 1\nif true do\n  x = 2  # Rebinds x in outer scope!\nend\nIO.puts(x)  # 2\n\n# Module scope\ndefmodule MyModule do\n  @module_attr 42  # Module attribute (compile-time)\n  def get_attr, do: @module_attr\nend\n\n# Process scope (each process has isolated state)\nspawn(fn -> x = 42 end)  # x only in spawned process",
    "PHP": "// Function scope\nfunction foo() {\n    $x = 42;  // Local\n}\n\n// Global access\n$global = 42;\nfunction bar() {\n    global $global;  // Must explicitly import\n    echo $global;\n}\n\n// Static local\nfunction counter() {\n    static $count = 0;\n    return ++$count;\n}\ncounter();  // 1\ncounter();  // 2\n\n// Closure capture\n$x = 42;\n$fn = function() use ($x) { return $x; };\n$fn2 = function() use (&$x) { $x++; };  // By reference\n\n// Namespace\nnamespace App\\Models;\nclass User {}  // App\\Models\\User",
    "Lua": "-- Function scope\nlocal x = 42  -- Local to current scope\ny = 42  -- Global (no local keyword)\n\n-- Block scope\ndo\n    local z = 42\nend\n-- z not accessible\n\n-- Closure\nlocal function make_counter()\n    local count = 0\n    return function()\n        count = count + 1\n        return count\n    end\nend\n\n-- Upvalues (captured variables)\nlocal a = 1\nlocal function foo()\n    -- a is an upvalue here\n    print(a)\nend",
    "Julia": "# Module scope\nmodule MyModule\n    export public_fn\n    public_fn() = 42\n    private_fn() = 0  # Not exported\nend\n\n# Local scope (let block)\nlet x = 42\n    println(x)\nend\n\n# Function scope\nfunction foo()\n    local_var = 42  # Local to foo\nend\n\n# Global scope (explicit in functions)\nglobal_var = 42\nfunction bar()\n    global global_var\n    global_var += 1\nend",
    "Dart": "// Block scope\n{\n  final x = 42;\n}  // x gone\n\n// Library scope (each file is a library)\nfinal _private = 42;  // Underscore = library-private\nfinal public = 42;\n\n// Class scope\nclass MyClass {\n  final int _privateProp;  // Private to library\n  final int publicProp;\n  MyClass(this._privateProp, this.publicProp);\n}\n\n// Closure\nFunction makeCounter() {\n  var count = 0;\n  return () => ++count;\n}",
    "Clojure": ";; let binding (local scope)\n(let [x 42\n      y (+ x 1)]\n  (println x y))  ;; 42 43\n;; x, y not accessible here\n\n;; def (namespace scope)\n(def ^:private private-var 42)  ;; Private to namespace\n(def public-var 42)  ;; Public\n\n;; Closure\n(defn make-counter []\n  (let [count (atom 0)]\n    (fn [] (swap! count inc))))\n\n;; Dynamic scope\n(def ^:dynamic *debug* false)\n(binding [*debug* true]\n  (when *debug* (println \"debug mode\")))",
    "Nim": "# Block scope\nblock:\n  let x = 42\n# x gone\n\n# Module scope\nproc publicProc*() = discard  # * = exported\nproc privateProc() = discard  # Not exported\n\n# Closure\nproc makeCounter(): proc(): int =\n  var count = 0\n  return proc(): int =\n    count += 1\n    count",
    "Crystal": "# Block scope\nbegin\n  x = 42\nend\n# x accessible (Crystal doesn't have true block scope for begin)\n\n# Visibility\nclass MyClass\n  def public_method; end\n  private def private_method; end\n  protected def protected_method; end\nend\n\n# Closure\ncounter = 0\nincrement = -> { counter += 1; counter }",
    "Erlang": "%% Function clause scope\nfoo() ->\n    X = 42,  %% X bound in this clause\n    X.\n\n%% Pattern matching creates bindings\ncase {1, 2} of\n    {A, B} -> A + B  %% A, B scoped to this clause\nend.\n\n%% Module scope\n-module(my_module).\n-export([public_fn/0]).  %% Only exported functions are accessible\npublic_fn() -> 42.\nprivate_fn() -> 0.  %% Not exported",
    "Racket": ";; let (local scope)\n(let ([x 42] [y 43])\n  (+ x y))  ;; 85\n;; x, y not accessible\n\n;; define (module scope)\n(provide public-fn)  ;; Export\n(define (public-fn) 42)\n(define (private-fn) 0)  ;; Not provided\n\n;; Closure\n(define (make-counter)\n  (define count 0)\n  (lambda ()\n    (set! count (add1 count))\n    count))",
    "OCaml": "(* let binding scope *)\nlet result =\n  let x = 42 in\n  let y = x + 1 in\n  y  (* 43 *)\n(* x, y not accessible *)\n\n(* Module scope *)\nmodule MyModule : sig\n  val public_fn : int -> int  (* Exposed *)\nend = struct\n  let public_fn x = x + 1\n  let private_fn x = x - 1  (* Hidden by signature *)\nend",
    "F#": "// let binding scope\nlet result =\n    let x = 42\n    let y = x + 1\n    y  // 43\n\n// Module scope\nmodule MyModule =\n    let publicFn x = x + 1\n    let private privateFn x = x - 1\n\n// Closure\nlet makeCounter () =\n    let mutable count = 0\n    fun () -> count <- count + 1; count\n\n// use (scope-based cleanup)\nuse file = File.OpenRead(\"data.txt\")\n// file disposed when scope exits",
    "D": "// Block scope\n{\n    int x = 42;\n}  // x gone\n\n// Module scope\nmodule mymodule;\npublic int publicVar = 42;\nprivate int privateVar = 0;\n\n// scope(exit) guard\nvoid process() {\n    auto file = File(\"data.txt\");\n    scope(exit) file.close();  // Called when scope exits\n    scope(failure) rollback();  // Called on exception\n    scope(success) commit();  // Called on normal exit\n}",
    "Perl": "# Lexical scope (my)\n{\n    my $x = 42;\n}\n# $x gone\n\n# Dynamic scope (local)\nour $global = 42;\nsub foo { local $global = 0; bar(); }\nsub bar { print $global; }  # 0 (dynamic scope!)\n\n# Closure\nsub make_counter {\n    my $count = 0;\n    return sub { ++$count };\n}",
    "R": "# Function scope\nfoo <- function() {\n  x <- 42  # Local\n  x\n}\n\n# Lexical scoping\nx <- 'global'\nfoo <- function() {\n  bar <- function() print(x)  # Looks up to parent env\n  bar()\n}\n\n# Environment manipulation\ne <- new.env(parent = emptyenv())\ne$x <- 42\nls(e)  # 'x'",
    "Zig": "// Block scope\n{\n    const x: i32 = 42;\n}  // x gone\n\n// Function scope\nfn foo() void {\n    var local: i32 = 42;\n}  // local freed (stack)\n\n// defer (scope-based cleanup)\nfn process() !void {\n    const file = try std.fs.cwd().openFile(\"data.txt\", .{});\n    defer file.close();  // Called when scope exits\n    // ... use file ...\n}\n\n// comptime scope\ncomptime {\n    var x: i32 = 0;  // Only exists at compile time\n}",
}

EXPANDED_V10["property_access"] = {
    "Python": "class User:\n    def __init__(self, name, age):\n        self._name = name\n        self._age = age\n    \n    @property\n    def name(self): return self._name\n    \n    @name.setter\n    def name(self, value):\n        if not value: raise ValueError('Name required')\n        self._name = value\n    \n    @property\n    def age(self): return self._age\n    \n    @age.setter\n    def age(self, value):\n        if value < 0: raise ValueError('Age must be positive')\n        self._age = value\n    \n    # Computed property\n    @property\n    def is_adult(self): return self._age >= 18\n\n# __getattr__ / __setattr__\nclass Dynamic:\n    def __getattr__(self, name): return f'dynamic_{name}'\n\n# Descriptor protocol\nclass Validated:\n    def __set_name__(self, owner, name): self.name = name\n    def __get__(self, obj, type): return obj.__dict__.get(self.name)\n    def __set__(self, obj, value): obj.__dict__[self.name] = value",
    "JavaScript": "class User {\n  #name;  // Private field\n  #age;\n\n  constructor(name, age) {\n    this.#name = name;\n    this.#age = age;\n  }\n\n  get name() { return this.#name; }\n  set name(value) {\n    if (!value) throw new Error('Name required');\n    this.#name = value;\n  }\n\n  get age() { return this.#age; }\n  set age(value) {\n    if (value < 0) throw new Error('Age must be positive');\n    this.#age = value;\n  }\n\n  // Computed\n  get isAdult() { return this.#age >= 18; }\n}\n\n// Proxy for dynamic access\nconst handler = {\n  get(target, prop) { return prop in target ? target[prop] : `dynamic_${prop}`; },\n  set(target, prop, value) { target[prop] = value; return true; },\n};\n\n// Object.defineProperty\nObject.defineProperty(obj, 'readonly', {\n  get() { return 42; },\n  enumerable: true,\n});",
    "Rust": "// Rust doesn't have properties — use methods\nstruct User {\n    name: String,\n    age: u32,\n}\n\nimpl User {\n    fn new(name: &str, age: u32) -> Self {\n        User { name: name.into(), age }\n    }\n    // Getter\n    fn name(&self) -> &str { &self.name }\n    fn age(&self) -> u32 { self.age }\n    \n    // Setter\n    fn set_name(&mut self, name: &str) {\n        assert!(!name.is_empty(), \"Name required\");\n        self.name = name.into();\n    }\n    \n    // Computed\n    fn is_adult(&self) -> bool { self.age >= 18 }\n}\n\n// Deref for smart access\nuse std::ops::Deref;\nimpl Deref for Wrapper {\n    type Target = Inner;\n    fn deref(&self) -> &Inner { &self.0 }\n}",
    "Go": "type User struct {\n    name string  // unexported (private)\n    age  int\n}\n\n// Getter\nfunc (u *User) Name() string { return u.name }\nfunc (u *User) Age() int { return u.age }\n\n// Setter with validation\nfunc (u *User) SetName(name string) error {\n    if name == \"\" { return errors.New(\"name required\") }\n    u.name = name\n    return nil\n}\n\nfunc (u *User) SetAge(age int) error {\n    if age < 0 { return errors.New(\"age must be positive\") }\n    u.age = age\n    return nil\n}\n\n// Computed\nfunc (u *User) IsAdult() bool { return u.age >= 18 }",
    "Kotlin": "class User(name: String, age: Int) {\n    var name: String = name\n        set(value) {\n            require(value.isNotBlank()) { \"Name required\" }\n            field = value\n        }\n    \n    var age: Int = age\n        set(value) {\n            require(value >= 0) { \"Age must be positive\" }\n            field = value\n        }\n    \n    // Computed (no backing field)\n    val isAdult: Boolean get() = age >= 18\n    \n    // Lazy\n    val expensiveComputed: String by lazy { computeExpensive() }\n    \n    // Delegated\n    var observed: String by Delegates.observable(\"initial\") { _, old, new ->\n        println(\"$old -> $new\")\n    }\n}",
    "Swift": "class User {\n    private var _name: String\n    private var _age: Int\n    \n    init(name: String, age: Int) {\n        _name = name\n        _age = age\n    }\n    \n    var name: String {\n        get { _name }\n        set {\n            precondition(!newValue.isEmpty, \"Name required\")\n            _name = newValue\n        }\n    }\n    \n    var age: Int {\n        get { _age }\n        set {\n            precondition(newValue >= 0, \"Age must be positive\")\n            _age = newValue\n        }\n    }\n    \n    // Computed\n    var isAdult: Bool { age >= 18 }\n    \n    // Lazy\n    lazy var expensive: String = computeExpensive()\n    \n    // willSet/didSet\n    var score: Int = 0 {\n        willSet { print(\"Will change to \\(newValue)\") }\n        didSet { print(\"Changed from \\(oldValue)\") }\n    }\n}",
    "C#": "class User {\n    private string _name;\n    private int _age;\n\n    public string Name {\n        get => _name;\n        set => _name = !string.IsNullOrEmpty(value)\n            ? value : throw new ArgumentException(\"Name required\");\n    }\n\n    public int Age {\n        get => _age;\n        set => _age = value >= 0\n            ? value : throw new ArgumentException(\"Age must be positive\");\n    }\n\n    // Computed\n    public bool IsAdult => Age >= 18;\n\n    // Auto-property\n    public string Email { get; set; }\n    public string Id { get; init; }  // Init-only (C# 9)\n\n    // Indexer\n    public string this[int index] => index == 0 ? Name : \"\";\n}",
    "Java": "public class User {\n    private String name;\n    private int age;\n\n    public String getName() { return name; }\n    public void setName(String name) {\n        if (name == null || name.isEmpty()) throw new IllegalArgumentException(\"Name required\");\n        this.name = name;\n    }\n\n    public int getAge() { return age; }\n    public void setAge(int age) {\n        if (age < 0) throw new IllegalArgumentException(\"Age must be positive\");\n        this.age = age;\n    }\n\n    // Computed\n    public boolean isAdult() { return age >= 18; }\n}\n\n// Record (immutable, auto-getters)\nrecord Point(double x, double y) {\n    double magnitude() { return Math.sqrt(x*x + y*y); }\n}",
    "Ruby": "class User\n  attr_reader :name, :age\n\n  def initialize(name, age)\n    self.name = name\n    self.age = age\n  end\n\n  def name=(value)\n    raise ArgumentError, 'Name required' if value.nil? || value.empty?\n    @name = value\n  end\n\n  def age=(value)\n    raise ArgumentError, 'Age must be positive' if value < 0\n    @age = value\n  end\n\n  # Computed\n  def adult?\n    @age >= 18\n  end\nend\n\n# method_missing for dynamic properties\nclass OpenStruct\n  def method_missing(name, *args)\n    name.to_s.end_with?('=') ? @data[name] = args[0] : @data[name]\n  end\nend",
    "TypeScript": "class User {\n  private _name: string;\n  private _age: number;\n\n  constructor(name: string, age: number) {\n    this._name = name;\n    this._age = age;\n  }\n\n  get name(): string { return this._name; }\n  set name(value: string) {\n    if (!value) throw new Error('Name required');\n    this._name = value;\n  }\n\n  get age(): number { return this._age; }\n  set age(value: number) {\n    if (value < 0) throw new Error('Age must be positive');\n    this._age = value;\n  }\n\n  get isAdult(): boolean { return this._age >= 18; }\n}",
    "C++": "class User {\n    std::string name_;\n    int age_;\npublic:\n    User(std::string name, int age) : name_(name), age_(age) {}\n    \n    const std::string& name() const { return name_; }\n    void set_name(const std::string& name) {\n        if (name.empty()) throw std::invalid_argument(\"Name required\");\n        name_ = name;\n    }\n    \n    int age() const { return age_; }\n    void set_age(int age) {\n        if (age < 0) throw std::invalid_argument(\"Age must be positive\");\n        age_ = age;\n    }\n    \n    bool is_adult() const { return age_ >= 18; }\n};",
    "PHP": "class User {\n    private string $name;\n    private int $age;\n\n    public function __construct(string $name, int $age) {\n        $this->setName($name);\n        $this->setAge($age);\n    }\n\n    public function getName(): string { return $this->name; }\n    public function setName(string $name): void {\n        if (empty($name)) throw new InvalidArgumentException('Name required');\n        $this->name = $name;\n    }\n\n    // Magic methods\n    public function __get(string $name) { return $this->$name ?? null; }\n    public function __set(string $name, $value) { $this->$name = $value; }\n    public function __isset(string $name): bool { return isset($this->$name); }\n}",
    "Dart": "class User {\n  String _name;\n  int _age;\n\n  User(this._name, this._age);\n\n  String get name => _name;\n  set name(String value) {\n    if (value.isEmpty) throw ArgumentError('Name required');\n    _name = value;\n  }\n\n  int get age => _age;\n  set age(int value) {\n    if (value < 0) throw ArgumentError('Age must be positive');\n    _age = value;\n  }\n\n  bool get isAdult => _age >= 18;\n}",
    "Scala": "class User(private var _name: String, private var _age: Int) {\n  def name: String = _name\n  def name_=(value: String): Unit = {\n    require(value.nonEmpty, \"Name required\")\n    _name = value\n  }\n  \n  def age: Int = _age\n  def age_=(value: Int): Unit = {\n    require(value >= 0, \"Age must be positive\")\n    _age = value\n  }\n  \n  def isAdult: Boolean = _age >= 18\n}\n\n// Case class (immutable, auto-getters)\ncase class Point(x: Double, y: Double) {\n  def magnitude: Double = math.sqrt(x*x + y*y)\n}",
    "Elixir": "defmodule User do\n  defstruct [:name, :age]\n\n  def new(name, age) do\n    %User{name: name, age: age}\n  end\n\n  def set_name(%User{} = user, name) when is_binary(name) and name != \"\" do\n    %{user | name: name}\n  end\n\n  def adult?(%User{age: age}), do: age >= 18\nend\n\n# Access via dot notation\nuser = User.new(\"Alice\", 30)\nuser.name  # \"Alice\"\nuser.age   # 30\nUser.adult?(user)  # true",
    "Julia": "mutable struct User\n    name::String\n    age::Int\nend\n\n# Getter\nname(u::User) = u.name\nage(u::User) = u.age\n\n# Setter with validation\nfunction set_name!(u::User, name::String)\n    isempty(name) && error(\"Name required\")\n    u.name = name\nend\n\n# Computed\nis_adult(u::User) = u.age >= 18\n\n# Overload getproperty/setproperty! for custom access\nfunction Base.getproperty(u::User, s::Symbol)\n    s === :is_adult && return u.age >= 18\n    getfield(u, s)\nend",
    "Nim": "type User = object\n  name: string\n  age: int\n\nproc name*(u: User): string = u.name\nproc age*(u: User): int = u.age\n\nproc `name=`*(u: var User, name: string) =\n  assert name.len > 0, \"Name required\"\n  u.name = name\n\nproc isAdult*(u: User): bool = u.age >= 18",
    "Clojure": ";; Maps as records (functional access)\n(def user {:name \"Alice\" :age 30})\n\n;; Access\n(:name user)  ;; \"Alice\"\n(get user :age)  ;; 30\n\n;; Update (returns new map)\n(assoc user :name \"Bob\")\n(update user :age inc)\n\n;; Spec for validation\n(s/def ::name (s/and string? not-empty))\n(s/def ::age (s/and int? pos?))\n(s/def ::user (s/keys :req-un [::name ::age]))\n(s/valid? ::user user)",
    "Haskell": "-- Record syntax\ndata User = User { userName :: String, userAge :: Int }\n\n-- Auto-generated getters\nlet u = User { userName = \"Alice\", userAge = 30 }\nuserName u  -- \"Alice\"\nuserAge u   -- 30\n\n-- Functional update\nlet u2 = u { userName = \"Bob\" }\n\n-- Lenses (lens library)\nimport Control.Lens\nmakeLenses ''User\nu ^. name  -- \"Alice\"\nu & name .~ \"Bob\"\nu & age %~ (+1)",
    "Crystal": "class User\n  getter name : String\n  getter age : Int32\n\n  def initialize(@name, @age); end\n\n  def name=(value : String)\n    raise \"Name required\" if value.empty?\n    @name = value\n  end\n\n  def adult?\n    @age >= 18\n  end\nend",
    "Lua": "local User = {}\nUser.__index = User\n\nfunction User.new(name, age)\n    return setmetatable({_name = name, _age = age}, User)\nend\n\n-- Getter/setter via __index/__newindex\nfunction User:getName() return self._name end\nfunction User:getAge() return self._age end\n\nfunction User:setName(name)\n    assert(name and #name > 0, 'Name required')\n    self._name = name\nend\n\nfunction User:isAdult() return self._age >= 18 end",
    "C": "// C uses getter/setter functions\ntypedef struct { char name[64]; int age; } User;\n\nconst char* user_get_name(const User* u) { return u->name; }\nint user_get_age(const User* u) { return u->age; }\n\nvoid user_set_name(User* u, const char* name) {\n    assert(name && strlen(name) > 0);\n    strncpy(u->name, name, sizeof(u->name) - 1);\n}\n\nint user_is_adult(const User* u) { return u->age >= 18; }",
    "Erlang": "%% Records\n-record(user, {name, age}).\n\nget_name(#user{name = Name}) -> Name.\nget_age(#user{age = Age}) -> Age.\n\nset_name(User, Name) when is_list(Name), length(Name) > 0 ->\n    User#user{name = Name}.\n\nis_adult(#user{age = Age}) -> Age >= 18.",
    "Racket": "(struct user (name age) #:transparent #:mutable)\n\n(define u (user \"Alice\" 30))\n(user-name u)  ;; \"Alice\"\n(user-age u)   ;; 30\n(set-user-name! u \"Bob\")\n\n;; Computed\n(define (user-adult? u)\n  (>= (user-age u) 18))",
    "F#": "type User = {\n    mutable Name: string\n    mutable Age: int\n} with\n    member this.IsAdult = this.Age >= 18\n\nlet u = { Name = \"Alice\"; Age = 30 }\nu.Name  // \"Alice\"\nu.IsAdult  // true\n\n// Immutable update\nlet u2 = { u with Name = \"Bob\" }",
    "OCaml": "type user = { mutable name: string; mutable age: int }\n\nlet create name age = { name; age }\nlet get_name u = u.name\nlet get_age u = u.age\nlet set_name u name =\n  assert (String.length name > 0);\n  u.name <- name\nlet is_adult u = u.age >= 18",
    "D": "class User {\n    private string _name;\n    private int _age;\n\n    @property string name() { return _name; }\n    @property void name(string value) {\n        enforce(!value.empty, \"Name required\");\n        _name = value;\n    }\n\n    @property bool isAdult() { return _age >= 18; }\n}",
    "Perl": "# Moose\npackage User;\nuse Moose;\n\nhas 'name' => (\n    is => 'rw', isa => 'Str',\n    trigger => sub { die 'Name required' unless $_[1] },\n);\n\nhas 'age' => (\n    is => 'rw', isa => 'Int',\n    trigger => sub { die 'Age must be positive' if $_[1] < 0 },\n);\n\nsub is_adult { $_[0]->age >= 18 }",
    "R": "# R5 reference classes\nUser <- setRefClass('User',\n  fields = list(name = 'character', age = 'numeric'),\n  methods = list(\n    initialize = function(name, age) {\n      stopifnot(nchar(name) > 0)\n      .self$name <- name\n      .self$age <- age\n    },\n    is_adult = function() .self$age >= 18\n  )\n)",
    "Zig": "const User = struct {\n    name: []const u8,\n    age: u32,\n\n    fn isAdult(self: User) bool {\n        return self.age >= 18;\n    }\n};\n\nconst u = User{ .name = \"Alice\", .age = 30 };\nu.name;  // \"Alice\"\nu.isAdult();  // true",
}

EXPANDED_V10["casting_conversion"] = {
    "Python": "# Type conversion\nint('42')     # 42\nfloat('3.14') # 3.14\nstr(42)       # '42'\nbool(1)       # True\nlist('abc')   # ['a', 'b', 'c']\ntuple([1,2])  # (1, 2)\nset([1,1,2])  # {1, 2}\ndict([('a',1)])  # {'a': 1}\n\n# isinstance check\nisinstance(42, int)  # True\nisinstance('hi', (str, bytes))  # True\n\n# Custom conversion\nclass Celsius:\n    def __init__(self, temp): self.temp = temp\n    def __float__(self): return self.temp\n    def __int__(self): return int(self.temp)\n    def to_fahrenheit(self): return self.temp * 9/5 + 32",
    "JavaScript": "// Implicit coercion\n'5' + 3;    // '53' (string concat)\n'5' - 3;    // 2 (numeric)\n!!'hello';  // true\n+'42';      // 42\n\n// Explicit conversion\nNumber('42');    // 42\nString(42);      // '42'\nBoolean(0);      // false\nparseInt('42px');  // 42\nparseFloat('3.14');  // 3.14\n\n// Array conversions\nArray.from('abc');  // ['a', 'b', 'c']\n[...new Set([1,1,2])];  // [1, 2]\nObject.entries({a:1});  // [['a', 1]]\nObject.fromEntries([['a', 1]]);  // {a: 1}\n\n// BigInt\nBigInt(42);  // 42n\nNumber(42n); // 42",
    "Rust": "// as (primitive casting)\nlet x: f64 = 42.0;\nlet y: i32 = x as i32;  // 42\nlet z: u8 = 256_u16 as u8;  // 0 (truncation!)\n\n// From/Into traits\nlet s: String = String::from(\"hello\");\nlet n: i64 = i32::from(42_i16) as i64;\n\nimpl From<Celsius> for Fahrenheit {\n    fn from(c: Celsius) -> Self {\n        Fahrenheit(c.0 * 9.0/5.0 + 32.0)\n    }\n}\nlet f: Fahrenheit = Celsius(100.0).into();\n\n// TryFrom (fallible)\nlet n: Result<u8, _> = u8::try_from(256_u16);  // Err\n\n// Parse\nlet n: i32 = \"42\".parse().unwrap();\nlet f: f64 = \"3.14\".parse().unwrap();",
    "Go": "// Type conversion (explicit)\nvar x float64 = 42.7\nvar y int = int(x)  // 42 (truncation)\nvar z float64 = float64(y)\n\n// String conversions\nimport \"strconv\"\ns := strconv.Itoa(42)  // \"42\"\nn, _ := strconv.Atoi(\"42\")  // 42\nf, _ := strconv.ParseFloat(\"3.14\", 64)\n\n// Type assertion\nvar i interface{} = \"hello\"\ns, ok := i.(string)  // \"hello\", true\n\n// Type switch\nswitch v := i.(type) {\ncase int:    fmt.Println(\"int\", v)\ncase string: fmt.Println(\"string\", v)\n}",
    "TypeScript": "// Type assertions\nconst x = someValue as string;\nconst y = <string>someValue;\n\n// Runtime conversions\nNumber('42');  // 42\nString(42);  // '42'\nBoolean('');  // false\nparseInt('42px');  // 42\n\n// Type narrowing\nfunction process(x: string | number): string {\n  if (typeof x === 'string') return x.toUpperCase();\n  return x.toFixed(2);\n}\n\n// Custom type guard\nfunction isUser(obj: any): obj is User {\n  return obj && typeof obj.name === 'string';\n}\n\n// satisfies operator\nconst config = { port: 8080 } satisfies Record<string, number>;",
    "Java": "// Widening (automatic)\nint x = 42;\nlong y = x;  // int -> long\ndouble z = x;  // int -> double\n\n// Narrowing (explicit cast)\ndouble d = 42.7;\nint n = (int) d;  // 42\nbyte b = (byte) 256;  // 0\n\n// String conversions\nString s = String.valueOf(42);  // \"42\"\nint parsed = Integer.parseInt(\"42\");\ndouble f = Double.parseDouble(\"3.14\");\n\n// Object casting\nObject obj = \"hello\";\nString str = (String) obj;\n\n// instanceof pattern (Java 16)\nif (obj instanceof String s2) {\n    System.out.println(s2.toUpperCase());\n}",
    "C": "// Implicit promotion\nint x = 42;\ndouble y = x;  // 42.0\n\n// Explicit cast\ndouble d = 42.7;\nint n = (int)d;  // 42\n\n// Pointer casts\nvoid* ptr = &x;\nint* ip = (int*)ptr;\n\n// String conversions\n#include <stdlib.h>\nint n2 = atoi(\"42\");\ndouble f = atof(\"3.14\");\nchar buf[20];\nsnprintf(buf, sizeof(buf), \"%d\", 42);",
    "C++": "// static_cast (safe)\ndouble d = 42.7;\nint n = static_cast<int>(d);  // 42\n\n// dynamic_cast (runtime, polymorphic)\nBase* bp = new Derived();\nDerived* dp = dynamic_cast<Derived*>(bp);\n\n// const_cast\nconst int* cp = &x;\nint* p = const_cast<int*>(cp);\n\n// reinterpret_cast (dangerous)\nint* ip = reinterpret_cast<int*>(0xDEADBEEF);\n\n// String conversions\nstd::to_string(42);  // \"42\"\nstd::stoi(\"42\");  // 42\nstd::stod(\"3.14\");  // 3.14",
    "C#": "// Implicit\nint x = 42;\nlong y = x;\ndouble z = x;\n\n// Explicit\ndouble d = 42.7;\nint n = (int)d;  // 42\n\n// Convert class\nint parsed = Convert.ToInt32(\"42\");\ndouble f = Convert.ToDouble(\"3.14\");\n\n// TryParse\nif (int.TryParse(\"42\", out int result)) { }\n\n// as (safe cast, reference types)\nobject obj = \"hello\";\nstring s = obj as string;  // \"hello\" or null\n\n// is + pattern\nif (obj is string str) { Console.WriteLine(str); }",
    "Swift": "// Type casting\nlet x: Double = 42.7\nlet n = Int(x)  // 42\nlet s = String(42)  // \"42\"\nlet f = Double(\"3.14\")  // Optional(3.14)\n\n// as (upcasting)\nlet animal: Animal = dog as Animal\n\n// as? (conditional downcast)\nif let dog = animal as? Dog {\n    dog.bark()\n}\n\n// as! (forced downcast)\nlet dog = animal as! Dog  // Crashes if not Dog\n\n// is (type check)\nif animal is Dog { print(\"It's a dog\") }",
    "Kotlin": "// Smart cast\nfun process(x: Any) {\n    if (x is String) println(x.uppercase())  // Auto-cast\n}\n\n// Safe cast\nval s: String? = obj as? String  // null if not String\n\n// Explicit conversion\nval n: Int = \"42\".toInt()\nval f: Double = \"3.14\".toDouble()\nval s: String = 42.toString()\n\n// toIntOrNull (safe)\nval parsed: Int? = \"abc\".toIntOrNull()  // null\n\n// Number conversions\nval x: Long = 42.toLong()\nval y: Float = 42.toFloat()",
    "Ruby": "# Conversion methods\n42.to_s        # '42'\n42.to_f        # 42.0\n'42'.to_i      # 42\n'3.14'.to_f    # 3.14\n[1,2].to_a     # [1, 2]\n\n# Kernel methods (strict)\nInteger('42')  # 42\nFloat('3.14')  # 3.14\n# Integer('abc')  # ArgumentError!\n\n# is_a?\n42.is_a?(Integer)    # true\n'hi'.is_a?(String)   # true\n42.is_a?(Numeric)    # true (parent class)\n\n# respond_to? (duck typing)\nobj.respond_to?(:to_str)",
    "Haskell": "-- fromIntegral (integer conversions)\nlet x = fromIntegral (42 :: Int) :: Double  -- 42.0\n\n-- show / read\nshow 42        -- \"42\"\nread \"42\" :: Int  -- 42\n\n-- realToFrac\nlet f = realToFrac (42 :: Int) :: Double\n\n-- Data.Text conversions\nimport qualified Data.Text as T\nT.pack \"hello\"  -- String -> Text\nT.unpack text   -- Text -> String",
    "Elixir": "# String conversions\nInteger.to_string(42)    # \"42\"\nString.to_integer(\"42\")  # 42\nFloat.to_string(3.14)    # \"3.14\"\nString.to_float(\"3.14\")  # 3.14\n\n# Atom/string\nAtom.to_string(:hello)   # \"hello\"\nString.to_atom(\"hello\")  # :hello\n\n# List/tuple\nTuple.to_list({1, 2, 3})  # [1, 2, 3]\nList.to_tuple([1, 2, 3])  # {1, 2, 3}\n\n# is_ guards\nis_integer(42)   # true\nis_binary(\"hi\")  # true\nis_atom(:ok)     # true",
    "Dart": "// Type casting\nfinal x = 42;\nfinal d = x.toDouble();  // 42.0\nfinal s = x.toString();  // '42'\nfinal n = int.parse('42');  // 42\nfinal f = double.parse('3.14');  // 3.14\n\n// tryParse\nfinal parsed = int.tryParse('abc');  // null\n\n// as (downcast)\nfinal obj = getObject();\nfinal user = obj as User;  // Throws if not User\n\n// is (type check)\nif (obj is User) { print(obj.name); }",
    "Julia": "# Conversion\nInt(42.7)       # 42 (truncation error if not exact)\nFloat64(42)     # 42.0\nstring(42)      # \"42\"\nparse(Int, \"42\")  # 42\nparse(Float64, \"3.14\")  # 3.14\n\n# tryparse\ntryparse(Int, \"abc\")  # nothing\n\n# convert\nconvert(Float64, 42)  # 42.0\n\n# isa\n42 isa Int       # true\n\"hi\" isa String  # true",
    "PHP": "// Type casting\n$n = (int)'42';       // 42\n$f = (float)'3.14';   // 3.14\n$s = (string)42;      // '42'\n$b = (bool)1;         // true\n$a = (array)'hello';  // ['hello']\n$o = (object)['a'=>1];  // stdClass\n\n// Functions\nintval('42');    // 42\nfloatval('3.14');  // 3.14\nstrval(42);     // '42'\n\n// Type checking\nis_int(42);      // true\nis_string('hi'); // true\ngettype(42);     // 'integer'",
    "Scala": "// asInstanceOf (unsafe cast)\nval x: Any = \"hello\"\nval s = x.asInstanceOf[String]\n\n// isInstanceOf\nif (x.isInstanceOf[String]) println(x.asInstanceOf[String])\n\n// Pattern matching (safe)\nx match {\n  case s: String => println(s.toUpperCase)\n  case n: Int => println(n * 2)\n}\n\n// Conversions\n42.toString  // \"42\"\n\"42\".toInt   // 42\n42.toDouble  // 42.0",
    "Clojure": ";; Coercion\n(int 42.7)       ;; 42\n(double 42)      ;; 42.0\n(str 42)         ;; \"42\"\n(Integer/parseInt \"42\")  ;; 42\n\n;; Type checking\n(instance? String \"hi\")  ;; true\n(number? 42)     ;; true\n(string? \"hi\")   ;; true",
    "Nim": "# Type conversion\nlet x = int(42.7)      # 42\nlet f = float(42)      # 42.0\nlet s = $42            # \"42\"\nlet n = parseInt(\"42\") # 42\n\n# Type checking\nwhen x is int: echo \"integer\"",
    "Lua": "-- tonumber / tostring\ntonumber('42')    -- 42\ntonumber('3.14')  -- 3.14\ntostring(42)      -- '42'\n\n-- Type checking\ntype(42)       -- 'number'\ntype('hi')     -- 'string'\ntype(true)     -- 'boolean'\n\n-- Implicit coercion\n'5' + 3   -- 8 (string to number)\n5 .. '!'  -- '5!' (number to string)",
    "Perl": "# Perl auto-converts between strings and numbers\nmy $n = '42' + 0;    # 42 (number)\nmy $s = 42 . '';     # '42' (string)\n\n# Explicit\nmy $int = int(42.7);   # 42\nsprintf('%d', 42.7);   # '42'\n\n# ref() for type\nref([])     # 'ARRAY'\nref({})     # 'HASH'\nref(\\42)    # 'SCALAR'",
    "R": "# Type conversion\nas.integer(42.7)    # 42\nas.double(42L)      # 42\nas.character(42)    # '42'\nas.numeric('42')    # 42\nas.logical(0)       # FALSE\n\n# Type checking\nis.numeric(42)      # TRUE\nis.character('hi')  # TRUE\nclass(42)           # 'numeric'\ntypeof(42L)         # 'integer'",
    "Erlang": "%% Type conversions\nlist_to_integer(\"42\").  %% 42\ninteger_to_list(42).    %% \"42\"\nfloat_to_list(3.14).   %% \"3.14\"\nlist_to_atom(\"hello\"). %% hello\natom_to_list(hello).   %% \"hello\"\n\n%% Type checking\nis_integer(42).   %% true\nis_list(\"hi\").    %% true\nis_atom(ok).      %% true",
    "OCaml": "(* Explicit conversions *)\nint_of_float 42.7  (* 42 *)\nfloat_of_int 42    (* 42.0 *)\nstring_of_int 42   (* \"42\" *)\nint_of_string \"42\" (* 42 *)\n\n(* Printf for formatting *)\nPrintf.sprintf \"%d\" 42  (* \"42\" *)",
    "F#": "// Explicit conversions\nint 42.7       // 42\nfloat 42       // 42.0\nstring 42      // \"42\"\nint \"42\"       // 42 (throws if invalid)\n\n// TryParse\nmatch System.Int32.TryParse(\"42\") with\n| true, n -> printfn \"%d\" n\n| false, _ -> printfn \"Invalid\"\n\n// :?> (downcast)\nlet obj: obj = upcast \"hello\"\nlet s = obj :?> string",
    "Zig": "// @intCast, @floatCast\nconst x: i32 = 42;\nconst y: i64 = @intCast(x);\nconst f: f64 = @floatToInt(f32, 42.0);\n\n// @intToFloat\nconst d: f64 = @floatFromInt(x);\n\n// @truncate\nconst byte: u8 = @truncate(@as(u16, 256));  // 0",
    "Racket": ";; Conversions\n(number->string 42)    ;; \"42\"\n(string->number \"42\")  ;; 42\n(integer->char 65)     ;; #\\A\n(char->integer #\\A)    ;; 65\n(list->vector '(1 2))  ;; #(1 2)\n(vector->list #(1 2))  ;; '(1 2)\n\n;; Type predicates\n(number? 42)    ;; true\n(string? \"hi\")  ;; true\n(pair? '(1))    ;; true",
    "D": "// cast\nauto x = cast(int)42.7;  // 42\nauto s = to!string(42);  // \"42\"\nauto n = to!int(\"42\");   // 42\n\n// safe casts\nauto d = cast(Derived)base;  // null if not Derived\n\n// Type checking\ntypeid(x) == typeid(int)",
    "Crystal": "42.to_s        # \"42\"\n42.to_f        # 42.0\n\"42\".to_i      # 42\n\"3.14\".to_f    # 3.14\n\n# as (cast)\nobj.as(String)   # Raises if not String\nobj.as?(String)  # nil if not String\n\n# is_a?\nobj.is_a?(String)  # true/false",
}


def get_expanded_v10_rosetta():
    """Return all v10 expanded handcrafted entries."""
    entries = []
    idx = 100000
    for concept, lang_codes in EXPANDED_V10.items():
        cn = concept.replace('_', ' ').title()
        for lang, code in lang_codes.items():
            idx += 1
            entries.append({
                "id": f"rosetta_v10_{idx}",
                "concept": concept,
                "concept_name": cn,
                "language": lang,
                "code": code,
                "category": "rosetta_stone",
                "has_code": True,
                "code_lines": len(code.split('\n')),
                "source": "handcrafted",
            })
    return entries
