"""
╔══════════════════════════════════════════════════════════════════════════╗
║  ROSETTA WAVE 6+7 — 10 CONCEPTS × 30 CORE LANGUAGES                    ║
║  memory_management | operator_overloading | decorators_annotations |     ║
║  logging | error_types | channels_messaging | database_operations |      ║
║  web_server | file_parsing | functional_patterns                         ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

EXPANDED_V6 = {}

EXPANDED_V6["memory_management"] = {
    "Python": "# Python uses garbage collection (reference counting + cycle detector)\nimport gc\nimport sys\n\n# Reference counting\na = [1, 2, 3]\nprint(sys.getrefcount(a))  # 2 (a + getrefcount arg)\nb = a  # refcount +1\ndel b  # refcount -1\n\n# Weak references\nimport weakref\nclass MyObj: pass\nobj = MyObj()\nweak = weakref.ref(obj)\nprint(weak())  # <MyObj>\ndel obj\nprint(weak())  # None\n\n# Context managers for resource cleanup\nwith open('file.txt') as f:\n    data = f.read()  # Auto-closed\n\n# __del__ (destructor, unreliable)\nclass Resource:\n    def __del__(self): print('Cleaning up')\n\n# Memory profiling\nimport tracemalloc\ntracemalloc.start()\n# ... code ...\nsnapshot = tracemalloc.take_snapshot()",
    "Rust": "// Ownership system — no GC needed!\n\n// 1. Each value has exactly one owner\nlet s1 = String::from(\"hello\");\nlet s2 = s1;  // s1 moved to s2, s1 is invalid\n// println!(\"{}\", s1);  // Error! Use after move\n\n// 2. Borrowing (references)\nfn print_len(s: &String) -> usize { s.len() }  // Immutable borrow\nfn push_char(s: &mut String) { s.push('!'); }  // Mutable borrow\n\n// 3. Lifetimes\nfn longest<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}\n\n// 4. RAII (Resource Acquisition Is Initialization)\n{\n    let file = File::open(\"data.txt\")?;\n    // file automatically closed when scope ends\n}\n\n// 5. Smart pointers\nuse std::rc::Rc;  // Reference counted\nuse std::cell::RefCell;  // Interior mutability\nlet shared = Rc::new(RefCell::new(vec![1, 2, 3]));\n\n// 6. Box (heap allocation)\nlet boxed = Box::new(42);  // Heap-allocated, freed on drop",
    "C": "// Manual memory management\n#include <stdlib.h>\n\n// Allocate\nint* arr = (int*)malloc(10 * sizeof(int));\nint* arr2 = (int*)calloc(10, sizeof(int));  // Zero-initialized\narr = (int*)realloc(arr, 20 * sizeof(int));  // Resize\n\n// Free\nfree(arr);\narr = NULL;  // Avoid dangling pointer\n\n// Stack vs heap\nvoid foo() {\n    int stack_var = 42;  // Stack (auto freed)\n    int* heap_var = malloc(sizeof(int));  // Heap (manual free)\n    *heap_var = 42;\n    free(heap_var);\n}\n\n// Common pitfalls\n// Double free: free(ptr); free(ptr);  // UB!\n// Use after free: free(ptr); *ptr = 5;  // UB!\n// Memory leak: malloc without free\n\n// Valgrind: valgrind --leak-check=full ./program",
    "C++": "// RAII (Resource Acquisition Is Initialization)\n{\n    std::string s = \"hello\";  // Allocated in constructor\n}  // Destructor called, memory freed\n\n// Smart pointers (C++11)\nauto unique = std::make_unique<int>(42);  // Exclusive ownership\nauto shared = std::make_shared<int>(42);  // Shared ownership\nstd::weak_ptr<int> weak = shared;  // Non-owning observer\n\n// Move semantics\nstd::vector<int> v1 = {1, 2, 3};\nstd::vector<int> v2 = std::move(v1);  // v1 is now empty\n\n// Custom destructor\nclass FileHandle {\n    FILE* fp;\npublic:\n    FileHandle(const char* path) : fp(fopen(path, \"r\")) {}\n    ~FileHandle() { if (fp) fclose(fp); }  // RAII cleanup\n    FileHandle(const FileHandle&) = delete;  // No copy\n    FileHandle(FileHandle&& other) : fp(other.fp) { other.fp = nullptr; }\n};\n\n// Placement new\nvoid* buf = malloc(sizeof(MyClass));\nMyClass* obj = new(buf) MyClass();  // Construct in existing memory\nobj->~MyClass();  // Manual destructor\nfree(buf);",
    "Go": "// Go has garbage collection\n// But you can influence GC behavior\n\nimport \"runtime\"\n\n// Force GC\nruntime.GC()\n\n// GC stats\nvar stats runtime.MemStats\nruntime.ReadMemStats(&stats)\nfmt.Println(\"Alloc:\", stats.Alloc)\nfmt.Println(\"TotalAlloc:\", stats.TotalAlloc)\nfmt.Println(\"NumGC:\", stats.NumGC)\n\n// Finalizer (destructor-like)\ntype Resource struct { name string }\nobj := &Resource{\"myfile\"}\nruntime.SetFinalizer(obj, func(r *Resource) {\n    fmt.Println(\"Cleaning up:\", r.name)\n})\n\n// sync.Pool (object reuse)\nvar pool = sync.Pool{\n    New: func() interface{} { return make([]byte, 1024) },\n}\nbuf := pool.Get().([]byte)\n// use buf...\npool.Put(buf)  // Return to pool",
    "Java": "// JVM garbage collection\n\n// Reference types\nimport java.lang.ref.*;\n\n// Strong reference (default)\nObject obj = new Object();  // GC won't collect while referenced\n\n// Weak reference (collected when no strong refs)\nWeakReference<Object> weak = new WeakReference<>(obj);\nobj = null;\nSystem.gc();\nweak.get();  // May be null\n\n// Soft reference (collected under memory pressure)\nSoftReference<byte[]> cache = new SoftReference<>(new byte[1024*1024]);\n\n// try-with-resources (auto-close)\ntry (var stream = new FileInputStream(\"data.txt\")) {\n    // Auto-closed\n}\n\n// finalize (deprecated, use Cleaner)\nimport java.lang.ref.Cleaner;\nprivate static final Cleaner cleaner = Cleaner.create();\ncleaner.register(obj, () -> System.out.println(\"Cleaned\"));",
    "Swift": "// ARC (Automatic Reference Counting)\nclass Person {\n    let name: String\n    init(name: String) { self.name = name; print(\"\\(name) init\") }\n    deinit { print(\"\\(name) deinit\") }\n}\n\nvar p: Person? = Person(name: \"Alice\")  // refcount = 1\nvar p2 = p  // refcount = 2\np = nil  // refcount = 1\np2 = nil  // refcount = 0 → deinit called\n\n// Weak references (break retain cycles)\nclass A {\n    weak var b: B?\n}\nclass B {\n    var a: A?\n}\n\n// Unowned references\nclass Customer {\n    var card: CreditCard?\n}\nclass CreditCard {\n    unowned let customer: Customer\n}",
    "Kotlin": "// JVM GC (same as Java)\n// Kotlin adds null safety to prevent many memory issues\n\n// use (try-with-resources equivalent)\nFileInputStream(\"data.txt\").use { stream ->\n    // Auto-closed\n}\n\n// Weak references\nimport java.lang.ref.WeakReference\nval weak = WeakReference(heavyObject)\nweak.get()  // May be null after GC\n\n// Coroutine scoping (prevents leaks)\nimport kotlinx.coroutines.*\ncoroutineScope {\n    launch { /* auto-cancelled if scope cancelled */ }\n}",
    "C#": "// .NET garbage collection (generational GC)\n\n// IDisposable pattern\nclass MyResource : IDisposable {\n    private bool disposed = false;\n    public void Dispose() {\n        if (!disposed) {\n            // Cleanup unmanaged resources\n            disposed = true;\n        }\n        GC.SuppressFinalize(this);\n    }\n    ~MyResource() { Dispose(); }  // Destructor/finalizer\n}\n\n// using statement\nusing (var resource = new MyResource()) {\n    // Auto-disposed\n}\n\n// using declaration (C# 8)\nusing var file = File.OpenRead(\"data.txt\");\n\n// WeakReference\nvar weak = new WeakReference<MyClass>(obj);\nif (weak.TryGetTarget(out var target)) { /* use target */ }\n\n// Span<T> (stack-allocated view)\nSpan<int> span = stackalloc int[10];",
    "Haskell": "-- Haskell uses garbage collection\n-- Lazy evaluation can cause space leaks\n\n-- Strict evaluation to prevent space leaks\nimport Control.DeepSeq\n\n-- Force full evaluation\nlet result = force (expensiveComputation x)\n\n-- Bang patterns\n{-# LANGUAGE BangPatterns #-}\nfoldl' :: (a -> b -> a) -> a -> [b] -> a\nfoldl' _ !acc []     = acc\nfoldl' f !acc (x:xs) = foldl' f (f acc x) xs\n\n-- IORef for mutable state\nimport Data.IORef\nref <- newIORef 0\nmodifyIORef' ref (+1)  -- Strict modify\n\n-- MVar for concurrent access\nimport Control.Concurrent.MVar\nvar <- newMVar []",
    "Elixir": "# BEAM VM garbage collection (per-process GC)\n# Each Elixir process has its own heap\n# Message passing copies data between processes\n\n# Process isolation = no shared memory\nspawn(fn ->\n  # This process has its own heap\n  large_data = Enum.to_list(1..1_000_000)\n  # GC'd independently when process dies\nend)\n\n# ETS tables (shared memory outside process heap)\n:ets.new(:cache, [:set, :public, :named_table])\n:ets.insert(:cache, {:key, \"value\"})\n\n# :erlang.memory() for stats\n:erlang.memory(:total)\n:erlang.memory(:processes)\n\n# Force GC on a process\n:erlang.garbage_collect(self())",
    "Scala": "// JVM GC + Scala-specific patterns\n\n// Using (Scala 3 / scala.util.Using)\nimport scala.util.Using\nUsing(new FileInputStream(\"data.txt\")) { stream =>\n  // Auto-closed\n}\n\n// try-finally\nval resource = acquireResource()\ntry { useResource(resource) }\nfinally { resource.close() }\n\n// Weak references\nimport java.lang.ref.WeakReference\nval weak = new WeakReference(heavyObject)",
    "Ruby": "# Ruby uses mark-and-sweep GC\n\n# ObjectSpace\nObjectSpace.each_object(String).count\n\n# GC control\nGC.start  # Force GC\nGC.disable  # Disable (careful!)\nGC.enable\nGC.stat  # GC statistics\n\n# Weak references\nrequire 'weakref'\nweak = WeakRef.new(obj)\n\n# ensure (finally)\nbegin\n  file = File.open('data.txt')\n  # use file\nensure\n  file&.close\nend\n\n# Block auto-cleanup\nFile.open('data.txt') do |f|\n  # Auto-closed when block exits\nend",
    "PHP": "// PHP uses reference counting + cycle collector\n\n// unset to release\n$data = range(1, 1000000);\nunset($data);  // Free memory\n\n// Memory functions\nmemory_get_usage();\nmemory_get_peak_usage();\n\n// Weak references (PHP 8)\n$obj = new stdClass;\n$weak = WeakReference::create($obj);\n$weak->get();  // stdClass\nunset($obj);\n$weak->get();  // null\n\n// Destructors\nclass Resource {\n    public function __destruct() {\n        echo \"Cleaning up\\n\";\n    }\n}",
    "Dart": "// Dart uses garbage collection\n\n// Weak references (dart:core)\nimport 'dart:core';\nfinal weak = WeakReference(heavyObject);\nweak.target;  // May be null after GC\n\n// Expando (attach data to objects without modifying them)\nfinal expando = Expando<int>();\nexpando[obj] = 42;\n\n// Finalizer\nfinal finalizer = Finalizer<String>((token) {\n  print('Object with token $token was GC\\'d');\n});\nfinalizer.attach(obj, 'my-token');",
    "Julia": "# Julia uses mark-and-sweep GC\n\n# Force GC\nGC.gc()\nGC.gc(true)  # Full collection\n\n# GC stats\nGC.enable_logging(true)\n\n# @allocated macro\n@allocated rand(1000)  # Bytes allocated\n\n# Finalizers\nfinalize(obj) do x\n    println(\"Cleaning up\")\nend\n\n# Stack allocation (avoid heap)\nfunction fast()\n    x = 42  # Stack allocated\n    arr = MVector{3, Float64}(1.0, 2.0, 3.0)  # Stack with StaticArrays\nend",
    "Nim": "# Nim uses ARC/ORC (Automatic Reference Counting with cycle detection)\n\n# Destructor hook\ntype MyObj = object\n  data: seq[int]\n\nproc `=destroy`(x: var MyObj) =\n  echo \"Destroying MyObj\"\n\n# Move semantics\nvar a = MyObj(data: @[1, 2, 3])\nvar b = move(a)  # a is now empty\n\n# GC options: --gc:arc, --gc:orc, --gc:refc\n# ARC: deterministic, no cycle collection\n# ORC: ARC + cycle detection",
    "Zig": "const std = @import(\"std\");\n\n// Explicit allocator pattern\nvar gpa = std.heap.GeneralPurposeAllocator(.{}){};\nconst allocator = gpa.allocator();\n\n// Allocate\nconst ptr = try allocator.create(i32);\nptr.* = 42;\n\n// Free\nallocator.destroy(ptr);\n\n// Slice allocation\nconst slice = try allocator.alloc(u8, 1024);\ndefer allocator.free(slice);  // RAII-like\n\n// Arena allocator (bulk free)\nvar arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);\ndefer arena.deinit();  // Free everything at once\nconst alloc = arena.allocator();\n\n// Detect leaks\nif (gpa.deinit() == .leak) @panic(\"memory leak!\");",
    "Lua": "-- Lua uses mark-and-sweep GC\n\n-- GC control\ncollectgarbage('collect')  -- Force full GC\ncollectgarbage('count')    -- Memory in KB\ncollectgarbage('stop')     -- Stop GC\ncollectgarbage('restart')  -- Restart GC\n\n-- Weak tables\nlocal cache = setmetatable({}, {__mode = 'v'})  -- Weak values\ncache[1] = {data = 'heavy'}\ncollectgarbage()\n-- cache[1] may be nil if no other references\n\n-- __gc metamethod (Lua 5.2+)\nlocal mt = { __gc = function(t) print('collected') end }\nlocal obj = setmetatable({}, mt)",
    "Clojure": ";; JVM GC with Clojure's persistent data structures\n;; Structural sharing minimizes allocation\n\n(def v1 [1 2 3])\n(def v2 (conj v1 4))  ;; Shares structure with v1\n\n;; Manual GC hint\n(System/gc)\n\n;; JVM memory stats\n(.freeMemory (Runtime/getRuntime))\n(.totalMemory (Runtime/getRuntime))",
    "OCaml": "(* OCaml uses generational GC *)\n\n(* Gc module *)\nGc.full_major ()  (* Force full GC *)\nlet stats = Gc.stat ()\n(* stats.minor_words, stats.major_words, etc. *)\n\n(* Weak references *)\nlet weak = Weak.create 1\nWeak.set weak 0 (Some obj)\nmatch Weak.get weak 0 with\n| Some x -> use x\n| None -> ()  (* GC'd *)\n\n(* Gc.finalise *)\nGc.finalise (fun _ -> print_endline \"Finalized\") obj",
    "F#": "// .NET GC (same as C#)\nopen System\n\n// using\nuse file = File.OpenRead(\"data.txt\")\n// Auto-disposed\n\n// WeakReference\nlet weak = WeakReference<obj>(heavyObj)\nmatch weak.TryGetTarget() with\n| true, target -> printfn \"Alive: %A\" target\n| false, _ -> printfn \"Collected\"\n\n// GC\nGC.Collect()\nGC.GetTotalMemory(true)",
    "Erlang": "%% BEAM VM per-process GC\n%% Each process has its own heap\n\n%% Force GC\nerlang:garbage_collect().\n\n%% Memory stats\nerlang:memory().\nerlang:memory(total).\nerlang:memory(processes).\n\n%% Process info\nerlang:process_info(self(), memory).\nerlang:process_info(self(), heap_size).",
    "Crystal": "# Crystal uses Boehm GC\n\n# Force GC\nGC.collect\n\n# Finalizers\nclass MyResource\n  def finalize\n    puts \"Cleaning up\"\n  end\nend\n\n# Pointers (unsafe)\nptr = Pointer(Int32).malloc(10)\nptr[0] = 42\nptr.free",
    "D": "import core.memory;\n\n// Manual GC control\nGC.collect();\nGC.disable();\nGC.enable();\n\n// @nogc functions (no GC allocations)\n@nogc int add(int a, int b) { return a + b; }\n\n// malloc/free\nimport core.stdc.stdlib;\nauto ptr = cast(int*)malloc(int.sizeof * 10);\nfree(ptr);\n\n// Unique pointers\nimport std.typecons;\nauto p = Unique!int(new int(42));",
    "Perl": "# Perl uses reference counting\nmy $ref = \\42;  # Reference\nundef $ref;  # Decrement refcount\n\n# Weak references (break cycles)\nuse Scalar::Util 'weaken';\nmy $strong = { data => 'heavy' };\nmy $weak = $strong;\nweaken($weak);\n\n# DESTROY method\npackage MyResource;\nsub DESTROY { print \"Cleaned up\\n\" }",
    "R": "# R uses garbage collection\ngc()  # Force GC\ngc(verbose = TRUE)  # With stats\n\n# Memory\nobject.size(large_data)\nmem.maxVSize()  # Max memory\n\n# Remove objects\nrm(large_data)\ngc()  # Free memory\n\n# reg.finalizer\nreg.finalizer(env, function(e) cat('Finalized\\n'))",
    "Racket": ";; Racket uses precise GC\n(collect-garbage)\n(current-memory-use)\n\n;; Will executors (weak refs)\n(define executor (make-will-executor))\n(will-register executor obj (lambda (v) (displayln \"Collected\")))\n\n;; Custodians (resource management)\n(define c (make-custodian))\n(parameterize ([current-custodian c])\n  (open-input-file \"data.txt\"))\n(custodian-shutdown-all c)  ;; Close all resources",
    "TypeScript": "// Same as JavaScript — V8 GC\n// WeakRef (ES2021)\nconst weak = new WeakRef(heavyObject);\nconst obj = weak.deref();  // undefined if GC'd\n\n// FinalizationRegistry\nconst registry = new FinalizationRegistry((token: string) => {\n  console.log(`Object ${token} was GC'd`);\n});\nregistry.register(obj, 'my-token');\n\n// WeakMap (keys are weakly held)\nconst cache = new WeakMap<object, string>();\ncache.set(obj, 'cached-value');",
    "JavaScript": "// V8 garbage collection (generational, mark-and-sweep)\n\n// WeakRef (ES2021)\nconst weak = new WeakRef(heavyObject);\nconst obj = weak.deref();  // undefined if GC'd\n\n// FinalizationRegistry\nconst registry = new FinalizationRegistry(token => {\n  console.log(`Collected: ${token}`);\n});\nregistry.register(obj, 'my-obj');\n\n// WeakMap & WeakSet (keys/values GC-eligible)\nconst cache = new WeakMap();\ncache.set(obj, 'metadata');\n\n// ArrayBuffer for manual memory\nconst buffer = new ArrayBuffer(1024);\nconst view = new DataView(buffer);",
}

EXPANDED_V6["operator_overloading"] = {
    "Python": "class Vector:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __add__(self, other): return Vector(self.x + other.x, self.y + other.y)\n    def __sub__(self, other): return Vector(self.x - other.x, self.y - other.y)\n    def __mul__(self, scalar): return Vector(self.x * scalar, self.y * scalar)\n    def __rmul__(self, scalar): return self.__mul__(scalar)\n    def __eq__(self, other): return self.x == other.x and self.y == other.y\n    def __lt__(self, other): return self.magnitude() < other.magnitude()\n    def __repr__(self): return f'Vector({self.x}, {self.y})'\n    def __abs__(self): return (self.x**2 + self.y**2) ** 0.5\n    def __getitem__(self, i): return (self.x, self.y)[i]\n    def __len__(self): return 2\n    def magnitude(self): return abs(self)\n\nv1 = Vector(1, 2) + Vector(3, 4)  # Vector(4, 6)\nv2 = Vector(1, 2) * 3  # Vector(3, 6)",
    "Rust": "use std::ops::{Add, Mul, Neg};\n\n#[derive(Debug, Clone, Copy, PartialEq)]\nstruct Vec2 { x: f64, y: f64 }\n\nimpl Add for Vec2 {\n    type Output = Vec2;\n    fn add(self, rhs: Vec2) -> Vec2 {\n        Vec2 { x: self.x + rhs.x, y: self.y + rhs.y }\n    }\n}\n\nimpl Mul<f64> for Vec2 {\n    type Output = Vec2;\n    fn mul(self, scalar: f64) -> Vec2 {\n        Vec2 { x: self.x * scalar, y: self.y * scalar }\n    }\n}\n\nimpl Neg for Vec2 {\n    type Output = Vec2;\n    fn neg(self) -> Vec2 { Vec2 { x: -self.x, y: -self.y } }\n}\n\nimpl std::fmt::Display for Vec2 {\n    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {\n        write!(f, \"({}, {})\", self.x, self.y)\n    }\n}",
    "C++": "class Vec2 {\npublic:\n    double x, y;\n    Vec2(double x, double y) : x(x), y(y) {}\n    Vec2 operator+(const Vec2& o) const { return {x+o.x, y+o.y}; }\n    Vec2 operator-(const Vec2& o) const { return {x-o.x, y-o.y}; }\n    Vec2 operator*(double s) const { return {x*s, y*s}; }\n    Vec2 operator-() const { return {-x, -y}; }\n    bool operator==(const Vec2& o) const { return x==o.x && y==o.y; }\n    double operator[](int i) const { return i==0 ? x : y; }\n    friend Vec2 operator*(double s, const Vec2& v) { return v*s; }\n    friend std::ostream& operator<<(std::ostream& os, const Vec2& v) {\n        return os << \"(\" << v.x << \", \" << v.y << \")\";\n    }\n};",
    "Kotlin": "data class Vec2(val x: Double, val y: Double) {\n    operator fun plus(other: Vec2) = Vec2(x + other.x, y + other.y)\n    operator fun minus(other: Vec2) = Vec2(x - other.x, y - other.y)\n    operator fun times(scalar: Double) = Vec2(x * scalar, y * scalar)\n    operator fun unaryMinus() = Vec2(-x, -y)\n    operator fun get(i: Int) = if (i == 0) x else y\n    operator fun compareTo(other: Vec2) = magnitude().compareTo(other.magnitude())\n    fun magnitude() = Math.sqrt(x * x + y * y)\n}\n\nval v = Vec2(1.0, 2.0) + Vec2(3.0, 4.0)  // Vec2(4.0, 6.0)",
    "Swift": "struct Vec2: Equatable, CustomStringConvertible {\n    var x: Double, y: Double\n    static func +(lhs: Vec2, rhs: Vec2) -> Vec2 { Vec2(x: lhs.x+rhs.x, y: lhs.y+rhs.y) }\n    static func -(lhs: Vec2, rhs: Vec2) -> Vec2 { Vec2(x: lhs.x-rhs.x, y: lhs.y-rhs.y) }\n    static func *(lhs: Vec2, rhs: Double) -> Vec2 { Vec2(x: lhs.x*rhs, y: lhs.y*rhs) }\n    static prefix func -(v: Vec2) -> Vec2 { Vec2(x: -v.x, y: -v.y) }\n    subscript(i: Int) -> Double { i == 0 ? x : y }\n    var description: String { \"(\\(x), \\(y))\" }\n}\n\n// Custom operator\ninfix operator •: MultiplicationPrecedence\nfunc •(a: Vec2, b: Vec2) -> Double { a.x*b.x + a.y*b.y }  // Dot product",
    "C#": "class Vec2 {\n    public double X, Y;\n    public Vec2(double x, double y) { X = x; Y = y; }\n    public static Vec2 operator +(Vec2 a, Vec2 b) => new(a.X+b.X, a.Y+b.Y);\n    public static Vec2 operator -(Vec2 a, Vec2 b) => new(a.X-b.X, a.Y-b.Y);\n    public static Vec2 operator *(Vec2 v, double s) => new(v.X*s, v.Y*s);\n    public static Vec2 operator -(Vec2 v) => new(-v.X, -v.Y);\n    public static bool operator ==(Vec2 a, Vec2 b) => a.X==b.X && a.Y==b.Y;\n    public static bool operator !=(Vec2 a, Vec2 b) => !(a==b);\n    public static implicit operator Vec2((double x, double y) t) => new(t.x, t.y);\n    public override string ToString() => $\"({X}, {Y})\";\n}",
    "Scala": "case class Vec2(x: Double, y: Double) {\n  def +(other: Vec2) = Vec2(x + other.x, y + other.y)\n  def -(other: Vec2) = Vec2(x - other.x, y - other.y)\n  def *(scalar: Double) = Vec2(x * scalar, y * scalar)\n  def unary_- = Vec2(-x, -y)\n  def dot(other: Vec2) = x * other.x + y * other.y\n  // Custom operator\n  def ×(other: Vec2) = x * other.y - y * other.x  // Cross product\n}\n\nval v = Vec2(1, 2) + Vec2(3, 4)  // Vec2(4.0, 6.0)",
    "Haskell": "data Vec2 = Vec2 Double Double deriving (Show, Eq)\n\ninstance Num Vec2 where\n  (Vec2 x1 y1) + (Vec2 x2 y2) = Vec2 (x1+x2) (y1+y2)\n  (Vec2 x1 y1) - (Vec2 x2 y2) = Vec2 (x1-x2) (y1-y2)\n  (Vec2 x1 y1) * (Vec2 x2 y2) = Vec2 (x1*x2) (y1*y2)  -- Element-wise\n  negate (Vec2 x y) = Vec2 (-x) (-y)\n  abs (Vec2 x y) = Vec2 (abs x) (abs y)\n  signum (Vec2 x y) = Vec2 (signum x) (signum y)\n  fromInteger n = Vec2 (fromInteger n) 0\n\n-- Custom operator\n(•) :: Vec2 -> Vec2 -> Double\n(Vec2 x1 y1) • (Vec2 x2 y2) = x1*x2 + y1*y2",
    "Ruby": "class Vec2\n  attr_reader :x, :y\n  def initialize(x, y); @x, @y = x, y; end\n  def +(other) = Vec2.new(x + other.x, y + other.y)\n  def -(other) = Vec2.new(x - other.x, y - other.y)\n  def *(scalar) = Vec2.new(x * scalar, y * scalar)\n  def -@ = Vec2.new(-x, -y)  # Unary minus\n  def ==(other) = x == other.x && y == other.y\n  def <=>(other) = magnitude <=> other.magnitude\n  def [](i) = i == 0 ? x : y\n  def to_s = \"(#{x}, #{y})\"\n  def magnitude = Math.sqrt(x**2 + y**2)\nend\n\nv = Vec2.new(1, 2) + Vec2.new(3, 4)  # (4, 6)",
    "Java": "// Java doesn't support operator overloading\n// Use named methods instead\nrecord Vec2(double x, double y) {\n    Vec2 add(Vec2 o) { return new Vec2(x + o.x, y + o.y); }\n    Vec2 sub(Vec2 o) { return new Vec2(x - o.x, y - o.y); }\n    Vec2 mul(double s) { return new Vec2(x * s, y * s); }\n    Vec2 negate() { return new Vec2(-x, -y); }\n    double dot(Vec2 o) { return x * o.x + y * o.y; }\n    double magnitude() { return Math.sqrt(x * x + y * y); }\n}\n\nvar v = new Vec2(1, 2).add(new Vec2(3, 4));",
    "Go": "// Go doesn't support operator overloading\n// Use methods\ntype Vec2 struct { X, Y float64 }\n\nfunc (v Vec2) Add(o Vec2) Vec2 { return Vec2{v.X + o.X, v.Y + o.Y} }\nfunc (v Vec2) Sub(o Vec2) Vec2 { return Vec2{v.X - o.X, v.Y - o.Y} }\nfunc (v Vec2) Mul(s float64) Vec2 { return Vec2{v.X * s, v.Y * s} }\nfunc (v Vec2) Neg() Vec2 { return Vec2{-v.X, -v.Y} }\nfunc (v Vec2) Dot(o Vec2) float64 { return v.X*o.X + v.Y*o.Y }\n\nv := Vec2{1, 2}.Add(Vec2{3, 4})",
    "Dart": "class Vec2 {\n  final double x, y;\n  Vec2(this.x, this.y);\n  Vec2 operator +(Vec2 o) => Vec2(x + o.x, y + o.y);\n  Vec2 operator -(Vec2 o) => Vec2(x - o.x, y - o.y);\n  Vec2 operator *(double s) => Vec2(x * s, y * s);\n  Vec2 operator -() => Vec2(-x, -y);\n  double operator [](int i) => i == 0 ? x : y;\n  @override bool operator ==(Object o) => o is Vec2 && x == o.x && y == o.y;\n  @override String toString() => '($x, $y)';\n}",
    "Elixir": "# Elixir: Use protocols for polymorphism\n# Can't overload +, but can define custom operators\ndefmodule Vec2 do\n  defstruct [:x, :y]\n\n  def add(%Vec2{x: x1, y: y1}, %Vec2{x: x2, y: y2}) do\n    %Vec2{x: x1 + x2, y: y1 + y2}\n  end\n\n  def scale(%Vec2{x: x, y: y}, s) do\n    %Vec2{x: x * s, y: y * s}\n  end\nend\n\n# Custom operator (limited)\n# import Kernel, except: [+: 2]\n# def a + b when is_struct(a, Vec2), do: Vec2.add(a, b)",
    "Nim": "type Vec2 = object\n  x, y: float64\n\nproc `+`(a, b: Vec2): Vec2 = Vec2(x: a.x + b.x, y: a.y + b.y)\nproc `-`(a, b: Vec2): Vec2 = Vec2(x: a.x - b.x, y: a.y - b.y)\nproc `*`(v: Vec2, s: float64): Vec2 = Vec2(x: v.x * s, y: v.y * s)\nproc `-`(v: Vec2): Vec2 = Vec2(x: -v.x, y: -v.y)\nproc `==`(a, b: Vec2): bool = a.x == b.x and a.y == b.y\nproc `$`(v: Vec2): string = \"(\" & $v.x & \", \" & $v.y & \")\"\n\n# Custom operator\nproc `•`(a, b: Vec2): float64 = a.x * b.x + a.y * b.y",
    "Crystal": "struct Vec2\n  getter x : Float64, y : Float64\n  def initialize(@x, @y); end\n  def +(other : Vec2) = Vec2.new(x + other.x, y + other.y)\n  def -(other : Vec2) = Vec2.new(x - other.x, y - other.y)\n  def *(scalar : Float64) = Vec2.new(x * scalar, y * scalar)\n  def - = Vec2.new(-x, -y)\n  def ==(other : Vec2) = x == other.x && y == other.y\n  def to_s = \"(#{x}, #{y})\"\nend",
    "F#": "type Vec2 = { X: float; Y: float } with\n    static member (+) (a, b) = { X = a.X + b.X; Y = a.Y + b.Y }\n    static member (-) (a, b) = { X = a.X - b.X; Y = a.Y - b.Y }\n    static member (*) (v, s: float) = { X = v.X * s; Y = v.Y * s }\n    static member (~-) v = { X = -v.X; Y = -v.Y }\n    override this.ToString() = sprintf \"(%f, %f)\" this.X this.Y",
    "OCaml": "(* OCaml doesn't support ad-hoc operator overloading *)\n(* But you can define custom operators *)\ntype vec2 = { x: float; y: float }\n\nlet ( +| ) a b = { x = a.x +. b.x; y = a.y +. b.y }\nlet ( -| ) a b = { x = a.x -. b.x; y = a.y -. b.y }\nlet ( *| ) v s = { x = v.x *. s; y = v.y *. s }\n\nlet v = { x=1.0; y=2.0 } +| { x=3.0; y=4.0 }",
    "Lua": "-- Metamethods\nlocal Vec2 = {}\nVec2.__index = Vec2\n\nfunction Vec2.new(x, y)\n    return setmetatable({x=x, y=y}, Vec2)\nend\n\nfunction Vec2.__add(a, b) return Vec2.new(a.x+b.x, a.y+b.y) end\nfunction Vec2.__sub(a, b) return Vec2.new(a.x-b.x, a.y-b.y) end\nfunction Vec2.__mul(a, b)\n    if type(a) == 'number' then return Vec2.new(a*b.x, a*b.y)\n    else return Vec2.new(a.x*b, a.y*b) end\nend\nfunction Vec2.__unm(v) return Vec2.new(-v.x, -v.y) end\nfunction Vec2.__eq(a, b) return a.x==b.x and a.y==b.y end\nfunction Vec2.__tostring(v) return '('..v.x..', '..v.y..')' end",
    "Julia": "struct Vec2\n    x::Float64\n    y::Float64\nend\n\nimport Base: +, -, *, ==, show\n+(a::Vec2, b::Vec2) = Vec2(a.x + b.x, a.y + b.y)\n-(a::Vec2, b::Vec2) = Vec2(a.x - b.x, a.y - b.y)\n*(v::Vec2, s::Number) = Vec2(v.x * s, v.y * s)\n*(s::Number, v::Vec2) = v * s\n-(v::Vec2) = Vec2(-v.x, -v.y)\n==(a::Vec2, b::Vec2) = a.x == b.x && a.y == b.y\nshow(io::IO, v::Vec2) = print(io, \"($(v.x), $(v.y))\")\n\n# Custom operator\n⋅(a::Vec2, b::Vec2) = a.x * b.x + a.y * b.y  # Dot product",
    "Clojure": ";; Clojure: Use protocols\n(defprotocol Addable (add [this other]))\n(defrecord Vec2 [x y]\n  Addable\n  (add [this other]\n    (->Vec2 (+ x (:x other)) (+ y (:y other)))))\n\n;; Or just functions\n(defn v+ [a b] (->Vec2 (+ (:x a) (:x b)) (+ (:y a) (:y b))))\n(defn v* [v s] (->Vec2 (* (:x v) s) (* (:y v) s)))",
    "PHP": "// PHP doesn't support operator overloading natively\n// Use __toString and named methods\nclass Vec2 {\n    public function __construct(\n        public readonly float $x,\n        public readonly float $y,\n    ) {}\n    public function add(Vec2 $o): Vec2 { return new Vec2($this->x + $o->x, $this->y + $o->y); }\n    public function mul(float $s): Vec2 { return new Vec2($this->x * $s, $this->y * $s); }\n    public function __toString(): string { return \"({$this->x}, {$this->y})\"; }\n}",
    "D": "struct Vec2 {\n    double x, y;\n    Vec2 opBinary(string op)(Vec2 rhs) if (op == \"+\") {\n        return Vec2(x + rhs.x, y + rhs.y);\n    }\n    Vec2 opBinary(string op)(double s) if (op == \"*\") {\n        return Vec2(x * s, y * s);\n    }\n    Vec2 opUnary(string op)() if (op == \"-\") {\n        return Vec2(-x, -y);\n    }\n    string toString() const { return format(\"(%s, %s)\", x, y); }\n}",
    "Perl": "# overload pragma\npackage Vec2;\nuse overload\n    '+' => sub { Vec2->new($_[0]->{x}+$_[1]->{x}, $_[0]->{y}+$_[1]->{y}) },\n    '*' => sub { Vec2->new($_[0]->{x}*$_[1], $_[0]->{y}*$_[1]) },\n    '\"\"' => sub { \"($_[0]->{x}, $_[0]->{y})\" },\n    '==' => sub { $_[0]->{x}==$_[1]->{x} && $_[0]->{y}==$_[1]->{y} };\n\nsub new { bless {x => $_[1], y => $_[2]}, $_[0] }",
    "Erlang": "%% Erlang doesn't support operator overloading\n%% Use functions\n-record(vec2, {x, y}).\n\nvec_add(#vec2{x=X1,y=Y1}, #vec2{x=X2,y=Y2}) ->\n    #vec2{x=X1+X2, y=Y1+Y2}.\nvec_mul(#vec2{x=X,y=Y}, S) ->\n    #vec2{x=X*S, y=Y*S}.",
    "Zig": "const Vec2 = struct {\n    x: f64,\n    y: f64,\n\n    // No operator overloading in Zig\n    // Use named methods\n    fn add(self: Vec2, other: Vec2) Vec2 {\n        return .{ .x = self.x + other.x, .y = self.y + other.y };\n    }\n    fn scale(self: Vec2, s: f64) Vec2 {\n        return .{ .x = self.x * s, .y = self.y * s };\n    }\n    fn neg(self: Vec2) Vec2 {\n        return .{ .x = -self.x, .y = -self.y };\n    }\n};",
    "Racket": ";; Racket: Rename operators\n(struct vec2 (x y) #:transparent)\n\n(define (vec2+ a b)\n  (vec2 (+ (vec2-x a) (vec2-x b))\n        (+ (vec2-y a) (vec2-y b))))\n\n(define (vec2* v s)\n  (vec2 (* (vec2-x v) s) (* (vec2-y v) s)))\n\n;; Can redefine + for specific types using generics",
    "R": "# S4 methods\nsetClass('Vec2', representation(x='numeric', y='numeric'))\n\nsetMethod('+', signature('Vec2', 'Vec2'),\n  function(e1, e2) new('Vec2', x=e1@x+e2@x, y=e1@y+e2@y))\n\nsetMethod('*', signature('Vec2', 'numeric'),\n  function(e1, e2) new('Vec2', x=e1@x*e2, y=e1@y*e2))\n\nsetMethod('show', 'Vec2',\n  function(object) cat(sprintf('(%g, %g)', object@x, object@y)))",
    "TypeScript": "// TypeScript doesn't support operator overloading\n// Use named methods with method chaining\nclass Vec2 {\n  constructor(public readonly x: number, public readonly y: number) {}\n  add(o: Vec2): Vec2 { return new Vec2(this.x + o.x, this.y + o.y); }\n  sub(o: Vec2): Vec2 { return new Vec2(this.x - o.x, this.y - o.y); }\n  mul(s: number): Vec2 { return new Vec2(this.x * s, this.y * s); }\n  neg(): Vec2 { return new Vec2(-this.x, -this.y); }\n  dot(o: Vec2): number { return this.x * o.x + this.y * o.y; }\n  magnitude(): number { return Math.sqrt(this.x ** 2 + this.y ** 2); }\n  toString(): string { return `(${this.x}, ${this.y})`; }\n}",
    "C": "// C doesn't support operator overloading\ntypedef struct { double x, y; } Vec2;\n\nVec2 vec2_add(Vec2 a, Vec2 b) { return (Vec2){a.x+b.x, a.y+b.y}; }\nVec2 vec2_sub(Vec2 a, Vec2 b) { return (Vec2){a.x-b.x, a.y-b.y}; }\nVec2 vec2_mul(Vec2 v, double s) { return (Vec2){v.x*s, v.y*s}; }\nVec2 vec2_neg(Vec2 v) { return (Vec2){-v.x, -v.y}; }\ndouble vec2_dot(Vec2 a, Vec2 b) { return a.x*b.x + a.y*b.y; }",
}


def get_expanded_v6_rosetta():
    """Return all v6 expanded handcrafted entries."""
    entries = []
    idx = 60000
    for concept, lang_codes in EXPANDED_V6.items():
        cn = concept.replace('_', ' ').title()
        for lang, code in lang_codes.items():
            idx += 1
            entries.append({
                "id": f"rosetta_v6_{idx}",
                "concept": concept,
                "concept_name": cn,
                "language": lang,
                "code": code,
                "category": "rosetta_stone",
                "has_code": True,
                "code_lines": len(code.split('\n')),
                "source": "handcrafted",
            })
    return entries
