/**
 * routeRegistry — central registry of every navigable route in the app.
 *
 * Used by /audit-routes for validation and by deep-link helpers. Routes
 * are categorised the same way as /menu so the UX stays consistent.
 */
export interface RouteEntry {
  path: string;
  title: string;
  category: 'core' | 'learn' | 'build' | 'code' | 'ai' | 'tools' | 'progress' | 'settings' | 'system';
  heavy?: boolean;
}

export const ROUTE_REGISTRY: ReadonlyArray<RouteEntry> = [
  { path: '/', title: 'Entry (redirect)', category: 'core' },
  { path: '/welcome', title: 'Welcome / Starfall', category: 'core' },
  { path: '/hub', title: 'Ultimate Hub', category: 'core', heavy: true },
  { path: '/menu', title: 'Menu', category: 'core' },
  { path: '/workspaces', title: 'Unified Workspaces', category: 'core' },
  { path: '/safe-mode', title: 'Safe Mode', category: 'system' },
  { path: '/audit-routes', title: 'Audit Routes', category: 'system' },
  { path: '/perf', title: 'Performance', category: 'system' },
  { path: '/telemetry', title: 'Telemetry', category: 'system' },
  { path: '/migration-map', title: 'Legacy Migration Map', category: 'system' },

  { path: '/my-classes', title: 'My Classes', category: 'learn' },
  { path: '/class-week', title: 'Class Week', category: 'learn' },
  { path: '/readingLibrary', title: 'Reading Library', category: 'learn' },
  { path: '/reading-corner', title: 'Reading Corner', category: 'learn' },
  { path: '/mega-academy', title: 'Mega Academy', category: 'learn' },
  { path: '/cs-academy', title: 'CS Academy', category: 'learn' },
  { path: '/math-academy', title: 'Math Academy', category: 'learn' },
  { path: '/math-academy-full', title: 'Math Academy (Full)', category: 'learn' },
  { path: '/physics-academy', title: 'Physics Academy', category: 'learn' },
  { path: '/language-academy', title: 'Language Academy', category: 'learn' },
  { path: '/language-track', title: 'Language Track', category: 'learn' },
  { path: '/masterclass', title: 'Masterclass', category: 'learn' },
  { path: '/study-paths', title: 'Study Paths', category: 'learn' },
  { path: '/education', title: 'Education Hub', category: 'learn' },
  { path: '/learning-hub', title: 'Learning Hub', category: 'learn' },
  { path: '/immersive-learning', title: 'Immersive Learning', category: 'learn' },
  { path: '/immersive-tutor', title: 'Immersive Tutor', category: 'learn' },
  { path: '/knowledge-databases', title: 'Knowledge DBs', category: 'learn' },
  { path: '/curriculum', title: 'Curriculum', category: 'learn' },
  { path: '/flashcards', title: 'Flashcards', category: 'learn' },
  { path: '/interactive-quizzes', title: 'Interactive Quizzes', category: 'learn' },
  { path: '/daily-challenges', title: 'Daily Challenges', category: 'learn' },
  { path: '/challenges', title: 'Challenge Arena', category: 'learn' },
  { path: '/rosetta', title: 'Rosetta', category: 'learn' },
  { path: '/rosetta-playground', title: 'Rosetta Playground', category: 'learn' },
  { path: '/bible', title: 'Code Bible', category: 'learn' },

  { path: '/galaxy', title: 'Galaxy Studio', category: 'build', heavy: true },
  { path: '/ai-game-generator', title: 'AI Game Generator', category: 'build' },
  { path: '/game-factory', title: 'Game Factory', category: 'build' },
  { path: '/code-to-app', title: 'Code → App', category: 'build' },
  { path: '/playground', title: 'Code Playground', category: 'build' },
  { path: '/assets', title: 'Asset Pipeline', category: 'build' },
  { path: '/music', title: 'Music Pipeline', category: 'build' },
  { path: '/imagine', title: 'Imagine', category: 'build' },
  { path: '/ai-pipeline', title: 'AI Pipeline', category: 'build' },
  { path: '/hybrid-pipeline', title: 'Hybrid Pipeline', category: 'build' },
  { path: '/agents', title: 'Multi-Agent', category: 'build' },
  { path: '/multi-agent', title: 'Multi-Agent (alt)', category: 'build' },
  { path: '/gallery', title: 'Build Gallery', category: 'build' },
  { path: '/my-builds', title: 'My Builds', category: 'build' },
  { path: '/agentCodex', title: 'Agent Codex', category: 'build' },
  { path: '/build-hub', title: 'Build · Code · AI Hub', category: 'build' },

  { path: '/compiler', title: 'Compiler Suite', category: 'code' },
  { path: '/debugger', title: 'Debugger', category: 'code' },
  { path: '/intelligence', title: 'Code Intelligence', category: 'code' },
  { path: '/bugfix-library', title: 'Bugfix Library', category: 'code' },
  { path: '/reference', title: 'Reference Hub', category: 'code' },
  { path: '/collab', title: 'Live Collab', category: 'code' },
  { path: '/collaboration', title: 'Collaboration Hub', category: 'code' },
  { path: '/group-chat', title: 'Group Chat', category: 'code' },
  { path: '/vault', title: 'Vault', category: 'code' },
  { path: '/lang-recommend', title: 'Language Recommend', category: 'code' },

  { path: '/jeeves', title: 'Jeeves', category: 'ai' },
  { path: '/jeeves-hub', title: 'Jeeves Hub', category: 'ai' },
  { path: '/jeeves-control', title: 'Jeeves Operator', category: 'ai' },
  { path: '/market-intelligence', title: 'Market Intelligence', category: 'ai' },
  { path: '/jeeves-eq', title: 'Jeeves EQ', category: 'ai' },
  { path: '/jeeves-level', title: 'Jeeves Level', category: 'ai' },
  { path: '/jeeves-audio-test', title: 'Jeeves Audio', category: 'ai' },
  { path: '/ai-suggestions', title: 'AI Suggestions', category: 'ai' },
  { path: '/ai-interactions', title: 'AI Interactions', category: 'ai' },
  { path: '/sota', title: 'SOTA Models', category: 'ai' },
  { path: '/sota-extended', title: 'SOTA Extended', category: 'ai' },

  { path: '/apk-inspector', title: 'APK Inspector', category: 'tools' },
  { path: '/tools-arena', title: 'Tools Arena', category: 'tools' },
  { path: '/scheduler', title: 'Scheduler', category: 'tools' },
  { path: '/pomodoro', title: 'Pomodoro', category: 'tools' },
  { path: '/search', title: 'Search', category: 'tools' },
  { path: '/notes', title: 'Sticky Notes', category: 'tools' },
  { path: '/advanced', title: 'Advanced Features', category: 'tools' },
  { path: '/offline-sync', title: 'Offline Sync', category: 'tools' },
  { path: '/thermal', title: 'Thermal Monitor', category: 'tools' },
  { path: '/workforce', title: 'Work OS', category: 'tools' },

  { path: '/dashboard', title: 'Dashboard', category: 'progress' },
  { path: '/profile', title: 'Profile', category: 'progress' },
  { path: '/progress', title: 'My Progress', category: 'progress' },
  { path: '/achievements', title: 'Achievements', category: 'progress' },
  { path: '/gamification', title: 'Gamification', category: 'progress' },
  { path: '/leaderboard', title: 'Leaderboard', category: 'progress' },
  { path: '/certificate', title: 'Certificate', category: 'progress' },
  { path: '/wealth', title: 'Wealth & Progress', category: 'progress' },

  { path: '/settings', title: 'All Settings', category: 'settings' },
  { path: '/settings/academy', title: 'Academy Settings', category: 'settings' },
  { path: '/settings/api', title: 'API Settings', category: 'settings' },
  { path: '/settings/coding', title: 'Coding Settings', category: 'settings' },
  { path: '/settings/galaxy-studio', title: 'Galaxy Studio Settings', category: 'settings' },
  { path: '/settings/haptics', title: 'Haptics Intensity', category: 'settings' },
  { path: '/settings/jeeves', title: 'Jeeves Settings', category: 'settings' },
  { path: '/settings/offline', title: 'Offline Settings', category: 'settings' },
  { path: '/settings/feature-flags', title: 'Feature Flags', category: 'settings' },

  // Filesystem-discovered routes kept in the same canonical registry so
  // route coverage fails closed when screens are added or removed.
  { path: '/agent-memory', title: 'Agent Memory', category: 'ai' },
  { path: '/agent-review', title: 'Agent Review', category: 'ai' },
  { path: '/ai-router', title: 'AI Router', category: 'ai' },
  { path: '/anti-cheat', title: 'Anti Cheat', category: 'system' },
  { path: '/apk-build', title: 'APK Build', category: 'build' },
  { path: '/asset-genesis', title: 'Asset Genesis', category: 'build' },
  { path: '/boot-log', title: 'Boot Log', category: 'system' },
  { path: '/camera-director', title: 'Camera Director', category: 'build' },
  { path: '/canon-graph', title: 'Canon Graph', category: 'build' },
  { path: '/capabilities', title: 'Capabilities', category: 'system' },
  { path: '/capability', title: 'Capability', category: 'system' },
  { path: '/champions', title: 'Champions', category: 'progress' },
  { path: '/collections', title: 'Collections', category: 'progress' },
  { path: '/command-center', title: 'Command Center', category: 'system' },
  { path: '/compose-scene', title: 'Compose Scene', category: 'build' },
  { path: '/construct-forge', title: 'Construct Forge', category: 'build' },
  { path: '/control-plane', title: 'Control Plane', category: 'system' },
  { path: '/cover-studio', title: 'Cover Studio', category: 'build' },
  { path: '/create-mode', title: 'Create Mode', category: 'build' },
  { path: '/creator', title: 'Creator', category: 'build' },
  { path: '/design-spec', title: 'Design Spec', category: 'build' },
  { path: '/discourse', title: 'Discourse', category: 'tools' },
  { path: '/discover', title: 'Discover', category: 'core' },
  { path: '/edit-gamefiles', title: 'Edit Game Files', category: 'code' },
  { path: '/factions', title: 'Factions', category: 'build' },
  { path: '/feature-flags', title: 'Feature Flags', category: 'settings' },
  { path: '/forge-hub', title: 'Forge Hub', category: 'build' },
  { path: '/forge', title: 'Forge', category: 'build' },
  { path: '/game-kb', title: 'Game Knowledge Base', category: 'build' },
  { path: '/gameforge-studio', title: 'GameForge Studio', category: 'build', heavy: true },
  { path: '/gate/[stage]', title: 'Stage Gate', category: 'build' },
  { path: '/groupchat', title: 'Group Chat', category: 'code' },
  { path: '/health', title: 'Health', category: 'system' },
  { path: '/item-foundry', title: 'Item Foundry', category: 'build' },
  { path: '/jeeves-chat', title: 'Jeeves Chat', category: 'ai' },
  { path: '/jury-room', title: 'Jury Room', category: 'ai' },
  { path: '/liveops', title: 'Live Ops', category: 'system' },
  { path: '/marketplace', title: 'Marketplace', category: 'core' },
  { path: '/media-studio', title: 'Media Studio', category: 'build' },
  { path: '/mission-control', title: 'Mission Control', category: 'system' },
  { path: '/multiplayer', title: 'Multiplayer', category: 'build' },
  { path: '/operation', title: 'Operation', category: 'system' },
  { path: '/ops', title: 'Operations', category: 'system' },
  { path: '/organism', title: 'Organism', category: 'build' },
  { path: '/physics-studio', title: 'Physics Studio', category: 'build' },
  { path: '/playable', title: 'Playable', category: 'build' },
  { path: '/polish', title: 'Polish', category: 'build' },
  { path: '/product', title: 'Product', category: 'core' },
  { path: '/quality-control', title: 'Quality Control', category: 'build' },
  { path: '/refine', title: 'Refine', category: 'build' },
  { path: '/render-compare', title: 'Render Compare', category: 'build' },
  { path: '/safety', title: 'Safety', category: 'system' },
  { path: '/scorecard', title: 'Scorecard', category: 'progress' },
  { path: '/settings/appearance', title: 'Appearance Settings', category: 'settings' },
  { path: '/settings/jeeves-voice', title: 'Jeeves Voice Settings', category: 'settings' },
  { path: '/snowball', title: 'Snowball', category: 'build' },
  { path: '/stages', title: 'Stages', category: 'build' },
  { path: '/storage', title: 'Storage', category: 'system' },
  { path: '/studio-prefs', title: 'Studio Preferences', category: 'settings' },
  { path: '/studio', title: 'Studio', category: 'build' },
  { path: '/swarm-planner', title: 'Swarm Planner', category: 'ai' },
  { path: '/systems-forge', title: 'Systems Forge', category: 'build' },
  { path: '/tools-hub', title: 'Tools Hub', category: 'tools' },
  { path: '/top', title: 'Top', category: 'progress' },
  { path: '/tournaments', title: 'Tournaments', category: 'progress' },
  { path: '/trophy-case', title: 'Trophy Case', category: 'progress' },
  { path: '/worldforge-map', title: 'WorldForge Map', category: 'build' },
  { path: '/worldforge-vault', title: 'WorldForge Vault', category: 'build' },
  { path: '/worldforge', title: 'WorldForge', category: 'build', heavy: true },
  { path: '/worlds-gallery', title: 'Worlds Gallery', category: 'build' },
  { path: '/zaibatsu', title: 'Zaibatsu', category: 'build' },
  { path: '/zip-export', title: 'ZIP Export', category: 'tools' },
];

export function getRoutesByCategory(): Record<string, RouteEntry[]> {
  const out: Record<string, RouteEntry[]> = {};
  for (const r of ROUTE_REGISTRY) (out[r.category] ||= []).push(r);
  return out;
}

export function getRouteCount(): number {
  return ROUTE_REGISTRY.length;
}
