"""Research evidence and historical lineage; this namespace grants no production authority."""

from ..research import (
    EvidenceGraph,
    EvidenceNode,
    ExperimentPlan,
    Outcome,
    ReproductionRecord,
    ResearchConclusion,
    ResearchError,
    ResearchQuestion,
    synthesize,
    validate_reproduction,
)

from .source_lineage import (
    CitationEdge,
    CitationGraphReport,
    CitationRelation,
    CitationSpec,
    HistoricalTechnique,
    IngestionReceipt,
    ReplicationOutcome,
    ReplicationRecord,
    ResearchClaim,
    ResearchLineageError,
    ResearchSource,
    ResearchSourceRegistry,
    RetractionRecord,
    SourceStatus,
    content_digest,
)

__all__ = [
    "EvidenceGraph",
    "EvidenceNode",
    "ExperimentPlan",
    "Outcome",
    "ReproductionRecord",
    "ResearchConclusion",
    "ResearchError",
    "ResearchQuestion",
    "synthesize",
    "validate_reproduction",
    "CitationEdge",
    "CitationGraphReport",
    "CitationRelation",
    "CitationSpec",
    "HistoricalTechnique",
    "IngestionReceipt",
    "ReplicationOutcome",
    "ReplicationRecord",
    "ResearchClaim",
    "ResearchLineageError",
    "ResearchSource",
    "ResearchSourceRegistry",
    "RetractionRecord",
    "SourceStatus",
    "content_digest",
]
