"""Engine-neutral world/scene state graph contracts."""

from .scene import (
    SCHEMA_NAME,
    SCHEMA_VERSION,
    MAX_CHILDREN,
    MAX_DEPTH,
    MAX_ENTITIES,
    GraphDiagnosis,
    SceneEntity,
    Transform,
    WorldBoundError,
    WorldCycleError,
    WorldOrphanError,
    WorldReferenceError,
    WorldSceneError,
    WorldSchemaError,
    WorldState,
    WorldTimeError,
    diagnose_payload,
)

__all__ = [
    "SCHEMA_NAME",
    "SCHEMA_VERSION",
    "MAX_CHILDREN",
    "MAX_DEPTH",
    "MAX_ENTITIES",
    "GraphDiagnosis",
    "SceneEntity",
    "Transform",
    "WorldBoundError",
    "WorldCycleError",
    "WorldOrphanError",
    "WorldReferenceError",
    "WorldSceneError",
    "WorldSchemaError",
    "WorldState",
    "WorldTimeError",
    "diagnose_payload",
]
