"""Stable Jeeves probabilistic-modeling facade.

This module keeps the public import surface compact while the implementation is
split into state-space filtering, exact Bayesian parameter uncertainty, online
Bayesian ensembles, distributional calibration, hidden-Markov regime inference,
multiscale harmonic forecasting, cross-family arbitration, paired model
comparison, and explicit promotion eligibility contracts.
"""

from .probabilistic_arbitration import (
    ArbitratedForecast,
    CrossFamilyArbitrator,
    CrossFamilyConfig,
    CrossFamilyReport,
    CrossFamilyStep,
    ExpertComponent,
    ExpertKind,
    PredictiveDistribution,
)
from .probabilistic_arena import (
    ArenaCandidate,
    ArenaFold,
    ArenaMetrics,
    HACComparison,
    PredictiveArenaConfig,
    PredictiveArenaDecision,
    PredictiveArenaReport,
    evaluate_predictive_arena,
    newey_west_mean_test,
    regime_forecast_crps,
)
from .probabilistic_bayes import (
    BayesianTrendConfig,
    BayesianTrendEvaluation,
    BayesianTrendFit,
    BayesianTrendFold,
    StudentTForecast,
    evaluate_bayesian_trend,
    fit_bayesian_trend,
    forecast_bayesian_trend,
)
from .probabilistic_calibration import (
    CalibrationConfig,
    CalibrationReport,
    CoverageDiagnostic,
    DistributionObservation,
    DriftEvent,
    PitDiagnostic,
    calibrate_distributions,
    central_interval,
    gaussian_as_mixture,
    mixture_cdf,
    mixture_quantile,
    pinball_loss,
)
from .probabilistic_contracts import (
    ProbabilisticPromotionDecision,
    ProbabilisticPromotionGate,
    evaluate_probabilistic_promotion,
)
from .probabilistic_ensemble import (
    BayesianEnsembleConfig,
    BayesianEnsembleReport,
    EnsembleStep,
    MixtureForecast,
    OnlineBayesianEnsemble,
    WeightedForecast,
    gaussian_mixture_crps,
    probability_integral_transform,
)
from .probabilistic_regimes import (
    GaussianRegime,
    RegimeForecast,
    RegimeForecastComponent,
    RegimeHMMConfig,
    RegimeHMMFit,
    RegimeHMMModel,
    RegimePosteriorStep,
    RegimePrequentialScore,
    evaluate_regime_hmm_prequential,
    fit_regime_hmm,
    forecast_regime_hmm,
)
from .probabilistic_spectral import (
    HarmonicComponent,
    SpectralConfig,
    SpectralFit,
    SpectralPeak,
    SpectralScore,
    SpectralTournament,
    discover_spectral_peaks,
    evaluate_spectral_complexities,
    fit_spectral_model,
    forecast_spectral,
)
from .probabilistic_state_space import (
    FilterStep,
    GaussianForecast,
    InnovationRegime,
    RegimePosterior,
    SeriesValues,
    StateSpaceConfig,
    StateSpaceError,
    StateSpaceFamily,
    StateSpaceFit,
    StateSpaceScore,
    StateSpaceTournament,
    evaluate_state_space_families,
    fit_state_space,
    forecast_state_space,
)

__all__ = [
    "ArbitratedForecast",
    "ArenaCandidate",
    "ArenaFold",
    "ArenaMetrics",
    "BayesianEnsembleConfig",
    "BayesianEnsembleReport",
    "BayesianTrendConfig",
    "BayesianTrendEvaluation",
    "BayesianTrendFit",
    "BayesianTrendFold",
    "CalibrationConfig",
    "CalibrationReport",
    "CoverageDiagnostic",
    "CrossFamilyArbitrator",
    "CrossFamilyConfig",
    "CrossFamilyReport",
    "CrossFamilyStep",
    "DistributionObservation",
    "DriftEvent",
    "EnsembleStep",
    "ExpertComponent",
    "ExpertKind",
    "FilterStep",
    "GaussianForecast",
    "GaussianRegime",
    "HACComparison",
    "HarmonicComponent",
    "InnovationRegime",
    "MixtureForecast",
    "OnlineBayesianEnsemble",
    "PitDiagnostic",
    "PredictiveArenaConfig",
    "PredictiveArenaDecision",
    "PredictiveArenaReport",
    "PredictiveDistribution",
    "ProbabilisticPromotionDecision",
    "ProbabilisticPromotionGate",
    "RegimeForecast",
    "RegimeForecastComponent",
    "RegimeHMMConfig",
    "RegimeHMMFit",
    "RegimeHMMModel",
    "RegimePosterior",
    "RegimePosteriorStep",
    "RegimePrequentialScore",
    "SeriesValues",
    "SpectralConfig",
    "SpectralFit",
    "SpectralPeak",
    "SpectralScore",
    "SpectralTournament",
    "StateSpaceConfig",
    "StateSpaceError",
    "StateSpaceFamily",
    "StateSpaceFit",
    "StateSpaceScore",
    "StateSpaceTournament",
    "StudentTForecast",
    "WeightedForecast",
    "calibrate_distributions",
    "central_interval",
    "discover_spectral_peaks",
    "evaluate_bayesian_trend",
    "evaluate_predictive_arena",
    "evaluate_probabilistic_promotion",
    "evaluate_regime_hmm_prequential",
    "evaluate_spectral_complexities",
    "evaluate_state_space_families",
    "fit_bayesian_trend",
    "fit_regime_hmm",
    "fit_spectral_model",
    "fit_state_space",
    "forecast_bayesian_trend",
    "forecast_regime_hmm",
    "forecast_spectral",
    "forecast_state_space",
    "gaussian_as_mixture",
    "gaussian_mixture_crps",
    "mixture_cdf",
    "mixture_quantile",
    "newey_west_mean_test",
    "pinball_loss",
    "probability_integral_transform",
    "regime_forecast_crps",
]
