"""Stable Jeeves probabilistic-modeling facade.

This module keeps the public import surface compact while the implementation is
split into state-space filtering, online Bayesian ensembles, distributional
calibration, hidden-Markov regime inference, multiscale harmonic forecasting,
and explicit promotion eligibility contracts.
"""

from .probabilistic_calibration import (
    CalibrationConfig,
    CalibrationReport,
    CoverageDiagnostic,
    DistributionObservation,
    DriftEvent,
    PitDiagnostic,
    calibrate_distributions,
    central_interval,
    gaussian_as_mixture,
    mixture_cdf,
    mixture_quantile,
    pinball_loss,
)
from .probabilistic_contracts import (
    ProbabilisticPromotionDecision,
    ProbabilisticPromotionGate,
    evaluate_probabilistic_promotion,
)
from .probabilistic_ensemble import (
    BayesianEnsembleConfig,
    BayesianEnsembleReport,
    EnsembleStep,
    MixtureForecast,
    OnlineBayesianEnsemble,
    WeightedForecast,
    gaussian_mixture_crps,
    probability_integral_transform,
)
from .probabilistic_regimes import (
    GaussianRegime,
    RegimeForecast,
    RegimeForecastComponent,
    RegimeHMMConfig,
    RegimeHMMFit,
    RegimeHMMModel,
    RegimePosteriorStep,
    RegimePrequentialScore,
    evaluate_regime_hmm_prequential,
    fit_regime_hmm,
    forecast_regime_hmm,
)
from .probabilistic_spectral import (
    HarmonicComponent,
    SpectralConfig,
    SpectralFit,
    SpectralPeak,
    SpectralScore,
    SpectralTournament,
    discover_spectral_peaks,
    evaluate_spectral_complexities,
    fit_spectral_model,
    forecast_spectral,
)
from .probabilistic_state_space import (
    FilterStep,
    GaussianForecast,
    InnovationRegime,
    RegimePosterior,
    SeriesValues,
    StateSpaceConfig,
    StateSpaceError,
    StateSpaceFamily,
    StateSpaceFit,
    StateSpaceScore,
    StateSpaceTournament,
    evaluate_state_space_families,
    fit_state_space,
    forecast_state_space,
)

__all__ = [
    "BayesianEnsembleConfig",
    "BayesianEnsembleReport",
    "CalibrationConfig",
    "CalibrationReport",
    "CoverageDiagnostic",
    "DistributionObservation",
    "DriftEvent",
    "EnsembleStep",
    "FilterStep",
    "GaussianForecast",
    "GaussianRegime",
    "HarmonicComponent",
    "InnovationRegime",
    "MixtureForecast",
    "OnlineBayesianEnsemble",
    "PitDiagnostic",
    "ProbabilisticPromotionDecision",
    "ProbabilisticPromotionGate",
    "RegimeForecast",
    "RegimeForecastComponent",
    "RegimeHMMConfig",
    "RegimeHMMFit",
    "RegimeHMMModel",
    "RegimePosterior",
    "RegimePosteriorStep",
    "RegimePrequentialScore",
    "SeriesValues",
    "SpectralConfig",
    "SpectralFit",
    "SpectralPeak",
    "SpectralScore",
    "SpectralTournament",
    "StateSpaceConfig",
    "StateSpaceError",
    "StateSpaceFamily",
    "StateSpaceFit",
    "StateSpaceScore",
    "StateSpaceTournament",
    "WeightedForecast",
    "calibrate_distributions",
    "central_interval",
    "discover_spectral_peaks",
    "evaluate_probabilistic_promotion",
    "evaluate_regime_hmm_prequential",
    "evaluate_spectral_complexities",
    "evaluate_state_space_families",
    "fit_regime_hmm",
    "fit_spectral_model",
    "fit_state_space",
    "forecast_regime_hmm",
    "forecast_spectral",
    "forecast_state_space",
    "gaussian_as_mixture",
    "gaussian_mixture_crps",
    "mixture_cdf",
    "mixture_quantile",
    "pinball_loss",
    "probability_integral_transform",
]
