"""Stable Jeeves probabilistic-modeling facade.

This module keeps the public import surface compact while the implementation is
split into state-space filtering, online Bayesian ensembles, distributional
calibration, hidden-Markov regime inference, paired model comparison, and explicit
promotion eligibility contracts.
"""

from .probabilistic_arena import (
    ArenaCandidate,
    ArenaFold,
    ArenaMetrics,
    HACComparison,
    PredictiveArenaConfig,
    PredictiveArenaDecision,
    PredictiveArenaReport,
    evaluate_predictive_arena,
    newey_west_mean_test,
    regime_forecast_crps,
)
from .probabilistic_calibration import (
    CalibrationConfig,
    CalibrationReport,
    CoverageDiagnostic,
    DistributionObservation,
    DriftEvent,
    PitDiagnostic,
    calibrate_distributions,
    central_interval,
    gaussian_as_mixture,
    mixture_cdf,
    mixture_quantile,
    pinball_loss,
)
from .probabilistic_contracts import (
    ProbabilisticPromotionDecision,
    ProbabilisticPromotionGate,
    evaluate_probabilistic_promotion,
)
from .probabilistic_ensemble import (
    BayesianEnsembleConfig,
    BayesianEnsembleReport,
    EnsembleStep,
    MixtureForecast,
    OnlineBayesianEnsemble,
    WeightedForecast,
    gaussian_mixture_crps,
    probability_integral_transform,
)
from .probabilistic_regimes import (
    GaussianRegime,
    RegimeForecast,
    RegimeForecastComponent,
    RegimeHMMConfig,
    RegimeHMMFit,
    RegimeHMMModel,
    RegimePosteriorStep,
    RegimePrequentialScore,
    evaluate_regime_hmm_prequential,
    fit_regime_hmm,
    forecast_regime_hmm,
)
from .probabilistic_state_space import (
    FilterStep,
    GaussianForecast,
    InnovationRegime,
    RegimePosterior,
    SeriesValues,
    StateSpaceConfig,
    StateSpaceError,
    StateSpaceFamily,
    StateSpaceFit,
    StateSpaceScore,
    StateSpaceTournament,
    evaluate_state_space_families,
    fit_state_space,
    forecast_state_space,
)

__all__ = [
    "ArenaCandidate",
    "ArenaFold",
    "ArenaMetrics",
    "BayesianEnsembleConfig",
    "BayesianEnsembleReport",
    "CalibrationConfig",
    "CalibrationReport",
    "CoverageDiagnostic",
    "DistributionObservation",
    "DriftEvent",
    "EnsembleStep",
    "FilterStep",
    "GaussianForecast",
    "GaussianRegime",
    "HACComparison",
    "InnovationRegime",
    "MixtureForecast",
    "OnlineBayesianEnsemble",
    "PitDiagnostic",
    "PredictiveArenaConfig",
    "PredictiveArenaDecision",
    "PredictiveArenaReport",
    "ProbabilisticPromotionDecision",
    "ProbabilisticPromotionGate",
    "RegimeForecast",
    "RegimeForecastComponent",
    "RegimeHMMConfig",
    "RegimeHMMFit",
    "RegimeHMMModel",
    "RegimePosterior",
    "RegimePosteriorStep",
    "RegimePrequentialScore",
    "SeriesValues",
    "StateSpaceConfig",
    "StateSpaceError",
    "StateSpaceFamily",
    "StateSpaceFit",
    "StateSpaceScore",
    "StateSpaceTournament",
    "WeightedForecast",
    "calibrate_distributions",
    "central_interval",
    "evaluate_predictive_arena",
    "evaluate_probabilistic_promotion",
    "evaluate_regime_hmm_prequential",
    "evaluate_state_space_families",
    "fit_regime_hmm",
    "fit_state_space",
    "forecast_regime_hmm",
    "forecast_state_space",
    "gaussian_as_mixture",
    "gaussian_mixture_crps",
    "mixture_cdf",
    "mixture_quantile",
    "newey_west_mean_test",
    "pinball_loss",
    "probability_integral_transform",
    "regime_forecast_crps",
]
