"""Archive inspection, integrity checking, and bounded creation contracts.

Extraction is intentionally omitted because archive path traversal, symlink
replacement, and overwrite semantics require a dedicated extraction sandbox.
"""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="archive.tar_list",
        executable_key="tar",
        options=(OptionSpec("-t"), OptionSpec("--list"), OptionSpec("-f", "path"), OptionSpec("--verbose"), OptionSpec("--numeric-owner"), OptionSpec("--utc"), OptionSpec("--full-time")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("archive",)),
        description="archive.tar_list",
    ),
    OperationSpec(
        logical_name="archive.tar_compare",
        executable_key="tar",
        options=(OptionSpec("-d"), OptionSpec("--diff"), OptionSpec("--compare"), OptionSpec("-f", "path"), OptionSpec("--verbose")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.tar_compare",
    ),
    OperationSpec(
        logical_name="archive.tar_create",
        executable_key="tar",
        options=(OptionSpec("-c"), OptionSpec("--create"), OptionSpec("-f", "path"), OptionSpec("--format", "short"), OptionSpec("--sort", "short"), OptionSpec("--mtime", "short"), OptionSpec("--owner", "short"), OptionSpec("--group", "short"), OptionSpec("--numeric-owner")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE, CommandEffect.PACKAGE}),
        risk=CommandRisk.MODERATE,
        timeout=600,
        tags=frozenset(("archive",)),
        description="archive.tar_create",
    ),
    OperationSpec(
        logical_name="archive.unzip_list",
        executable_key="unzip",
        options=(OptionSpec("-l"), OptionSpec("-v"), OptionSpec("-Z")),
        positionals=("path",),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.unzip_list",
    ),
    OperationSpec(
        logical_name="archive.unzip_test",
        executable_key="unzip",
        options=(OptionSpec("-t"), OptionSpec("-qq")),
        positionals=("path",),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.unzip_test",
    ),
    OperationSpec(
        logical_name="archive.zipinfo",
        executable_key="zipinfo",
        options=(OptionSpec("-1"), OptionSpec("-s"), OptionSpec("-l"), OptionSpec("-v"), OptionSpec("-h"), OptionSpec("-t"), OptionSpec("-z")),
        positionals=("path",),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.zipinfo",
    ),
    OperationSpec(
        logical_name="archive.gzip_test",
        executable_key="gzip",
        options=(OptionSpec("-t"), OptionSpec("--test"), OptionSpec("-v"), OptionSpec("--verbose")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.gzip_test",
    ),
    OperationSpec(
        logical_name="archive.gzip_list",
        executable_key="gzip",
        options=(OptionSpec("-l"), OptionSpec("--list"), OptionSpec("-v"), OptionSpec("--verbose")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("archive",)),
        description="archive.gzip_list",
    ),
    OperationSpec(
        logical_name="archive.bzip2_test",
        executable_key="bzip2",
        options=(OptionSpec("-t"), OptionSpec("--test"), OptionSpec("-v"), OptionSpec("--verbose")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.bzip2_test",
    ),
    OperationSpec(
        logical_name="archive.xz_test",
        executable_key="xz",
        options=(OptionSpec("-t"), OptionSpec("--test"), OptionSpec("-v"), OptionSpec("--verbose")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.xz_test",
    ),
    OperationSpec(
        logical_name="archive.xz_list",
        executable_key="xz",
        options=(OptionSpec("-l"), OptionSpec("--list"), OptionSpec("-v"), OptionSpec("--verbose"), OptionSpec("--robot")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("archive",)),
        description="archive.xz_list",
    ),
    OperationSpec(
        logical_name="archive.zstd_test",
        executable_key="zstd",
        options=(OptionSpec("-t"), OptionSpec("--test"), OptionSpec("-v"), OptionSpec("--verbose")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.zstd_test",
    ),
    OperationSpec(
        logical_name="archive.zstd_list",
        executable_key="zstd",
        options=(OptionSpec("-l"), OptionSpec("--list"), OptionSpec("-v"), OptionSpec("--verbose")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("archive",)),
        description="archive.zstd_list",
    ),
    OperationSpec(
        logical_name="archive.7z_list",
        executable_key="7z",
        fixed_prefix=("l",),
        positionals=("path",),
        variadic="safe",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.7z_list",
    ),
    OperationSpec(
        logical_name="archive.7z_test",
        executable_key="7z",
        fixed_prefix=("t",),
        positionals=("path",),
        variadic="safe",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.7z_test",
    ),
    OperationSpec(
        logical_name="archive.zip_test",
        executable_key="zip",
        options=(OptionSpec("-T"), OptionSpec("--test")),
        positionals=("path",),
        min_positionals=1,
        max_positionals=1,
        effects=frozenset({CommandEffect.READ, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("archive",)),
        description="archive.zip_test",
    ),
    OperationSpec(
        logical_name="archive.zip_create",
        executable_key="zip",
        options=(OptionSpec("-r"), OptionSpec("--recurse-paths"), OptionSpec("-9"), OptionSpec("--best"), OptionSpec("-X"), OptionSpec("--no-extra")),
        positionals=("path",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE, CommandEffect.PACKAGE}),
        risk=CommandRisk.MODERATE,
        timeout=600,
        tags=frozenset(("archive",)),
        description="archive.zip_create",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS


DENIED_EXTRACTION_OPERATIONS = frozenset({
    "tar:extract", "unzip:extract", "7z:x", "7z:e", "cpio:extract",
})
