"""Read-only binary and artifact inspection contracts.

No linker, loader, signing, patching, stripping, or archive extraction
operations are exposed here.
"""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="artifact.file",
        executable_key="file",
        options=(OptionSpec("-b"), OptionSpec("--brief"), OptionSpec("-i"), OptionSpec("--mime"), OptionSpec("--mime-type"), OptionSpec("--mime-encoding"), OptionSpec("-L"), OptionSpec("--dereference"), OptionSpec("-k"), OptionSpec("--keep-going")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.file",
    ),
    OperationSpec(
        logical_name="artifact.strings",
        executable_key="strings",
        options=(OptionSpec("-a"), OptionSpec("--all"), OptionSpec("-f"), OptionSpec("--print-file-name"), OptionSpec("-n", "integer"), OptionSpec("--bytes", "integer"), OptionSpec("-t", "short"), OptionSpec("--radix", "short"), OptionSpec("-e", "short"), OptionSpec("--encoding", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.strings",
    ),
    OperationSpec(
        logical_name="artifact.readelf_headers",
        executable_key="readelf",
        options=(OptionSpec("-h"), OptionSpec("--file-header")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.readelf_headers",
    ),
    OperationSpec(
        logical_name="artifact.readelf_sections",
        executable_key="readelf",
        options=(OptionSpec("-S"), OptionSpec("--section-headers"), OptionSpec("-W"), OptionSpec("--wide")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.readelf_sections",
    ),
    OperationSpec(
        logical_name="artifact.readelf_symbols",
        executable_key="readelf",
        options=(OptionSpec("-s"), OptionSpec("--symbols"), OptionSpec("--dyn-syms"), OptionSpec("-W"), OptionSpec("--wide")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.readelf_symbols",
    ),
    OperationSpec(
        logical_name="artifact.readelf_relocs",
        executable_key="readelf",
        options=(OptionSpec("-r"), OptionSpec("--relocs"), OptionSpec("-W"), OptionSpec("--wide")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.readelf_relocs",
    ),
    OperationSpec(
        logical_name="artifact.readelf_dynamic",
        executable_key="readelf",
        options=(OptionSpec("-d"), OptionSpec("--dynamic"), OptionSpec("-W"), OptionSpec("--wide")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.readelf_dynamic",
    ),
    OperationSpec(
        logical_name="artifact.readelf_notes",
        executable_key="readelf",
        options=(OptionSpec("-n"), OptionSpec("--notes"), OptionSpec("-W"), OptionSpec("--wide")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.readelf_notes",
    ),
    OperationSpec(
        logical_name="artifact.readelf_version_info",
        executable_key="readelf",
        options=(OptionSpec("-V"), OptionSpec("--version-info"), OptionSpec("-W"), OptionSpec("--wide")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.readelf_version_info",
    ),
    OperationSpec(
        logical_name="artifact.readelf_debug",
        executable_key="readelf",
        options=(OptionSpec("--debug-dump", "short"), OptionSpec("-W"), OptionSpec("--wide")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.readelf_debug",
    ),
    OperationSpec(
        logical_name="artifact.objdump_headers",
        executable_key="objdump",
        options=(OptionSpec("-f"), OptionSpec("--file-headers"), OptionSpec("-p"), OptionSpec("--private-headers")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.objdump_headers",
    ),
    OperationSpec(
        logical_name="artifact.objdump_sections",
        executable_key="objdump",
        options=(OptionSpec("-h"), OptionSpec("--section-headers"), OptionSpec("-x"), OptionSpec("--all-headers")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.objdump_sections",
    ),
    OperationSpec(
        logical_name="artifact.objdump_symbols",
        executable_key="objdump",
        options=(OptionSpec("-t"), OptionSpec("--syms"), OptionSpec("-T"), OptionSpec("--dynamic-syms")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.objdump_symbols",
    ),
    OperationSpec(
        logical_name="artifact.objdump_disassemble",
        executable_key="objdump",
        options=(OptionSpec("-d"), OptionSpec("--disassemble"), OptionSpec("-D"), OptionSpec("--disassemble-all"), OptionSpec("-S"), OptionSpec("--source"), OptionSpec("-l"), OptionSpec("--line-numbers"), OptionSpec("-C"), OptionSpec("--demangle")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.objdump_disassemble",
    ),
    OperationSpec(
        logical_name="artifact.objdump_contents",
        executable_key="objdump",
        options=(OptionSpec("-s"), OptionSpec("--full-contents"), OptionSpec("-j", "short"), OptionSpec("--section", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.objdump_contents",
    ),
    OperationSpec(
        logical_name="artifact.nm",
        executable_key="nm",
        options=(OptionSpec("-a"), OptionSpec("--debug-syms"), OptionSpec("-C"), OptionSpec("--demangle"), OptionSpec("-D"), OptionSpec("--dynamic"), OptionSpec("-g"), OptionSpec("--extern-only"), OptionSpec("-n"), OptionSpec("--numeric-sort"), OptionSpec("-S"), OptionSpec("--print-size"), OptionSpec("-u"), OptionSpec("--undefined-only")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.nm",
    ),
    OperationSpec(
        logical_name="artifact.size",
        executable_key="size",
        options=(OptionSpec("-A"), OptionSpec("--format", "short"), OptionSpec("-d"), OptionSpec("-o"), OptionSpec("-x")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.size",
    ),
    OperationSpec(
        logical_name="artifact.ar_list",
        executable_key="ar",
        fixed_prefix=("t",),
        positionals=("path",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.ar_list",
    ),
    OperationSpec(
        logical_name="artifact.ar_verbose_list",
        executable_key="ar",
        fixed_prefix=("tv",),
        positionals=("path",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.ar_verbose_list",
    ),
    OperationSpec(
        logical_name="artifact.otool_libraries",
        executable_key="otool",
        options=(OptionSpec("-L"),),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.otool_libraries",
    ),
    OperationSpec(
        logical_name="artifact.otool_headers",
        executable_key="otool",
        options=(OptionSpec("-h"), OptionSpec("-l")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.otool_headers",
    ),
    OperationSpec(
        logical_name="artifact.otool_symbols",
        executable_key="otool",
        options=(OptionSpec("-Iv"),),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.otool_symbols",
    ),
    OperationSpec(
        logical_name="artifact.codesign_display",
        executable_key="codesign",
        options=(OptionSpec("-d"), OptionSpec("--display"), OptionSpec("--verbose", "integer"), OptionSpec("--entitlements", "literal:-")),
        positionals=("path",),
        min_positionals=1,
        max_positionals=1,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.codesign_display",
    ),
    OperationSpec(
        logical_name="artifact.wasm2wat",
        executable_key="wasm2wat",
        options=(OptionSpec("--enable-all"), OptionSpec("--no-check")),
        positionals=("path",),
        min_positionals=1,
        max_positionals=1,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.wasm2wat",
    ),
    OperationSpec(
        logical_name="artifact.wasm_objdump_headers",
        executable_key="wasm_objdump",
        options=(OptionSpec("-h"), OptionSpec("--headers")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.wasm_objdump_headers",
    ),
    OperationSpec(
        logical_name="artifact.wasm_objdump_details",
        executable_key="wasm_objdump",
        options=(OptionSpec("-x"), OptionSpec("--details")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.wasm_objdump_details",
    ),
    OperationSpec(
        logical_name="artifact.wasm_objdump_disassemble",
        executable_key="wasm_objdump",
        options=(OptionSpec("-d"), OptionSpec("--disassemble")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("artifact", "inspection")),
        description="artifact.wasm_objdump_disassemble",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS


DENIED_MUTATORS = frozenset({
    "strip", "objcopy", "install_name_tool", "codesign:--sign",
    "ar:r", "ar:q", "ar:d",
})
