"""Build systems logical command contracts."""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="build.cmake_version",
        executable_key="cmake",
        options=(OptionSpec("--version"),),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("build",)),
        description="build.cmake_version",
    ),
    OperationSpec(
        logical_name="build.cmake_configure",
        executable_key="cmake",
        options=(OptionSpec("-S", "path"), OptionSpec("-B", "path"), OptionSpec("-G", "short"), OptionSpec("-D", "safe", True), OptionSpec("--preset", "short"), OptionSpec("--fresh")),
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=900.0,
        tags=frozenset(("build",)),
        description="build.cmake_configure",
    ),
    OperationSpec(
        logical_name="build.cmake_build",
        executable_key="cmake",
        subcommand="--build",
        options=(OptionSpec("--target", "short", True), OptionSpec("--config", "short"), OptionSpec("--parallel", "integer"), OptionSpec("--clean-first"), OptionSpec("--verbose")),
        positionals=("path",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("build",)),
        description="build.cmake_build",
    ),
    OperationSpec(
        logical_name="build.cmake_install",
        executable_key="cmake",
        subcommand="--install",
        options=(OptionSpec("--prefix", "path"), OptionSpec("--config", "short"), OptionSpec("--component", "short"), OptionSpec("--strip")),
        positionals=("path",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=900.0,
        tags=frozenset(("build",)),
        description="build.cmake_install",
    ),
    OperationSpec(
        logical_name="build.cmake_open",
        executable_key="cmake",
        subcommand="--open",
        positionals=("path",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.PROCESS}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("build",)),
        description="build.cmake_open",
    ),
    OperationSpec(
        logical_name="build.ctest",
        executable_key="ctest",
        options=(OptionSpec("--test-dir", "path"), OptionSpec("--output-on-failure"), OptionSpec("--parallel", "integer"), OptionSpec("--timeout", "integer"), OptionSpec("-R", "safe"), OptionSpec("-E", "safe"), OptionSpec("-C", "short")),
        effects=frozenset({CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        allow_nonzero_success=True,
        tags=frozenset(("build",)),
        description="build.ctest",
    ),
    OperationSpec(
        logical_name="build.ninja_version",
        executable_key="ninja",
        options=(OptionSpec("--version"),),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("build",)),
        description="build.ninja_version",
    ),
    OperationSpec(
        logical_name="build.ninja_build",
        executable_key="ninja",
        options=(OptionSpec("-C", "path"), OptionSpec("-j", "integer"), OptionSpec("-k", "integer"), OptionSpec("-v")),
        variadic="short",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("build",)),
        description="build.ninja_build",
    ),
    OperationSpec(
        logical_name="build.ninja_dry_run",
        executable_key="ninja",
        options=(OptionSpec("-C", "path"), OptionSpec("-n"), OptionSpec("-d", "short")),
        variadic="short",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("build",)),
        description="build.ninja_dry_run",
    ),
    OperationSpec(
        logical_name="build.ninja_clean",
        executable_key="ninja",
        subcommand="-t",
        positionals=("short",),
        variadic="short",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE, CommandEffect.BUILD}),
        risk=CommandRisk.HIGH,
        timeout=600.0,
        tags=frozenset(("build",)),
        description="build.ninja_clean",
    ),
    OperationSpec(
        logical_name="build.make_dry",
        executable_key="make",
        options=(OptionSpec("-n"), OptionSpec("--dry-run"), OptionSpec("-C", "path"), OptionSpec("-f", "path"), OptionSpec("-j", "integer")),
        variadic="short",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("build",)),
        description="build.make_dry",
    ),
    OperationSpec(
        logical_name="build.make_build",
        executable_key="make",
        options=(OptionSpec("-C", "path"), OptionSpec("-f", "path"), OptionSpec("-j", "integer"), OptionSpec("-k"), OptionSpec("--warn-undefined-variables")),
        variadic="short",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("build",)),
        description="build.make_build",
    ),
    OperationSpec(
        logical_name="build.make_clean",
        executable_key="make",
        options=(OptionSpec("-C", "path"), OptionSpec("-f", "path")),
        positionals=("short",),
        min_positionals=1,
        max_positionals=1,
        effects=frozenset({CommandEffect.WRITE, CommandEffect.BUILD}),
        risk=CommandRisk.HIGH,
        timeout=600.0,
        tags=frozenset(("build",)),
        description="build.make_clean",
    ),
    OperationSpec(
        logical_name="build.meson_setup",
        executable_key="meson",
        subcommand="setup",
        options=(OptionSpec("--buildtype", "short"), OptionSpec("--wipe"), OptionSpec("--reconfigure"), OptionSpec("--prefix", "path")),
        positionals=("path",),
        variadic="path",
        min_positionals=2,
        max_positionals=3,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=900.0,
        tags=frozenset(("build",)),
        description="build.meson_setup",
    ),
    OperationSpec(
        logical_name="build.meson_compile",
        executable_key="meson",
        subcommand="compile",
        options=(OptionSpec("-C", "path"), OptionSpec("-j", "integer"), OptionSpec("--clean")),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("build",)),
        description="build.meson_compile",
    ),
    OperationSpec(
        logical_name="build.meson_test",
        executable_key="meson",
        subcommand="test",
        options=(OptionSpec("-C", "path"), OptionSpec("--print-errorlogs"), OptionSpec("--num-processes", "integer"), OptionSpec("--suite", "short", True)),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        allow_nonzero_success=True,
        tags=frozenset(("build",)),
        description="build.meson_test",
    ),
    OperationSpec(
        logical_name="build.bazel_query",
        executable_key="bazel",
        subcommand="query",
        options=(OptionSpec("--output", "short"), OptionSpec("--keep_going")),
        positionals=("safe",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("build",)),
        description="build.bazel_query",
    ),
    OperationSpec(
        logical_name="build.bazel_build",
        executable_key="bazel",
        subcommand="build",
        options=(OptionSpec("--keep_going"), OptionSpec("--jobs", "integer"), OptionSpec("--config", "short"), OptionSpec("--define", "safe", True)),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("build",)),
        description="build.bazel_build",
    ),
    OperationSpec(
        logical_name="build.bazel_test",
        executable_key="bazel",
        subcommand="test",
        options=(OptionSpec("--keep_going"), OptionSpec("--jobs", "integer"), OptionSpec("--config", "short"), OptionSpec("--test_output", "short")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        allow_nonzero_success=True,
        tags=frozenset(("build",)),
        description="build.bazel_test",
    ),
    OperationSpec(
        logical_name="build.bazel_clean",
        executable_key="bazel",
        subcommand="clean",
        options=(OptionSpec("--expunge"), OptionSpec("--async")),
        effects=frozenset({CommandEffect.WRITE, CommandEffect.BUILD}),
        risk=CommandRisk.HIGH,
        timeout=900.0,
        tags=frozenset(("build",)),
        description="build.bazel_clean",
    ),
    OperationSpec(
        logical_name="build.just_list",
        executable_key="just",
        subcommand="--list",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("build",)),
        description="build.just_list",
    ),
    OperationSpec(
        logical_name="build.just_dry",
        executable_key="just",
        subcommand="--dry-run",
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("build",)),
        description="build.just_dry",
    ),
    OperationSpec(
        logical_name="build.just_run",
        executable_key="just",
        variadic="safe",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.PROCESS, CommandEffect.BUILD}),
        risk=CommandRisk.MODERATE,
        timeout=1800.0,
        tags=frozenset(("build",)),
        description="build.just_run",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS
