"""Read-only data transformation, search, and repository measurement contracts.

Write/in-place flags such as yq -i, sed -i, fd --exec, and rg --pre are
intentionally absent.
"""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="jq.filter",
        executable_key="jq",
        options=(OptionSpec("-c"), OptionSpec("--compact-output"), OptionSpec("-r"), OptionSpec("--raw-output"), OptionSpec("-S"), OptionSpec("--sort-keys"), OptionSpec("-e"), OptionSpec("--exit-status"), OptionSpec("-M"), OptionSpec("--monochrome-output"), OptionSpec("--tab"), OptionSpec("--indent", "integer")),
        positionals=("safe",),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        allow_stdin=True,
        tags=frozenset(("data",)),
        description="jq.filter",
    ),
    OperationSpec(
        logical_name="jq.slurp",
        executable_key="jq",
        options=(OptionSpec("-s"), OptionSpec("--slurp"), OptionSpec("-c"), OptionSpec("-r"), OptionSpec("-S")),
        positionals=("safe",),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        allow_stdin=True,
        tags=frozenset(("data",)),
        description="jq.slurp",
    ),
    OperationSpec(
        logical_name="jq.raw_input",
        executable_key="jq",
        options=(OptionSpec("-R"), OptionSpec("--raw-input"), OptionSpec("-s"), OptionSpec("-r"), OptionSpec("-c")),
        positionals=("safe",),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        allow_stdin=True,
        tags=frozenset(("data",)),
        description="jq.raw_input",
    ),
    OperationSpec(
        logical_name="jq.null_input",
        executable_key="jq",
        options=(OptionSpec("-n"), OptionSpec("--null-input"), OptionSpec("-c"), OptionSpec("-r"), OptionSpec("-S")),
        positionals=("safe",),
        min_positionals=1,
        max_positionals=1,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="jq.null_input",
    ),
    OperationSpec(
        logical_name="jq.seq",
        executable_key="jq",
        options=(OptionSpec("--seq"), OptionSpec("-c"), OptionSpec("-r"), OptionSpec("-S")),
        positionals=("safe",),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        allow_stdin=True,
        tags=frozenset(("data",)),
        description="jq.seq",
    ),
    OperationSpec(
        logical_name="yq.eval",
        executable_key="yq",
        subcommand="eval",
        options=(OptionSpec("-o", "short"), OptionSpec("--output-format", "short"), OptionSpec("-p", "short"), OptionSpec("--input-format", "short"), OptionSpec("-P"), OptionSpec("--prettyPrint"), OptionSpec("-N"), OptionSpec("--no-doc"), OptionSpec("--unwrapScalar", "short"), OptionSpec("--colors", "short")),
        positionals=("safe",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        allow_stdin=True,
        tags=frozenset(("data",)),
        description="yq.eval",
    ),
    OperationSpec(
        logical_name="yq.eval_all",
        executable_key="yq",
        subcommand="eval-all",
        options=(OptionSpec("-o", "short"), OptionSpec("-p", "short"), OptionSpec("-P"), OptionSpec("-N")),
        positionals=("safe",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        allow_stdin=True,
        tags=frozenset(("data",)),
        description="yq.eval_all",
    ),
    OperationSpec(
        logical_name="yq.properties",
        executable_key="yq",
        subcommand="eval",
        options=(OptionSpec("-o", "literal:props"), OptionSpec("-p", "short")),
        positionals=("safe",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        allow_stdin=True,
        tags=frozenset(("data",)),
        description="yq.properties",
    ),
    OperationSpec(
        logical_name="yq.json",
        executable_key="yq",
        subcommand="eval",
        options=(OptionSpec("-o", "literal:json"), OptionSpec("-I", "integer")),
        positionals=("safe",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        allow_stdin=True,
        tags=frozenset(("data",)),
        description="yq.json",
    ),
    OperationSpec(
        logical_name="rg.search",
        executable_key="rg",
        options=(OptionSpec("-n"), OptionSpec("--line-number"), OptionSpec("-i"), OptionSpec("--ignore-case"), OptionSpec("-F"), OptionSpec("--fixed-strings"), OptionSpec("-S"), OptionSpec("--smart-case"), OptionSpec("-w"), OptionSpec("--word-regexp"), OptionSpec("-l"), OptionSpec("--files-with-matches"), OptionSpec("-c"), OptionSpec("--count"), OptionSpec("--hidden"), OptionSpec("--no-ignore"), OptionSpec("-g", "short", True), OptionSpec("--glob", "short", True), OptionSpec("-t", "short", True), OptionSpec("--type", "short", True), OptionSpec("-T", "short", True), OptionSpec("--type-not", "short", True), OptionSpec("--max-count", "integer"), OptionSpec("--max-depth", "integer")),
        positionals=("safe",),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="rg.search",
    ),
    OperationSpec(
        logical_name="rg.files",
        executable_key="rg",
        fixed_prefix=("--files",),
        options=(OptionSpec("--hidden"), OptionSpec("--no-ignore"), OptionSpec("-g", "short", True), OptionSpec("--glob", "short", True), OptionSpec("-t", "short", True), OptionSpec("-T", "short", True), OptionSpec("--max-depth", "integer")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("data",)),
        description="rg.files",
    ),
    OperationSpec(
        logical_name="rg.files_with_matches",
        executable_key="rg",
        options=(OptionSpec("-l"), OptionSpec("--files-with-matches"), OptionSpec("-i"), OptionSpec("-F"), OptionSpec("-g", "short", True)),
        positionals=("safe",),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="rg.files_with_matches",
    ),
    OperationSpec(
        logical_name="rg.count",
        executable_key="rg",
        options=(OptionSpec("-c"), OptionSpec("--count"), OptionSpec("-i"), OptionSpec("-F"), OptionSpec("-g", "short", True)),
        positionals=("safe",),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="rg.count",
    ),
    OperationSpec(
        logical_name="rg.json",
        executable_key="rg",
        options=(OptionSpec("--json"), OptionSpec("-i"), OptionSpec("-F"), OptionSpec("-g", "short", True)),
        positionals=("safe",),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="rg.json",
    ),
    OperationSpec(
        logical_name="fd.search",
        executable_key="fd",
        options=(OptionSpec("-H"), OptionSpec("--hidden"), OptionSpec("-I"), OptionSpec("--no-ignore"), OptionSpec("-a"), OptionSpec("--absolute-path"), OptionSpec("-p"), OptionSpec("--full-path"), OptionSpec("-i"), OptionSpec("--ignore-case"), OptionSpec("-s"), OptionSpec("--case-sensitive"), OptionSpec("-d", "integer"), OptionSpec("--max-depth", "integer"), OptionSpec("--min-depth", "integer"), OptionSpec("-t", "short", True), OptionSpec("--type", "short", True), OptionSpec("-e", "short", True), OptionSpec("--extension", "short", True), OptionSpec("-E", "short", True), OptionSpec("--exclude", "short", True)),
        variadic="safe",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="fd.search",
    ),
    OperationSpec(
        logical_name="fd.files",
        executable_key="fd",
        options=(OptionSpec("-t", "literal:f"), OptionSpec("-e", "short", True), OptionSpec("-d", "integer"), OptionSpec("-H"), OptionSpec("-I"), OptionSpec("-E", "short", True)),
        variadic="safe",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="fd.files",
    ),
    OperationSpec(
        logical_name="fd.directories",
        executable_key="fd",
        options=(OptionSpec("-t", "literal:d"), OptionSpec("-d", "integer"), OptionSpec("-H"), OptionSpec("-I"), OptionSpec("-E", "short", True)),
        variadic="safe",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="fd.directories",
    ),
    OperationSpec(
        logical_name="fd.symlinks",
        executable_key="fd",
        options=(OptionSpec("-t", "literal:l"), OptionSpec("-d", "integer"), OptionSpec("-H"), OptionSpec("-I"), OptionSpec("-E", "short", True)),
        variadic="safe",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="fd.symlinks",
    ),
    OperationSpec(
        logical_name="tree.list",
        executable_key="tree",
        options=(OptionSpec("-a"), OptionSpec("-d"), OptionSpec("-L", "integer"), OptionSpec("-I", "short"), OptionSpec("-P", "short"), OptionSpec("--dirsfirst"), OptionSpec("--filelimit", "integer"), OptionSpec("--du"), OptionSpec("--prune"), OptionSpec("--noreport")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("data",)),
        description="tree.list",
    ),
    OperationSpec(
        logical_name="tree.json",
        executable_key="tree",
        options=(OptionSpec("-J"), OptionSpec("-a"), OptionSpec("-d"), OptionSpec("-L", "integer"), OptionSpec("-I", "short"), OptionSpec("--noreport")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("data",)),
        description="tree.json",
    ),
    OperationSpec(
        logical_name="tree.xml",
        executable_key="tree",
        options=(OptionSpec("-X"), OptionSpec("-a"), OptionSpec("-d"), OptionSpec("-L", "integer"), OptionSpec("-I", "short"), OptionSpec("--noreport")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("data",)),
        description="tree.xml",
    ),
    OperationSpec(
        logical_name="xmllint.format",
        executable_key="xmllint",
        options=(OptionSpec("--format"), OptionSpec("--noblanks"), OptionSpec("--noout"), OptionSpec("--recover"), OptionSpec("--nonet")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="xmllint.format",
    ),
    OperationSpec(
        logical_name="xmllint.xpath",
        executable_key="xmllint",
        options=(OptionSpec("--xpath", "safe"), OptionSpec("--nonet"), OptionSpec("--nowarning")),
        positionals=("safe",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="xmllint.xpath",
    ),
    OperationSpec(
        logical_name="xmllint.validate",
        executable_key="xmllint",
        options=(OptionSpec("--noout"), OptionSpec("--nonet"), OptionSpec("--schema", "path"), OptionSpec("--dtdvalid", "path")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        allow_nonzero_success=True,
        tags=frozenset(("data",)),
        description="xmllint.validate",
    ),
    OperationSpec(
        logical_name="cloc.count",
        executable_key="cloc",
        options=(OptionSpec("--by-file"), OptionSpec("--by-file-by-lang"), OptionSpec("--json"), OptionSpec("--yaml"), OptionSpec("--xml"), OptionSpec("--csv"), OptionSpec("--exclude-dir", "short"), OptionSpec("--include-ext", "short"), OptionSpec("--exclude-ext", "short"), OptionSpec("--max-file-size", "integer")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("data",)),
        description="cloc.count",
    ),
    OperationSpec(
        logical_name="scc.count",
        executable_key="scc",
        options=(OptionSpec("--by-file"), OptionSpec("--format", "short"), OptionSpec("--include-ext", "short"), OptionSpec("--exclude-ext", "short"), OptionSpec("--exclude-dir", "short"), OptionSpec("--no-cocomo")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("data",)),
        description="scc.count",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS


DENIED_MUTATION_FLAGS = frozenset({
    "yq:-i", "yq:--inplace", "fd:-x", "fd:--exec", "fd:-X", "fd:--exec-batch",
    "rg:--pre", "rg:--pre-glob",
})
