""".NET ecosystem logical command contracts."""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="dotnet.info",
        executable_key="dotnet",
        subcommand="--info",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.info",
    ),
    OperationSpec(
        logical_name="dotnet.version",
        executable_key="dotnet",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.version",
    ),
    OperationSpec(
        logical_name="dotnet.restore",
        executable_key="dotnet",
        subcommand="restore",
        options=(OptionSpec("--locked-mode"), OptionSpec("--force-evaluate"), OptionSpec("--no-cache"), OptionSpec("--ignore-failed-sources"), OptionSpec("--packages", "path"), OptionSpec("--runtime", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=1200.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.restore",
    ),
    OperationSpec(
        logical_name="dotnet.build",
        executable_key="dotnet",
        subcommand="build",
        options=(OptionSpec("--no-restore"), OptionSpec("--configuration", "short"), OptionSpec("--framework", "short"), OptionSpec("--runtime", "short"), OptionSpec("--output", "path"), OptionSpec("--verbosity", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.build",
    ),
    OperationSpec(
        logical_name="dotnet.test",
        executable_key="dotnet",
        subcommand="test",
        options=(OptionSpec("--no-restore"), OptionSpec("--no-build"), OptionSpec("--configuration", "short"), OptionSpec("--framework", "short"), OptionSpec("--filter", "safe"), OptionSpec("--logger", "safe"), OptionSpec("--collect", "safe"), OptionSpec("--results-directory", "path")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.test",
    ),
    OperationSpec(
        logical_name="dotnet.format_check",
        executable_key="dotnet",
        subcommand="format",
        options=(OptionSpec("--verify-no-changes"), OptionSpec("--no-restore"), OptionSpec("--severity", "short"), OptionSpec("--include", "path", True), OptionSpec("--exclude", "path", True)),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.FORMAT, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        allow_nonzero_success=True,
        tags=frozenset(("dotnet",)),
        description="dotnet.format_check",
    ),
    OperationSpec(
        logical_name="dotnet.format_write",
        executable_key="dotnet",
        subcommand="format",
        options=(OptionSpec("--no-restore"), OptionSpec("--severity", "short"), OptionSpec("--include", "path", True), OptionSpec("--exclude", "path", True)),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.FORMAT, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=900.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.format_write",
    ),
    OperationSpec(
        logical_name="dotnet.pack",
        executable_key="dotnet",
        subcommand="pack",
        options=(OptionSpec("--no-build"), OptionSpec("--no-restore"), OptionSpec("--configuration", "short"), OptionSpec("--output", "path"), OptionSpec("--include-symbols"), OptionSpec("--include-source")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.pack",
    ),
    OperationSpec(
        logical_name="dotnet.publish",
        executable_key="dotnet",
        subcommand="publish",
        options=(OptionSpec("--no-build"), OptionSpec("--no-restore"), OptionSpec("--configuration", "short"), OptionSpec("--framework", "short"), OptionSpec("--runtime", "short"), OptionSpec("--output", "path"), OptionSpec("--self-contained", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=1800.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.publish",
    ),
    OperationSpec(
        logical_name="dotnet.clean",
        executable_key="dotnet",
        subcommand="clean",
        options=(OptionSpec("--configuration", "short"), OptionSpec("--framework", "short"), OptionSpec("--runtime", "short"), OptionSpec("--verbosity", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=600.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.clean",
    ),
    OperationSpec(
        logical_name="dotnet.list_package",
        executable_key="dotnet",
        subcommand="list",
        options=(OptionSpec("--include-transitive"), OptionSpec("--outdated"), OptionSpec("--vulnerable"), OptionSpec("--deprecated"), OptionSpec("--format", "short")),
        positionals=("path", "literal:package"),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        allow_nonzero_success=True,
        tags=frozenset(("dotnet",)),
        description="dotnet.list_package",
    ),
    OperationSpec(
        logical_name="dotnet.add_package",
        executable_key="dotnet",
        subcommand="add",
        options=(OptionSpec("--version", "short"), OptionSpec("--framework", "short"), OptionSpec("--no-restore"), OptionSpec("--source", "https")),
        positionals=("path", "literal:package", "package"),
        min_positionals=4,
        max_positionals=4,
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE, CommandEffect.NETWORK}),
        risk=CommandRisk.HIGH,
        timeout=900.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.add_package",
    ),
    OperationSpec(
        logical_name="dotnet.remove_package",
        executable_key="dotnet",
        subcommand="remove",
        positionals=("path", "literal:package", "package"),
        min_positionals=4,
        max_positionals=4,
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.remove_package",
    ),
    OperationSpec(
        logical_name="dotnet.tool_list",
        executable_key="dotnet",
        subcommand="tool",
        options=(OptionSpec("--global"), OptionSpec("--local")),
        positionals=("literal:list",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.tool_list",
    ),
    OperationSpec(
        logical_name="dotnet.tool_restore",
        executable_key="dotnet",
        subcommand="tool",
        positionals=("literal:restore",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=900.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.tool_restore",
    ),
    OperationSpec(
        logical_name="dotnet.nuget_list_source",
        executable_key="dotnet",
        subcommand="nuget",
        positionals=("literal:list", "literal:source"),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.nuget_list_source",
    ),
    OperationSpec(
        logical_name="dotnet.sln_list",
        executable_key="dotnet",
        subcommand="sln",
        positionals=("path", "literal:list"),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.sln_list",
    ),
    OperationSpec(
        logical_name="dotnet.sln_add",
        executable_key="dotnet",
        subcommand="sln",
        positionals=("path", "literal:add"),
        variadic="path",
        min_positionals=3,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.sln_add",
    ),
    OperationSpec(
        logical_name="dotnet.sln_remove",
        executable_key="dotnet",
        subcommand="sln",
        positionals=("path", "literal:remove"),
        variadic="path",
        min_positionals=3,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.sln_remove",
    ),
    OperationSpec(
        logical_name="dotnet.msbuild",
        executable_key="dotnet",
        subcommand="msbuild",
        options=(OptionSpec("-t", "short"), OptionSpec("-p", "safe", True), OptionSpec("-m"), OptionSpec("-v", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.msbuild",
    ),
    OperationSpec(
        logical_name="dotnet.new_list",
        executable_key="dotnet",
        subcommand="new",
        positionals=("short",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.new_list",
    ),
    OperationSpec(
        logical_name="dotnet.new_create",
        executable_key="dotnet",
        subcommand="new",
        options=(OptionSpec("--output", "path"), OptionSpec("--name", "identifier"), OptionSpec("--framework", "short")),
        positionals=("identifier",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("dotnet",)),
        description="dotnet.new_create",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS
