"""Git logical command contracts."""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="git.version",
        executable_key="git",
        subcommand="--version",
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.version",
    ),
    OperationSpec(
        logical_name="git.status",
        executable_key="git",
        subcommand="status",
        options=(OptionSpec("--short"), OptionSpec("--branch"), OptionSpec("--porcelain", "short"), OptionSpec("--untracked-files", "short")),
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.status",
    ),
    OperationSpec(
        logical_name="git.diff",
        executable_key="git",
        subcommand="diff",
        options=(OptionSpec("--stat"), OptionSpec("--name-only"), OptionSpec("--name-status"), OptionSpec("--cached"), OptionSpec("--check"), OptionSpec("--color", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.diff",
    ),
    OperationSpec(
        logical_name="git.diff_word",
        executable_key="git",
        subcommand="diff",
        options=(OptionSpec("--word-diff", "short"), OptionSpec("--word-diff-regex", "safe"), OptionSpec("--cached")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.diff_word",
    ),
    OperationSpec(
        logical_name="git.show",
        executable_key="git",
        subcommand="show",
        options=(OptionSpec("--stat"), OptionSpec("--name-only"), OptionSpec("--format", "safe")),
        positionals=("git_ref",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.show",
    ),
    OperationSpec(
        logical_name="git.log",
        executable_key="git",
        subcommand="log",
        options=(OptionSpec("--oneline"), OptionSpec("--decorate"), OptionSpec("--graph"), OptionSpec("--max-count", "integer"), OptionSpec("--format", "safe"), OptionSpec("--since", "short"), OptionSpec("--until", "short")),
        variadic="git_ref",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.log",
    ),
    OperationSpec(
        logical_name="git.log_paths",
        executable_key="git",
        subcommand="log",
        options=(OptionSpec("--oneline"), OptionSpec("--follow"), OptionSpec("--max-count", "integer")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.log_paths",
    ),
    OperationSpec(
        logical_name="git.rev_parse",
        executable_key="git",
        subcommand="rev-parse",
        options=(OptionSpec("--verify"), OptionSpec("--short"), OptionSpec("--show-toplevel"), OptionSpec("--abbrev-ref")),
        variadic="git_ref",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.rev_parse",
    ),
    OperationSpec(
        logical_name="git.rev_list",
        executable_key="git",
        subcommand="rev-list",
        options=(OptionSpec("--count"), OptionSpec("--max-count", "integer"), OptionSpec("--all"), OptionSpec("--objects")),
        variadic="git_ref",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.rev_list",
    ),
    OperationSpec(
        logical_name="git.ls_files",
        executable_key="git",
        subcommand="ls-files",
        options=(OptionSpec("--cached"), OptionSpec("--modified"), OptionSpec("--deleted"), OptionSpec("--others"), OptionSpec("--exclude-standard"), OptionSpec("--stage")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.ls_files",
    ),
    OperationSpec(
        logical_name="git.ls_tree",
        executable_key="git",
        subcommand="ls-tree",
        options=(OptionSpec("-r"), OptionSpec("--name-only"), OptionSpec("--full-tree"), OptionSpec("-l")),
        positionals=("git_ref",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.ls_tree",
    ),
    OperationSpec(
        logical_name="git.grep",
        executable_key="git",
        subcommand="grep",
        options=(OptionSpec("-n"), OptionSpec("-i"), OptionSpec("-F"), OptionSpec("-E"), OptionSpec("--count"), OptionSpec("--files-with-matches")),
        positionals=("safe",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        allow_nonzero_success=True,
        tags=frozenset(("git",)),
        description="git.grep",
    ),
    OperationSpec(
        logical_name="git.branch_list",
        executable_key="git",
        subcommand="branch",
        options=(OptionSpec("--list"), OptionSpec("--all"), OptionSpec("--remotes"), OptionSpec("--contains", "git_ref"), OptionSpec("--merged", "git_ref"), OptionSpec("--format", "safe")),
        variadic="git_ref",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.branch_list",
    ),
    OperationSpec(
        logical_name="git.tag_list",
        executable_key="git",
        subcommand="tag",
        options=(OptionSpec("--list"), OptionSpec("--contains", "git_ref"), OptionSpec("--points-at", "git_ref"), OptionSpec("--sort", "short"), OptionSpec("--format", "safe")),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.tag_list",
    ),
    OperationSpec(
        logical_name="git.remote_list",
        executable_key="git",
        subcommand="remote",
        options=(OptionSpec("-v"), OptionSpec("--verbose")),
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.remote_list",
    ),
    OperationSpec(
        logical_name="git.remote_get_url",
        executable_key="git",
        subcommand="remote",
        positionals=("literal:get-url", "short"),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.remote_get_url",
    ),
    OperationSpec(
        logical_name="git.cat_file_type",
        executable_key="git",
        subcommand="cat-file",
        options=(OptionSpec("-t"),),
        positionals=("git_ref",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.cat_file_type",
    ),
    OperationSpec(
        logical_name="git.cat_file_size",
        executable_key="git",
        subcommand="cat-file",
        options=(OptionSpec("-s"),),
        positionals=("git_ref",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.cat_file_size",
    ),
    OperationSpec(
        logical_name="git.cat_file_pretty",
        executable_key="git",
        subcommand="cat-file",
        options=(OptionSpec("-p"),),
        positionals=("git_ref",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.cat_file_pretty",
    ),
    OperationSpec(
        logical_name="git.check_ignore",
        executable_key="git",
        subcommand="check-ignore",
        options=(OptionSpec("-v"), OptionSpec("--no-index"), OptionSpec("--stdin")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        allow_stdin=True,
        allow_nonzero_success=True,
        tags=frozenset(("git",)),
        description="git.check_ignore",
    ),
    OperationSpec(
        logical_name="git.check_attr",
        executable_key="git",
        subcommand="check-attr",
        options=(OptionSpec("-a"), OptionSpec("--all"), OptionSpec("--cached")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.check_attr",
    ),
    OperationSpec(
        logical_name="git.describe",
        executable_key="git",
        subcommand="describe",
        options=(OptionSpec("--tags"), OptionSpec("--always"), OptionSpec("--dirty"), OptionSpec("--abbrev", "integer")),
        variadic="git_ref",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.describe",
    ),
    OperationSpec(
        logical_name="git.merge_base",
        executable_key="git",
        subcommand="merge-base",
        options=(OptionSpec("--all"), OptionSpec("--is-ancestor")),
        positionals=("git_ref", "git_ref"),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        allow_nonzero_success=True,
        tags=frozenset(("git",)),
        description="git.merge_base",
    ),
    OperationSpec(
        logical_name="git.name_rev",
        executable_key="git",
        subcommand="name-rev",
        options=(OptionSpec("--name-only"), OptionSpec("--tags"), OptionSpec("--refs", "safe")),
        variadic="git_ref",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.name_rev",
    ),
    OperationSpec(
        logical_name="git.add",
        executable_key="git",
        subcommand="add",
        options=(OptionSpec("--intent-to-add"), OptionSpec("--update"), OptionSpec("--all"), OptionSpec("--dry-run"), OptionSpec("--verbose")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.add",
    ),
    OperationSpec(
        logical_name="git.restore",
        executable_key="git",
        subcommand="restore",
        options=(OptionSpec("--staged"), OptionSpec("--worktree"), OptionSpec("--source", "git_ref"), OptionSpec("--patch")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.restore",
    ),
    OperationSpec(
        logical_name="git.switch",
        executable_key="git",
        subcommand="switch",
        options=(OptionSpec("--create", "git_ref"), OptionSpec("--detach"), OptionSpec("--force-create", "git_ref")),
        positionals=("git_ref",),
        min_positionals=1,
        max_positionals=2,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.switch",
    ),
    OperationSpec(
        logical_name="git.branch_create",
        executable_key="git",
        subcommand="branch",
        positionals=("git_ref",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.branch_create",
    ),
    OperationSpec(
        logical_name="git.branch_delete",
        executable_key="git",
        subcommand="branch",
        options=(OptionSpec("-d"), OptionSpec("--delete")),
        variadic="git_ref",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.branch_delete",
    ),
    OperationSpec(
        logical_name="git.tag_create",
        executable_key="git",
        subcommand="tag",
        options=(OptionSpec("-a"), OptionSpec("-m", "safe"), OptionSpec("--force")),
        positionals=("git_ref",),
        variadic="git_ref",
        min_positionals=2,
        max_positionals=3,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.tag_create",
    ),
    OperationSpec(
        logical_name="git.tag_delete",
        executable_key="git",
        subcommand="tag",
        options=(OptionSpec("-d"), OptionSpec("--delete")),
        variadic="git_ref",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.tag_delete",
    ),
    OperationSpec(
        logical_name="git.commit",
        executable_key="git",
        subcommand="commit",
        options=(OptionSpec("-m", "safe"), OptionSpec("--message", "safe"), OptionSpec("--allow-empty"), OptionSpec("--amend"), OptionSpec("--no-edit")),
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        env_keys=("GIT_AUTHOR_NAME", "GIT_AUTHOR_EMAIL", "GIT_COMMITTER_NAME", "GIT_COMMITTER_EMAIL"),
        tags=frozenset(("git",)),
        description="git.commit",
    ),
    OperationSpec(
        logical_name="git.merge",
        executable_key="git",
        subcommand="merge",
        options=(OptionSpec("--no-ff"), OptionSpec("--ff-only"), OptionSpec("--no-commit"), OptionSpec("--squash"), OptionSpec("--strategy", "short")),
        positionals=("git_ref",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.merge",
    ),
    OperationSpec(
        logical_name="git.rebase",
        executable_key="git",
        subcommand="rebase",
        options=(OptionSpec("--onto", "git_ref"), OptionSpec("--continue"), OptionSpec("--abort"), OptionSpec("--skip")),
        variadic="git_ref",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.rebase",
    ),
    OperationSpec(
        logical_name="git.cherry_pick",
        executable_key="git",
        subcommand="cherry-pick",
        options=(OptionSpec("--no-commit"), OptionSpec("--continue"), OptionSpec("--abort")),
        variadic="git_ref",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.cherry_pick",
    ),
    OperationSpec(
        logical_name="git.revert",
        executable_key="git",
        subcommand="revert",
        options=(OptionSpec("--no-commit"), OptionSpec("--continue"), OptionSpec("--abort")),
        variadic="git_ref",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.revert",
    ),
    OperationSpec(
        logical_name="git.fetch",
        executable_key="git",
        subcommand="fetch",
        options=(OptionSpec("--all"), OptionSpec("--prune"), OptionSpec("--tags"), OptionSpec("--depth", "integer"), OptionSpec("--force")),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=300.0,
        tags=frozenset(("git",)),
        description="git.fetch",
    ),
    OperationSpec(
        logical_name="git.pull_ff_only",
        executable_key="git",
        subcommand="pull",
        options=(OptionSpec("--ff-only"), OptionSpec("--rebase")),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=300.0,
        tags=frozenset(("git",)),
        description="git.pull_ff_only",
    ),
    OperationSpec(
        logical_name="git.push",
        executable_key="git",
        subcommand="push",
        options=(OptionSpec("--set-upstream"), OptionSpec("--tags"), OptionSpec("--follow-tags"), OptionSpec("--dry-run")),
        variadic="git_ref",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=300.0,
        tags=frozenset(("git",)),
        description="git.push",
    ),
    OperationSpec(
        logical_name="git.clean_dry_run",
        executable_key="git",
        subcommand="clean",
        options=(OptionSpec("-n"), OptionSpec("--dry-run"), OptionSpec("-d"), OptionSpec("-x"), OptionSpec("-X")),
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.clean_dry_run",
    ),
    OperationSpec(
        logical_name="git.clean",
        executable_key="git",
        subcommand="clean",
        options=(OptionSpec("-f"), OptionSpec("--force"), OptionSpec("-d"), OptionSpec("-x"), OptionSpec("-X")),
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.clean",
    ),
    OperationSpec(
        logical_name="git.worktree_list",
        executable_key="git",
        subcommand="worktree",
        positionals=("literal:list",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.worktree_list",
    ),
    OperationSpec(
        logical_name="git.worktree_add",
        executable_key="git",
        subcommand="worktree",
        positionals=("literal:add", "path"),
        variadic="git_ref",
        min_positionals=3,
        max_positionals=4,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.worktree_add",
    ),
    OperationSpec(
        logical_name="git.worktree_remove",
        executable_key="git",
        subcommand="worktree",
        options=(OptionSpec("--force"),),
        positionals=("literal:remove", "path"),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.worktree_remove",
    ),
    OperationSpec(
        logical_name="git.submodule_status",
        executable_key="git",
        subcommand="submodule",
        positionals=("literal:status",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.submodule_status",
    ),
    OperationSpec(
        logical_name="git.submodule_update",
        executable_key="git",
        subcommand="submodule",
        options=(OptionSpec("--init"), OptionSpec("--recursive"), OptionSpec("--depth", "integer")),
        positionals=("literal:update",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=600.0,
        tags=frozenset(("git",)),
        description="git.submodule_update",
    ),
    OperationSpec(
        logical_name="git.stash_list",
        executable_key="git",
        subcommand="stash",
        positionals=("literal:list",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.stash_list",
    ),
    OperationSpec(
        logical_name="git.stash_show",
        executable_key="git",
        subcommand="stash",
        options=(OptionSpec("--stat"), OptionSpec("--patch")),
        positionals=("literal:show",),
        variadic="git_ref",
        min_positionals=2,
        max_positionals=3,
        effects=frozenset({CommandEffect.SOURCE_CONTROL, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.stash_show",
    ),
    OperationSpec(
        logical_name="git.stash_push",
        executable_key="git",
        subcommand="stash",
        options=(OptionSpec("--include-untracked"), OptionSpec("--keep-index"), OptionSpec("-m", "safe")),
        positionals=("literal:push",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.stash_push",
    ),
    OperationSpec(
        logical_name="git.stash_pop",
        executable_key="git",
        subcommand="stash",
        positionals=("literal:pop",),
        variadic="git_ref",
        min_positionals=2,
        max_positionals=3,
        effects=frozenset({CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=60.0,
        tags=frozenset(("git",)),
        description="git.stash_pop",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS
