"""Go ecosystem logical command contracts."""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="go.env",
        executable_key="go",
        subcommand="env",
        variadic="identifier",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("go",)),
        description="go.env",
    ),
    OperationSpec(
        logical_name="go.version",
        executable_key="go",
        subcommand="version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("go",)),
        description="go.version",
    ),
    OperationSpec(
        logical_name="go.list",
        executable_key="go",
        subcommand="list",
        options=(OptionSpec("-json"), OptionSpec("-m"), OptionSpec("-deps"), OptionSpec("-test"), OptionSpec("-f", "safe")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("go",)),
        description="go.list",
    ),
    OperationSpec(
        logical_name="go.mod_download",
        executable_key="go",
        fixed_prefix=("mod", "download"),
        options=(OptionSpec("-json"), OptionSpec("-x")),
        variadic="package",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        tags=frozenset(("go",)),
        description="go.mod_download",
    ),
    OperationSpec(
        logical_name="go.mod_tidy",
        executable_key="go",
        fixed_prefix=("mod", "tidy"),
        options=(OptionSpec("-v"), OptionSpec("-e"), OptionSpec("-compat", "short")),
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=900.0,
        tags=frozenset(("go",)),
        description="go.mod_tidy",
    ),
    OperationSpec(
        logical_name="go.mod_verify",
        executable_key="go",
        fixed_prefix=("mod", "verify"),
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        allow_nonzero_success=True,
        tags=frozenset(("go",)),
        description="go.mod_verify",
    ),
    OperationSpec(
        logical_name="go.mod_graph",
        executable_key="go",
        fixed_prefix=("mod", "graph"),
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        tags=frozenset(("go",)),
        description="go.mod_graph",
    ),
    OperationSpec(
        logical_name="go.mod_why",
        executable_key="go",
        fixed_prefix=("mod", "why"),
        options=(OptionSpec("-m"), OptionSpec("-vendor")),
        variadic="package",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("go",)),
        description="go.mod_why",
    ),
    OperationSpec(
        logical_name="go.work_sync",
        executable_key="go",
        fixed_prefix=("work", "sync"),
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=600.0,
        tags=frozenset(("go",)),
        description="go.work_sync",
    ),
    OperationSpec(
        logical_name="go.work_use",
        executable_key="go",
        fixed_prefix=("work", "use"),
        options=(OptionSpec("-r"),),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=60.0,
        tags=frozenset(("go",)),
        description="go.work_use",
    ),
    OperationSpec(
        logical_name="go.fmt",
        executable_key="gofmt",
        options=(OptionSpec("-w"), OptionSpec("-s")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.FORMAT, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=300.0,
        tags=frozenset(("go",)),
        description="go.fmt",
    ),
    OperationSpec(
        logical_name="go.fmt_check",
        executable_key="gofmt",
        options=(OptionSpec("-d"), OptionSpec("-s")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.FORMAT}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        allow_nonzero_success=True,
        tags=frozenset(("go",)),
        description="go.fmt_check",
    ),
    OperationSpec(
        logical_name="go.test",
        executable_key="go",
        subcommand="test",
        options=(OptionSpec("-v"), OptionSpec("-race"), OptionSpec("-count", "integer"), OptionSpec("-run", "safe"), OptionSpec("-bench", "safe"), OptionSpec("-cover"), OptionSpec("-coverprofile", "path"), OptionSpec("-timeout", "short"), OptionSpec("-tags", "short")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("go",)),
        description="go.test",
    ),
    OperationSpec(
        logical_name="go.test_short",
        executable_key="go",
        subcommand="test",
        options=(OptionSpec("-short"), OptionSpec("-v"), OptionSpec("-count", "integer")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        tags=frozenset(("go",)),
        description="go.test_short",
    ),
    OperationSpec(
        logical_name="go.vet",
        executable_key="go",
        subcommand="vet",
        options=(OptionSpec("-json"), OptionSpec("-tags", "short")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.LINT, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        allow_nonzero_success=True,
        tags=frozenset(("go",)),
        description="go.vet",
    ),
    OperationSpec(
        logical_name="go.build",
        executable_key="go",
        subcommand="build",
        options=(OptionSpec("-v"), OptionSpec("-race"), OptionSpec("-trimpath"), OptionSpec("-tags", "short"), OptionSpec("-o", "path")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("go",)),
        description="go.build",
    ),
    OperationSpec(
        logical_name="go.install",
        executable_key="go",
        subcommand="install",
        options=(OptionSpec("-v"), OptionSpec("-race"), OptionSpec("-trimpath"), OptionSpec("-tags", "short")),
        variadic="package",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.PACKAGE, CommandEffect.WRITE, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=1800.0,
        tags=frozenset(("go",)),
        description="go.install",
    ),
    OperationSpec(
        logical_name="go.run",
        executable_key="go",
        subcommand="run",
        options=(OptionSpec("-race"), OptionSpec("-trimpath"), OptionSpec("-tags", "short")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.PROCESS, CommandEffect.BUILD}),
        risk=CommandRisk.MODERATE,
        timeout=1800.0,
        tags=frozenset(("go",)),
        description="go.run",
    ),
    OperationSpec(
        logical_name="go.generate",
        executable_key="go",
        subcommand="generate",
        options=(OptionSpec("-run", "safe"), OptionSpec("-skip", "safe")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.PROCESS, CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=1800.0,
        tags=frozenset(("go",)),
        description="go.generate",
    ),
    OperationSpec(
        logical_name="go.clean",
        executable_key="go",
        subcommand="clean",
        options=(OptionSpec("-cache"), OptionSpec("-testcache"), OptionSpec("-modcache"), OptionSpec("-fuzzcache")),
        effects=frozenset({CommandEffect.WRITE, CommandEffect.BUILD}),
        risk=CommandRisk.HIGH,
        timeout=600.0,
        tags=frozenset(("go",)),
        description="go.clean",
    ),
    OperationSpec(
        logical_name="go.doc",
        executable_key="go",
        subcommand="doc",
        options=(OptionSpec("-all"), OptionSpec("-short"), OptionSpec("-src"), OptionSpec("-u")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("go",)),
        description="go.doc",
    ),
    OperationSpec(
        logical_name="go.tool_cover",
        executable_key="go",
        fixed_prefix=("tool", "cover"),
        options=(OptionSpec("-func", "path"), OptionSpec("-html", "path"), OptionSpec("-o", "path")),
        effects=frozenset({CommandEffect.TEST, CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        tags=frozenset(("go",)),
        description="go.tool_cover",
    ),
    OperationSpec(
        logical_name="go.tool_pprof",
        executable_key="go",
        fixed_prefix=("tool", "pprof"),
        options=(OptionSpec("-top"), OptionSpec("-text"), OptionSpec("-json"), OptionSpec("-nodecount", "integer")),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        tags=frozenset(("go",)),
        description="go.tool_pprof",
    ),
    OperationSpec(
        logical_name="go.benchstat",
        executable_key="benchstat",
        options=(OptionSpec("-row", "safe"), OptionSpec("-col", "safe"), OptionSpec("-filter", "safe")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        tags=frozenset(("go",)),
        description="go.benchstat",
    ),
    OperationSpec(
        logical_name="go.staticcheck",
        executable_key="staticcheck",
        options=(OptionSpec("-checks", "short"), OptionSpec("-fail", "short"), OptionSpec("-tags", "short")),
        variadic="safe",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        allow_nonzero_success=True,
        tags=frozenset(("go",)),
        description="go.staticcheck",
    ),
    OperationSpec(
        logical_name="go.govulncheck",
        executable_key="govulncheck",
        options=(OptionSpec("-json"), OptionSpec("-mode", "short"), OptionSpec("-scan", "short")),
        variadic="safe",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.LINT, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        allow_nonzero_success=True,
        tags=frozenset(("go",)),
        description="go.govulncheck",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS
