"""Infrastructure planning and read-mostly operational command contracts.

This surface intentionally omits Terraform/OpenTofu apply/destroy, kubectl
create/apply/delete/patch/exec/port-forward, and Helm install/upgrade/uninstall.
Those operations require a separate explicit authority design.
"""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="terraform.version",
        executable_key="terraform",
        subcommand="version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "terraform")),
        description="terraform.version",
    ),
    OperationSpec(
        logical_name="tofu.version",
        executable_key="tofu",
        subcommand="version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.version",
    ),
    OperationSpec(
        logical_name="terraform.validate",
        executable_key="terraform",
        subcommand="validate",
        options=(OptionSpec("-json"), OptionSpec("-no-color")),
        effects=frozenset({CommandEffect.READ, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "terraform")),
        description="terraform.validate",
    ),
    OperationSpec(
        logical_name="tofu.validate",
        executable_key="tofu",
        subcommand="validate",
        options=(OptionSpec("-json"), OptionSpec("-no-color")),
        effects=frozenset({CommandEffect.READ, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.validate",
    ),
    OperationSpec(
        logical_name="terraform.fmt_check",
        executable_key="terraform",
        subcommand="fmt",
        options=(OptionSpec("-check"), OptionSpec("-diff"), OptionSpec("-recursive"), OptionSpec("-no-color")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.FORMAT}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "terraform")),
        description="terraform.fmt_check",
    ),
    OperationSpec(
        logical_name="tofu.fmt_check",
        executable_key="tofu",
        subcommand="fmt",
        options=(OptionSpec("-check"), OptionSpec("-diff"), OptionSpec("-recursive"), OptionSpec("-no-color")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.FORMAT}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.fmt_check",
    ),
    OperationSpec(
        logical_name="terraform.providers",
        executable_key="terraform",
        subcommand="providers",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "terraform")),
        description="terraform.providers",
    ),
    OperationSpec(
        logical_name="tofu.providers",
        executable_key="tofu",
        subcommand="providers",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.providers",
    ),
    OperationSpec(
        logical_name="terraform.providers_lock",
        executable_key="terraform",
        fixed_prefix=("providers", "lock"),
        options=(OptionSpec("-platform", "short", True), OptionSpec("-fs-mirror", "path"), OptionSpec("-net-mirror", "https")),
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=600,
        tags=frozenset(("infra", "terraform")),
        description="terraform.providers_lock",
    ),
    OperationSpec(
        logical_name="tofu.providers_lock",
        executable_key="tofu",
        fixed_prefix=("providers", "lock"),
        options=(OptionSpec("-platform", "short", True), OptionSpec("-fs-mirror", "path"), OptionSpec("-net-mirror", "https")),
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=600,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.providers_lock",
    ),
    OperationSpec(
        logical_name="terraform.providers_schema",
        executable_key="terraform",
        fixed_prefix=("providers", "schema"),
        options=(OptionSpec("-json"),),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "terraform")),
        description="terraform.providers_schema",
    ),
    OperationSpec(
        logical_name="tofu.providers_schema",
        executable_key="tofu",
        fixed_prefix=("providers", "schema"),
        options=(OptionSpec("-json"),),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.providers_schema",
    ),
    OperationSpec(
        logical_name="terraform.workspace_list",
        executable_key="terraform",
        fixed_prefix=("workspace", "list"),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "terraform")),
        description="terraform.workspace_list",
    ),
    OperationSpec(
        logical_name="tofu.workspace_list",
        executable_key="tofu",
        fixed_prefix=("workspace", "list"),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.workspace_list",
    ),
    OperationSpec(
        logical_name="terraform.workspace_show",
        executable_key="terraform",
        fixed_prefix=("workspace", "show"),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "terraform")),
        description="terraform.workspace_show",
    ),
    OperationSpec(
        logical_name="tofu.workspace_show",
        executable_key="tofu",
        fixed_prefix=("workspace", "show"),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.workspace_show",
    ),
    OperationSpec(
        logical_name="terraform.state_list",
        executable_key="terraform",
        fixed_prefix=("state", "list"),
        variadic="safe",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "terraform")),
        description="terraform.state_list",
    ),
    OperationSpec(
        logical_name="tofu.state_list",
        executable_key="tofu",
        fixed_prefix=("state", "list"),
        variadic="safe",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.state_list",
    ),
    OperationSpec(
        logical_name="terraform.graph",
        executable_key="terraform",
        subcommand="graph",
        options=(OptionSpec("-type", "short"), OptionSpec("-draw-cycles")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "terraform")),
        description="terraform.graph",
    ),
    OperationSpec(
        logical_name="tofu.graph",
        executable_key="tofu",
        subcommand="graph",
        options=(OptionSpec("-type", "short"), OptionSpec("-draw-cycles")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "opentofu")),
        description="tofu.graph",
    ),
    OperationSpec(
        logical_name="terraform.plan",
        executable_key="terraform",
        subcommand="plan",
        options=(OptionSpec("-refresh-only"), OptionSpec("-destroy"), OptionSpec("-lock", "short"), OptionSpec("-lock-timeout", "short"), OptionSpec("-parallelism", "integer"), OptionSpec("-target", "safe", True), OptionSpec("-var", "safe", True), OptionSpec("-var-file", "path", True), OptionSpec("-no-color"), OptionSpec("-compact-warnings"), OptionSpec("-detailed-exitcode")),
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK, CommandEffect.BUILD}),
        risk=CommandRisk.MODERATE,
        timeout=1800,
        allow_nonzero_success=True,
        tags=frozenset(("infra", "terraform")),
        env_keys=("TF_IN_AUTOMATION", "TF_INPUT", "TF_LOG"),
        description="terraform.plan",
    ),
    OperationSpec(
        logical_name="tofu.plan",
        executable_key="tofu",
        subcommand="plan",
        options=(OptionSpec("-refresh-only"), OptionSpec("-destroy"), OptionSpec("-lock", "short"), OptionSpec("-lock-timeout", "short"), OptionSpec("-parallelism", "integer"), OptionSpec("-target", "safe", True), OptionSpec("-var", "safe", True), OptionSpec("-var-file", "path", True), OptionSpec("-no-color"), OptionSpec("-compact-warnings"), OptionSpec("-detailed-exitcode")),
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK, CommandEffect.BUILD}),
        risk=CommandRisk.MODERATE,
        timeout=1800,
        allow_nonzero_success=True,
        tags=frozenset(("infra", "opentofu")),
        env_keys=("TF_IN_AUTOMATION", "TF_INPUT", "TF_LOG"),
        description="tofu.plan",
    ),
    OperationSpec(
        logical_name="terraform.init_backend_false",
        executable_key="terraform",
        subcommand="init",
        options=(OptionSpec("-backend", "short"), OptionSpec("-get", "short"), OptionSpec("-upgrade"), OptionSpec("-lockfile", "short"), OptionSpec("-plugin-dir", "path", True), OptionSpec("-no-color")),
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=1200,
        tags=frozenset(("infra", "terraform")),
        env_keys=("TF_IN_AUTOMATION", "TF_INPUT"),
        description="terraform.init_backend_false",
    ),
    OperationSpec(
        logical_name="tofu.init_backend_false",
        executable_key="tofu",
        subcommand="init",
        options=(OptionSpec("-backend", "short"), OptionSpec("-get", "short"), OptionSpec("-upgrade"), OptionSpec("-lockfile", "short"), OptionSpec("-plugin-dir", "path", True), OptionSpec("-no-color")),
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=1200,
        tags=frozenset(("infra", "opentofu")),
        env_keys=("TF_IN_AUTOMATION", "TF_INPUT"),
        description="tofu.init_backend_false",
    ),
    OperationSpec(
        logical_name="terraform.test",
        executable_key="terraform",
        subcommand="test",
        options=(OptionSpec("-filter", "path", True), OptionSpec("-json"), OptionSpec("-no-color"), OptionSpec("-verbose")),
        effects=frozenset({CommandEffect.TEST, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=1800,
        tags=frozenset(("infra", "terraform")),
        env_keys=("TF_IN_AUTOMATION", "TF_INPUT"),
        description="terraform.test",
    ),
    OperationSpec(
        logical_name="tofu.test",
        executable_key="tofu",
        subcommand="test",
        options=(OptionSpec("-filter", "path", True), OptionSpec("-json"), OptionSpec("-no-color"), OptionSpec("-verbose")),
        effects=frozenset({CommandEffect.TEST, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=1800,
        tags=frozenset(("infra", "opentofu")),
        env_keys=("TF_IN_AUTOMATION", "TF_INPUT"),
        description="tofu.test",
    ),
    OperationSpec(
        logical_name="kubectl.version_client",
        executable_key="kubectl",
        subcommand="version",
        options=(OptionSpec("--client"), OptionSpec("--output", "short")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.version_client",
    ),
    OperationSpec(
        logical_name="kubectl.api_resources",
        executable_key="kubectl",
        subcommand="api-resources",
        options=(OptionSpec("--api-group", "short"), OptionSpec("--namespaced"), OptionSpec("--verbs", "short"), OptionSpec("--sort-by", "short"), OptionSpec("--output", "short")),
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.api_resources",
    ),
    OperationSpec(
        logical_name="kubectl.api_versions",
        executable_key="kubectl",
        subcommand="api-versions",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.api_versions",
    ),
    OperationSpec(
        logical_name="kubectl.cluster_info",
        executable_key="kubectl",
        subcommand="cluster-info",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=120,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.cluster_info",
    ),
    OperationSpec(
        logical_name="kubectl.current_context",
        executable_key="kubectl",
        fixed_prefix=("config", "current-context"),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.current_context",
    ),
    OperationSpec(
        logical_name="kubectl.get_contexts",
        executable_key="kubectl",
        fixed_prefix=("config", "get-contexts"),
        options=(OptionSpec("-o", "short"), OptionSpec("--no-headers")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_contexts",
    ),
    OperationSpec(
        logical_name="kubectl.auth_can_i",
        executable_key="kubectl",
        fixed_prefix=("auth", "can-i"),
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--list"), OptionSpec("--quiet")),
        variadic="short",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.auth_can_i",
    ),
    OperationSpec(
        logical_name="kubectl.explain",
        executable_key="kubectl",
        subcommand="explain",
        options=(OptionSpec("--api-version", "short"), OptionSpec("--recursive")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.explain",
    ),
    OperationSpec(
        logical_name="kubectl.top_pods",
        executable_key="kubectl",
        fixed_prefix=("top", "pods"),
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--containers"), OptionSpec("--no-headers"), OptionSpec("--sort-by", "short"), OptionSpec("--sum")),
        variadic="identifier",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=120,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.top_pods",
    ),
    OperationSpec(
        logical_name="kubectl.top_nodes",
        executable_key="kubectl",
        fixed_prefix=("top", "nodes"),
        options=(OptionSpec("--no-headers"), OptionSpec("--sort-by", "short"), OptionSpec("--selector", "safe")),
        variadic="identifier",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=120,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.top_nodes",
    ),
    OperationSpec(
        logical_name="kubectl.get_pods",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:pods",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_pods",
    ),
    OperationSpec(
        logical_name="kubectl.describe_pods",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:pods",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_pods",
    ),
    OperationSpec(
        logical_name="kubectl.get_deployments",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:deployments",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_deployments",
    ),
    OperationSpec(
        logical_name="kubectl.describe_deployments",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:deployments",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_deployments",
    ),
    OperationSpec(
        logical_name="kubectl.get_statefulsets",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:statefulsets",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_statefulsets",
    ),
    OperationSpec(
        logical_name="kubectl.describe_statefulsets",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:statefulsets",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_statefulsets",
    ),
    OperationSpec(
        logical_name="kubectl.get_daemonsets",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:daemonsets",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_daemonsets",
    ),
    OperationSpec(
        logical_name="kubectl.describe_daemonsets",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:daemonsets",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_daemonsets",
    ),
    OperationSpec(
        logical_name="kubectl.get_replicasets",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:replicasets",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_replicasets",
    ),
    OperationSpec(
        logical_name="kubectl.describe_replicasets",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:replicasets",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_replicasets",
    ),
    OperationSpec(
        logical_name="kubectl.get_services",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:services",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_services",
    ),
    OperationSpec(
        logical_name="kubectl.describe_services",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:services",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_services",
    ),
    OperationSpec(
        logical_name="kubectl.get_ingresses",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:ingresses",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_ingresses",
    ),
    OperationSpec(
        logical_name="kubectl.describe_ingresses",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:ingresses",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_ingresses",
    ),
    OperationSpec(
        logical_name="kubectl.get_jobs",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:jobs",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_jobs",
    ),
    OperationSpec(
        logical_name="kubectl.describe_jobs",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:jobs",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_jobs",
    ),
    OperationSpec(
        logical_name="kubectl.get_cronjobs",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:cronjobs",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_cronjobs",
    ),
    OperationSpec(
        logical_name="kubectl.describe_cronjobs",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:cronjobs",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_cronjobs",
    ),
    OperationSpec(
        logical_name="kubectl.get_configmaps",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:configmaps",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_configmaps",
    ),
    OperationSpec(
        logical_name="kubectl.describe_configmaps",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:configmaps",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_configmaps",
    ),
    OperationSpec(
        logical_name="kubectl.get_persistentvolumeclaims",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:persistentvolumeclaims",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_persistentvolumeclaims",
    ),
    OperationSpec(
        logical_name="kubectl.describe_persistentvolumeclaims",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:persistentvolumeclaims",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_persistentvolumeclaims",
    ),
    OperationSpec(
        logical_name="kubectl.get_persistentvolumes",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:persistentvolumes",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_persistentvolumes",
    ),
    OperationSpec(
        logical_name="kubectl.describe_persistentvolumes",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:persistentvolumes",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_persistentvolumes",
    ),
    OperationSpec(
        logical_name="kubectl.get_nodes",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:nodes",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_nodes",
    ),
    OperationSpec(
        logical_name="kubectl.describe_nodes",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:nodes",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_nodes",
    ),
    OperationSpec(
        logical_name="kubectl.get_namespaces",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:namespaces",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_namespaces",
    ),
    OperationSpec(
        logical_name="kubectl.describe_namespaces",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:namespaces",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_namespaces",
    ),
    OperationSpec(
        logical_name="kubectl.get_events",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:events",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_events",
    ),
    OperationSpec(
        logical_name="kubectl.describe_events",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:events",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_events",
    ),
    OperationSpec(
        logical_name="kubectl.get_serviceaccounts",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:serviceaccounts",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_serviceaccounts",
    ),
    OperationSpec(
        logical_name="kubectl.describe_serviceaccounts",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:serviceaccounts",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_serviceaccounts",
    ),
    OperationSpec(
        logical_name="kubectl.get_networkpolicies",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:networkpolicies",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_networkpolicies",
    ),
    OperationSpec(
        logical_name="kubectl.describe_networkpolicies",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:networkpolicies",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_networkpolicies",
    ),
    OperationSpec(
        logical_name="kubectl.get_horizontalpodautoscalers",
        executable_key="kubectl",
        subcommand="get",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe"), OptionSpec("--field-selector", "safe"), OptionSpec("--show-labels"), OptionSpec("--sort-by", "safe"), OptionSpec("--no-headers"), OptionSpec("--output", "short"), OptionSpec("--chunk-size", "integer")),
        positionals=("literal:horizontalpodautoscalers",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.get_horizontalpodautoscalers",
    ),
    OperationSpec(
        logical_name="kubectl.describe_horizontalpodautoscalers",
        executable_key="kubectl",
        subcommand="describe",
        options=(OptionSpec("--namespace", "identifier"), OptionSpec("--all-namespaces"), OptionSpec("--selector", "safe")),
        positionals=("literal:horizontalpodautoscalers",),
        variadic="identifier",
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.MODERATE,
        timeout=180,
        tags=frozenset(("infra", "kubernetes")),
        description="kubectl.describe_horizontalpodautoscalers",
    ),
    OperationSpec(
        logical_name="helm.version",
        executable_key="helm",
        subcommand="version",
        options=(OptionSpec("--short"), OptionSpec("--template", "safe")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "helm")),
        description="helm.version",
    ),
    OperationSpec(
        logical_name="helm.env",
        executable_key="helm",
        subcommand="env",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60,
        tags=frozenset(("infra", "helm")),
        description="helm.env",
    ),
    OperationSpec(
        logical_name="helm.lint",
        executable_key="helm",
        subcommand="lint",
        options=(OptionSpec("--strict"), OptionSpec("--with-subcharts"), OptionSpec("--values", "path", True), OptionSpec("--set", "safe", True), OptionSpec("--set-string", "safe", True), OptionSpec("--namespace", "identifier")),
        positionals=("path",),
        variadic="path",
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        tags=frozenset(("infra", "helm")),
        description="helm.lint",
    ),
    OperationSpec(
        logical_name="helm.template",
        executable_key="helm",
        subcommand="template",
        options=(OptionSpec("--values", "path", True), OptionSpec("--set", "safe", True), OptionSpec("--set-string", "safe", True), OptionSpec("--namespace", "identifier"), OptionSpec("--include-crds"), OptionSpec("--skip-tests"), OptionSpec("--show-only", "path", True), OptionSpec("--api-versions", "short", True), OptionSpec("--kube-version", "short")),
        positionals=("identifier", "path"),
        effects=frozenset({CommandEffect.READ, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=600,
        tags=frozenset(("infra", "helm")),
        description="helm.template",
    ),
    OperationSpec(
        logical_name="helm.show_chart",
        executable_key="helm",
        fixed_prefix=("show", "chart"),
        positionals=("path",),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "helm")),
        description="helm.show_chart",
    ),
    OperationSpec(
        logical_name="helm.show_values",
        executable_key="helm",
        fixed_prefix=("show", "values"),
        positionals=("path",),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "helm")),
        description="helm.show_values",
    ),
    OperationSpec(
        logical_name="helm.show_readme",
        executable_key="helm",
        fixed_prefix=("show", "readme"),
        positionals=("path",),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "helm")),
        description="helm.show_readme",
    ),
    OperationSpec(
        logical_name="helm.dependency_list",
        executable_key="helm",
        fixed_prefix=("dependency", "list"),
        positionals=("path",),
        min_positionals=3,
        max_positionals=3,
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "helm")),
        description="helm.dependency_list",
    ),
    OperationSpec(
        logical_name="helm.repo_list",
        executable_key="helm",
        fixed_prefix=("repo", "list"),
        options=(OptionSpec("--output", "short"),),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=120,
        tags=frozenset(("infra", "helm")),
        description="helm.repo_list",
    ),
    OperationSpec(
        logical_name="helm.search_repo",
        executable_key="helm",
        fixed_prefix=("search", "repo"),
        options=(OptionSpec("--versions"), OptionSpec("--regexp"), OptionSpec("--devel"), OptionSpec("--max-col-width", "integer"), OptionSpec("--output", "short")),
        positionals=("short",),
        effects=frozenset({CommandEffect.READ, CommandEffect.NETWORK}),
        risk=CommandRisk.LOW,
        timeout=180,
        tags=frozenset(("infra", "helm")),
        description="helm.search_repo",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS


def mutation_capable_names() -> frozenset[str]:
    """Names deliberately absent from this read-mostly infrastructure tier."""
    return frozenset({
        "terraform.apply", "terraform.destroy", "tofu.apply", "tofu.destroy",
        "kubectl.apply", "kubectl.create", "kubectl.delete", "kubectl.patch",
        "kubectl.edit", "kubectl.exec", "kubectl.port_forward",
        "helm.install", "helm.upgrade", "helm.uninstall", "helm.rollback",
    })
