"""JVM ecosystem logical command contracts."""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="jvm.java_version",
        executable_key="java",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("jvm",)),
        description="jvm.java_version",
    ),
    OperationSpec(
        logical_name="jvm.javac_version",
        executable_key="javac",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("jvm",)),
        description="jvm.javac_version",
    ),
    OperationSpec(
        logical_name="jvm.javac_compile",
        executable_key="javac",
        options=(OptionSpec("-d", "path"), OptionSpec("-cp", "path"), OptionSpec("-classpath", "path"), OptionSpec("--release", "short"), OptionSpec("-g"), OptionSpec("-parameters"), OptionSpec("-Werror")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        tags=frozenset(("jvm",)),
        description="jvm.javac_compile",
    ),
    OperationSpec(
        logical_name="jvm.jar_list",
        executable_key="jar",
        subcommand="tf",
        positionals=("path",),
        min_positionals=2,
        max_positionals=2,
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("jvm",)),
        description="jvm.jar_list",
    ),
    OperationSpec(
        logical_name="jvm.jar_create",
        executable_key="jar",
        subcommand="cf",
        positionals=("path",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("jvm",)),
        description="jvm.jar_create",
    ),
    OperationSpec(
        logical_name="jvm.jar_update",
        executable_key="jar",
        subcommand="uf",
        positionals=("path",),
        variadic="path",
        min_positionals=2,
        max_positionals=None,
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=600.0,
        tags=frozenset(("jvm",)),
        description="jvm.jar_update",
    ),
    OperationSpec(
        logical_name="jvm.javadoc",
        executable_key="javadoc",
        options=(OptionSpec("-d", "path"), OptionSpec("-classpath", "path"), OptionSpec("-sourcepath", "path"), OptionSpec("-quiet"), OptionSpec("-Xdoclint:none")),
        variadic="safe",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        tags=frozenset(("jvm",)),
        description="jvm.javadoc",
    ),
    OperationSpec(
        logical_name="jvm.mvn_version",
        executable_key="mvn",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("jvm",)),
        description="jvm.mvn_version",
    ),
    OperationSpec(
        logical_name="jvm.mvn_validate",
        executable_key="mvn",
        subcommand="validate",
        options=(OptionSpec("-q"), OptionSpec("-B"), OptionSpec("-o"), OptionSpec("-DskipTests")),
        effects=frozenset({CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("jvm",)),
        description="jvm.mvn_validate",
    ),
    OperationSpec(
        logical_name="jvm.mvn_test",
        executable_key="mvn",
        subcommand="test",
        options=(OptionSpec("-q"), OptionSpec("-B"), OptionSpec("-o"), OptionSpec("-DskipTests"), OptionSpec("-Dtest", "safe"), OptionSpec("-pl", "short"), OptionSpec("-am")),
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("jvm",)),
        description="jvm.mvn_test",
    ),
    OperationSpec(
        logical_name="jvm.mvn_verify",
        executable_key="mvn",
        subcommand="verify",
        options=(OptionSpec("-q"), OptionSpec("-B"), OptionSpec("-o"), OptionSpec("-DskipTests"), OptionSpec("-pl", "short"), OptionSpec("-am")),
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("jvm",)),
        description="jvm.mvn_verify",
    ),
    OperationSpec(
        logical_name="jvm.mvn_package",
        executable_key="mvn",
        subcommand="package",
        options=(OptionSpec("-q"), OptionSpec("-B"), OptionSpec("-o"), OptionSpec("-DskipTests"), OptionSpec("-pl", "short"), OptionSpec("-am")),
        effects=frozenset({CommandEffect.BUILD, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("jvm",)),
        description="jvm.mvn_package",
    ),
    OperationSpec(
        logical_name="jvm.mvn_dependency_tree",
        executable_key="mvn",
        subcommand="dependency:tree",
        options=(OptionSpec("-Dscope", "short"), OptionSpec("-Dincludes", "short"), OptionSpec("-DoutputType", "short")),
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("jvm",)),
        description="jvm.mvn_dependency_tree",
    ),
    OperationSpec(
        logical_name="jvm.mvn_dependency_analyze",
        executable_key="mvn",
        subcommand="dependency:analyze",
        options=(OptionSpec("-DignoreNonCompile"), OptionSpec("-DfailOnWarning")),
        effects=frozenset({CommandEffect.LINT, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        allow_nonzero_success=True,
        tags=frozenset(("jvm",)),
        description="jvm.mvn_dependency_analyze",
    ),
    OperationSpec(
        logical_name="jvm.mvn_clean",
        executable_key="mvn",
        subcommand="clean",
        options=(OptionSpec("-q"), OptionSpec("-B")),
        effects=frozenset({CommandEffect.WRITE, CommandEffect.BUILD}),
        risk=CommandRisk.HIGH,
        timeout=600.0,
        tags=frozenset(("jvm",)),
        description="jvm.mvn_clean",
    ),
    OperationSpec(
        logical_name="jvm.gradle_version",
        executable_key="gradle",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("jvm",)),
        description="jvm.gradle_version",
    ),
    OperationSpec(
        logical_name="jvm.gradle_tasks",
        executable_key="gradle",
        subcommand="tasks",
        options=(OptionSpec("--all"), OptionSpec("--quiet"), OptionSpec("--console", "short")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        tags=frozenset(("jvm",)),
        description="jvm.gradle_tasks",
    ),
    OperationSpec(
        logical_name="jvm.gradle_dependencies",
        executable_key="gradle",
        subcommand="dependencies",
        options=(OptionSpec("--configuration", "short"), OptionSpec("--quiet")),
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("jvm",)),
        description="jvm.gradle_dependencies",
    ),
    OperationSpec(
        logical_name="jvm.gradle_test",
        executable_key="gradle",
        subcommand="test",
        options=(OptionSpec("--no-daemon"), OptionSpec("--offline"), OptionSpec("--rerun-tasks"), OptionSpec("--tests", "safe"), OptionSpec("--max-workers", "integer")),
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("jvm",)),
        description="jvm.gradle_test",
    ),
    OperationSpec(
        logical_name="jvm.gradle_check",
        executable_key="gradle",
        subcommand="check",
        options=(OptionSpec("--no-daemon"), OptionSpec("--offline"), OptionSpec("--rerun-tasks"), OptionSpec("--max-workers", "integer")),
        effects=frozenset({CommandEffect.TEST, CommandEffect.LINT, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("jvm",)),
        description="jvm.gradle_check",
    ),
    OperationSpec(
        logical_name="jvm.gradle_build",
        executable_key="gradle",
        subcommand="build",
        options=(OptionSpec("--no-daemon"), OptionSpec("--offline"), OptionSpec("--rerun-tasks"), OptionSpec("--max-workers", "integer"), OptionSpec("-x", "short", True)),
        effects=frozenset({CommandEffect.BUILD, CommandEffect.TEST, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("jvm",)),
        description="jvm.gradle_build",
    ),
    OperationSpec(
        logical_name="jvm.gradle_clean",
        executable_key="gradle",
        subcommand="clean",
        options=(OptionSpec("--no-daemon"),),
        effects=frozenset({CommandEffect.WRITE, CommandEffect.BUILD}),
        risk=CommandRisk.HIGH,
        timeout=600.0,
        tags=frozenset(("jvm",)),
        description="jvm.gradle_clean",
    ),
    OperationSpec(
        logical_name="jvm.junit_console",
        executable_key="junit-platform-console",
        options=(OptionSpec("--scan-classpath"), OptionSpec("--select-class", "identifier", True), OptionSpec("--select-package", "identifier", True), OptionSpec("--details", "short"), OptionSpec("--fail-if-no-tests")),
        effects=frozenset({CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        allow_nonzero_success=True,
        tags=frozenset(("jvm",)),
        description="jvm.junit_console",
    ),
    OperationSpec(
        logical_name="jvm.checkstyle",
        executable_key="checkstyle",
        options=(OptionSpec("-c", "path"), OptionSpec("-f", "short"), OptionSpec("-o", "path")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        allow_nonzero_success=True,
        tags=frozenset(("jvm",)),
        description="jvm.checkstyle",
    ),
    OperationSpec(
        logical_name="jvm.spotbugs",
        executable_key="spotbugs",
        options=(OptionSpec("-textui"), OptionSpec("-effort", "short"), OptionSpec("-low"), OptionSpec("-medium"), OptionSpec("-high"), OptionSpec("-xml"), OptionSpec("-output", "path")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        allow_nonzero_success=True,
        tags=frozenset(("jvm",)),
        description="jvm.spotbugs",
    ),
    OperationSpec(
        logical_name="jvm.jdeps",
        executable_key="jdeps",
        options=(OptionSpec("--recursive"), OptionSpec("--summary"), OptionSpec("--multi-release", "short"), OptionSpec("--class-path", "path")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("jvm",)),
        description="jvm.jdeps",
    ),
    OperationSpec(
        logical_name="jvm.jlink",
        executable_key="jlink",
        options=(OptionSpec("--module-path", "path"), OptionSpec("--add-modules", "short"), OptionSpec("--output", "path"), OptionSpec("--strip-debug"), OptionSpec("--no-header-files"), OptionSpec("--no-man-pages")),
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        tags=frozenset(("jvm",)),
        description="jvm.jlink",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS
