"""Static analysis, policy, and security-scanner command contracts.

Auto-fix, remote-rule auto-discovery, infrastructure apply, and secret-printing
modes are intentionally excluded. Scanner exit codes may be non-zero when
findings are present and are modeled as evidence rather than process crashes.
"""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="quality.shellcheck",
        executable_key="shellcheck",
        options=(OptionSpec("-S", "short"), OptionSpec("--severity", "short"), OptionSpec("-s", "short"), OptionSpec("--shell", "short"), OptionSpec("-f", "short"), OptionSpec("--format", "short"), OptionSpec("-x"), OptionSpec("--external-sources"), OptionSpec("-e", "short", True), OptionSpec("--exclude", "short", True)),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.shellcheck",
    ),
    OperationSpec(
        logical_name="quality.hadolint",
        executable_key="hadolint",
        options=(OptionSpec("--format", "short"), OptionSpec("--failure-threshold", "short"), OptionSpec("--ignore", "short", True), OptionSpec("--trusted-registry", "short", True), OptionSpec("--no-fail")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.hadolint",
    ),
    OperationSpec(
        logical_name="quality.actionlint",
        executable_key="actionlint",
        options=(OptionSpec("-format", "safe"), OptionSpec("-ignore", "safe", True), OptionSpec("-no-color"), OptionSpec("-oneline")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.actionlint",
    ),
    OperationSpec(
        logical_name="quality.yamllint",
        executable_key="yamllint",
        options=(OptionSpec("-f", "short"), OptionSpec("--format", "short"), OptionSpec("-c", "path"), OptionSpec("--config-file", "path"), OptionSpec("-s"), OptionSpec("--strict"), OptionSpec("--no-warnings")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.yamllint",
    ),
    OperationSpec(
        logical_name="quality.semgrep_scan",
        executable_key="semgrep",
        subcommand="scan",
        options=(OptionSpec("--config", "path", True), OptionSpec("--json"), OptionSpec("--text"), OptionSpec("--error"), OptionSpec("--strict"), OptionSpec("--exclude", "short", True), OptionSpec("--include", "short", True), OptionSpec("--timeout", "integer"), OptionSpec("--max-target-bytes", "integer"), OptionSpec("--metrics", "literal:off"), OptionSpec("--disable-version-check"), OptionSpec("--no-git-ignore")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.semgrep_scan",
    ),
    OperationSpec(
        logical_name="quality.checkov_directory",
        executable_key="checkov",
        options=(OptionSpec("-d", "path"), OptionSpec("--directory", "path"), OptionSpec("--framework", "short", True), OptionSpec("--skip-framework", "short", True), OptionSpec("--check", "short", True), OptionSpec("--skip-check", "short", True), OptionSpec("--output", "short"), OptionSpec("--quiet"), OptionSpec("--compact"), OptionSpec("--soft-fail")),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.checkov_directory",
    ),
    OperationSpec(
        logical_name="quality.checkov_file",
        executable_key="checkov",
        options=(OptionSpec("-f", "path", True), OptionSpec("--file", "path", True), OptionSpec("--framework", "short", True), OptionSpec("--check", "short", True), OptionSpec("--skip-check", "short", True), OptionSpec("--output", "short"), OptionSpec("--quiet"), OptionSpec("--compact"), OptionSpec("--soft-fail")),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.checkov_file",
    ),
    OperationSpec(
        logical_name="quality.conftest_test",
        executable_key="conftest",
        subcommand="test",
        options=(OptionSpec("--policy", "path", True), OptionSpec("--data", "path", True), OptionSpec("--namespace", "identifier"), OptionSpec("--output", "short"), OptionSpec("--strict"), OptionSpec("--no-color"), OptionSpec("--fail-on-warn")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=600,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.conftest_test",
    ),
    OperationSpec(
        logical_name="quality.conftest_verify",
        executable_key="conftest",
        subcommand="verify",
        options=(OptionSpec("--policy", "path", True), OptionSpec("--output", "short"), OptionSpec("--no-color")),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.conftest_verify",
    ),
    OperationSpec(
        logical_name="quality.opa_eval",
        executable_key="opa",
        subcommand="eval",
        options=(OptionSpec("--data", "path", True), OptionSpec("--input", "path"), OptionSpec("--format", "short"), OptionSpec("--fail"), OptionSpec("--fail-defined"), OptionSpec("--strict"), OptionSpec("--strict-builtin-errors"), OptionSpec("--explain", "short"), OptionSpec("--metrics")),
        positionals=("safe",),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.opa_eval",
    ),
    OperationSpec(
        logical_name="quality.opa_check",
        executable_key="opa",
        subcommand="check",
        options=(OptionSpec("--strict"), OptionSpec("--bundle"), OptionSpec("--format", "short"), OptionSpec("--max-errors", "integer")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.opa_check",
    ),
    OperationSpec(
        logical_name="quality.opa_fmt_diff",
        executable_key="opa",
        subcommand="fmt",
        options=(OptionSpec("--diff"), OptionSpec("--fail"), OptionSpec("--list")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=120,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.opa_fmt_diff",
    ),
    OperationSpec(
        logical_name="quality.kubeconform",
        executable_key="kubeconform",
        options=(OptionSpec("-strict"), OptionSpec("-summary"), OptionSpec("-verbose"), OptionSpec("-ignore-missing-schemas"), OptionSpec("-kubernetes-version", "short"), OptionSpec("-schema-location", "path", True), OptionSpec("-skip", "short"), OptionSpec("-reject", "short"), OptionSpec("-output", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=600,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.kubeconform",
    ),
    OperationSpec(
        logical_name="quality.kube_score",
        executable_key="kube_score",
        subcommand="score",
        options=(OptionSpec("--output-format", "short"), OptionSpec("--ignore-test", "short", True), OptionSpec("--enable-optional-test", "short", True), OptionSpec("--kubernetes-version", "short")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.kube_score",
    ),
    OperationSpec(
        logical_name="quality.gitleaks_detect",
        executable_key="gitleaks",
        subcommand="detect",
        options=(OptionSpec("--source", "path"), OptionSpec("--no-git"), OptionSpec("--redact", "integer"), OptionSpec("--verbose"), OptionSpec("--exit-code", "integer"), OptionSpec("--config", "path"), OptionSpec("--max-decode-depth", "integer"), OptionSpec("--max-archive-depth", "integer")),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.gitleaks_detect",
    ),
    OperationSpec(
        logical_name="quality.gitleaks_git",
        executable_key="gitleaks",
        subcommand="git",
        options=(OptionSpec("--redact", "integer"), OptionSpec("--verbose"), OptionSpec("--exit-code", "integer"), OptionSpec("--config", "path"), OptionSpec("--log-opts", "safe")),
        positionals=("path",),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.gitleaks_git",
    ),
    OperationSpec(
        logical_name="quality.trivy_fs",
        executable_key="trivy",
        fixed_prefix=("fs", "--skip-db-update", "--offline-scan"),
        options=(OptionSpec("--scanners", "short"), OptionSpec("--severity", "short"), OptionSpec("--format", "short"), OptionSpec("--exit-code", "integer"), OptionSpec("--ignore-unfixed"), OptionSpec("--no-progress"), OptionSpec("--skip-dirs", "path", True), OptionSpec("--skip-files", "path", True), OptionSpec("--timeout", "short")),
        positionals=("path",),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=1200,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.trivy_fs",
    ),
    OperationSpec(
        logical_name="quality.trivy_config",
        executable_key="trivy",
        fixed_prefix=("config", "--skip-check-update"),
        options=(OptionSpec("--severity", "short"), OptionSpec("--format", "short"), OptionSpec("--exit-code", "integer"), OptionSpec("--no-progress"), OptionSpec("--skip-dirs", "path", True), OptionSpec("--skip-files", "path", True)),
        positionals=("path",),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.trivy_config",
    ),
    OperationSpec(
        logical_name="quality.syft_scan",
        executable_key="syft",
        subcommand="scan",
        options=(OptionSpec("-o", "short"), OptionSpec("--output", "short"), OptionSpec("--select-catalogers", "short"), OptionSpec("--exclude", "path", True), OptionSpec("--scope", "short"), OptionSpec("--quiet")),
        positionals=("path",),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.syft_scan",
    ),
    OperationSpec(
        logical_name="quality.osv_scan_source",
        executable_key="osv_scanner",
        subcommand="scan",
        options=(OptionSpec("--recursive"), OptionSpec("--format", "short"), OptionSpec("--verbosity", "short"), OptionSpec("--lockfile", "path", True), OptionSpec("--skip-git"), OptionSpec("--call-analysis", "literal:off")),
        positionals=("path",),
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.osv_scan_source",
    ),
    OperationSpec(
        logical_name="quality.markdownlint",
        executable_key="markdownlint",
        options=(OptionSpec("--ignore", "path", True), OptionSpec("--config", "path")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.markdownlint",
    ),
    OperationSpec(
        logical_name="quality.sqlfluff_lint",
        executable_key="sqlfluff",
        subcommand="lint",
        options=(OptionSpec("--dialect", "short"), OptionSpec("--format", "short"), OptionSpec("--exclude-rules", "short"), OptionSpec("--rules", "short"), OptionSpec("--ignore", "short"), OptionSpec("--config", "path"), OptionSpec("--nofail")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=600,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.sqlfluff_lint",
    ),
    OperationSpec(
        logical_name="quality.sqlfluff_parse",
        executable_key="sqlfluff",
        subcommand="parse",
        options=(OptionSpec("--dialect", "short"), OptionSpec("--format", "short"), OptionSpec("--config", "path")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=600,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.sqlfluff_parse",
    ),
    OperationSpec(
        logical_name="quality.spectral_lint",
        executable_key="spectral",
        subcommand="lint",
        options=(OptionSpec("--ruleset", "path"), OptionSpec("--format", "short"), OptionSpec("--fail-severity", "short"), OptionSpec("--display-only-failures"), OptionSpec("--quiet")),
        variadic="path",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.READ, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=300,
        allow_nonzero_success=True,
        tags=frozenset(("security", "analysis")),
        description="quality.spectral_lint",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS


DENIED_FIX_OR_REMOTE_MODES = frozenset({
    "semgrep:--config=auto", "semgrep:--autofix", "sqlfluff:fix",
    "trivy:image", "trivy:repository", "checkov:--download-external-modules",
    "gitleaks:--report-path", "opa:run",
})
