"""Rust ecosystem logical command contracts."""

from __future__ import annotations

from skeleton.shells.toolchains.factory import OperationSpec, OptionSpec, build_many
from skeleton.shells.toolchains.types import CommandEffect, CommandRisk

SPECS = (
    OperationSpec(
        logical_name="rust.cargo_version",
        executable_key="cargo",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("rust",)),
        description="rust.cargo_version",
    ),
    OperationSpec(
        logical_name="rust.metadata",
        executable_key="cargo",
        subcommand="metadata",
        options=(OptionSpec("--no-deps"), OptionSpec("--format-version", "integer"), OptionSpec("--filter-platform", "short")),
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=120.0,
        tags=frozenset(("rust",)),
        description="rust.metadata",
    ),
    OperationSpec(
        logical_name="rust.check",
        executable_key="cargo",
        subcommand="check",
        options=(OptionSpec("--workspace"), OptionSpec("--all-targets"), OptionSpec("--all-features"), OptionSpec("--no-default-features"), OptionSpec("--features", "short"), OptionSpec("--package", "short", True), OptionSpec("--locked"), OptionSpec("--offline")),
        effects=frozenset({CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        tags=frozenset(("rust",)),
        description="rust.check",
    ),
    OperationSpec(
        logical_name="rust.build",
        executable_key="cargo",
        subcommand="build",
        options=(OptionSpec("--release"), OptionSpec("--workspace"), OptionSpec("--all-targets"), OptionSpec("--all-features"), OptionSpec("--features", "short"), OptionSpec("--package", "short", True), OptionSpec("--locked"), OptionSpec("--offline"), OptionSpec("--target", "short")),
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("rust",)),
        description="rust.build",
    ),
    OperationSpec(
        logical_name="rust.test",
        executable_key="cargo",
        subcommand="test",
        options=(OptionSpec("--release"), OptionSpec("--workspace"), OptionSpec("--all-targets"), OptionSpec("--all-features"), OptionSpec("--features", "short"), OptionSpec("--package", "short", True), OptionSpec("--locked"), OptionSpec("--offline"), OptionSpec("--no-fail-fast")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("rust",)),
        description="rust.test",
    ),
    OperationSpec(
        logical_name="rust.clippy",
        executable_key="cargo",
        subcommand="clippy",
        options=(OptionSpec("--workspace"), OptionSpec("--all-targets"), OptionSpec("--all-features"), OptionSpec("--features", "short"), OptionSpec("--package", "short", True), OptionSpec("--locked"), OptionSpec("--offline")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.LINT, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        allow_nonzero_success=True,
        tags=frozenset(("rust",)),
        description="rust.clippy",
    ),
    OperationSpec(
        logical_name="rust.fmt_check",
        executable_key="cargo",
        subcommand="fmt",
        options=(OptionSpec("--all"), OptionSpec("--check")),
        effects=frozenset({CommandEffect.FORMAT}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        allow_nonzero_success=True,
        tags=frozenset(("rust",)),
        description="rust.fmt_check",
    ),
    OperationSpec(
        logical_name="rust.fmt_write",
        executable_key="cargo",
        subcommand="fmt",
        options=(OptionSpec("--all"),),
        effects=frozenset({CommandEffect.FORMAT, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=300.0,
        tags=frozenset(("rust",)),
        description="rust.fmt_write",
    ),
    OperationSpec(
        logical_name="rust.doc",
        executable_key="cargo",
        subcommand="doc",
        options=(OptionSpec("--workspace"), OptionSpec("--all-features"), OptionSpec("--no-deps"), OptionSpec("--document-private-items"), OptionSpec("--locked"), OptionSpec("--offline")),
        effects=frozenset({CommandEffect.BUILD, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=1200.0,
        tags=frozenset(("rust",)),
        description="rust.doc",
    ),
    OperationSpec(
        logical_name="rust.tree",
        executable_key="cargo",
        subcommand="tree",
        options=(OptionSpec("--workspace"), OptionSpec("--all-features"), OptionSpec("--edges", "short"), OptionSpec("--depth", "integer"), OptionSpec("--package", "short")),
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        tags=frozenset(("rust",)),
        description="rust.tree",
    ),
    OperationSpec(
        logical_name="rust.locate_project",
        executable_key="cargo",
        subcommand="locate-project",
        options=(OptionSpec("--workspace"), OptionSpec("--message-format", "short")),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("rust",)),
        description="rust.locate_project",
    ),
    OperationSpec(
        logical_name="rust.package_list",
        executable_key="cargo",
        subcommand="package",
        options=(OptionSpec("--list"), OptionSpec("--allow-dirty"), OptionSpec("--no-verify"), OptionSpec("--locked")),
        effects=frozenset({CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        tags=frozenset(("rust",)),
        description="rust.package_list",
    ),
    OperationSpec(
        logical_name="rust.package",
        executable_key="cargo",
        subcommand="package",
        options=(OptionSpec("--allow-dirty"), OptionSpec("--no-verify"), OptionSpec("--locked"), OptionSpec("--offline")),
        effects=frozenset({CommandEffect.PACKAGE, CommandEffect.WRITE, CommandEffect.BUILD}),
        risk=CommandRisk.MODERATE,
        timeout=1200.0,
        tags=frozenset(("rust",)),
        description="rust.package",
    ),
    OperationSpec(
        logical_name="rust.update_dry",
        executable_key="cargo",
        subcommand="update",
        options=(OptionSpec("--dry-run"), OptionSpec("--precise", "short"), OptionSpec("--package", "short"), OptionSpec("--recursive")),
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.READ, CommandEffect.PACKAGE}),
        risk=CommandRisk.LOW,
        timeout=600.0,
        tags=frozenset(("rust",)),
        description="rust.update_dry",
    ),
    OperationSpec(
        logical_name="rust.update",
        executable_key="cargo",
        subcommand="update",
        options=(OptionSpec("--precise", "short"), OptionSpec("--package", "short"), OptionSpec("--recursive"), OptionSpec("--offline")),
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=600.0,
        tags=frozenset(("rust",)),
        description="rust.update",
    ),
    OperationSpec(
        logical_name="rust.fetch",
        executable_key="cargo",
        subcommand="fetch",
        options=(OptionSpec("--locked"), OptionSpec("--offline"), OptionSpec("--target", "short")),
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.PACKAGE, CommandEffect.WRITE}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        tags=frozenset(("rust",)),
        description="rust.fetch",
    ),
    OperationSpec(
        logical_name="rust.clean",
        executable_key="cargo",
        subcommand="clean",
        options=(OptionSpec("--package", "short"), OptionSpec("--target", "short"), OptionSpec("--release")),
        effects=frozenset({CommandEffect.WRITE, CommandEffect.BUILD}),
        risk=CommandRisk.HIGH,
        timeout=600.0,
        tags=frozenset(("rust",)),
        description="rust.clean",
    ),
    OperationSpec(
        logical_name="rust.bench",
        executable_key="cargo",
        subcommand="bench",
        options=(OptionSpec("--workspace"), OptionSpec("--features", "short"), OptionSpec("--package", "short", True), OptionSpec("--no-run")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.TEST, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("rust",)),
        description="rust.bench",
    ),
    OperationSpec(
        logical_name="rust.run",
        executable_key="cargo",
        subcommand="run",
        options=(OptionSpec("--release"), OptionSpec("--package", "short"), OptionSpec("--bin", "short"), OptionSpec("--example", "short"), OptionSpec("--features", "short"), OptionSpec("--locked"), OptionSpec("--offline")),
        variadic="safe",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.PROCESS, CommandEffect.BUILD}),
        risk=CommandRisk.MODERATE,
        timeout=1800.0,
        tags=frozenset(("rust",)),
        description="rust.run",
    ),
    OperationSpec(
        logical_name="rust.fix",
        executable_key="cargo",
        subcommand="fix",
        options=(OptionSpec("--allow-dirty"), OptionSpec("--allow-staged"), OptionSpec("--broken-code"), OptionSpec("--edition"), OptionSpec("--edition-idioms")),
        effects=frozenset({CommandEffect.LINT, CommandEffect.WRITE}),
        risk=CommandRisk.HIGH,
        timeout=1200.0,
        tags=frozenset(("rust",)),
        description="rust.fix",
    ),
    OperationSpec(
        logical_name="rust.rustc_version",
        executable_key="rustc",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("rust",)),
        description="rust.rustc_version",
    ),
    OperationSpec(
        logical_name="rust.rustc_verbose",
        executable_key="rustc",
        subcommand="--version",
        options=(OptionSpec("--verbose"),),
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("rust",)),
        description="rust.rustc_verbose",
    ),
    OperationSpec(
        logical_name="rust.rustfmt_check",
        executable_key="rustfmt",
        options=(OptionSpec("--check"), OptionSpec("--edition", "short")),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.FORMAT}),
        risk=CommandRisk.LOW,
        timeout=300.0,
        allow_nonzero_success=True,
        tags=frozenset(("rust",)),
        description="rust.rustfmt_check",
    ),
    OperationSpec(
        logical_name="rust.rustfmt_write",
        executable_key="rustfmt",
        options=(OptionSpec("--edition", "short"),),
        variadic="path",
        min_positionals=0,
        max_positionals=None,
        effects=frozenset({CommandEffect.FORMAT, CommandEffect.WRITE}),
        risk=CommandRisk.MODERATE,
        timeout=300.0,
        tags=frozenset(("rust",)),
        description="rust.rustfmt_write",
    ),
    OperationSpec(
        logical_name="rust.clippy_driver_version",
        executable_key="clippy-driver",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("rust",)),
        description="rust.clippy_driver_version",
    ),
    OperationSpec(
        logical_name="rust.rustdoc_version",
        executable_key="rustdoc",
        subcommand="--version",
        effects=frozenset({CommandEffect.READ}),
        risk=CommandRisk.LOW,
        timeout=60.0,
        tags=frozenset(("rust",)),
        description="rust.rustdoc_version",
    ),
    OperationSpec(
        logical_name="rust.cargo_audit",
        executable_key="cargo-audit",
        subcommand="audit",
        options=(OptionSpec("--json"), OptionSpec("--deny", "short"), OptionSpec("--ignore", "short", True)),
        effects=frozenset({CommandEffect.NETWORK, CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        allow_nonzero_success=True,
        tags=frozenset(("rust",)),
        description="rust.cargo_audit",
    ),
    OperationSpec(
        logical_name="rust.cargo_deny_check",
        executable_key="cargo-deny",
        subcommand="check",
        options=(OptionSpec("--config", "path"), OptionSpec("--hide-inclusion-graph"), OptionSpec("--disable-fetch")),
        variadic="short",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.LINT}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        allow_nonzero_success=True,
        tags=frozenset(("rust",)),
        description="rust.cargo_deny_check",
    ),
    OperationSpec(
        logical_name="rust.cargo_nextest",
        executable_key="cargo-nextest",
        subcommand="run",
        options=(OptionSpec("--workspace"), OptionSpec("--all-features"), OptionSpec("--no-fail-fast"), OptionSpec("--profile", "short")),
        variadic="test",
        min_positionals=1,
        max_positionals=None,
        effects=frozenset({CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        tags=frozenset(("rust",)),
        description="rust.cargo_nextest",
    ),
    OperationSpec(
        logical_name="rust.cargo_expand",
        executable_key="cargo-expand",
        options=(OptionSpec("--lib"), OptionSpec("--bin", "short"), OptionSpec("--test", "short"), OptionSpec("--package", "short"), OptionSpec("--features", "short")),
        effects=frozenset({CommandEffect.READ, CommandEffect.BUILD}),
        risk=CommandRisk.LOW,
        timeout=900.0,
        tags=frozenset(("rust",)),
        description="rust.cargo_expand",
    ),
    OperationSpec(
        logical_name="rust.cargo_msrv",
        executable_key="cargo-msrv",
        subcommand="verify",
        options=(OptionSpec("--path", "path"), OptionSpec("--output-format", "short")),
        effects=frozenset({CommandEffect.BUILD, CommandEffect.TEST}),
        risk=CommandRisk.LOW,
        timeout=1800.0,
        allow_nonzero_success=True,
        tags=frozenset(("rust",)),
        description="rust.cargo_msrv",
    ),
)

CONTRACTS = build_many(SPECS)


def contracts():
    return CONTRACTS
