"""Stable public facade for Jeeves predictive and mathematical modeling.

The implementation remains split into focused modules so forecasting, AR fitting,
seasonal challengers, conformal uncertainty, regime diagnostics, stacking,
bidirectional stress tests, regime-aware route validation, evidence projection,
and end-to-end coordination can evolve independently. Callers that want the
supported predictive surface should import from this module instead of reaching
into implementation modules.
"""

from __future__ import annotations

from .historical_autoregression import (
    AdvancedForecastReport,
    AdvancedHistoricalForecastTournament,
    AutoRegressiveEvaluation,
    AutoRegressiveFit,
    AutoRegressiveForecaster,
    AutoRegressiveParameters,
    AutoRegressiveSelectionPolicy,
    HistoricalAutoregressionError,
    summarize_advanced_forecast,
)
from .historical_conformal import (
    ConformalBand,
    ConformalIntervalPoint,
    ConformalPolicy,
    CoverageAudit,
    HistoricalConformalCalibrator,
    HistoricalConformalError,
    summarize_conformal_band,
    summarize_coverage_audit,
)
from .historical_ensemble import (
    EnsembleEvaluation,
    FittedForecastEnsemble,
    ForecastEnsemblePolicy,
    ForecastEnsembleReport,
    HistoricalEnsembleError,
    HistoricalForecastEnsembler,
    summarize_forecast_ensemble,
)
from .historical_forecasting import (
    FittedForecast,
    ForecastEvaluation,
    ForecastMethod,
    ForecastObservation,
    ForecastParameters,
    ForecastPoint,
    ForecastSelectionPolicy,
    ForecastTournamentReport,
    HistoricalForecastError,
    HistoricalForecaster,
    HistoricalForecastTournament,
    HistoricalSeries,
    HorizonMetrics,
    series_from_registry,
    summarize_forecast_tournament,
)
from .historical_regimes import (
    HistoricalRegimeDetector,
    HistoricalRegimeError,
    RegimeCandidate,
    RegimeDetectionPolicy,
    RegimeShiftReport,
    SegmentStatistics,
    summarize_regime_shift,
)
from .historical_seasonal import (
    FittedSeasonalForecast,
    HistoricalSeasonalError,
    HistoricalSeasonalForecaster,
    HistoricalSeasonalTournament,
    SeasonalEvaluation,
    SeasonalHorizonMetrics,
    SeasonalMethod,
    SeasonalParameters,
    SeasonalSelectionPolicy,
    SeasonalTournamentReport,
    summarize_seasonal_tournament,
)
from .predictive_bidirectional import (
    BidirectionalPredictiveAuditor,
    BidirectionalPredictiveError,
    BidirectionalPredictivePolicy,
    BidirectionalPredictiveReport,
    mirror_series,
    summarize_bidirectional_predictive,
)
from .predictive_engine import (
    JeevesPredictiveEngine,
    PredictiveEngineError,
    PredictiveEnginePolicy,
    PredictivePoint,
    PredictiveResult,
    summarize_predictive_result,
)
from .predictive_evidence import (
    PredictiveEvidenceBridge,
    PredictiveEvidenceBundle,
    PredictiveEvidenceError,
    summarize_predictive_evidence,
)
from .predictive_regime_routing import (
    PredictiveRegimeRoutingError,
    RegimeAwarePredictiveRouter,
    RegimeRoutePolicy,
    RegimeRouteReport,
    RouteValidationScore,
    summarize_regime_route,
)
from .predictive_seasonal import (
    CommonFamilyScore,
    FamilyHorizonScore,
    SeasonalAwarePredictiveEngine,
    SeasonalChallengeReport,
    SeasonalPredictiveError,
    SeasonalPromotionPolicy,
    summarize_seasonal_challenge,
)


__all__ = [
    "AdvancedForecastReport",
    "AdvancedHistoricalForecastTournament",
    "AutoRegressiveEvaluation",
    "AutoRegressiveFit",
    "AutoRegressiveForecaster",
    "AutoRegressiveParameters",
    "AutoRegressiveSelectionPolicy",
    "HistoricalAutoregressionError",
    "summarize_advanced_forecast",
    "ConformalBand",
    "ConformalIntervalPoint",
    "ConformalPolicy",
    "CoverageAudit",
    "HistoricalConformalCalibrator",
    "HistoricalConformalError",
    "summarize_conformal_band",
    "summarize_coverage_audit",
    "EnsembleEvaluation",
    "FittedForecastEnsemble",
    "ForecastEnsemblePolicy",
    "ForecastEnsembleReport",
    "HistoricalEnsembleError",
    "HistoricalForecastEnsembler",
    "summarize_forecast_ensemble",
    "FittedForecast",
    "ForecastEvaluation",
    "ForecastMethod",
    "ForecastObservation",
    "ForecastParameters",
    "ForecastPoint",
    "ForecastSelectionPolicy",
    "ForecastTournamentReport",
    "HistoricalForecastError",
    "HistoricalForecaster",
    "HistoricalForecastTournament",
    "HistoricalSeries",
    "HorizonMetrics",
    "series_from_registry",
    "summarize_forecast_tournament",
    "HistoricalRegimeDetector",
    "HistoricalRegimeError",
    "RegimeCandidate",
    "RegimeDetectionPolicy",
    "RegimeShiftReport",
    "SegmentStatistics",
    "summarize_regime_shift",
    "FittedSeasonalForecast",
    "HistoricalSeasonalError",
    "HistoricalSeasonalForecaster",
    "HistoricalSeasonalTournament",
    "SeasonalEvaluation",
    "SeasonalHorizonMetrics",
    "SeasonalMethod",
    "SeasonalParameters",
    "SeasonalSelectionPolicy",
    "SeasonalTournamentReport",
    "summarize_seasonal_tournament",
    "BidirectionalPredictiveAuditor",
    "BidirectionalPredictiveError",
    "BidirectionalPredictivePolicy",
    "BidirectionalPredictiveReport",
    "mirror_series",
    "summarize_bidirectional_predictive",
    "JeevesPredictiveEngine",
    "PredictiveEngineError",
    "PredictiveEnginePolicy",
    "PredictivePoint",
    "PredictiveResult",
    "summarize_predictive_result",
    "PredictiveEvidenceBridge",
    "PredictiveEvidenceBundle",
    "PredictiveEvidenceError",
    "summarize_predictive_evidence",
    "PredictiveRegimeRoutingError",
    "RegimeAwarePredictiveRouter",
    "RegimeRoutePolicy",
    "RegimeRouteReport",
    "RouteValidationScore",
    "summarize_regime_route",
    "CommonFamilyScore",
    "FamilyHorizonScore",
    "SeasonalAwarePredictiveEngine",
    "SeasonalChallengeReport",
    "SeasonalPredictiveError",
    "SeasonalPromotionPolicy",
    "summarize_seasonal_challenge",
]