// ═══════════════════════════════════════════════════════════════════════
//  STYLE SLIDERS — 9 style pickers for Galaxy Studio Factory
//  Each is a named-option picker (not 1-7) so the selection carries
//  meaningful semantic weight into the generator and swarm prompts.
// ═══════════════════════════════════════════════════════════════════════

export type StyleOption = { id: string; label: string; tag: string };

export type StyleSlider = {
  key: string;             // payload key sent to backend
  label: string;           // UI title
  icon: string;            // ionicon name
  color: string;           // accent color
  hint: string;            // one-line explanation
  options: StyleOption[];
};

export const STYLE_SLIDERS: StyleSlider[] = [
  {
    key: 'graphic_style',
    label: 'Graphic Style',
    icon: 'color-palette-outline',
    color: '#F59E0B',
    hint: 'Overall visual treatment — pixel, painterly, photoreal, etc.',
    options: [
      { id: 'photoreal',       label: 'Photoreal',        tag: 'PBR + scanned textures' },
      { id: 'stylized_pbr',    label: 'Stylized PBR',     tag: 'realistic light + artistic tone' },
      { id: 'cel_shaded',      label: 'Cel-Shaded',       tag: 'hard ink lines + flat fills' },
      { id: 'toon',            label: 'Toon',             tag: 'anime outlines + soft shade' },
      { id: 'pixel_16bit',     label: 'Pixel 16-bit',     tag: 'SNES / Genesis era sprites' },
      { id: 'pixel_32bit',     label: 'Pixel 32-bit',     tag: 'PS1 / Saturn prerendered' },
      { id: 'low_poly_retro',  label: 'Low-Poly Retro',   tag: 'N64 / PS1 polygons' },
      { id: 'voxel',           label: 'Voxel',            tag: 'cubic blocks' },
      { id: 'painterly',       label: 'Painterly Oil',    tag: 'brush strokes visible' },
      { id: 'watercolor',      label: 'Watercolor',       tag: 'washed pastels, paper grain' },
      { id: 'ukiyoe',          label: 'Ukiyo-e',          tag: 'woodblock print flatness' },
      { id: 'stained_glass',   label: 'Stained Glass',    tag: 'leaded panes + color jewels' },
      { id: 'charcoal',        label: 'Charcoal Sketch',  tag: 'grainy monochrome' },
      { id: 'papercraft',      label: 'Papercraft',       tag: 'folded cardstock + seams' },
      { id: 'claymation',      label: 'Claymation',       tag: 'stop-motion thumbprints' },
      { id: 'comic_book',      label: 'Comic Book',       tag: 'halftone dots + onomatopoeia' },
      { id: 'vector_flat',     label: 'Vector Flat',      tag: 'bold shapes, no gradient' },
      { id: 'noir_bw',         label: 'Noir B/W',         tag: 'high contrast monochrome' },
      { id: 'neon_retrowave',  label: 'Neon Retrowave',   tag: 'grid horizon + magenta/cyan' },
      { id: 'ps2_ero',         label: 'PS2-era',          tag: 'early HD muddy polygons' },
    ],
  },
  {
    key: 'sound_style',
    label: 'Sound Style',
    icon: 'volume-high-outline',
    color: '#10B981',
    hint: 'Sound design philosophy — foley realism, synthetic, musical, etc.',
    options: [
      { id: 'foley_realism',   label: 'Foley Realism',    tag: 'field-recorded detail' },
      { id: 'hyperreal',       label: 'Hyperreal',        tag: 'exaggerated physical feel' },
      { id: 'chiptune',        label: 'Chiptune SFX',     tag: '8/16-bit square waves' },
      { id: 'synthetic',       label: 'Synthetic',        tag: 'pure synth design' },
      { id: 'industrial',      label: 'Industrial',       tag: 'metal, steam, clang' },
      { id: 'organic_ambient', label: 'Organic Ambient',  tag: 'breath, wind, wood' },
      { id: 'cinematic_fx',    label: 'Cinematic FX',     tag: 'over-engineered transients' },
      { id: 'minimal_diegetic',label: 'Minimal Diegetic', tag: 'only what the world would make' },
      { id: 'dream_surreal',   label: 'Dream Surreal',    tag: 'reversed, distorted, warped' },
      { id: 'retro_arcade',    label: 'Retro Arcade',     tag: 'coin-drop, blip, crowd' },
      { id: 'horror_dread',    label: 'Horror Dread',     tag: 'sub-bass drones + stingers' },
      { id: 'crunchy_8bit',    label: 'Crunchy 8-bit',    tag: 'tiny speaker compression' },
      { id: 'spatial_binaural',label: 'Spatial Binaural', tag: '3D audio / HRTF' },
      { id: 'lo_fi',           label: 'Lo-Fi',            tag: 'tape hiss + warmth' },
    ],
  },
  {
    key: 'music_style',
    label: 'Music Style',
    icon: 'musical-notes-outline',
    color: '#EC4899',
    hint: 'Score genre + emotional tone.',
    options: [
      { id: 'orchestral_epic',  label: 'Orchestral Epic',  tag: 'strings + brass heroism' },
      { id: 'orchestral_melan', label: 'Orchestral Melan.',tag: 'solo cello + piano' },
      { id: 'chiptune_8bit',    label: 'Chiptune 8-bit',   tag: 'NES / GB era' },
      { id: 'chiptune_16bit',   label: 'Chiptune 16-bit',  tag: 'SNES / Genesis' },
      { id: 'synthwave',        label: 'Synthwave',        tag: '80s retro-future' },
      { id: 'dark_ambient',     label: 'Dark Ambient',     tag: 'drones, texture, decay' },
      { id: 'jazz_noir',        label: 'Jazz Noir',        tag: 'smoke, sax, upright bass' },
      { id: 'folk_acoustic',    label: 'Folk Acoustic',    tag: 'strum, fiddle, flute' },
      { id: 'edm_energetic',    label: 'EDM Energetic',    tag: 'four-on-floor, drops' },
      { id: 'metal_heavy',      label: 'Metal Heavy',      tag: 'riffs, growls, double-kick' },
      { id: 'classical',        label: 'Classical',        tag: 'baroque / romantic' },
      { id: 'hip_hop_beat',     label: 'Hip-Hop Beat',     tag: 'sampled loops + 808' },
      { id: 'lo_fi_beats',      label: 'Lo-Fi Beats',      tag: 'dust, chill, study' },
      { id: 'world_fusion',     label: 'World Fusion',     tag: 'ethnic instrument blend' },
      { id: 'opera_aria',       label: 'Opera / Aria',     tag: 'vocal-forward grandeur' },
      { id: 'vaporwave',        label: 'Vaporwave',        tag: 'slowed + mallsoft' },
      { id: 'drum_bass',        label: 'Drum & Bass',      tag: 'breakbeat + sub' },
      { id: 'post_rock',        label: 'Post-Rock',        tag: 'build + crescendo' },
      { id: 'gregorian',        label: 'Gregorian Chant',  tag: 'male choir plainsong' },
      { id: 'dynamic_adaptive', label: 'Dynamic Adaptive', tag: 'vertical + horizontal re-mix' },
    ],
  },
  {
    key: 'design_style',
    label: 'Design Style',
    icon: 'layers-outline',
    color: '#8B5CF6',
    hint: 'UI/UX + spatial design philosophy.',
    options: [
      { id: 'minimalist',     label: 'Minimalist',      tag: 'negative space, tiny UI' },
      { id: 'brutalist',      label: 'Brutalist',       tag: 'raw, blocky, honest' },
      { id: 'art_deco',       label: 'Art Deco',        tag: 'gold, fans, geometric' },
      { id: 'bauhaus',        label: 'Bauhaus',         tag: 'primary colors + grids' },
      { id: 'cyberpunk',      label: 'Cyberpunk',       tag: 'neon + glass + chrome' },
      { id: 'steampunk',      label: 'Steampunk',       tag: 'brass + gears + leather' },
      { id: 'gothic',         label: 'Gothic',          tag: 'pointed arch + shadow' },
      { id: 'baroque',        label: 'Baroque',         tag: 'gilded, dramatic, ornate' },
      { id: 'art_nouveau',    label: 'Art Nouveau',     tag: 'vines, curves, stained' },
      { id: 'memphis',        label: 'Memphis',         tag: '80s squiggle party' },
      { id: 'swiss',          label: 'Swiss Intl.',     tag: 'grid + helvetica' },
      { id: 'skeuomorphic',   label: 'Skeuomorphic',    tag: 'real-object mimic' },
      { id: 'flat',           label: 'Flat',            tag: '2013 iOS7 era' },
      { id: 'neumorphic',     label: 'Neumorphic',      tag: 'soft shadow + emboss' },
      { id: 'y2k',            label: 'Y2K',             tag: 'gel + chrome + glassy' },
      { id: 'dieselpunk',     label: 'Dieselpunk',      tag: 'interwar brass + grease' },
      { id: 'solarpunk',      label: 'Solarpunk',       tag: 'green + hopeful + tile' },
      { id: 'vapor_retro',    label: 'Vapor Retro',     tag: 'windows95 + mall' },
    ],
  },
  {
    key: 'cinematic_style',
    label: 'Cinematic Style',
    icon: 'videocam-outline',
    color: '#DC2626',
    hint: 'Cutscene + camera sensibility.',
    options: [
      { id: 'hitchcock',      label: 'Hitchcock Suspense', tag: 'dolly, reveal, dread' },
      { id: 'kurosawa',       label: 'Kurosawa Sweep',     tag: 'wide + rain + wind' },
      { id: 'nolan',          label: 'Nolan Nonlinear',    tag: 'time-split + scale' },
      { id: 'tarantino',      label: 'Tarantino Dialogue', tag: 'long talk + split' },
      { id: 'kubrick',        label: 'Kubrick Symmetry',   tag: 'central perspective' },
      { id: 'scorsese',       label: 'Scorsese Energy',    tag: 'tracking shots + pop' },
      { id: 'villeneuve',     label: 'Villeneuve Scale',   tag: 'vast landscape + silent' },
      { id: 'miyazaki',       label: 'Miyazaki Wonder',    tag: 'wind + flight + stillness' },
      { id: 'wes_anderson',   label: 'Wes Anderson',       tag: 'centered dollhouse' },
      { id: 'fincher',        label: 'Fincher Noir',       tag: 'green-teal + clinical' },
      { id: 'coen',           label: 'Coen Brothers',      tag: 'ironic detachment' },
      { id: 'spielberg',      label: 'Spielberg Awe',      tag: 'lens-flare + face close' },
      { id: 'malick',         label: 'Malick Poetic',      tag: 'voice-over + sky' },
      { id: 'lynch',          label: 'Lynchian Dread',     tag: 'red room + hum' },
      { id: 'anime_shounen',  label: 'Anime Shounen',      tag: 'speed-lines + shout' },
      { id: 'noir_classic',   label: 'Noir Classic',       tag: 'blinds + fedora + rain' },
      { id: 'mockumentary',   label: 'Mockumentary',       tag: 'handheld + 4th wall' },
      { id: 'found_footage',  label: 'Found Footage',      tag: 'VHS + crack + drop' },
    ],
  },
  {
    key: 'director_style',
    label: 'Director Style',
    icon: 'megaphone-outline',
    color: '#3B82F6',
    hint: 'Which legendary director\'s sensibility should guide the swarm.',
    options: [
      { id: 'kojima',         label: 'Kojima Meta',          tag: '4th-wall + long cinematic' },
      { id: 'miyamoto',       label: 'Miyamoto Playful',     tag: 'pure joy-first mechanics' },
      { id: 'yoko_taro',      label: 'Yoko Taro Subversive', tag: 'structural subversion' },
      { id: 'miyazaki_fs',    label: 'Miyazaki (FromSoft)',  tag: 'punishing + mythic' },
      { id: 'druckmann',      label: 'Druckmann Trauma',     tag: 'character grief arcs' },
      { id: 'sakaguchi',      label: 'Sakaguchi Epic',       tag: 'grand-scale JRPG' },
      { id: 'sid_meier',      label: 'Sid Meier Systems',    tag: 'one more turn loops' },
      { id: 'todd_howard',    label: 'Todd Howard Sandbox',  tag: 'it just works' },
      { id: 'warren_spector', label: 'Warren Spector',       tag: 'immersive-sim emergent' },
      { id: 'suda51',         label: 'Suda51 Punk',          tag: 'chaotic art-violence' },
      { id: 'ken_levine',     label: 'Ken Levine',           tag: 'narrative-dense shooter' },
      { id: 'david_cage',     label: 'David Cage Dramatic',  tag: 'QTE-cinema' },
      { id: 'sid_toby',       label: 'Toby Fox Intimate',    tag: 'underground heart' },
      { id: 'amy_hennig',     label: 'Amy Hennig',           tag: 'pulpy set-piece' },
      { id: 'sam_lake',       label: 'Sam Lake',             tag: 'metatextual thriller' },
      { id: 'hironobu_uematsu',label: 'Sakimoto/Uematsu',    tag: 'lush composition-led' },
      { id: 'fumito_ueda',    label: 'Fumito Ueda',          tag: 'wordless relationship' },
      { id: 'tetsuya_nomura', label: 'Tetsuya Nomura',       tag: 'belts, zippers, drama' },
    ],
  },
  {
    key: 'dimension',
    label: 'Dimension',
    icon: 'cube-outline',
    color: '#22C55E',
    hint: '2D, fractional 2.xD depth layers, 3D + variants, and beyond.',
    options: [
      { id: '2d_pure',         label: '2D Pure',         tag: 'single plane sprite' },
      { id: '2d_parallax',     label: '2D Parallax',     tag: 'multiple scrolling layers' },
      { id: '2_5d',            label: '2.5D',            tag: '2D art on 3D space' },
      { id: '2_5d_isometric',  label: '2.5D Isometric',  tag: 'axonometric tile view' },
      { id: '2_6d',            label: '2.6D',            tag: 'sprite with billboard 3D bg' },
      { id: '2_7d',            label: '2.7D',            tag: '2.5D + parallax + depth cue' },
      { id: '2_8d',            label: '2.8D',            tag: 'sprite + 3D FX + light' },
      { id: '2_9d',            label: '2.9D',            tag: 'nearly full 3D w/ flat shade' },
      { id: '3d_basic',        label: '3D Basic',        tag: 'untextured polygons' },
      { id: '3d_pbr',          label: '3D PBR',          tag: 'physically-based rendering' },
      { id: '3d_rtx',          label: '3D RTX',          tag: 'ray-traced GI + reflections' },
      { id: '3d_photoreal',    label: '3D Photoreal',    tag: 'scanned-texture realism' },
      { id: '3d_stylized',     label: '3D Stylized',     tag: 'toon / painterly 3D' },
      { id: '3d_voxel',        label: '3D Voxel',        tag: 'blocky voxel geometry' },
      { id: '3d_procedural',   label: '3D Procedural',   tag: 'SDF / generated meshes' },
      { id: 'vr_3d',           label: 'VR 3D',           tag: 'head-tracked stereoscopic' },
      { id: 'ar_mixed',        label: 'AR Mixed',        tag: 'camera-composited real+CG' },
      { id: '4d_temporal',     label: '4D Temporal',     tag: 'time-layered scrubbable' },
    ],
  },
  {
    key: 'asset_style',
    label: 'Asset Style',
    icon: 'cube',
    color: '#F97316',
    hint: 'How props / environments / FX assets are authored.',
    options: [
      { id: 'stylized_handpainted',label: 'Hand-Painted',    tag: 'texture-paint art-directed' },
      { id: 'realistic_pbr',       label: 'Realistic PBR',   tag: 'metalness + roughness' },
      { id: 'pixel_sprite',        label: 'Pixel Sprite',    tag: '16/32-bit sprite sheets' },
      { id: 'voxel_cubic',         label: 'Voxel Cubic',     tag: 'magicavoxel blocks' },
      { id: 'low_poly_flat',       label: 'Low-Poly Flat',   tag: 'flat-shaded faceted' },
      { id: 'high_poly_sculpt',    label: 'High-Poly Sculpt',tag: 'zbrush micro-detail' },
      { id: 'toon_outlined',       label: 'Toon Outlined',   tag: 'inked silhouette' },
      { id: 'procedural_generated',label: 'Procedural',      tag: 'rule-driven assets' },
      { id: 'photogrammetry',      label: 'Photogrammetry',  tag: 'scanned real objects' },
      { id: 'ai_generated',        label: 'AI-Generated',    tag: 'model-synth + pass' },
      { id: 'modular_kitbash',     label: 'Modular Kitbash', tag: 'snap-together parts' },
      { id: 'paper_cutout',        label: 'Paper Cutout',    tag: 'layered 2D collage' },
      { id: 'claymation_sculpt',   label: 'Claymation',      tag: 'dough fingerprint' },
      { id: 'vector_svg',          label: 'Vector SVG',      tag: 'scale-perfect vectors' },
    ],
  },
  {
    key: 'model_style',
    label: 'Model Style',
    icon: 'person-outline',
    color: '#A855F7',
    hint: 'Character / creature proportion + rigging philosophy.',
    options: [
      { id: 'realistic_anatomy', label: 'Realistic Anatomy',  tag: 'anatomically accurate' },
      { id: 'stylized_exagg',    label: 'Stylized Exaggerated',tag: 'big hands, heroic' },
      { id: 'chibi',             label: 'Chibi',              tag: '3-head-tall cute' },
      { id: 'heroic_8head',      label: 'Heroic 8-head',      tag: 'comic-book idealized' },
      { id: 'low_poly_retro',    label: 'Low-Poly Retro',     tag: 'PS1 / N64 chunk' },
      { id: 'pixel_character',   label: 'Pixel Character',    tag: 'pixel art + rig' },
      { id: 'voxel_block',       label: 'Voxel Block',        tag: 'cube stacks' },
      { id: 'paper_cutout',      label: 'Paper Cutout',       tag: 'flat joint puppet' },
      { id: 'rigged_skeletal',   label: 'Rigged Skeletal',    tag: 'full bone + IK' },
      { id: 'photogrammetry_scan',label: 'Photogram. Scan',   tag: 'real actor cap' },
      { id: 'mocap_drive',       label: 'Motion-Cap Driven',  tag: 'realistic motion' },
      { id: 'keyframe_anim',     label: 'Keyframe Animated',  tag: 'hand-posed frames' },
      { id: 'procedural_rigged', label: 'Procedural Rig',     tag: 'driven by game state' },
      { id: 'muppet_felt',       label: 'Muppet / Felt',      tag: 'fabric + seam charm' },
      { id: 'mech_hard_surface', label: 'Mech Hard-Surface',  tag: 'engineered precision' },
    ],
  },
];

// Build default selection = first option of each slider
export const DEFAULT_STYLE_PARAMS: Record<string, string> = STYLE_SLIDERS.reduce((acc, s) => {
  acc[s.key] = s.options[0].id;
  return acc;
}, {} as Record<string, string>);
