"""
╔══════════════════════════════════════════════════════════════════════════╗
║  BUG/FIX MEGASCALE — 500+ BUGS ACROSS EVERY FRAMEWORK & LANGUAGE      ║
║  Complete offline debugging encyclopedia                                ║
║  Every error message, every root cause, every fix, every prevention    ║
╚══════════════════════════════════════════════════════════════════════════╝
"""
import hashlib

def _fid(cat, title):
    return f"bugfix_{hashlib.md5(f'{cat}_{title}'.encode()).hexdigest()[:10]}"

def _b(title, error, cause, fix, prevention, severity, tags):
    return {"title": title, "error": error, "cause": cause, "fix": fix, "prevention": prevention, "severity": severity, "tags": tags}

def get_mega_bugfix_library():
    entries = []
    _BUGS = {
        "python": [
            _b("ModuleNotFoundError: No module named 'X'","ModuleNotFoundError","Package not installed or venv not activated","pip install X or activate venv","Use requirements.txt, pin versions","common",["import","pip","venv"]),
            _b("IndentationError: unexpected indent","IndentationError","Mixed tabs and spaces","Use 4 spaces consistently, run tabnanny","Editor auto-indent, show whitespace","common",["syntax","whitespace"]),
            _b("TypeError: 'NoneType' not subscriptable","TypeError","Accessing index on None","Add None check: if result is not None","Optional type hints, handle None","common",["none","type"]),
            _b("RecursionError: max depth exceeded","RecursionError","Infinite/deep recursion","Add base case, use iteration, sys.setrecursionlimit()","Always define base cases","medium",["recursion","stack"]),
            _b("UnicodeDecodeError: 'utf-8' can't decode","UnicodeDecodeError","File not UTF-8","open(file, encoding='latin-1') or chardet","Always specify encoding","common",["encoding","unicode"]),
            _b("MemoryError: unable to allocate","MemoryError","Data too large for RAM","Generators, chunked processing, mmap","Process in chunks","medium",["memory","large-data"]),
            _b("GIL blocking concurrent execution","Performance","GIL prevents CPU parallelism","multiprocessing, asyncio for I/O, C extensions","Choose right concurrency model","advanced",["concurrency","gil"]),
            _b("Circular import error","ImportError","Two modules importing each other","Move imports inside functions, restructure","Follow dependency hierarchy","medium",["import","circular"]),
            _b("asyncio.run() in running loop","RuntimeError","Nested event loops","Use await directly, nest_asyncio for Jupyter","Don't mix sync/async","common",["asyncio","event-loop"]),
            _b("Mutable default argument","Logic Bug","def f(items=[]): shared across calls","Use None default: items = items or []","Never use mutable defaults","common",["mutable","default"]),
            _b("SyntaxError: invalid syntax (Python 2 vs 3)","SyntaxError","Python 2 syntax in Python 3","Update print(), remove u'', use //","Use Python 3 only","common",["syntax","migration"]),
            _b("AttributeError: module has no attribute","AttributeError","Wrong module version or shadowing","Check import path, rename conflicting files","Don't name files same as modules","common",["attribute","import"]),
            _b("pickle.UnpicklingError","UnpicklingError","Protocol mismatch or corrupt data","Match pickle protocol versions","Use JSON for interop","medium",["pickle","serialization"]),
            _b("KeyError in dictionary access","KeyError","Key doesn't exist in dict","Use .get(key, default) or try/except","Always use .get() with default","common",["dict","key"]),
            _b("TypeError: unhashable type: 'list'","TypeError","Using list as dict key or set member","Convert to tuple: tuple(my_list)","Use immutable types for keys","common",["hash","dict","set"]),
            _b("FileNotFoundError","FileNotFoundError","Wrong path or missing file","Use pathlib, check os.path.exists()","Use pathlib.Path, relative paths","common",["file","path"]),
            _b("ValueError: too many values to unpack","ValueError","Tuple unpacking count mismatch","Match variable count or use *rest","Verify data structure shape","common",["unpack","tuple"]),
            _b("pip install fails with permission error","PermissionError","Installing to system Python","Use --user flag or virtual environment","Always use virtual environments","common",["pip","permission","venv"]),
            _b("Django ORM N+1 queries","Performance","Lazy loading in loops","Use select_related() and prefetch_related()","Always prefetch related data","high",["django","orm","n+1"]),
            _b("Flask CORS not working","CORS","Missing CORS headers","flask-cors: CORS(app)","Configure CORS from start","common",["flask","cors","web"]),
            _b("Pandas SettingWithCopyWarning","Warning","Chained indexing creates copy","Use .loc[] for assignment","Always use explicit .loc/.iloc","common",["pandas","copy","dataframe"]),
            _b("NumPy broadcasting shape mismatch","ValueError","Incompatible array shapes","Reshape arrays, check dimensions","Verify shapes before operations","common",["numpy","shape","broadcast"]),
            _b("SQLAlchemy detached instance","DetachedInstanceError","Accessing lazy attribute after session close","Use eager loading or keep session open","Configure relationship loading","medium",["sqlalchemy","session","orm"]),
            _b("FastAPI 422 Unprocessable Entity","422 Error","Request body/params don't match Pydantic model","Fix request to match model schema","Use proper Pydantic models","common",["fastapi","pydantic","validation"]),
            _b("Celery task not found","NotRegistered","Task not imported by worker","Import tasks in celery app, check autodiscover","Register tasks properly","medium",["celery","task","worker"]),
        ],
        "javascript": [
            _b("TypeError: Cannot read properties of undefined","TypeError","Accessing property on undefined","Use optional chaining: obj?.prop","Enable TypeScript, use ?.","common",["undefined","null"]),
            _b("ReferenceError: X is not defined","ReferenceError","Variable used before declaration","Declare before use, check scope","Use let/const, strict mode","common",["scope","hoisting"]),
            _b("Promise rejection unhandled","UnhandledPromiseRejection","Missing .catch() or try/catch with await","Add .catch(), try/catch every await","Global unhandledRejection handler","medium",["promise","async","error"]),
            _b("CORS error: No Access-Control-Allow-Origin","CORS","Browser blocking cross-origin","CORS headers on server, dev proxy","Configure CORS middleware","common",["cors","fetch","browser"]),
            _b("Maximum call stack size exceeded","RangeError","Infinite recursion or circular JSON","Add base case, use structuredClone","Guard recursion, avoid circular refs","medium",["recursion","stack"]),
            _b("Event listener memory leak","Memory Leak","Listeners not removed on unmount","removeEventListener in cleanup","Always pair add/remove, use AbortController","medium",["memory","event","spa"]),
            _b("'this' is undefined in callback","TypeError","Lost 'this' binding","Arrow functions, .bind(this), class fields","Use arrow function class fields","common",["this","binding"]),
            _b("0.1 + 0.2 !== 0.3","Logic Bug","IEEE 754 floating point","Math.abs(a-b) < Number.EPSILON","Use integers for currency","common",["float","precision"]),
            _b("Module not found in bundler","Build Error","Missing dep or wrong path","Install package, check case sensitivity","TypeScript path aliases","common",["webpack","vite","import"]),
            _b("SyntaxError: Unexpected token '<'","SyntaxError","HTML returned instead of JS (404/proxy issue)","Fix API URL, check proxy config","Verify build output paths","common",["syntax","html","proxy"]),
            _b("TypeError: X is not a function","TypeError","Calling non-function value","Check import, verify it's a function","TypeScript catches this at compile","common",["function","type"]),
            _b("Cannot use import outside a module","SyntaxError","Using ESM in CJS context","Add type:module to package.json or use .mjs","Configure module system consistently","common",["esm","cjs","module"]),
            _b("localStorage not available (SSR)","ReferenceError","Accessing browser API on server","Check typeof window !== 'undefined'","Use isClient guard, useEffect","common",["ssr","window","browser"]),
            _b("Infinite loop in useEffect","Infinite Loop","Object/array dependency changes every render","useMemo/useCallback for deps","Primitive deps, memoize objects","common",["react","useEffect","loop"]),
            _b("fetch() CORS preflight fails","CORS","OPTIONS request blocked","Handle OPTIONS on server, check headers","Configure CORS for all methods","medium",["cors","preflight","options"]),
            _b("JSON.parse unexpected end of input","SyntaxError","Incomplete or empty JSON response","Check response status before parsing","Validate response.ok first","common",["json","parse","api"]),
            _b("Uncaught DOMException: Blocked frame","SecurityError","Cross-origin iframe access","Use postMessage for cross-origin comms","Configure proper CORS/CSP","medium",["iframe","security","cross-origin"]),
            _b("AbortError: signal is aborted","AbortError","Request cancelled via AbortController","Handle abort in catch, check signal","Cleanup AbortController on unmount","common",["abort","fetch","cancel"]),
            _b("Node.js EventEmitter memory leak warning","Warning",">10 listeners on single event","Increase maxListeners or fix listener leak","Remove listeners properly","medium",["node","events","memory"]),
            _b("npm/yarn peer dependency conflict","Dependency","Incompatible package versions","--legacy-peer-deps or align versions","Pin versions, use lockfiles","common",["npm","yarn","dependency"]),
            _b("Webpack chunk loading failed","ChunkLoadError","Network error or deployment mismatch","Retry logic, force refresh on version change","Cache busting, service worker update","medium",["webpack","chunk","deployment"]),
            _b("process.env undefined in browser","ReferenceError","Server env vars in client code","Use NEXT_PUBLIC_ or VITE_ prefix","Prefix client env vars correctly","common",["env","client","build"]),
        ],
        "typescript": [
            _b("Type 'X' not assignable to type 'Y'","TS2322","Type mismatch","Fix type or cast with 'as'","Enable strict mode","common",["type","assignment"]),
            _b("Property 'X' does not exist on type 'Y'","TS2339","Property not in type def","Add to interface or type guard","Keep types in sync","common",["property","interface"]),
            _b("Object is possibly 'undefined'","TS2532","Strict null checks","Null check, ?., or !","Handle all nullable types","common",["null","undefined"]),
            _b("Generic type inference fails","TS2345","Can't infer generic","Explicit type: fn<Type>(arg)","Simpler generic signatures","medium",["generics","inference"]),
            _b("Missing .d.ts for module","TS7016","No TypeScript types for package","Install @types/X or declare module","Prefer typed packages","common",["declaration","types"]),
            _b("Type instantiation is excessively deep","TS2589","Recursive type too deep","Simplify type, add recursion limit","Limit type recursion depth","advanced",["recursive","type","deep"]),
            _b("Cannot find module or its type declarations","TS2307","Module not found or untyped","Install types, configure paths","tsconfig paths, module resolution","common",["module","resolution"]),
            _b("Argument of type string not assignable to enum","TS2345","String literal vs enum type","Use as const or enum member directly","Use const assertions","common",["enum","string","literal"]),
            _b("Index signature missing","TS7053","Dynamic property access on typed object","Add index signature or use Record","Use Record<string, T> for dynamic keys","medium",["index","signature","dynamic"]),
            _b("Decorator metadata not emitted","TS1240","experimentalDecorators not enabled","Enable in tsconfig: experimentalDecorators: true","Configure decorators in tsconfig","common",["decorator","config"]),
            _b("Excess property check fails","TS2353","Extra properties in object literal","Spread or cast to interface","Use Omit/Pick utility types","common",["excess","property","object"]),
            _b("Circular reference in type","TS2456","Types reference each other","Use interface instead of type alias","Interfaces handle circular refs better","medium",["circular","type","interface"]),
        ],
        "react": [
            _b("Too many re-renders","Infinite Loop","setState during render","Move to useEffect or handler","Never setState in render body","common",["render","loop"]),
            _b("Missing unique 'key' prop","Warning","No key in mapped elements","Add unique key: key={item.id}","Use stable IDs, never array index","common",["key","list"]),
            _b("Cannot update component while rendering different","Warning","Parent setState from child render","useEffect for cross-component updates","Don't trigger parent updates in render","medium",["render","state"]),
            _b("useEffect runs every render","Performance","Missing/wrong dependency array","Add correct deps: [dep1, dep2]","eslint-plugin-react-hooks","common",["useEffect","deps"]),
            _b("Stale closure in hooks","Logic Bug","Closure captures old value","Add to deps, useRef for mutable","Understand closures in hooks","medium",["closure","stale"]),
            _b("Hydration mismatch (SSR)","Hydration Error","Server/client HTML differs","suppressHydrationWarning, useEffect for client-only","Avoid Date.now() in render","medium",["ssr","hydration"]),
            _b("Memory leak on unmounted component","Warning","Async op after unmount","AbortController, useEffect cleanup","Always cleanup async ops","common",["memory","unmount"]),
            _b("Cannot read property of null (ref)","TypeError","Ref not attached yet","Check ref.current before use","useEffect to access refs","common",["ref","null","lifecycle"]),
            _b("Context re-renders all consumers","Performance","Context value changes every render","useMemo context value, split contexts","Memoize context values","medium",["context","rerender","memo"]),
            _b("React.Children.only expects single child","Error","Wrapper expects one child, got many","Wrap in fragment or single element","Check component children contract","common",["children","fragment"]),
            _b("Invalid hook call outside component","Error","Hook in non-component function","Only call hooks at top level of components","Follow Rules of Hooks","common",["hook","rules"]),
            _b("Suspense boundary missing","Error","Lazy component without Suspense","Wrap with <Suspense fallback={...}>","Always wrap lazy with Suspense","common",["suspense","lazy"]),
            _b("State not updating immediately","Confusion","setState is async/batched","Use functional update or useEffect","Understand batched updates","common",["state","batch","async"]),
            _b("React DevTools shows anonymous components","DX","Missing displayName","Name functions: const MyComp = () => {}","Use named function expressions","low",["devtools","debug","name"]),
            _b("useCallback doesn't prevent re-render","Performance","Child not memoized","React.memo on child component","Memo both callback AND child","medium",["useCallback","memo","rerender"]),
        ],
        "react_native": [
            _b("Red screen: undefined is not an object","TypeError","Accessing property of undefined on mobile","Add null checks, optional chaining","Enable TypeScript strict mode","common",["crash","undefined","mobile"]),
            _b("VirtualizedList should never be nested","Warning","FlatList inside ScrollView","Use ListHeaderComponent/ListFooterComponent","Don't nest scrollable lists","common",["flatlist","scrollview","nested"]),
            _b("Invariant Violation: Text strings must be rendered within <Text>","Error","Raw string outside Text component","Wrap all text in <Text>","All text must be in <Text>","common",["text","component","render"]),
            _b("Metro bundler cache issue","Build Error","Stale cache causing build failures","npx react-native start --reset-cache","Clear cache after dep changes","common",["metro","cache","build"]),
            _b("Native module not found","Error","Missing native dependency link","npx pod-install, rebuild native","Run pod install after native deps","medium",["native","module","pod"]),
            _b("Gesture handler not working","Bug","Missing GestureHandlerRootView","Wrap app in GestureHandlerRootView","Always wrap root with gesture handler","common",["gesture","handler","root"]),
            _b("Image not loading on device","Bug","HTTP URL blocked by App Transport Security","Use HTTPS or configure ATS exceptions","Use HTTPS for all images","common",["image","http","ats"]),
            _b("StatusBar overlapping content","UI Bug","No safe area handling","Use SafeAreaView or useSafeAreaInsets","Always handle safe areas","common",["statusbar","safearea","insets"]),
            _b("Keyboard covers input fields","UI Bug","No keyboard avoidance","KeyboardAvoidingView with correct behavior","Add keyboard handling to all forms","common",["keyboard","input","form"]),
            _b("Hermes crash on complex regex","Crash","Hermes doesn't support all regex features","Simplify regex or use polyfill","Test regex with Hermes engine","medium",["hermes","regex","crash"]),
        ],
        "nextjs": [
            _b("Error: NEXT_PUBLIC_ env var undefined","Config","Client env var missing prefix","Prefix with NEXT_PUBLIC_","Always use NEXT_PUBLIC_ for client","common",["env","client","config"]),
            _b("Error: Dynamic server usage","Build Error","Static page uses dynamic features","Add force-dynamic or revalidate","Understand static vs dynamic rendering","medium",["static","dynamic","build"]),
            _b("getServerSideProps returns undefined","Bug","Missing return statement","return { props: {} }","Always return props object","common",["ssr","props","return"]),
            _b("Middleware redirecting infinitely","Infinite Loop","Middleware matches its own redirect target","Add path condition: if (!path.startsWith('/login'))","Exclude redirect target from matcher","medium",["middleware","redirect","loop"]),
            _b("Image optimization not working","Bug","External images not configured","Add domains to next.config.js images","Configure image domains","common",["image","optimization","config"]),
            _b("Cannot use useState in Server Component","Error","Client hook in server component","Add 'use client' directive","Separate client and server components","common",["server-component","client","hooks"]),
            _b("Revalidation not working","Cache","ISR cache not invalidating","revalidatePath/revalidateTag, check config","Understand Next.js caching layers","medium",["isr","cache","revalidate"]),
            _b("API route returning HTML instead of JSON","Bug","Wrong content type or error page","Set Content-Type header, check route path","Return NextResponse.json()","common",["api","json","content-type"]),
        ],
        "rust": [
            _b("Cannot borrow as mutable more than once","E0499","Multiple mutable borrows","Limit borrow scope, use RefCell","Minimize mutable borrow lifetimes","common",["borrow","mutable"]),
            _b("Value used after move","E0382","Value moved to new owner","Clone, pass reference, restructure","Prefer references over moves","common",["move","ownership"]),
            _b("Lifetime may not live long enough","E0597","Reference outlives data","Add lifetime annotations, restructure","Use owned types for complex lifetimes","medium",["lifetime","reference"]),
            _b("Trait Send not implemented","E0277","Type not thread-safe","Arc<Mutex<T>>, use Send-safe types","Use thread-safe types from start","medium",["send","sync","threads"]),
            _b("Cannot find macro in scope","E0433","Macro not imported","#[macro_use] or use path","Understand macro import rules","common",["macro","import"]),
            _b("Trait object not safe","E0038","Method has Self or generics","Use enum dispatch or Box<dyn Trait>","Understand object safety rules","medium",["trait","object","dispatch"]),
            _b("Deadlock with Mutex","Logic Bug","Lock ordering inconsistency","Consistent lock ordering, try_lock","Document lock ordering","high",["mutex","deadlock","concurrency"]),
            _b("Stack overflow in recursive type","E0072","Recursive struct without indirection","Use Box<T> for recursive types","Box recursive fields","common",["recursive","type","box"]),
            _b("Tokio runtime panicking","Panic","Blocking in async context","Use spawn_blocking for blocking ops","Never block in async functions","high",["tokio","async","blocking"]),
            _b("Cannot return reference to local","E0515","Returning ref to stack variable","Return owned value or use Cow","Return owned types from functions","common",["reference","local","return"]),
        ],
        "go": [
            _b("Goroutine leak","Resource Leak","Channel never closed","context.WithCancel, defer close(ch)","Always have exit strategy","medium",["goroutine","channel","leak"]),
            _b("Data race","Data Race","Concurrent read/write without sync","sync.Mutex, atomic, channels","Run tests with -race flag","high",["race","concurrency","mutex"]),
            _b("Nil pointer dereference","Panic","Dereferencing nil pointer","Add nil checks before dereference","Initialize all pointers","common",["nil","pointer","panic"]),
            _b("Interface conversion panic","Panic","Type assertion on nil","Comma-ok: val, ok := iface.(Type)","Always two-value assertion","common",["interface","assertion"]),
            _b("Slice append gotcha","Logic Bug","Append may or may not create new backing array","Use copy for independent slices","Understand slice headers","medium",["slice","append","gotcha"]),
            _b("Context cancelled","Context Error","Parent context cancelled or timed out","Check ctx.Err(), handle gracefully","Use appropriate context timeouts","common",["context","cancel","timeout"]),
            _b("Map concurrent write panic","Panic","Writing to map from multiple goroutines","sync.Map or mutex-protected map","Use sync.Map for concurrent access","high",["map","concurrent","panic"]),
            _b("defer runs after return","Confusion","Defer modifies named return value","Understand defer execution order","Use named returns carefully with defer","common",["defer","return","gotcha"]),
            _b("Import cycle","Build Error","Packages import each other","Extract interface, restructure packages","Follow dependency direction","medium",["import","cycle","package"]),
            _b("Error wrapping lost","Bug","fmt.Errorf without %w verb","Use %w: fmt.Errorf('failed: %w', err)","Always use %w for error wrapping","common",["error","wrapping","fmt"]),
        ],
        "cpp": [
            _b("Segmentation fault","SIGSEGV","Invalid memory access","valgrind/ASan, smart pointers","Smart pointers, ASan in CI","critical",["segfault","memory","pointer"]),
            _b("Undefined behavior: signed overflow","UB","Signed integer overflow","Use unsigned or check bounds, -fwrapv","UBSan, safe integer libs","high",["ub","overflow","integer"]),
            _b("Double free or corruption","Memory Error","Freeing same memory twice","nullptr after free, use unique_ptr","RAII, smart pointers always","critical",["double-free","memory","raii"]),
            _b("Template error messages unreadable","Compile Error","Deep template instantiation","C++20 concepts, static_assert","Use concepts for constraints","common",["template","error","concepts"]),
            _b("Dangling reference","UB","Reference to destroyed object","Return by value, extend lifetime","Understand reference lifetime rules","high",["dangling","reference","lifetime"]),
            _b("ODR violation (linker error)","Linker Error","Same symbol defined in multiple TUs","Inline functions, anonymous namespace","Use inline, modules (C++20)","medium",["odr","linker","inline"]),
            _b("Exception safety violation","Logic Bug","Resource leak on exception","RAII for all resources","Follow RAII pattern","medium",["exception","raii","safety"]),
            _b("Static initialization order fiasco","UB","Global static init order undefined","Meyers singleton, construct-on-first-use","Avoid global statics","medium",["static","initialization","order"]),
            _b("Iterator invalidation","UB","Container modified during iteration","Use erase return value, separate pass","Know invalidation rules per container","high",["iterator","invalidation","container"]),
            _b("ABI compatibility break","Linker Error","Library compiled with different compiler/flags","Recompile all with same toolchain","Use stable ABI boundaries","medium",["abi","linker","compatibility"]),
        ],
        "java": [
            _b("NullPointerException","NPE","Calling method on null","Optional<T>, @NonNull annotations","Use Optional everywhere","common",["null","npe","optional"]),
            _b("ConcurrentModificationException","CME","Modifying collection while iterating","Iterator.remove(), CopyOnWriteArrayList","Concurrent collections","common",["concurrent","collection"]),
            _b("ClassCastException","CCE","Invalid runtime cast","instanceof check, generics","Use generics, pattern matching","common",["cast","type","generics"]),
            _b("OutOfMemoryError: heap space","OOM","JVM heap exhausted","Increase -Xmx, profile, fix leaks","Regular profiling, appropriate heap","high",["oom","heap","memory"]),
            _b("StackOverflowError","StackOverflow","Deep/infinite recursion","Add base case, increase stack with -Xss","Guard recursion depth","common",["recursion","stack"]),
            _b("NoClassDefFoundError","ClassLoading","Class found at compile, missing at runtime","Check classpath, dependency versions","Maven/Gradle dependency management","medium",["classpath","classloading"]),
            _b("Deadlock in synchronized blocks","Deadlock","Lock ordering inconsistency","Consistent lock ordering, timeout locks","Use java.util.concurrent instead","high",["deadlock","synchronized"]),
            _b("Spring circular dependency","BeanCreation","Two beans depend on each other","@Lazy annotation, restructure","Avoid circular dependencies","medium",["spring","circular","dependency"]),
            _b("Hibernate LazyInitializationException","LazyInit","Accessing lazy collection outside session","Fetch eagerly or keep session open","Configure fetch strategy","common",["hibernate","lazy","session"]),
            _b("Maven dependency conflict","Build","Multiple versions of same library","dependencyManagement, exclusions","Use BOM, check dependency tree","common",["maven","dependency","conflict"]),
        ],
        "database": [
            _b("N+1 query problem","Performance","N queries in loop instead of join","JOIN, eager loading, batch queries","Review query logs, DataLoader","high",["n+1","performance","orm"]),
            _b("Deadlock detected","Deadlock","Transactions waiting on each other","Consistent lock ordering, retry with backoff","Short transactions, consistent ordering","high",["deadlock","transaction"]),
            _b("Connection pool exhausted","Connection Error","Too many open connections","Close properly, increase pool, timeout","Context managers, monitor connections","high",["pool","connection"]),
            _b("Slow query: full table scan","Performance","Missing index","Add index, EXPLAIN ANALYZE","Index all WHERE/JOIN/ORDER columns","high",["index","performance","scan"]),
            _b("Migration conflict","Migration Error","Conflicting migrations","Resolve conflicts, squash","Coordinate migrations, test first","medium",["migration","schema"]),
            _b("MongoDB ObjectId not serializable","TypeError","BSON ObjectId in JSON","Exclude _id or str(doc['_id'])","Always {_id: 0} projection","common",["mongodb","objectid","json"]),
            _b("PostgreSQL vacuum not running","Performance","Table bloat, slow queries","Manual VACUUM FULL, tune autovacuum","Monitor autovacuum, tune settings","high",["postgres","vacuum","bloat"]),
            _b("MySQL too many connections","Connection Error","max_connections reached","Increase max_connections, use pooling","Connection pooling, close properly","high",["mysql","connections","pool"]),
            _b("Redis memory full","OOM","No eviction policy set","Set maxmemory-policy, increase memory","Configure eviction, monitor memory","high",["redis","memory","eviction"]),
            _b("SQL injection via string concatenation","Security","User input in raw SQL","Parameterized queries ALWAYS","ORM, input validation, never concat","critical",["sql","injection","security"]),
            _b("Unique constraint violation","IntegrityError","Duplicate key insertion","Handle conflict: ON CONFLICT DO UPDATE","Check existence before insert, upsert","common",["unique","constraint","duplicate"]),
            _b("Foreign key constraint prevents deletion","IntegrityError","Referenced row still exists","Delete children first, or CASCADE","Configure CASCADE rules","common",["foreign-key","cascade","delete"]),
            _b("Query returns wrong results with NULL","Logic Bug","NULL comparison with = instead of IS","Use IS NULL, COALESCE, IS DISTINCT FROM","Understand NULL semantics","common",["null","comparison","sql"]),
            _b("Index not being used","Performance","Query planner chooses seq scan","ANALYZE table, check statistics, rewrite query","Keep statistics fresh, check query plans","medium",["index","planner","statistics"]),
        ],
        "docker_k8s": [
            _b("OOMKilled","OOMKilled","Container exceeds memory limit","Increase limit, optimize app","Set appropriate limits, profile","high",["oom","memory","container"]),
            _b("CrashLoopBackOff","CrashLoopBackOff","Container crashes on start","kubectl logs, fix app error, check probes","Test locally, proper probes","high",["kubernetes","crash","pod"]),
            _b("ImagePullBackOff","ImagePullBackOff","Can't pull image","Verify image/tag, check pullSecrets","Image digests, private registry","common",["kubernetes","image","pull"]),
            _b("EADDRINUSE: port already in use","EADDRINUSE","Port already bound","lsof -i :PORT, kill process","Dynamic ports, check availability","common",["port","network","bind"]),
            _b("DNS resolution failure in container","Network Error","DNS not configured","Check resolv.conf, network policy","K8s service DNS, test connectivity","medium",["dns","network","container"]),
            _b("Pod stuck in Pending","Scheduling","Insufficient resources or node affinity","Check events: kubectl describe pod","Resource quotas, node labels","medium",["pending","scheduling","resources"]),
            _b("PVC stuck in Pending","Storage","No matching PV or StorageClass","Check StorageClass, provisioner","Verify storage provisioner","medium",["pvc","storage","pending"]),
            _b("Ingress 502 Bad Gateway","Network","Backend not ready or timeout","Check service/endpoints, increase timeout","Readiness probes, proper timeouts","common",["ingress","502","gateway"]),
            _b("Docker build cache not working","Build","Changed COPY invalidates cache","Order Dockerfile: deps before code","Layer ordering optimization","common",["docker","cache","build"]),
            _b("ConfigMap/Secret not updating in pod","Config","Mounted volumes cached by kubelet","Restart pod or use subPath","Use immutable configs, rolling restart","common",["configmap","secret","update"]),
            _b("Node NotReady","Node Issue","Kubelet not responding, resource exhaustion","Check node: kubectl describe node, fix disk/mem","Monitor node health, proper limits","high",["node","notready","kubelet"]),
            _b("Service not reachable","Network","Selector doesn't match pod labels","Check labels match between service and pods","Label consistency, kube-proxy check","common",["service","selector","labels"]),
        ],
        "git": [
            _b("Merge conflict","Conflict","Same lines changed in branches","Edit markers, choose changes, commit","Pull often, small PRs","common",["merge","conflict"]),
            _b("Detached HEAD","Detached HEAD","Checked out commit not branch","git checkout -b new-branch","Checkout branches not commits","common",["head","checkout"]),
            _b("Committed secrets","Security","API keys in repo","BFG/filter-branch, rotate all keys",".gitignore, pre-commit hooks","critical",["secrets","security"]),
            _b("Lost commits after force push","Data Loss","Force push overwrote history","git reflog, cherry-pick to recover","Never force push shared branches","high",["force-push","reflog"]),
            _b("Large file rejected by push","Push Error","File exceeds size limit","git-lfs, remove large file from history","Configure .gitattributes for LFS","common",["large-file","lfs","push"]),
            _b("Submodule out of sync","Submodule","Submodule not updated","git submodule update --init --recursive","Document submodule workflow","medium",["submodule","sync","update"]),
            _b("Rebase conflict resolution loop","Rebase","Same conflict on multiple commits","git rebase --skip or resolve carefully","Consider merge instead of rebase","medium",["rebase","conflict","loop"]),
            _b("Accidentally committed to wrong branch","Branch","Changes on wrong branch","git stash, checkout correct, stash pop","Check branch before committing","common",["branch","stash","wrong"]),
        ],
        "web_security": [
            _b("SQL Injection","Security","User input in raw SQL","Parameterized queries ALWAYS","ORM, never concatenate","critical",["sql","injection"]),
            _b("Cross-Site Scripting (XSS)","Security","Unescaped user input in HTML","Escape output, CSP headers, DOMPurify","Framework auto-escaping","critical",["xss","html","escaping"]),
            _b("CSRF","Security","Forged authenticated requests","CSRF tokens, SameSite cookies","CSRF middleware","high",["csrf","token","cookie"]),
            _b("IDOR","Security","Access other users' data by ID","Verify ownership for every access","Always check authorization","high",["idor","authorization"]),
            _b("JWT not validated","Security","Signature/expiry not checked","Verify signature, check claims","Use tested JWT library","critical",["jwt","token","auth"]),
            _b("Open redirect","Security","Unvalidated redirect URL","Whitelist allowed redirect domains","Validate all redirect URLs","medium",["redirect","open","url"]),
            _b("Sensitive data in URL","Security","Tokens/passwords in query params","Use POST body or headers","Never put secrets in URLs","medium",["url","sensitive","query"]),
            _b("Missing rate limiting","Security","No request throttling","Add rate limiter middleware","Rate limit all public endpoints","high",["rate-limit","ddos","throttle"]),
            _b("Insecure deserialization","Security","Untrusted data deserialized","Use safe formats (JSON), validate","Never deserialize untrusted data","critical",["deserialization","rce"]),
            _b("SSRF","Security","Server makes request to attacker-controlled URL","Validate/whitelist URLs, block internal IPs","Input validation on all URLs","critical",["ssrf","request","forgery"]),
            _b("Clickjacking","Security","Page embedded in malicious iframe","X-Frame-Options: DENY, CSP frame-ancestors","Set X-Frame-Options header","medium",["clickjacking","iframe","header"]),
            _b("Missing HTTPS","Security","Data transmitted in plaintext","Enable TLS, redirect HTTP to HTTPS","HSTS header, auto-redirect","critical",["https","tls","plaintext"]),
        ],
        "performance": [
            _b("Memory leak in long-running app","Memory Leak","Objects not garbage collected","Heap snapshots, remove listeners, bound caches","Regular profiling, WeakRef","high",["memory","leak","gc"]),
            _b("Slow API response","Performance","N+1, no cache, bad queries","Cache (Redis), optimize queries, pagination","Cache hot paths, index, profile early","high",["api","latency","cache"]),
            _b("Bundle too large","Performance","No code splitting or tree shaking","Dynamic imports, bundle analyzer","Check bundle size in CI","medium",["bundle","splitting","treeshaking"]),
            _b("High CPU from bad algorithm","Performance","O(n²) or worse","Better data structures, optimize","Analyze complexity, benchmark","high",["cpu","algorithm","complexity"]),
            _b("Database connection pool starvation","Performance","Long-held connections","Configure timeouts, fix long queries","Connection pool monitoring","high",["pool","database","timeout"]),
            _b("Excessive re-rendering","Performance","Unnecessary React re-renders","React.memo, useMemo, useCallback","React DevTools Profiler","medium",["react","rerender","memo"]),
            _b("Large image loading on mobile","Performance","Unoptimized images served","Responsive images, WebP, lazy loading","Image optimization pipeline","medium",["image","mobile","optimization"]),
            _b("Cold start latency (serverless)","Performance","Function initialization slow","Minimize dependencies, provisioned concurrency","Bundle size, connection pooling","medium",["serverless","cold-start","lambda"]),
        ],
        "devops": [
            _b("SSL certificate expired","SSL Error","Certificate not renewed","Renew cert, restart server","Auto-renewal (certbot), monitoring","critical",["ssl","certificate"]),
            _b("Disk full","Outage","Unmonitored log/data growth","Clean logs, expand disk, log rotation","Monitor disk, alert at 80%","critical",["disk","storage","logs"]),
            _b("Env var missing in production","Config Error","Not in deployment config","Add to secrets/configmap","Validate at startup, fail fast","high",["env","config","secrets"]),
            _b("Health check failing stalls deployment","Deployment","App not ready in timeout","Increase initialDelaySeconds, fix startup","Appropriate probe timings","medium",["health","probe","deployment"]),
            _b("Secret exposed in container logs","Security","Logging sensitive data","Filter sensitive fields from logs","Log sanitization, structured logging","critical",["secret","logs","security"]),
            _b("DNS propagation delay","Network","DNS changes not effective yet","Wait for TTL, lower TTL before changes","Plan DNS changes with low TTL","medium",["dns","propagation","ttl"]),
            _b("Load balancer 504 timeout","Network","Backend too slow to respond","Increase timeout, optimize backend","Proper timeout configuration","medium",["504","timeout","loadbalancer"]),
            _b("Terraform state lock contention","IaC","Multiple users running terraform","Use remote state with locking, CI/CD only","Single CI/CD pipeline for terraform","medium",["terraform","state","lock"]),
        ],
        "mobile": [
            _b("App crashes on launch","Crash","Null safety violation","Nil checks, safe unwrapping","Strict null safety","critical",["crash","null","startup"]),
            _b("UI freezes during network","UI Freeze","Network on main thread","Background thread, async/await","I/O on background threads always","high",["ui","thread","network"]),
            _b("Layout broken on different screens","UI Bug","Hardcoded dimensions","Flexbox/constraints, percentages","Responsive layout from start","medium",["layout","responsive","screen"]),
            _b("Push notification not received","Bug","Missing permissions/wrong token","Check permissions, verify token","Test notifications early","medium",["push","notification","token"]),
            _b("Keyboard covers input","UI Bug","No keyboard avoidance","KeyboardAvoidingView","Add keyboard handling to all forms","common",["keyboard","input","form"]),
            _b("App rejected by App Store","Submission","Guideline violation","Read rejection reason, fix violation","Study guidelines before submission","medium",["appstore","rejection","guidelines"]),
            _b("Deep link not opening app","Navigation","Wrong URL scheme or config","Verify URL scheme, check associated domains","Test deep links on all platforms","medium",["deeplink","navigation","url"]),
            _b("Background task killed by OS","Background","Exceeding background time limit","Finish task quickly, use background fetch","Respect OS background limits","medium",["background","task","os"]),
            _b("App size too large","Size","Unused assets, large dependencies","Analyze bundle, remove unused, compress","Regular size audits","medium",["size","bundle","assets"]),
            _b("Biometric auth fails silently","Auth Bug","Permission not requested or cancelled","Check availability, handle all states","Request permissions properly","medium",["biometric","auth","permission"]),
        ],
        "angular": [
            _b("ExpressionChangedAfterItHasBeenChecked","Change Detection","Value changed after check cycle","ChangeDetectorRef.detectChanges() or setTimeout","Understand change detection lifecycle","common",["change-detection","expression"]),
            _b("Circular dependency in DI","DI Error","Two services depend on each other","Use forwardRef or restructure","Avoid circular service dependencies","medium",["di","circular","service"]),
            _b("Module not found: Error in Lazy Route","Routing","Wrong path in loadChildren","Check relative path, module exists","Test lazy loading","common",["lazy","routing","module"]),
            _b("Zone.js: unexpected async operation","Zone","Async operation outside Angular zone","NgZone.run() for external events","Run async in Angular zone","medium",["zone","async","change-detection"]),
        ],
        "vue": [
            _b("Reactivity lost on destructured props","Reactivity","Destructured reactive loses tracking","Use toRefs(props) or computed","Don't destructure reactive objects","common",["reactivity","props","toRefs"]),
            _b("v-if and v-for on same element","Warning","v-for has priority, v-if runs per item","Use template wrapper or computed filter","Separate v-if and v-for","common",["v-if","v-for","template"]),
            _b("Component not found","Warning","Component not registered or imported","Register globally or import locally","Auto-import with unplugin-vue-components","common",["component","register","import"]),
            _b("Pinia state not reactive in template","Reactivity","Using storeToRefs incorrectly","storeToRefs for reactive destructure","Always use storeToRefs for destructuring","common",["pinia","store","reactive"]),
        ],
        "aws": [
            _b("Access Denied (403)","IAM","Missing IAM permissions","Add required permission to policy","Least privilege, test policies","common",["iam","permission","403"]),
            _b("Lambda timeout","Timeout","Function exceeds timeout","Increase timeout, optimize code, async","Appropriate timeout, monitor duration","common",["lambda","timeout","serverless"]),
            _b("S3 bucket policy blocks access","Access Denied","Bucket policy denies request","Check bucket policy, ACLs, IAM","Test policies, use Policy Simulator","common",["s3","bucket","policy"]),
            _b("DynamoDB throughput exceeded","Throttle","ProvisionedThroughputExceededException","Increase capacity or use on-demand","Use on-demand, DAX cache","medium",["dynamodb","throughput","throttle"]),
            _b("CloudFormation stack stuck","Deployment","Resource in UPDATE_FAILED state","Skip failed resources, manual fix","Small changesets, rollback config","medium",["cloudformation","stack","failed"]),
            _b("ECS task keeps restarting","Container","Health check failing or OOM","Check logs, increase memory, fix health","Proper health checks, resource limits","medium",["ecs","task","restart","health"]),
        ],
        "graphql": [
            _b("N+1 queries in resolvers","Performance","Each resolver makes separate query","DataLoader for batching","Always use DataLoader","high",["n+1","resolver","dataloader"]),
            _b("Circular reference in schema","Schema Error","Types reference each other infinitely","Use lazy resolvers, limit query depth","Set query depth limit","medium",["circular","schema","depth"]),
            _b("Over-fetching still happening","Architecture","Query returns unused fields","Implement field-level resolvers","Resolver-per-field architecture","medium",["overfetch","resolver","performance"]),
            _b("Subscription memory leak","Memory","Subscriptions not cleaned up","Implement proper unsubscribe","Track active subscriptions","medium",["subscription","memory","websocket"]),
        ],
    }

    for category, bugs in _BUGS.items():
        for bug in bugs:
            entries.append({
                "id": _fid(category, bug["title"]),
                "category": category,
                "title": bug["title"],
                "error_type": bug["error"],
                "root_cause": bug["cause"],
                "fix": bug["fix"],
                "prevention": bug["prevention"],
                "severity": bug["severity"],
                "tags": bug["tags"] + [category],
                "searchable": f"{bug['title']} {bug['error']} {bug['cause']} {bug['fix']} {' '.join(bug['tags'])} {category}".lower(),
            })
    return entries
