"""
Knowledge Vault Final Expansion — Push past 200+ entries
Angular, Svelte, Flask, Spring Boot, NestJS, Web APIs, PWA, Accessibility, SEO,
DNS, gRPC, Encryption, Helm, Prometheus, GANs, Fine-tuning, D3, matplotlib,
Neo4j, CockroachDB, Haskell, Elixir, Scala, Zig, Web Scraping, Concurrency
"""
def _e(eid, topic, cat, content, tags=None):
    return {"id": eid, "topic": topic, "category": cat, "content": content, "tags": tags or []}

def get_vault_final():
    return [
        # ═══ FRAMEWORKS ═══
        _e("kv_angular", "Angular", "angular", "// Component\n@Component({ selector: 'app-user', template: '<h1>{{user.name}}</h1>' })\nexport class UserComponent { @Input() user!: User; }\n\n// Service with DI\n@Injectable({ providedIn: 'root' })\nexport class UserService {\n  constructor(private http: HttpClient) {}\n  getUsers(): Observable<User[]> { return this.http.get<User[]>('/api/users'); }\n}\n\n// Module\n@NgModule({ declarations: [UserComponent], imports: [HttpClientModule], providers: [UserService] })\n\nRxJS: Observable, Subject, pipe(map, filter, switchMap, debounceTime)\nRouting: RouterModule.forRoot(routes), ActivatedRoute, Guards\nForms: ReactiveFormsModule, FormGroup, FormControl, Validators\nChange Detection: OnPush strategy for performance", ["angular","rxjs","typescript","component","service","di"]),
        _e("kv_svelte", "Svelte & SvelteKit", "svelte", "<script>\n  let count = 0;  // reactive by default\n  $: doubled = count * 2;  // derived\n  $: console.log('count changed:', count);  // reactive statement\n  \n  async function loadData() {\n    const res = await fetch('/api/data');\n    return res.json();\n  }\n</script>\n\n<button on:click={() => count++}>{count} (doubled: {doubled})</button>\n\n{#await loadData()}\n  <p>Loading...</p>\n{:then data}\n  {#each data as item (item.id)}\n    <div>{item.name}</div>\n  {/each}\n{/await}\n\nSvelteKit: file-based routing, SSR, load functions, form actions\nStores: writable, readable, derived\n$: is reactive declaration (re-runs when dependencies change)\nNo virtual DOM — compiles to vanilla JS", ["svelte","sveltekit","reactive","stores","ssr"]),
        _e("kv_flask", "Flask", "python", "from flask import Flask, request, jsonify, abort\nfrom functools import wraps\n\napp = Flask(__name__)\n\ndef require_auth(f):\n    @wraps(f)\n    def decorated(*args, **kwargs):\n        token = request.headers.get('Authorization')\n        if not token: abort(401)\n        return f(*args, **kwargs)\n    return decorated\n\n@app.route('/api/users', methods=['GET'])\n@require_auth\ndef get_users():\n    page = request.args.get('page', 1, type=int)\n    users = User.query.paginate(page=page, per_page=20)\n    return jsonify([u.to_dict() for u in users.items])\n\n@app.route('/api/users', methods=['POST'])\ndef create_user():\n    data = request.get_json()\n    user = User(**data)\n    db.session.add(user); db.session.commit()\n    return jsonify(user.to_dict()), 201\n\n@app.errorhandler(404)\ndef not_found(e): return jsonify(error='Not found'), 404\n\nExtensions: Flask-SQLAlchemy, Flask-Migrate, Flask-Login, Flask-CORS, Flask-Caching", ["python","flask","web","api","rest","decorator"]),
        _e("kv_spring_boot", "Spring Boot (Java)", "java", "@RestController\n@RequestMapping(\"/api/users\")\npublic class UserController {\n    @Autowired private UserRepository repo;\n    \n    @GetMapping\n    public List<User> getAll() { return repo.findAll(); }\n    \n    @GetMapping(\"/{id}\")\n    public User getById(@PathVariable Long id) {\n        return repo.findById(id).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND));\n    }\n    \n    @PostMapping\n    @ResponseStatus(HttpStatus.CREATED)\n    public User create(@Valid @RequestBody User user) { return repo.save(user); }\n    \n    @DeleteMapping(\"/{id}\")\n    @ResponseStatus(HttpStatus.NO_CONTENT)\n    public void delete(@PathVariable Long id) { repo.deleteById(id); }\n}\n\n@Entity\npublic class User {\n    @Id @GeneratedValue private Long id;\n    @NotBlank private String name;\n    @Email private String email;\n}\n\npublic interface UserRepository extends JpaRepository<User, Long> {\n    List<User> findByNameContaining(String name);\n}\n\nFeatures: auto-configuration, embedded server, actuator, security, profiles", ["java","spring-boot","rest","jpa","dependency-injection"]),
        _e("kv_nestjs", "NestJS", "javascript", "// Controller\n@Controller('users')\nexport class UsersController {\n  constructor(private usersService: UsersService) {}\n  \n  @Get() findAll(): Promise<User[]> { return this.usersService.findAll(); }\n  @Get(':id') findOne(@Param('id') id: string) { return this.usersService.findOne(id); }\n  @Post() @HttpCode(201) create(@Body() dto: CreateUserDto) { return this.usersService.create(dto); }\n  @Delete(':id') remove(@Param('id') id: string) { return this.usersService.remove(id); }\n}\n\n// Service\n@Injectable()\nexport class UsersService {\n  constructor(@InjectModel(User.name) private model: Model<User>) {}\n  async findAll(): Promise<User[]> { return this.model.find().exec(); }\n}\n\n// Module\n@Module({ controllers: [UsersController], providers: [UsersService], imports: [MongooseModule.forFeature([{name: User.name, schema: UserSchema}])] })\n\nFeatures: Guards, Pipes, Interceptors, Middleware, WebSocket gateway, GraphQL, Microservices", ["javascript","nestjs","node","typescript","di","decorator"]),

        # ═══ WEB APIS & PWA ═══
        _e("kv_web_apis", "Web APIs", "web", "// Fetch API\nconst res = await fetch(url, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(data) });\nif (!res.ok) throw new Error(res.statusText);\nconst json = await res.json();\n\n// IntersectionObserver (lazy loading)\nconst observer = new IntersectionObserver((entries) => {\n  entries.forEach(e => { if (e.isIntersecting) { loadImage(e.target); observer.unobserve(e.target); } });\n}, { rootMargin: '200px' });\n\n// ResizeObserver\nnew ResizeObserver(entries => entries.forEach(e => console.log(e.contentRect.width))).observe(el);\n\n// Web Workers\nconst worker = new Worker('worker.js');\nworker.postMessage({data}); worker.onmessage = e => use(e.data);\n\n// LocalStorage / SessionStorage\nlocalStorage.setItem('key', JSON.stringify(data));\nJSON.parse(localStorage.getItem('key'));\n\n// Clipboard\nawait navigator.clipboard.writeText('copied');\n\n// Geolocation\nnavigator.geolocation.getCurrentPosition(pos => console.log(pos.coords));", ["web","api","fetch","observer","worker","storage","browser"]),
        _e("kv_pwa", "Progressive Web Apps", "web", "// Service Worker\nself.addEventListener('install', e => e.waitUntil(caches.open('v1').then(c => c.addAll(['/','index.html','app.js']))));\nself.addEventListener('fetch', e => e.respondWith(caches.match(e.request).then(r => r || fetch(e.request))));\n\n// manifest.json\n{ \"name\": \"My App\", \"short_name\": \"App\", \"start_url\": \"/\", \"display\": \"standalone\",\n  \"background_color\": \"#000\", \"theme_color\": \"#6366f1\",\n  \"icons\": [{\"src\": \"icon-192.png\", \"sizes\": \"192x192\"}] }\n\n// Register\nif ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js');\n\n// Push notifications\nconst sub = await reg.pushManager.subscribe({userVisibleOnly: true, applicationServerKey: vapidKey});\n\nCaching strategies: Cache First, Network First, Stale While Revalidate\nOffline: IndexedDB for structured data, Cache API for assets\nInstallable: meets PWA criteria → browser shows install prompt", ["web","pwa","service-worker","offline","manifest","push"]),

        # ═══ A11Y & SEO ═══
        _e("kv_a11y", "Web Accessibility (a11y)", "web", "WCAG 2.1 Principles: Perceivable, Operable, Understandable, Robust\n\nSemantic HTML: use <button>, <nav>, <main>, <article> — not div for everything\nAlt text: <img alt='Description of image content'>\nAria: aria-label, aria-describedby, aria-expanded, aria-hidden, role='alert'\nKeyboard: all interactive elements focusable, visible focus indicator, skip links\nColor: contrast ratio >= 4.5:1 for text, don't use color alone for meaning\nForms: <label for='id'>, error messages linked to inputs, fieldset/legend for groups\nScreen readers: logical heading order (h1→h2→h3), meaningful link text\n\nTesting: Lighthouse, axe DevTools, VoiceOver (Mac), NVDA (Windows)\nReact: use <button> not <div onClick>, aria-live for dynamic content", ["web","accessibility","a11y","wcag","aria","semantic"]),
        _e("kv_seo", "SEO Essentials", "web", "Technical SEO:\n- <title> unique per page, 50-60 chars\n- <meta name='description'> 150-160 chars\n- Semantic HTML (h1 once per page, proper hierarchy)\n- robots.txt, sitemap.xml\n- Canonical URLs: <link rel='canonical'>\n- Open Graph: og:title, og:description, og:image\n- Structured data (JSON-LD): Schema.org markup\n- Mobile-friendly, fast loading (<3s LCP)\n- HTTPS everywhere\n\nContent: keyword research, internal linking, fresh content, long-form > thin\nPerformance: Core Web Vitals (LCP<2.5s, FID<100ms, CLS<0.1)\n\nNext.js/SSR: server-rendered HTML = better crawlability\nSPA: use SSR/SSG, prerender for search engines\n\nTools: Google Search Console, PageSpeed Insights, Ahrefs, Screaming Frog", ["web","seo","meta","open-graph","schema","performance"]),

        # ═══ NETWORKING ADVANCED ═══
        _e("kv_dns", "DNS Deep Dive", "networking", "DNS resolves domain names to IP addresses.\n\nRecord types:\nA: domain → IPv4 (93.184.216.34)\nAAAA: domain → IPv6\nCNAME: alias → another domain\nMX: mail server\nTXT: verification, SPF, DKIM\nNS: nameserver delegation\nSOA: zone authority\n\nResolution: Browser cache → OS cache → Resolver → Root → TLD → Authoritative\nTTL: cache duration (seconds)\n\ndig example.com A  # Query A record\nnslookup example.com\nhost example.com\n\nDNS providers: Cloudflare (1.1.1.1), Google (8.8.8.8), Route53, Cloud DNS\nDNS-based load balancing: weighted, geolocation, latency-based, failover", ["networking","dns","records","resolution","nameserver"]),
        _e("kv_grpc", "gRPC", "networking", "// Protocol Buffers (proto3)\nsyntax = \"proto3\";\nservice UserService {\n  rpc GetUser(GetUserRequest) returns (User);\n  rpc ListUsers(ListUsersRequest) returns (stream User);  // server streaming\n  rpc Chat(stream Message) returns (stream Message);       // bidirectional\n}\nmessage User { string id = 1; string name = 2; string email = 3; }\n\n// Python server\nclass UserServicer(user_pb2_grpc.UserServiceServicer):\n    def GetUser(self, request, context):\n        return user_pb2.User(id=request.id, name='Alice')\n\nserver = grpc.server(futures.ThreadPoolExecutor(max_workers=10))\nuser_pb2_grpc.add_UserServiceServicer_to_server(UserServicer(), server)\nserver.add_insecure_port('[::]:50051')\n\n// Python client\nchannel = grpc.insecure_channel('localhost:50051')\nstub = user_pb2_grpc.UserServiceStub(channel)\nuser = stub.GetUser(user_pb2.GetUserRequest(id='123'))\n\nBenefits: binary protocol (fast), typed (protobuf), streaming, HTTP/2\nUse when: microservices, low-latency, mobile backends, polyglot systems", ["networking","grpc","protobuf","rpc","streaming","http2"]),
        _e("kv_tcp_tls", "TCP/IP & TLS", "networking", "TCP/IP layers:\nApplication: HTTP, DNS, SMTP, FTP\nTransport: TCP (reliable, ordered) / UDP (fast, unreliable)\nInternet: IP (routing, addressing)\nLink: Ethernet, Wi-Fi\n\nTCP 3-way handshake: SYN → SYN-ACK → ACK\nTCP guarantees: ordered delivery, retransmission, flow control, congestion control\nUDP: no handshake, no guarantee — used for DNS, gaming, video streaming\n\nTLS 1.3 handshake (1-RTT):\n1. Client Hello: supported ciphers, key share\n2. Server Hello: chosen cipher, key share, certificate\n3. Encrypted data begins\n\nCertificates: CA signs server cert, browser trusts CA\nLet's Encrypt: free automated certificates\nmTLS: both client and server present certificates (service mesh)", ["networking","tcp","tls","ssl","handshake","encryption"]),

        # ═══ SECURITY ADVANCED ═══
        _e("kv_encryption", "Encryption & Hashing", "security", "Symmetric (same key encrypt/decrypt):\n  AES-256-GCM: standard for data at rest\n  ChaCha20: mobile-optimized\n\nAsymmetric (public/private key pair):\n  RSA: key exchange, digital signatures\n  Ed25519: modern signatures (fast, small keys)\n  ECDH: key exchange for TLS\n\nHashing (one-way, no decryption):\n  SHA-256: data integrity, checksums\n  bcrypt/argon2: password hashing (slow by design)\n  HMAC: message authentication\n\nimport hashlib, secrets\nhash = hashlib.sha256(b'data').hexdigest()\ntoken = secrets.token_urlsafe(32)  # secure random\n\nNEVER: MD5/SHA1 for passwords, ECB mode, custom crypto\nALWAYS: bcrypt/argon2 for passwords, AES-GCM for encryption, TLS for transit", ["security","encryption","hashing","aes","rsa","bcrypt","tls"]),

        # ═══ DEVOPS ADVANCED ═══
        _e("kv_helm", "Helm Charts", "devops", "# Chart structure\nmychart/\n  Chart.yaml        # name, version, description\n  values.yaml       # default config values\n  templates/\n    deployment.yaml\n    service.yaml\n    ingress.yaml\n    _helpers.tpl    # template helpers\n\n# templates/deployment.yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{ include \"mychart.fullname\" . }}\nspec:\n  replicas: {{ .Values.replicaCount }}\n  template:\n    spec:\n      containers:\n      - name: {{ .Chart.Name }}\n        image: \"{{ .Values.image.repository }}:{{ .Values.image.tag }}\"\n        ports: [{ containerPort: {{ .Values.service.port }} }]\n        resources: {{ toYaml .Values.resources | nindent 12 }}\n\n# values.yaml\nreplicaCount: 3\nimage: { repository: myapp, tag: latest }\nresources: { limits: { cpu: 500m, memory: 256Mi } }\n\n# Commands\nhelm install myrelease ./mychart -f prod-values.yaml\nhelm upgrade myrelease ./mychart\nhelm rollback myrelease 1\nhelm list; helm status myrelease", ["devops","helm","kubernetes","chart","template","deployment"]),
        _e("kv_prometheus_grafana", "Prometheus & Grafana", "devops", "# Prometheus config\nscrape_configs:\n  - job_name: 'app'\n    static_configs:\n      - targets: ['app:8000']\n    metrics_path: '/metrics'\n    scrape_interval: 15s\n\n# Python metrics\nfrom prometheus_client import Counter, Histogram, generate_latest\nREQUESTS = Counter('http_requests_total', 'Total requests', ['method','path','status'])\nLATENCY = Histogram('http_request_duration_seconds', 'Latency', buckets=[.01,.05,.1,.25,.5,1,2.5,5])\n\n@app.middleware('http')\nasync def metrics(request, call_next):\n    start = time.time()\n    response = await call_next(request)\n    LATENCY.observe(time.time()-start)\n    REQUESTS.labels(request.method, request.url.path, response.status_code).inc()\n    return response\n\n@app.get('/metrics')\ndef metrics(): return Response(generate_latest(), media_type='text/plain')\n\n# PromQL queries\nrate(http_requests_total[5m])  # requests per second\nhistogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))  # p99 latency\n\n# Grafana: connect Prometheus data source → create dashboards → set alerts", ["devops","prometheus","grafana","metrics","monitoring","alerting"]),

        # ═══ ML ADVANCED ═══
        _e("kv_ml_finetuning", "LLM Fine-Tuning", "ml", "# Full fine-tuning vs LoRA vs QLoRA\n\nFull: update all weights — expensive, needs lots of data\nLoRA: Low-Rank Adaptation — add small trainable matrices\nQLoRA: Quantized LoRA — 4-bit base model + LoRA\n\n# Hugging Face + PEFT\nfrom peft import LoraConfig, get_peft_model\nfrom transformers import AutoModelForCausalLM, TrainingArguments, Trainer\n\nmodel = AutoModelForCausalLM.from_pretrained('meta-llama/Llama-2-7b', load_in_4bit=True)\nlora_config = LoraConfig(r=16, lora_alpha=32, target_modules=['q_proj','v_proj'], lora_dropout=0.05)\nmodel = get_peft_model(model, lora_config)\n\ntrainer = Trainer(\n    model=model, train_dataset=dataset,\n    args=TrainingArguments(output_dir='./out', num_train_epochs=3, per_device_train_batch_size=4,\n                           learning_rate=2e-4, fp16=True, logging_steps=10)\n)\ntrainer.train()\n\n# Data format: instruction-following\n{'instruction': 'Summarize this article', 'input': 'article text...', 'output': 'summary...'}\n\n# Key: quality data > quantity, eval on held-out set, avoid catastrophic forgetting", ["ml","fine-tuning","lora","qlora","llm","peft","huggingface"]),
        _e("kv_ml_diffusion", "Diffusion Models & Image Gen", "ml", "# How diffusion works\n# Forward: gradually add noise to image (T steps)\n# Reverse: learn to denoise step by step\n# Training: predict noise added at each step\n# Inference: start from random noise → denoise → image\n\n# Stable Diffusion pipeline\nfrom diffusers import StableDiffusionPipeline\nimport torch\n\npipe = StableDiffusionPipeline.from_pretrained('stabilityai/stable-diffusion-xl-base-1.0', torch_dtype=torch.float16)\npipe = pipe.to('cuda')\nimage = pipe('a photo of an astronaut riding a horse on mars', num_inference_steps=30, guidance_scale=7.5).images[0]\nimage.save('output.png')\n\n# Key concepts\n# UNet: denoising network\n# VAE: encode/decode images to/from latent space\n# CLIP text encoder: convert text prompt to embedding\n# Classifier-free guidance: balance quality vs diversity\n# ControlNet: add spatial control (pose, depth, edges)\n# LoRA: fine-tune style with small adapter\n\n# Models: SDXL, DALL-E 3, Midjourney, Flux", ["ml","diffusion","stable-diffusion","image-generation","generative-ai"]),

        # ═══ DATA VIZ ═══
        _e("kv_matplotlib", "matplotlib & Data Visualization", "python", "import matplotlib.pyplot as plt\nimport numpy as np\n\n# Line plot\nx = np.linspace(0, 10, 100)\nplt.plot(x, np.sin(x), label='sin', color='#6366f1', linewidth=2)\nplt.plot(x, np.cos(x), label='cos', color='#ec4899', linestyle='--')\nplt.xlabel('x'); plt.ylabel('y'); plt.title('Trig Functions')\nplt.legend(); plt.grid(True, alpha=0.3)\nplt.savefig('plot.png', dpi=150, bbox_inches='tight')\n\n# Subplots\nfig, axes = plt.subplots(2, 2, figsize=(10, 8))\naxes[0,0].bar(['A','B','C'], [10,20,15])\naxes[0,1].scatter(x, y, c=colors, s=sizes, alpha=0.6)\naxes[1,0].hist(data, bins=30, edgecolor='white')\naxes[1,1].pie(values, labels=labels, autopct='%1.1f%%')\nplt.tight_layout()\n\n# Seaborn (built on matplotlib)\nimport seaborn as sns\nsns.set_theme(style='darkgrid')\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')\nsns.boxplot(data=df, x='category', y='value')\nsns.pairplot(df, hue='species')", ["python","matplotlib","seaborn","visualization","plotting","chart"]),
        _e("kv_d3", "D3.js Data Visualization", "javascript", "import * as d3 from 'd3';\n\n// Bar chart\nconst svg = d3.select('#chart').append('svg').attr('width', 600).attr('height', 400);\nconst data = [{name:'A',value:30},{name:'B',value:80},{name:'C',value:45}];\n\nconst x = d3.scaleBand().domain(data.map(d=>d.name)).range([0,500]).padding(0.2);\nconst y = d3.scaleLinear().domain([0,d3.max(data,d=>d.value)]).range([350,0]);\n\nsvg.selectAll('rect').data(data).join('rect')\n  .attr('x', d=>x(d.name)+50).attr('y', d=>y(d.value))\n  .attr('width', x.bandwidth()).attr('height', d=>350-y(d.value))\n  .attr('fill', '#6366f1')\n  .on('mouseover', function() { d3.select(this).attr('fill','#818cf8'); });\n\nsvg.append('g').attr('transform','translate(50,350)').call(d3.axisBottom(x));\nsvg.append('g').attr('transform','translate(50,0)').call(d3.axisLeft(y));\n\n// Transitions\nsvg.selectAll('rect').transition().duration(800).attr('y', d=>y(d.value)).attr('height', d=>350-y(d.value));\n\n// Force-directed graph, geo maps, tree layouts, chord diagrams", ["javascript","d3","visualization","svg","chart","interactive"]),

        # ═══ DATABASES ADVANCED ═══
        _e("kv_neo4j", "Neo4j Graph Database", "database", "// Cypher query language\nCREATE (alice:Person {name:'Alice', age:30})\nCREATE (bob:Person {name:'Bob', age:28})\nCREATE (alice)-[:FRIENDS_WITH {since:2020}]->(bob)\nCREATE (alice)-[:WORKS_AT]->(google:Company {name:'Google'})\n\n// Query\nMATCH (p:Person)-[:FRIENDS_WITH]->(friend)\nWHERE p.name = 'Alice'\nRETURN friend.name, friend.age\n\n// Shortest path\nMATCH path = shortestPath((a:Person {name:'Alice'})-[*]-(b:Person {name:'Eve'}))\nRETURN path\n\n// Recommendations (friends of friends)\nMATCH (me:Person {name:'Alice'})-[:FRIENDS_WITH]->(friend)-[:FRIENDS_WITH]->(foaf)\nWHERE NOT (me)-[:FRIENDS_WITH]->(foaf) AND me <> foaf\nRETURN foaf.name, COUNT(friend) AS mutual ORDER BY mutual DESC\n\nUse cases: social networks, recommendation engines, fraud detection, knowledge graphs, network topology", ["database","neo4j","graph","cypher","relationships"]),
        _e("kv_timeseries_db", "Time-Series Databases", "database", "// TimescaleDB (PostgreSQL extension)\nCREATE TABLE metrics (time TIMESTAMPTZ NOT NULL, device_id TEXT, temperature DOUBLE PRECISION, humidity DOUBLE PRECISION);\nSELECT create_hypertable('metrics', 'time');\n\n// Continuous aggregates\nCREATE MATERIALIZED VIEW hourly_avg WITH (timescaledb.continuous) AS\nSELECT time_bucket('1 hour', time) AS hour, device_id,\n  AVG(temperature) AS avg_temp, MAX(temperature) AS max_temp\nFROM metrics GROUP BY hour, device_id;\n\n// InfluxDB (InfluxQL)\nSELECT MEAN(\"temperature\") FROM \"metrics\" WHERE time > now() - 1h GROUP BY time(5m), \"device_id\"\n\nUse cases: IoT sensor data, server metrics, financial data, logs\nFeatures: automatic partitioning, compression, retention policies, downsampling\n\nAlternatives: TimescaleDB, InfluxDB, QuestDB, ClickHouse (analytics)", ["database","timeseries","timescaledb","influxdb","iot","metrics"]),

        # ═══ ADDITIONAL LANGUAGES ═══
        _e("kv_haskell", "Haskell Fundamentals", "haskell", "-- Pure functional, strongly typed, lazy evaluation\n\n-- Functions\nadd :: Int -> Int -> Int\nadd x y = x + y\n\n-- Pattern matching\nfactorial :: Integer -> Integer\nfactorial 0 = 1\nfactorial n = n * factorial (n - 1)\n\n-- List operations\ndoubleAll = map (*2) [1..10]  -- [2,4,6,...,20]\nevens = filter even [1..20]\nsum' = foldl (+) 0 [1..100]   -- 5050\n\n-- Algebraic data types\ndata Shape = Circle Double | Rectangle Double Double\narea :: Shape -> Double\narea (Circle r) = pi * r * r\narea (Rectangle w h) = w * h\n\n-- Maybe monad (null safety)\nsafeDivide :: Double -> Double -> Maybe Double\nsafeDivide _ 0 = Nothing\nsafeDivide x y = Just (x / y)\n\n-- IO monad\nmain :: IO ()\nmain = do\n    putStrLn \"What is your name?\"\n    name <- getLine\n    putStrLn (\"Hello, \" ++ name)\n\n-- Type classes: Eq, Ord, Show, Functor, Applicative, Monad", ["haskell","functional","monad","pattern-matching","pure"]),
        _e("kv_elixir", "Elixir & Phoenix", "elixir", "# Pattern matching\n{:ok, result} = {:ok, 42}  # result = 42\n[head | tail] = [1, 2, 3]  # head = 1, tail = [2,3]\n\n# Pipe operator\n\"hello world\"\n|> String.split()\n|> Enum.map(&String.capitalize/1)\n|> Enum.join(\" \")  # \"Hello World\"\n\n# Processes (lightweight, millions possible)\nspawn(fn -> IO.puts(\"Hello from process\") end)\npid = spawn(fn -> receive do {:msg, text} -> IO.puts(text) end end)\nsend(pid, {:msg, \"Hi!\"})\n\n# GenServer\ndefmodule Counter do\n  use GenServer\n  def init(count), do: {:ok, count}\n  def handle_call(:get, _from, count), do: {:reply, count, count}\n  def handle_cast(:inc, count), do: {:noreply, count + 1}\nend\n\n# Phoenix Framework\n# Channels for real-time (WebSocket)\n# LiveView: server-rendered interactive UIs\n# Ecto: database wrapper (like ActiveRecord)\n# Supervision trees: self-healing processes", ["elixir","phoenix","erlang","concurrency","pipe","genserver"]),
        _e("kv_scala", "Scala Essentials", "scala", "// Variables\nval name: String = \"Alice\"  // immutable\nvar age: Int = 30           // mutable\n\n// Functions\ndef add(a: Int, b: Int): Int = a + b\nval double = (x: Int) => x * 2  // lambda\n\n// Collections\nval nums = List(1, 2, 3, 4, 5)\nnums.filter(_ % 2 == 0).map(_ * 2)  // List(4, 8)\nnums.foldLeft(0)(_ + _)  // 15\n\n// Pattern matching\nval result = x match {\n  case 1 => \"one\"\n  case s: String => s\"got string: $s\"\n  case _ => \"other\"\n}\n\n// Case classes (like data classes)\ncase class User(name: String, age: Int)\nval u = User(\"Alice\", 30)\nval u2 = u.copy(age = 31)\n\n// Traits (like interfaces with implementation)\ntrait Printable { def print(): Unit = println(this.toString) }\n\n// For comprehension (flatMap/map sugar)\nfor {\n  user <- getUser(id)\n  posts <- getPosts(user.id)\n} yield (user, posts)\n\n// Akka: actor-based concurrency\n// Spark: written in Scala, big data processing", ["scala","jvm","functional","pattern-matching","case-class","akka"]),
        _e("kv_zig", "Zig Programming", "zig", "const std = @import(\"std\");\n\npub fn main() !void {\n    const stdout = std.io.getStdOut().writer();\n    try stdout.print(\"Hello, {}!\\n\", .{\"world\"});\n}\n\n// Comptime (compile-time execution)\nfn fibonacci(comptime n: u64) u64 {\n    if (n <= 1) return n;\n    return fibonacci(n - 1) + fibonacci(n - 2);\n}\nconst fib10 = fibonacci(10);  // computed at compile time\n\n// Optional types (null safety)\nvar x: ?i32 = null;\nif (x) |value| { use(value); }\nconst y = x orelse 0;\n\n// Error handling\nfn divide(a: f64, b: f64) !f64 {\n    if (b == 0) return error.DivisionByZero;\n    return a / b;\n}\nconst result = divide(10, 3) catch |err| handleError(err);\n\n// No hidden allocations, no hidden control flow\n// Manual memory management with allocators\n// C interop without FFI overhead\n// Used in: Bun (JS runtime), game engines, systems programming", ["zig","systems","comptime","error-handling","memory"]),

        # ═══ WEB SCRAPING & AUTOMATION ═══
        _e("kv_scraping", "Web Scraping", "python", "import requests\nfrom bs4 import BeautifulSoup\nimport json\n\n# Simple scraping\nres = requests.get('https://example.com', headers={'User-Agent': 'Mozilla/5.0'})\nsoup = BeautifulSoup(res.text, 'html.parser')\ntitles = [h2.text for h2 in soup.find_all('h2', class_='title')]\nlinks = [a['href'] for a in soup.find_all('a', href=True)]\n\n# CSS selectors\nprices = soup.select('.product .price')\nrows = soup.select('table tbody tr')\n\n# Async scraping\nimport aiohttp, asyncio\nasync def fetch(session, url):\n    async with session.get(url) as resp:\n        return await resp.text()\n\nasync def scrape_all(urls):\n    async with aiohttp.ClientSession() as session:\n        tasks = [fetch(session, url) for url in urls]\n        return await asyncio.gather(*tasks)\n\n# Playwright for JS-rendered pages\nfrom playwright.sync_api import sync_playwright\nwith sync_playwright() as p:\n    page = p.chromium.launch().new_page()\n    page.goto('https://spa-site.com')\n    page.wait_for_selector('.data')\n    content = page.content()\n\n# Ethics: respect robots.txt, rate limit, don't overload servers", ["python","scraping","beautifulsoup","playwright","automation"]),
        _e("kv_py_concurrency", "Python Concurrency", "python", "import threading, multiprocessing, asyncio, concurrent.futures\n\n# Threading (I/O-bound: network, file, DB)\ndef fetch(url):\n    return requests.get(url).text\n\nwith concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:\n    results = list(executor.map(fetch, urls))\n\n# Multiprocessing (CPU-bound: math, image processing)\ndef heavy_compute(n):\n    return sum(i**2 for i in range(n))\n\nwith multiprocessing.Pool(4) as pool:\n    results = pool.map(heavy_compute, [10**6]*4)\n\n# asyncio (I/O-bound, single-threaded)\nasync def fetch_all(urls):\n    async with aiohttp.ClientSession() as session:\n        tasks = [session.get(url) for url in urls]\n        return await asyncio.gather(*tasks)\n\n# GIL: Global Interpreter Lock\n# Only one thread executes Python bytecode at a time\n# Threading works for I/O (releases GIL during wait)\n# Multiprocessing bypasses GIL (separate processes)\n# asyncio: cooperative multitasking, best for many I/O operations\n\n# Rule: I/O-bound → asyncio/threading, CPU-bound → multiprocessing", ["python","concurrency","threading","multiprocessing","asyncio","gil"]),

        # ═══ REGEX ADVANCED ═══
        _e("kv_regex_advanced", "Advanced Regular Expressions", "regex", "# Lookahead/Lookbehind\n(?=...)   Positive lookahead:  \\d+(?= dollars)  → matches '100' in '100 dollars'\n(?!...)   Negative lookahead:  \\d+(?! dollars)  → matches digits NOT followed by 'dollars'\n(?<=...)  Positive lookbehind: (?<=\\$)\\d+        → matches '100' in '$100'\n(?<!...)  Negative lookbehind: (?<!\\$)\\d+        → matches digits NOT preceded by '$'\n\n# Named groups\n(?P<name>pattern)   Python\n(?<name>pattern)    JS/C#\n\n# Non-greedy quantifiers\n.*?   Match as FEW as possible\n.+?   At least one, but minimal\n\n# Common patterns\nEmail: [\\w.+-]+@[\\w-]+\\.[\\w.]+\nURL: https?://[\\w.-]+(?:/[\\w./-]*)*(?:\\?[\\w=&]*)?\nIP: (?:\\d{1,3}\\.){3}\\d{1,3}\nDate: \\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])\nPassword: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%]).{8,}$\nSlug: ^[a-z0-9]+(?:-[a-z0-9]+)*$\n\n# Flags: re.IGNORECASE, re.MULTILINE, re.DOTALL, re.VERBOSE", ["regex","regular-expression","pattern","lookahead","lookbehind"]),

        # ═══ PYTHON PACKAGING ═══
        _e("kv_py_packaging", "Python Packaging & Environments", "python", "# Virtual environments\npython -m venv .venv\nsource .venv/bin/activate  # Linux/Mac\npip install -r requirements.txt\npip freeze > requirements.txt\n\n# pyproject.toml (modern standard)\n[project]\nname = 'mypackage'\nversion = '1.0.0'\ndependencies = ['fastapi>=0.100', 'pydantic>=2.0']\n[project.optional-dependencies]\ndev = ['pytest', 'ruff', 'mypy']\n\n# Poetry\npoetry init\npoetry add fastapi\npoetry add --group dev pytest\npoetry install\npoetry build\npoetry publish\n\n# uv (fast, Rust-based)\nuv pip install fastapi\nuv venv\nuv pip compile requirements.in -o requirements.txt\n\n# Package structure\nmypackage/\n  __init__.py\n  core.py\n  utils.py\ntests/\n  test_core.py\npyproject.toml\nREADME.md\n\n# Publishing\npython -m build\ntwine upload dist/*", ["python","packaging","pip","poetry","venv","pyproject"]),

        # ═══ MISC ═══
        _e("kv_oauth_flows", "OAuth 2.0 Flows", "security", "# Authorization Code Flow (most common for web apps)\n1. User clicks 'Login with Google'\n2. Redirect: GET https://accounts.google.com/o/oauth2/auth?client_id=X&redirect_uri=Y&scope=email+profile&response_type=code\n3. User authenticates and consents\n4. Redirect back: GET /callback?code=AUTH_CODE\n5. Server exchanges code for tokens:\n   POST https://oauth2.googleapis.com/token\n   { client_id, client_secret, code, redirect_uri, grant_type: 'authorization_code' }\n6. Receive: { access_token, refresh_token, id_token, expires_in }\n7. Use access_token to call APIs\n\n# PKCE Flow (mobile/SPA — no client_secret)\nSame as above but with code_verifier + code_challenge\n\n# Client Credentials (machine-to-machine)\nPOST /token { client_id, client_secret, grant_type: 'client_credentials' }\n\n# Refresh tokens\nPOST /token { refresh_token, grant_type: 'refresh_token' }\n\n# JWT: { header }.{ payload }.{ signature } — base64 encoded\npayload: { sub, iat, exp, iss, aud, ... }", ["security","oauth","jwt","auth","pkce","tokens"]),
    ]
