"""priority_table — route class + admit priority catalog for Pack A.

Control-plane traffic uses priority 0 (may overdraw AdaptiveGate).
Bulk/upload sheds first (priority >= 3).
"""

from __future__ import annotations

from typing import Dict, List, Tuple

# (path_prefix_or_exact, route_class, priority)
PRIORITY_TABLE: List[Tuple[str, str, int]] = [
    ('/health', 'open', 0),
    ('/ready', 'open', 0),
    ('/metrics', 'telemetry', 2),
    ('/v1/auth/token', 'auth', 0),
    ('/v1/oauth/callback', 'auth', 0),
    ('/v1/forge/materialise', 'forge', 1),
    ('/v1/forge/plan', 'forge', 1),
    ('/v1/gameforge/run', 'gameforge', 1),
    ('/v1/gameforge/intake', 'gameforge', 1),
    ('/v1/swarm/fence', 'swarm', 1),
    ('/v1/swarm/ingress', 'swarm', 1),
    ('/v1/admin/shutdown', 'control', 0),
    ('/v1/admin/drain', 'control', 0),
    ('/v1/upload', 'bulk', 3),
    ('/v1/bulk/import', 'bulk', 3),
    ('/v1/gameforge/entity/0', 'gameforge', 1),
    ('/v1/gameforge/entity/1', 'gameforge', 2),
    ('/v1/gameforge/entity/2', 'gameforge', 3),
    ('/v1/gameforge/entity/3', 'gameforge', 1),
    ('/v1/gameforge/entity/4', 'gameforge', 2),
    ('/v1/gameforge/entity/5', 'gameforge', 3),
    ('/v1/gameforge/entity/6', 'gameforge', 1),
    ('/v1/gameforge/entity/7', 'gameforge', 2),
    ('/v1/gameforge/entity/8', 'gameforge', 3),
    ('/v1/gameforge/entity/9', 'gameforge', 1),
    ('/v1/gameforge/entity/10', 'gameforge', 2),
    ('/v1/gameforge/entity/11', 'gameforge', 3),
    ('/v1/gameforge/entity/12', 'gameforge', 1),
    ('/v1/gameforge/entity/13', 'gameforge', 2),
    ('/v1/gameforge/entity/14', 'gameforge', 3),
    ('/v1/gameforge/entity/15', 'gameforge', 1),
    ('/v1/gameforge/entity/16', 'gameforge', 2),
    ('/v1/gameforge/entity/17', 'gameforge', 3),
    ('/v1/gameforge/entity/18', 'gameforge', 1),
    ('/v1/gameforge/entity/19', 'gameforge', 2),
    ('/v1/gameforge/entity/20', 'gameforge', 3),
    ('/v1/gameforge/entity/21', 'gameforge', 1),
    ('/v1/gameforge/entity/22', 'gameforge', 2),
    ('/v1/gameforge/entity/23', 'gameforge', 3),
    ('/v1/gameforge/entity/24', 'gameforge', 1),
    ('/v1/gameforge/entity/25', 'gameforge', 2),
    ('/v1/gameforge/entity/26', 'gameforge', 3),
    ('/v1/gameforge/entity/27', 'gameforge', 1),
    ('/v1/gameforge/entity/28', 'gameforge', 2),
    ('/v1/gameforge/entity/29', 'gameforge', 3),
    ('/v1/gameforge/entity/30', 'gameforge', 1),
    ('/v1/gameforge/entity/31', 'gameforge', 2),
    ('/v1/gameforge/entity/32', 'gameforge', 3),
    ('/v1/gameforge/entity/33', 'gameforge', 1),
    ('/v1/gameforge/entity/34', 'gameforge', 2),
    ('/v1/gameforge/entity/35', 'gameforge', 3),
    ('/v1/gameforge/entity/36', 'gameforge', 1),
    ('/v1/gameforge/entity/37', 'gameforge', 2),
    ('/v1/gameforge/entity/38', 'gameforge', 3),
    ('/v1/gameforge/entity/39', 'gameforge', 1),
    ('/v1/gameforge/entity/40', 'gameforge', 2),
    ('/v1/gameforge/entity/41', 'gameforge', 3),
    ('/v1/gameforge/entity/42', 'gameforge', 1),
    ('/v1/gameforge/entity/43', 'gameforge', 2),
    ('/v1/gameforge/entity/44', 'gameforge', 3),
    ('/v1/gameforge/entity/45', 'gameforge', 1),
    ('/v1/gameforge/entity/46', 'gameforge', 2),
    ('/v1/gameforge/entity/47', 'gameforge', 3),
    ('/v1/gameforge/entity/48', 'gameforge', 1),
    ('/v1/gameforge/entity/49', 'gameforge', 2),
    ('/v1/gameforge/entity/50', 'gameforge', 3),
    ('/v1/gameforge/entity/51', 'gameforge', 1),
    ('/v1/gameforge/entity/52', 'gameforge', 2),
    ('/v1/gameforge/entity/53', 'gameforge', 3),
    ('/v1/gameforge/entity/54', 'gameforge', 1),
    ('/v1/gameforge/entity/55', 'gameforge', 2),
    ('/v1/gameforge/entity/56', 'gameforge', 3),
    ('/v1/gameforge/entity/57', 'gameforge', 1),
    ('/v1/gameforge/entity/58', 'gameforge', 2),
    ('/v1/gameforge/entity/59', 'gameforge', 3),
    ('/v1/gameforge/entity/60', 'gameforge', 1),
    ('/v1/gameforge/entity/61', 'gameforge', 2),
    ('/v1/gameforge/entity/62', 'gameforge', 3),
    ('/v1/gameforge/entity/63', 'gameforge', 1),
    ('/v1/gameforge/entity/64', 'gameforge', 2),
    ('/v1/gameforge/entity/65', 'gameforge', 3),
    ('/v1/gameforge/entity/66', 'gameforge', 1),
    ('/v1/gameforge/entity/67', 'gameforge', 2),
    ('/v1/gameforge/entity/68', 'gameforge', 3),
    ('/v1/gameforge/entity/69', 'gameforge', 1),
    ('/v1/gameforge/entity/70', 'gameforge', 2),
    ('/v1/gameforge/entity/71', 'gameforge', 3),
    ('/v1/gameforge/entity/72', 'gameforge', 1),
    ('/v1/gameforge/entity/73', 'gameforge', 2),
    ('/v1/gameforge/entity/74', 'gameforge', 3),
    ('/v1/gameforge/entity/75', 'gameforge', 1),
    ('/v1/gameforge/entity/76', 'gameforge', 2),
    ('/v1/gameforge/entity/77', 'gameforge', 3),
    ('/v1/gameforge/entity/78', 'gameforge', 1),
    ('/v1/gameforge/entity/79', 'gameforge', 2),
    ('/v1/gameforge/entity/80', 'gameforge', 3),
    ('/v1/gameforge/entity/81', 'gameforge', 1),
    ('/v1/gameforge/entity/82', 'gameforge', 2),
    ('/v1/gameforge/entity/83', 'gameforge', 3),
    ('/v1/gameforge/entity/84', 'gameforge', 1),
    ('/v1/gameforge/entity/85', 'gameforge', 2),
    ('/v1/gameforge/entity/86', 'gameforge', 3),
    ('/v1/gameforge/entity/87', 'gameforge', 1),
    ('/v1/gameforge/entity/88', 'gameforge', 2),
    ('/v1/gameforge/entity/89', 'gameforge', 3),
    ('/v1/gameforge/entity/90', 'gameforge', 1),
    ('/v1/gameforge/entity/91', 'gameforge', 2),
    ('/v1/gameforge/entity/92', 'gameforge', 3),
    ('/v1/gameforge/entity/93', 'gameforge', 1),
    ('/v1/gameforge/entity/94', 'gameforge', 2),
    ('/v1/gameforge/entity/95', 'gameforge', 3),
    ('/v1/gameforge/entity/96', 'gameforge', 1),
    ('/v1/gameforge/entity/97', 'gameforge', 2),
    ('/v1/gameforge/entity/98', 'gameforge', 3),
    ('/v1/gameforge/entity/99', 'gameforge', 1),
    ('/v1/gameforge/entity/100', 'gameforge', 2),
    ('/v1/gameforge/entity/101', 'gameforge', 3),
    ('/v1/gameforge/entity/102', 'gameforge', 1),
    ('/v1/gameforge/entity/103', 'gameforge', 2),
    ('/v1/gameforge/entity/104', 'gameforge', 3),
    ('/v1/gameforge/entity/105', 'gameforge', 1),
    ('/v1/gameforge/entity/106', 'gameforge', 2),
    ('/v1/gameforge/entity/107', 'gameforge', 3),
    ('/v1/gameforge/entity/108', 'gameforge', 1),
    ('/v1/gameforge/entity/109', 'gameforge', 2),
    ('/v1/gameforge/entity/110', 'gameforge', 3),
    ('/v1/gameforge/entity/111', 'gameforge', 1),
    ('/v1/gameforge/entity/112', 'gameforge', 2),
    ('/v1/gameforge/entity/113', 'gameforge', 3),
    ('/v1/gameforge/entity/114', 'gameforge', 1),
    ('/v1/gameforge/entity/115', 'gameforge', 2),
    ('/v1/gameforge/entity/116', 'gameforge', 3),
    ('/v1/gameforge/entity/117', 'gameforge', 1),
    ('/v1/gameforge/entity/118', 'gameforge', 2),
    ('/v1/gameforge/entity/119', 'gameforge', 3),
    ('/v1/gameforge/entity/120', 'gameforge', 1),
    ('/v1/gameforge/entity/121', 'gameforge', 2),
    ('/v1/gameforge/entity/122', 'gameforge', 3),
    ('/v1/gameforge/entity/123', 'gameforge', 1),
    ('/v1/gameforge/entity/124', 'gameforge', 2),
    ('/v1/gameforge/entity/125', 'gameforge', 3),
    ('/v1/gameforge/entity/126', 'gameforge', 1),
    ('/v1/gameforge/entity/127', 'gameforge', 2),
    ('/v1/gameforge/entity/128', 'gameforge', 3),
    ('/v1/gameforge/entity/129', 'gameforge', 1),
    ('/v1/gameforge/entity/130', 'gameforge', 2),
    ('/v1/gameforge/entity/131', 'gameforge', 3),
    ('/v1/gameforge/entity/132', 'gameforge', 1),
    ('/v1/gameforge/entity/133', 'gameforge', 2),
    ('/v1/gameforge/entity/134', 'gameforge', 3),
    ('/v1/gameforge/entity/135', 'gameforge', 1),
    ('/v1/gameforge/entity/136', 'gameforge', 2),
    ('/v1/gameforge/entity/137', 'gameforge', 3),
    ('/v1/gameforge/entity/138', 'gameforge', 1),
    ('/v1/gameforge/entity/139', 'gameforge', 2),
    ('/v1/gameforge/entity/140', 'gameforge', 3),
    ('/v1/gameforge/entity/141', 'gameforge', 1),
    ('/v1/gameforge/entity/142', 'gameforge', 2),
    ('/v1/gameforge/entity/143', 'gameforge', 3),
    ('/v1/gameforge/entity/144', 'gameforge', 1),
    ('/v1/gameforge/entity/145', 'gameforge', 2),
    ('/v1/gameforge/entity/146', 'gameforge', 3),
    ('/v1/gameforge/entity/147', 'gameforge', 1),
    ('/v1/gameforge/entity/148', 'gameforge', 2),
    ('/v1/gameforge/entity/149', 'gameforge', 3),
    ('/v1/gameforge/entity/150', 'gameforge', 1),
    ('/v1/gameforge/entity/151', 'gameforge', 2),
    ('/v1/gameforge/entity/152', 'gameforge', 3),
    ('/v1/gameforge/entity/153', 'gameforge', 1),
    ('/v1/gameforge/entity/154', 'gameforge', 2),
    ('/v1/gameforge/entity/155', 'gameforge', 3),
    ('/v1/gameforge/entity/156', 'gameforge', 1),
    ('/v1/gameforge/entity/157', 'gameforge', 2),
    ('/v1/gameforge/entity/158', 'gameforge', 3),
    ('/v1/gameforge/entity/159', 'gameforge', 1),
    ('/v1/gameforge/entity/160', 'gameforge', 2),
    ('/v1/gameforge/entity/161', 'gameforge', 3),
    ('/v1/gameforge/entity/162', 'gameforge', 1),
    ('/v1/gameforge/entity/163', 'gameforge', 2),
    ('/v1/gameforge/entity/164', 'gameforge', 3),
    ('/v1/gameforge/entity/165', 'gameforge', 1),
    ('/v1/gameforge/entity/166', 'gameforge', 2),
    ('/v1/gameforge/entity/167', 'gameforge', 3),
    ('/v1/gameforge/entity/168', 'gameforge', 1),
    ('/v1/gameforge/entity/169', 'gameforge', 2),
    ('/v1/gameforge/entity/170', 'gameforge', 3),
    ('/v1/gameforge/entity/171', 'gameforge', 1),
    ('/v1/gameforge/entity/172', 'gameforge', 2),
    ('/v1/gameforge/entity/173', 'gameforge', 3),
    ('/v1/gameforge/entity/174', 'gameforge', 1),
    ('/v1/gameforge/entity/175', 'gameforge', 2),
    ('/v1/gameforge/entity/176', 'gameforge', 3),
    ('/v1/gameforge/entity/177', 'gameforge', 1),
    ('/v1/gameforge/entity/178', 'gameforge', 2),
    ('/v1/gameforge/entity/179', 'gameforge', 3),
    ('/v1/gameforge/entity/180', 'gameforge', 1),
    ('/v1/gameforge/entity/181', 'gameforge', 2),
    ('/v1/gameforge/entity/182', 'gameforge', 3),
    ('/v1/gameforge/entity/183', 'gameforge', 1),
    ('/v1/gameforge/entity/184', 'gameforge', 2),
    ('/v1/gameforge/entity/185', 'gameforge', 3),
    ('/v1/gameforge/entity/186', 'gameforge', 1),
    ('/v1/gameforge/entity/187', 'gameforge', 2),
    ('/v1/gameforge/entity/188', 'gameforge', 3),
    ('/v1/gameforge/entity/189', 'gameforge', 1),
    ('/v1/gameforge/entity/190', 'gameforge', 2),
    ('/v1/gameforge/entity/191', 'gameforge', 3),
    ('/v1/gameforge/entity/192', 'gameforge', 1),
    ('/v1/gameforge/entity/193', 'gameforge', 2),
    ('/v1/gameforge/entity/194', 'gameforge', 3),
    ('/v1/gameforge/entity/195', 'gameforge', 1),
    ('/v1/gameforge/entity/196', 'gameforge', 2),
    ('/v1/gameforge/entity/197', 'gameforge', 3),
    ('/v1/gameforge/entity/198', 'gameforge', 1),
    ('/v1/gameforge/entity/199', 'gameforge', 2),
    ('/v1/swarm/worker/0', 'swarm', 1),
    ('/v1/swarm/worker/1', 'swarm', 2),
    ('/v1/swarm/worker/2', 'swarm', 1),
    ('/v1/swarm/worker/3', 'swarm', 2),
    ('/v1/swarm/worker/4', 'swarm', 1),
    ('/v1/swarm/worker/5', 'swarm', 2),
    ('/v1/swarm/worker/6', 'swarm', 1),
    ('/v1/swarm/worker/7', 'swarm', 2),
    ('/v1/swarm/worker/8', 'swarm', 1),
    ('/v1/swarm/worker/9', 'swarm', 2),
    ('/v1/swarm/worker/10', 'swarm', 1),
    ('/v1/swarm/worker/11', 'swarm', 2),
    ('/v1/swarm/worker/12', 'swarm', 1),
    ('/v1/swarm/worker/13', 'swarm', 2),
    ('/v1/swarm/worker/14', 'swarm', 1),
    ('/v1/swarm/worker/15', 'swarm', 2),
    ('/v1/swarm/worker/16', 'swarm', 1),
    ('/v1/swarm/worker/17', 'swarm', 2),
    ('/v1/swarm/worker/18', 'swarm', 1),
    ('/v1/swarm/worker/19', 'swarm', 2),
    ('/v1/swarm/worker/20', 'swarm', 1),
    ('/v1/swarm/worker/21', 'swarm', 2),
    ('/v1/swarm/worker/22', 'swarm', 1),
    ('/v1/swarm/worker/23', 'swarm', 2),
    ('/v1/swarm/worker/24', 'swarm', 1),
    ('/v1/swarm/worker/25', 'swarm', 2),
    ('/v1/swarm/worker/26', 'swarm', 1),
    ('/v1/swarm/worker/27', 'swarm', 2),
    ('/v1/swarm/worker/28', 'swarm', 1),
    ('/v1/swarm/worker/29', 'swarm', 2),
    ('/v1/swarm/worker/30', 'swarm', 1),
    ('/v1/swarm/worker/31', 'swarm', 2),
    ('/v1/swarm/worker/32', 'swarm', 1),
    ('/v1/swarm/worker/33', 'swarm', 2),
    ('/v1/swarm/worker/34', 'swarm', 1),
    ('/v1/swarm/worker/35', 'swarm', 2),
    ('/v1/swarm/worker/36', 'swarm', 1),
    ('/v1/swarm/worker/37', 'swarm', 2),
    ('/v1/swarm/worker/38', 'swarm', 1),
    ('/v1/swarm/worker/39', 'swarm', 2),
    ('/v1/swarm/worker/40', 'swarm', 1),
    ('/v1/swarm/worker/41', 'swarm', 2),
    ('/v1/swarm/worker/42', 'swarm', 1),
    ('/v1/swarm/worker/43', 'swarm', 2),
    ('/v1/swarm/worker/44', 'swarm', 1),
    ('/v1/swarm/worker/45', 'swarm', 2),
    ('/v1/swarm/worker/46', 'swarm', 1),
    ('/v1/swarm/worker/47', 'swarm', 2),
    ('/v1/swarm/worker/48', 'swarm', 1),
    ('/v1/swarm/worker/49', 'swarm', 2),
    ('/v1/swarm/worker/50', 'swarm', 1),
    ('/v1/swarm/worker/51', 'swarm', 2),
    ('/v1/swarm/worker/52', 'swarm', 1),
    ('/v1/swarm/worker/53', 'swarm', 2),
    ('/v1/swarm/worker/54', 'swarm', 1),
    ('/v1/swarm/worker/55', 'swarm', 2),
    ('/v1/swarm/worker/56', 'swarm', 1),
    ('/v1/swarm/worker/57', 'swarm', 2),
    ('/v1/swarm/worker/58', 'swarm', 1),
    ('/v1/swarm/worker/59', 'swarm', 2),
    ('/v1/swarm/worker/60', 'swarm', 1),
    ('/v1/swarm/worker/61', 'swarm', 2),
    ('/v1/swarm/worker/62', 'swarm', 1),
    ('/v1/swarm/worker/63', 'swarm', 2),
    ('/v1/swarm/worker/64', 'swarm', 1),
    ('/v1/swarm/worker/65', 'swarm', 2),
    ('/v1/swarm/worker/66', 'swarm', 1),
    ('/v1/swarm/worker/67', 'swarm', 2),
    ('/v1/swarm/worker/68', 'swarm', 1),
    ('/v1/swarm/worker/69', 'swarm', 2),
    ('/v1/swarm/worker/70', 'swarm', 1),
    ('/v1/swarm/worker/71', 'swarm', 2),
    ('/v1/swarm/worker/72', 'swarm', 1),
    ('/v1/swarm/worker/73', 'swarm', 2),
    ('/v1/swarm/worker/74', 'swarm', 1),
    ('/v1/swarm/worker/75', 'swarm', 2),
    ('/v1/swarm/worker/76', 'swarm', 1),
    ('/v1/swarm/worker/77', 'swarm', 2),
    ('/v1/swarm/worker/78', 'swarm', 1),
    ('/v1/swarm/worker/79', 'swarm', 2),
    ('/v1/swarm/worker/80', 'swarm', 1),
    ('/v1/swarm/worker/81', 'swarm', 2),
    ('/v1/swarm/worker/82', 'swarm', 1),
    ('/v1/swarm/worker/83', 'swarm', 2),
    ('/v1/swarm/worker/84', 'swarm', 1),
    ('/v1/swarm/worker/85', 'swarm', 2),
    ('/v1/swarm/worker/86', 'swarm', 1),
    ('/v1/swarm/worker/87', 'swarm', 2),
    ('/v1/swarm/worker/88', 'swarm', 1),
    ('/v1/swarm/worker/89', 'swarm', 2),
    ('/v1/swarm/worker/90', 'swarm', 1),
    ('/v1/swarm/worker/91', 'swarm', 2),
    ('/v1/swarm/worker/92', 'swarm', 1),
    ('/v1/swarm/worker/93', 'swarm', 2),
    ('/v1/swarm/worker/94', 'swarm', 1),
    ('/v1/swarm/worker/95', 'swarm', 2),
    ('/v1/swarm/worker/96', 'swarm', 1),
    ('/v1/swarm/worker/97', 'swarm', 2),
    ('/v1/swarm/worker/98', 'swarm', 1),
    ('/v1/swarm/worker/99', 'swarm', 2),
    ('/v1/forge/blueprint/0', 'forge', 1),
    ('/v1/forge/blueprint/1', 'forge', 1),
    ('/v1/forge/blueprint/2', 'forge', 1),
    ('/v1/forge/blueprint/3', 'forge', 1),
    ('/v1/forge/blueprint/4', 'forge', 1),
    ('/v1/forge/blueprint/5', 'forge', 1),
    ('/v1/forge/blueprint/6', 'forge', 1),
    ('/v1/forge/blueprint/7', 'forge', 1),
    ('/v1/forge/blueprint/8', 'forge', 1),
    ('/v1/forge/blueprint/9', 'forge', 1),
    ('/v1/forge/blueprint/10', 'forge', 1),
    ('/v1/forge/blueprint/11', 'forge', 1),
    ('/v1/forge/blueprint/12', 'forge', 1),
    ('/v1/forge/blueprint/13', 'forge', 1),
    ('/v1/forge/blueprint/14', 'forge', 1),
    ('/v1/forge/blueprint/15', 'forge', 1),
    ('/v1/forge/blueprint/16', 'forge', 1),
    ('/v1/forge/blueprint/17', 'forge', 1),
    ('/v1/forge/blueprint/18', 'forge', 1),
    ('/v1/forge/blueprint/19', 'forge', 1),
    ('/v1/forge/blueprint/20', 'forge', 1),
    ('/v1/forge/blueprint/21', 'forge', 1),
    ('/v1/forge/blueprint/22', 'forge', 1),
    ('/v1/forge/blueprint/23', 'forge', 1),
    ('/v1/forge/blueprint/24', 'forge', 1),
    ('/v1/forge/blueprint/25', 'forge', 1),
    ('/v1/forge/blueprint/26', 'forge', 1),
    ('/v1/forge/blueprint/27', 'forge', 1),
    ('/v1/forge/blueprint/28', 'forge', 1),
    ('/v1/forge/blueprint/29', 'forge', 1),
    ('/v1/forge/blueprint/30', 'forge', 1),
    ('/v1/forge/blueprint/31', 'forge', 1),
    ('/v1/forge/blueprint/32', 'forge', 1),
    ('/v1/forge/blueprint/33', 'forge', 1),
    ('/v1/forge/blueprint/34', 'forge', 1),
    ('/v1/forge/blueprint/35', 'forge', 1),
    ('/v1/forge/blueprint/36', 'forge', 1),
    ('/v1/forge/blueprint/37', 'forge', 1),
    ('/v1/forge/blueprint/38', 'forge', 1),
    ('/v1/forge/blueprint/39', 'forge', 1),
    ('/v1/forge/blueprint/40', 'forge', 1),
    ('/v1/forge/blueprint/41', 'forge', 1),
    ('/v1/forge/blueprint/42', 'forge', 1),
    ('/v1/forge/blueprint/43', 'forge', 1),
    ('/v1/forge/blueprint/44', 'forge', 1),
    ('/v1/forge/blueprint/45', 'forge', 1),
    ('/v1/forge/blueprint/46', 'forge', 1),
    ('/v1/forge/blueprint/47', 'forge', 1),
    ('/v1/forge/blueprint/48', 'forge', 1),
    ('/v1/forge/blueprint/49', 'forge', 1),
    ('/v1/forge/blueprint/50', 'forge', 1),
    ('/v1/forge/blueprint/51', 'forge', 1),
    ('/v1/forge/blueprint/52', 'forge', 1),
    ('/v1/forge/blueprint/53', 'forge', 1),
    ('/v1/forge/blueprint/54', 'forge', 1),
    ('/v1/forge/blueprint/55', 'forge', 1),
    ('/v1/forge/blueprint/56', 'forge', 1),
    ('/v1/forge/blueprint/57', 'forge', 1),
    ('/v1/forge/blueprint/58', 'forge', 1),
    ('/v1/forge/blueprint/59', 'forge', 1),
    ('/v1/forge/blueprint/60', 'forge', 1),
    ('/v1/forge/blueprint/61', 'forge', 1),
    ('/v1/forge/blueprint/62', 'forge', 1),
    ('/v1/forge/blueprint/63', 'forge', 1),
    ('/v1/forge/blueprint/64', 'forge', 1),
    ('/v1/forge/blueprint/65', 'forge', 1),
    ('/v1/forge/blueprint/66', 'forge', 1),
    ('/v1/forge/blueprint/67', 'forge', 1),
    ('/v1/forge/blueprint/68', 'forge', 1),
    ('/v1/forge/blueprint/69', 'forge', 1),
    ('/v1/forge/blueprint/70', 'forge', 1),
    ('/v1/forge/blueprint/71', 'forge', 1),
    ('/v1/forge/blueprint/72', 'forge', 1),
    ('/v1/forge/blueprint/73', 'forge', 1),
    ('/v1/forge/blueprint/74', 'forge', 1),
    ('/v1/forge/blueprint/75', 'forge', 1),
    ('/v1/forge/blueprint/76', 'forge', 1),
    ('/v1/forge/blueprint/77', 'forge', 1),
    ('/v1/forge/blueprint/78', 'forge', 1),
    ('/v1/forge/blueprint/79', 'forge', 1),
    ('/v1/telemetry/event/0', 'telemetry', 2),
    ('/v1/telemetry/event/1', 'telemetry', 2),
    ('/v1/telemetry/event/2', 'telemetry', 2),
    ('/v1/telemetry/event/3', 'telemetry', 2),
    ('/v1/telemetry/event/4', 'telemetry', 2),
    ('/v1/telemetry/event/5', 'telemetry', 2),
    ('/v1/telemetry/event/6', 'telemetry', 2),
    ('/v1/telemetry/event/7', 'telemetry', 2),
    ('/v1/telemetry/event/8', 'telemetry', 2),
    ('/v1/telemetry/event/9', 'telemetry', 2),
    ('/v1/telemetry/event/10', 'telemetry', 2),
    ('/v1/telemetry/event/11', 'telemetry', 2),
    ('/v1/telemetry/event/12', 'telemetry', 2),
    ('/v1/telemetry/event/13', 'telemetry', 2),
    ('/v1/telemetry/event/14', 'telemetry', 2),
    ('/v1/telemetry/event/15', 'telemetry', 2),
    ('/v1/telemetry/event/16', 'telemetry', 2),
    ('/v1/telemetry/event/17', 'telemetry', 2),
    ('/v1/telemetry/event/18', 'telemetry', 2),
    ('/v1/telemetry/event/19', 'telemetry', 2),
    ('/v1/telemetry/event/20', 'telemetry', 2),
    ('/v1/telemetry/event/21', 'telemetry', 2),
    ('/v1/telemetry/event/22', 'telemetry', 2),
    ('/v1/telemetry/event/23', 'telemetry', 2),
    ('/v1/telemetry/event/24', 'telemetry', 2),
    ('/v1/telemetry/event/25', 'telemetry', 2),
    ('/v1/telemetry/event/26', 'telemetry', 2),
    ('/v1/telemetry/event/27', 'telemetry', 2),
    ('/v1/telemetry/event/28', 'telemetry', 2),
    ('/v1/telemetry/event/29', 'telemetry', 2),
    ('/v1/telemetry/event/30', 'telemetry', 2),
    ('/v1/telemetry/event/31', 'telemetry', 2),
    ('/v1/telemetry/event/32', 'telemetry', 2),
    ('/v1/telemetry/event/33', 'telemetry', 2),
    ('/v1/telemetry/event/34', 'telemetry', 2),
    ('/v1/telemetry/event/35', 'telemetry', 2),
    ('/v1/telemetry/event/36', 'telemetry', 2),
    ('/v1/telemetry/event/37', 'telemetry', 2),
    ('/v1/telemetry/event/38', 'telemetry', 2),
    ('/v1/telemetry/event/39', 'telemetry', 2),
    ('/v1/admin/ops/0', 'control', 0),
    ('/v1/admin/ops/1', 'control', 0),
    ('/v1/admin/ops/2', 'control', 0),
    ('/v1/admin/ops/3', 'control', 0),
    ('/v1/admin/ops/4', 'control', 0),
    ('/v1/admin/ops/5', 'control', 0),
    ('/v1/admin/ops/6', 'control', 0),
    ('/v1/admin/ops/7', 'control', 0),
    ('/v1/admin/ops/8', 'control', 0),
    ('/v1/admin/ops/9', 'control', 0),
    ('/v1/admin/ops/10', 'control', 0),
    ('/v1/admin/ops/11', 'control', 0),
    ('/v1/admin/ops/12', 'control', 0),
    ('/v1/admin/ops/13', 'control', 0),
    ('/v1/admin/ops/14', 'control', 0),
    ('/v1/admin/ops/15', 'control', 0),
    ('/v1/admin/ops/16', 'control', 0),
    ('/v1/admin/ops/17', 'control', 0),
    ('/v1/admin/ops/18', 'control', 0),
    ('/v1/admin/ops/19', 'control', 0),
    ('/v1/admin/ops/20', 'control', 0),
    ('/v1/admin/ops/21', 'control', 0),
    ('/v1/admin/ops/22', 'control', 0),
    ('/v1/admin/ops/23', 'control', 0),
    ('/v1/admin/ops/24', 'control', 0),
    ('/v1/admin/ops/25', 'control', 0),
    ('/v1/admin/ops/26', 'control', 0),
    ('/v1/admin/ops/27', 'control', 0),
    ('/v1/admin/ops/28', 'control', 0),
    ('/v1/admin/ops/29', 'control', 0),
]

_PREFIX_INDEX: Dict[str, Tuple[str, int]] = {}
for _path, _rc, _pr in PRIORITY_TABLE:
    _PREFIX_INDEX[_path] = (_rc, _pr)


def route_class_for_path(path: str) -> str:
    p = path or "/"
    if p in _PREFIX_INDEX:
        return _PREFIX_INDEX[p][0]
    # longest prefix match
    best = ""
    best_rc = "default"
    for key, (rc, _pr) in _PREFIX_INDEX.items():
        if p.startswith(key) and len(key) > len(best):
            best = key
            best_rc = rc
    if best:
        return best_rc
    from skeleton.kernel.pack_a.buffer_arena import classify_path
    return classify_path(p)


def priority_for_path(path: str) -> int:
    p = path or "/"
    if p in _PREFIX_INDEX:
        return _PREFIX_INDEX[p][1]
    best = ""
    best_pr = 1
    for key, (_rc, pr) in _PREFIX_INDEX.items():
        if p.startswith(key) and len(key) > len(best):
            best = key
            best_pr = pr
    return best_pr if best else 1


def table_size() -> int:
    return len(PRIORITY_TABLE)


def entries_for_class(route_class: str) -> List[Tuple[str, str, int]]:
    return [row for row in PRIORITY_TABLE if row[1] == route_class]


__all__ = [
    "PRIORITY_TABLE",
    "entries_for_class",
    "priority_for_path",
    "route_class_for_path",
    "table_size",
]
