"""Queue lattice — Pack C scheduling board for cortex jobs."""
from __future__ import annotations
from typing import Any, Mapping, Tuple

QUEUE_LATTICE: Tuple[Mapping[str, Any], ...] = (
    {
        "qid": "Q0001",
        "band": 1,
        "slot": "midbrain",
        "priority": 0.02,
        "allow_transformer": True,
        "label": "queue-cell-0001",
    },
    {
        "qid": "Q0002",
        "band": 2,
        "slot": "neo",
        "priority": 0.04,
        "allow_transformer": True,
        "label": "queue-cell-0002",
    },
    {
        "qid": "Q0003",
        "band": 3,
        "slot": "pfc",
        "priority": 0.06,
        "allow_transformer": False,
        "label": "queue-cell-0003",
    },
    {
        "qid": "Q0004",
        "band": 4,
        "slot": "midbrain",
        "priority": 0.08,
        "allow_transformer": True,
        "label": "queue-cell-0004",
    },
    {
        "qid": "Q0005",
        "band": 5,
        "slot": "neo",
        "priority": 0.1,
        "allow_transformer": True,
        "label": "queue-cell-0005",
    },
    {
        "qid": "Q0006",
        "band": 6,
        "slot": "pfc",
        "priority": 0.12,
        "allow_transformer": False,
        "label": "queue-cell-0006",
    },
    {
        "qid": "Q0007",
        "band": 7,
        "slot": "midbrain",
        "priority": 0.14,
        "allow_transformer": True,
        "label": "queue-cell-0007",
    },
    {
        "qid": "Q0008",
        "band": 8,
        "slot": "neo",
        "priority": 0.16,
        "allow_transformer": True,
        "label": "queue-cell-0008",
    },
    {
        "qid": "Q0009",
        "band": 9,
        "slot": "pfc",
        "priority": 0.18,
        "allow_transformer": False,
        "label": "queue-cell-0009",
    },
    {
        "qid": "Q0010",
        "band": 10,
        "slot": "midbrain",
        "priority": 0.2,
        "allow_transformer": True,
        "label": "queue-cell-0010",
    },
    {
        "qid": "Q0011",
        "band": 11,
        "slot": "neo",
        "priority": 0.22,
        "allow_transformer": True,
        "label": "queue-cell-0011",
    },
    {
        "qid": "Q0012",
        "band": 12,
        "slot": "pfc",
        "priority": 0.24,
        "allow_transformer": False,
        "label": "queue-cell-0012",
    },
    {
        "qid": "Q0013",
        "band": 13,
        "slot": "midbrain",
        "priority": 0.26,
        "allow_transformer": True,
        "label": "queue-cell-0013",
    },
    {
        "qid": "Q0014",
        "band": 14,
        "slot": "neo",
        "priority": 0.28,
        "allow_transformer": True,
        "label": "queue-cell-0014",
    },
    {
        "qid": "Q0015",
        "band": 15,
        "slot": "pfc",
        "priority": 0.3,
        "allow_transformer": False,
        "label": "queue-cell-0015",
    },
    {
        "qid": "Q0016",
        "band": 16,
        "slot": "midbrain",
        "priority": 0.32,
        "allow_transformer": True,
        "label": "queue-cell-0016",
    },
    {
        "qid": "Q0017",
        "band": 17,
        "slot": "neo",
        "priority": 0.34,
        "allow_transformer": True,
        "label": "queue-cell-0017",
    },
    {
        "qid": "Q0018",
        "band": 18,
        "slot": "pfc",
        "priority": 0.36,
        "allow_transformer": False,
        "label": "queue-cell-0018",
    },
    {
        "qid": "Q0019",
        "band": 19,
        "slot": "midbrain",
        "priority": 0.38,
        "allow_transformer": True,
        "label": "queue-cell-0019",
    },
    {
        "qid": "Q0020",
        "band": 20,
        "slot": "neo",
        "priority": 0.4,
        "allow_transformer": True,
        "label": "queue-cell-0020",
    },
    {
        "qid": "Q0021",
        "band": 21,
        "slot": "pfc",
        "priority": 0.42,
        "allow_transformer": False,
        "label": "queue-cell-0021",
    },
    {
        "qid": "Q0022",
        "band": 22,
        "slot": "midbrain",
        "priority": 0.44,
        "allow_transformer": True,
        "label": "queue-cell-0022",
    },
    {
        "qid": "Q0023",
        "band": 23,
        "slot": "neo",
        "priority": 0.46,
        "allow_transformer": True,
        "label": "queue-cell-0023",
    },
    {
        "qid": "Q0024",
        "band": 24,
        "slot": "pfc",
        "priority": 0.48,
        "allow_transformer": False,
        "label": "queue-cell-0024",
    },
    {
        "qid": "Q0025",
        "band": 25,
        "slot": "midbrain",
        "priority": 0.5,
        "allow_transformer": True,
        "label": "queue-cell-0025",
    },
    {
        "qid": "Q0026",
        "band": 26,
        "slot": "neo",
        "priority": 0.52,
        "allow_transformer": True,
        "label": "queue-cell-0026",
    },
    {
        "qid": "Q0027",
        "band": 27,
        "slot": "pfc",
        "priority": 0.54,
        "allow_transformer": False,
        "label": "queue-cell-0027",
    },
    {
        "qid": "Q0028",
        "band": 28,
        "slot": "midbrain",
        "priority": 0.56,
        "allow_transformer": True,
        "label": "queue-cell-0028",
    },
    {
        "qid": "Q0029",
        "band": 29,
        "slot": "neo",
        "priority": 0.58,
        "allow_transformer": True,
        "label": "queue-cell-0029",
    },
    {
        "qid": "Q0030",
        "band": 0,
        "slot": "pfc",
        "priority": 0.6,
        "allow_transformer": False,
        "label": "queue-cell-0030",
    },
    {
        "qid": "Q0031",
        "band": 1,
        "slot": "midbrain",
        "priority": 0.62,
        "allow_transformer": True,
        "label": "queue-cell-0031",
    },
    {
        "qid": "Q0032",
        "band": 2,
        "slot": "neo",
        "priority": 0.64,
        "allow_transformer": True,
        "label": "queue-cell-0032",
    },
    {
        "qid": "Q0033",
        "band": 3,
        "slot": "pfc",
        "priority": 0.66,
        "allow_transformer": False,
        "label": "queue-cell-0033",
    },
    {
        "qid": "Q0034",
        "band": 4,
        "slot": "midbrain",
        "priority": 0.68,
        "allow_transformer": True,
        "label": "queue-cell-0034",
    },
    {
        "qid": "Q0035",
        "band": 5,
        "slot": "neo",
        "priority": 0.7,
        "allow_transformer": True,
        "label": "queue-cell-0035",
    },
    {
        "qid": "Q0036",
        "band": 6,
        "slot": "pfc",
        "priority": 0.72,
        "allow_transformer": False,
        "label": "queue-cell-0036",
    },
    {
        "qid": "Q0037",
        "band": 7,
        "slot": "midbrain",
        "priority": 0.74,
        "allow_transformer": True,
        "label": "queue-cell-0037",
    },
    {
        "qid": "Q0038",
        "band": 8,
        "slot": "neo",
        "priority": 0.76,
        "allow_transformer": True,
        "label": "queue-cell-0038",
    },
    {
        "qid": "Q0039",
        "band": 9,
        "slot": "pfc",
        "priority": 0.78,
        "allow_transformer": False,
        "label": "queue-cell-0039",
    },
    {
        "qid": "Q0040",
        "band": 10,
        "slot": "midbrain",
        "priority": 0.8,
        "allow_transformer": True,
        "label": "queue-cell-0040",
    },
    {
        "qid": "Q0041",
        "band": 11,
        "slot": "neo",
        "priority": 0.82,
        "allow_transformer": True,
        "label": "queue-cell-0041",
    },
    {
        "qid": "Q0042",
        "band": 12,
        "slot": "pfc",
        "priority": 0.84,
        "allow_transformer": False,
        "label": "queue-cell-0042",
    },
    {
        "qid": "Q0043",
        "band": 13,
        "slot": "midbrain",
        "priority": 0.86,
        "allow_transformer": True,
        "label": "queue-cell-0043",
    },
    {
        "qid": "Q0044",
        "band": 14,
        "slot": "neo",
        "priority": 0.88,
        "allow_transformer": True,
        "label": "queue-cell-0044",
    },
    {
        "qid": "Q0045",
        "band": 15,
        "slot": "pfc",
        "priority": 0.9,
        "allow_transformer": False,
        "label": "queue-cell-0045",
    },
    {
        "qid": "Q0046",
        "band": 16,
        "slot": "midbrain",
        "priority": 0.92,
        "allow_transformer": True,
        "label": "queue-cell-0046",
    },
    {
        "qid": "Q0047",
        "band": 17,
        "slot": "neo",
        "priority": 0.94,
        "allow_transformer": True,
        "label": "queue-cell-0047",
    },
    {
        "qid": "Q0048",
        "band": 18,
        "slot": "pfc",
        "priority": 0.96,
        "allow_transformer": False,
        "label": "queue-cell-0048",
    },
    {
        "qid": "Q0049",
        "band": 19,
        "slot": "midbrain",
        "priority": 0.98,
        "allow_transformer": True,
        "label": "queue-cell-0049",
    },
    {
        "qid": "Q0050",
        "band": 20,
        "slot": "neo",
        "priority": 0.0,
        "allow_transformer": True,
        "label": "queue-cell-0050",
    },
    {
        "qid": "Q0051",
        "band": 21,
        "slot": "pfc",
        "priority": 0.02,
        "allow_transformer": False,
        "label": "queue-cell-0051",
    },
    {
        "qid": "Q0052",
        "band": 22,
        "slot": "midbrain",
        "priority": 0.04,
        "allow_transformer": True,
        "label": "queue-cell-0052",
    },
    {
        "qid": "Q0053",
        "band": 23,
        "slot": "neo",
        "priority": 0.06,
        "allow_transformer": True,
        "label": "queue-cell-0053",
    },
    {
        "qid": "Q0054",
        "band": 24,
        "slot": "pfc",
        "priority": 0.08,
        "allow_transformer": False,
        "label": "queue-cell-0054",
    },
    {
        "qid": "Q0055",
        "band": 25,
        "slot": "midbrain",
        "priority": 0.1,
        "allow_transformer": True,
        "label": "queue-cell-0055",
    },
    {
        "qid": "Q0056",
        "band": 26,
        "slot": "neo",
        "priority": 0.12,
        "allow_transformer": True,
        "label": "queue-cell-0056",
    },
    {
        "qid": "Q0057",
        "band": 27,
        "slot": "pfc",
        "priority": 0.14,
        "allow_transformer": False,
        "label": "queue-cell-0057",
    },
    {
        "qid": "Q0058",
        "band": 28,
        "slot": "midbrain",
        "priority": 0.16,
        "allow_transformer": True,
        "label": "queue-cell-0058",
    },
    {
        "qid": "Q0059",
        "band": 29,
        "slot": "neo",
        "priority": 0.18,
        "allow_transformer": True,
        "label": "queue-cell-0059",
    },
    {
        "qid": "Q0060",
        "band": 0,
        "slot": "pfc",
        "priority": 0.2,
        "allow_transformer": False,
        "label": "queue-cell-0060",
    },
    {
        "qid": "Q0061",
        "band": 1,
        "slot": "midbrain",
        "priority": 0.22,
        "allow_transformer": True,
        "label": "queue-cell-0061",
    },
    {
        "qid": "Q0062",
        "band": 2,
        "slot": "neo",
        "priority": 0.24,
        "allow_transformer": True,
        "label": "queue-cell-0062",
    },
    {
        "qid": "Q0063",
        "band": 3,
        "slot": "pfc",
        "priority": 0.26,
        "allow_transformer": False,
        "label": "queue-cell-0063",
    },
    {
        "qid": "Q0064",
        "band": 4,
        "slot": "midbrain",
        "priority": 0.28,
        "allow_transformer": True,
        "label": "queue-cell-0064",
    },
    {
        "qid": "Q0065",
        "band": 5,
        "slot": "neo",
        "priority": 0.3,
        "allow_transformer": True,
        "label": "queue-cell-0065",
    },
    {
        "qid": "Q0066",
        "band": 6,
        "slot": "pfc",
        "priority": 0.32,
        "allow_transformer": False,
        "label": "queue-cell-0066",
    },
    {
        "qid": "Q0067",
        "band": 7,
        "slot": "midbrain",
        "priority": 0.34,
        "allow_transformer": True,
        "label": "queue-cell-0067",
    },
    {
        "qid": "Q0068",
        "band": 8,
        "slot": "neo",
        "priority": 0.36,
        "allow_transformer": True,
        "label": "queue-cell-0068",
    },
    {
        "qid": "Q0069",
        "band": 9,
        "slot": "pfc",
        "priority": 0.38,
        "allow_transformer": False,
        "label": "queue-cell-0069",
    },
    {
        "qid": "Q0070",
        "band": 10,
        "slot": "midbrain",
        "priority": 0.4,
        "allow_transformer": True,
        "label": "queue-cell-0070",
    },
    {
        "qid": "Q0071",
        "band": 11,
        "slot": "neo",
        "priority": 0.42,
        "allow_transformer": True,
        "label": "queue-cell-0071",
    },
    {
        "qid": "Q0072",
        "band": 12,
        "slot": "pfc",
        "priority": 0.44,
        "allow_transformer": False,
        "label": "queue-cell-0072",
    },
    {
        "qid": "Q0073",
        "band": 13,
        "slot": "midbrain",
        "priority": 0.46,
        "allow_transformer": True,
        "label": "queue-cell-0073",
    },
    {
        "qid": "Q0074",
        "band": 14,
        "slot": "neo",
        "priority": 0.48,
        "allow_transformer": True,
        "label": "queue-cell-0074",
    },
    {
        "qid": "Q0075",
        "band": 15,
        "slot": "pfc",
        "priority": 0.5,
        "allow_transformer": False,
        "label": "queue-cell-0075",
    },
    {
        "qid": "Q0076",
        "band": 16,
        "slot": "midbrain",
        "priority": 0.52,
        "allow_transformer": True,
        "label": "queue-cell-0076",
    },
    {
        "qid": "Q0077",
        "band": 17,
        "slot": "neo",
        "priority": 0.54,
        "allow_transformer": True,
        "label": "queue-cell-0077",
    },
    {
        "qid": "Q0078",
        "band": 18,
        "slot": "pfc",
        "priority": 0.56,
        "allow_transformer": False,
        "label": "queue-cell-0078",
    },
    {
        "qid": "Q0079",
        "band": 19,
        "slot": "midbrain",
        "priority": 0.58,
        "allow_transformer": True,
        "label": "queue-cell-0079",
    },
    {
        "qid": "Q0080",
        "band": 20,
        "slot": "neo",
        "priority": 0.6,
        "allow_transformer": True,
        "label": "queue-cell-0080",
    },
    {
        "qid": "Q0081",
        "band": 21,
        "slot": "pfc",
        "priority": 0.62,
        "allow_transformer": False,
        "label": "queue-cell-0081",
    },
    {
        "qid": "Q0082",
        "band": 22,
        "slot": "midbrain",
        "priority": 0.64,
        "allow_transformer": True,
        "label": "queue-cell-0082",
    },
    {
        "qid": "Q0083",
        "band": 23,
        "slot": "neo",
        "priority": 0.66,
        "allow_transformer": True,
        "label": "queue-cell-0083",
    },
    {
        "qid": "Q0084",
        "band": 24,
        "slot": "pfc",
        "priority": 0.68,
        "allow_transformer": False,
        "label": "queue-cell-0084",
    },
    {
        "qid": "Q0085",
        "band": 25,
        "slot": "midbrain",
        "priority": 0.7,
        "allow_transformer": True,
        "label": "queue-cell-0085",
    },
    {
        "qid": "Q0086",
        "band": 26,
        "slot": "neo",
        "priority": 0.72,
        "allow_transformer": True,
        "label": "queue-cell-0086",
    },
    {
        "qid": "Q0087",
        "band": 27,
        "slot": "pfc",
        "priority": 0.74,
        "allow_transformer": False,
        "label": "queue-cell-0087",
    },
    {
        "qid": "Q0088",
        "band": 28,
        "slot": "midbrain",
        "priority": 0.76,
        "allow_transformer": True,
        "label": "queue-cell-0088",
    },
    {
        "qid": "Q0089",
        "band": 29,
        "slot": "neo",
        "priority": 0.78,
        "allow_transformer": True,
        "label": "queue-cell-0089",
    },
    {
        "qid": "Q0090",
        "band": 0,
        "slot": "pfc",
        "priority": 0.8,
        "allow_transformer": False,
        "label": "queue-cell-0090",
    },
    {
        "qid": "Q0091",
        "band": 1,
        "slot": "midbrain",
        "priority": 0.82,
        "allow_transformer": True,
        "label": "queue-cell-0091",
    },
    {
        "qid": "Q0092",
        "band": 2,
        "slot": "neo",
        "priority": 0.84,
        "allow_transformer": True,
        "label": "queue-cell-0092",
    },
    {
        "qid": "Q0093",
        "band": 3,
        "slot": "pfc",
        "priority": 0.86,
        "allow_transformer": False,
        "label": "queue-cell-0093",
    },
    {
        "qid": "Q0094",
        "band": 4,
        "slot": "midbrain",
        "priority": 0.88,
        "allow_transformer": True,
        "label": "queue-cell-0094",
    },
    {
        "qid": "Q0095",
        "band": 5,
        "slot": "neo",
        "priority": 0.9,
        "allow_transformer": True,
        "label": "queue-cell-0095",
    },
    {
        "qid": "Q0096",
        "band": 6,
        "slot": "pfc",
        "priority": 0.92,
        "allow_transformer": False,
        "label": "queue-cell-0096",
    },
    {
        "qid": "Q0097",
        "band": 7,
        "slot": "midbrain",
        "priority": 0.94,
        "allow_transformer": True,
        "label": "queue-cell-0097",
    },
    {
        "qid": "Q0098",
        "band": 8,
        "slot": "neo",
        "priority": 0.96,
        "allow_transformer": True,
        "label": "queue-cell-0098",
    },
    {
        "qid": "Q0099",
        "band": 9,
        "slot": "pfc",
        "priority": 0.98,
        "allow_transformer": False,
        "label": "queue-cell-0099",
    },
    {
        "qid": "Q0100",
        "band": 10,
        "slot": "midbrain",
        "priority": 0.0,
        "allow_transformer": True,
        "label": "queue-cell-0100",
    },
    {
        "qid": "Q0101",
        "band": 11,
        "slot": "neo",
        "priority": 0.02,
        "allow_transformer": True,
        "label": "queue-cell-0101",
    },
    {
        "qid": "Q0102",
        "band": 12,
        "slot": "pfc",
        "priority": 0.04,
        "allow_transformer": False,
        "label": "queue-cell-0102",
    },
    {
        "qid": "Q0103",
        "band": 13,
        "slot": "midbrain",
        "priority": 0.06,
        "allow_transformer": True,
        "label": "queue-cell-0103",
    },
    {
        "qid": "Q0104",
        "band": 14,
        "slot": "neo",
        "priority": 0.08,
        "allow_transformer": True,
        "label": "queue-cell-0104",
    },
    {
        "qid": "Q0105",
        "band": 15,
        "slot": "pfc",
        "priority": 0.1,
        "allow_transformer": False,
        "label": "queue-cell-0105",
    },
    {
        "qid": "Q0106",
        "band": 16,
        "slot": "midbrain",
        "priority": 0.12,
        "allow_transformer": True,
        "label": "queue-cell-0106",
    },
    {
        "qid": "Q0107",
        "band": 17,
        "slot": "neo",
        "priority": 0.14,
        "allow_transformer": True,
        "label": "queue-cell-0107",
    },
    {
        "qid": "Q0108",
        "band": 18,
        "slot": "pfc",
        "priority": 0.16,
        "allow_transformer": False,
        "label": "queue-cell-0108",
    },
    {
        "qid": "Q0109",
        "band": 19,
        "slot": "midbrain",
        "priority": 0.18,
        "allow_transformer": True,
        "label": "queue-cell-0109",
    },
    {
        "qid": "Q0110",
        "band": 20,
        "slot": "neo",
        "priority": 0.2,
        "allow_transformer": True,
        "label": "queue-cell-0110",
    },
    {
        "qid": "Q0111",
        "band": 21,
        "slot": "pfc",
        "priority": 0.22,
        "allow_transformer": False,
        "label": "queue-cell-0111",
    },
    {
        "qid": "Q0112",
        "band": 22,
        "slot": "midbrain",
        "priority": 0.24,
        "allow_transformer": True,
        "label": "queue-cell-0112",
    },
    {
        "qid": "Q0113",
        "band": 23,
        "slot": "neo",
        "priority": 0.26,
        "allow_transformer": True,
        "label": "queue-cell-0113",
    },
    {
        "qid": "Q0114",
        "band": 24,
        "slot": "pfc",
        "priority": 0.28,
        "allow_transformer": False,
        "label": "queue-cell-0114",
    },
    {
        "qid": "Q0115",
        "band": 25,
        "slot": "midbrain",
        "priority": 0.3,
        "allow_transformer": True,
        "label": "queue-cell-0115",
    },
    {
        "qid": "Q0116",
        "band": 26,
        "slot": "neo",
        "priority": 0.32,
        "allow_transformer": True,
        "label": "queue-cell-0116",
    },
    {
        "qid": "Q0117",
        "band": 27,
        "slot": "pfc",
        "priority": 0.34,
        "allow_transformer": False,
        "label": "queue-cell-0117",
    },
    {
        "qid": "Q0118",
        "band": 28,
        "slot": "midbrain",
        "priority": 0.36,
        "allow_transformer": True,
        "label": "queue-cell-0118",
    },
    {
        "qid": "Q0119",
        "band": 29,
        "slot": "neo",
        "priority": 0.38,
        "allow_transformer": True,
        "label": "queue-cell-0119",
    },
    {
        "qid": "Q0120",
        "band": 0,
        "slot": "pfc",
        "priority": 0.4,
        "allow_transformer": False,
        "label": "queue-cell-0120",
    },
    {
        "qid": "Q0121",
        "band": 1,
        "slot": "midbrain",
        "priority": 0.42,
        "allow_transformer": True,
        "label": "queue-cell-0121",
    },
    {
        "qid": "Q0122",
        "band": 2,
        "slot": "neo",
        "priority": 0.44,
        "allow_transformer": True,
        "label": "queue-cell-0122",
    },
    {
        "qid": "Q0123",
        "band": 3,
        "slot": "pfc",
        "priority": 0.46,
        "allow_transformer": False,
        "label": "queue-cell-0123",
    },
    {
        "qid": "Q0124",
        "band": 4,
        "slot": "midbrain",
        "priority": 0.48,
        "allow_transformer": True,
        "label": "queue-cell-0124",
    },
    {
        "qid": "Q0125",
        "band": 5,
        "slot": "neo",
        "priority": 0.5,
        "allow_transformer": True,
        "label": "queue-cell-0125",
    },
    {
        "qid": "Q0126",
        "band": 6,
        "slot": "pfc",
        "priority": 0.52,
        "allow_transformer": False,
        "label": "queue-cell-0126",
    },
    {
        "qid": "Q0127",
        "band": 7,
        "slot": "midbrain",
        "priority": 0.54,
        "allow_transformer": True,
        "label": "queue-cell-0127",
    },
    {
        "qid": "Q0128",
        "band": 8,
        "slot": "neo",
        "priority": 0.56,
        "allow_transformer": True,
        "label": "queue-cell-0128",
    },
    {
        "qid": "Q0129",
        "band": 9,
        "slot": "pfc",
        "priority": 0.58,
        "allow_transformer": False,
        "label": "queue-cell-0129",
    },
    {
        "qid": "Q0130",
        "band": 10,
        "slot": "midbrain",
        "priority": 0.6,
        "allow_transformer": True,
        "label": "queue-cell-0130",
    },
    {
        "qid": "Q0131",
        "band": 11,
        "slot": "neo",
        "priority": 0.62,
        "allow_transformer": True,
        "label": "queue-cell-0131",
    },
    {
        "qid": "Q0132",
        "band": 12,
        "slot": "pfc",
        "priority": 0.64,
        "allow_transformer": False,
        "label": "queue-cell-0132",
    },
    {
        "qid": "Q0133",
        "band": 13,
        "slot": "midbrain",
        "priority": 0.66,
        "allow_transformer": True,
        "label": "queue-cell-0133",
    },
    {
        "qid": "Q0134",
        "band": 14,
        "slot": "neo",
        "priority": 0.68,
        "allow_transformer": True,
        "label": "queue-cell-0134",
    },
    {
        "qid": "Q0135",
        "band": 15,
        "slot": "pfc",
        "priority": 0.7,
        "allow_transformer": False,
        "label": "queue-cell-0135",
    },
    {
        "qid": "Q0136",
        "band": 16,
        "slot": "midbrain",
        "priority": 0.72,
        "allow_transformer": True,
        "label": "queue-cell-0136",
    },
    {
        "qid": "Q0137",
        "band": 17,
        "slot": "neo",
        "priority": 0.74,
        "allow_transformer": True,
        "label": "queue-cell-0137",
    },
    {
        "qid": "Q0138",
        "band": 18,
        "slot": "pfc",
        "priority": 0.76,
        "allow_transformer": False,
        "label": "queue-cell-0138",
    },
    {
        "qid": "Q0139",
        "band": 19,
        "slot": "midbrain",
        "priority": 0.78,
        "allow_transformer": True,
        "label": "queue-cell-0139",
    },
    {
        "qid": "Q0140",
        "band": 20,
        "slot": "neo",
        "priority": 0.8,
        "allow_transformer": True,
        "label": "queue-cell-0140",
    },
    {
        "qid": "Q0141",
        "band": 21,
        "slot": "pfc",
        "priority": 0.82,
        "allow_transformer": False,
        "label": "queue-cell-0141",
    },
    {
        "qid": "Q0142",
        "band": 22,
        "slot": "midbrain",
        "priority": 0.84,
        "allow_transformer": True,
        "label": "queue-cell-0142",
    },
    {
        "qid": "Q0143",
        "band": 23,
        "slot": "neo",
        "priority": 0.86,
        "allow_transformer": True,
        "label": "queue-cell-0143",
    },
    {
        "qid": "Q0144",
        "band": 24,
        "slot": "pfc",
        "priority": 0.88,
        "allow_transformer": False,
        "label": "queue-cell-0144",
    },
    {
        "qid": "Q0145",
        "band": 25,
        "slot": "midbrain",
        "priority": 0.9,
        "allow_transformer": True,
        "label": "queue-cell-0145",
    },
    {
        "qid": "Q0146",
        "band": 26,
        "slot": "neo",
        "priority": 0.92,
        "allow_transformer": True,
        "label": "queue-cell-0146",
    },
    {
        "qid": "Q0147",
        "band": 27,
        "slot": "pfc",
        "priority": 0.94,
        "allow_transformer": False,
        "label": "queue-cell-0147",
    },
    {
        "qid": "Q0148",
        "band": 28,
        "slot": "midbrain",
        "priority": 0.96,
        "allow_transformer": True,
        "label": "queue-cell-0148",
    },
    {
        "qid": "Q0149",
        "band": 29,
        "slot": "neo",
        "priority": 0.98,
        "allow_transformer": True,
        "label": "queue-cell-0149",
    },
    {
        "qid": "Q0150",
        "band": 0,
        "slot": "pfc",
        "priority": 0.0,
        "allow_transformer": False,
        "label": "queue-cell-0150",
    },
    {
        "qid": "Q0151",
        "band": 1,
        "slot": "midbrain",
        "priority": 0.02,
        "allow_transformer": True,
        "label": "queue-cell-0151",
    },
    {
        "qid": "Q0152",
        "band": 2,
        "slot": "neo",
        "priority": 0.04,
        "allow_transformer": True,
        "label": "queue-cell-0152",
    },
    {
        "qid": "Q0153",
        "band": 3,
        "slot": "pfc",
        "priority": 0.06,
        "allow_transformer": False,
        "label": "queue-cell-0153",
    },
    {
        "qid": "Q0154",
        "band": 4,
        "slot": "midbrain",
        "priority": 0.08,
        "allow_transformer": True,
        "label": "queue-cell-0154",
    },
    {
        "qid": "Q0155",
        "band": 5,
        "slot": "neo",
        "priority": 0.1,
        "allow_transformer": True,
        "label": "queue-cell-0155",
    },
    {
        "qid": "Q0156",
        "band": 6,
        "slot": "pfc",
        "priority": 0.12,
        "allow_transformer": False,
        "label": "queue-cell-0156",
    },
    {
        "qid": "Q0157",
        "band": 7,
        "slot": "midbrain",
        "priority": 0.14,
        "allow_transformer": True,
        "label": "queue-cell-0157",
    },
    {
        "qid": "Q0158",
        "band": 8,
        "slot": "neo",
        "priority": 0.16,
        "allow_transformer": True,
        "label": "queue-cell-0158",
    },
    {
        "qid": "Q0159",
        "band": 9,
        "slot": "pfc",
        "priority": 0.18,
        "allow_transformer": False,
        "label": "queue-cell-0159",
    },
    {
        "qid": "Q0160",
        "band": 10,
        "slot": "midbrain",
        "priority": 0.2,
        "allow_transformer": True,
        "label": "queue-cell-0160",
    },
    {
        "qid": "Q0161",
        "band": 11,
        "slot": "neo",
        "priority": 0.22,
        "allow_transformer": True,
        "label": "queue-cell-0161",
    },
    {
        "qid": "Q0162",
        "band": 12,
        "slot": "pfc",
        "priority": 0.24,
        "allow_transformer": False,
        "label": "queue-cell-0162",
    },
    {
        "qid": "Q0163",
        "band": 13,
        "slot": "midbrain",
        "priority": 0.26,
        "allow_transformer": True,
        "label": "queue-cell-0163",
    },
    {
        "qid": "Q0164",
        "band": 14,
        "slot": "neo",
        "priority": 0.28,
        "allow_transformer": True,
        "label": "queue-cell-0164",
    },
    {
        "qid": "Q0165",
        "band": 15,
        "slot": "pfc",
        "priority": 0.3,
        "allow_transformer": False,
        "label": "queue-cell-0165",
    },
    {
        "qid": "Q0166",
        "band": 16,
        "slot": "midbrain",
        "priority": 0.32,
        "allow_transformer": True,
        "label": "queue-cell-0166",
    },
    {
        "qid": "Q0167",
        "band": 17,
        "slot": "neo",
        "priority": 0.34,
        "allow_transformer": True,
        "label": "queue-cell-0167",
    },
    {
        "qid": "Q0168",
        "band": 18,
        "slot": "pfc",
        "priority": 0.36,
        "allow_transformer": False,
        "label": "queue-cell-0168",
    },
    {
        "qid": "Q0169",
        "band": 19,
        "slot": "midbrain",
        "priority": 0.38,
        "allow_transformer": True,
        "label": "queue-cell-0169",
    },
    {
        "qid": "Q0170",
        "band": 20,
        "slot": "neo",
        "priority": 0.4,
        "allow_transformer": True,
        "label": "queue-cell-0170",
    },
    {
        "qid": "Q0171",
        "band": 21,
        "slot": "pfc",
        "priority": 0.42,
        "allow_transformer": False,
        "label": "queue-cell-0171",
    },
    {
        "qid": "Q0172",
        "band": 22,
        "slot": "midbrain",
        "priority": 0.44,
        "allow_transformer": True,
        "label": "queue-cell-0172",
    },
    {
        "qid": "Q0173",
        "band": 23,
        "slot": "neo",
        "priority": 0.46,
        "allow_transformer": True,
        "label": "queue-cell-0173",
    },
    {
        "qid": "Q0174",
        "band": 24,
        "slot": "pfc",
        "priority": 0.48,
        "allow_transformer": False,
        "label": "queue-cell-0174",
    },
    {
        "qid": "Q0175",
        "band": 25,
        "slot": "midbrain",
        "priority": 0.5,
        "allow_transformer": True,
        "label": "queue-cell-0175",
    },
    {
        "qid": "Q0176",
        "band": 26,
        "slot": "neo",
        "priority": 0.52,
        "allow_transformer": True,
        "label": "queue-cell-0176",
    },
    {
        "qid": "Q0177",
        "band": 27,
        "slot": "pfc",
        "priority": 0.54,
        "allow_transformer": False,
        "label": "queue-cell-0177",
    },
    {
        "qid": "Q0178",
        "band": 28,
        "slot": "midbrain",
        "priority": 0.56,
        "allow_transformer": True,
        "label": "queue-cell-0178",
    },
    {
        "qid": "Q0179",
        "band": 29,
        "slot": "neo",
        "priority": 0.58,
        "allow_transformer": True,
        "label": "queue-cell-0179",
    },
    {
        "qid": "Q0180",
        "band": 0,
        "slot": "pfc",
        "priority": 0.6,
        "allow_transformer": False,
        "label": "queue-cell-0180",
    },
    {
        "qid": "Q0181",
        "band": 1,
        "slot": "midbrain",
        "priority": 0.62,
        "allow_transformer": True,
        "label": "queue-cell-0181",
    },
    {
        "qid": "Q0182",
        "band": 2,
        "slot": "neo",
        "priority": 0.64,
        "allow_transformer": True,
        "label": "queue-cell-0182",
    },
    {
        "qid": "Q0183",
        "band": 3,
        "slot": "pfc",
        "priority": 0.66,
        "allow_transformer": False,
        "label": "queue-cell-0183",
    },
    {
        "qid": "Q0184",
        "band": 4,
        "slot": "midbrain",
        "priority": 0.68,
        "allow_transformer": True,
        "label": "queue-cell-0184",
    },
    {
        "qid": "Q0185",
        "band": 5,
        "slot": "neo",
        "priority": 0.7,
        "allow_transformer": True,
        "label": "queue-cell-0185",
    },
    {
        "qid": "Q0186",
        "band": 6,
        "slot": "pfc",
        "priority": 0.72,
        "allow_transformer": False,
        "label": "queue-cell-0186",
    },
    {
        "qid": "Q0187",
        "band": 7,
        "slot": "midbrain",
        "priority": 0.74,
        "allow_transformer": True,
        "label": "queue-cell-0187",
    },
    {
        "qid": "Q0188",
        "band": 8,
        "slot": "neo",
        "priority": 0.76,
        "allow_transformer": True,
        "label": "queue-cell-0188",
    },
    {
        "qid": "Q0189",
        "band": 9,
        "slot": "pfc",
        "priority": 0.78,
        "allow_transformer": False,
        "label": "queue-cell-0189",
    },
    {
        "qid": "Q0190",
        "band": 10,
        "slot": "midbrain",
        "priority": 0.8,
        "allow_transformer": True,
        "label": "queue-cell-0190",
    },
    {
        "qid": "Q0191",
        "band": 11,
        "slot": "neo",
        "priority": 0.82,
        "allow_transformer": True,
        "label": "queue-cell-0191",
    },
    {
        "qid": "Q0192",
        "band": 12,
        "slot": "pfc",
        "priority": 0.84,
        "allow_transformer": False,
        "label": "queue-cell-0192",
    },
    {
        "qid": "Q0193",
        "band": 13,
        "slot": "midbrain",
        "priority": 0.86,
        "allow_transformer": True,
        "label": "queue-cell-0193",
    },
    {
        "qid": "Q0194",
        "band": 14,
        "slot": "neo",
        "priority": 0.88,
        "allow_transformer": True,
        "label": "queue-cell-0194",
    },
    {
        "qid": "Q0195",
        "band": 15,
        "slot": "pfc",
        "priority": 0.9,
        "allow_transformer": False,
        "label": "queue-cell-0195",
    },
    {
        "qid": "Q0196",
        "band": 16,
        "slot": "midbrain",
        "priority": 0.92,
        "allow_transformer": True,
        "label": "queue-cell-0196",
    },
    {
        "qid": "Q0197",
        "band": 17,
        "slot": "neo",
        "priority": 0.94,
        "allow_transformer": True,
        "label": "queue-cell-0197",
    },
    {
        "qid": "Q0198",
        "band": 18,
        "slot": "pfc",
        "priority": 0.96,
        "allow_transformer": False,
        "label": "queue-cell-0198",
    },
    {
        "qid": "Q0199",
        "band": 19,
        "slot": "midbrain",
        "priority": 0.98,
        "allow_transformer": True,
        "label": "queue-cell-0199",
    },
    {
        "qid": "Q0200",
        "band": 20,
        "slot": "neo",
        "priority": 0.0,
        "allow_transformer": True,
        "label": "queue-cell-0200",
    },
    {
        "qid": "Q0201",
        "band": 21,
        "slot": "pfc",
        "priority": 0.02,
        "allow_transformer": False,
        "label": "queue-cell-0201",
    },
    {
        "qid": "Q0202",
        "band": 22,
        "slot": "midbrain",
        "priority": 0.04,
        "allow_transformer": True,
        "label": "queue-cell-0202",
    },
    {
        "qid": "Q0203",
        "band": 23,
        "slot": "neo",
        "priority": 0.06,
        "allow_transformer": True,
        "label": "queue-cell-0203",
    },
    {
        "qid": "Q0204",
        "band": 24,
        "slot": "pfc",
        "priority": 0.08,
        "allow_transformer": False,
        "label": "queue-cell-0204",
    },
    {
        "qid": "Q0205",
        "band": 25,
        "slot": "midbrain",
        "priority": 0.1,
        "allow_transformer": True,
        "label": "queue-cell-0205",
    },
    {
        "qid": "Q0206",
        "band": 26,
        "slot": "neo",
        "priority": 0.12,
        "allow_transformer": True,
        "label": "queue-cell-0206",
    },
    {
        "qid": "Q0207",
        "band": 27,
        "slot": "pfc",
        "priority": 0.14,
        "allow_transformer": False,
        "label": "queue-cell-0207",
    },
    {
        "qid": "Q0208",
        "band": 28,
        "slot": "midbrain",
        "priority": 0.16,
        "allow_transformer": True,
        "label": "queue-cell-0208",
    },
    {
        "qid": "Q0209",
        "band": 29,
        "slot": "neo",
        "priority": 0.18,
        "allow_transformer": True,
        "label": "queue-cell-0209",
    },
    {
        "qid": "Q0210",
        "band": 0,
        "slot": "pfc",
        "priority": 0.2,
        "allow_transformer": False,
        "label": "queue-cell-0210",
    },
    {
        "qid": "Q0211",
        "band": 1,
        "slot": "midbrain",
        "priority": 0.22,
        "allow_transformer": True,
        "label": "queue-cell-0211",
    },
    {
        "qid": "Q0212",
        "band": 2,
        "slot": "neo",
        "priority": 0.24,
        "allow_transformer": True,
        "label": "queue-cell-0212",
    },
    {
        "qid": "Q0213",
        "band": 3,
        "slot": "pfc",
        "priority": 0.26,
        "allow_transformer": False,
        "label": "queue-cell-0213",
    },
    {
        "qid": "Q0214",
        "band": 4,
        "slot": "midbrain",
        "priority": 0.28,
        "allow_transformer": True,
        "label": "queue-cell-0214",
    },
    {
        "qid": "Q0215",
        "band": 5,
        "slot": "neo",
        "priority": 0.3,
        "allow_transformer": True,
        "label": "queue-cell-0215",
    },
    {
        "qid": "Q0216",
        "band": 6,
        "slot": "pfc",
        "priority": 0.32,
        "allow_transformer": False,
        "label": "queue-cell-0216",
    },
    {
        "qid": "Q0217",
        "band": 7,
        "slot": "midbrain",
        "priority": 0.34,
        "allow_transformer": True,
        "label": "queue-cell-0217",
    },
    {
        "qid": "Q0218",
        "band": 8,
        "slot": "neo",
        "priority": 0.36,
        "allow_transformer": True,
        "label": "queue-cell-0218",
    },
    {
        "qid": "Q0219",
        "band": 9,
        "slot": "pfc",
        "priority": 0.38,
        "allow_transformer": False,
        "label": "queue-cell-0219",
    },
    {
        "qid": "Q0220",
        "band": 10,
        "slot": "midbrain",
        "priority": 0.4,
        "allow_transformer": True,
        "label": "queue-cell-0220",
    },
)

def cells_for_slot(slot: str) -> Tuple[Mapping[str, Any], ...]:
    return tuple(c for c in QUEUE_LATTICE if c["slot"] == slot)

def assert_pfc_queue_no_transformer() -> None:
    for c in cells_for_slot("pfc"):
        assert c["allow_transformer"] is False
