"""Sigil survival — fitted amalgam keeps composed text beside decode."""
from __future__ import annotations
from typing import Any, Mapping, Tuple

def survive(gen: str, composed: str, sep: str = " || ") -> str:
    if gen and composed:
        return f"{gen}{sep}{composed}"
    return gen or composed or ""

SIGIL_CASES: Tuple[Mapping[str, Any], ...] = (
    {
        "id": "sigil-0001",
        "gen": "gen-0001",
        "composed": "own-tape-0001",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0002",
        "gen": "gen-0002",
        "composed": "own-tape-0002",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0003",
        "gen": "gen-0003",
        "composed": "own-tape-0003",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0004",
        "gen": "gen-0004",
        "composed": "own-tape-0004",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0005",
        "gen": "gen-0005",
        "composed": "own-tape-0005",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0006",
        "gen": "gen-0006",
        "composed": "own-tape-0006",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0007",
        "gen": "gen-0007",
        "composed": "own-tape-0007",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0008",
        "gen": "gen-0008",
        "composed": "own-tape-0008",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0009",
        "gen": "gen-0009",
        "composed": "own-tape-0009",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0010",
        "gen": "gen-0010",
        "composed": "own-tape-0010",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0011",
        "gen": "gen-0011",
        "composed": "own-tape-0011",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0012",
        "gen": "gen-0012",
        "composed": "own-tape-0012",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0013",
        "gen": "gen-0013",
        "composed": "own-tape-0013",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0014",
        "gen": "gen-0014",
        "composed": "own-tape-0014",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0015",
        "gen": "gen-0015",
        "composed": "own-tape-0015",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0016",
        "gen": "gen-0016",
        "composed": "own-tape-0016",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0017",
        "gen": "gen-0017",
        "composed": "own-tape-0017",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0018",
        "gen": "gen-0018",
        "composed": "own-tape-0018",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0019",
        "gen": "gen-0019",
        "composed": "own-tape-0019",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0020",
        "gen": "gen-0020",
        "composed": "own-tape-0020",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0021",
        "gen": "gen-0021",
        "composed": "own-tape-0021",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0022",
        "gen": "gen-0022",
        "composed": "own-tape-0022",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0023",
        "gen": "gen-0023",
        "composed": "own-tape-0023",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0024",
        "gen": "gen-0024",
        "composed": "own-tape-0024",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0025",
        "gen": "gen-0025",
        "composed": "own-tape-0025",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0026",
        "gen": "gen-0026",
        "composed": "own-tape-0026",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0027",
        "gen": "gen-0027",
        "composed": "own-tape-0027",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0028",
        "gen": "gen-0028",
        "composed": "own-tape-0028",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0029",
        "gen": "gen-0029",
        "composed": "own-tape-0029",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0030",
        "gen": "gen-0030",
        "composed": "own-tape-0030",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0031",
        "gen": "gen-0031",
        "composed": "own-tape-0031",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0032",
        "gen": "gen-0032",
        "composed": "own-tape-0032",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0033",
        "gen": "gen-0033",
        "composed": "own-tape-0033",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0034",
        "gen": "gen-0034",
        "composed": "own-tape-0034",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0035",
        "gen": "gen-0035",
        "composed": "own-tape-0035",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0036",
        "gen": "gen-0036",
        "composed": "own-tape-0036",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0037",
        "gen": "gen-0037",
        "composed": "own-tape-0037",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0038",
        "gen": "gen-0038",
        "composed": "own-tape-0038",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0039",
        "gen": "gen-0039",
        "composed": "own-tape-0039",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0040",
        "gen": "gen-0040",
        "composed": "own-tape-0040",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0041",
        "gen": "gen-0041",
        "composed": "own-tape-0041",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0042",
        "gen": "gen-0042",
        "composed": "own-tape-0042",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0043",
        "gen": "gen-0043",
        "composed": "own-tape-0043",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0044",
        "gen": "gen-0044",
        "composed": "own-tape-0044",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0045",
        "gen": "gen-0045",
        "composed": "own-tape-0045",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0046",
        "gen": "gen-0046",
        "composed": "own-tape-0046",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0047",
        "gen": "gen-0047",
        "composed": "own-tape-0047",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0048",
        "gen": "gen-0048",
        "composed": "own-tape-0048",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0049",
        "gen": "gen-0049",
        "composed": "own-tape-0049",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0050",
        "gen": "gen-0050",
        "composed": "own-tape-0050",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0051",
        "gen": "gen-0051",
        "composed": "own-tape-0051",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0052",
        "gen": "gen-0052",
        "composed": "own-tape-0052",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0053",
        "gen": "gen-0053",
        "composed": "own-tape-0053",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0054",
        "gen": "gen-0054",
        "composed": "own-tape-0054",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0055",
        "gen": "gen-0055",
        "composed": "own-tape-0055",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0056",
        "gen": "gen-0056",
        "composed": "own-tape-0056",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0057",
        "gen": "gen-0057",
        "composed": "own-tape-0057",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0058",
        "gen": "gen-0058",
        "composed": "own-tape-0058",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0059",
        "gen": "gen-0059",
        "composed": "own-tape-0059",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0060",
        "gen": "gen-0060",
        "composed": "own-tape-0060",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0061",
        "gen": "gen-0061",
        "composed": "own-tape-0061",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0062",
        "gen": "gen-0062",
        "composed": "own-tape-0062",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0063",
        "gen": "gen-0063",
        "composed": "own-tape-0063",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0064",
        "gen": "gen-0064",
        "composed": "own-tape-0064",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0065",
        "gen": "gen-0065",
        "composed": "own-tape-0065",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0066",
        "gen": "gen-0066",
        "composed": "own-tape-0066",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0067",
        "gen": "gen-0067",
        "composed": "own-tape-0067",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0068",
        "gen": "gen-0068",
        "composed": "own-tape-0068",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0069",
        "gen": "gen-0069",
        "composed": "own-tape-0069",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0070",
        "gen": "gen-0070",
        "composed": "own-tape-0070",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0071",
        "gen": "gen-0071",
        "composed": "own-tape-0071",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0072",
        "gen": "gen-0072",
        "composed": "own-tape-0072",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0073",
        "gen": "gen-0073",
        "composed": "own-tape-0073",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0074",
        "gen": "gen-0074",
        "composed": "own-tape-0074",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0075",
        "gen": "gen-0075",
        "composed": "own-tape-0075",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0076",
        "gen": "gen-0076",
        "composed": "own-tape-0076",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0077",
        "gen": "gen-0077",
        "composed": "own-tape-0077",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0078",
        "gen": "gen-0078",
        "composed": "own-tape-0078",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0079",
        "gen": "gen-0079",
        "composed": "own-tape-0079",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0080",
        "gen": "gen-0080",
        "composed": "own-tape-0080",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0081",
        "gen": "gen-0081",
        "composed": "own-tape-0081",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0082",
        "gen": "gen-0082",
        "composed": "own-tape-0082",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0083",
        "gen": "gen-0083",
        "composed": "own-tape-0083",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0084",
        "gen": "gen-0084",
        "composed": "own-tape-0084",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0085",
        "gen": "gen-0085",
        "composed": "own-tape-0085",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0086",
        "gen": "gen-0086",
        "composed": "own-tape-0086",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0087",
        "gen": "gen-0087",
        "composed": "own-tape-0087",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0088",
        "gen": "gen-0088",
        "composed": "own-tape-0088",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0089",
        "gen": "gen-0089",
        "composed": "own-tape-0089",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0090",
        "gen": "gen-0090",
        "composed": "own-tape-0090",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0091",
        "gen": "gen-0091",
        "composed": "own-tape-0091",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0092",
        "gen": "gen-0092",
        "composed": "own-tape-0092",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0093",
        "gen": "gen-0093",
        "composed": "own-tape-0093",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0094",
        "gen": "gen-0094",
        "composed": "own-tape-0094",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0095",
        "gen": "gen-0095",
        "composed": "own-tape-0095",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0096",
        "gen": "gen-0096",
        "composed": "own-tape-0096",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0097",
        "gen": "gen-0097",
        "composed": "own-tape-0097",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0098",
        "gen": "gen-0098",
        "composed": "own-tape-0098",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0099",
        "gen": "gen-0099",
        "composed": "own-tape-0099",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0100",
        "gen": "gen-0100",
        "composed": "own-tape-0100",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0101",
        "gen": "gen-0101",
        "composed": "own-tape-0101",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0102",
        "gen": "gen-0102",
        "composed": "own-tape-0102",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0103",
        "gen": "gen-0103",
        "composed": "own-tape-0103",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0104",
        "gen": "gen-0104",
        "composed": "own-tape-0104",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0105",
        "gen": "gen-0105",
        "composed": "own-tape-0105",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0106",
        "gen": "gen-0106",
        "composed": "own-tape-0106",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0107",
        "gen": "gen-0107",
        "composed": "own-tape-0107",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0108",
        "gen": "gen-0108",
        "composed": "own-tape-0108",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0109",
        "gen": "gen-0109",
        "composed": "own-tape-0109",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0110",
        "gen": "gen-0110",
        "composed": "own-tape-0110",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0111",
        "gen": "gen-0111",
        "composed": "own-tape-0111",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0112",
        "gen": "gen-0112",
        "composed": "own-tape-0112",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0113",
        "gen": "gen-0113",
        "composed": "own-tape-0113",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0114",
        "gen": "gen-0114",
        "composed": "own-tape-0114",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0115",
        "gen": "gen-0115",
        "composed": "own-tape-0115",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0116",
        "gen": "gen-0116",
        "composed": "own-tape-0116",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0117",
        "gen": "gen-0117",
        "composed": "own-tape-0117",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0118",
        "gen": "gen-0118",
        "composed": "own-tape-0118",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0119",
        "gen": "gen-0119",
        "composed": "own-tape-0119",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0120",
        "gen": "gen-0120",
        "composed": "own-tape-0120",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0121",
        "gen": "gen-0121",
        "composed": "own-tape-0121",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0122",
        "gen": "gen-0122",
        "composed": "own-tape-0122",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0123",
        "gen": "gen-0123",
        "composed": "own-tape-0123",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0124",
        "gen": "gen-0124",
        "composed": "own-tape-0124",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0125",
        "gen": "gen-0125",
        "composed": "own-tape-0125",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0126",
        "gen": "gen-0126",
        "composed": "own-tape-0126",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0127",
        "gen": "gen-0127",
        "composed": "own-tape-0127",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0128",
        "gen": "gen-0128",
        "composed": "own-tape-0128",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0129",
        "gen": "gen-0129",
        "composed": "own-tape-0129",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0130",
        "gen": "gen-0130",
        "composed": "own-tape-0130",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0131",
        "gen": "gen-0131",
        "composed": "own-tape-0131",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0132",
        "gen": "gen-0132",
        "composed": "own-tape-0132",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0133",
        "gen": "gen-0133",
        "composed": "own-tape-0133",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0134",
        "gen": "gen-0134",
        "composed": "own-tape-0134",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0135",
        "gen": "gen-0135",
        "composed": "own-tape-0135",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0136",
        "gen": "gen-0136",
        "composed": "own-tape-0136",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0137",
        "gen": "gen-0137",
        "composed": "own-tape-0137",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0138",
        "gen": "gen-0138",
        "composed": "own-tape-0138",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0139",
        "gen": "gen-0139",
        "composed": "own-tape-0139",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0140",
        "gen": "gen-0140",
        "composed": "own-tape-0140",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0141",
        "gen": "gen-0141",
        "composed": "own-tape-0141",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0142",
        "gen": "gen-0142",
        "composed": "own-tape-0142",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0143",
        "gen": "gen-0143",
        "composed": "own-tape-0143",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0144",
        "gen": "gen-0144",
        "composed": "own-tape-0144",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0145",
        "gen": "gen-0145",
        "composed": "own-tape-0145",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0146",
        "gen": "gen-0146",
        "composed": "own-tape-0146",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0147",
        "gen": "gen-0147",
        "composed": "own-tape-0147",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0148",
        "gen": "gen-0148",
        "composed": "own-tape-0148",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0149",
        "gen": "gen-0149",
        "composed": "own-tape-0149",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0150",
        "gen": "gen-0150",
        "composed": "own-tape-0150",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0151",
        "gen": "gen-0151",
        "composed": "own-tape-0151",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0152",
        "gen": "gen-0152",
        "composed": "own-tape-0152",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0153",
        "gen": "gen-0153",
        "composed": "own-tape-0153",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0154",
        "gen": "gen-0154",
        "composed": "own-tape-0154",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0155",
        "gen": "gen-0155",
        "composed": "own-tape-0155",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0156",
        "gen": "gen-0156",
        "composed": "own-tape-0156",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0157",
        "gen": "gen-0157",
        "composed": "own-tape-0157",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0158",
        "gen": "gen-0158",
        "composed": "own-tape-0158",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0159",
        "gen": "gen-0159",
        "composed": "own-tape-0159",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0160",
        "gen": "gen-0160",
        "composed": "own-tape-0160",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0161",
        "gen": "gen-0161",
        "composed": "own-tape-0161",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0162",
        "gen": "gen-0162",
        "composed": "own-tape-0162",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0163",
        "gen": "gen-0163",
        "composed": "own-tape-0163",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0164",
        "gen": "gen-0164",
        "composed": "own-tape-0164",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0165",
        "gen": "gen-0165",
        "composed": "own-tape-0165",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0166",
        "gen": "gen-0166",
        "composed": "own-tape-0166",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0167",
        "gen": "gen-0167",
        "composed": "own-tape-0167",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0168",
        "gen": "gen-0168",
        "composed": "own-tape-0168",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0169",
        "gen": "gen-0169",
        "composed": "own-tape-0169",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0170",
        "gen": "gen-0170",
        "composed": "own-tape-0170",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0171",
        "gen": "gen-0171",
        "composed": "own-tape-0171",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0172",
        "gen": "gen-0172",
        "composed": "own-tape-0172",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0173",
        "gen": "gen-0173",
        "composed": "own-tape-0173",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0174",
        "gen": "gen-0174",
        "composed": "own-tape-0174",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0175",
        "gen": "gen-0175",
        "composed": "own-tape-0175",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0176",
        "gen": "gen-0176",
        "composed": "own-tape-0176",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0177",
        "gen": "gen-0177",
        "composed": "own-tape-0177",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0178",
        "gen": "gen-0178",
        "composed": "own-tape-0178",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0179",
        "gen": "gen-0179",
        "composed": "own-tape-0179",
        "expect_contains_composed": True,
    },
    {
        "id": "sigil-0180",
        "gen": "gen-0180",
        "composed": "own-tape-0180",
        "expect_contains_composed": True,
    },
)

def run_sigil_battery() -> int:
    ok = 0
    for row in SIGIL_CASES:
        body = survive(str(row["gen"]), str(row["composed"]))
        if str(row["composed"]) in body and str(row["gen"]) in body:
            ok += 1
    return ok
