"""Canonical AI mathematical reference substrate.

The package is deterministic, side-effect free, and authority-neutral.  It exists
to make numerical contracts explicit and to provide a correctness oracle for
optimized runtime implementations.
"""
from .autodiff import (
    Dual,
    cos as dual_cos,
    directional_derivative,
    exp as dual_exp,
    gradient,
    jacobian,
    log as dual_log,
    sigmoid as dual_sigmoid,
    sin as dual_sin,
    softplus as dual_softplus,
    sqrt as dual_sqrt,
    tanh as dual_tanh,
    value_and_gradient,
)
from .contracts import MathInvariantError, Matrix, Vector
from .integration import (
    ODEPoint,
    ODEReport,
    QuadratureReport,
    adaptive_simpson,
    rk4_integrate,
    rk4_step,
)
from .linear import (
    LinearSolveReport,
    cosine_similarity,
    dot,
    l2_norm,
    matmul,
    matvec,
    solve_linear_system,
    transpose,
)
from .numerics import (
    almost_equal,
    compensated_sum,
    logsumexp,
    normalize_log_weights,
    relative_error,
    stable_mean,
    stable_softmax,
)
from .optimization import (
    OptimizationConfig,
    OptimizationResult,
    OptimizationStep,
    finite_difference_gradient,
    project,
    projected_gradient_descent,
)
from .probability import (
    cross_entropy,
    effective_sample_size,
    entropy,
    jensen_shannon_divergence,
    kl_divergence,
    normalize_distribution,
    weighted_moments,
)
from .spectral import (
    EigenReport,
    SpectrumBin,
    dominant_eigenpair_symmetric,
    dominant_frequency,
    periodogram,
    spectral_power_fraction,
)
from .statistics import (
    MomentReport,
    correlation,
    covariance,
    covariance_matrix,
    median,
    median_absolute_deviation,
    moments,
    quantile,
    standardize,
)
from .tensor import (
    DenseTensor,
    add as tensor_add,
    broadcast_shape,
    divide as tensor_divide,
    multiply as tensor_multiply,
    reduce_mean as tensor_reduce_mean,
    reduce_sum as tensor_reduce_sum,
    subtract as tensor_subtract,
    tensor_zip,
)
from .validation import MathAuditCase, MathAuditReport, audit_runtime_kernels

__all__ = [
    "MathInvariantError",
    "Matrix",
    "Vector",
    "Dual",
    "dual_cos",
    "directional_derivative",
    "dual_exp",
    "gradient",
    "jacobian",
    "dual_log",
    "dual_sigmoid",
    "dual_sin",
    "dual_softplus",
    "dual_sqrt",
    "dual_tanh",
    "value_and_gradient",
    "ODEPoint",
    "ODEReport",
    "QuadratureReport",
    "adaptive_simpson",
    "rk4_integrate",
    "rk4_step",
    "LinearSolveReport",
    "cosine_similarity",
    "dot",
    "l2_norm",
    "matmul",
    "matvec",
    "solve_linear_system",
    "transpose",
    "almost_equal",
    "compensated_sum",
    "logsumexp",
    "normalize_log_weights",
    "relative_error",
    "stable_mean",
    "stable_softmax",
    "OptimizationConfig",
    "OptimizationResult",
    "OptimizationStep",
    "finite_difference_gradient",
    "project",
    "projected_gradient_descent",
    "cross_entropy",
    "effective_sample_size",
    "entropy",
    "jensen_shannon_divergence",
    "kl_divergence",
    "normalize_distribution",
    "weighted_moments",
    "EigenReport",
    "SpectrumBin",
    "dominant_eigenpair_symmetric",
    "dominant_frequency",
    "periodogram",
    "spectral_power_fraction",
    "MomentReport",
    "correlation",
    "covariance",
    "covariance_matrix",
    "median",
    "median_absolute_deviation",
    "moments",
    "quantile",
    "standardize",
    "DenseTensor",
    "tensor_add",
    "broadcast_shape",
    "tensor_divide",
    "tensor_multiply",
    "tensor_reduce_mean",
    "tensor_reduce_sum",
    "tensor_subtract",
    "tensor_zip",
    "MathAuditCase",
    "MathAuditReport",
    "audit_runtime_kernels",
]
