"""Canonical AI mathematical reference substrate.

The package is deterministic, side-effect free, and authority-neutral.  It exists
to make numerical contracts explicit and to provide a correctness oracle for
optimized runtime implementations.
"""
from .autodiff import (
    Dual,
    cos as dual_cos,
    directional_derivative,
    exp as dual_exp,
    gradient,
    jacobian,
    log as dual_log,
    sigmoid as dual_sigmoid,
    sin as dual_sin,
    softplus as dual_softplus,
    sqrt as dual_sqrt,
    tanh as dual_tanh,
    value_and_gradient,
)
from .approximation import (
    barycentric_interpolate,
    barycentric_weights,
    chebyshev_nodes,
    horner,
    newton_divided_differences,
    newton_interpolate,
    piecewise_linear_interpolate,
)
from .calculus2 import (
    HessianReport,
    finite_difference_hessian,
    gradient_norm,
    hessian_vector_product,
    quadratic_model_change,
)
from .calibration_metrics import (
    CalibrationBin,
    CalibrationMetricReport,
    binary_calibration_report,
    top_label_calibration_report,
)
from .contracts import MathInvariantError, Matrix, Vector
from .decompositions import (
    CholeskyReport,
    LeastSquaresReport,
    QRReport,
    cholesky_decompose,
    least_squares,
    qr_decompose,
    solve_cholesky,
)
from .differentiation import (
    DerivativeReport,
    GradientCheckReport,
    JacobianReport,
    check_gradient,
    finite_difference_jacobian,
    richardson_derivative,
)
from .distributions import (
    bernoulli_log_pmf,
    gaussian_mixture_log_density,
    normal_cdf,
    normal_log_pdf,
    normal_pdf,
    normal_quantile,
    poisson_log_pmf,
    student_t_log_pdf,
)
from .eigensystems import (
    PCAReport,
    SymmetricEigensystemReport,
    principal_components,
    symmetric_eigensystem,
)
from .geometry import (
    ProjectionReport,
    angular_distance,
    barycentric_triangle,
    euclidean_distance,
    project_onto_subspace,
    project_probability_simplex,
    squared_distance,
)
from .graph import (
    StationaryDistributionReport,
    combinatorial_laplacian,
    degree_vector,
    graph_quadratic_form,
    normalized_laplacian,
    random_walk_matrix,
    stationary_distribution,
    validate_transition_matrix,
)
from .information_geometry import (
    bhattacharyya_coefficient,
    bhattacharyya_distance,
    fisher_rao_distance,
    hellinger_distance,
    mahalanobis_distance,
    total_variation_distance,
)
from .integration2 import AdaptiveODEPoint, AdaptiveODEReport, adaptive_rk45
from .integration import (
    ODEPoint,
    ODEReport,
    QuadratureReport,
    adaptive_simpson,
    rk4_integrate,
    rk4_step,
)
from .linear import (
    LinearSolveReport,
    cosine_similarity,
    dot,
    l2_norm,
    matmul,
    matvec,
    solve_linear_system,
    transpose,
)
from .kernels import (
    centered_gram,
    gram_matrix,
    laplacian_kernel,
    linear_kernel,
    maximum_mean_discrepancy_squared,
    polynomial_kernel,
    rbf_kernel,
)
from .losses import (
    binary_cross_entropy,
    brier_score,
    cross_entropy_from_logits,
    huber_loss,
    label_smoothed_cross_entropy_from_logits,
    mean_absolute_error,
    mean_squared_error,
    perplexity,
)
from .numerics import (
    almost_equal,
    compensated_sum,
    logsumexp,
    normalize_log_weights,
    relative_error,
    stable_mean,
    stable_softmax,
)
from .optimization2 import (
    AdvancedOptimizationResult,
    AdvancedOptimizationStep,
    bfgs,
    damped_newton,
)
from .optimization import (
    OptimizationConfig,
    OptimizationResult,
    OptimizationStep,
    finite_difference_gradient,
    project,
    projected_gradient_descent,
)
from .probability import (
    cross_entropy,
    effective_sample_size,
    entropy,
    jensen_shannon_divergence,
    kl_divergence,
    normalize_distribution,
    weighted_moments,
)
from .sampling import (
    MonteCarloReport,
    SplitMix64,
    halton_point,
    monte_carlo_unit_cube,
    radical_inverse,
    systematic_resample,
)
from .sparse import CSRMatrix, sparse_dense_matmul
from .sequence import (
    DTWReport,
    discrete_frechet_distance,
    dynamic_time_warping,
    levenshtein_distance,
    normalized_levenshtein_distance,
)
from .solvers import (
    ConjugateGradientReport,
    RootReport,
    bisection_root,
    bracketed_newton_root,
    conjugate_gradient,
)
from .spectral import (
    EigenReport,
    SpectrumBin,
    dominant_eigenpair_symmetric,
    dominant_frequency,
    periodogram,
    spectral_power_fraction,
)
from .statistics import (
    MomentReport,
    correlation,
    covariance,
    covariance_matrix,
    median,
    median_absolute_deviation,
    moments,
    quantile,
    standardize,
)
from .tensor import (
    DenseTensor,
    add as tensor_add,
    broadcast_shape,
    divide as tensor_divide,
    multiply as tensor_multiply,
    reduce_mean as tensor_reduce_mean,
    reduce_sum as tensor_reduce_sum,
    subtract as tensor_subtract,
    tensor_zip,
)
from .transforms import (
    autocorrelation,
    convolution,
    dft,
    fft_radix2,
    inverse_dft,
    inverse_fft_radix2,
)
from .validation import MathAuditCase, MathAuditReport, audit_runtime_kernels

__all__ = [
    "barycentric_interpolate",
    "barycentric_weights",
    "chebyshev_nodes",
    "horner",
    "newton_divided_differences",
    "newton_interpolate",
    "piecewise_linear_interpolate",
    "HessianReport",
    "finite_difference_hessian",
    "gradient_norm",
    "hessian_vector_product",
    "quadratic_model_change",
    "CalibrationBin",
    "CalibrationMetricReport",
    "binary_calibration_report",
    "top_label_calibration_report",
    "MathInvariantError",
    "Matrix",
    "Vector",
    "Dual",
    "dual_cos",
    "directional_derivative",
    "dual_exp",
    "gradient",
    "jacobian",
    "dual_log",
    "dual_sigmoid",
    "dual_sin",
    "dual_softplus",
    "dual_sqrt",
    "dual_tanh",
    "value_and_gradient",
    "CholeskyReport",
    "LeastSquaresReport",
    "QRReport",
    "cholesky_decompose",
    "least_squares",
    "qr_decompose",
    "solve_cholesky",
    "DerivativeReport",
    "GradientCheckReport",
    "JacobianReport",
    "check_gradient",
    "finite_difference_jacobian",
    "richardson_derivative",
    "bernoulli_log_pmf",
    "gaussian_mixture_log_density",
    "normal_cdf",
    "normal_log_pdf",
    "normal_pdf",
    "normal_quantile",
    "poisson_log_pmf",
    "student_t_log_pdf",
    "PCAReport",
    "SymmetricEigensystemReport",
    "principal_components",
    "symmetric_eigensystem",
    "ProjectionReport",
    "angular_distance",
    "barycentric_triangle",
    "euclidean_distance",
    "project_onto_subspace",
    "project_probability_simplex",
    "squared_distance",
    "StationaryDistributionReport",
    "combinatorial_laplacian",
    "degree_vector",
    "graph_quadratic_form",
    "normalized_laplacian",
    "random_walk_matrix",
    "stationary_distribution",
    "validate_transition_matrix",
    "bhattacharyya_coefficient",
    "bhattacharyya_distance",
    "fisher_rao_distance",
    "hellinger_distance",
    "mahalanobis_distance",
    "total_variation_distance",
    "AdaptiveODEPoint",
    "AdaptiveODEReport",
    "adaptive_rk45",
    "ODEPoint",
    "ODEReport",
    "QuadratureReport",
    "adaptive_simpson",
    "rk4_integrate",
    "rk4_step",
    "LinearSolveReport",
    "cosine_similarity",
    "dot",
    "l2_norm",
    "matmul",
    "matvec",
    "solve_linear_system",
    "transpose",
    "centered_gram",
    "gram_matrix",
    "laplacian_kernel",
    "linear_kernel",
    "maximum_mean_discrepancy_squared",
    "polynomial_kernel",
    "rbf_kernel",
    "binary_cross_entropy",
    "brier_score",
    "cross_entropy_from_logits",
    "huber_loss",
    "label_smoothed_cross_entropy_from_logits",
    "mean_absolute_error",
    "mean_squared_error",
    "perplexity",
    "almost_equal",
    "compensated_sum",
    "logsumexp",
    "normalize_log_weights",
    "relative_error",
    "stable_mean",
    "stable_softmax",
    "AdvancedOptimizationResult",
    "AdvancedOptimizationStep",
    "bfgs",
    "damped_newton",
    "OptimizationConfig",
    "OptimizationResult",
    "OptimizationStep",
    "finite_difference_gradient",
    "project",
    "projected_gradient_descent",
    "cross_entropy",
    "effective_sample_size",
    "entropy",
    "jensen_shannon_divergence",
    "kl_divergence",
    "normalize_distribution",
    "weighted_moments",
    "MonteCarloReport",
    "SplitMix64",
    "halton_point",
    "monte_carlo_unit_cube",
    "radical_inverse",
    "systematic_resample",
    "DTWReport",
    "discrete_frechet_distance",
    "dynamic_time_warping",
    "levenshtein_distance",
    "normalized_levenshtein_distance",
    "CSRMatrix",
    "sparse_dense_matmul",
    "ConjugateGradientReport",
    "RootReport",
    "bisection_root",
    "bracketed_newton_root",
    "conjugate_gradient",
    "EigenReport",
    "SpectrumBin",
    "dominant_eigenpair_symmetric",
    "dominant_frequency",
    "periodogram",
    "spectral_power_fraction",
    "MomentReport",
    "correlation",
    "covariance",
    "covariance_matrix",
    "median",
    "median_absolute_deviation",
    "moments",
    "quantile",
    "standardize",
    "DenseTensor",
    "tensor_add",
    "broadcast_shape",
    "tensor_divide",
    "tensor_multiply",
    "tensor_reduce_mean",
    "tensor_reduce_sum",
    "tensor_subtract",
    "tensor_zip",
    "autocorrelation",
    "convolution",
    "dft",
    "fft_radix2",
    "inverse_dft",
    "inverse_fft_radix2",
    "MathAuditCase",
    "MathAuditReport",
    "audit_runtime_kernels",
]
