"""Canonical AI mathematical reference substrate.

The package is deterministic, side-effect free, and authority-neutral.  It exists
to make numerical contracts explicit and to provide a correctness oracle for
optimized runtime implementations.
"""
from .autodiff import (
    Dual,
    cos as dual_cos,
    directional_derivative,
    exp as dual_exp,
    gradient,
    jacobian,
    log as dual_log,
    sigmoid as dual_sigmoid,
    sin as dual_sin,
    softplus as dual_softplus,
    sqrt as dual_sqrt,
    tanh as dual_tanh,
    value_and_gradient,
)
from .approximation import (
    barycentric_interpolate,
    barycentric_weights,
    chebyshev_nodes,
    horner,
    newton_divided_differences,
    newton_interpolate,
    piecewise_linear_interpolate,
)
from .bezier import BezierCurve
from .bsplines import (
    BSplineBasisReport,
    bspline_basis,
    bspline_curve,
    clamped_uniform_knots,
)
from .calculus2 import (
    HessianReport,
    finite_difference_hessian,
    gradient_norm,
    hessian_vector_product,
    quadratic_model_change,
)
from .bayes import (
    BetaBinomialPosterior,
    DirichletMultinomialPosterior,
    NormalInverseGammaPosterior,
    NormalNormalPosterior,
    beta_binomial_posterior,
    dirichlet_multinomial_posterior,
    normal_inverse_gamma_posterior,
    normal_normal_posterior,
)
from .calibration_metrics import (
    CalibrationBin,
    CalibrationMetricReport,
    binary_calibration_report,
    top_label_calibration_report,
)
from .combinatorics import (
    binomial_coefficient,
    binomial_log_pmf,
    hypergeometric_log_pmf,
    log_binomial_coefficient,
    log_factorial,
    multinomial_log_pmf,
)
from .covariance_shrinkage import (
    CovarianceShrinkageReport,
    oracle_approximating_shrinkage,
    shrink_covariance,
)
from .conditioning import (
    BackwardErrorReport,
    ConditionReport,
    condition_number,
    linear_backward_error,
    matrix_infinity_norm,
    matrix_max_norm,
    matrix_one_norm,
)
from .contracts import MathInvariantError, Matrix, Vector
from .cosine_transforms import dct2, dct_ii, dct_iv, inverse_dct2, inverse_dct_ii
from .decompositions import (
    CholeskyReport,
    LeastSquaresReport,
    QRReport,
    cholesky_decompose,
    least_squares,
    qr_decompose,
    solve_cholesky,
)
from .differentiation import (
    DerivativeReport,
    GradientCheckReport,
    JacobianReport,
    check_gradient,
    finite_difference_jacobian,
    richardson_derivative,
)
from .continuous_distributions import (
    beta_cdf,
    beta_log_pdf,
    dirichlet_log_pdf,
    gamma_cdf,
    gamma_log_pdf,
    log_beta,
    regularized_beta,
    regularized_gamma_p,
)
from .density import (
    EmpiricalCDF,
    HistogramReport,
    empirical_cdf,
    gaussian_kde_density,
    histogram,
    silverman_bandwidth,
)
from .derivative_free import (
    GoldenSectionReport,
    NelderMeadReport,
    golden_section_minimize,
    nelder_mead,
)
from .distances import (
    bray_curtis_distance,
    canberra_distance,
    chebyshev_distance,
    cosine_distance,
    dice_distance,
    jaccard_distance,
    manhattan_distance,
    minkowski_distance,
    pairwise_distance_matrix,
    weighted_jaccard_distance,
)
from .distributions import (
    bernoulli_log_pmf,
    gaussian_mixture_log_density,
    normal_cdf,
    normal_log_pdf,
    normal_pdf,
    normal_quantile,
    poisson_log_pmf,
    student_t_log_pdf,
)
from .entropy2 import (
    conditional_entropy_y_given_x,
    gini_impurity,
    mutual_information,
    renyi_entropy,
    tsallis_entropy,
    variation_of_information,
)
from .eigensystems import (
    PCAReport,
    SymmetricEigensystemReport,
    principal_components,
    symmetric_eigensystem,
)
from .finite_element1d import (
    FEMPoissonReport,
    LinearFEMAssembly,
    assemble_linear_fem_1d,
    solve_poisson_fem_1d,
)
from .finite_difference2d import curl_z_2d, divergence_2d, gradient_2d, laplacian_2d
from .finite_difference import (
    Poisson1DReport,
    explicit_diffusion_stable_step,
    first_derivative_grid,
    second_derivative_grid,
    solve_poisson_dirichlet_1d,
)
from .geometry2 import (
    convex_hull,
    orientation,
    point_in_polygon,
    polygon_area,
    polygon_centroid,
    signed_polygon_area,
)
from .geometry import (
    ProjectionReport,
    angular_distance,
    barycentric_triangle,
    euclidean_distance,
    project_onto_subspace,
    project_probability_simplex,
    squared_distance,
)
from .graph import (
    StationaryDistributionReport,
    combinatorial_laplacian,
    degree_vector,
    graph_quadratic_form,
    normalized_laplacian,
    random_walk_matrix,
    stationary_distribution,
    validate_transition_matrix,
)
from .iterative_linear import (
    StationaryIterationReport,
    gauss_seidel_solve,
    jacobi_solve,
    sor_solve,
)
from .information_geometry import (
    bhattacharyya_coefficient,
    bhattacharyya_distance,
    fisher_rao_distance,
    hellinger_distance,
    mahalanobis_distance,
    total_variation_distance,
)
from .interpolation_nd import bilinear_gradient, bilinear_interpolate, trilinear_interpolate
from .interval import Interval, interval_hull, interval_intersection
from .inference_tests import (
    ANOVAReport,
    MannWhitneyReport,
    WelchTReport,
    mann_whitney_u,
    one_way_anova,
    welch_t_test,
)
from .integration2 import AdaptiveODEPoint, AdaptiveODEReport, adaptive_rk45
from .integration import (
    ODEPoint,
    ODEReport,
    QuadratureReport,
    adaptive_simpson,
    rk4_integrate,
    rk4_step,
)
from .ldlt import LDLTReport, ldlt_decompose, ldlt_solve
from .linear import (
    LinearSolveReport,
    cosine_similarity,
    dot,
    l2_norm,
    matmul,
    matvec,
    solve_linear_system,
    transpose,
)
from .lu import InverseReport, LUReport, determinant, lu_decompose, lu_solve, matrix_inverse
from .krylov import ArnoldiReport, GMRESReport, arnoldi_iteration, gmres
from .isotonic import IsotonicBlock, IsotonicReport, isotonic_regression
from .kernels import (
    centered_gram,
    gram_matrix,
    laplacian_kernel,
    linear_kernel,
    maximum_mean_discrepancy_squared,
    polynomial_kernel,
    rbf_kernel,
)
from .low_rank import (
    LowRankApproximationReport,
    rank_for_retained_energy,
    truncated_svd_approximation,
)
from .losses import (
    binary_cross_entropy,
    brier_score,
    cross_entropy_from_logits,
    huber_loss,
    label_smoothed_cross_entropy_from_logits,
    mean_absolute_error,
    mean_squared_error,
    perplexity,
)
from .monotone import MonotoneCubicInterpolator, monotone_cubic_interpolator
from .numerics import (
    almost_equal,
    compensated_sum,
    logsumexp,
    normalize_log_weights,
    relative_error,
    stable_mean,
    stable_softmax,
)
from .online_stats import RunningCovariance, RunningMoments
from .hyperdual import (
    HyperDual,
    HyperDualHessianReport,
    cos as hyperdual_cos,
    exp as hyperdual_exp,
    log as hyperdual_log,
    second_derivative as hyperdual_second_derivative,
    sin as hyperdual_sin,
    sqrt as hyperdual_sqrt,
    tanh as hyperdual_tanh,
    value_gradient_hessian,
)
from .hypothesis import (
    ChiSquareReport,
    TwoSampleKSReport,
    chi_square_goodness_of_fit,
    two_sample_ks,
)
from .optimization2 import (
    AdvancedOptimizationResult,
    AdvancedOptimizationStep,
    bfgs,
    damped_newton,
)
from .optimization import (
    OptimizationConfig,
    OptimizationResult,
    OptimizationStep,
    finite_difference_gradient,
    project,
    projected_gradient_descent,
)
from .proximal import (
    group_l2_shrinkage,
    project_l1_ball,
    project_l2_ball,
    project_linf_ball,
    proximal_elastic_net,
    soft_threshold,
    soft_threshold_vector,
)
from .polynomials import (
    PolynomialRootsReport,
    polynomial_add,
    polynomial_derivative,
    polynomial_divmod,
    polynomial_evaluate,
    polynomial_integral,
    polynomial_multiply,
    polynomial_roots,
)
from .orthogonal import (
    GivensRotation,
    HouseholderReflection,
    apply_givens_pair,
    apply_householder_left,
    apply_householder_vector,
    givens_rotation,
    householder_reflection,
    orthogonal_reflection_matrix,
)
from .orthogonal_polynomials import (
    ChebyshevSeries,
    chebyshev_t,
    clenshaw_chebyshev,
    fit_chebyshev_series,
    legendre_p,
    probabilists_hermite,
)
from .probability import (
    cross_entropy,
    effective_sample_size,
    entropy,
    jensen_shannon_divergence,
    kl_divergence,
    normalize_distribution,
    weighted_moments,
)
from .quadrature2 import (
    GaussLegendreRule,
    GaussianQuadratureReport,
    gauss_legendre_integrate,
    gauss_legendre_rule,
)
from .resampling import BootstrapReport, JackknifeReport, bootstrap, jackknife
from .rank_statistics import (
    KendallTauReport,
    kendall_tau_b,
    rank_biserial_correlation,
    rankdata,
    spearman_correlation,
)
from .robust import (
    HuberLocationReport,
    huber_location,
    modified_z_scores,
    robust_interquartile_range,
    robust_scale_mad,
    trimmed_mean,
    winsorized_mean,
)
from .rotations import (
    Quaternion,
    quaternion_from_axis_angle,
    quaternion_multiply,
    quaternion_rotate_vector,
    quaternion_slerp,
    quaternion_to_rotation_matrix,
)
from .sampling import (
    MonteCarloReport,
    SplitMix64,
    halton_point,
    monte_carlo_unit_cube,
    radical_inverse,
    systematic_resample,
)
from .sparse import CSRMatrix, sparse_dense_matmul
from .sequence import (
    DTWReport,
    discrete_frechet_distance,
    dynamic_time_warping,
    levenshtein_distance,
    normalized_levenshtein_distance,
)
from .symmetric_functions import (
    SymmetricMatrixFunctionReport,
    symmetric_matrix_exp,
    symmetric_matrix_inverse_sqrt,
    symmetric_matrix_log,
    symmetric_matrix_sqrt,
)
from .svd import (
    PseudoinverseReport,
    SVDReport,
    least_norm_solve,
    pseudoinverse,
    singular_value_decomposition,
)
from .stochastic import (
    HittingTimeReport,
    absorbing_probability,
    expected_hitting_times,
    propagate_distribution,
    transition_power,
)
from .matrix_algebra2 import (
    SLogDetReport,
    frobenius_norm,
    identity_matrix,
    kronecker_product,
    matrix_power,
    matrix_trace,
    slogdet,
)
from .matrix_equations import (
    LyapunovReport,
    SylvesterReport,
    solve_continuous_lyapunov,
    solve_sylvester,
)
from .matrix_functions import MatrixExponentialReport, matrix_exponential
from .matrix_structures import (
    GershgorinDisc,
    circulant,
    diagonal_dominance_margins,
    gershgorin_discs,
    is_strictly_diagonally_dominant,
    symmetrize,
    toeplitz,
)
from .matrix_updates import (
    CholeskyUpdateReport,
    cholesky_factor_after_rank_one_update,
    cholesky_rank_one_update,
    symmetric_rank_one_update,
)
from .matching import AssignmentReport, minimum_cost_assignment
from .solvers import (
    ConjugateGradientReport,
    RootReport,
    bisection_root,
    bracketed_newton_root,
    conjugate_gradient,
)
from .spectral import (
    EigenReport,
    SpectrumBin,
    dominant_eigenpair_symmetric,
    dominant_frequency,
    periodogram,
    spectral_power_fraction,
)
from .signal2 import (
    CrossCorrelationReport,
    blackman_window,
    cross_correlation,
    hamming_window,
    hann_window,
    linear_detrend,
    moving_average,
    moving_rms,
)
from .smoothing import (
    LocalPolynomialReport,
    local_polynomial_smooth,
    savitzky_golay_derivative,
    savitzky_golay_smooth,
)
from .special_functions import (
    inverse_softplus,
    log1mexp,
    log_cosh,
    logaddexp,
    logsubexp,
    stable_logit,
    stable_sigmoid,
    stable_softplus,
)
from .splines import NaturalCubicSpline, natural_cubic_spline
from .statistics import (
    MomentReport,
    correlation,
    covariance,
    covariance_matrix,
    median,
    median_absolute_deviation,
    moments,
    quantile,
    standardize,
)
from .tensor_contract import mode_product, tensor_contract, tensor_dot, tensor_outer
from .tensor import (
    DenseTensor,
    add as tensor_add,
    broadcast_shape,
    divide as tensor_divide,
    multiply as tensor_multiply,
    reduce_mean as tensor_reduce_mean,
    reduce_sum as tensor_reduce_sum,
    subtract as tensor_subtract,
    tensor_zip,
)
from .tridiagonal import TridiagonalSolveReport, solve_tridiagonal, tridiagonal_matvec
from .transport import SinkhornReport, sinkhorn_transport, wasserstein_distance_1d
from .transforms import (
    autocorrelation,
    convolution,
    dft,
    fft_radix2,
    inverse_dft,
    inverse_fft_radix2,
)
from .whitening import WhiteningReport, whiten
from .wavelets import (
    haar_transform,
    hadamard_transform,
    inverse_haar_transform,
    inverse_hadamard_transform,
)
from .validation import MathAuditCase, MathAuditReport, audit_runtime_kernels

__all__ = [
    "barycentric_interpolate",
    "barycentric_weights",
    "chebyshev_nodes",
    "horner",
    "newton_divided_differences",
    "newton_interpolate",
    "piecewise_linear_interpolate",
    "BezierCurve",
    "BSplineBasisReport",
    "bspline_basis",
    "bspline_curve",
    "clamped_uniform_knots",
    "HessianReport",
    "finite_difference_hessian",
    "gradient_norm",
    "hessian_vector_product",
    "quadratic_model_change",
    "BetaBinomialPosterior",
    "DirichletMultinomialPosterior",
    "NormalInverseGammaPosterior",
    "NormalNormalPosterior",
    "beta_binomial_posterior",
    "dirichlet_multinomial_posterior",
    "normal_inverse_gamma_posterior",
    "normal_normal_posterior",
    "CalibrationBin",
    "CalibrationMetricReport",
    "binary_calibration_report",
    "top_label_calibration_report",
    "binomial_coefficient",
    "binomial_log_pmf",
    "hypergeometric_log_pmf",
    "log_binomial_coefficient",
    "log_factorial",
    "multinomial_log_pmf",
    "CovarianceShrinkageReport",
    "oracle_approximating_shrinkage",
    "shrink_covariance",
    "BackwardErrorReport",
    "ConditionReport",
    "condition_number",
    "linear_backward_error",
    "matrix_infinity_norm",
    "matrix_max_norm",
    "matrix_one_norm",
    "MathInvariantError",
    "Matrix",
    "Vector",
    "Dual",
    "dual_cos",
    "directional_derivative",
    "dual_exp",
    "gradient",
    "jacobian",
    "dual_log",
    "dual_sigmoid",
    "dual_sin",
    "dual_softplus",
    "dual_sqrt",
    "dual_tanh",
    "value_and_gradient",
    "dct2",
    "dct_ii",
    "dct_iv",
    "inverse_dct2",
    "inverse_dct_ii",
    "CholeskyReport",
    "LeastSquaresReport",
    "QRReport",
    "cholesky_decompose",
    "least_squares",
    "qr_decompose",
    "solve_cholesky",
    "DerivativeReport",
    "GradientCheckReport",
    "JacobianReport",
    "check_gradient",
    "finite_difference_jacobian",
    "richardson_derivative",
    "beta_cdf",
    "beta_log_pdf",
    "dirichlet_log_pdf",
    "gamma_cdf",
    "gamma_log_pdf",
    "log_beta",
    "regularized_beta",
    "regularized_gamma_p",
    "EmpiricalCDF",
    "HistogramReport",
    "empirical_cdf",
    "gaussian_kde_density",
    "histogram",
    "silverman_bandwidth",
    "GoldenSectionReport",
    "NelderMeadReport",
    "golden_section_minimize",
    "nelder_mead",
    "bray_curtis_distance",
    "canberra_distance",
    "chebyshev_distance",
    "cosine_distance",
    "dice_distance",
    "jaccard_distance",
    "manhattan_distance",
    "minkowski_distance",
    "pairwise_distance_matrix",
    "weighted_jaccard_distance",
    "bernoulli_log_pmf",
    "gaussian_mixture_log_density",
    "normal_cdf",
    "normal_log_pdf",
    "normal_pdf",
    "normal_quantile",
    "poisson_log_pmf",
    "student_t_log_pdf",
    "conditional_entropy_y_given_x",
    "gini_impurity",
    "mutual_information",
    "renyi_entropy",
    "tsallis_entropy",
    "variation_of_information",
    "PCAReport",
    "SymmetricEigensystemReport",
    "principal_components",
    "symmetric_eigensystem",
    "FEMPoissonReport",
    "LinearFEMAssembly",
    "assemble_linear_fem_1d",
    "solve_poisson_fem_1d",
    "curl_z_2d",
    "divergence_2d",
    "gradient_2d",
    "laplacian_2d",
    "Poisson1DReport",
    "explicit_diffusion_stable_step",
    "first_derivative_grid",
    "second_derivative_grid",
    "solve_poisson_dirichlet_1d",
    "convex_hull",
    "orientation",
    "point_in_polygon",
    "polygon_area",
    "polygon_centroid",
    "signed_polygon_area",
    "ProjectionReport",
    "angular_distance",
    "barycentric_triangle",
    "euclidean_distance",
    "project_onto_subspace",
    "project_probability_simplex",
    "squared_distance",
    "StationaryDistributionReport",
    "combinatorial_laplacian",
    "degree_vector",
    "graph_quadratic_form",
    "normalized_laplacian",
    "random_walk_matrix",
    "stationary_distribution",
    "validate_transition_matrix",
    "StationaryIterationReport",
    "gauss_seidel_solve",
    "jacobi_solve",
    "sor_solve",
    "bhattacharyya_coefficient",
    "bhattacharyya_distance",
    "fisher_rao_distance",
    "hellinger_distance",
    "mahalanobis_distance",
    "total_variation_distance",
    "bilinear_gradient",
    "bilinear_interpolate",
    "trilinear_interpolate",
    "Interval",
    "interval_hull",
    "interval_intersection",
    "ANOVAReport",
    "MannWhitneyReport",
    "WelchTReport",
    "mann_whitney_u",
    "one_way_anova",
    "welch_t_test",
    "AdaptiveODEPoint",
    "AdaptiveODEReport",
    "adaptive_rk45",
    "ODEPoint",
    "ODEReport",
    "QuadratureReport",
    "adaptive_simpson",
    "rk4_integrate",
    "rk4_step",
    "LDLTReport",
    "ldlt_decompose",
    "ldlt_solve",
    "LinearSolveReport",
    "cosine_similarity",
    "dot",
    "l2_norm",
    "matmul",
    "matvec",
    "solve_linear_system",
    "transpose",
    "InverseReport",
    "LUReport",
    "determinant",
    "lu_decompose",
    "lu_solve",
    "matrix_inverse",
    "ArnoldiReport",
    "GMRESReport",
    "arnoldi_iteration",
    "gmres",
    "IsotonicBlock",
    "IsotonicReport",
    "isotonic_regression",
    "centered_gram",
    "gram_matrix",
    "laplacian_kernel",
    "linear_kernel",
    "maximum_mean_discrepancy_squared",
    "polynomial_kernel",
    "rbf_kernel",
    "LowRankApproximationReport",
    "rank_for_retained_energy",
    "truncated_svd_approximation",
    "binary_cross_entropy",
    "brier_score",
    "cross_entropy_from_logits",
    "huber_loss",
    "label_smoothed_cross_entropy_from_logits",
    "mean_absolute_error",
    "mean_squared_error",
    "perplexity",
    "MonotoneCubicInterpolator",
    "monotone_cubic_interpolator",
    "almost_equal",
    "compensated_sum",
    "logsumexp",
    "normalize_log_weights",
    "relative_error",
    "stable_mean",
    "stable_softmax",
    "RunningCovariance",
    "RunningMoments",
    "HyperDual",
    "HyperDualHessianReport",
    "hyperdual_cos",
    "hyperdual_exp",
    "hyperdual_log",
    "hyperdual_second_derivative",
    "hyperdual_sin",
    "hyperdual_sqrt",
    "hyperdual_tanh",
    "value_gradient_hessian",
    "ChiSquareReport",
    "TwoSampleKSReport",
    "chi_square_goodness_of_fit",
    "two_sample_ks",
    "AdvancedOptimizationResult",
    "AdvancedOptimizationStep",
    "bfgs",
    "damped_newton",
    "OptimizationConfig",
    "OptimizationResult",
    "OptimizationStep",
    "finite_difference_gradient",
    "project",
    "projected_gradient_descent",
    "group_l2_shrinkage",
    "project_l1_ball",
    "project_l2_ball",
    "project_linf_ball",
    "proximal_elastic_net",
    "soft_threshold",
    "soft_threshold_vector",
    "PolynomialRootsReport",
    "polynomial_add",
    "polynomial_derivative",
    "polynomial_divmod",
    "polynomial_evaluate",
    "polynomial_integral",
    "polynomial_multiply",
    "polynomial_roots",
    "GivensRotation",
    "HouseholderReflection",
    "apply_givens_pair",
    "apply_householder_left",
    "apply_householder_vector",
    "givens_rotation",
    "householder_reflection",
    "orthogonal_reflection_matrix",
    "ChebyshevSeries",
    "chebyshev_t",
    "clenshaw_chebyshev",
    "fit_chebyshev_series",
    "legendre_p",
    "probabilists_hermite",
    "cross_entropy",
    "effective_sample_size",
    "entropy",
    "jensen_shannon_divergence",
    "kl_divergence",
    "normalize_distribution",
    "weighted_moments",
    "GaussLegendreRule",
    "GaussianQuadratureReport",
    "gauss_legendre_integrate",
    "gauss_legendre_rule",
    "BootstrapReport",
    "JackknifeReport",
    "bootstrap",
    "jackknife",
    "KendallTauReport",
    "kendall_tau_b",
    "rank_biserial_correlation",
    "rankdata",
    "spearman_correlation",
    "HuberLocationReport",
    "huber_location",
    "modified_z_scores",
    "robust_interquartile_range",
    "robust_scale_mad",
    "trimmed_mean",
    "winsorized_mean",
    "Quaternion",
    "quaternion_from_axis_angle",
    "quaternion_multiply",
    "quaternion_rotate_vector",
    "quaternion_slerp",
    "quaternion_to_rotation_matrix",
    "MonteCarloReport",
    "SplitMix64",
    "halton_point",
    "monte_carlo_unit_cube",
    "radical_inverse",
    "systematic_resample",
    "DTWReport",
    "discrete_frechet_distance",
    "dynamic_time_warping",
    "levenshtein_distance",
    "normalized_levenshtein_distance",
    "CSRMatrix",
    "sparse_dense_matmul",
    "SymmetricMatrixFunctionReport",
    "symmetric_matrix_exp",
    "symmetric_matrix_inverse_sqrt",
    "symmetric_matrix_log",
    "symmetric_matrix_sqrt",
    "PseudoinverseReport",
    "SVDReport",
    "least_norm_solve",
    "pseudoinverse",
    "singular_value_decomposition",
    "HittingTimeReport",
    "absorbing_probability",
    "expected_hitting_times",
    "propagate_distribution",
    "transition_power",
    "SLogDetReport",
    "frobenius_norm",
    "identity_matrix",
    "kronecker_product",
    "matrix_power",
    "matrix_trace",
    "slogdet",
    "LyapunovReport",
    "SylvesterReport",
    "solve_continuous_lyapunov",
    "solve_sylvester",
    "MatrixExponentialReport",
    "matrix_exponential",
    "GershgorinDisc",
    "circulant",
    "diagonal_dominance_margins",
    "gershgorin_discs",
    "is_strictly_diagonally_dominant",
    "symmetrize",
    "toeplitz",
    "CholeskyUpdateReport",
    "cholesky_factor_after_rank_one_update",
    "cholesky_rank_one_update",
    "symmetric_rank_one_update",
    "AssignmentReport",
    "minimum_cost_assignment",
    "ConjugateGradientReport",
    "RootReport",
    "bisection_root",
    "bracketed_newton_root",
    "conjugate_gradient",
    "EigenReport",
    "SpectrumBin",
    "dominant_eigenpair_symmetric",
    "dominant_frequency",
    "periodogram",
    "spectral_power_fraction",
    "CrossCorrelationReport",
    "blackman_window",
    "cross_correlation",
    "hamming_window",
    "hann_window",
    "linear_detrend",
    "moving_average",
    "moving_rms",
    "LocalPolynomialReport",
    "local_polynomial_smooth",
    "savitzky_golay_derivative",
    "savitzky_golay_smooth",
    "inverse_softplus",
    "log1mexp",
    "log_cosh",
    "logaddexp",
    "logsubexp",
    "stable_logit",
    "stable_sigmoid",
    "stable_softplus",
    "NaturalCubicSpline",
    "natural_cubic_spline",
    "MomentReport",
    "correlation",
    "covariance",
    "covariance_matrix",
    "median",
    "median_absolute_deviation",
    "moments",
    "quantile",
    "standardize",
    "mode_product",
    "tensor_contract",
    "tensor_dot",
    "tensor_outer",
    "DenseTensor",
    "tensor_add",
    "broadcast_shape",
    "tensor_divide",
    "tensor_multiply",
    "tensor_reduce_mean",
    "tensor_reduce_sum",
    "tensor_subtract",
    "tensor_zip",
    "TridiagonalSolveReport",
    "solve_tridiagonal",
    "tridiagonal_matvec",
    "SinkhornReport",
    "sinkhorn_transport",
    "wasserstein_distance_1d",
    "autocorrelation",
    "convolution",
    "dft",
    "fft_radix2",
    "inverse_dft",
    "inverse_fft_radix2",
    "WhiteningReport",
    "whiten",
    "haar_transform",
    "hadamard_transform",
    "inverse_haar_transform",
    "inverse_hadamard_transform",
    "MathAuditCase",
    "MathAuditReport",
    "audit_runtime_kernels",
]
