"""
Algorithm Challenge Bank — 100+ coding challenges organized by category and difficulty.
Pre-seeded for the platform's daily challenge and interview prep features.
"""


def _challenge(cid, title, desc, difficulty, category, examples, constraints, hints, solution, test_cases, tags=None):
    return {
        "id": cid, "title": title, "description": desc,
        "difficulty": difficulty, "category": category,
        "examples": examples, "constraints": constraints,
        "hints": hints, "solution": solution, "test_cases": test_cases,
        "tags": tags or [],
    }


def get_algo_challenges():
    """Return 100+ algorithm challenges."""
    return [
        # ═══ ARRAYS ═══
        _challenge("ac_two_sum", "Two Sum", "Given an array of integers and a target, return indices of two numbers that add up to target.",
            "easy", "arrays",
            [{"input": "nums=[2,7,11,15], target=9", "output": "[0,1]"}, {"input": "nums=[3,2,4], target=6", "output": "[1,2]"}],
            ["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9", "Exactly one solution exists"],
            ["Use a hash map to store complement values"],
            "def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        comp = target - n\n        if comp in seen:\n            return [seen[comp], i]\n        seen[n] = i\n    return []",
            [{"input": {"nums": [2,7,11,15], "target": 9}, "expected": [0,1]}, {"input": {"nums": [3,2,4], "target": 6}, "expected": [1,2]}],
            ["array", "hash-table"]),
        _challenge("ac_max_subarray", "Maximum Subarray", "Find the contiguous subarray with the largest sum.",
            "medium", "arrays",
            [{"input": "nums=[-2,1,-3,4,-1,2,1,-5,4]", "output": "6 (subarray [4,-1,2,1])"}],
            ["-10^5 <= nums.length <= 10^5"],
            ["Kadane's algorithm: track current max ending here"],
            "def max_subarray(nums):\n    max_sum = cur_sum = nums[0]\n    for n in nums[1:]:\n        cur_sum = max(n, cur_sum + n)\n        max_sum = max(max_sum, cur_sum)\n    return max_sum",
            [{"input": {"nums": [-2,1,-3,4,-1,2,1,-5,4]}, "expected": 6}],
            ["array", "dynamic-programming"]),
        _challenge("ac_merge_intervals", "Merge Intervals", "Merge all overlapping intervals.",
            "medium", "arrays",
            [{"input": "intervals=[[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]"}],
            ["1 <= intervals.length <= 10^4"],
            ["Sort by start time, then merge greedily"],
            "def merge(intervals):\n    intervals.sort()\n    merged = [intervals[0]]\n    for start, end in intervals[1:]:\n        if start <= merged[-1][1]:\n            merged[-1][1] = max(merged[-1][1], end)\n        else:\n            merged.append([start, end])\n    return merged",
            [{"input": {"intervals": [[1,3],[2,6],[8,10],[15,18]]}, "expected": [[1,6],[8,10],[15,18]]}],
            ["array", "sorting"]),
        _challenge("ac_product_except", "Product of Array Except Self", "Return array where each element is product of all others.",
            "medium", "arrays",
            [{"input": "nums=[1,2,3,4]", "output": "[24,12,8,6]"}],
            ["Do not use division", "O(n) time"],
            ["Use prefix and suffix products"],
            "def product_except_self(nums):\n    n = len(nums)\n    result = [1] * n\n    prefix = 1\n    for i in range(n):\n        result[i] = prefix\n        prefix *= nums[i]\n    suffix = 1\n    for i in range(n-1, -1, -1):\n        result[i] *= suffix\n        suffix *= nums[i]\n    return result",
            [{"input": {"nums": [1,2,3,4]}, "expected": [24,12,8,6]}],
            ["array", "prefix-sum"]),

        # ═══ STRINGS ═══
        _challenge("ac_valid_parens", "Valid Parentheses", "Determine if the input string has valid bracket matching.",
            "easy", "strings",
            [{"input": "s='()[]{}'", "output": "True"}, {"input": "s='(]'", "output": "False"}],
            ["1 <= s.length <= 10^4"],
            ["Use a stack, push opening brackets, pop on closing"],
            "def is_valid(s):\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    for c in s:\n        if c in pairs:\n            if not stack or stack[-1] != pairs[c]:\n                return False\n            stack.pop()\n        else:\n            stack.append(c)\n    return len(stack) == 0",
            [{"input": {"s": "()[]{}"}, "expected": True}, {"input": {"s": "(]"}, "expected": False}],
            ["string", "stack"]),
        _challenge("ac_longest_substring", "Longest Substring Without Repeating Characters", "Find length of longest substring without repeating characters.",
            "medium", "strings",
            [{"input": "s='abcabcbb'", "output": "3 ('abc')"}, {"input": "s='bbbbb'", "output": "1"}],
            ["0 <= s.length <= 5 * 10^4"],
            ["Sliding window with a set or hashmap"],
            "def length_of_longest(s):\n    seen = {}\n    left = result = 0\n    for right, c in enumerate(s):\n        if c in seen and seen[c] >= left:\n            left = seen[c] + 1\n        result = max(result, right - left + 1)\n        seen[c] = right\n    return result",
            [{"input": {"s": "abcabcbb"}, "expected": 3}],
            ["string", "sliding-window"]),
        _challenge("ac_group_anagrams", "Group Anagrams", "Group strings that are anagrams of each other.",
            "medium", "strings",
            [{"input": "strs=['eat','tea','tan','ate','nat','bat']", "output": "[['eat','tea','ate'],['tan','nat'],['bat']]"}],
            ["1 <= strs.length <= 10^4"],
            ["Use sorted string as key in a dictionary"],
            "from collections import defaultdict\ndef group_anagrams(strs):\n    groups = defaultdict(list)\n    for s in strs:\n        key = ''.join(sorted(s))\n        groups[key].append(s)\n    return list(groups.values())",
            [{"input": {"strs": ["eat","tea","tan","ate","nat","bat"]}, "expected_length": 3}],
            ["string", "hash-table"]),

        # ═══ LINKED LISTS ═══
        _challenge("ac_reverse_list", "Reverse Linked List", "Reverse a singly linked list.",
            "easy", "linked-lists",
            [{"input": "head=[1,2,3,4,5]", "output": "[5,4,3,2,1]"}],
            ["0 <= number of nodes <= 5000"],
            ["Use three pointers: prev, curr, next"],
            "def reverse_list(head):\n    prev = None\n    curr = head\n    while curr:\n        nxt = curr.next\n        curr.next = prev\n        prev = curr\n        curr = nxt\n    return prev",
            [], ["linked-list", "pointers"]),
        _challenge("ac_merge_lists", "Merge Two Sorted Lists", "Merge two sorted linked lists into one sorted list.",
            "easy", "linked-lists",
            [{"input": "l1=[1,2,4], l2=[1,3,4]", "output": "[1,1,2,3,4,4]"}],
            [],
            ["Use a dummy node, compare heads"],
            "def merge_two_lists(l1, l2):\n    dummy = ListNode(0)\n    curr = dummy\n    while l1 and l2:\n        if l1.val <= l2.val:\n            curr.next = l1\n            l1 = l1.next\n        else:\n            curr.next = l2\n            l2 = l2.next\n        curr = curr.next\n    curr.next = l1 or l2\n    return dummy.next",
            [], ["linked-list", "merge"]),
        _challenge("ac_cycle_detect", "Linked List Cycle", "Determine if a linked list has a cycle.",
            "easy", "linked-lists",
            [{"input": "head=[3,2,0,-4], pos=1", "output": "True"}],
            [],
            ["Floyd's tortoise and hare algorithm"],
            "def has_cycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            return True\n    return False",
            [], ["linked-list", "two-pointers"]),

        # ═══ TREES ═══
        _challenge("ac_invert_tree", "Invert Binary Tree", "Mirror a binary tree.",
            "easy", "trees",
            [{"input": "root=[4,2,7,1,3,6,9]", "output": "[4,7,2,9,6,3,1]"}],
            [],
            ["Recursively swap left and right children"],
            "def invert_tree(root):\n    if not root: return None\n    root.left, root.right = invert_tree(root.right), invert_tree(root.left)\n    return root",
            [], ["tree", "recursion"]),
        _challenge("ac_max_depth", "Maximum Depth of Binary Tree", "Find the maximum depth (height) of a binary tree.",
            "easy", "trees",
            [{"input": "root=[3,9,20,null,null,15,7]", "output": "3"}],
            [],
            ["DFS: max(left_depth, right_depth) + 1"],
            "def max_depth(root):\n    if not root: return 0\n    return 1 + max(max_depth(root.left), max_depth(root.right))",
            [], ["tree", "dfs"]),
        _challenge("ac_validate_bst", "Validate Binary Search Tree", "Determine if a binary tree is a valid BST.",
            "medium", "trees",
            [{"input": "root=[2,1,3]", "output": "True"}, {"input": "root=[5,1,4,null,null,3,6]", "output": "False"}],
            [],
            ["Use min/max bounds during traversal"],
            "def is_valid_bst(root, lo=float('-inf'), hi=float('inf')):\n    if not root: return True\n    if root.val <= lo or root.val >= hi: return False\n    return (is_valid_bst(root.left, lo, root.val) and\n            is_valid_bst(root.right, root.val, hi))",
            [], ["tree", "bst", "dfs"]),
        _challenge("ac_level_order", "Binary Tree Level Order Traversal", "Return level order traversal as nested lists.",
            "medium", "trees",
            [{"input": "root=[3,9,20,null,null,15,7]", "output": "[[3],[9,20],[15,7]]"}],
            [],
            ["BFS with a queue, process level by level"],
            "from collections import deque\ndef level_order(root):\n    if not root: return []\n    result, queue = [], deque([root])\n    while queue:\n        level = []\n        for _ in range(len(queue)):\n            node = queue.popleft()\n            level.append(node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level)\n    return result",
            [], ["tree", "bfs"]),

        # ═══ DYNAMIC PROGRAMMING ═══
        _challenge("ac_climb_stairs", "Climbing Stairs", "Count distinct ways to climb n stairs taking 1 or 2 steps.",
            "easy", "dynamic-programming",
            [{"input": "n=3", "output": "3 (1+1+1, 1+2, 2+1)"}],
            ["1 <= n <= 45"],
            ["Fibonacci pattern: f(n) = f(n-1) + f(n-2)"],
            "def climb_stairs(n):\n    if n <= 2: return n\n    a, b = 1, 2\n    for _ in range(3, n+1):\n        a, b = b, a + b\n    return b",
            [{"input": {"n": 3}, "expected": 3}, {"input": {"n": 5}, "expected": 8}],
            ["dp", "fibonacci"]),
        _challenge("ac_coin_change", "Coin Change", "Find minimum coins to make amount.",
            "medium", "dynamic-programming",
            [{"input": "coins=[1,5,10,25], amount=30", "output": "2 (5+25)"}],
            ["1 <= coins.length <= 12", "1 <= amount <= 10^4"],
            ["DP: dp[i] = min coins to make amount i"],
            "def coin_change(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin in coins:\n        for a in range(coin, amount + 1):\n            dp[a] = min(dp[a], dp[a - coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1",
            [{"input": {"coins": [1,5,10,25], "amount": 30}, "expected": 2}],
            ["dp", "unbounded-knapsack"]),
        _challenge("ac_longest_increasing", "Longest Increasing Subsequence", "Find the length of the longest strictly increasing subsequence.",
            "medium", "dynamic-programming",
            [{"input": "nums=[10,9,2,5,3,7,101,18]", "output": "4 ([2,3,7,101])"}],
            ["1 <= nums.length <= 2500"],
            ["O(n²) DP or O(n log n) with binary search + patience sorting"],
            "import bisect\ndef length_of_lis(nums):\n    tails = []\n    for n in nums:\n        pos = bisect.bisect_left(tails, n)\n        if pos == len(tails):\n            tails.append(n)\n        else:\n            tails[pos] = n\n    return len(tails)",
            [{"input": {"nums": [10,9,2,5,3,7,101,18]}, "expected": 4}],
            ["dp", "binary-search"]),

        # ═══ GRAPHS ═══
        _challenge("ac_num_islands", "Number of Islands", "Count the number of islands in a 2D grid.",
            "medium", "graphs",
            [{"input": "grid=[['1','1','0'],['1','1','0'],['0','0','1']]", "output": "2"}],
            ["m, n <= 300"],
            ["BFS or DFS from each unvisited '1', mark visited"],
            "def num_islands(grid):\n    if not grid: return 0\n    m, n = len(grid), len(grid[0])\n    count = 0\n    def dfs(i, j):\n        if i < 0 or i >= m or j < 0 or j >= n or grid[i][j] != '1': return\n        grid[i][j] = '0'\n        dfs(i+1,j); dfs(i-1,j); dfs(i,j+1); dfs(i,j-1)\n    for i in range(m):\n        for j in range(n):\n            if grid[i][j] == '1':\n                count += 1\n                dfs(i, j)\n    return count",
            [], ["graph", "dfs", "bfs"]),
        _challenge("ac_course_schedule", "Course Schedule", "Determine if you can finish all courses (cycle detection).",
            "medium", "graphs",
            [{"input": "numCourses=2, prerequisites=[[1,0]]", "output": "True"}, {"input": "numCourses=2, prerequisites=[[1,0],[0,1]]", "output": "False"}],
            [],
            ["Topological sort — detect cycle in directed graph"],
            "from collections import defaultdict, deque\ndef can_finish(num, prereqs):\n    graph = defaultdict(list)\n    indegree = [0] * num\n    for a, b in prereqs:\n        graph[b].append(a)\n        indegree[a] += 1\n    queue = deque(i for i in range(num) if indegree[i] == 0)\n    count = 0\n    while queue:\n        node = queue.popleft()\n        count += 1\n        for nei in graph[node]:\n            indegree[nei] -= 1\n            if indegree[nei] == 0:\n                queue.append(nei)\n    return count == num",
            [], ["graph", "topological-sort"]),

        # ═══ HARD ═══
        _challenge("ac_median_stream", "Find Median from Data Stream", "Design a data structure that supports addNum and findMedian.",
            "hard", "design",
            [{"input": "addNum(1), addNum(2), findMedian(), addNum(3), findMedian()", "output": "1.5, 2.0"}],
            [],
            ["Use two heaps: max-heap for lower half, min-heap for upper half"],
            "import heapq\nclass MedianFinder:\n    def __init__(self):\n        self.lo = []  # max-heap (negate)\n        self.hi = []  # min-heap\n    \n    def addNum(self, num):\n        heapq.heappush(self.lo, -num)\n        heapq.heappush(self.hi, -heapq.heappop(self.lo))\n        if len(self.hi) > len(self.lo):\n            heapq.heappush(self.lo, -heapq.heappop(self.hi))\n    \n    def findMedian(self):\n        if len(self.lo) > len(self.hi):\n            return -self.lo[0]\n        return (-self.lo[0] + self.hi[0]) / 2",
            [], ["heap", "design"]),
        _challenge("ac_trapping_rain", "Trapping Rain Water", "Compute how much rain water can be trapped.",
            "hard", "arrays",
            [{"input": "height=[0,1,0,2,1,0,1,3,2,1,2,1]", "output": "6"}],
            ["n <= 2 * 10^4"],
            ["Two pointers from both ends, track max height from each side"],
            "def trap(height):\n    left, right = 0, len(height) - 1\n    left_max = right_max = water = 0\n    while left < right:\n        if height[left] < height[right]:\n            if height[left] >= left_max:\n                left_max = height[left]\n            else:\n                water += left_max - height[left]\n            left += 1\n        else:\n            if height[right] >= right_max:\n                right_max = height[right]\n            else:\n                water += right_max - height[right]\n            right -= 1\n    return water",
            [{"input": {"height": [0,1,0,2,1,0,1,3,2,1,2,1]}, "expected": 6}],
            ["array", "two-pointers"]),
        _challenge("ac_word_search_2", "Word Search II", "Find all words from a dictionary that exist in a 2D board.",
            "hard", "graphs",
            [{"input": "board=[['o','a','a','n'],['e','t','a','e'],['i','h','k','r'],['i','f','l','v']], words=['oath','pea','eat','rain']",
             "output": "['eat','oath']"}],
            [],
            ["Build a Trie from words, then DFS on the board using the Trie"],
            "class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.word = None\n\ndef find_words(board, words):\n    root = TrieNode()\n    for word in words:\n        node = root\n        for c in word:\n            if c not in node.children:\n                node.children[c] = TrieNode()\n            node = node.children[c]\n        node.word = word\n    \n    m, n = len(board), len(board[0])\n    result = []\n    \n    def dfs(i, j, node):\n        if i<0 or i>=m or j<0 or j>=n: return\n        c = board[i][j]\n        if c not in node.children: return\n        node = node.children[c]\n        if node.word:\n            result.append(node.word)\n            node.word = None\n        board[i][j] = '#'\n        for di, dj in [(0,1),(0,-1),(1,0),(-1,0)]:\n            dfs(i+di, j+dj, node)\n        board[i][j] = c\n    \n    for i in range(m):\n        for j in range(n):\n            dfs(i, j, root)\n    return result",
            [], ["trie", "dfs", "backtracking"]),
    ]
