"""
MEGA Bibles — 12 new comprehensive knowledge bibles to push past 20 total.
"""
def _a(aid,title,content,tags=None,code="",diff="intermediate"):
    return {"id":aid,"title":title,"content":content,"tags":tags or[],"code_playground":code,"difficulty":diff}
def _s(sid,name,articles):
    return {"id":sid,"name":name,"articles":articles,"article_count":len(articles)}

def get_mega_bibles():
    return [
        {"id":"devops_complete_bible","name":"DevOps Complete Bible","icon":"git-branch","color":"#FF6B35","total_hours":1200,"category":"bible",
         "description":"Complete DevOps from CI/CD to GitOps, IaC, observability, and platform engineering.",
         "sections":[
             _s("dv_cicd","CI/CD Mastery",[
                 _a("dv_pipelines","Pipeline Design Patterns","Trunk-based development: short-lived branches, frequent merges\nGitFlow: feature/develop/release/hotfix branches\nCI: lint→test→build→publish on every push\nCD: staging→canary→production→rollback\n\nGitHub Actions:\non: push\njobs:\n  test: {runs-on: ubuntu-latest, steps: [checkout, setup, test, coverage]}\n  build: {needs: test, steps: [docker build, push]}\n  deploy: {needs: build, if: github.ref=='refs/heads/main', steps: [kubectl apply]}",["cicd","pipeline","github-actions","gitflow"]),
                 _a("dv_gitops","GitOps with ArgoCD","Git as single source of truth for infrastructure.\n\nArgoCD watches Git repo → auto-syncs to Kubernetes\napiVersion: argoproj.io/v1alpha1\nkind: Application\nspec:\n  source: {repoURL: 'https://github.com/org/k8s-configs', path: 'prod'}\n  destination: {server: 'https://kubernetes.default.svc', namespace: default}\n  syncPolicy: {automated: {prune: true, selfHeal: true}}\n\nFlux: alternative GitOps operator\nBenefits: audit trail, rollback via git revert, PR-based deployments",["gitops","argocd","flux","kubernetes"]),
             ]),
             _s("dv_observability","Observability",[
                 _a("dv_three_pillars","Three Pillars","Metrics: Prometheus, Grafana — request rate, error rate, duration (RED)\nLogs: ELK/Loki — structured JSON, correlation IDs, log levels\nTraces: Jaeger/Tempo — distributed tracing, span context, service maps\n\nOpenTelemetry: unified SDK for all three\nfrom opentelemetry import trace\ntracer = trace.get_tracer(__name__)\nwith tracer.start_as_current_span('process_order') as span:\n    span.set_attribute('order.id', order_id)\n    result = process(order)\n\nSLOs: 99.9% availability = 43.8min downtime/month\nError budget: 100% - SLO = allowed unreliability",["observability","metrics","logs","traces","opentelemetry","slo"]),
                 _a("dv_alerting","Alerting Best Practices","Alert on symptoms not causes: high error rate, not high CPU\nSeverity: P1 (revenue impact), P2 (degraded), P3 (non-urgent)\nRunbooks: link to troubleshooting doc in every alert\n\nPrometheus alerting rules:\ngroups:\n- name: api\n  rules:\n  - alert: HighErrorRate\n    expr: rate(http_requests_total{status=~'5..'}[5m]) / rate(http_requests_total[5m]) > 0.05\n    for: 5m\n    labels: {severity: critical}\n    annotations: {summary: 'Error rate > 5%', runbook: 'https://wiki/runbook/high-errors'}\n\nPagerDuty/OpsGenie: on-call rotation, escalation policies",["alerting","prometheus","pagerduty","slo","oncall"]),
             ]),
             _s("dv_iac","Infrastructure as Code",[
                 _a("dv_terraform_adv","Terraform Advanced","Modules: reusable infrastructure components\nWorkspaces: dev/staging/prod from same code\nState locking: S3 backend + DynamoDB lock\nImport: terraform import aws_instance.web i-1234567890\n\nterraform plan -out=plan.tfplan\nterraform apply plan.tfplan\nterraform state mv/rm/list\n\nBest practices:\n- Remote state with locking\n- Separate state per environment\n- Module versioning\n- Validate + fmt in CI\n- Use data sources for existing resources\n- Terragrunt for DRY multi-env",["terraform","iac","modules","state","terragrunt"]),
             ]),
         ]},
        {"id":"api_design_bible","name":"API Design Bible","icon":"code-working","color":"#3B82F6","total_hours":900,"category":"bible",
         "description":"Complete API design from REST to GraphQL, gRPC, WebSocket, and API gateway patterns.",
         "sections":[
             _s("api_rest","REST API Design",[
                 _a("api_rest_best","REST Best Practices","Resources: /users, /users/{id}, /users/{id}/posts\nMethods: GET (read), POST (create), PUT (replace), PATCH (update), DELETE\nStatus: 200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 409 Conflict, 422 Unprocessable, 429 Rate Limited\n\nPagination: ?page=2&per_page=20 or cursor-based ?cursor=abc123&limit=20\nFiltering: ?status=active&created_after=2024-01-01&sort=-created_at\nVersioning: /v1/users (URL) or Accept: application/vnd.api.v2+json (header)\nHATEOAS: include links to related resources\n\nIdempotency: GET/PUT/DELETE are idempotent, POST is not\nUse Idempotency-Key header for safe retries on POST",["api","rest","pagination","versioning","idempotency"]),
                 _a("api_error","Error Handling","Standard error format:\n{\n  \"error\": {\n    \"code\": \"VALIDATION_ERROR\",\n    \"message\": \"Invalid input\",\n    \"request_id\": \"req_abc123\",\n    \"details\": [\n      {\"field\": \"email\", \"message\": \"Must be valid email\", \"code\": \"invalid_format\"},\n      {\"field\": \"age\", \"message\": \"Must be positive\", \"code\": \"out_of_range\"}\n    ]\n  }\n}\n\nAlways include request_id for debugging\nUse problem+json (RFC 7807) for standard error responses\nLog errors server-side with full context, return safe messages to client\nRate limit with 429 + Retry-After header",["api","error-handling","validation","rfc7807"]),
             ]),
             _s("api_graphql","GraphQL",[
                 _a("api_graphql_deep","GraphQL Deep Dive","Schema-first design:\ntype Query {\n  user(id: ID!): User\n  users(filter: UserFilter, page: Int, limit: Int): UserConnection!\n}\ntype User {\n  id: ID!\n  name: String!\n  posts(first: Int): [Post!]!\n}\ntype UserConnection {\n  edges: [UserEdge!]!\n  pageInfo: PageInfo!\n  totalCount: Int!\n}\n\nN+1 Problem: use DataLoader for batching\nSubscriptions: real-time via WebSocket\nFederation: split schema across microservices\nPersisted queries: hash queries for security + caching\n\nTools: Apollo Server, Hasura, Prisma, Relay, urql",["graphql","schema","dataloader","federation","subscriptions"]),
             ]),
             _s("api_grpc","gRPC",[
                 _a("api_grpc_deep","gRPC Deep Dive","Protocol Buffers (proto3):\nsyntax = \"proto3\";\nservice OrderService {\n  rpc CreateOrder(CreateOrderRequest) returns (Order);\n  rpc ListOrders(ListOrdersRequest) returns (stream Order);\n  rpc Chat(stream Message) returns (stream Message);\n}\n\nStreaming types:\n- Unary: request → response\n- Server streaming: request → stream of responses\n- Client streaming: stream of requests → response\n- Bidirectional: stream ↔ stream\n\nBenefits: binary (10x faster), typed, HTTP/2, streaming\nUse: microservices, mobile backends, real-time\nTools: grpcurl, grpc-web, Buf for schema management",["grpc","protobuf","streaming","http2"]),
             ]),
         ]},
        {"id":"cloud_architecture_bible","name":"Cloud Architecture Bible","icon":"cloud","color":"#0EA5E9","total_hours":1400,"category":"bible",
         "description":"Master multi-cloud architecture, serverless, containers, and cost optimization.",
         "sections":[
             _s("ca_patterns","Cloud Patterns",[
                 _a("ca_patterns_core","Cloud Architecture Patterns","1. Microservices: independent services, own data, API/events\n2. Event-Driven: producers→event bus→consumers (async)\n3. CQRS: separate read (optimized queries) from write (domain logic)\n4. Saga: distributed transactions via choreography/orchestration\n5. Strangler Fig: gradually migrate monolith to microservices\n6. Circuit Breaker: prevent cascade failures (Hystrix pattern)\n7. Bulkhead: isolate failures to prevent resource exhaustion\n8. Sidecar: attach proxy to each service (Envoy/Istio)\n9. Ambassador: proxy for cross-cutting concerns\n10. Anti-Corruption Layer: translate between bounded contexts\n\nResilience: retry with exponential backoff + jitter\nretry_delay = min(base * 2^attempt + random_jitter, max_delay)",["cloud","patterns","microservices","resilience","circuit-breaker"]),
             ]),
             _s("ca_cost","Cost Optimization",[
                 _a("ca_cost_opt","Cloud Cost Optimization","1. Right-sizing: match instance type to actual usage\n2. Reserved Instances: 1-3 year commitment, 30-60% savings\n3. Spot/Preemptible: 60-90% savings for fault-tolerant workloads\n4. Auto-scaling: scale to zero when idle\n5. Serverless: pay-per-invocation, no idle cost\n6. Storage tiering: hot→warm→cold→archive\n7. CDN caching: reduce origin requests\n8. Data transfer: keep traffic within same region/AZ\n9. Committed Use Discounts (GCP): similar to Reserved\n10. Savings Plans (AWS): flexible commitment across services\n\nTools: AWS Cost Explorer, GCP Billing, Kubecost, Infracost\nFinOps: shared accountability for cloud spend across teams",["cloud","cost","optimization","finops","reserved","spot"]),
             ]),
         ]},
        {"id":"ml_production_bible","name":"ML Production Bible","icon":"rocket","color":"#7C3AED","total_hours":1100,"category":"bible",
         "description":"Deploy ML models at scale: MLOps, monitoring, A/B testing, and infrastructure.",
         "sections":[
             _s("mlp_ops","MLOps",[
                 _a("mlp_pipeline","ML Pipeline Design","Data Pipeline: ingest→validate→transform→feature store\nTraining Pipeline: experiment→train→evaluate→register\nServing Pipeline: deploy→monitor→retrain\n\nMLflow:\nimport mlflow\nwith mlflow.start_run():\n    mlflow.log_param('lr', 0.01)\n    mlflow.log_metric('accuracy', 0.95)\n    mlflow.sklearn.log_model(model, 'model')\n\nFeature Store: Feast, Tecton — consistent features across training and serving\nModel Registry: version, stage (staging→production), metadata\nExperiment Tracking: MLflow, W&B, Neptune\n\nCI/CD for ML: data validation→training→evaluation→deployment→monitoring",["mlops","pipeline","mlflow","feature-store","experiment"]),
                 _a("mlp_serving","Model Serving","Batch: scheduled predictions on stored data\nReal-time: API serving with <100ms latency\nStreaming: continuous predictions on event streams\n\nServing frameworks:\n- TorchServe: PyTorch models\n- TensorFlow Serving: TF models\n- Triton: multi-framework GPU inference\n- vLLM: optimized LLM serving\n- BentoML: framework-agnostic\n\nOptimization:\n- Quantization: FP32→INT8 (2-4x speedup)\n- Pruning: remove unimportant weights\n- Distillation: train smaller model from larger\n- ONNX: cross-framework model format\n- TensorRT: NVIDIA GPU optimization\n\nA/B Testing: shadow mode→canary→gradual rollout\nMonitoring: data drift, prediction drift, model performance",["mlops","serving","inference","quantization","monitoring"]),
             ]),
         ]},
        {"id":"react_ecosystem_bible","name":"React Ecosystem Bible","icon":"logo-react","color":"#61DAFB","total_hours":1000,"category":"bible",
         "description":"Complete React ecosystem: hooks, state, routing, testing, SSR, and performance.",
         "sections":[
             _s("re_hooks","Advanced Hooks",[
                 _a("re_custom_hooks","Custom Hook Patterns","function useFetch<T>(url: string) {\n  const [data, setData] = useState<T | null>(null);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState<Error | null>(null);\n  useEffect(() => {\n    const controller = new AbortController();\n    fetch(url, { signal: controller.signal })\n      .then(r => r.json()).then(setData)\n      .catch(e => { if (e.name !== 'AbortError') setError(e); })\n      .finally(() => setLoading(false));\n    return () => controller.abort();\n  }, [url]);\n  return { data, loading, error };\n}\n\nfunction useDebounce<T>(value: T, delay: number): T {\n  const [debounced, setDebounced] = useState(value);\n  useEffect(() => { const t = setTimeout(() => setDebounced(value), delay); return () => clearTimeout(t); }, [value, delay]);\n  return debounced;\n}\n\nfunction useLocalStorage<T>(key: string, initial: T) {\n  const [value, setValue] = useState<T>(() => {\n    const stored = localStorage.getItem(key);\n    return stored ? JSON.parse(stored) : initial;\n  });\n  useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value]);\n  return [value, setValue] as const;\n}",["react","hooks","custom-hooks","useFetch","useDebounce"]),
             ]),
             _s("re_patterns","Architecture Patterns",[
                 _a("re_arch","React Architecture","Feature-based structure:\nsrc/\n  features/\n    auth/ (components, hooks, api, types)\n    dashboard/\n    settings/\n  shared/ (components, hooks, utils)\n  app/ (routes, providers, layout)\n\nState management decision tree:\n- Server state → React Query / SWR\n- Global UI state → Zustand / Jotai\n- Complex forms → React Hook Form\n- URL state → search params\n- Component state → useState\n\nError Boundaries:\nclass ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  static getDerivedStateFromError() { return { hasError: true }; }\n  componentDidCatch(error, info) { logError(error, info); }\n  render() { return this.state.hasError ? <Fallback /> : this.props.children; }\n}",["react","architecture","state-management","error-boundary"]),
             ]),
         ]},
        {"id":"database_engineering_bible","name":"Database Engineering Bible","icon":"server","color":"#10B981","total_hours":1300,"category":"bible",
         "description":"Master database internals, optimization, scaling, and choosing the right database.",
         "sections":[
             _s("dbe_internals","Database Internals",[
                 _a("dbe_indexes","Index Deep Dive","B-Tree: balanced tree, O(log n) lookup, range queries\n  - Default for most RDBMS\n  - Composite: (a, b, c) — leftmost prefix rule\n  - Covering: includes all query columns\n\nHash Index: O(1) exact match, no range queries\nGIN (Generalized Inverted): full-text search, JSONB, arrays\nGIST: spatial data (PostGIS)\nBRIN (Block Range): very large tables, sequential data\n\nIndex tips:\n- Don't index everything (write overhead)\n- EXPLAIN ANALYZE to verify usage\n- Partial indexes: WHERE active = true\n- Expression indexes: ON lower(email)\n- Monitor unused indexes and drop them\n\nQuery planner: cost-based optimization\nSeq Scan → Index Scan → Bitmap Scan → Index Only Scan",["database","index","b-tree","explain","optimization"]),
                 _a("dbe_transactions","Transactions & Isolation","ACID:\nAtomicity: all or nothing\nConsistency: valid state transitions\nIsolation: concurrent transactions don't interfere\nDurability: committed data survives crashes\n\nIsolation levels:\nRead Uncommitted: dirty reads possible\nRead Committed: no dirty reads (PostgreSQL default)\nRepeatable Read: no phantom reads (MySQL InnoDB default)\nSerializable: full isolation, slowest\n\nMVCC (Multi-Version Concurrency Control):\n- Each transaction sees a snapshot\n- Readers don't block writers, writers don't block readers\n- PostgreSQL: xmin/xmax version tracking\n- Vacuum cleans up dead tuples\n\nDeadlocks: circular wait → detection + abort one transaction\nDistributed: 2PC (two-phase commit), Saga pattern",["database","transactions","acid","isolation","mvcc","deadlock"]),
             ]),
             _s("dbe_scaling","Database Scaling",[
                 _a("dbe_scaling_patterns","Scaling Patterns","Read Replicas: master writes, replicas read (async replication)\n  - Replication lag: eventual consistency\n  - Use for: read-heavy workloads, analytics\n\nSharding: partition data across multiple servers\n  - Range: user_id 1-1M → shard 1, 1M-2M → shard 2\n  - Hash: hash(user_id) % num_shards\n  - Consistent hashing: handles rebalancing\n  - Challenges: cross-shard queries, rebalancing, joins\n\nConnection Pooling: PgBouncer, ProxySQL\n  - Transaction mode: reuse connections between transactions\n  - Session mode: pin connection to session\n\nCaching layer: Redis/Memcached in front of DB\n  - Cache-aside: check cache → miss → query DB → cache result\n  - Invalidation: TTL, event-based, write-through\n\nVertical: bigger machine (limited)\nHorizontal: more machines (unlimited but complex)",["database","scaling","sharding","replication","caching","pooling"]),
             ]),
         ]},
        {"id":"typescript_bible","name":"TypeScript Mastery Bible","icon":"code-slash","color":"#3178C6","total_hours":800,"category":"bible",
         "description":"Complete TypeScript from basics to advanced type-level programming.",
         "sections":[
             _s("ts_types","Advanced Types",[
                 _a("ts_type_level","Type-Level Programming","// Conditional types\ntype IsString<T> = T extends string ? true : false;\ntype ExtractPromise<T> = T extends Promise<infer U> ? U : T;\n\n// Mapped types\ntype Optional<T> = { [K in keyof T]?: T[K] };\ntype Readonly<T> = { readonly [K in keyof T]: T[K] };\ntype Getters<T> = { [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K] };\n\n// Template literal types\ntype HTTPMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';\ntype Route = `/${string}`;\ntype Endpoint = `${HTTPMethod} ${Route}`;\n\n// Recursive types\ntype DeepReadonly<T> = { readonly [K in keyof T]: T[K] extends object ? DeepReadonly<T[K]> : T[K] };\ntype Flatten<T> = T extends Array<infer U> ? Flatten<U> : T;\n\n// Branded types (nominal)\ntype USD = number & { __brand: 'USD' };\ntype EUR = number & { __brand: 'EUR' };\nfunction usd(n: number): USD { return n as USD; }\n// Can't accidentally mix USD and EUR",["typescript","types","conditional","mapped","template-literal","branded"]),
             ]),
         ]},
        {"id":"python_mastery_bible","name":"Python Mastery Bible","icon":"logo-python","color":"#3776AB","total_hours":1100,"category":"bible",
         "description":"Advanced Python: metaclasses, descriptors, C extensions, performance, and production patterns.",
         "sections":[
             _s("py_advanced","Advanced Python",[
                 _a("py_metaclass","Metaclasses & Descriptors","# Metaclass: class that creates classes\nclass SingletonMeta(type):\n    _instances = {}\n    def __call__(cls, *args, **kwargs):\n        if cls not in cls._instances:\n            cls._instances[cls] = super().__call__(*args, **kwargs)\n        return cls._instances[cls]\n\nclass Database(metaclass=SingletonMeta):\n    def __init__(self): self.connection = connect()\n\n# Descriptor: controls attribute access\nclass Validated:\n    def __init__(self, validator): self.validator = validator\n    def __set_name__(self, owner, name): self.name = name\n    def __get__(self, obj, type=None): return obj.__dict__.get(self.name)\n    def __set__(self, obj, value):\n        if not self.validator(value): raise ValueError(f'Invalid {self.name}')\n        obj.__dict__[self.name] = value\n\nclass User:\n    name = Validated(lambda v: isinstance(v, str) and len(v) > 0)\n    age = Validated(lambda v: isinstance(v, int) and 0 < v < 150)",["python","metaclass","descriptor","singleton","advanced"]),
                 _a("py_production","Production Python","# Structured logging\nimport structlog\nlogger = structlog.get_logger()\nlogger.info('request_processed', user_id='123', latency_ms=45)\n\n# Configuration\nfrom pydantic_settings import BaseSettings\nclass Settings(BaseSettings):\n    database_url: str\n    redis_url: str\n    debug: bool = False\n    class Config:\n        env_file = '.env'\n\n# Dependency injection\nclass OrderService:\n    def __init__(self, repo: OrderRepository, notifier: Notifier):\n        self.repo = repo; self.notifier = notifier\n\n# Health checks\n@app.get('/health')\nasync def health():\n    db_ok = await check_db()\n    redis_ok = await check_redis()\n    return {'status': 'ok' if all([db_ok, redis_ok]) else 'degraded',\n            'checks': {'db': db_ok, 'redis': redis_ok}}\n\n# Graceful shutdown\nimport signal\nsignal.signal(signal.SIGTERM, lambda *_: shutdown())",["python","production","logging","configuration","health-check","di"]),
             ]),
         ]},
        {"id":"security_complete_bible","name":"Security Complete Bible","icon":"lock-closed","color":"#EF4444","total_hours":1100,"category":"bible",
         "description":"Complete application security: auth, encryption, OWASP, pentesting, compliance.",
         "sections":[
             _s("sec_auth","Authentication & Authorization",[
                 _a("sec_auth_patterns","Auth Patterns","Session-based: server stores session, cookie has session ID\n  + Simple, server controls invalidation\n  - Requires sticky sessions or shared store\n\nJWT: stateless token with claims\n  + Scalable, no server state\n  - Can't revoke (use short expiry + refresh token)\n  \nOAuth 2.0 flows:\n  Authorization Code + PKCE (web/mobile)\n  Client Credentials (machine-to-machine)\n  Device Code (TV/IoT)\n\nMFA: TOTP (Google Authenticator), WebAuthn/FIDO2 (biometric/hardware key)\nPasskeys: password-less auth using device biometrics\n\nRBAC: role → permissions\nABAC: attribute-based (user.dept == resource.dept)\nReBAC: relationship-based (Google Zanzibar)",["security","auth","jwt","oauth","mfa","passkeys","rbac"]),
             ]),
             _s("sec_appsec","Application Security",[
                 _a("sec_supply_chain","Supply Chain Security","Dependencies are attack vectors.\n\nTools:\n- npm audit / pip-audit / cargo-audit\n- Dependabot / Renovate: auto-update\n- Snyk: vulnerability scanning\n- Socket.dev: detect malicious packages\n\nSBOM (Software Bill of Materials): list all dependencies\nSLSA: Supply chain Levels for Software Artifacts\nSignature verification: sigstore/cosign for container images\n\nBest practices:\n- Pin exact versions in production\n- Use lockfiles (package-lock.json, poetry.lock)\n- Review dependency diffs in PRs\n- Minimal base images (distroless, Alpine)\n- Don't run as root in containers",["security","supply-chain","dependencies","sbom","scanning"]),
             ]),
         ]},
        {"id":"concurrency_bible","name":"Concurrency & Parallelism Bible","icon":"git-network","color":"#8B5CF6","total_hours":900,"category":"bible",
         "description":"Master concurrency patterns across languages: threads, async, actors, CSP.",
         "sections":[
             _s("con_models","Concurrency Models",[
                 _a("con_models_overview","Concurrency Models Overview","1. Threads + Locks (Java, C++, Python)\n  Shared memory, mutex/semaphore synchronization\n  Challenges: deadlocks, race conditions, priority inversion\n\n2. Async/Await (Python, JS, Rust, C#)\n  Cooperative multitasking on single thread\n  Event loop schedules coroutines\n  Best for I/O-bound workloads\n\n3. Actor Model (Erlang/Elixir, Akka)\n  Isolated actors communicate via messages\n  No shared state, fault-tolerant (supervision trees)\n  Location-transparent: works across nodes\n\n4. CSP — Communicating Sequential Processes (Go)\n  Goroutines + channels\n  'Don't communicate by sharing memory; share memory by communicating'\n\n5. STM — Software Transactional Memory (Haskell, Clojure)\n  Atomic, composable transactions on shared memory\n\nChoosing:\n  I/O-bound → async/await\n  CPU-bound → threads/processes/parallel\n  Distributed → actors\n  Simple concurrency → Go channels",["concurrency","threads","async","actors","csp","models"]),
             ]),
         ]},
        {"id":"data_structures_bible","name":"Data Structures Bible","icon":"git-network","color":"#F59E0B","total_hours":1000,"category":"bible",
         "description":"Every data structure from arrays to advanced trees, graphs, and probabilistic structures.",
         "sections":[
             _s("ds_linear","Linear Structures",[
                 _a("ds_array_list","Arrays & Lists","Array: contiguous memory, O(1) access, O(n) insert/delete\nLinked List: nodes with pointers, O(1) insert/delete at head, O(n) access\nDoubly Linked: prev + next pointers, O(1) delete given node\nCircular: tail.next = head, useful for round-robin\n\nDynamic Array (ArrayList/vector): amortized O(1) append\n  Growth: double capacity when full → amortized O(1)\n  Python list, Java ArrayList, C++ std::vector\n\nSkip List: sorted linked list with express lanes\n  O(log n) search/insert/delete\n  Used in Redis sorted sets, LevelDB",["data-structures","array","linked-list","skip-list"]),
             ]),
             _s("ds_trees","Trees",[
                 _a("ds_tree_types","Tree Types","BST: left < root < right, O(log n) avg, O(n) worst\nAVL: self-balancing BST, strict balance (heights differ by ≤1)\nRed-Black: self-balancing BST, relaxed balance (used in Java TreeMap)\nB-Tree: multi-way balanced tree, used in databases and filesystems\nB+ Tree: B-tree variant, all data in leaves, linked for range queries\n\nTrie: prefix tree for strings, O(m) operations where m=key length\nSegment Tree: range queries + point updates, O(log n)\nFenwick Tree (BIT): prefix sums + point updates, O(log n)\n\nHeap: complete binary tree, O(1) min/max, O(log n) insert/delete\n  Min-heap: parent ≤ children\n  Max-heap: parent ≥ children\n  Applications: priority queue, Dijkstra, K-th element\n\nSplay Tree: self-adjusting, recently accessed near root\nTreap: BST + heap hybrid, randomized balancing",["data-structures","tree","bst","avl","b-tree","heap","trie"]),
             ]),
             _s("ds_probabilistic","Probabilistic Structures",[
                 _a("ds_bloom","Bloom Filter & HyperLogLog","Bloom Filter: test set membership\n  False positives possible, false negatives impossible\n  Operations: add (set bits), contains (check bits)\n  Space: ~10 bits per element for 1% FP rate\n  Used in: Chrome safe browsing, databases (skip disk reads)\n\nHyperLogLog: approximate cardinality (count distinct)\n  O(1) add, O(1) count, ~0.8% error\n  12KB memory for billions of elements\n  Used in: Redis PFCOUNT, database query planners\n\nCount-Min Sketch: approximate frequency counting\n  Multiple hash functions, array of counters\n  Over-estimates never under-estimates\n\nCuckoo Filter: like Bloom but supports deletion\nMinHash: approximate Jaccard similarity",["data-structures","bloom-filter","hyperloglog","probabilistic","sketch"]),
             ]),
         ]},
    ]
