"""
Expanded Knowledge Bibles — Hyperscale Edition
System Design, Architecture, Algorithms, Performance, Testing, Mobile Dev bibles
Each with deep-dive articles, code playgrounds, and reference docs.
"""


def _article(aid, title, content, tags=None, code_playground="", difficulty="intermediate"):
    return {
        "id": aid, "title": title, "content": content,
        "tags": tags or [], "code_playground": code_playground,
        "difficulty": difficulty,
    }


def _section(sid, name, articles):
    return {"id": sid, "name": name, "articles": articles, "article_count": len(articles)}


def get_expanded_bibles():
    """Return expanded knowledge bibles with deep-dive articles."""
    return [
        # ═══════════════════════════════════════════════════════════════
        # SYSTEM DESIGN BIBLE (Expanded)
        # ═══════════════════════════════════════════════════════════════
        {
            "id": "system_design_bible", "name": "System Design Bible", "icon": "git-branch",
            "color": "#3B82F6", "total_hours": 1280, "category": "bible",
            "description": "Master large-scale distributed system design from load balancers to global-scale architectures.",
            "sections": [
                _section("sd_fundamentals", "Fundamentals", [
                    _article("sd_scaling", "Horizontal vs Vertical Scaling",
                        "# Scaling Strategies\n\n## Vertical Scaling (Scale Up)\nAdd more power to existing machine.\n```\nBefore: 4 CPU, 16GB RAM\nAfter:  32 CPU, 256GB RAM\n```\n**Pros:** Simple, no code changes\n**Cons:** Hardware limits, single point of failure\n\n## Horizontal Scaling (Scale Out)\nAdd more machines.\n```\nBefore: 1 server\nAfter:  10 servers behind load balancer\n```\n**Pros:** Nearly unlimited scale, fault tolerance\n**Cons:** Complex, needs stateless design\n\n## When to Choose\n```\nVertical: Database servers, legacy apps, < 10K users\nHorizontal: Web servers, microservices, > 100K users\nHybrid: Most production systems\n```\n\n## Auto-Scaling (AWS)\n```yaml\nAutoScalingGroup:\n  MinSize: 2\n  MaxSize: 20\n  TargetTrackingPolicy:\n    TargetValue: 70  # CPU utilization %\n    PredefinedMetricSpecification:\n      PredefinedMetricType: ASGAverageCPUUtilization\n```",
                        ["scaling", "architecture"], difficulty="beginner"),
                    _article("sd_load_balancing", "Load Balancing Deep Dive",
                        "# Load Balancing\n\n## Algorithms\n```\nRound Robin:     A → B → C → A → B → C\nWeighted RR:     A(3) → A → A → B(1) → C(2) → C\nLeast Conn:      Route to server with fewest active connections\nIP Hash:         hash(client_ip) % num_servers → consistent routing\nRandom:          Random selection (surprisingly effective)\n```\n\n## Layer 4 vs Layer 7\n```\nL4 (Transport): TCP/UDP level, very fast, no content inspection\n  → HAProxy, AWS NLB\n  → Use for: Gaming, real-time, raw throughput\n\nL7 (Application): HTTP level, content-based routing\n  → Nginx, AWS ALB, Envoy\n  → Use for: API routing, A/B testing, SSL termination\n```\n\n## Nginx Configuration\n```nginx\nupstream backend {\n    least_conn;\n    server app1:8000 weight=3;\n    server app2:8000 weight=2;\n    server app3:8000 weight=1;\n    server app4:8000 backup;\n}\n\nserver {\n    listen 80;\n    location / {\n        proxy_pass http://backend;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_connect_timeout 5s;\n        proxy_read_timeout 60s;\n    }\n    location /api/v2 {\n        proxy_pass http://backend_v2;\n    }\n}\n```\n\n## Health Checks\n```nginx\nupstream backend {\n    server app1:8000 max_fails=3 fail_timeout=30s;\n    server app2:8000 max_fails=3 fail_timeout=30s;\n}\n```",
                        ["load-balancing", "nginx", "haproxy"]),
                    _article("sd_caching", "Caching Strategies",
                        "# Caching\n\n## Cache Patterns\n```\nCache-Aside (Lazy Loading):\n  1. Check cache\n  2. If miss → read DB → write cache → return\n  Pros: Only caches what's needed\n  Cons: Cache miss penalty, stale data\n\nWrite-Through:\n  1. Write to cache AND DB simultaneously\n  Pros: Cache always fresh\n  Cons: Write latency, caches unused data\n\nWrite-Behind (Write-Back):\n  1. Write to cache → async write to DB\n  Pros: Fast writes\n  Cons: Data loss risk if cache fails\n```\n\n## Redis Implementation\n```python\nimport redis\nimport json\n\nr = redis.Redis(host='localhost', port=6379, decode_responses=True)\n\ndef get_user(user_id: str) -> dict:\n    # Check cache first\n    cached = r.get(f'user:{user_id}')\n    if cached:\n        return json.loads(cached)\n    \n    # Cache miss — fetch from DB\n    user = db.users.find_one({'id': user_id})\n    if user:\n        # Cache for 5 minutes\n        r.setex(f'user:{user_id}', 300, json.dumps(user))\n    return user\n\ndef invalidate_user(user_id: str):\n    r.delete(f'user:{user_id}')\n```\n\n## Cache Eviction Policies\n```\nLRU (Least Recently Used): Remove oldest unused — best general purpose\nLFU (Least Frequently Used): Remove least popular — good for hot data\nTTL (Time To Live): Expire after duration — good for sessions\nFIFO: First in, first out — simplest\n```\n\n## CDN Caching\n```\nCloudflare / CloudFront:\n  Edge locations worldwide\n  Cache static assets: images, CSS, JS\n  Cache-Control headers drive behavior\n\nHeaders:\n  Cache-Control: public, max-age=31536000  (1 year, immutable assets)\n  Cache-Control: no-cache                   (revalidate every time)\n  Cache-Control: private, max-age=300       (browser only, 5 min)\n  ETag: \"abc123\"                            (conditional requests)\n```",
                        ["caching", "redis", "cdn"]),
                    _article("sd_database_design", "Database Scaling Patterns",
                        "# Database Scaling\n\n## Replication\n```\nMaster-Slave (Primary-Replica):\n  Write → Master → async replicate → Slaves\n  Read ← Slaves (read replicas)\n  \n  Pros: Read scaling, fault tolerance\n  Cons: Replication lag, write bottleneck\n\nMaster-Master:\n  Both accept writes, sync bidirectionally\n  Pros: Write availability\n  Cons: Conflict resolution, complexity\n```\n\n## Sharding\n```python\n# Range-based sharding\ndef get_shard(user_id: int, num_shards: int = 4) -> int:\n    if user_id < 1_000_000: return 0\n    if user_id < 2_000_000: return 1\n    if user_id < 3_000_000: return 2\n    return 3\n\n# Hash-based sharding (more uniform)\ndef get_shard_hash(user_id: int, num_shards: int = 4) -> int:\n    return hash(str(user_id)) % num_shards\n\n# Consistent hashing (handles rebalancing)\nimport hashlib\nclass ConsistentHash:\n    def __init__(self, nodes, replicas=150):\n        self.ring = {}\n        self.sorted_keys = []\n        for node in nodes:\n            for i in range(replicas):\n                key = self._hash(f'{node}:{i}')\n                self.ring[key] = node\n                self.sorted_keys.append(key)\n        self.sorted_keys.sort()\n    \n    def _hash(self, key):\n        return int(hashlib.md5(key.encode()).hexdigest(), 16)\n    \n    def get_node(self, key):\n        h = self._hash(str(key))\n        for ring_key in self.sorted_keys:\n            if h <= ring_key:\n                return self.ring[ring_key]\n        return self.ring[self.sorted_keys[0]]\n```\n\n## CAP Theorem\n```\nConsistency: Every read gets latest write\nAvailability: Every request gets a response\nPartition Tolerance: System works despite network splits\n\nPick 2:\n  CP: MongoDB, HBase (consistent but may be unavailable)\n  AP: Cassandra, DynamoDB (available but eventually consistent)\n  CA: Single-node DB (no partition tolerance)\n```",
                        ["database", "sharding", "replication", "cap-theorem"]),
                    _article("sd_message_queues", "Message Queues & Event Streaming",
                        "# Message Queues\n\n## When to Use\n```\n✓ Decouple producers from consumers\n✓ Handle traffic spikes (buffer)\n✓ Ensure reliable delivery\n✓ Enable async processing\n✓ Fan-out to multiple consumers\n```\n\n## Kafka Architecture\n```\nProducer → Topic (partitioned) → Consumer Group\n\nTopic: orders\n  Partition 0: [msg1, msg4, msg7, ...]\n  Partition 1: [msg2, msg5, msg8, ...]\n  Partition 2: [msg3, msg6, msg9, ...]\n\nConsumer Group A:\n  Consumer 1 reads Partition 0\n  Consumer 2 reads Partition 1,2\n\nConsumer Group B (independent):\n  Consumer 3 reads all partitions\n```\n\n## Python + Kafka\n```python\nfrom kafka import KafkaProducer, KafkaConsumer\nimport json\n\n# Producer\nproducer = KafkaProducer(\n    bootstrap_servers='localhost:9092',\n    value_serializer=lambda v: json.dumps(v).encode()\n)\n\nproducer.send('orders', {\n    'order_id': '12345',\n    'user_id': 'u789',\n    'total': 99.99,\n    'items': ['widget_a', 'widget_b']\n})\nproducer.flush()\n\n# Consumer\nconsumer = KafkaConsumer(\n    'orders',\n    bootstrap_servers='localhost:9092',\n    group_id='order-processor',\n    value_deserializer=lambda m: json.loads(m.decode())\n)\n\nfor message in consumer:\n    order = message.value\n    process_order(order)\n    print(f'Processed order {order[\"order_id\"]}')\n```\n\n## RabbitMQ vs Kafka vs SQS\n```\nRabbitMQ: Traditional queue, message routing, small-medium scale\nKafka: Event streaming, replay, high throughput, big data\nSQS: Managed AWS, serverless, no ops, auto-scale\nRedis Streams: Lightweight, in-memory, good for real-time\n```",
                        ["kafka", "rabbitmq", "event-streaming"]),
                ]),
                _section("sd_real_world", "Real-World System Designs", [
                    _article("sd_url_shortener", "Design: URL Shortener",
                        "# URL Shortener (bit.ly)\n\n## Requirements\n```\nFunctional:\n  - Shorten URL → 7 char code\n  - Redirect short URL → original\n  - Optional custom aliases\n  - Expiration support\n  - Analytics (click count)\n\nNon-Functional:\n  - 100M URLs/month created\n  - 10B redirects/month (100:1 read:write)\n  - < 100ms redirect latency\n  - 99.99% availability\n```\n\n## Storage Estimate\n```\n100M URLs/month × 12 months × 5 years = 6B URLs\nEach URL: ~500 bytes (original) + 50 bytes (metadata) = 550 bytes\nTotal: 6B × 550B = 3.3 TB\n```\n\n## Architecture\n```\nClient → Load Balancer → API Servers → Cache (Redis) → Database\n                                                    ↓\n                                              Analytics (Kafka → ClickHouse)\n```\n\n## URL Encoding\n```python\nimport hashlib\nimport string\n\nALPHABET = string.ascii_letters + string.digits  # 62 chars\n# 62^7 = 3.5 trillion possible URLs\n\ndef encode(url: str) -> str:\n    hash_val = hashlib.md5(url.encode()).hexdigest()\n    num = int(hash_val[:12], 16)  # First 12 hex chars\n    result = []\n    while num and len(result) < 7:\n        result.append(ALPHABET[num % 62])\n        num //= 62\n    return ''.join(result).ljust(7, 'a')\n\n# Or use auto-increment ID + base62\ndef id_to_short(id_num: int) -> str:\n    result = []\n    while id_num:\n        result.append(ALPHABET[id_num % 62])\n        id_num //= 62\n    return ''.join(reversed(result))\n```\n\n## Database Schema\n```sql\nCREATE TABLE urls (\n    id BIGINT PRIMARY KEY AUTO_INCREMENT,\n    short_code VARCHAR(7) UNIQUE NOT NULL,\n    original_url TEXT NOT NULL,\n    user_id BIGINT,\n    created_at TIMESTAMP DEFAULT NOW(),\n    expires_at TIMESTAMP,\n    click_count BIGINT DEFAULT 0\n);\nCREATE INDEX idx_short ON urls(short_code);\n```",
                        ["url-shortener", "system-design"], difficulty="intermediate"),
                    _article("sd_chat_system", "Design: Real-Time Chat (WhatsApp)",
                        "# Chat System Design\n\n## Requirements\n```\nFunctional:\n  - 1:1 messaging\n  - Group chat (up to 500 members)\n  - Online/offline status\n  - Read receipts\n  - Media sharing\n  - Message history\n\nNon-Functional:\n  - 500M daily active users\n  - 40B messages/day\n  - < 200ms delivery latency\n  - End-to-end encryption\n```\n\n## Architecture\n```\n┌──────────┐     ┌───────────────┐     ┌──────────────┐\n│  Client  │────→│  API Gateway  │────→│  Chat Server │\n│ (WebSocket)    │  (Auth, Rate) │     │  (Stateful)  │\n└──────────┘     └───────────────┘     └──────┬───────┘\n                                              │\n                    ┌─────────────────────────┼──────────────┐\n                    │                         │              │\n              ┌─────▼─────┐           ┌──────▼──────┐ ┌─────▼─────┐\n              │   Redis    │           │  Cassandra  │ │   Kafka   │\n              │ (Presence) │           │ (Messages)  │ │  (Events) │\n              └────────────┘           └─────────────┘ └───────────┘\n```\n\n## WebSocket Connection\n```python\nimport asyncio\nimport websockets\nimport json\n\nclass ChatServer:\n    def __init__(self):\n        self.connections = {}  # user_id -> websocket\n    \n    async def handler(self, ws, path):\n        user_id = await self.authenticate(ws)\n        self.connections[user_id] = ws\n        try:\n            async for message in ws:\n                data = json.loads(message)\n                await self.route_message(user_id, data)\n        finally:\n            del self.connections[user_id]\n    \n    async def route_message(self, sender_id, data):\n        recipient_id = data['to']\n        msg = {\n            'from': sender_id,\n            'text': data['text'],\n            'timestamp': time.time(),\n            'id': str(uuid.uuid4())\n        }\n        \n        # Store in Cassandra\n        await self.store_message(msg)\n        \n        # Deliver if online\n        if recipient_id in self.connections:\n            await self.connections[recipient_id].send(json.dumps(msg))\n        else:\n            # Queue for push notification\n            await self.queue_push(recipient_id, msg)\n```\n\n## Message Storage (Cassandra)\n```sql\nCREATE TABLE messages (\n    chat_id UUID,\n    message_id TIMEUUID,\n    sender_id UUID,\n    content TEXT,\n    media_url TEXT,\n    created_at TIMESTAMP,\n    PRIMARY KEY (chat_id, message_id)\n) WITH CLUSTERING ORDER BY (message_id DESC);\n```",
                        ["chat", "websocket", "real-time"], difficulty="advanced"),
                    _article("sd_notification", "Design: Notification System",
                        "# Notification System\n\n## Types\n```\nPush: Mobile notifications (APNs, FCM)\nSMS: Text messages (Twilio, AWS SNS)\nEmail: Transactional + marketing (SendGrid, SES)\nIn-App: Real-time UI updates (WebSocket)\n```\n\n## Architecture\n```\nEvent Source → Kafka → Notification Service → Channel Router\n                                                  ├→ Push (APNs/FCM)\n                                                  ├→ Email (SES)\n                                                  ├→ SMS (Twilio)\n                                                  └→ In-App (WebSocket)\n```\n\n## Rate Limiting & Deduplication\n```python\nclass NotificationService:\n    def __init__(self, redis_client):\n        self.redis = redis_client\n    \n    async def send(self, user_id: str, notification: dict):\n        # Deduplication (idempotency key)\n        dedup_key = f'notif:{notification[\"id\"]}'\n        if await self.redis.exists(dedup_key):\n            return  # Already sent\n        \n        # Rate limit: max 10 notifications per hour\n        rate_key = f'rate:{user_id}:notif'\n        count = await self.redis.incr(rate_key)\n        if count == 1:\n            await self.redis.expire(rate_key, 3600)\n        if count > 10:\n            return  # Rate limited\n        \n        # Check user preferences\n        prefs = await self.get_preferences(user_id)\n        if not prefs.get(notification['channel'], True):\n            return  # User opted out\n        \n        # Send via channel\n        await self.dispatch(user_id, notification)\n        await self.redis.setex(dedup_key, 86400, '1')\n```",
                        ["notifications", "push", "real-time"], difficulty="intermediate"),
                ]),
            ],
        },
        # ═══════════════════════════════════════════════════════════════
        # ALGORITHMS & DATA STRUCTURES BIBLE
        # ═══════════════════════════════════════════════════════════════
        {
            "id": "algorithms_bible", "name": "Algorithms & Data Structures Bible", "icon": "git-network",
            "color": "#8B5CF6", "total_hours": 1600, "category": "bible",
            "description": "Master algorithms from sorting to advanced graph theory, with 200+ problems.",
            "sections": [
                _section("algo_sorting", "Sorting & Searching", [
                    _article("algo_quicksort", "QuickSort In-Depth",
                        "# QuickSort\n\n## Algorithm\n```python\ndef quicksort(arr, low=0, high=None):\n    if high is None: high = len(arr) - 1\n    if low < high:\n        pivot_idx = partition(arr, low, high)\n        quicksort(arr, low, pivot_idx - 1)\n        quicksort(arr, pivot_idx + 1, high)\n    return arr\n\ndef partition(arr, low, high):\n    pivot = arr[high]\n    i = low - 1\n    for j in range(low, high):\n        if arr[j] <= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    arr[i+1], arr[high] = arr[high], arr[i+1]\n    return i + 1\n```\n\n## Complexity\n```\nBest:    O(n log n) — balanced partitions\nAverage: O(n log n)\nWorst:   O(n²) — already sorted (use random pivot)\nSpace:   O(log n) — recursion stack\n```\n\n## Three-Way QuickSort (Dutch National Flag)\n```python\ndef quicksort_3way(arr, low, high):\n    if low >= high: return\n    lt, gt = low, high\n    pivot = arr[low]\n    i = low + 1\n    while i <= gt:\n        if arr[i] < pivot:\n            arr[lt], arr[i] = arr[i], arr[lt]\n            lt += 1; i += 1\n        elif arr[i] > pivot:\n            arr[gt], arr[i] = arr[i], arr[gt]\n            gt -= 1\n        else:\n            i += 1\n    quicksort_3way(arr, low, lt - 1)\n    quicksort_3way(arr, gt + 1, high)\n```",
                        ["sorting", "quicksort", "divide-and-conquer"],
                        code_playground="def quicksort(arr):\n    if len(arr) <= 1: return arr\n    pivot = arr[len(arr)//2]\n    left = [x for x in arr if x < pivot]\n    mid = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + mid + quicksort(right)\n\nprint(quicksort([3,6,8,10,1,2,1]))"),
                    _article("algo_mergesort", "MergeSort & External Sorting",
                        "# MergeSort\n\n```python\ndef mergesort(arr):\n    if len(arr) <= 1: return arr\n    mid = len(arr) // 2\n    left = mergesort(arr[:mid])\n    right = mergesort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i]); i += 1\n        else:\n            result.append(right[j]); j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n```\n\n## Complexity\n```\nTime:  O(n log n) — always\nSpace: O(n) — merge buffer\nStable: Yes (preserves equal element order)\n```\n\n## External Merge Sort (for data > RAM)\n```\n1. Split file into chunks that fit in RAM\n2. Sort each chunk in memory, write to temp files\n3. K-way merge temp files using min-heap\n\nUsed by: Database query engines, hadoop MapReduce\n```\n\n```python\nimport heapq\n\ndef external_merge(sorted_files):\n    \"\"\"K-way merge of pre-sorted iterators.\"\"\"\n    heap = []\n    for i, f in enumerate(sorted_files):\n        val = next(f, None)\n        if val is not None:\n            heapq.heappush(heap, (val, i))\n    \n    while heap:\n        val, i = heapq.heappop(heap)\n        yield val\n        nxt = next(sorted_files[i], None)\n        if nxt is not None:\n            heapq.heappush(heap, (nxt, i))\n```",
                        ["sorting", "mergesort", "external-sort"]),
                    _article("algo_binary_search", "Binary Search Patterns",
                        "# Binary Search\n\n## Classic Binary Search\n```python\ndef binary_search(arr, target):\n    lo, hi = 0, len(arr) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return -1\n```\n\n## Find First/Last Occurrence\n```python\ndef first_occurrence(arr, target):\n    lo, hi, result = 0, len(arr)-1, -1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target:\n            result = mid\n            hi = mid - 1  # Keep searching left\n        elif arr[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return result\n\ndef last_occurrence(arr, target):\n    lo, hi, result = 0, len(arr)-1, -1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target:\n            result = mid\n            lo = mid + 1  # Keep searching right\n        elif arr[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return result\n```\n\n## Binary Search on Answer\n```python\n# Find minimum capacity to ship packages in D days\ndef ship_within_days(weights, days):\n    def can_ship(capacity):\n        d, current = 1, 0\n        for w in weights:\n            if current + w > capacity:\n                d += 1\n                current = 0\n            current += w\n        return d <= days\n    \n    lo, hi = max(weights), sum(weights)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if can_ship(mid): hi = mid\n        else: lo = mid + 1\n    return lo\n```",
                        ["binary-search", "searching"]),
                ]),
                _section("algo_graphs", "Graph Algorithms", [
                    _article("algo_dijkstra", "Dijkstra's Shortest Path",
                        "# Dijkstra's Algorithm\n\n```python\nimport heapq\nfrom collections import defaultdict\n\ndef dijkstra(graph, start):\n    distances = {node: float('inf') for node in graph}\n    distances[start] = 0\n    prev = {node: None for node in graph}\n    pq = [(0, start)]\n    visited = set()\n    \n    while pq:\n        dist, node = heapq.heappop(pq)\n        if node in visited: continue\n        visited.add(node)\n        \n        for neighbor, weight in graph[node]:\n            new_dist = dist + weight\n            if new_dist < distances[neighbor]:\n                distances[neighbor] = new_dist\n                prev[neighbor] = node\n                heapq.heappush(pq, (new_dist, neighbor))\n    \n    return distances, prev\n\ndef reconstruct_path(prev, start, end):\n    path = []\n    node = end\n    while node is not None:\n        path.append(node)\n        node = prev[node]\n    return path[::-1] if path[-1] == start else []\n\n# Usage\ngraph = {\n    'A': [('B', 4), ('C', 2)],\n    'B': [('D', 3), ('C', 1)],\n    'C': [('B', 1), ('D', 5)],\n    'D': []\n}\ndist, prev = dijkstra(graph, 'A')\nprint(f'A→D: {dist[\"D\"]}')  # 5\nprint(f'Path: {reconstruct_path(prev, \"A\", \"D\")}')  # [A, C, B, D]\n```\n\n## Complexity\n```\nTime:  O((V + E) log V) with min-heap\nSpace: O(V)\nConstraint: No negative edge weights\n```",
                        ["graphs", "dijkstra", "shortest-path"]),
                    _article("algo_union_find", "Union-Find (Disjoint Set)",
                        "# Union-Find\n\n```python\nclass UnionFind:\n    def __init__(self, n):\n        self.parent = list(range(n))\n        self.rank = [0] * n\n        self.components = n\n    \n    def find(self, x):\n        if self.parent[x] != x:\n            self.parent[x] = self.find(self.parent[x])  # Path compression\n        return self.parent[x]\n    \n    def union(self, x, y):\n        px, py = self.find(x), self.find(y)\n        if px == py: return False\n        # Union by rank\n        if self.rank[px] < self.rank[py]: px, py = py, px\n        self.parent[py] = px\n        if self.rank[px] == self.rank[py]: self.rank[px] += 1\n        self.components -= 1\n        return True\n    \n    def connected(self, x, y):\n        return self.find(x) == self.find(y)\n\n# Kruskal's MST\ndef kruskal(n, edges):\n    edges.sort(key=lambda e: e[2])  # Sort by weight\n    uf = UnionFind(n)\n    mst = []\n    total = 0\n    for u, v, w in edges:\n        if uf.union(u, v):\n            mst.append((u, v, w))\n            total += w\n    return total, mst\n```\n\n## Applications\n```\n- Minimum Spanning Tree (Kruskal's)\n- Network connectivity\n- Image segmentation\n- Cycle detection in undirected graphs\n- Percolation problems\n```",
                        ["union-find", "graphs", "mst"]),
                ]),
                _section("algo_dp", "Dynamic Programming", [
                    _article("algo_dp_patterns", "DP Problem Patterns",
                        "# DP Patterns\n\n## 1. Linear DP\n```python\n# Climbing Stairs: how many ways to reach step n?\ndef climb_stairs(n):\n    if n <= 2: return n\n    a, b = 1, 2\n    for _ in range(3, n+1):\n        a, b = b, a + b\n    return b\n\n# House Robber: max money without robbing adjacent\ndef rob(nums):\n    if not nums: return 0\n    prev2, prev1 = 0, 0\n    for num in nums:\n        prev2, prev1 = prev1, max(prev1, prev2 + num)\n    return prev1\n```\n\n## 2. Knapsack DP\n```python\n# 0/1 Knapsack\ndef knapsack(weights, values, capacity):\n    n = len(weights)\n    dp = [0] * (capacity + 1)\n    for i in range(n):\n        for w in range(capacity, weights[i]-1, -1):\n            dp[w] = max(dp[w], dp[w-weights[i]] + values[i])\n    return dp[capacity]\n\n# Unbounded Knapsack (Coin Change)\ndef coin_change(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin in coins:\n        for a in range(coin, amount + 1):\n            dp[a] = min(dp[a], dp[a-coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1\n```\n\n## 3. Grid DP\n```python\n# Unique Paths in m x n grid\ndef unique_paths(m, n):\n    dp = [[1]*n for _ in range(m)]\n    for i in range(1, m):\n        for j in range(1, n):\n            dp[i][j] = dp[i-1][j] + dp[i][j-1]\n    return dp[m-1][n-1]\n\n# Minimum Path Sum\ndef min_path_sum(grid):\n    m, n = len(grid), len(grid[0])\n    for i in range(m):\n        for j in range(n):\n            if i == 0 and j == 0: continue\n            elif i == 0: grid[i][j] += grid[i][j-1]\n            elif j == 0: grid[i][j] += grid[i-1][j]\n            else: grid[i][j] += min(grid[i-1][j], grid[i][j-1])\n    return grid[m-1][n-1]\n```\n\n## 4. String DP\n```python\n# Edit Distance (Levenshtein)\ndef edit_distance(s1, s2):\n    m, n = len(s1), len(s2)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0] = i\n    for j in range(n+1): dp[0][j] = j\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            if s1[i-1] == s2[j-1]:\n                dp[i][j] = dp[i-1][j-1]\n            else:\n                dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n    return dp[m][n]\n```",
                        ["dynamic-programming", "patterns"]),
                ]),
            ],
        },
        # ═══════════════════════════════════════════════════════════════
        # TESTING & QA BIBLE
        # ═══════════════════════════════════════════════════════════════
        {
            "id": "testing_bible", "name": "Testing & QA Bible", "icon": "checkmark-circle",
            "color": "#10B981", "total_hours": 720, "category": "bible",
            "description": "Complete testing from unit tests to E2E, performance, and chaos engineering.",
            "sections": [
                _section("test_unit", "Unit Testing", [
                    _article("test_pytest", "pytest Mastery",
                        "# pytest\n\n## Fixtures\n```python\nimport pytest\nfrom app.models import User, db\n\n@pytest.fixture\ndef app():\n    app = create_app('testing')\n    with app.app_context():\n        db.create_all()\n        yield app\n        db.drop_all()\n\n@pytest.fixture\ndef client(app):\n    return app.test_client()\n\n@pytest.fixture\ndef sample_user(app):\n    user = User(name='Test', email='test@test.com')\n    db.session.add(user)\n    db.session.commit()\n    return user\n\ndef test_get_user(client, sample_user):\n    resp = client.get(f'/api/users/{sample_user.id}')\n    assert resp.status_code == 200\n    assert resp.json['name'] == 'Test'\n```\n\n## Parametrize\n```python\n@pytest.mark.parametrize('input,expected', [\n    ('', False),\n    ('a', False),\n    ('ab', True),\n    ('abc@test.com', True),\n    ('no-at-sign', False),\n    ('double@@at.com', False),\n])\ndef test_validate_email(input, expected):\n    assert validate_email(input) == expected\n```\n\n## Mocking\n```python\nfrom unittest.mock import patch, MagicMock\n\n@patch('app.services.external_api.fetch')\ndef test_data_processing(mock_fetch):\n    mock_fetch.return_value = {'status': 'ok', 'data': [1,2,3]}\n    result = process_data()\n    assert result == 6\n    mock_fetch.assert_called_once()\n```",
                        ["testing", "pytest", "unit-test"]),
                    _article("test_jest", "Jest & React Testing",
                        "# Jest & React Testing Library\n\n## Component Testing\n```jsx\nimport { render, screen, fireEvent, waitFor } from '@testing-library/react';\nimport '@testing-library/jest-dom';\nimport UserForm from './UserForm';\n\ntest('submits form with user data', async () => {\n  const onSubmit = jest.fn();\n  render(<UserForm onSubmit={onSubmit} />);\n  \n  fireEvent.change(screen.getByLabelText(/name/i), {\n    target: { value: 'Alice' }\n  });\n  fireEvent.change(screen.getByLabelText(/email/i), {\n    target: { value: 'alice@test.com' }\n  });\n  fireEvent.click(screen.getByRole('button', { name: /submit/i }));\n  \n  await waitFor(() => {\n    expect(onSubmit).toHaveBeenCalledWith({\n      name: 'Alice',\n      email: 'alice@test.com'\n    });\n  });\n});\n\ntest('shows error for invalid email', () => {\n  render(<UserForm />);\n  fireEvent.change(screen.getByLabelText(/email/i), {\n    target: { value: 'invalid' }\n  });\n  fireEvent.click(screen.getByRole('button'));\n  expect(screen.getByText(/valid email/i)).toBeInTheDocument();\n});\n```\n\n## API Mocking with MSW\n```javascript\nimport { rest } from 'msw';\nimport { setupServer } from 'msw/node';\n\nconst server = setupServer(\n  rest.get('/api/users', (req, res, ctx) => {\n    return res(ctx.json([\n      { id: 1, name: 'Alice' },\n      { id: 2, name: 'Bob' }\n    ]));\n  })\n);\n\nbeforeAll(() => server.listen());\nafterEach(() => server.resetHandlers());\nafterAll(() => server.close());\n```",
                        ["testing", "jest", "react"]),
                ]),
                _section("test_integration", "Integration & E2E", [
                    _article("test_playwright", "Playwright E2E Testing",
                        "# Playwright\n\n```python\nfrom playwright.sync_api import sync_playwright\n\ndef test_login_flow():\n    with sync_playwright() as p:\n        browser = p.chromium.launch()\n        page = browser.new_page()\n        \n        page.goto('http://localhost:3000/login')\n        page.fill('[data-testid=email-input]', 'user@test.com')\n        page.fill('[data-testid=password-input]', 'password123')\n        page.click('[data-testid=login-button]')\n        \n        page.wait_for_url('**/dashboard')\n        assert page.text_content('h1') == 'Welcome back'\n        \n        # Screenshot for visual regression\n        page.screenshot(path='tests/screenshots/dashboard.png')\n        browser.close()\n```\n\n## Visual Regression\n```python\ndef test_homepage_visual():\n    page.goto('http://localhost:3000')\n    expect(page).to_have_screenshot('homepage.png', max_diff_pixels=100)\n```\n\n## API Testing\n```python\ndef test_api_crud():\n    context = browser.new_context()\n    \n    # Create\n    resp = context.request.post('/api/items', data={'name': 'Test'})\n    assert resp.status == 201\n    item_id = resp.json()['id']\n    \n    # Read\n    resp = context.request.get(f'/api/items/{item_id}')\n    assert resp.json()['name'] == 'Test'\n    \n    # Delete\n    resp = context.request.delete(f'/api/items/{item_id}')\n    assert resp.status == 200\n```",
                        ["e2e", "playwright", "visual-regression"]),
                ]),
            ],
        },
        # ═══════════════════════════════════════════════════════════════
        # PERFORMANCE & OPTIMIZATION BIBLE
        # ═══════════════════════════════════════════════════════════════
        {
            "id": "performance_bible", "name": "Performance Bible", "icon": "speedometer",
            "color": "#F59E0B", "total_hours": 800, "category": "bible",
            "description": "Master performance optimization from profiling to caching, concurrency, and memory management.",
            "sections": [
                _section("perf_profiling", "Profiling & Benchmarking", [
                    _article("perf_python", "Python Performance",
                        "# Python Performance\n\n## cProfile\n```python\nimport cProfile\nimport pstats\n\ndef profile(func):\n    def wrapper(*args, **kwargs):\n        profiler = cProfile.Profile()\n        profiler.enable()\n        result = func(*args, **kwargs)\n        profiler.disable()\n        stats = pstats.Stats(profiler).sort_stats('cumulative')\n        stats.print_stats(10)\n        return result\n    return wrapper\n\n@profile\ndef expensive_function():\n    return sum(i**2 for i in range(1_000_000))\n```\n\n## Memory Profiling\n```python\nfrom memory_profiler import profile\n\n@profile\ndef memory_heavy():\n    big_list = [i**2 for i in range(1_000_000)]  # ~8MB\n    big_dict = {i: i**2 for i in range(100_000)}  # ~5MB\n    return len(big_list) + len(big_dict)\n```\n\n## Optimization Techniques\n```python\n# 1. Use generators instead of lists\nsum(x**2 for x in range(10**6))  # Generator: O(1) memory\nsum([x**2 for x in range(10**6)])  # List: O(n) memory\n\n# 2. Use __slots__ for memory-efficient classes\nclass Point:\n    __slots__ = ('x', 'y')\n    def __init__(self, x, y): self.x, self.y = x, y\n\n# 3. Use numpy for numerical operations\nimport numpy as np\narr = np.arange(10**6)\nresult = np.sum(arr ** 2)  # 100x faster than pure Python\n\n# 4. Use functools.lru_cache\nfrom functools import lru_cache\n@lru_cache(maxsize=1024)\ndef fibonacci(n):\n    if n < 2: return n\n    return fibonacci(n-1) + fibonacci(n-2)\n```",
                        ["performance", "profiling", "python"]),
                ]),
                _section("perf_web", "Web Performance", [
                    _article("perf_frontend", "Frontend Performance",
                        "# Frontend Performance\n\n## Core Web Vitals\n```\nLCP (Largest Contentful Paint): < 2.5s\n  - Optimize images (WebP, lazy loading)\n  - Preload critical resources\n  - Use CDN\n\nFID (First Input Delay): < 100ms\n  - Break up long tasks\n  - Use web workers\n  - Defer non-critical JS\n\nCLS (Cumulative Layout Shift): < 0.1\n  - Set image dimensions\n  - Avoid inserting content above fold\n  - Use transform animations\n```\n\n## Bundle Optimization\n```javascript\n// Dynamic imports (code splitting)\nconst Dashboard = React.lazy(() => import('./Dashboard'));\n\n// Tree shaking\nimport { debounce } from 'lodash-es';  // Only imports debounce\n// NOT: import _ from 'lodash';  // Imports everything\n\n// Image optimization\n<Image\n  src=\"hero.webp\"\n  loading=\"lazy\"\n  decoding=\"async\"\n  srcSet=\"hero-400.webp 400w, hero-800.webp 800w\"\n  sizes=\"(max-width: 600px) 400px, 800px\"\n/>\n```\n\n## Caching Strategy\n```javascript\n// Service Worker\nself.addEventListener('fetch', event => {\n  event.respondWith(\n    caches.match(event.request)\n      .then(cached => cached || fetch(event.request)\n        .then(response => {\n          const clone = response.clone();\n          caches.open('v1').then(cache => cache.put(event.request, clone));\n          return response;\n        })\n      )\n  );\n});\n```",
                        ["web-performance", "core-web-vitals", "optimization"]),
                ]),
            ],
        },
        # ═══════════════════════════════════════════════════════════════
        # MOBILE DEVELOPMENT BIBLE
        # ═══════════════════════════════════════════════════════════════
        {
            "id": "mobile_bible", "name": "Mobile Development Bible", "icon": "phone-portrait",
            "color": "#EC4899", "total_hours": 1200, "category": "bible",
            "description": "Complete mobile development covering React Native, Flutter, Swift, and Kotlin.",
            "sections": [
                _section("mobile_rn", "React Native", [
                    _article("rn_architecture", "React Native Architecture",
                        "# React Native Architecture\n\n## New Architecture (Fabric + TurboModules)\n```\nOld: JS Thread ↔ Bridge (JSON) ↔ Native Thread\nNew: JS Thread ↔ JSI (C++) ↔ Native Thread\n\nBenefits:\n  - Synchronous native calls\n  - No serialization overhead\n  - Lazy module loading\n  - Concurrent rendering\n```\n\n## Performance Patterns\n```jsx\nimport { useMemo, useCallback, memo } from 'react';\nimport { FlatList } from 'react-native';\n\n// Memoize expensive renders\nconst Item = memo(({ title, onPress }) => (\n  <TouchableOpacity onPress={onPress}>\n    <Text>{title}</Text>\n  </TouchableOpacity>\n));\n\nfunction List({ data }) {\n  // Memoize callbacks\n  const renderItem = useCallback(({ item }) => (\n    <Item title={item.title} onPress={() => navigate(item.id)} />\n  ), []);\n\n  const keyExtractor = useCallback(item => item.id, []);\n\n  return (\n    <FlatList\n      data={data}\n      renderItem={renderItem}\n      keyExtractor={keyExtractor}\n      removeClippedSubviews={true}\n      maxToRenderPerBatch={10}\n      windowSize={5}\n      initialNumToRender={10}\n      getItemLayout={(data, index) => ({\n        length: 80, offset: 80 * index, index\n      })}\n    />\n  );\n}\n```\n\n## Navigation\n```jsx\nimport { createNativeStackNavigator } from '@react-navigation/native-stack';\nimport { createBottomTabNavigator } from '@react-navigation/bottom-tabs';\n\nconst Stack = createNativeStackNavigator();\nconst Tab = createBottomTabNavigator();\n\nfunction App() {\n  return (\n    <NavigationContainer>\n      <Stack.Navigator>\n        <Stack.Screen name=\"Auth\" component={AuthScreen} />\n        <Stack.Screen name=\"Main\" component={MainTabs} />\n      </Stack.Navigator>\n    </NavigationContainer>\n  );\n}\n```",
                        ["react-native", "mobile", "architecture"]),
                ]),
                _section("mobile_flutter", "Flutter", [
                    _article("flutter_arch", "Flutter Architecture",
                        "# Flutter Architecture\n\n## Widget Tree\n```dart\nclass MyApp extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      theme: ThemeData(useMaterial3: true),\n      home: const HomeScreen(),\n    );\n  }\n}\n\nclass HomeScreen extends StatefulWidget {\n  const HomeScreen({super.key});\n  @override\n  State<HomeScreen> createState() => _HomeScreenState();\n}\n\nclass _HomeScreenState extends State<HomeScreen> {\n  int _count = 0;\n  \n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      appBar: AppBar(title: const Text('Counter')),\n      body: Center(\n        child: Text('Count: $_count', style: Theme.of(context).textTheme.headlineLarge),\n      ),\n      floatingActionButton: FloatingActionButton(\n        onPressed: () => setState(() => _count++),\n        child: const Icon(Icons.add),\n      ),\n    );\n  }\n}\n```\n\n## State Management (Riverpod)\n```dart\nfinal counterProvider = StateNotifierProvider<CounterNotifier, int>((ref) {\n  return CounterNotifier();\n});\n\nclass CounterNotifier extends StateNotifier<int> {\n  CounterNotifier() : super(0);\n  void increment() => state++;\n  void decrement() => state--;\n}\n\nclass CounterWidget extends ConsumerWidget {\n  @override\n  Widget build(BuildContext context, WidgetRef ref) {\n    final count = ref.watch(counterProvider);\n    return Text('$count');\n  }\n}\n```",
                        ["flutter", "dart", "mobile"]),
                ]),
            ],
        },
        # ═══════════════════════════════════════════════════════════════
        # AI / MACHINE LEARNING BIBLE (Expanded)
        # ═══════════════════════════════════════════════════════════════
        {
            "id": "ml_bible_expanded", "name": "AI & Machine Learning Bible", "icon": "hardware-chip",
            "color": "#7C3AED", "total_hours": 2000, "category": "bible",
            "description": "Complete ML/AI from linear regression to transformers, LLMs, and deployment.",
            "sections": [
                _section("ml_foundations", "ML Foundations", [
                    _article("ml_linear_reg", "Linear Regression from Scratch",
                        "# Linear Regression\n\n## Math\n```\ny = wx + b\nLoss = (1/n) Σ(yi - ŷi)²  (MSE)\n\nGradient Descent:\n  w = w - α * ∂L/∂w\n  b = b - α * ∂L/∂b\n\nwhere:\n  ∂L/∂w = (-2/n) Σ xi(yi - ŷi)\n  ∂L/∂b = (-2/n) Σ (yi - ŷi)\n```\n\n## Implementation\n```python\nimport numpy as np\n\nclass LinearRegression:\n    def __init__(self, lr=0.01, epochs=1000):\n        self.lr = lr\n        self.epochs = epochs\n    \n    def fit(self, X, y):\n        n, m = X.shape\n        self.w = np.zeros(m)\n        self.b = 0\n        \n        for _ in range(self.epochs):\n            y_pred = X @ self.w + self.b\n            error = y_pred - y\n            \n            self.w -= self.lr * (2/n) * (X.T @ error)\n            self.b -= self.lr * (2/n) * np.sum(error)\n    \n    def predict(self, X):\n        return X @ self.w + self.b\n    \n    def score(self, X, y):\n        y_pred = self.predict(X)\n        ss_res = np.sum((y - y_pred)**2)\n        ss_tot = np.sum((y - np.mean(y))**2)\n        return 1 - ss_res / ss_tot  # R² score\n\n# Usage\nX = np.random.randn(100, 3)\ny = 3*X[:,0] + 2*X[:,1] - X[:,2] + np.random.randn(100)*0.1\n\nmodel = LinearRegression(lr=0.01, epochs=1000)\nmodel.fit(X, y)\nprint(f'R²: {model.score(X, y):.4f}')\nprint(f'Weights: {model.w}')\n```",
                        ["ml", "linear-regression", "gradient-descent"],
                        code_playground="import numpy as np\nX = np.random.randn(100, 2)\ny = 3*X[:,0] - 2*X[:,1] + np.random.randn(100)*0.1\nw = np.linalg.lstsq(X, y, rcond=None)[0]\nprint(f'Weights: {w}')"),
                    _article("ml_neural_net", "Neural Network from Scratch",
                        "# Neural Network\n\n```python\nimport numpy as np\n\nclass NeuralNetwork:\n    def __init__(self, layers):\n        self.weights = []\n        self.biases = []\n        for i in range(len(layers)-1):\n            w = np.random.randn(layers[i], layers[i+1]) * np.sqrt(2/layers[i])\n            b = np.zeros((1, layers[i+1]))\n            self.weights.append(w)\n            self.biases.append(b)\n    \n    def relu(self, x): return np.maximum(0, x)\n    def relu_deriv(self, x): return (x > 0).astype(float)\n    def sigmoid(self, x): return 1 / (1 + np.exp(-np.clip(x, -500, 500)))\n    \n    def forward(self, X):\n        self.activations = [X]\n        self.z_values = []\n        current = X\n        for i, (w, b) in enumerate(zip(self.weights, self.biases)):\n            z = current @ w + b\n            self.z_values.append(z)\n            if i < len(self.weights) - 1:\n                current = self.relu(z)\n            else:\n                current = self.sigmoid(z)\n            self.activations.append(current)\n        return current\n    \n    def backward(self, X, y, lr=0.01):\n        m = X.shape[0]\n        output = self.activations[-1]\n        delta = output - y  # BCE gradient\n        \n        for i in range(len(self.weights)-1, -1, -1):\n            dw = self.activations[i].T @ delta / m\n            db = np.sum(delta, axis=0, keepdims=True) / m\n            if i > 0:\n                delta = (delta @ self.weights[i].T) * self.relu_deriv(self.z_values[i-1])\n            self.weights[i] -= lr * dw\n            self.biases[i] -= lr * db\n    \n    def train(self, X, y, epochs=1000, lr=0.01):\n        for epoch in range(epochs):\n            output = self.forward(X)\n            self.backward(X, y, lr)\n            if epoch % 100 == 0:\n                loss = -np.mean(y*np.log(output+1e-8) + (1-y)*np.log(1-output+1e-8))\n                print(f'Epoch {epoch}: Loss={loss:.4f}')\n\n# XOR problem\nX = np.array([[0,0],[0,1],[1,0],[1,1]])\ny = np.array([[0],[1],[1],[0]])\n\nnn = NeuralNetwork([2, 8, 4, 1])\nnn.train(X, y, epochs=2000, lr=0.5)\nprint('Predictions:', nn.forward(X).round(2).flatten())\n```",
                        ["neural-network", "deep-learning", "backpropagation"]),
                ]),
                _section("ml_transformers", "Transformers & LLMs", [
                    _article("ml_attention", "Attention Mechanism",
                        "# Self-Attention\n\n## Scaled Dot-Product Attention\n```python\nimport numpy as np\n\ndef attention(Q, K, V, mask=None):\n    \"\"\"Scaled dot-product attention.\"\"\"\n    d_k = Q.shape[-1]\n    scores = Q @ K.transpose(-2, -1) / np.sqrt(d_k)\n    if mask is not None:\n        scores = np.where(mask == 0, -1e9, scores)\n    weights = softmax(scores, axis=-1)\n    return weights @ V\n\ndef softmax(x, axis=-1):\n    e_x = np.exp(x - np.max(x, axis=axis, keepdims=True))\n    return e_x / np.sum(e_x, axis=axis, keepdims=True)\n\n# Multi-Head Attention\nclass MultiHeadAttention:\n    def __init__(self, d_model, num_heads):\n        self.num_heads = num_heads\n        self.d_k = d_model // num_heads\n        self.W_q = np.random.randn(d_model, d_model) * 0.02\n        self.W_k = np.random.randn(d_model, d_model) * 0.02\n        self.W_v = np.random.randn(d_model, d_model) * 0.02\n        self.W_o = np.random.randn(d_model, d_model) * 0.02\n    \n    def split_heads(self, x):\n        batch_size, seq_len, d_model = x.shape\n        return x.reshape(batch_size, seq_len, self.num_heads, self.d_k).transpose(0, 2, 1, 3)\n    \n    def forward(self, x, mask=None):\n        Q = x @ self.W_q\n        K = x @ self.W_k\n        V = x @ self.W_v\n        \n        Q = self.split_heads(Q)\n        K = self.split_heads(K)\n        V = self.split_heads(V)\n        \n        attn_output = attention(Q, K, V, mask)\n        # Concat heads\n        attn_output = attn_output.transpose(0, 2, 1, 3).reshape(x.shape)\n        return attn_output @ self.W_o\n```\n\n## Transformer Architecture\n```\nInput → Embedding + Positional Encoding\n  → [Multi-Head Attention → Add & Norm → FFN → Add & Norm] × N\n  → Output\n\nEncoder: Bidirectional attention (BERT)\nDecoder: Causal (masked) attention (GPT)\n```",
                        ["transformers", "attention", "llm"]),
                ]),
            ],
        },
    ]
