"""
╔══════════════════════════════════════════════════════════════════════════╗
║  ROSETTA WAVE 14 — HYPERSCALE EXPANSION                                  ║
║  smart_pointers | lazy_evaluation | union_intersection_types |          ║
║  static_analysis                                                         ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

EXPANDED_V14 = {}

EXPANDED_V14["smart_pointers"] = {
    "C++": "#include <memory>\n#include <iostream>\n\n// Unique pointer (exclusive ownership)\nstd::unique_ptr<int> uptr = std::make_unique<int>(42);\n// Cannot copy: auto uptr2 = uptr; // Error\nauto uptr2 = std::move(uptr);      // Transfer ownership\n\n// Shared pointer (reference counting)\nstd::shared_ptr<int> sptr1 = std::make_shared<int>(100);\nstd::shared_ptr<int> sptr2 = sptr1; // Ref count = 2\nstd::cout << sptr1.use_count();     // 2\n\n// Weak pointer (breaks cycles)\nstd::weak_ptr<int> wptr = sptr1;\nif (auto locked = wptr.lock()) {\n    std::cout << *locked;\n}",
    "Rust": "// Box (unique ownership on heap)\nlet b = Box::new(42);\n\n// Rc (Reference counted, single threaded)\nuse std::rc::Rc;\nlet rc1 = Rc::new(100);\nlet rc2 = Rc::clone(&rc1); // Ref count = 2\nprintln!(\"{}\", Rc::strong_count(&rc1));\n\n// Arc (Atomic reference counted, multi-threaded)\nuse std::sync::Arc;\nlet arc = Arc::new(200);\n\n// RefCell / Mutex (Interior mutability)\nuse std::cell::RefCell;\nlet shared_mut = Rc::new(RefCell::new(5));\n*shared_mut.borrow_mut() += 1;",
    "Go": "// Go uses garbage collection. No manual smart pointers.\n// new() and & return regular pointers to heap/stack.\np := new(int)\n*p = 42\n\n// Sync package for concurrency\nimport \"sync\"\nvar mu sync.Mutex\nmu.Lock()\n*p++\nmu.Unlock()",
    "Java": "// Java relies on Garbage Collection.\n// Closest equivalents are Reference classes for GC interaction.\nimport java.lang.ref.*;\n\nObject obj = new Object();\n// WeakReference (won't prevent GC)\nWeakReference<Object> weak = new WeakReference<>(obj);\n\n// SoftReference (cleared on memory pressure)\nSoftReference<Object> soft = new SoftReference<>(obj);\n\nobj = null; // Eligible for collection if only weak/soft refs exist",
    "C#": "// C# uses Garbage Collection for objects (classes).\n// Memory<T> and Span<T> for safe memory views (C# 7+)\nint[] arr = {1, 2, 3};\nSpan<int> span = arr.AsSpan(1, 2);\n\n// WeakReference\nWeakReference<object> weak = new WeakReference<object>(new object());\nif (weak.TryGetTarget(out object target)) {\n    Console.WriteLine(\"Still alive\");\n}",
    "Python": "# Python is reference-counted with a cycle detector.\n# weakref module provides weak pointers.\nimport weakref\n\nclass Data:\n    def __init__(self, val): self.val = val\n\nd = Data(42)\nref = weakref.ref(d)\n\nprint(ref().val)  # 42\nd = None\nprint(ref())      # None (collected)",
    "JavaScript": "// JS has Garbage Collection.\n// WeakMap and WeakSet for weak references to objects.\nlet obj = { x: 42 };\nconst weakMap = new WeakMap();\nweakMap.set(obj, \"metadata\");\n\n// WeakRef (ES2021)\nconst weakRef = new WeakRef(obj);\nlet target = weakRef.deref(); // returns object or undefined\nobj = null; // Now eligible for GC",
    "Swift": "// Swift uses Automatic Reference Counting (ARC).\nclass Person { var name = \"Alice\" }\nvar p1: Person? = Person()\nvar p2 = p1 // Ref count = 2\n\n// Weak reference (breaks retain cycles, must be optional var)\nweak var p3 = p1\n\n// Unowned reference (assumes target outlives reference)\n// unowned let p4 = p1\n\np1 = nil\np2 = nil // Deallocated here"
}

EXPANDED_V14["lazy_evaluation"] = {
    "Haskell": "-- Haskell is lazily evaluated by default\n-- Infinite lists\nones = repeat 1\n-- Take first 5 (computes only what's needed)\nfirstFive = take 5 ones\n\n-- Fibonacci sequence\nfibs = 0 : 1 : zipWith (+) fibs (tail fibs)\nprint (take 10 fibs)",
    "Python": "# Generators provide lazy sequences\ndef infinite_ones():\n    while True:\n        yield 1\n\n# itertools for lazy operations\nimport itertools\nones = infinite_ones()\nfirst_five = list(itertools.islice(ones, 5))\n\n# Lazy evaluation of boolean operators (short-circuiting)\nresult = True or some_expensive_function()",
    "JavaScript": "// Generator functions\nfunction* infiniteOnes() {\n  while (true) yield 1;\n}\n\n// Short-circuiting\nconst result = true || expensiveFn();\n\n// Lazy initialization pattern\nlet _cache;\nfunction getLazy() {\n  if (!_cache) _cache = compute();\n  return _cache;\n}",
    "Scala": "// Lazy vals (computed once on first access)\nlazy val expensive = {\n  println(\"Computing...\")\n  42\n}\n\n// LazyList (Stream in older Scala) for infinite sequences\nval ones: LazyList[Int] = 1 #:: ones\nval firstFive = ones.take(5).toList\n\n// Call-by-name parameters (evaluated every time they are used)\ndef myWhile(cond: => Boolean)(body: => Unit): Unit = {\n  if (cond) { body; myWhile(cond)(body) }\n}",
    "C#": "// Lazy<T> class\nLazy<ExpensiveObj> lazyObj = new Lazy<ExpensiveObj>(() => new ExpensiveObj());\n// Creation happens here:\nExpensiveObj obj = lazyObj.Value;\n\n// IEnumerable/yield return is inherently lazy\nIEnumerable<int> InfiniteOnes() {\n    while (true) yield return 1;\n}",
    "Kotlin": "// Lazy delegates (Thread-safe by default)\nval expensive: Int by lazy {\n    println(\"Computing...\")\n    42\n}\n\n// Sequences (Lazy collections)\nval fibs = generateSequence(Pair(0, 1)) { Pair(it.second, it.first + it.second) }\n    .map { it.first }\n    .take(10)\n    .toList()",
    "Swift": "// Lazy properties (Computed once on first access)\nclass Manager {\n    lazy var expensiveData: [String] = loadData()\n}\n\n// Lazy sequences\nlet numbers = 1...1000\nlet lazySquares = numbers.lazy.map { $0 * $0 }\n// Not computed until accessed\nprint(lazySquares[0])",
    "Ruby": "# Enumerator::Lazy\n# Normal map creates intermediate arrays\n# Lazy avoids them\n(1..Float::INFINITY).lazy\n  .map { |x| x * x }\n  .select { |x| x.even? }\n  .first(5)\n\n# Conditional assignment (memoization)\ndef expensive_data\n  @data ||= compute_data()\nend"
}

EXPANDED_V14["union_intersection_types"] = {
    "TypeScript": "// Union types (A OR B)\ntype ID = string | number;\nfunction printId(id: ID) {\n  if (typeof id === \"string\") console.log(id.toUpperCase());\n  else console.log(id.toFixed(2));\n}\n\n// Intersection types (A AND B)\ninterface ErrorHandling { success: boolean; error?: string }\ninterface ArtworksData { artworks: { title: string }[] }\n\ntype ArtworksResponse = ArtworksData & ErrorHandling;\nconst response: ArtworksResponse = { success: true, artworks: [] };",
    "Python": "from typing import Union, Optional\n# Python 3.10+ Union syntax\nID = str | int\n\ndef process(id: ID):\n    if isinstance(id, str): return id.upper()\n    return id + 1\n\n# Intersection is not natively supported in typing (except via Protocols/Multiple Inheritance)\n# Or using typing.Intersection (proposed in PEP but not yet standard)\nclass Runnable:\n    def run(self): pass\nclass Stoppable:\n    def stop(self): pass",
    "Rust": "// Rust doesn't have open unions, uses Enums (Tagged Unions/Sum Types)\nenum ID {\n    Text(String),\n    Number(i32),\n}\n\nfn process(id: ID) {\n    match id {\n        ID::Text(s) => println!(\"{}\", s.to_uppercase()),\n        ID::Number(n) => println!(\"{}\", n + 1),\n    }\n}\n\n// Trait bounds acting like intersection types\nfn handle_both<T: Runnable + Stoppable>(item: &T) {\n    item.run();\n    item.stop();\n}",
    "C++": "// std::variant (C++17 Tagged Union)\n#include <variant>\n#include <string>\n\nstd::variant<int, std::string> id = 42;\nid = \"user123\";\n\n// Access via std::visit (Pattern matching)\nstd::visit([](auto&& arg) {\n    std::cout << arg << '\\n';\n}, id);\n\n// Multiple inheritance (Intersection-like)\nclass Runnable { virtual void run() = 0; };\nclass Stoppable { virtual void stop() = 0; };\nclass Task : public Runnable, public Stoppable { /* ... */ };",
    "Java": "// Java doesn't have true union types.\n// Exceptions can use a multi-catch block (union-like syntax)\ntry {\n    // ...\n} catch (IOException | SQLException e) {\n    e.printStackTrace();\n}\n\n// Intersection types in Generics (bounds)\npublic <T extends Runnable & AutoCloseable> void process(T item) {\n    item.run();\n    try { item.close(); } catch (Exception e) {}\n}",
    "C#": "// No union types. Uses object, dynamic, or discriminated union libraries (OneOf<T0, T1>)\n// Or Pattern Matching with switch expressions\nstring Process(object id) => id switch {\n    string s => s.ToUpper(),\n    int n => (n + 1).ToString(),\n    _ => throw new ArgumentException()\n};\n\n// Intersection via multiple interface constraints\nvoid Process<T>(T item) where T : IRunnable, IStoppable {\n    item.Run();\n    item.Stop();\n}",
    "PHP": "// Union Types (PHP 8.0+)\nfunction process(string|int $id): string|int {\n    if (is_string($id)) return strtoupper($id);\n    return $id + 1;\n}\n\n// Intersection Types (PHP 8.1+)\nfunction handle(Runnable&Stoppable $item) {\n    $item->run();\n    $item->stop();\n}\n\n// DNF Types (PHP 8.2+) - Disjunctive Normal Form\n// (A&B)|C",
    "Scala": "// Union types (Scala 3)\ntype ID = String | Int\ndef process(id: ID): Unit = id match {\n  case s: String => println(s.toUpperCase)\n  case i: Int => println(i + 1)\n}\n\n// Intersection types (Scala 3)\ntrait Resettable { def reset(): Unit }\ntrait Growable[T] { def add(x: T): Unit }\n\ndef f(x: Resettable & Growable[String]) = {\n  x.reset()\n  x.add(\"first\")\n}"
}

EXPANDED_V14["static_analysis"] = {
    "Python": "# Python is dynamic, but tools provide static analysis:\n# - mypy, pyright (Type checking)\n# - pylint, flake8 (Linting)\n# - black, ruff (Formatting/Linting)\n\ndef add(a: int, b: int) -> int:\n    return a + b\n\n# mypy will flag this:\n# result = add(1, \"2\")",
    "JavaScript": "// JS uses ESLint for static analysis\n// TypeScript adds compiler-level static type checking\n\n/** @type {number} */\nlet x = 42;\n\n// JSDoc can be used by TS server to check standard JS files\n/**\n * @param {number} a\n * @param {number} b\n * @returns {number}\n */\nfunction add(a, b) { return a + b; }",
    "Rust": "// Rust compiler (rustc) has aggressive static analysis built-in\n// (Borrow checker, lifetimes, mutability tracking)\n// Clippy provides additional lints\n// #[warn(clippy::all)]\n// #[deny(clippy::pedantic)]\n\nfn main() {\n    let mut x = 5;\n    let y = &mut x;\n    // let z = &mut x; // Rustc error: cannot borrow twice mutably\n}",
    "Go": "// 'go vet' is built-in for suspicious constructs\n// 'staticcheck' and 'golangci-lint' are popular external tools\n\nfunc main() {\n    fmt.Printf(\"%d\\n\") // go vet warns: missing argument for %d\n    \n    // Unused variables are compile errors in Go\n    // unused := 42\n}",
    "Java": "// Java is strongly typed.\n// Additional static analysis:\n// - SonarQube, Checkstyle, PMD\n// - ErrorProne, SpotBugs\n\n@SuppressWarnings(\"unchecked\")\npublic void method() {\n    // Suppress compiler warnings\n}",
    "C#": "// Roslyn compiler provides deep static analysis\n// Analyzers can be added via NuGet packages\n\n#pragma warning disable CS0168 // Disable \"variable declared but never used\"\nint unused;\n#pragma warning restore CS0168",
    "C++": "// clang-tidy and cppcheck for C++ codebases\n// Static analyzers find memory leaks, use-after-free, etc.\n\nint* ptr = new int(10);\n// cppcheck warns: Memory leak: ptr\n\n// [[nodiscard]] attribute forces caller to use result\n[[nodiscard]] int get_status() { return 0; }",
    "Ruby": "# RuboCop is the standard static analyzer/linter for Ruby\n# Sorbet provides static type checking\n# typed: true\n\nextend T::Sig\n\nsig { params(a: Integer, b: Integer).returns(Integer) }\ndef add(a, b)\n  a + b\nend"
}
