"""
╔══════════════════════════════════════════════════════════════════════════╗
║  ROSETTA WAVE 7+8 — 8 CONCEPTS × 30 CORE LANGUAGES                     ║
║  decorators_annotations | logging | error_types | channels_messaging |   ║
║  web_server | file_parsing | functional_patterns | scope_lifetime        ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

EXPANDED_V7 = {}

EXPANDED_V7["decorators_annotations"] = {
    "Python": "import functools\n\n# Function decorator\ndef log_calls(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        print(f'Calling {func.__name__}({args}, {kwargs})')\n        result = func(*args, **kwargs)\n        print(f'{func.__name__} returned {result}')\n        return result\n    return wrapper\n\n@log_calls\ndef add(a, b): return a + b\n\n# Decorator with arguments\ndef retry(max_attempts=3):\n    def decorator(func):\n        @functools.wraps(func)\n        def wrapper(*args, **kwargs):\n            for i in range(max_attempts):\n                try: return func(*args, **kwargs)\n                except Exception as e:\n                    if i == max_attempts - 1: raise\n        return wrapper\n    return decorator\n\n@retry(max_attempts=5)\ndef fetch(url): pass\n\n# Class decorator\ndef singleton(cls):\n    instances = {}\n    def get_instance(*args, **kwargs):\n        if cls not in instances:\n            instances[cls] = cls(*args, **kwargs)\n        return instances[cls]\n    return get_instance\n\n# Property decorator\nclass Circle:\n    def __init__(self, r): self._r = r\n    @property\n    def area(self): return 3.14159 * self._r ** 2",
    "TypeScript": "// Method decorators (Stage 3)\nfunction log(target: any, key: string, desc: PropertyDescriptor) {\n  const original = desc.value;\n  desc.value = function(...args: any[]) {\n    console.log(`Calling ${key}(${args})`);\n    return original.apply(this, args);\n  };\n}\n\nclass Calculator {\n  @log\n  add(a: number, b: number) { return a + b; }\n}\n\n// Class decorator\nfunction sealed(constructor: Function) {\n  Object.seal(constructor);\n  Object.seal(constructor.prototype);\n}\n\n// Parameter decorator\nfunction required(target: any, key: string, index: number) {\n  // Mark parameter as required\n}\n\n// Property decorator\nfunction readonly(target: any, key: string) {\n  Object.defineProperty(target, key, { writable: false });\n}",
    "Java": "// Annotations\nimport java.lang.annotation.*;\n\n@Retention(RetentionPolicy.RUNTIME)\n@Target(ElementType.METHOD)\n@interface Benchmark {\n    int warmup() default 3;\n    int iterations() default 10;\n}\n\n@Retention(RetentionPolicy.RUNTIME)\n@Target(ElementType.TYPE)\n@interface Entity {\n    String table();\n}\n\n// Usage\n@Entity(table = \"users\")\nclass User {\n    @Benchmark(warmup = 5)\n    public void processData() { }\n\n    @Deprecated(since = \"2.0\", forRemoval = true)\n    public void oldMethod() { }\n\n    @Override\n    public String toString() { return \"User\"; }\n\n    @SuppressWarnings(\"unchecked\")\n    public void riskyMethod() { }\n}",
    "Rust": "// Derive macros\n#[derive(Debug, Clone, PartialEq, Eq, Hash)]\nstruct Point { x: i32, y: i32 }\n\n// Attribute macros\n#[cfg(test)]\nmod tests {\n    #[test]\n    fn it_works() { assert_eq!(2 + 2, 4); }\n\n    #[test]\n    #[should_panic(expected = \"overflow\")]\n    fn test_overflow() { panic!(\"overflow\"); }\n}\n\n// Conditional compilation\n#[cfg(target_os = \"linux\")]\nfn linux_only() { }\n\n#[cfg(feature = \"serde\")]\n#[derive(Serialize, Deserialize)]\nstruct Config { name: String }\n\n// Inline hints\n#[inline(always)]\nfn hot_function() { }\n\n#[deprecated(since = \"2.0\", note = \"Use new_function instead\")]\nfn old_function() { }\n\n// Custom derive (proc macro)\n// #[derive(MyTrait)]",
    "C#": "// Attributes\n[Serializable]\n[Obsolete(\"Use NewClass instead\", error: true)]\nclass OldClass { }\n\n// Custom attribute\n[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]\nclass RouteAttribute : Attribute {\n    public string Path { get; }\n    public RouteAttribute(string path) => Path = path;\n}\n\nclass Controller {\n    [Route(\"/api/users\")]\n    [HttpGet]\n    public IActionResult GetUsers() => Ok();\n\n    [Conditional(\"DEBUG\")]\n    void DebugLog(string msg) => Console.WriteLine(msg);\n}\n\n// Caller info\nvoid Log(string msg,\n    [CallerMemberName] string member = \"\",\n    [CallerFilePath] string file = \"\",\n    [CallerLineNumber] int line = 0) { }",
    "Kotlin": "// Annotations\n@Target(AnnotationTarget.FUNCTION)\n@Retention(AnnotationRetention.RUNTIME)\nannotation class Benchmark(val iterations: Int = 10)\n\n@Target(AnnotationTarget.CLASS)\nannotation class Entity(val table: String)\n\n@Entity(table = \"users\")\ndata class User(val name: String, val age: Int)\n\nclass Service {\n    @Benchmark(iterations = 100)\n    fun process() { }\n\n    @Deprecated(\"Use newMethod\", ReplaceWith(\"newMethod()\"))\n    fun oldMethod() { }\n\n    @JvmStatic\n    @JvmOverloads\n    fun create(name: String, age: Int = 0) = User(name, age)\n}",
    "Swift": "// Property wrappers (decorators)\n@propertyWrapper\nstruct Clamped {\n    var wrappedValue: Int {\n        didSet { wrappedValue = min(max(wrappedValue, range.lowerBound), range.upperBound) }\n    }\n    let range: ClosedRange<Int>\n    init(wrappedValue: Int, _ range: ClosedRange<Int>) {\n        self.range = range\n        self.wrappedValue = min(max(wrappedValue, range.lowerBound), range.upperBound)\n    }\n}\n\nstruct Player {\n    @Clamped(0...100) var health: Int = 100\n    @Clamped(0...999) var score: Int = 0\n}\n\n// Available\n@available(iOS 15, *)\nfunc newFeature() { }\n\n// @discardableResult\n@discardableResult\nfunc insert(_ item: String) -> Bool { true }",
    "Go": "// Go doesn't have decorators/annotations\n// Uses struct tags and conventions\n\ntype User struct {\n    Name  string `json:\"name\" validate:\"required\"`\n    Email string `json:\"email\" validate:\"email\"`\n    Age   int    `json:\"age,omitempty\" validate:\"min=0,max=150\"`\n}\n\n// Read tags via reflection\nimport \"reflect\"\nt := reflect.TypeOf(User{})\nfield, _ := t.FieldByName(\"Name\")\ntag := field.Tag.Get(\"json\")  // \"name\"\nvalidate := field.Tag.Get(\"validate\")  // \"required\"\n\n// go:generate for code generation\n//go:generate stringer -type=Color\n//go:embed config.json\nvar configJSON []byte",
    "C++": "// C++ attributes\n[[nodiscard]] int compute() { return 42; }\n[[deprecated(\"Use newFunc\")]] void oldFunc() { }\n[[maybe_unused]] int debug_var = 0;\n[[noreturn]] void fatal() { std::terminate(); }\n[[fallthrough]]  // In switch\n[[likely]] [[unlikely]]  // Branch hints (C++20)\n\n// Custom annotations via macros\n#define BENCHMARK __attribute__((noinline))\n#define PACKED __attribute__((packed))\n#define ALIGNED(n) __attribute__((aligned(n)))\n\nBENCHMARK void hotFunction() { }\n\nstruct PACKED PackedStruct {\n    char a;\n    int b;\n};",
    "PHP": "// PHP 8 Attributes\n#[Attribute(Attribute::TARGET_METHOD)]\nclass Route {\n    public function __construct(\n        public string $path,\n        public string $method = 'GET'\n    ) {}\n}\n\nclass Controller {\n    #[Route('/api/users', method: 'GET')]\n    public function listUsers(): array { return []; }\n\n    #[Route('/api/users', method: 'POST')]\n    public function createUser(): void { }\n\n    #[Deprecated('Use newMethod() instead')]\n    public function oldMethod(): void { }\n}\n\n// Read attributes via reflection\n$ref = new ReflectionMethod(Controller::class, 'listUsers');\n$attrs = $ref->getAttributes(Route::class);\n$route = $attrs[0]->newInstance();",
    "Ruby": "# Ruby doesn't have built-in decorators\n# But you can create them with metaprogramming\n\nmodule Decorators\n  def self.log(method_name)\n    original = instance_method(method_name)\n    define_method(method_name) do |*args|\n      puts \"Calling #{method_name}(#{args})\"\n      result = original.bind(self).call(*args)\n      puts \"#{method_name} returned #{result}\"\n      result\n    end\n  end\nend\n\nclass Calculator\n  extend Decorators\n  def add(a, b) = a + b\n  log :add\nend\n\n# Method added hook\nclass Base\n  def self.method_added(name)\n    puts \"Method added: #{name}\"\n  end\nend",
    "Scala": "// Annotations\nimport scala.annotation._\n\n@deprecated(\"Use newMethod\", \"2.0\")\ndef oldMethod(): Unit = {}\n\n@tailrec\ndef factorial(n: Int, acc: Int = 1): Int =\n  if (n <= 1) acc else factorial(n - 1, n * acc)\n\n@inline\ndef hot(x: Int): Int = x * 2\n\n// Custom annotation\nclass benchmark(iterations: Int = 10) extends StaticAnnotation\n\n@benchmark(100)\ndef process(): Unit = {}",
    "Elixir": "# Module attributes as annotations\ndefmodule MyModule do\n  @moduledoc \"My documented module\"\n  @doc \"Adds two numbers\"\n  @spec add(number(), number()) :: number()\n  def add(a, b), do: a + b\n\n  @deprecated \"Use new_function/1 instead\"\n  def old_function(x), do: x\n\n  # Compile-time attributes\n  @behaviour GenServer\n  @impl true\n  def init(state), do: {:ok, state}\nend\n\n# Custom decorator-like with macros\ndefmodule Benchmark do\n  defmacro __using__(_) do\n    quote do\n      import Benchmark\n    end\n  end\nend",
    "Haskell": "-- Pragmas (compiler directives)\n{-# LANGUAGE OverloadedStrings #-}\n{-# LANGUAGE DeriveGeneric #-}\n{-# INLINE hotFunction #-}\n{-# NOINLINE coldFunction #-}\n{-# DEPRECATED oldFunction \"Use newFunction\" #-}\n{-# MINIMAL methodA, (methodB | methodC) #-}\n\n-- Deriving\ndata Color = Red | Green | Blue\n  deriving (Show, Eq, Ord, Enum, Bounded, Generic)\n\n-- DerivingVia\nderiving via (Sum Int) instance Semigroup MyType\n\n-- ANN (arbitrary annotations)\n{-# ANN module \"HLint: ignore\" #-}",
    "Nim": "# Pragmas\nproc hotFunction() {.inline.} = discard\nproc oldFunction() {.deprecated: \"Use newFunction\".} = discard\nproc pureFunc(x: int): int {.noSideEffect.} = x * 2\nproc cFunc() {.exportc, cdecl.} = discard\n\n# Custom pragma\ntemplate benchmark(body: untyped) =\n  let start = cpuTime()\n  body\n  echo \"Took: \", cpuTime() - start, \"s\"\n\nbenchmark:\n  for i in 0..1000000: discard i * i",
    "Crystal": "# Annotations\nannotation Benchmark\nannotation Route\n\n@[Route(path: \"/api/users\")]\nclass UsersController\n  @[Benchmark]\n  def index\n    # ...\n  end\nend\n\n# Read at compile time\n{% for method in UsersController.methods %}\n  {% if method.annotation(Benchmark) %}\n    puts {{method.name.stringify}}\n  {% end %}\n{% end %}",
    "Dart": "// Annotations\nclass Route {\n  final String path;\n  final String method;\n  const Route(this.path, {this.method = 'GET'});\n}\n\nclass Deprecated {\n  final String message;\n  const Deprecated(this.message);\n}\n\nclass Controller {\n  @Route('/api/users')\n  List<Map> listUsers() => [];\n\n  @Route('/api/users', method: 'POST')\n  void createUser() {}\n\n  @Deprecated('Use newMethod instead')\n  @override\n  String toString() => 'Controller';\n}",
    "Clojure": ";; Metadata (Clojure's annotations)\n(defn ^:deprecated old-fn [] nil)\n\n(defn ^{:doc \"Adds numbers\" :added \"1.0\"}\n  add [a b] (+ a b))\n\n;; Read metadata\n(meta #'add)  ;; {:doc \"Adds numbers\", :added \"1.0\", ...}\n\n;; Custom metadata\n(defn ^{:benchmark true :iterations 100}\n  process [] nil)\n\n;; Type hints\n(defn fast-add ^long [^long a ^long b] (+ a b))",
    "Julia": "# Macros as decorators\nmacro benchmark(expr)\n    quote\n        t = @elapsed result = $(esc(expr))\n        println(\"Took: \", t, \"s\")\n        result\n    end\nend\n\n@benchmark sum(rand(1000000))\n\n# Built-in macros\n@inline function hot(x) x * 2 end\n@noinline function cold(x) x * 2 end\n@deprecate old_function new_function\n\n# Doc strings\n\"\"\"Compute the area of a circle.\"\"\"\nfunction area(r) pi * r^2 end",
    "Lua": "-- Lua has no decorators\n-- Simulate with wrapper functions\nlocal function log_calls(fn)\n    return function(...)\n        print('Calling function')\n        local result = fn(...)\n        print('Returned:', result)\n        return result\n    end\nend\n\nlocal add = log_calls(function(a, b) return a + b end)\nadd(3, 4)",
    "Perl": "# Perl attributes\nuse attributes;\n\nsub my_method : lvalue { }  # Built-in attribute\n\n# Attribute::Handlers\nuse Attribute::Handlers;\nsub Benchmark : ATTR(CODE) {\n    my ($pkg, $sym, $code) = @_;\n    # Wrap the code\n}\n\nsub process : Benchmark { }",
    "OCaml": "(* PPX attributes *)\nlet[@inline always] hot_function x = x * 2\nlet[@deprecated \"Use new_function\"] old_function x = x\n\n(* Deriving *)\ntype color = Red | Green | Blue [@@deriving show, eq, ord]\n\n(* Alert *)\nval old_api : unit -> unit [@@alert deprecated \"Use new API\"]",
    "F#": "// Attributes\n[<Obsolete(\"Use newFunction\")>]\nlet oldFunction () = ()\n\n[<Literal>]\nlet MaxSize = 100\n\n[<EntryPoint>]\nlet main argv = 0\n\n// Custom attribute\n[<AttributeUsage(AttributeTargets.Method)>]\ntype BenchmarkAttribute(iterations: int) =\n    inherit Attribute()\n    member _.Iterations = iterations\n\ntype Service() =\n    [<Benchmark(100)>]\n    member _.Process() = ()",
    "Erlang": "%% Module attributes\n-module(my_module).\n-author(\"Alice\").\n-vsn(\"1.0\").\n-deprecated([{old_function, 1}]).\n-export([new_function/1]).\n\n-spec add(number(), number()) -> number().\nadd(A, B) -> A + B.\n\n-callback init(term()) -> {ok, term()}.",
    "Zig": "// Zig doesn't have decorators\n// Uses built-in functions and comptime\nfn hotFunction(x: i32) i32 {\n    @setRuntimeSafety(false);  // Disable bounds checking\n    return x * 2;\n}\n\n// Export\nexport fn publicApi() void {}\n\n// Inline\ninline fn alwaysInlined() void {}",
    "Racket": ";; Contracts (like decorators for correctness)\n(provide (contract-out\n  [add (-> number? number? number?)]))\n\n(define/contract (add a b)\n  (-> number? number? number?)\n  (+ a b))\n\n;; Module-level annotations\n(module+ test\n  (check-equal? (add 1 2) 3))",
    "D": "// User-defined attributes\nenum Benchmark;\nenum Route(string path);\n\n@Benchmark @Route(\"/api/users\")\nvoid listUsers() { }\n\n// Built-in\n@safe void safeFunc() { }\n@nogc int pureCalc(int x) { return x * 2; }\n@deprecated(\"Use newFunc\") void oldFunc() { }\n\n// Read at compile time\nstatic foreach (attr; __traits(getAttributes, listUsers)) {\n    pragma(msg, attr.stringof);\n}",
    "R": "# R doesn't have decorators\n# Use function wrappers\nlog_calls <- function(fn) {\n  function(...) {\n    cat('Calling', deparse(substitute(fn)), '\\n')\n    result <- fn(...)\n    cat('Returned:', result, '\\n')\n    result\n  }\n}\n\nadd <- log_calls(function(a, b) a + b)\nadd(3, 4)",
    "C": "// C uses compiler attributes\n__attribute__((deprecated(\"Use new_func\")))\nvoid old_func(void) { }\n\n__attribute__((noreturn))\nvoid fatal(const char* msg) { fprintf(stderr, \"%s\\n\", msg); exit(1); }\n\n__attribute__((constructor))\nvoid init(void) { printf(\"Module loaded\\n\"); }\n\n__attribute__((destructor))\nvoid cleanup(void) { printf(\"Module unloaded\\n\"); }\n\n__attribute__((format(printf, 1, 2)))\nvoid my_printf(const char* fmt, ...) { }",
    "JavaScript": "// Decorators (Stage 3)\nfunction log(target, context) {\n  const original = target;\n  function replacement(...args) {\n    console.log(`Calling ${context.name}`);\n    return original.call(this, ...args);\n  }\n  return replacement;\n}\n\nclass Calculator {\n  @log\n  add(a, b) { return a + b; }\n}\n\n// Auto-accessor decorator\nfunction clamp(min, max) {\n  return (target, context) => {\n    return {\n      set(value) { target.set.call(this, Math.min(max, Math.max(min, value))); },\n      get() { return target.get.call(this); },\n    };\n  };\n}",
}

EXPANDED_V7["logging"] = {
    "Python": "import logging\n\n# Basic\nlogging.basicConfig(level=logging.DEBUG,\n    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s')\n\nlogger = logging.getLogger(__name__)\nlogger.debug('Debug message')\nlogger.info('Info message')\nlogger.warning('Warning message')\nlogger.error('Error message')\nlogger.critical('Critical message')\n\n# With context\nlogger.info('User %s logged in from %s', username, ip)\nlogger.exception('Failed to process', exc_info=True)\n\n# File handler\nfh = logging.FileHandler('app.log')\nfh.setLevel(logging.WARNING)\nlogger.addHandler(fh)\n\n# Structured logging\nimport json\nlogger.info(json.dumps({'event': 'login', 'user': 'alice'}))",
    "JavaScript": "// Console\nconsole.log('Info message');\nconsole.warn('Warning message');\nconsole.error('Error message');\nconsole.debug('Debug message');\nconsole.table([{a: 1}, {a: 2}]);\nconsole.time('operation');\n// ...work...\nconsole.timeEnd('operation');\nconsole.group('Group');\nconsole.log('Nested');\nconsole.groupEnd();\n\n// Structured\nconsole.log(JSON.stringify({level: 'info', event: 'login', user: 'alice'}));\n\n// Custom logger\nconst logger = {\n  info: (msg, data) => console.log(`[INFO] ${msg}`, data || ''),\n  error: (msg, err) => console.error(`[ERROR] ${msg}`, err?.stack || ''),\n  warn: (msg) => console.warn(`[WARN] ${msg}`),\n};",
    "Go": "import \"log\"\nimport \"log/slog\"  // Go 1.21+\n\n// Basic\nlog.Println(\"Info message\")\nlog.Printf(\"User %s logged in\", username)\nlog.Fatal(\"Fatal error\")  // Prints and exits\n\n// Custom logger\nlogger := log.New(os.Stderr, \"[APP] \", log.Ldate|log.Ltime|log.Lshortfile)\nlogger.Println(\"Custom logger\")\n\n// Structured logging (slog)\nslog.Info(\"User logged in\",\n    slog.String(\"user\", \"alice\"),\n    slog.String(\"ip\", \"1.2.3.4\"),\n    slog.Int(\"attempt\", 1))\n\nslog.Error(\"Failed to process\",\n    slog.String(\"error\", err.Error()))\n\n// JSON handler\nhandler := slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug})\nlogger := slog.New(handler)",
    "Rust": "// log crate + env_logger\nuse log::{debug, info, warn, error, trace};\n\nfn main() {\n    env_logger::init();\n    trace!(\"Trace message\");\n    debug!(\"Debug message\");\n    info!(\"User {} logged in from {}\", username, ip);\n    warn!(\"Disk usage at {}%\", 85);\n    error!(\"Failed to process: {}\", err);\n}\n\n// tracing (structured)\nuse tracing::{info, instrument, span, Level};\n\n#[instrument]\nfn process_request(id: u32) {\n    info!(\"Processing request\");\n    let span = span!(Level::INFO, \"database\", query = \"SELECT\");\n    let _enter = span.enter();\n}",
    "Java": "import java.util.logging.Logger;\nimport java.util.logging.Level;\n\n// java.util.logging\nLogger logger = Logger.getLogger(MyClass.class.getName());\nlogger.info(\"Info message\");\nlogger.warning(\"Warning message\");\nlogger.severe(\"Error message\");\nlogger.log(Level.INFO, \"User {0} logged in\", username);\n\n// SLF4J + Logback (recommended)\nimport org.slf4j.Logger;\nimport org.slf4j.LoggerFactory;\n\nLogger log = LoggerFactory.getLogger(MyClass.class);\nlog.info(\"User {} logged in from {}\", username, ip);\nlog.error(\"Failed to process\", exception);\nlog.debug(\"Debug: count={}\", count);\n\n// MDC (context)\nMDC.put(\"requestId\", requestId);\nlog.info(\"Processing request\");\nMDC.clear();",
    "C#": "using Microsoft.Extensions.Logging;\n\n// ILogger\npublic class MyService {\n    private readonly ILogger<MyService> _logger;\n    public MyService(ILogger<MyService> logger) => _logger = logger;\n\n    public void Process() {\n        _logger.LogDebug(\"Debug message\");\n        _logger.LogInformation(\"User {User} logged in\", username);\n        _logger.LogWarning(\"Disk usage at {Percent}%\", 85);\n        _logger.LogError(ex, \"Failed to process\");\n        _logger.LogCritical(\"System failure\");\n    }\n}\n\n// Scoped logging\nusing (_logger.BeginScope(\"RequestId: {Id}\", requestId)) {\n    _logger.LogInformation(\"Processing\");\n}\n\n// Serilog\nLog.Information(\"User {User} logged in at {Time}\", user, DateTime.Now);",
    "Ruby": "require 'logger'\n\nlogger = Logger.new(STDOUT)\nlogger.level = Logger::DEBUG\n\nlogger.debug('Debug message')\nlogger.info('Info message')\nlogger.warn('Warning message')\nlogger.error('Error message')\nlogger.fatal('Fatal message')\n\n# With context\nlogger.info(\"User #{username} logged in from #{ip}\")\n\n# File logging\nlogger = Logger.new('app.log', 'daily')  # Daily rotation\nlogger.formatter = proc do |severity, time, progname, msg|\n  \"#{time.iso8601} [#{severity}] #{msg}\\n\"\nend",
    "Kotlin": "import org.slf4j.LoggerFactory\n\nclass MyService {\n    companion object {\n        private val log = LoggerFactory.getLogger(MyService::class.java)\n    }\n\n    fun process() {\n        log.debug(\"Debug message\")\n        log.info(\"User {} logged in from {}\", username, ip)\n        log.warn(\"Disk usage at {}%\", 85)\n        log.error(\"Failed to process\", exception)\n    }\n}\n\n// kotlin-logging\nimport mu.KotlinLogging\nprivate val logger = KotlinLogging.logger {}\nlogger.info { \"Lazy evaluated: $expensiveCall\" }",
    "Swift": "import os\n\n// os.Logger (Apple)\nlet logger = Logger(subsystem: \"com.app\", category: \"network\")\nlogger.debug(\"Debug message\")\nlogger.info(\"User \\(username) logged in\")\nlogger.warning(\"Disk usage high\")\nlogger.error(\"Failed: \\(error.localizedDescription)\")\nlogger.critical(\"System failure\")\n\n// With privacy\nlogger.info(\"User \\(username, privacy: .public) from \\(ip, privacy: .private)\")\n\n// SignpostID for performance\nlet signpost = OSSignposter()\nlet id = signpost.makeSignpostID()\nlet state = signpost.beginInterval(\"Network\", id: id)\n// ...work...\nsignpost.endInterval(\"Network\", state)",
    "Elixir": "require Logger\n\n# Levels\nLogger.debug(\"Debug message\")\nLogger.info(\"User #{username} logged in\")\nLogger.warning(\"Disk usage at #{percent}%\")\nLogger.error(\"Failed to process: #{inspect(error)}\")\n\n# Metadata\nLogger.metadata(request_id: \"abc123\")\nLogger.info(\"Processing request\")\n\n# Configuration\nconfig :logger,\n  level: :info,\n  format: \"$time $metadata[$level] $message\\n\",\n  metadata: [:request_id]",
    "PHP": "// PSR-3 Logger\nuse Psr\\Log\\LoggerInterface;\n\nclass MyService {\n    public function __construct(private LoggerInterface $logger) {}\n\n    public function process(): void {\n        $this->logger->debug('Debug message');\n        $this->logger->info('User {user} logged in', ['user' => $username]);\n        $this->logger->warning('Disk usage at {percent}%', ['percent' => 85]);\n        $this->logger->error('Failed', ['exception' => $e]);\n    }\n}\n\n// Monolog\nuse Monolog\\Logger;\nuse Monolog\\Handler\\StreamHandler;\n\n$log = new Logger('app');\n$log->pushHandler(new StreamHandler('app.log', Logger::WARNING));",
    "Haskell": "-- monad-logger\nimport Control.Monad.Logger\n\nrunStdoutLoggingT $ do\n  logDebugN \"Debug message\"\n  logInfoN \"Info message\"\n  logWarnN \"Warning message\"\n  logErrorN \"Error message\"\n\n-- co-log\nimport Colog\n\nlogInfo \"User logged in\"\nlogError \"Failed to process\"",
    "Scala": "// SLF4J\nimport org.slf4j.LoggerFactory\nval log = LoggerFactory.getLogger(getClass)\nlog.info(\"User {} logged in\", username)\nlog.error(\"Failed\", exception)\n\n// scala-logging\nimport com.typesafe.scalalogging.LazyLogging\nclass MyService extends LazyLogging {\n  logger.info(s\"User $username logged in\")\n}",
    "Clojure": ";; tools.logging\n(require '[clojure.tools.logging :as log])\n\n(log/debug \"Debug message\")\n(log/info \"User\" username \"logged in\")\n(log/warn \"Disk usage high\")\n(log/error exception \"Failed to process\")",
    "Dart": "import 'package:logging/logging.dart';\n\nfinal log = Logger('MyApp');\n\nvoid main() {\n  Logger.root.level = Level.ALL;\n  Logger.root.onRecord.listen((record) {\n    print('${record.level.name}: ${record.time}: ${record.message}');\n  });\n\n  log.fine('Debug message');\n  log.info('Info message');\n  log.warning('Warning message');\n  log.severe('Error message');\n}",
    "Julia": "using Logging\n\n@debug \"Debug message\"\n@info \"User $username logged in\" ip=ip\n@warn \"Disk usage high\" percent=85\n@error \"Failed to process\" exception=e\n\n# Custom logger\nlogger = SimpleLogger(stderr, Logging.Warn)\nwith_logger(logger) do\n    @info \"This won't show\"\n    @warn \"This will show\"\nend",
    "C": "#include <syslog.h>\n\nopenlog(\"myapp\", LOG_PID | LOG_CONS, LOG_USER);\nsyslog(LOG_DEBUG, \"Debug: %s\", msg);\nsyslog(LOG_INFO, \"User %s logged in\", username);\nsyslog(LOG_WARNING, \"Disk usage at %d%%\", 85);\nsyslog(LOG_ERR, \"Failed: %s\", strerror(errno));\ncloselog();\n\n// Simple macro-based\n#define LOG(level, fmt, ...) \\\n    fprintf(stderr, \"[%s] \" fmt \"\\n\", level, ##__VA_ARGS__)\n\nLOG(\"INFO\", \"User %s logged in\", username);",
    "C++": "#include <spdlog/spdlog.h>\n\nspdlog::debug(\"Debug message\");\nspdlog::info(\"User {} logged in from {}\", username, ip);\nspdlog::warn(\"Disk usage at {}%\", 85);\nspdlog::error(\"Failed to process: {}\", err.what());\nspdlog::critical(\"System failure\");\n\n// File logger\nauto file_logger = spdlog::basic_logger_mt(\"file\", \"app.log\");\nfile_logger->info(\"Logged to file\");\n\n// Rotating logger\nauto rotating = spdlog::rotating_logger_mt(\"rot\", \"app.log\", 1048576, 3);",
    "Nim": "import std/logging\n\nvar logger = newConsoleLogger()\naddHandler(logger)\n\nlog(lvlDebug, \"Debug message\")\nlog(lvlInfo, \"User \" & username & \" logged in\")\nlog(lvlWarn, \"Disk usage high\")\nlog(lvlError, \"Failed to process\")\nlog(lvlFatal, \"System failure\")",
    "Crystal": "require \"log\"\n\nLog.setup(:debug)\nLog.info { \"User #{username} logged in\" }\nLog.warn { \"Disk usage at #{percent}%\" }\nLog.error(exception: ex) { \"Failed to process\" }\n\n# Custom backend\nLog.setup do |c|\n  c.bind \"*\", :info, Log::IOBackend.new(File.open(\"app.log\", \"a\"))\nend",
    "Erlang": "% Built-in logger (OTP 21+)\nlogger:debug(\"Debug message\"),\nlogger:info(\"User ~s logged in\", [Username]),\nlogger:warning(\"Disk usage at ~B%\", [85]),\nlogger:error(\"Failed: ~p\", [Error]),\n\n% With metadata\nlogger:info(#{msg => \"Request processed\", request_id => ReqId}).",
    "Perl": "use Log::Log4perl qw(:easy);\nLog::Log4perl->easy_init($DEBUG);\n\nmy $log = get_logger();\n$log->debug('Debug message');\n$log->info(\"User $username logged in\");\n$log->warn('Disk usage high');\n$log->error('Failed to process');\n$log->fatal('System failure');",
    "R": "library(logger)\n\nlog_debug('Debug message')\nlog_info('User {username} logged in')\nlog_warn('Disk usage at {percent}%')\nlog_error('Failed to process')\n\n# Configuration\nlog_threshold(INFO)\nlog_appender(appender_file('app.log'))",
    "TypeScript": "// winston\nimport winston from 'winston';\nconst logger = winston.createLogger({\n  level: 'info',\n  format: winston.format.json(),\n  transports: [\n    new winston.transports.File({ filename: 'error.log', level: 'error' }),\n    new winston.transports.Console({ format: winston.format.simple() }),\n  ],\n});\n\nlogger.debug('Debug message');\nlogger.info('User logged in', { user: username, ip });\nlogger.warn('Disk usage high', { percent: 85 });\nlogger.error('Failed', { error: err.message });",
    "Zig": "const std = @import(\"std\");\n\nstd.log.debug(\"Debug: {s}\", .{msg});\nstd.log.info(\"User {s} logged in\", .{username});\nstd.log.warn(\"Disk usage at {d}%\", .{percent});\nstd.log.err(\"Failed: {s}\", .{error_msg});\n\n// Custom log function\npub const std_options = struct {\n    pub const log_level = .debug;\n    pub const logFn = customLog;\n};",
    "Racket": "(require racket/logging)\n\n(log-debug \"Debug message\")\n(log-info \"User ~a logged in\" username)\n(log-warning \"Disk usage high\")\n(log-error \"Failed to process\")\n(log-fatal \"System failure\")\n\n;; With receiver\n(define receiver (make-log-receiver logger 'info))",
    "D": "import std.experimental.logger;\n\nlog(LogLevel.trace, \"Trace\");\nlog(LogLevel.info, \"User logged in\");\nlog(LogLevel.warning, \"Disk usage high\");\nlog(LogLevel.error, \"Failed\");\nlog(LogLevel.critical, \"Critical failure\");",
    "F#": "open Microsoft.Extensions.Logging\n\nlet logger = loggerFactory.CreateLogger<MyService>()\nlogger.LogDebug(\"Debug message\")\nlogger.LogInformation(\"User {User} logged in\", username)\nlogger.LogWarning(\"Disk usage at {Percent}%\", 85)\nlogger.LogError(ex, \"Failed to process\")",
    "OCaml": "(* Logs library *)\nLogs.debug (fun m -> m \"Debug message\");\nLogs.info (fun m -> m \"User %s logged in\" username);\nLogs.warn (fun m -> m \"Disk usage high\");\nLogs.err (fun m -> m \"Failed: %s\" (Printexc.to_string exn));\n\n(* Setup *)\nLogs.set_reporter (Logs_fmt.reporter ());\nLogs.set_level (Some Logs.Debug);",
    "Lua": "-- Simple logger\nlocal levels = {DEBUG=1, INFO=2, WARN=3, ERROR=4}\nlocal current_level = levels.DEBUG\n\nlocal function log(level, msg)\n    if levels[level] >= current_level then\n        print(os.date('%Y-%m-%d %H:%M:%S') .. ' [' .. level .. '] ' .. msg)\n    end\nend\n\nlog('DEBUG', 'Debug message')\nlog('INFO', 'User ' .. username .. ' logged in')\nlog('WARN', 'Disk usage high')\nlog('ERROR', 'Failed to process')",
}


def get_expanded_v7_rosetta():
    """Return all v7 expanded handcrafted entries."""
    entries = []
    idx = 70000
    for concept, lang_codes in EXPANDED_V7.items():
        cn = concept.replace('_', ' ').title()
        for lang, code in lang_codes.items():
            idx += 1
            entries.append({
                "id": f"rosetta_v7_{idx}",
                "concept": concept,
                "concept_name": cn,
                "language": lang,
                "code": code,
                "category": "rosetta_stone",
                "has_code": True,
                "code_lines": len(code.split('\n')),
                "source": "handcrafted",
            })
    return entries
