"""
╔══════════════════════════════════════════════════════════════════════════╗
║  ROSETTA WAVE 8 — 6 CONCEPTS × 30 CORE LANGUAGES → 50 TOTAL            ║
║  error_types | channels_messaging | web_server | file_parsing |          ║
║  functional_patterns | scope_lifetime                                    ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

EXPANDED_V8 = {}

EXPANDED_V8["error_types"] = {
    "Python": "# Custom exceptions\nclass AppError(Exception):\n    def __init__(self, message, code=None):\n        super().__init__(message)\n        self.code = code\n\nclass NotFoundError(AppError):\n    def __init__(self, resource, id):\n        super().__init__(f'{resource} {id} not found', code=404)\n\nclass ValidationError(AppError):\n    def __init__(self, field, reason):\n        super().__init__(f'{field}: {reason}', code=400)\n        self.field = field\n\n# Usage\ntry:\n    raise NotFoundError('User', 42)\nexcept NotFoundError as e:\n    print(f'[{e.code}] {e}')\nexcept AppError as e:\n    print(f'App error: {e}')\nexcept Exception as e:\n    print(f'Unexpected: {e}')\nfinally:\n    print('Cleanup')\n\n# Multiple exceptions\ntry: pass\nexcept (ValueError, TypeError) as e: pass",
    "Rust": "use std::fmt;\n\n// Custom error enum\n#[derive(Debug)]\nenum AppError {\n    NotFound(String),\n    Validation { field: String, reason: String },\n    Database(String),\n    Io(std::io::Error),\n}\n\nimpl fmt::Display for AppError {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        match self {\n            AppError::NotFound(r) => write!(f, \"Not found: {}\", r),\n            AppError::Validation { field, reason } => write!(f, \"{}: {}\", field, reason),\n            AppError::Database(msg) => write!(f, \"DB error: {}\", msg),\n            AppError::Io(e) => write!(f, \"IO error: {}\", e),\n        }\n    }\n}\n\nimpl std::error::Error for AppError {}\n\n// From conversions\nimpl From<std::io::Error> for AppError {\n    fn from(e: std::io::Error) -> Self { AppError::Io(e) }\n}\n\n// Usage with ? operator\nfn find_user(id: u32) -> Result<String, AppError> {\n    if id == 0 { return Err(AppError::NotFound(\"User\".into())); }\n    Ok(\"Alice\".into())\n}\n\n// thiserror crate (derive macro)\n// #[derive(thiserror::Error, Debug)]\n// enum AppError { #[error(\"not found: {0}\")] NotFound(String) }",
    "Go": "import (\n    \"errors\"\n    \"fmt\"\n)\n\n// Custom error types\ntype NotFoundError struct {\n    Resource string\n    ID       int\n}\nfunc (e *NotFoundError) Error() string {\n    return fmt.Sprintf(\"%s %d not found\", e.Resource, e.ID)\n}\n\ntype ValidationError struct {\n    Field  string\n    Reason string\n}\nfunc (e *ValidationError) Error() string {\n    return fmt.Sprintf(\"%s: %s\", e.Field, e.Reason)\n}\n\n// Sentinel errors\nvar ErrNotFound = errors.New(\"not found\")\nvar ErrUnauthorized = errors.New(\"unauthorized\")\n\n// Wrapping\nfunc process() error {\n    return fmt.Errorf(\"failed to process: %w\", ErrNotFound)\n}\n\n// errors.Is / errors.As\nif errors.Is(err, ErrNotFound) { }\nvar nfErr *NotFoundError\nif errors.As(err, &nfErr) { fmt.Println(nfErr.Resource) }",
    "TypeScript": "// Custom error classes\nclass AppError extends Error {\n  constructor(message: string, public code: number) {\n    super(message);\n    this.name = 'AppError';\n  }\n}\n\nclass NotFoundError extends AppError {\n  constructor(public resource: string, public id: number) {\n    super(`${resource} ${id} not found`, 404);\n    this.name = 'NotFoundError';\n  }\n}\n\nclass ValidationError extends AppError {\n  constructor(public field: string, public reason: string) {\n    super(`${field}: ${reason}`, 400);\n    this.name = 'ValidationError';\n  }\n}\n\n// Usage\ntry {\n  throw new NotFoundError('User', 42);\n} catch (e) {\n  if (e instanceof NotFoundError) console.log(e.resource);\n  else if (e instanceof AppError) console.log(e.code);\n  else throw e;\n}",
    "Java": "// Exception hierarchy\npublic class AppException extends Exception {\n    private final int code;\n    public AppException(String message, int code) {\n        super(message); this.code = code;\n    }\n    public int getCode() { return code; }\n}\n\npublic class NotFoundException extends AppException {\n    public NotFoundException(String resource, int id) {\n        super(resource + \" \" + id + \" not found\", 404);\n    }\n}\n\n// Checked vs unchecked\npublic class BusinessException extends Exception { }  // Checked\npublic class SystemException extends RuntimeException { }  // Unchecked\n\n// Multi-catch\ntry { riskyOperation(); }\ncatch (IOException | SQLException e) { log(e); }\ncatch (Exception e) { throw new AppException(\"Unexpected\", 500); }\nfinally { cleanup(); }",
    "C#": "// Exception hierarchy\npublic class AppException : Exception {\n    public int Code { get; }\n    public AppException(string message, int code) : base(message) => Code = code;\n}\n\npublic class NotFoundException : AppException {\n    public string Resource { get; }\n    public NotFoundException(string resource, int id)\n        : base($\"{resource} {id} not found\", 404) => Resource = resource;\n}\n\n// Usage with filters\ntry { throw new NotFoundException(\"User\", 42); }\ncatch (NotFoundException e) when (e.Resource == \"User\") { }\ncatch (AppException e) when (e.Code >= 500) { }\ncatch (Exception e) { }\nfinally { }",
    "Swift": "// Error protocol\nenum AppError: Error {\n    case notFound(resource: String, id: Int)\n    case validation(field: String, reason: String)\n    case network(URLError)\n    case unknown(String)\n}\n\n// LocalizedError\nextension AppError: LocalizedError {\n    var errorDescription: String? {\n        switch self {\n        case .notFound(let r, let id): return \"\\(r) \\(id) not found\"\n        case .validation(let f, let r): return \"\\(f): \\(r)\"\n        case .network(let e): return \"Network: \\(e.localizedDescription)\"\n        case .unknown(let msg): return msg\n        }\n    }\n}\n\n// Usage\ndo {\n    throw AppError.notFound(resource: \"User\", id: 42)\n} catch AppError.notFound(let r, let id) {\n    print(\"Missing \\(r) \\(id)\")\n} catch {\n    print(error.localizedDescription)\n}",
    "Kotlin": "// Exception hierarchy\nopen class AppException(message: String, val code: Int) : Exception(message)\n\nclass NotFoundException(resource: String, id: Int)\n    : AppException(\"$resource $id not found\", 404)\n\nclass ValidationException(val field: String, reason: String)\n    : AppException(\"$field: $reason\", 400)\n\n// Sealed class for Result pattern\nsealed class Result<out T> {\n    data class Success<T>(val value: T) : Result<T>()\n    data class Failure(val error: AppException) : Result<Nothing>()\n}\n\nfun findUser(id: Int): Result<String> {\n    if (id == 0) return Result.Failure(NotFoundException(\"User\", id))\n    return Result.Success(\"Alice\")\n}\n\nwhen (val r = findUser(42)) {\n    is Result.Success -> println(r.value)\n    is Result.Failure -> println(r.error.message)\n}",
    "C++": "// Exception hierarchy\n#include <stdexcept>\n\nclass AppError : public std::runtime_error {\n    int code_;\npublic:\n    AppError(const std::string& msg, int code)\n        : std::runtime_error(msg), code_(code) {}\n    int code() const { return code_; }\n};\n\nclass NotFoundError : public AppError {\npublic:\n    NotFoundError(const std::string& resource, int id)\n        : AppError(resource + \" not found\", 404) {}\n};\n\n// Usage\ntry {\n    throw NotFoundError(\"User\", 42);\n} catch (const NotFoundError& e) {\n    std::cerr << \"[404] \" << e.what() << '\\n';\n} catch (const AppError& e) {\n    std::cerr << \"[\" << e.code() << \"] \" << e.what() << '\\n';\n} catch (const std::exception& e) {\n    std::cerr << \"Unexpected: \" << e.what() << '\\n';\n}\n\n// std::expected (C++23)\nstd::expected<User, AppError> findUser(int id);",
    "Haskell": "-- Custom error types with Either\ndata AppError\n  = NotFound String Int\n  | Validation String String\n  | DatabaseError String\n  deriving (Show, Eq)\n\nfindUser :: Int -> Either AppError String\nfindUser 0 = Left (NotFound \"User\" 0)\nfindUser _ = Right \"Alice\"\n\n-- ExceptT monad transformer\nimport Control.Monad.Except\n\ntype App = ExceptT AppError IO\n\nrunApp :: App a -> IO (Either AppError a)\nrunApp = runExceptT\n\nfetchUser :: Int -> App String\nfetchUser id = do\n  when (id == 0) $ throwError (NotFound \"User\" id)\n  return \"Alice\"",
    "Elixir": "# Custom exceptions\ndefmodule AppError do\n  defexception [:message, :code]\nend\n\ndefmodule NotFoundError do\n  defexception [:resource, :id]\n  @impl true\n  def message(%{resource: r, id: id}), do: \"#{r} #{id} not found\"\nend\n\n# Usage\ntry do\n  raise NotFoundError, resource: \"User\", id: 42\nrescue\n  e in NotFoundError -> IO.puts(\"Not found: #{e.message}\")\n  e in AppError -> IO.puts(\"App error: #{e.message}\")\n  e -> IO.puts(\"Unexpected: #{inspect(e)}\")\nafter\n  IO.puts(\"Cleanup\")\nend\n\n# Pattern matching on tuples (preferred)\ncase find_user(42) do\n  {:ok, user} -> user\n  {:error, :not_found} -> nil\n  {:error, reason} -> raise \"Failed: #{reason}\"\nend",
    "Scala": "// Sealed trait hierarchy\nsealed trait AppError extends Throwable {\n  def code: Int\n  def message: String\n}\n\ncase class NotFoundError(resource: String, id: Int) extends AppError {\n  val code = 404\n  val message = s\"$resource $id not found\"\n}\n\ncase class ValidationError(field: String, reason: String) extends AppError {\n  val code = 400\n  val message = s\"$field: $reason\"\n}\n\n// Either pattern\ndef findUser(id: Int): Either[AppError, String] =\n  if (id == 0) Left(NotFoundError(\"User\", id))\n  else Right(\"Alice\")\n\nfindUser(42) match {\n  case Right(user) => println(user)\n  case Left(e: NotFoundError) => println(s\"Missing: ${e.resource}\")\n  case Left(e) => println(s\"Error: ${e.message}\")\n}",
    "Ruby": "# Custom exceptions\nclass AppError < StandardError\n  attr_reader :code\n  def initialize(message, code = 500)\n    super(message)\n    @code = code\n  end\nend\n\nclass NotFoundError < AppError\n  def initialize(resource, id)\n    super(\"#{resource} #{id} not found\", 404)\n  end\nend\n\nclass ValidationError < AppError\n  attr_reader :field\n  def initialize(field, reason)\n    super(\"#{field}: #{reason}\", 400)\n    @field = field\n  end\nend\n\nbegin\n  raise NotFoundError.new('User', 42)\nrescue NotFoundError => e\n  puts \"[#{e.code}] #{e.message}\"\nrescue AppError => e\n  puts \"App: #{e.message}\"\nrescue => e\n  puts \"Unexpected: #{e}\"\nensure\n  puts 'Cleanup'\nend",
    "PHP": "// Custom exceptions\nclass AppException extends \\Exception {\n    public function __construct(string $message, private int $appCode) {\n        parent::__construct($message, $appCode);\n    }\n    public function getAppCode(): int { return $this->appCode; }\n}\n\nclass NotFoundException extends AppException {\n    public function __construct(string $resource, int $id) {\n        parent::__construct(\"$resource $id not found\", 404);\n    }\n}\n\ntry {\n    throw new NotFoundException('User', 42);\n} catch (NotFoundException $e) {\n    echo \"[{$e->getAppCode()}] {$e->getMessage()}\\n\";\n} catch (AppException $e) {\n    echo \"App error: {$e->getMessage()}\\n\";\n} finally {\n    echo \"Cleanup\\n\";\n}",
    "C": "// C uses error codes\n#include <errno.h>\n\ntypedef enum {\n    ERR_NONE = 0,\n    ERR_NOT_FOUND = -1,\n    ERR_VALIDATION = -2,\n    ERR_IO = -3,\n} ErrorCode;\n\ntypedef struct {\n    ErrorCode code;\n    char message[256];\n} Error;\n\nError find_user(int id, char* out) {\n    if (id == 0) return (Error){ERR_NOT_FOUND, \"User not found\"};\n    strcpy(out, \"Alice\");\n    return (Error){ERR_NONE, \"\"};\n}\n\n// errno\nFILE* f = fopen(\"nofile.txt\", \"r\");\nif (!f) {\n    perror(\"fopen\");  // Prints: fopen: No such file or directory\n    printf(\"errno: %d\\n\", errno);\n}",
    "Dart": "// Custom exceptions\nclass AppException implements Exception {\n  final String message;\n  final int code;\n  AppException(this.message, this.code);\n  @override String toString() => '[$code] $message';\n}\n\nclass NotFoundException extends AppException {\n  NotFoundException(String resource, int id)\n    : super('$resource $id not found', 404);\n}\n\ntry {\n  throw NotFoundException('User', 42);\n} on NotFoundException catch (e) {\n  print(e);\n} on AppException catch (e) {\n  print('App error: $e');\n} catch (e) {\n  print('Unexpected: $e');\n} finally {\n  print('Cleanup');\n}",
    "Julia": "# Custom exception types\nstruct AppError <: Exception\n    message::String\n    code::Int\nend\n\nstruct NotFoundError <: Exception\n    resource::String\n    id::Int\nend\n\nBase.showerror(io::IO, e::NotFoundError) =\n    print(io, \"$(e.resource) $(e.id) not found\")\n\ntry\n    throw(NotFoundError(\"User\", 42))\ncatch e::NotFoundError\n    println(\"Not found: $(e.resource)\")\ncatch e\n    println(\"Unexpected: $e\")\nfinally\n    println(\"Cleanup\")\nend",
    "Clojure": ";; ex-info (data-carrying exceptions)\n(throw (ex-info \"User not found\"\n         {:type :not-found :resource \"User\" :id 42}))\n\n(try\n  (find-user 42)\n  (catch clojure.lang.ExceptionInfo e\n    (let [data (ex-data e)]\n      (case (:type data)\n        :not-found (println \"Missing:\" (:resource data))\n        :validation (println \"Invalid:\" (:field data))\n        (println \"Error:\" (ex-message e)))))\n  (catch Exception e\n    (println \"Unexpected:\" (.getMessage e)))\n  (finally\n    (println \"Cleanup\")))",
    "Nim": "type\n  AppError = object of CatchableError\n    code: int\n  NotFoundError = object of AppError\n    resource: string\n    id: int\n  ValidationError = object of AppError\n    field: string\n\ntry:\n  raise newException(NotFoundError, \"User 42 not found\")\nexcept NotFoundError as e:\n  echo \"Not found: \", e.msg\nexcept AppError as e:\n  echo \"App error: \", e.msg\nexcept:\n  echo \"Unexpected\"\nfinally:\n  echo \"Cleanup\"",
    "Crystal": "class AppError < Exception\n  getter code : Int32\n  def initialize(message, @code = 500)\n    super(message)\n  end\nend\n\nclass NotFoundError < AppError\n  def initialize(resource : String, id : Int32)\n    super(\"#{resource} #{id} not found\", 404)\n  end\nend\n\nbegin\n  raise NotFoundError.new(\"User\", 42)\nrescue e : NotFoundError\n  puts \"[#{e.code}] #{e.message}\"\nrescue e : AppError\n  puts \"App: #{e.message}\"\nensure\n  puts \"Cleanup\"\nend",
    "Erlang": "%% Tagged tuples for errors\nfind_user(0) -> {error, not_found};\nfind_user(Id) -> {ok, \"Alice\"}.\n\ncase find_user(42) of\n    {ok, User} -> io:format(\"Found: ~s~n\", [User]);\n    {error, not_found} -> io:format(\"Not found~n\");\n    {error, Reason} -> io:format(\"Error: ~p~n\", [Reason])\nend.",
    "OCaml": "(* Result type *)\ntype app_error =\n  | NotFound of string * int\n  | Validation of string * string\n  | Database of string\n\nlet find_user id =\n  if id = 0 then Error (NotFound (\"User\", id))\n  else Ok \"Alice\"\n\nmatch find_user 42 with\n| Ok user -> Printf.printf \"Found: %s\\n\" user\n| Error (NotFound (r, id)) -> Printf.printf \"%s %d not found\\n\" r id\n| Error (Validation (f, r)) -> Printf.printf \"%s: %s\\n\" f r\n| Error (Database msg) -> Printf.printf \"DB: %s\\n\" msg",
    "F#": "type AppError =\n    | NotFound of resource: string * id: int\n    | Validation of field: string * reason: string\n    | Database of string\n\nlet findUser id =\n    if id = 0 then Error (NotFound (\"User\", id))\n    else Ok \"Alice\"\n\nmatch findUser 42 with\n| Ok user -> printfn \"Found: %s\" user\n| Error (NotFound (r, id)) -> printfn \"%s %d not found\" r id\n| Error (Validation (f, r)) -> printfn \"%s: %s\" f r\n| Error (Database msg) -> printfn \"DB: %s\" msg",
    "Lua": "-- Error objects\nlocal function AppError(message, code)\n    return {message = message, code = code or 500, is_error = true}\nend\n\nlocal function NotFoundError(resource, id)\n    local e = AppError(resource .. ' ' .. id .. ' not found', 404)\n    e.resource = resource\n    e.id = id\n    return e\nend\n\n-- pcall pattern\nlocal ok, result = pcall(function()\n    error(NotFoundError('User', 42))\nend)\nif not ok then\n    if type(result) == 'table' and result.is_error then\n        print('[' .. result.code .. '] ' .. result.message)\n    end\nend",
    "Perl": "# Custom exception classes\npackage AppError;\nuse Moo;\nextends 'Throwable';\nhas code => (is => 'ro', default => 500);\nhas message => (is => 'ro', required => 1);\n\n# Or simple die/eval\neval {\n    die {type => 'not_found', resource => 'User', id => 42};\n};\nif (my $e = $@) {\n    if (ref $e eq 'HASH' && $e->{type} eq 'not_found') {\n        print \"Not found: $e->{resource}\\n\";\n    }\n}",
    "R": "# Conditions (R's error system)\nnotFoundError <- function(resource, id) {\n  structure(\n    class = c('not_found_error', 'app_error', 'error', 'condition'),\n    list(message = paste(resource, id, 'not found'), resource = resource, id = id)\n  )\n}\n\ntryCatch(\n  stop(notFoundError('User', 42)),\n  not_found_error = function(e) cat('Not found:', e$resource, '\\n'),\n  app_error = function(e) cat('App error:', e$message, '\\n'),\n  error = function(e) cat('Error:', e$message, '\\n'),\n  finally = cat('Cleanup\\n')\n)",
    "Racket": ";; Struct-based exceptions\n(struct exn:app exn:fail (code) #:transparent)\n(struct exn:not-found exn:app (resource id) #:transparent)\n\n(with-handlers\n  ([exn:not-found?\n    (lambda (e) (printf \"Not found: ~a ~a\\n\"\n                  (exn:not-found-resource e) (exn:not-found-id e)))]\n   [exn:app?\n    (lambda (e) (printf \"App error [~a]: ~a\\n\"\n                  (exn:app-code e) (exn-message e)))])\n  (raise (exn:not-found \"not found\" (current-continuation-marks)\n                         404 \"User\" 42)))",
    "D": "// Exception hierarchy\nclass AppException : Exception {\n    int code;\n    this(string msg, int code = 500) {\n        super(msg);\n        this.code = code;\n    }\n}\n\nclass NotFoundException : AppException {\n    string resource;\n    this(string resource, int id) {\n        super(resource ~ \" not found\", 404);\n        this.resource = resource;\n    }\n}\n\ntry {\n    throw new NotFoundException(\"User\", 42);\n} catch (NotFoundException e) {\n    writefln(\"[%d] %s\", e.code, e.msg);\n} catch (AppException e) {\n    writefln(\"App: %s\", e.msg);\n}",
    "Zig": "const AppError = error{\n    NotFound,\n    Validation,\n    Database,\n    Io,\n};\n\nfn findUser(id: u32) AppError![]const u8 {\n    if (id == 0) return AppError.NotFound;\n    return \"Alice\";\n}\n\nconst result = findUser(42) catch |err| switch (err) {\n    AppError.NotFound => { std.debug.print(\"Not found\\n\", .{}); return; },\n    AppError.Validation => { std.debug.print(\"Invalid\\n\", .{}); return; },\n    else => return err,\n};",
    "JavaScript": "class AppError extends Error {\n  constructor(message, code) {\n    super(message);\n    this.name = 'AppError';\n    this.code = code;\n  }\n}\n\nclass NotFoundError extends AppError {\n  constructor(resource, id) {\n    super(`${resource} ${id} not found`, 404);\n    this.name = 'NotFoundError';\n    this.resource = resource;\n  }\n}\n\ntry {\n  throw new NotFoundError('User', 42);\n} catch (e) {\n  if (e instanceof NotFoundError) console.log(`Missing: ${e.resource}`);\n  else if (e instanceof AppError) console.log(`[${e.code}] ${e.message}`);\n  else throw e;\n} finally {\n  console.log('Cleanup');\n}",
}

EXPANDED_V8["channels_messaging"] = {
    "Go": "// Channels — Go's core concurrency primitive\nch := make(chan string)  // Unbuffered\nbuf := make(chan int, 10)  // Buffered\n\n// Send & receive\ngo func() { ch <- \"hello\" }()\nmsg := <-ch\n\n// Select (multiplex)\nselect {\ncase msg := <-ch1:\n    fmt.Println(\"From ch1:\", msg)\ncase msg := <-ch2:\n    fmt.Println(\"From ch2:\", msg)\ncase ch3 <- \"sent\":\n    fmt.Println(\"Sent to ch3\")\ncase <-time.After(5 * time.Second):\n    fmt.Println(\"Timeout\")\ndefault:\n    fmt.Println(\"No channel ready\")\n}\n\n// Fan-out/fan-in\nfunc fanOut(in <-chan int, outs ...chan<- int) {\n    for v := range in {\n        for _, out := range outs { out <- v }\n    }\n}\n\n// Pipeline\nfunc square(in <-chan int) <-chan int {\n    out := make(chan int)\n    go func() {\n        for v := range in { out <- v * v }\n        close(out)\n    }()\n    return out\n}",
    "Rust": "use std::sync::mpsc;\nuse std::thread;\n\n// MPSC channel\nlet (tx, rx) = mpsc::channel();\n\nthread::spawn(move || {\n    tx.send(\"hello\").unwrap();\n});\nlet msg = rx.recv().unwrap();\n\n// Multiple producers\nlet tx2 = tx.clone();\nthread::spawn(move || tx2.send(\"from thread 2\").unwrap());\n\n// Iterate\nfor msg in rx {\n    println!(\"Got: {}\", msg);\n}\n\n// tokio channels (async)\nuse tokio::sync::mpsc;\nlet (tx, mut rx) = mpsc::channel(32);\ntokio::spawn(async move { tx.send(\"async hello\").await.unwrap(); });\nwhile let Some(msg) = rx.recv().await {\n    println!(\"{}\", msg);\n}\n\n// Broadcast\nuse tokio::sync::broadcast;\nlet (tx, _) = broadcast::channel(16);",
    "Elixir": "# Processes and message passing (core to Elixir)\npid = spawn(fn ->\n  receive do\n    {:greet, name} -> IO.puts(\"Hello, #{name}!\")\n    {:add, a, b, sender} -> send(sender, {:result, a + b})\n  end\nend)\n\nsend(pid, {:greet, \"Alice\"})\nsend(pid, {:add, 3, 4, self()})\nreceive do\n  {:result, sum} -> IO.puts(\"Sum: #{sum}\")\nafter\n  5000 -> IO.puts(\"Timeout\")\nend\n\n# GenServer (structured messaging)\ndefmodule Counter do\n  use GenServer\n  def init(state), do: {:ok, state}\n  def handle_call(:get, _from, state), do: {:reply, state, state}\n  def handle_cast(:inc, state), do: {:noreply, state + 1}\nend\n\n{:ok, pid} = GenServer.start_link(Counter, 0)\nGenServer.cast(pid, :inc)\nGenServer.call(pid, :get)  # 1",
    "Erlang": "%% Message passing (core to Erlang)\nPid = spawn(fun() ->\n    receive\n        {greet, Name} -> io:format(\"Hello, ~s!~n\", [Name]);\n        {add, A, B, Sender} -> Sender ! {result, A + B}\n    end\nend),\n\nPid ! {greet, \"Alice\"},\nPid ! {add, 3, 4, self()},\nreceive\n    {result, Sum} -> io:format(\"Sum: ~B~n\", [Sum])\nafter 5000 ->\n    io:format(\"Timeout~n\")\nend.",
    "Python": "import asyncio\nimport queue\nfrom multiprocessing import Process, Queue\n\n# asyncio Queue\nasync def producer(q):\n    for i in range(5):\n        await q.put(i)\n    await q.put(None)  # Signal done\n\nasync def consumer(q):\n    while True:\n        item = await q.get()\n        if item is None: break\n        print(f'Got: {item}')\n\nasync def main():\n    q = asyncio.Queue()\n    await asyncio.gather(producer(q), consumer(q))\n\n# threading Queue\nimport threading\nq = queue.Queue()\ndef worker():\n    while True:\n        item = q.get()\n        if item is None: break\n        print(f'Processing: {item}')\n        q.task_done()\n\n# multiprocessing\ndef mp_worker(q):\n    q.put('from child process')",
    "JavaScript": "// MessageChannel (Web)\nconst { port1, port2 } = new MessageChannel();\nport1.onmessage = (e) => console.log('Received:', e.data);\nport2.postMessage('hello');\n\n// Worker threads (Node.js)\nimport { Worker, parentPort } from 'worker_threads';\n// In worker:\nparentPort.on('message', (msg) => {\n  parentPort.postMessage(msg.toUpperCase());\n});\n// In main:\nconst worker = new Worker('./worker.js');\nworker.on('message', (msg) => console.log(msg));\nworker.postMessage('hello');\n\n// BroadcastChannel\nconst bc = new BroadcastChannel('my_channel');\nbc.onmessage = (e) => console.log(e.data);\nbc.postMessage('broadcast hello');",
    "Kotlin": "import kotlinx.coroutines.*\nimport kotlinx.coroutines.channels.*\n\n// Channel\nrunBlocking {\n    val channel = Channel<Int>()\n    launch { for (i in 1..5) channel.send(i); channel.close() }\n    for (msg in channel) println(\"Got: $msg\")\n}\n\n// Produce (convenience)\nfun CoroutineScope.numbers() = produce {\n    for (i in 1..5) send(i)\n}\n\n// Select\nselect<Unit> {\n    channel1.onReceive { println(\"From 1: $it\") }\n    channel2.onReceive { println(\"From 2: $it\") }\n}\n\n// Flow (cold stream)\nflow { for (i in 1..5) { emit(i); delay(100) } }\n    .collect { println(it) }",
    "Java": "import java.util.concurrent.*;\n\n// BlockingQueue\nBlockingQueue<String> queue = new LinkedBlockingQueue<>();\n\n// Producer\nnew Thread(() -> {\n    try { queue.put(\"hello\"); } catch (InterruptedException e) {}\n}).start();\n\n// Consumer\nString msg = queue.take();  // Blocks until available\n\n// CompletableFuture (async message passing)\nCompletableFuture.supplyAsync(() -> fetchData())\n    .thenAccept(data -> process(data));\n\n// Virtual threads + queues (Java 21)\ntry (var executor = Executors.newVirtualThreadPerTaskExecutor()) {\n    var queue = new LinkedBlockingQueue<String>();\n    executor.submit(() -> queue.put(\"from virtual thread\"));\n    System.out.println(queue.take());\n}",
    "C#": "using System.Threading.Channels;\n\n// Channel<T>\nvar channel = Channel.CreateUnbounded<string>();\n\n// Producer\nawait channel.Writer.WriteAsync(\"hello\");\nchannel.Writer.Complete();\n\n// Consumer\nawait foreach (var msg in channel.Reader.ReadAllAsync()) {\n    Console.WriteLine($\"Got: {msg}\");\n}\n\n// Bounded channel\nvar bounded = Channel.CreateBounded<int>(10);\n\n// Multiple consumers\nvar tasks = Enumerable.Range(0, 3).Select(i =>\n    Task.Run(async () => {\n        await foreach (var item in channel.Reader.ReadAllAsync())\n            Console.WriteLine($\"Worker {i}: {item}\");\n    })).ToArray();",
    "Swift": "// AsyncStream + AsyncChannel\nlet stream = AsyncStream<Int> { continuation in\n    for i in 1...5 {\n        continuation.yield(i)\n    }\n    continuation.finish()\n}\n\nfor await value in stream {\n    print(\"Got: \\(value)\")\n}\n\n// Actor (message-passing concurrency)\nactor Counter {\n    private var count = 0\n    func increment() { count += 1 }\n    func getCount() -> Int { count }\n}\n\nlet counter = Counter()\nawait counter.increment()\nprint(await counter.getCount())",
    "Scala": "import akka.actor.typed._\nimport akka.actor.typed.scaladsl._\n\n// Actor model\nobject Counter {\n  sealed trait Command\n  case object Increment extends Command\n  case class GetCount(replyTo: ActorRef[Int]) extends Command\n\n  def apply(): Behavior[Command] = count(0)\n  def count(n: Int): Behavior[Command] = Behaviors.receiveMessage {\n    case Increment => count(n + 1)\n    case GetCount(replyTo) => replyTo ! n; Behaviors.same\n  }\n}",
    "Clojure": ";; core.async channels\n(require '[clojure.core.async :as a])\n\n(def ch (a/chan 10))  ;; Buffered channel\n\n;; Put\n(a/go (a/>! ch \"hello\"))\n\n;; Take\n(a/go (println \"Got:\" (a/<! ch)))\n\n;; Pipeline\n(def in-ch (a/chan))\n(def out-ch (a/chan))\n(a/pipeline 4 out-ch (map #(* % %)) in-ch)\n\n;; Alts (select)\n(a/go\n  (let [[v ch] (a/alts! [ch1 ch2 (a/timeout 5000)])]\n    (println \"From\" ch \":\" v)))",
    "Crystal": "# Channels\nch = Channel(String).new\n\nspawn do\n  ch.send(\"hello\")\nend\nmsg = ch.receive  # \"hello\"\n\n# Buffered\nbuf = Channel(Int32).new(capacity: 10)\n\n# Select\nselect\nwhen msg = ch1.receive\n  puts \"From ch1: #{msg}\"\nwhen msg = ch2.receive\n  puts \"From ch2: #{msg}\"\nwhen timeout(5.seconds)\n  puts \"Timeout\"\nend",
    "Zig": "const std = @import(\"std\");\n\n// Zig doesn't have built-in channels\n// Use thread-safe queue or atomic operations\nconst Channel = struct {\n    mutex: std.Thread.Mutex = .{},\n    data: ?[]const u8 = null,\n    \n    fn send(self: *Channel, msg: []const u8) void {\n        self.mutex.lock();\n        defer self.mutex.unlock();\n        self.data = msg;\n    }\n    fn recv(self: *Channel) ?[]const u8 {\n        self.mutex.lock();\n        defer self.mutex.unlock();\n        defer self.data = null;\n        return self.data;\n    }\n};",
    "Dart": "// Isolates + SendPort/ReceivePort\nimport 'dart:isolate';\n\nvoid worker(SendPort sendPort) {\n  sendPort.send('hello from isolate');\n}\n\nvoid main() async {\n  final receivePort = ReceivePort();\n  await Isolate.spawn(worker, receivePort.sendPort);\n  final msg = await receivePort.first;\n  print(msg);  // 'hello from isolate'\n}\n\n// StreamController (in-process)\nfinal controller = StreamController<String>();\ncontroller.stream.listen((msg) => print('Got: $msg'));\ncontroller.add('hello');\ncontroller.close();",
    "Ruby": "require 'thread'\n\n# Queue (thread-safe)\nqueue = Queue.new\n\n# Producer\nThread.new { 5.times { |i| queue << i }; queue << nil }\n\n# Consumer\nwhile (item = queue.pop)\n  puts \"Got: #{item}\"\nend\n\n# Ractor (Ruby 3.0+ — true parallelism)\nr = Ractor.new do\n  msg = Ractor.receive\n  Ractor.yield msg.upcase\nend\nr.send('hello')\nputs r.take  # 'HELLO'",
    "Haskell": "import Control.Concurrent\nimport Control.Concurrent.Chan\n\n-- Chan (unbounded channel)\nchan <- newChan\nforkIO $ writeChan chan \"hello\"\nmsg <- readChan chan\nputStrLn msg\n\n-- MVar (single-slot channel)\nmvar <- newEmptyMVar\nforkIO $ putMVar mvar 42\nval <- takeMVar mvar\n\n-- STM (Software Transactional Memory)\nimport Control.Concurrent.STM\ntchan <- newTChanIO\natomically $ writeTChan tchan \"safe\"",
    "Nim": "import std/channels\n\nvar ch: Channel[string]\nch.open()\n\n# In a thread\nproc sender() {.thread.} =\n  ch.send(\"hello\")\n\nvar t: Thread[void]\ncreateThread(t, sender)\nlet msg = ch.recv()  # \"hello\"\njoinThread(t)\nch.close()",
    "PHP": "// parallel extension\nuse parallel\\Channel;\n\n$channel = new Channel();\n\n$runtime = new parallel\\Runtime();\n$runtime->run(function() use ($channel) {\n    $channel->send('hello from thread');\n});\n\n$msg = $channel->recv();\necho $msg;  // 'hello from thread'",
    "Julia": "# Channels\nch = Channel{String}(10)  # Buffered\n\n@async begin\n    put!(ch, \"hello\")\n    put!(ch, \"world\")\n    close(ch)\nend\n\nfor msg in ch\n    println(\"Got: $msg\")\nend\n\n# RemoteChannel (distributed)\nusing Distributed\nrc = RemoteChannel(() -> Channel{Int}(10))",
    "Lua": "-- Lua uses coroutines for cooperative concurrency\nlocal function producer()\n    for i = 1, 5 do\n        coroutine.yield(i)\n    end\nend\n\nlocal co = coroutine.create(producer)\nwhile true do\n    local ok, val = coroutine.resume(co)\n    if not ok or val == nil then break end\n    print('Got:', val)\nend",
    "C": "#include <pthread.h>\n\n// POSIX message queue or mutex+condition\npthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;\npthread_cond_t cond = PTHREAD_COND_INITIALIZER;\nchar* message = NULL;\n\nvoid* sender(void* arg) {\n    pthread_mutex_lock(&mutex);\n    message = \"hello\";\n    pthread_cond_signal(&cond);\n    pthread_mutex_unlock(&mutex);\n    return NULL;\n}\n\nvoid* receiver(void* arg) {\n    pthread_mutex_lock(&mutex);\n    while (message == NULL)\n        pthread_cond_wait(&cond, &mutex);\n    printf(\"Got: %s\\n\", message);\n    pthread_mutex_unlock(&mutex);\n    return NULL;\n}",
    "C++": "#include <thread>\n#include <queue>\n#include <mutex>\n#include <condition_variable>\n\ntemplate<typename T>\nclass Channel {\n    std::queue<T> queue_;\n    std::mutex mtx_;\n    std::condition_variable cv_;\npublic:\n    void send(T value) {\n        std::lock_guard lock(mtx_);\n        queue_.push(std::move(value));\n        cv_.notify_one();\n    }\n    T recv() {\n        std::unique_lock lock(mtx_);\n        cv_.wait(lock, [this] { return !queue_.empty(); });\n        T value = std::move(queue_.front());\n        queue_.pop();\n        return value;\n    }\n};",
    "TypeScript": "// Worker threads\nimport { Worker, parentPort } from 'worker_threads';\n\n// Main thread\nconst worker = new Worker('./worker.ts');\nworker.on('message', (msg: string) => console.log('Got:', msg));\nworker.postMessage('hello');\n\n// Worker file\nparentPort?.on('message', (msg: string) => {\n  parentPort?.postMessage(msg.toUpperCase());\n});\n\n// SharedArrayBuffer (low-level)\nconst sab = new SharedArrayBuffer(1024);\nconst view = new Int32Array(sab);\nAtomics.store(view, 0, 42);\nAtomics.notify(view, 0);",
    "Perl": "use threads;\nuse Thread::Queue;\n\nmy $q = Thread::Queue->new();\n\n# Producer\nasync { $q->enqueue('hello'); $q->enqueue(undef); };\n\n# Consumer\nwhile (defined(my $msg = $q->dequeue())) {\n    print \"Got: $msg\\n\";\n}",
    "R": "# parallel package\nlibrary(parallel)\n\n# mclapply (forked processes)\nresults <- mclapply(1:10, function(x) x^2, mc.cores = 4)\n\n# Explicit clusters\ncl <- makeCluster(4)\nclusterExport(cl, 'my_data')\nresults <- parLapply(cl, 1:10, function(x) x^2)\nstopCluster(cl)",
    "Racket": "(require racket/place)\n\n;; Places (separate memory spaces)\n(define p (place ch\n  (define msg (place-channel-get ch))\n  (place-channel-put ch (string-upcase msg))))\n\n(place-channel-put p \"hello\")\n(displayln (place-channel-get p))  ;; \"HELLO\"\n\n;; Threads with channels\n(define ch (make-channel))\n(thread (lambda () (channel-put ch 42)))\n(channel-get ch)  ;; 42",
    "D": "import std.concurrency;\n\nauto tid = spawn({\n    receive((string msg) {\n        writeln(\"Got: \", msg);\n    });\n});\n\ntid.send(\"hello\");",
    "F#": "open System.Threading.Channels\n\nlet channel = Channel.CreateUnbounded<string>()\n\nasync {\n    do! channel.Writer.WriteAsync(\"hello\").AsTask() |> Async.AwaitTask\n    channel.Writer.Complete()\n} |> Async.Start\n\nlet reader = async {\n    let mutable cont = true\n    while cont do\n        match! channel.Reader.ReadAsync().AsTask() |> Async.AwaitTask with\n        | msg -> printfn \"Got: %s\" msg\n}",
    "OCaml": "(* Lwt_mvar *)\nopen Lwt.Syntax\n\nlet mvar = Lwt_mvar.create_empty ()\n\nlet producer () =\n  Lwt_mvar.put mvar \"hello\"\n\nlet consumer () =\n  let* msg = Lwt_mvar.take mvar in\n  Lwt_io.printlf \"Got: %s\" msg",
}


def get_expanded_v8_rosetta():
    """Return all v8 expanded handcrafted entries."""
    entries = []
    idx = 80000
    for concept, lang_codes in EXPANDED_V8.items():
        cn = concept.replace('_', ' ').title()
        for lang, code in lang_codes.items():
            idx += 1
            entries.append({
                "id": f"rosetta_v8_{idx}",
                "concept": concept,
                "concept_name": cn,
                "language": lang,
                "code": code,
                "category": "rosetta_stone",
                "has_code": True,
                "code_lines": len(code.split('\n')),
                "source": "handcrafted",
            })
    return entries
