"""
╔══════════════════════════════════════════════════════════════════════════╗
║  ROSETTA WAVE 5+6 — 10 CONCEPTS × 30 CORE LANGUAGES                    ║
║  lambda_expressions | binary_operations | channels_messaging |           ║
║  promises_futures | metaprogramming | memory_management |                ║
║  operator_overloading | decorators_annotations | logging | env_config    ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

EXPANDED_V5 = {}

EXPANDED_V5["lambda_expressions"] = {
    "Python": "# Lambda\nsquare = lambda x: x ** 2\nadd = lambda a, b: a + b\n\n# As argument\nsorted(['banana', 'apple', 'cherry'], key=lambda s: len(s))\nlist(filter(lambda x: x > 0, [-1, 0, 1, 2]))\nlist(map(lambda x: x * 2, [1, 2, 3]))\n\n# Immediately invoked\nresult = (lambda x, y: x + y)(3, 4)  # 7\n\n# Lambda in data structures\nops = {'+': lambda a, b: a + b, '-': lambda a, b: a - b}\nops['+'](3, 4)  # 7\n\n# Conditional lambda\nabs_val = lambda x: x if x >= 0 else -x",
    "JavaScript": "// Arrow functions\nconst square = x => x ** 2;\nconst add = (a, b) => a + b;\nconst greet = name => `Hello, ${name}!`;\n\n// Multi-line\nconst process = (items) => {\n  const filtered = items.filter(x => x > 0);\n  return filtered.map(x => x * 2);\n};\n\n// IIFE\nconst result = ((x, y) => x + y)(3, 4);\n\n// As callbacks\n[3, 1, 4].sort((a, b) => a - b);\nsetTimeout(() => console.log('done'), 1000);\n\n// Returning functions\nconst multiplier = factor => x => x * factor;\nconst double = multiplier(2);\ndouble(5);  // 10",
    "TypeScript": "// Typed arrows\nconst square: (x: number) => number = x => x ** 2;\nconst add = (a: number, b: number): number => a + b;\n\n// Generic lambda\nconst identity = <T>(x: T): T => x;\nconst first = <T>(arr: T[]): T => arr[0];\n\n// Type alias for function\ntype Predicate<T> = (item: T) => boolean;\nconst isEven: Predicate<number> = n => n % 2 === 0;\n\n// Higher-order with types\nconst compose = <A, B, C>(f: (b: B) => C, g: (a: A) => B) =>\n  (a: A): C => f(g(a));",
    "Rust": "// Closures\nlet square = |x: i32| x * x;\nlet add = |a, b| a + b;\n\n// Multi-line closure\nlet process = |items: Vec<i32>| -> Vec<i32> {\n    items.into_iter().filter(|x| *x > 0).map(|x| x * 2).collect()\n};\n\n// Move closure (takes ownership)\nlet name = String::from(\"Alice\");\nlet greet = move || println!(\"Hello, {}!\", name);\n\n// As function parameter\nfn apply<F: Fn(i32) -> i32>(f: F, x: i32) -> i32 { f(x) }\napply(|x| x * 2, 5);  // 10\n\n// FnOnce, FnMut, Fn\nlet mut count = 0;\nlet mut inc = || { count += 1; count };",
    "Go": "// Function literals\nsquare := func(x int) int { return x * x }\nadd := func(a, b int) int { return a + b }\n\n// Immediately invoked\nresult := func(x, y int) int { return x + y }(3, 4)\n\n// Closure\ncounter := func() func() int {\n    n := 0\n    return func() int { n++; return n }\n}()\ncounter()  // 1\ncounter()  // 2\n\n// As callback\nsort.Slice(items, func(i, j int) bool {\n    return items[i] < items[j]\n})",
    "Java": "// Lambda expressions (Java 8+)\nFunction<Integer, Integer> square = x -> x * x;\nBiFunction<Integer, Integer, Integer> add = (a, b) -> a + b;\nPredicate<Integer> isEven = x -> x % 2 == 0;\nConsumer<String> printer = s -> System.out.println(s);\nSupplier<String> greeting = () -> \"Hello!\";\n\n// Multi-line\nFunction<List<Integer>, List<Integer>> process = items -> {\n    return items.stream()\n        .filter(x -> x > 0)\n        .map(x -> x * 2)\n        .collect(Collectors.toList());\n};\n\n// Method reference (shorthand)\nlist.forEach(System.out::println);\nlist.sort(Comparator.comparingInt(String::length));",
    "C++": "// Lambda expressions (C++11)\nauto square = [](int x) { return x * x; };\nauto add = [](int a, int b) { return a + b; };\n\n// Capture modes\nint factor = 2;\nauto multiply = [factor](int x) { return x * factor; };  // By value\nauto inc = [&factor]() { factor++; };  // By reference\nauto all_val = [=](int x) { return x * factor; };  // All by value\nauto all_ref = [&](int x) { return x * factor; };  // All by ref\n\n// Generic lambda (C++14)\nauto identity = [](auto x) { return x; };\n\n// Mutable\nauto counter = [n = 0]() mutable { return ++n; };\n\n// Immediately invoked\nauto result = [](int x, int y) { return x + y; }(3, 4);",
    "C#": "// Lambda expressions\nFunc<int, int> square = x => x * x;\nFunc<int, int, int> add = (a, b) => a + b;\nPredicate<int> isEven = x => x % 2 == 0;\nAction<string> printer = s => Console.WriteLine(s);\n\n// Statement lambda\nFunc<List<int>, List<int>> process = items => {\n    return items.Where(x => x > 0).Select(x => x * 2).ToList();\n};\n\n// As argument\nvar sorted = list.OrderBy(x => x.Length).ToList();\nvar evens = numbers.Where(x => x % 2 == 0).ToList();\n\n// Discard parameter\nbutton.Click += (_, _) => Console.WriteLine(\"Clicked!\");",
    "Swift": "// Closures\nlet square = { (x: Int) -> Int in x * x }\nlet add: (Int, Int) -> Int = { $0 + $1 }\n\n// Trailing closure\nlet sorted = [3, 1, 4].sorted { $0 < $1 }\nlet mapped = [1, 2, 3].map { $0 * 2 }\n\n// Shorthand argument names\nlet evens = numbers.filter { $0 % 2 == 0 }\n\n// Capturing\nfunc makeCounter() -> () -> Int {\n    var count = 0\n    return { count += 1; return count }\n}\n\n// Autoclosure\nfunc assert(_ condition: @autoclosure () -> Bool) {\n    if !condition() { fatalError() }\n}",
    "Kotlin": "// Lambda\nval square: (Int) -> Int = { it * it }\nval add = { a: Int, b: Int -> a + b }\n\n// Trailing lambda\nlistOf(3, 1, 4).sortedBy { it }\nlistOf(1, 2, 3).map { it * 2 }\nlistOf(1, 2, 3, 4).filter { it % 2 == 0 }\n\n// SAM conversion\nbutton.setOnClickListener { println(\"Clicked!\") }\n\n// With receiver\nval greet: String.() -> String = { \"Hello, $this!\" }\n\"Alice\".greet()  // \"Hello, Alice!\"\n\n// Anonymous function\nval square2 = fun(x: Int): Int = x * x",
    "Ruby": "# Lambda\nsquare = ->(x) { x ** 2 }\nsquare.call(5)  # 25\nsquare.(5)      # 25\nsquare[5]       # 25\n\n# Proc\ndouble = Proc.new { |x| x * 2 }\ndouble.call(5)  # 10\n\n# Block (implicit lambda)\n[1, 2, 3].map { |x| x ** 2 }\n[1, 2, 3, 4].select(&:even?)\n\n# Lambda vs Proc (return behavior)\nlam = lambda { |x| return x * 2 }  # Returns from lambda\nproc = Proc.new { |x| return x * 2 }  # Returns from enclosing\n\n# Method reference\n[1, -2, 3].map(&method(:abs))",
    "Haskell": "-- All functions are lambdas\nsquare = \\x -> x * x\nadd = \\a b -> a + b\n\n-- Sections (partial application of operators)\ndouble = (*2)\nincrement = (+1)\nisPositive = (>0)\n\n-- As arguments\nmap (\\x -> x * x) [1, 2, 3]\nfilter (\\x -> x > 0) [-1, 0, 1, 2]\nsortBy (\\a b -> compare (length a) (length b)) words\n\n-- Composition instead of lambda\nmap ((*2) . (+1)) [1, 2, 3]  -- [4, 6, 8]\n\n-- flip\nflip (\\a b -> a - b) 3 5  -- 2",
    "Scala": "// Lambda\nval square: Int => Int = x => x * x\nval add: (Int, Int) => Int = _ + _\n\n// Placeholder syntax\nList(1, 2, 3).map(_ * 2)\nList(1, 2, 3, 4).filter(_ % 2 == 0)\nList(3, 1, 4).sortBy(_.toString.length)\n\n// Multi-param\nval mult: (Int, Int) => Int = (a, b) => a * b\n\n// Partially applied\ndef add(a: Int)(b: Int): Int = a + b\nval add5 = add(5)_\nadd5(3)  // 8",
    "Elixir": "# Anonymous functions\nsquare = fn x -> x * x end\nsquare.(5)  # 25\n\nadd = fn a, b -> a + b end\nadd.(3, 4)  # 7\n\n# Shorthand capture\nsquare2 = &(&1 * &1)\nadd2 = &(&1 + &2)\n\n# As arguments\nEnum.map([1, 2, 3], fn x -> x * 2 end)\nEnum.map([1, 2, 3], &(&1 * 2))\nEnum.filter([1, 2, 3, 4], &(rem(&1, 2) == 0))\n\n# Multi-clause\nhandle = fn\n  {:ok, val} -> val\n  {:error, _} -> nil\nend",
    "Clojure": ";; fn (anonymous function)\n(fn [x] (* x x))\n((fn [a b] (+ a b)) 3 4)  ;; 7\n\n;; #() reader macro\n(#(* % %) 5)  ;; 25\n(#(+ %1 %2) 3 4)  ;; 7\n\n;; As arguments\n(map #(* % 2) [1 2 3])\n(filter #(> % 0) [-1 0 1 2])\n(sort-by count [\"banana\" \"apple\" \"cherry\"])\n\n;; Partial application\n(def add5 (partial + 5))\n(add5 3)  ;; 8\n\n;; comp\n(def double-inc (comp #(* % 2) inc))\n(double-inc 5)  ;; 12",
    "PHP": "// Arrow functions (PHP 7.4+)\n$square = fn($x) => $x ** 2;\n$add = fn($a, $b) => $a + $b;\n\n// Closures\n$factor = 2;\n$multiply = function($x) use ($factor) {\n    return $x * $factor;\n};\n\n// As callbacks\narray_map(fn($x) => $x * 2, [1, 2, 3]);\narray_filter([1, 2, 3, 4], fn($x) => $x % 2 === 0);\nusort($arr, fn($a, $b) => $a <=> $b);\n\n// IIFE\n$result = (fn($x, $y) => $x + $y)(3, 4);",
    "Dart": "// Arrow function\nint square(int x) => x * x;\nfinal add = (int a, int b) => a + b;\n\n// Anonymous\nfinal multiply = (int x, int factor) {\n  return x * factor;\n};\n\n// As arguments\n[1, 2, 3].map((x) => x * 2).toList();\n[1, 2, 3, 4].where((x) => x % 2 == 0).toList();\n[3, 1, 4].sort((a, b) => a.compareTo(b));\n\n// Tear-off\nvoid printItem(int x) => print(x);\n[1, 2, 3].forEach(printItem);",
    "Julia": "# Anonymous functions\nsquare = x -> x^2\nadd = (a, b) -> a + b\n\n# do block syntax\nmap([1, 2, 3]) do x\n    x * 2\nend\n\nfilter([1, 2, 3, 4]) do x\n    iseven(x)\nend\n\n# As arguments\nsort([\"banana\", \"apple\"], by=length)\nmap(x -> x^2, [1, 2, 3])\nfilter(x -> x > 0, [-1, 0, 1, 2])",
    "Lua": "-- Anonymous function\nlocal square = function(x) return x * x end\nlocal add = function(a, b) return a + b end\n\n-- As arguments\ntable.sort(items, function(a, b) return a < b end)\n\n-- IIFE\nlocal result = (function(x, y) return x + y end)(3, 4)\n\n-- Closure\nlocal function counter()\n    local n = 0\n    return function() n = n + 1; return n end\nend",
    "Nim": "import sugar\n\n# Arrow syntax (sugar module)\nlet square = (x: int) => x * x\nlet add = (a: int, b: int) => a + b\n\n# proc literal\nlet double = proc(x: int): int = x * 2\n\n# As arguments\nlet evens = @[1, 2, 3, 4].filterIt(it mod 2 == 0)\nlet doubled = @[1, 2, 3].mapIt(it * 2)",
    "Crystal": "# Block / Proc\nsquare = ->(x : Int32) { x ** 2 }\nsquare.call(5)  # 25\n\n# Blocks\n[1, 2, 3].map { |x| x ** 2 }\n[1, 2, 3, 4].select(&.even?)\n\n# Short block\n[1, 2, 3].map(&.to_s)",
    "OCaml": "(* Lambda (fun keyword) *)\nlet square = fun x -> x * x\nlet add = fun a b -> a + b\n\n(* As arguments *)\nList.map (fun x -> x * x) [1; 2; 3]\nList.filter (fun x -> x > 0) [-1; 0; 1; 2]\nList.sort (fun a b -> compare (String.length a) (String.length b)) words\n\n(* Immediately applied *)\n(fun x y -> x + y) 3 4  (* 7 *)",
    "F#": "// Lambda\nlet square = fun x -> x * x\nlet add = fun a b -> a + b\n\n// As arguments\n[1; 2; 3] |> List.map (fun x -> x * x)\n[1; 2; 3; 4] |> List.filter (fun x -> x % 2 = 0)\n\n// Pipe operator\n[1; 2; 3]\n|> List.map (fun x -> x * 2)\n|> List.filter (fun x -> x > 2)\n|> List.sum",
    "Erlang": "%% fun keyword\nSquare = fun(X) -> X * X end,\nSquare(5).  %% 25\n\nAdd = fun(A, B) -> A + B end,\n\n%% As arguments\nlists:map(fun(X) -> X * 2 end, [1, 2, 3]).\nlists:filter(fun(X) -> X > 0 end, [-1, 0, 1, 2]).\nlists:sort(fun(A, B) -> A =< B end, [3, 1, 4]).",
    "Zig": "// Function pointers (no closures in Zig)\nconst square = struct {\n    fn call(x: i32) i32 { return x * x; }\n}.call;\n\nconst result = square(5);  // 25\n\n// As parameter\nfn apply(x: i32, f: *const fn(i32) i32) i32 {\n    return f(x);\n}",
    "Racket": ";; Lambda\n(define square (lambda (x) (* x x)))\n(define add (lambda (a b) (+ a b)))\n\n;; Shorthand\n(define square2 (λ (x) (* x x)))\n\n;; As arguments\n(map (lambda (x) (* x 2)) '(1 2 3))\n(filter (lambda (x) (> x 0)) '(-1 0 1 2))\n(sort '(3 1 4) <)\n\n;; Immediately invoked\n((lambda (x y) (+ x y)) 3 4)  ;; 7",
    "D": "// Lambda\nauto square = (int x) => x * x;\nauto add = (int a, int b) => a + b;\n\n// Delegate\nauto multiply = (int x) {\n    return x * 2;\n};\n\n// As arguments\nimport std.algorithm;\n[1, 2, 3].map!(x => x * 2);\n[1, 2, 3, 4].filter!(x => x % 2 == 0);",
    "Perl": "# Anonymous sub\nmy $square = sub { $_[0] ** 2 };\nmy $add = sub { $_[0] + $_[1] };\n\n$square->(5);  # 25\n$add->(3, 4);  # 7\n\n# As arguments\nmy @doubled = map { $_ * 2 } @nums;\nmy @evens = grep { $_ % 2 == 0 } @nums;\nmy @sorted = sort { $a <=> $b } @nums;",
    "R": "# Anonymous function\nsquare <- function(x) x^2\nadd <- function(a, b) a + b\n\n# Shorthand (R 4.1+)\nsquare2 <- \\(x) x^2\n\n# As arguments\nsapply(1:5, function(x) x^2)\nFilter(function(x) x > 0, c(-1, 0, 1, 2))\n\n# purrr\nlibrary(purrr)\nmap_dbl(1:5, ~.x^2)",
    "C": "// No lambdas in C (use function pointers)\nint square(int x) { return x * x; }\nint (*fn_ptr)(int) = square;\nfn_ptr(5);  // 25\n\n// GCC extension: nested functions\nint apply(int x, int (*f)(int)) { return f(x); }\napply(5, square);  // 25\n\n// Blocks (Apple/Clang extension)\n// int (^block)(int) = ^(int x) { return x * x; };",
    "C++": "// See lambda_expressions in C++ above\nauto square = [](int x) { return x * x; };\nauto add = [](auto a, auto b) { return a + b; };\n\n// Immediately invoked\nauto result = [](int x, int y) { return x + y; }(3, 4);\n\n// As std::function\nstd::function<int(int)> fn = [](int x) { return x * x; };",
}

EXPANDED_V5["binary_operations"] = {
    "Python": "# Bitwise operators\na = 0b1100  # 12\nb = 0b1010  # 10\na & b   # AND: 0b1000 (8)\na | b   # OR:  0b1110 (14)\na ^ b   # XOR: 0b0110 (6)\n~a      # NOT: -13\na << 2  # Left shift: 48\na >> 1  # Right shift: 6\n\n# Bit manipulation\ndef is_set(n, bit): return bool(n & (1 << bit))\ndef set_bit(n, bit): return n | (1 << bit)\ndef clear_bit(n, bit): return n & ~(1 << bit)\ndef toggle_bit(n, bit): return n ^ (1 << bit)\n\n# Count bits\nbin(42).count('1')  # popcount\n42 .bit_length()  # 6\n\n# Powers of 2\ndef is_power_of_2(n): return n > 0 and (n & (n - 1)) == 0",
    "JavaScript": "// Bitwise operators\nconst a = 0b1100;  // 12\nconst b = 0b1010;  // 10\na & b;   // AND: 8\na | b;   // OR: 14\na ^ b;   // XOR: 6\n~a;      // NOT: -13\na << 2;  // Left shift: 48\na >> 1;  // Right shift: 6\na >>> 1; // Unsigned right shift: 6\n\n// Bit manipulation\nconst isSet = (n, bit) => (n & (1 << bit)) !== 0;\nconst setBit = (n, bit) => n | (1 << bit);\nconst clearBit = (n, bit) => n & ~(1 << bit);\n\n// BigInt bitwise\nconst big = 1n << 64n;\n\n// Typed arrays for binary data\nconst buf = new ArrayBuffer(4);\nconst view = new DataView(buf);\nview.setUint32(0, 0xDEADBEEF);\nview.getUint8(0);  // 0xDE",
    "Go": "a := 0b1100  // 12\nb := 0b1010  // 10\na & b   // AND: 8\na | b   // OR: 14\na ^ b   // XOR: 6\n^a      // NOT (bitwise complement)\na << 2  // Left shift: 48\na >> 1  // Right shift: 6\na &^ b  // AND NOT (bit clear)\n\nimport \"math/bits\"\nbits.OnesCount(uint(42))  // popcount: 3\nbits.Len(42)  // bit length: 6\nbits.LeadingZeros64(42)\nbits.TrailingZeros64(42)\nbits.RotateLeft64(42, 3)",
    "Rust": "let a: u32 = 0b1100;\nlet b: u32 = 0b1010;\na & b;   // AND: 8\na | b;   // OR: 14\na ^ b;   // XOR: 6\n!a;      // NOT\na << 2;  // Left shift: 48\na >> 1;  // Right shift: 6\n\n// Built-in methods\n42u32.count_ones();   // popcount: 3\n42u32.count_zeros();\n42u32.leading_zeros();\n42u32.trailing_zeros();\n42u32.rotate_left(3);\n42u32.is_power_of_two();  // false\n\n// Checked operations\n255u8.checked_add(1);  // None (overflow)",
    "C": "unsigned a = 0xC;  // 12\nunsigned b = 0xA;  // 10\na & b;   // AND: 8\na | b;   // OR: 14\na ^ b;   // XOR: 6\n~a;      // NOT\na << 2;  // Left shift: 48\na >> 1;  // Right shift: 6\n\n// Bit manipulation\n#define IS_SET(n, bit)    ((n) & (1U << (bit)))\n#define SET_BIT(n, bit)   ((n) | (1U << (bit)))\n#define CLEAR_BIT(n, bit) ((n) & ~(1U << (bit)))\n#define TOGGLE_BIT(n, bit) ((n) ^ (1U << (bit)))\n\n// GCC builtins\n__builtin_popcount(42);   // 3\n__builtin_clz(42);        // leading zeros\n__builtin_ctz(42);        // trailing zeros",
    "C++": "uint32_t a = 0b1100, b = 0b1010;\na & b; a | b; a ^ b; ~a; a << 2; a >> 1;\n\n// C++20 <bit>\n#include <bit>\nstd::popcount(42u);       // 3\nstd::countl_zero(42u);    // leading zeros\nstd::countr_zero(42u);    // trailing zeros\nstd::has_single_bit(16u); // true (power of 2)\nstd::bit_ceil(42u);       // 64\nstd::bit_floor(42u);      // 32\nstd::rotl(42u, 3);\nstd::rotr(42u, 3);\n\n// Bitset\n#include <bitset>\nstd::bitset<8> bits(42);  // 00101010\nbits.count();  // 3\nbits.set(0);   // Set bit 0\nbits.flip();   // Flip all",
    "Java": "int a = 0b1100, b = 0b1010;\na & b;  a | b;  a ^ b;  ~a;  a << 2;  a >> 1;  a >>> 1;\n\n// Integer methods\nInteger.bitCount(42);        // 3\nInteger.highestOneBit(42);   // 32\nInteger.lowestOneBit(42);    // 2\nInteger.numberOfLeadingZeros(42);\nInteger.numberOfTrailingZeros(42);\nInteger.reverse(42);\nInteger.rotateLeft(42, 3);\nInteger.toBinaryString(42);  // \"101010\"\n\n// BitSet\nBitSet bs = new BitSet();\nbs.set(0); bs.set(5);\nbs.get(5);  // true\nbs.cardinality();  // 2",
    "C#": "int a = 0b1100, b = 0b1010;\na & b; a | b; a ^ b; ~a; a << 2; a >> 1; a >>> 1;\n\n// BitOperations (.NET 6+)\nBitOperations.PopCount((uint)42);  // 3\nBitOperations.LeadingZeroCount((uint)42);\nBitOperations.TrailingZeroCount((uint)42);\nBitOperations.IsPow2(16);  // true\nBitOperations.RotateLeft((uint)42, 3);\n\n// Flags enum\n[Flags] enum Perms { None=0, Read=1, Write=2, Exec=4 }\nvar p = Perms.Read | Perms.Write;\np.HasFlag(Perms.Read);  // true",
    "Swift": "let a: UInt8 = 0b1100\nlet b: UInt8 = 0b1010\na & b; a | b; a ^ b; ~a; a << 2; a >> 1\n\n// Bit properties\n42.nonzeroBitCount  // popcount: 3\n42.leadingZeroBitCount\n42.trailingZeroBitCount\n\n// OptionSet (bitflags)\nstruct Permissions: OptionSet {\n    let rawValue: Int\n    static let read = Permissions(rawValue: 1 << 0)\n    static let write = Permissions(rawValue: 1 << 1)\n    static let execute = Permissions(rawValue: 1 << 2)\n}\nlet perms: Permissions = [.read, .write]\nperms.contains(.read)  // true",
    "Kotlin": "val a = 0b1100\nval b = 0b1010\na and b; a or b; a xor b; a.inv(); a shl 2; a shr 1; a ushr 1\n\n// Extension\nInteger.bitCount(42)  // 3\nInteger.toBinaryString(42)  // \"101010\"\n\n// Bit check\nfun Int.hasBit(bit: Int) = this and (1 shl bit) != 0",
    "Ruby": "a = 0b1100  # 12\nb = 0b1010  # 10\na & b  # 8\na | b  # 14\na ^ b  # 6\n~a     # -13\na << 2 # 48\na >> 1 # 6\n\n42.to_s(2)    # \"101010\"\n42.to_s(16)   # \"2a\"\n42.digits(2).count(1)  # popcount: 3\n\n# Bit array\nrequire 'set'\nflags = 0\nflags |= (1 << 3)  # set bit 3\nflags & (1 << 3) != 0  # check bit 3",
    "Haskell": "import Data.Bits\n\nlet a = 12 :: Int  -- 0b1100\nlet b = 10 :: Int  -- 0b1010\na .&. b       -- AND: 8\na .|. b       -- OR: 14\na `xor` b     -- XOR: 6\ncomplement a  -- NOT\nshiftL a 2    -- Left shift: 48\nshiftR a 1    -- Right shift: 6\n\npopCount 42   -- 3\nbit 5 :: Int  -- 32 (set bit 5)\ntestBit 42 1  -- True (bit 1 is set)\nsetBit 42 0   -- 43\nclearBit 42 1 -- 40",
    "Elixir": "import Bitwise\n\na = 0b1100\nb = 0b1010\na &&& b  # AND: 8\na ||| b  # OR: 14\na ^^^ b  # XOR: 6\nbnot(a)  # NOT\na <<< 2  # Left shift: 48\na >>> 1  # Right shift: 6\n\n# Binary pattern matching\n<<a::4, b::4>> = <<0xAB>>\n# a = 0xA, b = 0xB",
    "PHP": "$a = 0b1100; $b = 0b1010;\n$a & $b;  $a | $b;  $a ^ $b;  ~$a;  $a << 2;  $a >> 1;\n\ndecbin(42);  // \"101010\"\nbindec('101010');  // 42\nsubstr_count(decbin(42), '1');  // popcount",
    "Scala": "val a = 0xC; val b = 0xA\na & b; a | b; a ^ b; ~a; a << 2; a >> 1; a >>> 1\n\nInteger.bitCount(42)  // 3\nInteger.toBinaryString(42)  // \"101010\"",
    "Dart": "final a = 0xC, b = 0xA;\na & b; a | b; a ^ b; ~a; a << 2; a >> 1; a >>> 1;\n\n42.toRadixString(2);  // '101010'\n42.bitLength;  // 6",
    "Julia": "a = 0b1100; b = 0b1010\na & b; a | b; a ⊻ b; ~a; a << 2; a >> 1\n\ncount_ones(42)   # 3\nleading_zeros(42)\ntrailing_zeros(42)\nbitstring(42)  # \"00000000000000000000000000101010\"",
    "Lua": "-- Lua 5.3+ bitwise\nlocal a, b = 0xC, 0xA\na & b; a | b; a ~ b; ~a; a << 2; a >> 1",
    "Nim": "let a = 0b1100'u32\nlet b = 0b1010'u32\na and b; a or b; a xor b; not a; a shl 2; a shr 1\n\nimport std/bitops\ncountSetBits(42'u32)  # 3\nfirstSetBit(42'u32)",
    "Crystal": "a = 0b1100_u32; b = 0b1010_u32\na & b; a | b; a ^ b; ~a; a << 2; a >> 1\n\n42.popcount  # 3\n42.to_s(2)   # \"101010\"",
    "OCaml": "let a = 0b1100 and b = 0b1010\na land b   (* AND: 8 *)\na lor b    (* OR: 14 *)\na lxor b   (* XOR: 6 *)\nlnot a     (* NOT *)\na lsl 2    (* Left shift: 48 *)\na lsr 1    (* Logical right shift *)\na asr 1    (* Arithmetic right shift *)",
    "F#": "let a = 0b1100; let b = 0b1010\na &&& b; a ||| b; a ^^^ b; ~~~a; a <<< 2; a >>> 1\n\nSystem.Numerics.BitOperations.PopCount(42u)  // 3",
    "Erlang": "A = 16#C, B = 16#A,\nA band B,  A bor B,  A bxor B,  bnot(A),  A bsl 2,  A bsr 1.",
    "Zig": "const a: u32 = 0b1100;\nconst b: u32 = 0b1010;\na & b; a | b; a ^ b; ~a; a << 2; a >> 1;\n\n@popCount(u32, 42);  // 3\n@clz(u32, 42);       // count leading zeros\n@ctz(u32, 42);       // count trailing zeros",
    "Clojure": "(bit-and 12 10)  ;; 8\n(bit-or 12 10)   ;; 14\n(bit-xor 12 10)  ;; 6\n(bit-not 12)     ;; -13\n(bit-shift-left 12 2)   ;; 48\n(bit-shift-right 12 1)  ;; 6\n(bit-test 42 1)  ;; true\n(bit-set 42 0)   ;; 43\n(bit-clear 42 1) ;; 40\n(Integer/bitCount 42)  ;; 3",
    "Racket": "(bitwise-and 12 10)  ;; 8\n(bitwise-ior 12 10)  ;; 14\n(bitwise-xor 12 10)  ;; 6\n(bitwise-not 12)     ;; -13\n(arithmetic-shift 12 2)   ;; 48 (left)\n(arithmetic-shift 12 -1)  ;; 6 (right)\n(bitwise-bit-set? 42 1)  ;; true",
    "D": "uint a = 0b1100, b = 0b1010;\na & b; a | b; a ^ b; ~a; a << 2; a >> 1;\n\nimport core.bitop;\npopcnt(42);  // 3\nbsf(42);     // bit scan forward\nbsr(42);     // bit scan reverse",
    "Perl": "my $a = 0b1100; my $b = 0b1010;\n$a & $b; $a | $b; $a ^ $b; ~$a; $a << 2; $a >> 1;\n\nsprintf('%b', 42);  # '101010'\n# popcount\nmy $count = unpack('%32b*', pack('N', 42));",
    "R": "a <- 12L; b <- 10L  # Must be integer\nbitwAnd(a, b)  # 8\nbitwOr(a, b)   # 14\nbitwXor(a, b)  # 6\nbitwNot(a)     # -13\nbitwShiftL(a, 2)  # 48\nbitwShiftR(a, 1)  # 6",
    "TypeScript": "const a = 0b1100, b = 0b1010;\na & b; a | b; a ^ b; ~a; a << 2; a >> 1; a >>> 1;\n\n// TypedArrays for binary data\nconst buffer = new ArrayBuffer(4);\nconst view = new DataView(buffer);\nview.setUint32(0, 0xDEADBEEF);\n\n// Popcount\nfunction popcount(n: number): number {\n  let count = 0;\n  while (n) { count += n & 1; n >>>= 1; }\n  return count;\n}",
}

EXPANDED_V5["promises_futures"] = {
    "Python": "import asyncio\n\n# Coroutine (awaitable)\nasync def fetch_data(url: str) -> dict:\n    await asyncio.sleep(1)\n    return {'url': url, 'data': 'result'}\n\n# Gather (parallel)\nasync def main():\n    results = await asyncio.gather(\n        fetch_data('url1'),\n        fetch_data('url2'),\n        fetch_data('url3'),\n    )\n    return results\n\n# Task\nasync def main2():\n    task = asyncio.create_task(fetch_data('url'))\n    # Do other work...\n    result = await task\n\n# Future\nfrom concurrent.futures import ThreadPoolExecutor\ndef blocking_io(): return 'result'\nwith ThreadPoolExecutor() as pool:\n    future = pool.submit(blocking_io)\n    result = future.result(timeout=5)",
    "JavaScript": "// Promise\nconst promise = new Promise((resolve, reject) => {\n  setTimeout(() => resolve('done'), 1000);\n});\n\n// Then/catch\npromise.then(val => console.log(val)).catch(err => console.error(err));\n\n// Async/await\nasync function fetchData(url) {\n  const resp = await fetch(url);\n  return resp.json();\n}\n\n// Promise.all (parallel)\nconst [a, b, c] = await Promise.all([\n  fetchData('url1'),\n  fetchData('url2'),\n  fetchData('url3'),\n]);\n\n// Promise.race\nconst fastest = await Promise.race([fetchData('url1'), fetchData('url2')]);\n\n// Promise.allSettled\nconst results = await Promise.allSettled([p1, p2, p3]);\nresults.forEach(r => r.status === 'fulfilled' ? r.value : r.reason);",
    "TypeScript": "// Typed promises\nfunction fetchUser(id: number): Promise<User> {\n  return fetch(`/api/users/${id}`).then(r => r.json());\n}\n\n// Generic async\nasync function retry<T>(fn: () => Promise<T>, attempts: number): Promise<T> {\n  for (let i = 0; i < attempts; i++) {\n    try { return await fn(); }\n    catch (e) { if (i === attempts - 1) throw e; }\n  }\n  throw new Error('unreachable');\n}\n\n// Promise.all with types\nconst [user, posts]: [User, Post[]] = await Promise.all([\n  fetchUser(1),\n  fetchPosts(1),\n]);",
    "Rust": "// Futures with tokio\nuse tokio;\n\nasync fn fetch_data(url: &str) -> Result<String, reqwest::Error> {\n    reqwest::get(url).await?.text().await\n}\n\n// Join (parallel)\nlet (a, b) = tokio::join!(\n    fetch_data(\"url1\"),\n    fetch_data(\"url2\"),\n);\n\n// Select (race)\ntokio::select! {\n    val = fetch_data(\"url1\") => println!(\"First: {:?}\", val),\n    val = fetch_data(\"url2\") => println!(\"Second: {:?}\", val),\n}\n\n// Spawn task\nlet handle = tokio::spawn(async {\n    fetch_data(\"url\").await\n});\nlet result = handle.await??;",
    "Go": "// Go uses goroutines + channels instead of promises\n\n// Channel as future\nfunc fetchData(url string) <-chan string {\n    ch := make(chan string, 1)\n    go func() {\n        // ... fetch ...\n        ch <- \"result\"\n    }()\n    return ch\n}\n\nresult := <-fetchData(\"url\")\n\n// WaitGroup (await all)\nvar wg sync.WaitGroup\nresults := make([]string, 3)\nfor i, url := range urls {\n    wg.Add(1)\n    go func(i int, url string) {\n        defer wg.Done()\n        results[i] = fetch(url)\n    }(i, url)\n}\nwg.Wait()\n\n// errgroup\ng, ctx := errgroup.WithContext(ctx)\ng.Go(func() error { return fetchInto(ctx, url) })\nif err := g.Wait(); err != nil { log.Fatal(err) }",
    "Java": "// CompletableFuture\nCompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {\n    return fetchData(\"url\");\n});\n\n// Chain\nfuture.thenApply(String::toUpperCase)\n      .thenAccept(System.out::println)\n      .exceptionally(ex -> { System.err.println(ex); return null; });\n\n// AllOf (parallel)\nCompletableFuture.allOf(f1, f2, f3).join();\n\n// AnyOf (race)\nObject fastest = CompletableFuture.anyOf(f1, f2, f3).join();\n\n// Combine\nCompletableFuture<String> combined = f1.thenCombine(f2, (a, b) -> a + b);\n\n// Virtual threads (Java 21)\ntry (var executor = Executors.newVirtualThreadPerTaskExecutor()) {\n    var future = executor.submit(() -> fetchData(\"url\"));\n    String result = future.get();\n}",
    "C#": "// Task<T>\nasync Task<string> FetchData(string url) {\n    var client = new HttpClient();\n    return await client.GetStringAsync(url);\n}\n\n// Parallel\nvar (a, b, c) = await (\n    FetchData(\"url1\"),\n    FetchData(\"url2\"),\n    FetchData(\"url3\")\n);\n\n// WhenAll\nvar results = await Task.WhenAll(tasks);\n\n// WhenAny (race)\nvar fastest = await Task.WhenAny(tasks);\n\n// ContinueWith\nvar task = FetchData(\"url\")\n    .ContinueWith(t => t.Result.ToUpper());\n\n// ValueTask (allocation-free)\nasync ValueTask<int> CachedCompute() {\n    if (_cache != null) return _cache.Value;\n    return await ExpensiveCompute();\n}",
    "Swift": "// async/await (Swift 5.5+)\nfunc fetchData(url: URL) async throws -> Data {\n    let (data, _) = try await URLSession.shared.data(from: url)\n    return data\n}\n\n// TaskGroup (parallel)\nfunc fetchAll(urls: [URL]) async throws -> [Data] {\n    try await withThrowingTaskGroup(of: Data.self) { group in\n        for url in urls {\n            group.addTask { try await fetchData(url: url) }\n        }\n        var results: [Data] = []\n        for try await result in group {\n            results.append(result)\n        }\n        return results\n    }\n}\n\n// Task (fire-and-forget)\nTask { let data = try await fetchData(url: myURL) }",
    "Kotlin": "// Coroutines with Deferred\nimport kotlinx.coroutines.*\n\nsuspend fun fetchData(url: String): String {\n    delay(1000)\n    return \"result\"\n}\n\n// async (parallel)\nrunBlocking {\n    val deferred1 = async { fetchData(\"url1\") }\n    val deferred2 = async { fetchData(\"url2\") }\n    val (r1, r2) = awaitAll(deferred1, deferred2)\n}\n\n// Launch (fire-and-forget)\nCoroutineScope(Dispatchers.IO).launch {\n    val result = fetchData(\"url\")\n    withContext(Dispatchers.Main) { updateUI(result) }\n}",
    "Dart": "// Future\nFuture<String> fetchData(String url) async {\n  await Future.delayed(Duration(seconds: 1));\n  return 'result';\n}\n\n// Then/catchError\nfetchData('url').then((val) => print(val)).catchError((e) => print(e));\n\n// Await\nfinal result = await fetchData('url');\n\n// Future.wait (parallel)\nfinal results = await Future.wait([\n  fetchData('url1'),\n  fetchData('url2'),\n]);\n\n// Completer (manual promise)\nfinal completer = Completer<String>();\ncompleter.complete('done');\nfinal value = await completer.future;",
    "Elixir": "# Task\ntask = Task.async(fn -> fetch_data(\"url\") end)\nresult = Task.await(task)\n\n# Parallel\ntasks = Enum.map(urls, fn url -> Task.async(fn -> fetch_data(url) end) end)\nresults = Enum.map(tasks, &Task.await/1)\n\n# Task.async_stream\nurls\n|> Task.async_stream(fn url -> fetch_data(url) end, max_concurrency: 5)\n|> Enum.to_list()",
    "Scala": "import scala.concurrent.Future\nimport scala.concurrent.ExecutionContext.Implicits.global\n\n// Future\nval future: Future[String] = Future {\n  fetchData(\"url\")\n}\n\n// Map/flatMap\nfuture.map(_.toUpperCase).recover { case e => \"error\" }\n\n// For comprehension (sequential)\nfor {\n  a <- Future { fetchData(\"url1\") }\n  b <- Future { fetchData(\"url2\") }\n} yield (a, b)\n\n// Parallel\nval f1 = Future { fetchData(\"url1\") }\nval f2 = Future { fetchData(\"url2\") }\nval combined = Future.sequence(List(f1, f2))",
    "Haskell": "import Control.Concurrent.Async\n\n-- async\na1 <- async (fetchData \"url1\")\na2 <- async (fetchData \"url2\")\n(r1, r2) <- waitBoth a1 a2\n\n-- mapConcurrently\nresults <- mapConcurrently fetchData urls\n\n-- race\nfastest <- race (fetchData \"url1\") (fetchData \"url2\")\n\n-- MVar (promise-like)\nmvar <- newEmptyMVar\nforkIO $ putMVar mvar (compute value)\nresult <- takeMVar mvar",
    "Clojure": ";; future\n(def f (future (fetch-data \"url\")))\n@f  ;; deref (blocks)\n(deref f 5000 :timeout)  ;; with timeout\n\n;; pmap (parallel map)\n(pmap fetch-data urls)\n\n;; promise\n(def p (promise))\n(deliver p \"result\")\n@p  ;; \"result\"\n\n;; core.async\n(require '[clojure.core.async :as a])\n(a/go (a/<! (a/timeout 1000)) \"done\")",
    "Ruby": "# Async gem or Thread\nrequire 'async'\n\nAsync do |task|\n  result = task.async { fetch_data('url1') }\n  result.wait\nend\n\n# Concurrent::Promises (concurrent-ruby)\nrequire 'concurrent'\nfuture = Concurrent::Promises.future { fetch_data('url') }\nresult = future.value!  # Block until resolved\n\n# Parallel\nfutures = urls.map { |url| Concurrent::Promises.future { fetch_data(url) } }\nresults = futures.map(&:value!)",
    "PHP": "// ReactPHP / Amp\nuse Amp\\Future;\nuse function Amp\\async;\nuse function Amp\\await;\n\n$future = async(function() { return fetchData('url'); });\n$result = $future->await();\n\n// Parallel\n$futures = array_map(fn($url) => async(fn() => fetchData($url)), $urls);\n$results = array_map(fn($f) => $f->await(), $futures);\n\n// Guzzle promises\n$promise = $client->getAsync('url');\n$response = $promise->wait();",
    "Lua": "-- Lua has no built-in promises\n-- Use coroutines as poor man's futures\nlocal function async(fn)\n    local co = coroutine.create(fn)\n    return {\n        await = function()\n            local ok, result = coroutine.resume(co)\n            return result\n        end\n    }\nend\n\nlocal future = async(function()\n    coroutine.yield('computing...')\n    return 'done'\nend)",
    "Julia": "# @async and fetch\ntask = @async begin\n    sleep(1)\n    \"result\"\nend\nresult = fetch(task)\n\n# Parallel\ntasks = [@async fetch_data(url) for url in urls]\nresults = [fetch(t) for t in tasks]\n\n# Threads.@spawn\nusing Base.Threads\nt = @spawn expensive_computation()\nresult = fetch(t)",
    "Nim": "import std/asyncdispatch\n\n# Future\nproc fetchData(url: string): Future[string] {.async.} =\n  await sleepAsync(1000)\n  return \"result\"\n\n# Await\nlet result = waitFor fetchData(\"url\")\n\n# Parallel\nlet f1 = fetchData(\"url1\")\nlet f2 = fetchData(\"url2\")\nlet (r1, r2) = waitFor all(f1, f2)",
    "Erlang": "%% Erlang uses message passing\nPid = spawn(fun() -> Result = fetch(Url), self() ! {self(), Result} end),\nreceive {Pid, Result} -> Result end.\n\n%% rpc\nrpc:async_call(Node, Mod, Fun, Args),\nrpc:yield(Key).",
    "Crystal": "# Fibers and channels\nch = Channel(String).new\nspawn do\n  result = fetch_data(\"url\")\n  ch.send(result)\nend\nresult = ch.receive\n\n# Parallel\nresults = urls.map do |url|\n  Channel(String).new.tap do |ch|\n    spawn { ch.send(fetch_data(url)) }\n  end\nend.map(&.receive)",
    "Zig": "// Zig uses async frames\nconst frame = async fetchData(url);\nconst result = await frame;\n\n// Or use std.Thread\nconst thread = try std.Thread.spawn(.{}, fetchData, .{url});\nthread.join();",
    "F#": "// Async workflows\nlet fetchData url = async {\n    let! response = httpClient.GetStringAsync(url) |> Async.AwaitTask\n    return response\n}\n\n// Parallel\nlet! results = \n    [\"url1\"; \"url2\"; \"url3\"]\n    |> List.map fetchData\n    |> Async.Parallel\n\n// Task computation\nlet fetchTask url = task {\n    let! response = httpClient.GetStringAsync(url)\n    return response\n}",
    "OCaml": "(* Lwt promises *)\nopen Lwt.Syntax\n\nlet fetch_data url =\n  let* body = Cohttp_lwt_unix.Client.get (Uri.of_string url) in\n  Lwt.return body\n\n(* Parallel *)\nlet* (a, b) = Lwt.both (fetch_data \"url1\") (fetch_data \"url2\")\n\n(* Race *)\nlet* result = Lwt.pick [fetch_data \"url1\"; fetch_data \"url2\"]",
    "Racket": "(require racket/future)\n\n(define f (future (lambda () (fetch-data \"url\"))))\n(touch f)  ;; Block until resolved\n\n;; Parallel\n(define futures (map (lambda (url) (future (lambda () (fetch-data url)))) urls))\n(define results (map touch futures))",
    "D": "import std.parallelism;\n\n// Task\nauto task = taskPool.put!(() => fetchData(\"url\"));\nauto result = task.yieldForce();\n\n// Parallel\nauto results = urls.map!(url => taskPool.put!(() => fetchData(url))).array;\nauto values = results.map!(t => t.yieldForce()).array;",
    "Perl": "# Mojo::Promise\nuse Mojo::Promise;\nmy $promise = Mojo::Promise->new;\n$promise->then(sub { print shift })->catch(sub { warn shift });\n$promise->resolve('done');\n\n# Parallel\nMojo::Promise->all(@promises)->then(sub { my @results = @_ });",
    "R": "library(promises)\nlibrary(future)\nplan(multisession)\n\n# Future\nf <- future({ Sys.sleep(1); 42 })\nvalue(f)  # Blocks until resolved\n\n# Promise\npromise <- future_promise({ expensive_computation() })\npromise %...>% { result -> print(result) }",
    "Scala": "// Already covered above in main Scala entry",
}

EXPANDED_V5["metaprogramming"] = {
    "Python": "# Decorators\ndef timer(func):\n    import time\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        print(f'{func.__name__} took {time.time()-start:.3f}s')\n        return result\n    return wrapper\n\n@timer\ndef slow(): import time; time.sleep(1)\n\n# Metaclass\nclass SingletonMeta(type):\n    _instances = {}\n    def __call__(cls, *args, **kwargs):\n        if cls not in cls._instances:\n            cls._instances[cls] = super().__call__(*args, **kwargs)\n        return cls._instances[cls]\n\n# getattr/setattr\ngetattr(obj, 'method_name')()\nsetattr(obj, 'x', 42)\n\n# exec/eval\nexec('x = 42')\nresult = eval('2 + 3')\n\n# inspect\nimport inspect\ninspect.getmembers(obj)",
    "JavaScript": "// Proxy\nconst handler = {\n  get(target, prop) {\n    console.log(`Accessing ${prop}`);\n    return Reflect.get(target, prop);\n  },\n  set(target, prop, value) {\n    console.log(`Setting ${prop} = ${value}`);\n    return Reflect.set(target, prop, value);\n  }\n};\nconst proxy = new Proxy({}, handler);\n\n// Reflect\nReflect.ownKeys(obj);\nReflect.has(obj, 'key');\nReflect.apply(fn, thisArg, args);\n\n// Symbol for meta-behavior\nclass Collection {\n  [Symbol.iterator]() { /* ... */ }\n  [Symbol.toPrimitive](hint) { /* ... */ }\n  get [Symbol.toStringTag]() { return 'Collection'; }\n}\n\n// eval\neval('2 + 3');  // 5 (avoid in production!)",
    "Rust": "// Declarative macros\nmacro_rules! vec_of_strings {\n    ($($x:expr),*) => {\n        vec![$($x.to_string()),*]\n    };\n}\nlet v = vec_of_strings![\"a\", \"b\", \"c\"];\n\n// Derive macros\n#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\nstruct User { name: String, age: u32 }\n\n// Attribute macros\n#[tokio::main]\nasync fn main() { /* ... */ }\n\n// Procedural macros (in separate crate)\n// #[proc_macro_derive(MyTrait)]\n// pub fn my_derive(input: TokenStream) -> TokenStream { ... }",
    "Java": "// Reflection\nClass<?> cls = Class.forName(\"com.example.User\");\nObject obj = cls.getDeclaredConstructor().newInstance();\n\nMethod method = cls.getMethod(\"getName\");\nString name = (String) method.invoke(obj);\n\nField field = cls.getDeclaredField(\"age\");\nfield.setAccessible(true);\nfield.set(obj, 30);\n\n// Annotations\n@Retention(RetentionPolicy.RUNTIME)\n@Target(ElementType.METHOD)\n@interface Benchmark {}\n\n// Annotation processing\nfor (Method m : cls.getMethods()) {\n    if (m.isAnnotationPresent(Benchmark.class)) {\n        long start = System.nanoTime();\n        m.invoke(obj);\n        System.out.println(System.nanoTime() - start);\n    }\n}\n\n// Dynamic proxy\nvar proxy = Proxy.newProxyInstance(loader, interfaces, handler);",
    "C++": "// Templates as metaprogramming\ntemplate<int N>\nstruct Factorial {\n    static constexpr int value = N * Factorial<N-1>::value;\n};\ntemplate<> struct Factorial<0> { static constexpr int value = 1; };\nconstexpr int fact5 = Factorial<5>::value;  // 120\n\n// constexpr (C++17)\nconstexpr int fibonacci(int n) {\n    if (n <= 1) return n;\n    return fibonacci(n-1) + fibonacci(n-2);\n}\n\n// if constexpr (compile-time branching)\ntemplate<typename T>\nauto stringify(T val) {\n    if constexpr (std::is_arithmetic_v<T>)\n        return std::to_string(val);\n    else\n        return std::string(val);\n}\n\n// CRTP pattern\ntemplate<typename Derived>\nstruct Base {\n    void interface() { static_cast<Derived*>(this)->impl(); }\n};",
    "Elixir": "# Macros\ndefmodule MyMacros do\n  defmacro unless(condition, do: block) do\n    quote do\n      if !unquote(condition), do: unquote(block)\n    end\n  end\nend\n\n# quote/unquote\nquote do: 1 + 2  # {:+, [], [1, 2]}\n\n# Module attributes\ndefmodule MyModule do\n  @moduledoc \"My module\"\n  @pi 3.14159\n  Module.register_attribute(__MODULE__, :tags, accumulate: true)\n  @tags :important\n  @tags :reviewed\nend\n\n# __using__ macro\ndefmodule MyBehaviour do\n  defmacro __using__(_opts) do\n    quote do\n      import MyBehaviour\n    end\n  end\nend",
    "Ruby": "# method_missing\nclass DynamicProxy\n  def method_missing(name, *args)\n    puts \"Called: #{name}(#{args.join(', ')})\"\n  end\n  def respond_to_missing?(name, include_private = false)\n    true\n  end\nend\n\n# define_method\nclass MyClass\n  [:hello, :goodbye].each do |name|\n    define_method(name) { puts name }\n  end\nend\n\n# class_eval / instance_eval\nMyClass.class_eval { def dynamic_method; 'dynamic'; end }\n\n# Open classes (monkey patching)\nclass String\n  def shout; upcase + '!!!'; end\nend\n'hello'.shout  # 'HELLO!!!'",
    "Scala": "// Macros (Scala 3)\nimport scala.quoted.*\ninline def debug(inline expr: Any): Unit =\n  ${debugImpl('expr)}\ndef debugImpl(expr: Expr[Any])(using Quotes): Expr[Unit] =\n  '{println(${Expr(expr.show)} + \" = \" + $expr)}\n\n// Implicit conversions\ngiven Conversion[String, Int] = _.toInt\nval x: Int = \"42\"  // Auto-converted\n\n// Type-level programming\ntype If[C <: Boolean, T, F] = C match\n  case true => T\n  case false => F",
    "Haskell": "-- Template Haskell\n{-# LANGUAGE TemplateHaskell #-}\nimport Language.Haskell.TH\n\n-- Generate function at compile time\nmyFunc :: Q [Dec]\nmyFunc = [d|\n  hello :: String\n  hello = \"world\"\n  |]\n\n-- Deriving via\nderiving instance Show MyType\nderiving instance Eq MyType\n\n-- GHC Generics\nclass GSerialize f where\n  gserialize :: f a -> ByteString",
    "Clojure": ";; Macros\n(defmacro unless [condition & body]\n  `(if (not ~condition) (do ~@body)))\n\n(unless false\n  (println \"This runs!\"))\n\n;; Quote/unquote\n`(+ 1 ~(+ 2 3))  ;; (+ 1 5)\n\n;; Macro expansion\n(macroexpand '(unless false (println \"hi\")))\n\n;; eval\n(eval '(+ 1 2 3))  ;; 6\n\n;; Dynamic var creation\n(intern 'user 'dynamic-var 42)",
    "Go": "// Go has limited metaprogramming\n// reflect package\nimport \"reflect\"\n\nv := reflect.ValueOf(obj)\nt := v.Type()\n\n// Iterate fields\nfor i := 0; i < t.NumField(); i++ {\n    field := t.Field(i)\n    fmt.Println(field.Name, field.Type, v.Field(i).Interface())\n}\n\n// Struct tags\ntype User struct {\n    Name string `json:\"name\" validate:\"required\"`\n}\ntag := t.Field(0).Tag.Get(\"json\")  // \"name\"\n\n// go:generate for code generation\n//go:generate stringer -type=Color",
    "Swift": "// Mirror (reflection)\nstruct User { var name: String; var age: Int }\nlet mirror = Mirror(reflecting: User(name: \"Alice\", age: 30))\nfor child in mirror.children {\n    print(\"\\(child.label!): \\(child.value)\")\n}\n\n// Property wrappers\n@propertyWrapper\nstruct Clamped {\n    var wrappedValue: Int {\n        didSet { wrappedValue = min(max(wrappedValue, 0), 100) }\n    }\n}\n\n// Result builders\n@resultBuilder\nstruct StringBuilder {\n    static func buildBlock(_ components: String...) -> String {\n        components.joined(separator: \"\\n\")\n    }\n}",
    "Kotlin": "// Reflection\nimport kotlin.reflect.full.*\n\ndata class User(val name: String, val age: Int)\n\nval cls = User::class\ncls.memberProperties.forEach { println(\"${it.name}: ${it.returnType}\") }\n\n// KClass\nval user = cls.primaryConstructor!!.call(\"Alice\", 30)\n\n// Annotations\n@Target(AnnotationTarget.FUNCTION)\n@Retention(AnnotationRetention.RUNTIME)\nannotation class Benchmark\n\n// Compiler plugins (KSP)\n// @AutoFactory class UserFactory { ... }",
    "C#": "// Reflection\nvar type = typeof(User);\nvar obj = Activator.CreateInstance(type);\n\nforeach (var prop in type.GetProperties()) {\n    Console.WriteLine($\"{prop.Name}: {prop.PropertyType}\");\n}\n\n// Custom attributes\n[AttributeUsage(AttributeTargets.Method)]\nclass BenchmarkAttribute : Attribute {}\n\n// Expression trees\nExpression<Func<int, bool>> expr = x => x > 5;\nvar compiled = expr.Compile();\ncompiled(10);  // true\n\n// Source generators (compile-time)\n[Generator]\npublic class MyGenerator : IIncrementalGenerator { }",
    "PHP": "// Reflection\n$ref = new ReflectionClass('User');\nforeach ($ref->getProperties() as $prop) {\n    echo $prop->getName() . ': ' . $prop->getType() . \"\\n\";\n}\n\n// Magic methods\nclass Dynamic {\n    public function __get($name) { return $this->data[$name] ?? null; }\n    public function __set($name, $value) { $this->data[$name] = $value; }\n    public function __call($name, $args) { echo \"Called: $name\\n\"; }\n}\n\n// Attributes (PHP 8)\n#[Route('/api/users', methods: ['GET'])]\nfunction listUsers() {}",
    "Nim": "# Macros\nimport macros\n\nmacro debug(n: untyped): untyped =\n  let name = n.toStrLit\n  result = quote do:\n    echo `name`, \" = \", `n`\n\nvar x = 42\ndebug(x)  # prints: x = 42\n\n# Templates\ntemplate repeat(count: int, body: untyped) =\n  for _ in 0..<count:\n    body\n\nrepeat(3):\n  echo \"hello\"",
    "D": "// Compile-time function evaluation\nenum factorial = {\n    int result = 1;\n    foreach (i; 2 .. 6) result *= i;\n    return result;\n}();\nstatic assert(factorial == 120);\n\n// Mixins (string to code)\nmixin(\"int x = 42;\");\nassert(x == 42);\n\n// Template mixins\nmixin template Logging() {\n    void log(string msg) { writeln(msg); }\n}\nclass MyClass { mixin Logging; }",
    "Lua": "-- Metatables (core metaprogramming)\nlocal mt = {\n    __index = function(t, k)\n        print('Accessing: ' .. k)\n        return rawget(t, k)\n    end,\n    __newindex = function(t, k, v)\n        print('Setting: ' .. k .. ' = ' .. tostring(v))\n        rawset(t, k, v)\n    end,\n    __tostring = function(t) return 'MyObject' end,\n}\n\nlocal obj = setmetatable({}, mt)\nobj.x = 42  -- Triggers __newindex\nprint(obj.x)  -- Triggers __index",
    "Julia": "# Macros\nmacro debug(expr)\n    return quote\n        println($(string(expr)), \" = \", $(esc(expr)))\n    end\nend\n\nx = 42\n@debug x  # prints: x = 42\n\n# @generated functions\n@generated function mysum(x::NTuple{N, Float64}) where N\n    expr = :(x[1])\n    for i in 2:N\n        expr = :($expr + x[$i])\n    end\n    return expr\nend\n\n# Reflection\nfieldnames(typeof(obj))\nmethodswith(MyType)\n@which sin(1.0)",
    "Perl": "# AUTOLOAD\nsub AUTOLOAD {\n    our $AUTOLOAD;\n    my $method = $AUTOLOAD =~ s/.*:://r;\n    print \"Called: $method\\n\";\n}\n\n# eval\neval 'print \"hello\\n\"';\n\n# Symbol table manipulation\n*{\"MyPackage::$method\"} = sub { \"dynamic\" };\n\n# Moose meta\nmy $meta = MyClass->meta;\nfor my $attr ($meta->get_all_attributes) {\n    print $attr->name, \"\\n\";\n}",
    "R": "# substitute/deparse\nf <- function(x) {\n  deparse(substitute(x))\n}\nf(a + b)  # \"a + b\"\n\n# eval/parse\neval(parse(text = '1 + 2'))  # 3\n\n# Non-standard evaluation\nlibrary(rlang)\nexpr(x + y)\neval_tidy(expr(1 + 2))\n\n# Creating functions dynamically\nmake_adder <- function(n) function(x) x + n\nadd5 <- make_adder(5)\nadd5(3)  # 8",
    "Racket": ";; Macros (hygienic)\n(define-syntax-rule (unless cond body ...)\n  (when (not cond) body ...))\n\n(unless #f (displayln \"runs!\"))\n\n;; syntax-parse\n(define-syntax (my-let stx)\n  (syntax-parse stx\n    [(_ ([var:id val:expr] ...) body:expr ...+)\n     #'(let ([var val] ...) body ...)]))\n\n;; eval\n(eval '(+ 1 2 3))  ;; 6",
    "Erlang": "%% parse_transform (compile-time)\n%% -compile({parse_transform, my_transform}).\n\n%% Dynamic module loading\ncode:load_file(my_module),\napply(my_module, my_function, [Args]).\n\n%% Module info\nmodule_info(my_module).\nmy_module:module_info(exports).",
    "Zig": "// comptime (compile-time execution)\nfn fibonacci(comptime n: u32) u32 {\n    if (n <= 1) return n;\n    return fibonacci(n - 1) + fibonacci(n - 2);\n}\nconst fib10 = fibonacci(10);  // Computed at compile time\n\n// @typeInfo for reflection\nfn printFields(comptime T: type) void {\n    inline for (@typeInfo(T).Struct.fields) |field| {\n        std.debug.print(\"{s}\\n\", .{field.name});\n    }\n}",
    "Crystal": "# Macros\nmacro debug(expr)\n  puts \"#{{{expr.stringify}}} = #{{{expr}}}\"\nend\n\nx = 42\ndebug(x)  # prints: x = 42\n\n# macro hooks\nmacro inherited; end\nmacro included; end\nmacro method_added(name); end",
    "OCaml": "(* PPX (preprocessor extensions) *)\n(* [@@deriving show, eq] *)\ntype point = { x: float; y: float } [@@deriving show, eq]\n\n(* let%bind for monadic syntax *)\nlet%bind result = fetch_data url in\nprocess result",
    "F#": "// Type providers (compile-time metaprogramming)\ntype Csv = CsvProvider<\"data.csv\">\nlet data = Csv.Load(\"data.csv\")\ndata.Rows |> Seq.iter (fun row -> printfn \"%s\" row.Name)\n\n// Quotations\nopen FSharp.Quotations\nlet expr = <@ 1 + 2 @>\n\n// Computation expressions\ntype MaybeBuilder() =\n    member _.Bind(x, f) = Option.bind f x\n    member _.Return(x) = Some x\nlet maybe = MaybeBuilder()",
}


def get_expanded_v5_rosetta():
    """Return all v5 expanded handcrafted entries."""
    entries = []
    idx = 50000
    for concept, lang_codes in EXPANDED_V5.items():
        cn = concept.replace('_', ' ').title()
        for lang, code in lang_codes.items():
            idx += 1
            entries.append({
                "id": f"rosetta_v5_{idx}",
                "concept": concept,
                "concept_name": cn,
                "language": lang,
                "code": code,
                "category": "rosetta_stone",
                "has_code": True,
                "code_lines": len(code.split('\n')),
                "source": "handcrafted",
            })
    return entries
