"""
Knowledge Vault Expansion — Architecture, Mobile, Game Dev, Advanced Testing, Cloud, Functional Programming, Shell
"""
def _e(eid, topic, cat, content, tags=None):
    return {"id": eid, "topic": topic, "category": cat, "content": content, "tags": tags or []}

def get_vault_architecture():
    return [
        _e("kv_arch_clean", "Clean Architecture", "architecture", "Layers (outside→inside): Frameworks→Adapters→UseCases→Entities\nDependency Rule: outer depends on inner, NEVER reverse\n\nEntities: business rules (User, Order)\nUse Cases: application logic (CreateUserUseCase)\nAdapters: controllers, gateways, presenters\nFrameworks: web, DB, external services\n\nclass CreateUserUseCase:\n    def __init__(self, repo, email_svc):\n        self.repo = repo; self.email = email_svc\n    async def execute(self, name, email):\n        user = User(None, name, email)\n        saved = await self.repo.save(user)\n        await self.email.send_welcome(saved)\n        return saved\n\nBenefits: testable, framework-independent, DB-independent", ["architecture","clean-architecture","solid","layers"]),
        _e("kv_arch_microservices", "Microservices", "architecture", "Each service owns its data. Communicate via API/events. Deploy independently.\n\nPatterns:\n1. API Gateway: routing, auth, rate limiting\n2. Circuit Breaker: prevent cascade failures\n3. Saga: distributed transactions (choreography/orchestration)\n4. CQRS: separate read/write models\n5. Event Sourcing: store events, derive state\n6. Sidecar: proxy per service (Envoy/Istio)\n\nComm: Sync (REST/gRPC) | Async (Kafka/RabbitMQ)\nStart monolith → extract services when boundaries emerge", ["architecture","microservices","saga","cqrs","api-gateway"]),
        _e("kv_arch_ddd", "Domain-Driven Design", "architecture", "Value Object: immutable, equality by value (Money, Email)\nEntity: identity, mutable (User, Order)\nAggregate Root: consistency boundary (Order→OrderItems)\nRepository: persistence abstraction\nDomain Event: OrderPlaced, UserRegistered\nBounded Context: explicit boundary with ubiquitous language\n\nSales Context: Customer, Order, Product\nShipping Context: Address, Shipment, Package\nSame concept, different models per context", ["architecture","ddd","domain-driven-design","aggregate","entity"]),
        _e("kv_arch_api_design", "REST API Design", "architecture", "GET /api/users (list) | POST /api/users (create)\nGET /api/users/123 | PUT (replace) | PATCH (partial) | DELETE\n\nPagination: ?page=2&per_page=20\nFiltering: ?status=active&sort=-created_at\nVersioning: /api/v1/users or Accept header\n\nError format: {error: {code, message, details: [{field, message}]}}\n\nBest practices: nouns not verbs, proper status codes, plural nouns, rate limiting 429+Retry-After, HATEOAS", ["architecture","rest","api","design","pagination"]),
        _e("kv_arch_event_driven", "Event-Driven Architecture", "architecture", "Decouple producers from consumers via events.\n\nEvent types: Domain Events, Integration Events, Notifications, State Transfer\n\nEvent Sourcing: store events not state\nevents = [AccountCreated, Deposited(100), Withdrawn(30), Deposited(50)]\nstate = replay(events) → balance=120\n\nPub/Sub: Publisher→EventBus(Kafka)→Subscribers\nBenefits: audit trail, temporal queries, debugging\nChallenges: eventual consistency, schema evolution", ["architecture","event-driven","event-sourcing","pub-sub"]),

        # ═══ MOBILE ═══
        _e("kv_swift", "Swift Essentials", "swift", "let name = \"Alice\"  // immutable\nvar age = 30       // mutable\nvar score: Int? = nil  // optional\n\nif let s = score { print(s) }  // unwrap\nlet v = score ?? 0  // nil coalescing\n\nClosures: numbers.map { $0 * 2 }\nProtocols: protocol Drawable { func draw() }\nAsync: func fetch() async throws -> User { try await URLSession.shared.data(from: url) }\nStructs=value type, Classes=reference type\nEnums with associated values: case success(T), failure(Error)", ["swift","ios","optionals","closures","protocols","async"]),
        _e("kv_kotlin", "Kotlin Essentials", "kotlin", "val name = \"Alice\"  // immutable\nvar age = 30       // mutable\nval score: Int? = null  // nullable\nval len = name?.length ?: 0  // safe call + elvis\n\ndata class User(val name: String, val age: Int)\nfun String.exclaim() = this + \"!\"\nnumbers.filter { it % 2 == 0 }.map { it * 2 }\n\nCoroutines:\nsuspend fun fetch(): User = withContext(Dispatchers.IO) { api.getUser() }\nviewModelScope.launch { val user = fetch() }\n\nSealed classes: sealed class Result { Success(T), Error(msg), Loading }", ["kotlin","android","coroutines","null-safety","data-class"]),

        # ═══ GAME DEV ═══
        _e("kv_gamedev_ecs", "Entity Component System", "gamedev", "ECS separates data (components) from logic (systems).\n\nEntity: just an ID\nComponents: pure data (Position, Velocity, Health, Sprite)\nSystems: logic on components (MovementSystem, RenderSystem)\n\nclass World:\n    def create_entity(self, *components): ...\n    def query(self, *types): return matching entities\n\ndef movement_system(world, dt):\n    for eid, e in world.query(Position, Velocity):\n        e.pos.x += e.vel.dx * dt\n\nBenefits: cache-friendly, composable, easy to add features\nUsed by: Unity DOTS, Bevy (Rust), EnTT (C++)", ["gamedev","ecs","entity-component-system","game-engine"]),
        _e("kv_gamedev_physics", "Game Physics", "gamedev", "AABB collision: a.x < b.x+b.w and a.x+a.w > b.x and a.y < b.y+b.h and a.y+a.h > b.y\nCircle collision: dist(a,b) < a.r + b.r\n\nclass RigidBody:\n    pos, vel, acc, mass\n    def apply_force(f): acc += f/mass\n    def update(dt): vel += acc*dt; pos += vel*dt; acc = 0\n\nGravity: apply_force(Vec2(0, 9.81*mass))\nFriction: vel *= (1 - friction*dt)\nSAT for convex polygon collision\nSpatial partitioning: grid, quadtree, BVH", ["gamedev","physics","collision","vector","aabb"]),

        # ═══ TESTING ═══
        _e("kv_test_api", "API Testing", "testing", "Unit: test business logic in isolation\nIntegration: test with real DB\nE2E: test full HTTP flow\n\nasync def test_user_flow():\n    r = await client.post('/api/users', json=data)\n    assert r.status_code == 201\n    uid = r.json()['id']\n    r = await client.get(f'/api/users/{uid}')\n    assert r.json()['name'] == data['name']\n    r = await client.delete(f'/api/users/{uid}')\n    assert r.status_code == 200\n\nLoad testing: locust, k6, Artillery\nContract testing: Pact\nChaos testing: inject failures", ["testing","api","integration","e2e","load-testing"]),
        _e("kv_test_patterns", "Testing Best Practices", "testing", "AAA: Arrange, Act, Assert\nFIRST: Fast, Independent, Repeatable, Self-validating, Timely\n\nTest doubles: Stub (canned data), Mock (verify interactions), Spy (record), Fake (simplified impl)\n\nProperty-based: @given(st.lists(st.integers())) def test_sort(lst): assert sorted(lst) == sorted(sorted(lst))\n\nFixture factory: def user_factory(**kwargs): return User(**{**defaults, **kwargs})\n\n80% coverage is good. Focus on critical paths, edge cases, error handling.", ["testing","best-practices","fixtures","mocking","tdd"]),

        # ═══ CLOUD ═══
        _e("kv_gcp", "Google Cloud Platform", "cloud", "Compute: Compute Engine (VMs), Cloud Run (serverless containers), Cloud Functions, GKE (K8s)\nStorage: Cloud Storage (S3-like), Persistent Disk\nDB: Cloud SQL, Spanner (global SQL), Firestore (NoSQL), Bigtable, AlloyDB\nData: BigQuery (serverless warehouse), Vertex AI, Pub/Sub, Dataflow\nNetwork: Cloud CDN, DNS, Armor (WAF), Load Balancing\n\nBigQuery: SELECT user_id, COUNT(*) orders, SUM(total) revenue FROM orders GROUP BY 1", ["cloud","gcp","google-cloud","bigquery","cloud-run"]),
        _e("kv_serverless", "Serverless Patterns", "cloud", "API Gateway + Lambda: REST API\nS3 trigger + Lambda: file processing\nSQS + Lambda: async queue\nEventBridge + Lambda: scheduled tasks\nStep Functions: orchestrate workflows\n\nCold start mitigation: provisioned concurrency, smaller packages, faster runtimes (Go>Python>Java)\n\nFrameworks: AWS SAM, Serverless Framework, SST, Terraform\nPricing: per invocation + duration. Free tier: 1M req/mo", ["cloud","serverless","lambda","api-gateway"]),

        # ═══ SHELL & DEVOPS ═══
        _e("kv_bash_advanced", "Advanced Bash", "shell", "set -euo pipefail  # strict mode\narr=(one two three); echo ${arr[@]}\nfor f in *.py; do echo $f; done\nwhile read -r line; do process \"$line\"; done < input.txt\n\nfunction deploy() {\n    local env=\"$1\"\n    [[ \"$env\" == \"prod\" ]] && read -p 'Sure? (y/n) ' -n 1 -r\n    kubectl apply -f \"k8s/$env/\"\n}\n\nOne-liners:\nfind . -name '*.log' -mtime +30 -delete\ndu -sh */ | sort -rh | head -10\ncurl -s url | jq '.data[] | .name'\nwatch -n 5 'kubectl get pods'", ["shell","bash","scripting","automation","one-liners"]),
        _e("kv_terraform", "Terraform IaC", "devops", "resource \"aws_instance\" \"web\" {\n  ami = \"ami-xxx\"\n  instance_type = var.instance_type\n  tags = { Name = \"web\" }\n}\n\nmodule \"vpc\" { source = \"terraform-aws-modules/vpc/aws\" }\n\nterraform init → plan → apply → destroy\nRemote state in S3, workspaces for environments, modules for reuse\noutput \"ip\" { value = aws_instance.web.public_ip }", ["devops","terraform","iac","infrastructure","aws"]),

        # ═══ FUNCTIONAL PROGRAMMING ═══
        _e("kv_fp", "Functional Programming", "functional", "Pure functions: same input→same output, no side effects\nImmutability: return new objects, don't mutate\nHigher-order functions: functions that take/return functions\n\nmap/filter/reduce:\nlist(map(lambda x: x*2, [1,2,3]))  # [2,4,6]\nlist(filter(lambda x: x%2==0, [1,2,3,4]))  # [2,4]\nreduce(lambda a,b: a+b, [1,2,3,4])  # 10\n\nComposition: compose(f, g)(x) = f(g(x))\nCurrying: partial(multiply, 2) → double\nMonads: Optional/Maybe, Result/Either, IO, Future/Promise", ["functional","fp","pure-functions","immutability","composition"]),

        # ═══ ML/AI ═══
        _e("kv_ml_pytorch", "PyTorch Deep Learning", "ml", "class CNN(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.features = nn.Sequential(nn.Conv2d(3,32,3,padding=1), nn.ReLU(), nn.MaxPool2d(2))\n        self.classifier = nn.Sequential(nn.Flatten(), nn.Linear(32*16*16,256), nn.ReLU(), nn.Linear(256,10))\n    def forward(self, x): return self.classifier(self.features(x))\n\noptimizer = optim.Adam(model.parameters(), lr=1e-3)\nfor epoch in range(10):\n    for x,y in loader:\n        loss = criterion(model(x), y)\n        loss.backward(); optimizer.step(); optimizer.zero_grad()", ["ml","pytorch","cnn","deep-learning","training"]),
        _e("kv_ml_sklearn", "scikit-learn", "ml", "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import GridSearchCV, cross_val_score\n\npipe = Pipeline([('scaler', StandardScaler()), ('clf', RandomForestClassifier())])\nparam_grid = {'clf__n_estimators': [50,100,200], 'clf__max_depth': [None,10,20]}\ngrid = GridSearchCV(pipe, param_grid, cv=5, scoring='accuracy')\ngrid.fit(X_train, y_train)\nprint(f'Best: {grid.best_params_} → {grid.best_score_:.4f}')", ["ml","sklearn","classification","pipeline","grid-search"]),
        _e("kv_ml_nlp", "NLP & Transformers", "ml", "from transformers import pipeline\nsentiment = pipeline('sentiment-analysis')\nsentiment('I love this!') # POSITIVE 0.9998\n\nner = pipeline('ner', aggregation_strategy='simple')\nsummarizer = pipeline('summarization')\ntranslator = pipeline('translation_en_to_fr')\n\nTF-IDF: TfidfVectorizer(max_features=5000, ngram_range=(1,2))\nTokenization: word_tokenize, stopwords, lemmatization\nEmbeddings: Word2Vec, GloVe, BERT, sentence-transformers", ["ml","nlp","transformers","huggingface","sentiment"]),
        _e("kv_ml_embeddings", "Embeddings & RAG", "ml", "Words→dense vectors. Similar words are close.\nking - man + woman ≈ queen\n\nRAG (Retrieval-Augmented Generation):\n1. Chunk docs → embed → store in vector DB\n2. Query → embed → find similar chunks\n3. Inject chunks into LLM prompt\n4. LLM generates answer with context\n\nVector DBs: Pinecone, ChromaDB, Weaviate, Qdrant, pgvector\nEmbedding models: text-embedding-3-small, sentence-transformers\nCosine similarity: dot(a,b)/(norm(a)*norm(b))", ["ml","embeddings","vector-search","rag","similarity"]),
        _e("kv_ml_prompting", "LLM Prompt Engineering", "ml", "Roles: system (instructions), user (input), assistant (output)\n\nTechniques:\n1. Zero-shot: direct instruction\n2. Few-shot: provide examples\n3. Chain of thought: 'solve step by step'\n4. ReAct: reason + act\n5. Structured output: 'return JSON: {sentiment, confidence}'\n\nBest practices: be specific, provide context, use delimiters, specify format, set temperature (0=deterministic, 0.7=creative), use max_tokens", ["ml","llm","prompt-engineering","gpt","few-shot"]),
        _e("kv_ml_cv", "Computer Vision", "ml", "img = cv2.imread('img.jpg')\ngray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\nedges = cv2.Canny(gray, 50, 150)\n\nObject detection: YOLO (real-time), SSD, Faster R-CNN\nClassification: ResNet, EfficientNet, ViT\nSegmentation: U-Net, Mask R-CNN\n\nAugmentation: RandomCrop, HorizontalFlip, ColorJitter, Normalize\nPipeline: Resize→Normalize→Augment→CNN→ClassificationHead→CrossEntropyLoss", ["ml","computer-vision","opencv","yolo","cnn"]),

        # ═══ DATA ENGINEERING ═══
        _e("kv_de_spark", "Apache Spark", "data-engineering", "df = spark.read.parquet('s3://bucket/data/')\nresult = df.filter(col('age')>18).groupBy('dept').agg(avg('salary'))\nresult.write.mode('overwrite').parquet('output/')\n\nSQL: df.createOrReplaceTempView('t'); spark.sql('SELECT...')\nWindow: Window.partitionBy('dept').orderBy(col('salary').desc())\n\nConcepts: RDD vs DataFrame, lazy evaluation, partitioning, caching, broadcast joins\nspark.conf.set('spark.sql.shuffle.partitions', 200)", ["data-engineering","spark","pyspark","etl","big-data"]),
        _e("kv_de_kafka_adv", "Kafka Advanced", "data-engineering", "Producer→Topic(partitions)→ConsumerGroups\n\nPatterns: Event Sourcing, CQRS, CDC (Debezium), Stream Processing\n\nGuarantees:\nat-most-once: fire and forget\nat-least-once: ack after process (may duplicate)\nexactly-once: idempotent producer + transactional consumer\n\nRetention: time/size-based, compaction for latest-value\nPartitioning: key-based for ordering, round-robin for throughput", ["data-engineering","kafka","streaming","event-sourcing","cdc"]),
        _e("kv_de_airflow", "Apache Airflow", "data-engineering", "with DAG('daily_etl', schedule='0 6 * * *', catchup=False) as dag:\n    extract = PythonOperator(task_id='extract', python_callable=extract_fn)\n    transform = PythonOperator(task_id='transform', python_callable=transform_fn)\n    load = PostgresOperator(task_id='load', sql='INSERT INTO...')\n    notify = BashOperator(task_id='notify', bash_command='curl slack')\n    extract >> transform >> load >> notify\n\nConcepts: DAGs, operators, sensors, XCom, connections, pools, SLAs", ["data-engineering","airflow","etl","pipeline","scheduling"]),
        _e("kv_de_dbt", "dbt Analytics", "data-engineering", "-- models/fct_daily_revenue.sql\nSELECT DATE_TRUNC('day', ordered_at) AS date,\n  COUNT(DISTINCT order_id) AS orders,\n  SUM(amount) AS revenue\nFROM {{ ref('stg_orders') }}\nGROUP BY 1\n\ndbt run | dbt test | dbt docs generate\nFeatures: refs, sources, macros, snapshots, incremental models, tests\nschema.yml: column tests (unique, not_null, accepted_values)", ["data-engineering","dbt","sql","analytics","warehouse"]),

        # ═══ BLOCKCHAIN ═══
        _e("kv_solidity", "Solidity Smart Contracts", "blockchain", "contract MyToken is ERC20, Ownable {\n    uint256 public constant MAX_SUPPLY = 1_000_000 * 10**18;\n    constructor() ERC20('MyToken','MTK') { _mint(msg.sender, 100_000*10**18); }\n    function mint(address to, uint256 amount) public onlyOwner {\n        require(totalSupply()+amount<=MAX_SUPPLY);\n        _mint(to,amount);\n    }\n}\n\nKey: gas, msg.sender, require/revert, events, modifiers\nSecurity: reentrancy guard, overflow checks, access control\nFrameworks: Hardhat, Foundry", ["blockchain","solidity","smart-contract","ethereum","erc20"]),
        _e("kv_web3", "Web3 Development", "blockchain", "const provider = new ethers.JsonRpcProvider(rpcUrl);\nconst contract = new ethers.Contract(addr, abi, wallet);\nawait contract.transfer(recipient, ethers.parseEther('1.0'));\ncontract.on('Transfer', (from,to,amount) => {...});\n\nWallet connection: MetaMask, WalletConnect\nABI: contract interface definition\nENS: human-readable addresses\nIPFS: decentralized storage for metadata", ["blockchain","web3","ethers","dapp","ethereum"]),

        # ═══ DATABASES ═══
        _e("kv_postgres_adv", "PostgreSQL Advanced", "database", "JSONB: CREATE INDEX USING gin(data); SELECT data->>'key';\nFull-text: to_tsvector('english',content) @@ to_tsquery('python & web');\nPartitioning: PARTITION BY RANGE(created_at);\nMaterialized Views: CREATE MATERIALIZED VIEW mv AS SELECT...; REFRESH CONCURRENTLY;\nLISTEN/NOTIFY for real-time;\nExtensions: PostGIS, pgvector, pg_trgm", ["database","postgresql","jsonb","full-text-search","partitioning"]),
        _e("kv_elasticsearch", "Elasticsearch", "database", "PUT /products/_doc/1 { name, price, category, description }\nGET /products/_search { query: { bool: { must: [match], filter: [range, term] } } }\nAggregations: terms, avg, date_histogram\n\nConcepts: inverted index, analyzers, shards/replicas\nUse: log analysis (ELK), product search, autocomplete\nPython: Elasticsearch() client", ["database","elasticsearch","search","full-text","elk"]),

        # ═══ MATH ═══
        _e("kv_math_discrete", "Discrete Math", "math", "Sets: union, intersection, difference, cartesian product\nCombinatorics: P(n,r)=n!/(n-r)!, C(n,r)=n!/(r!(n-r)!)\nProbability: P(A|B)=P(A∩B)/P(B), E[X]=Σx·P(x)\nGraph theory: V-E+F=2, Σdeg(v)=2|E|, tree has V-1 edges\nLogic: De Morgan ¬(A∧B)=¬A∨¬B, contrapositive\nProofs: induction, contradiction, pigeonhole", ["math","discrete","combinatorics","probability","logic"]),
        _e("kv_math_linalg", "Linear Algebra for ML", "math", "Vectors: dot product (similarity), cross product, norm (magnitude)\nMatrices: multiply (linear transform), inverse, determinant, transpose\nEigenvalues: principal components (PCA)\nSVD: dimensionality reduction, recommender systems\n\nnp.dot(a,b), np.linalg.inv(A), np.linalg.eig(A)\nU,S,Vt = np.linalg.svd(A)\n\nGradient = vector of partial derivatives → optimization", ["math","linear-algebra","eigenvalues","svd","pca"]),

        # ═══ ADDITIONAL DSA ═══
        _e("kv_dsa_trie", "Trie", "algorithms", "class TrieNode:\n    children = {}; is_end = False\n\nclass Trie:\n    def insert(word): walk nodes, create missing, mark end\n    def search(word): walk nodes, check is_end\n    def starts_with(prefix): walk nodes, check exists\n    def autocomplete(prefix): DFS from prefix node\n\nO(m) operations where m=word length\nUses: autocomplete, spell check, IP routing, word games", ["algorithms","trie","prefix-tree","autocomplete"]),
        _e("kv_dsa_segment", "Segment Tree", "algorithms", "Range queries + point updates in O(log n).\n\nbuild: recursively split into halves, store aggregate\nquery(l,r): combine overlapping segments\nupdate(i,val): update leaf, propagate up\n\nUses: range sum, range min/max, count inversions\nLazy propagation: batch range updates O(log n)\nAlternative: Binary Indexed Tree (Fenwick) for prefix sums", ["algorithms","segment-tree","range-query","data-structure"]),
        _e("kv_dsa_heap", "Heap & Priority Queue", "algorithms", "import heapq\nheapq.heappush(h, val)  # O(log n)\nheapq.heappop(h)         # O(log n) remove min\nheapq.heapify(arr)       # O(n)\nheapq.nlargest(k, arr)   # Top K\n\nMax-heap: negate values\nUses: Dijkstra, Kth largest, merge K sorted lists, median stream (two heaps), task scheduling, Huffman encoding", ["algorithms","heap","priority-queue","heapq"]),
        _e("kv_dsa_backtrack", "Backtracking", "algorithms", "Template:\ndef backtrack(state, choices):\n    if is_solution(state): results.append(copy)\n    for choice in choices:\n        if valid(state, choice):\n            state.add(choice)\n            backtrack(state, choices)\n            state.remove(choice)\n\nProblems: N-Queens, Sudoku, permutations, subsets, combination sum, word search, palindrome partitioning", ["algorithms","backtracking","recursion","n-queens"]),
        _e("kv_dsa_sliding", "Sliding Window", "algorithms", "Fixed window: maintain sum, slide right adding new, removing old\nVariable window: expand right until condition met, shrink left to optimize\n\nTwo pointers: lo/hi converging from both ends\n\nProblems: max subarray sum, min window substring, longest substring without repeating, container with most water, 3sum", ["algorithms","sliding-window","two-pointers","substring"]),
    ]
