"""
services/registries/language_packs.py — LANGUAGE_PACK_REGISTRY.

Extracted from server.py (Feb 2026 Phase-8). Pure data: 50+ language pack
definitions grouped by category. No runtime logic.
"""
from __future__ import annotations


LANGUAGE_PACK_REGISTRY = {
    # === SYSTEMS PROGRAMMING ===
    "rust": {
        "name": "Rust",
        "version": "1.75+",
        "category": "systems",
        "icon": "cog",
        "color": "#DEA584",
        "features": ["memory_safety", "zero_cost_abstractions", "ownership", "lifetimes", "cargo"],
        "file_extensions": [".rs"],
        "compiler": "rustc",
        "package_manager": "cargo",
        "paradigms": ["imperative", "functional", "concurrent"],
        "tier": 1,
        "description": "Memory-safe systems programming with zero-cost abstractions"
    },
    "go": {
        "name": "Go",
        "version": "1.22+",
        "category": "systems",
        "icon": "flash",
        "color": "#00ADD8",
        "features": ["goroutines", "channels", "garbage_collection", "fast_compilation"],
        "file_extensions": [".go"],
        "compiler": "go",
        "paradigms": ["imperative", "concurrent"],
        "tier": 1,
        "description": "Fast, simple, concurrent programming language"
    },
    "zig": {
        "name": "Zig",
        "version": "0.12+",
        "category": "systems",
        "icon": "flash-outline",
        "color": "#F7A41D",
        "features": ["comptime", "no_hidden_control_flow", "c_interop", "manual_memory"],
        "file_extensions": [".zig"],
        "compiler": "zig",
        "paradigms": ["imperative"],
        "tier": 2,
        "description": "Modern systems language focused on simplicity"
    },
    "nim": {
        "name": "Nim",
        "version": "2.0+",
        "category": "systems",
        "icon": "diamond",
        "color": "#FFE953",
        "features": ["metaprogramming", "garbage_collection", "c_backend", "python_like_syntax"],
        "file_extensions": [".nim"],
        "compiler": "nim",
        "paradigms": ["imperative", "functional", "oop", "metaprogramming"],
        "tier": 2,
        "description": "Efficient, expressive, elegant"
    },
    "crystal": {
        "name": "Crystal",
        "version": "1.10+",
        "category": "systems",
        "icon": "prism",
        "color": "#000000",
        "features": ["type_inference", "ruby_syntax", "c_bindings", "concurrency"],
        "file_extensions": [".cr"],
        "compiler": "crystal",
        "paradigms": ["oop", "concurrent"],
        "tier": 2,
        "description": "Ruby-like syntax with C-like performance"
    },
    "d": {
        "name": "D",
        "version": "2.106+",
        "category": "systems",
        "icon": "code-slash",
        "color": "#B03931",
        "features": ["templates", "mixins", "ctfe", "garbage_collection"],
        "file_extensions": [".d"],
        "compiler": "dmd",
        "paradigms": ["imperative", "oop", "functional", "metaprogramming"],
        "tier": 2,
        "description": "Systems programming with high-level constructs"
    },
    "v": {
        "name": "V",
        "version": "0.4+",
        "category": "systems",
        "icon": "checkmark",
        "color": "#5D87BF",
        "features": ["fast_compilation", "simple_syntax", "c_interop", "no_gc_option"],
        "file_extensions": [".v"],
        "compiler": "v",
        "paradigms": ["imperative", "functional"],
        "tier": 3,
        "description": "Simple, fast, safe language"
    },
    "odin": {
        "name": "Odin",
        "version": "dev-2024",
        "category": "systems",
        "icon": "flame",
        "color": "#3882D6",
        "features": ["manual_memory", "array_programming", "context_system"],
        "file_extensions": [".odin"],
        "compiler": "odin",
        "paradigms": ["imperative", "data_oriented"],
        "tier": 3,
        "description": "Data-oriented programming language"
    },
    
    # === DATA SCIENCE & SCIENTIFIC ===
    "julia": {
        "name": "Julia",
        "version": "1.10+",
        "category": "scientific",
        "icon": "analytics",
        "color": "#9558B2",
        "features": ["multiple_dispatch", "jit_compilation", "parallelism", "metaprogramming"],
        "file_extensions": [".jl"],
        "compiler": "julia",
        "paradigms": ["functional", "imperative", "metaprogramming"],
        "tier": 1,
        "description": "High-performance scientific computing"
    },
    "r": {
        "name": "R",
        "version": "4.3+",
        "category": "scientific",
        "icon": "stats-chart",
        "color": "#276DC3",
        "features": ["statistical_computing", "data_visualization", "cran_packages"],
        "file_extensions": [".r", ".R"],
        "compiler": "r",
        "paradigms": ["functional", "oop"],
        "tier": 1,
        "description": "Statistical computing and graphics"
    },
    "octave": {
        "name": "GNU Octave",
        "version": "8.4+",
        "category": "scientific",
        "icon": "calculator",
        "color": "#0790C0",
        "features": ["matlab_compatible", "numerical_computing", "plotting"],
        "file_extensions": [".m", ".octave"],
        "compiler": "octave",
        "paradigms": ["imperative", "array"],
        "tier": 2,
        "description": "MATLAB-compatible scientific programming"
    },
    "fortran": {
        "name": "Fortran",
        "version": "2023",
        "category": "scientific",
        "icon": "grid",
        "color": "#4D41BE",
        "features": ["array_operations", "coarrays", "high_performance"],
        "file_extensions": [".f90", ".f95", ".f03", ".f08"],
        "compiler": "gfortran",
        "paradigms": ["imperative", "array", "oop"],
        "tier": 2,
        "description": "High-performance scientific computing legacy"
    },
    "wolfram": {
        "name": "Wolfram",
        "version": "14.0",
        "category": "scientific",
        "icon": "planet",
        "color": "#DD1100",
        "features": ["symbolic_computation", "knowledge_base", "notebook_interface"],
        "file_extensions": [".wl", ".nb"],
        "paradigms": ["functional", "symbolic"],
        "tier": 2,
        "description": "Computational intelligence"
    },
    
    # === WEB & MOBILE ===
    "swift": {
        "name": "Swift",
        "version": "5.9+",
        "category": "mobile",
        "icon": "logo-apple",
        "color": "#F05138",
        "features": ["optionals", "protocols", "generics", "async_await", "actors"],
        "file_extensions": [".swift"],
        "compiler": "swiftc",
        "paradigms": ["oop", "functional", "protocol_oriented"],
        "tier": 1,
        "description": "Apple platforms development"
    },
    "kotlin": {
        "name": "Kotlin",
        "version": "1.9+",
        "category": "mobile",
        "icon": "logo-android",
        "color": "#7F52FF",
        "features": ["null_safety", "coroutines", "extension_functions", "data_classes"],
        "file_extensions": [".kt", ".kts"],
        "compiler": "kotlinc",
        "paradigms": ["oop", "functional"],
        "tier": 1,
        "description": "Modern JVM & Android development"
    },
    "dart": {
        "name": "Dart",
        "version": "3.2+",
        "category": "mobile",
        "icon": "logo-flutter",
        "color": "#0175C2",
        "features": ["null_safety", "async_await", "isolates", "flutter"],
        "file_extensions": [".dart"],
        "compiler": "dart",
        "paradigms": ["oop", "functional"],
        "tier": 1,
        "description": "Flutter & cross-platform development"
    },
    "objective_c": {
        "name": "Objective-C",
        "version": "2.0",
        "category": "mobile",
        "icon": "logo-apple",
        "color": "#438EFF",
        "features": ["message_passing", "dynamic_typing", "categories"],
        "file_extensions": [".m", ".mm", ".h"],
        "compiler": "clang",
        "paradigms": ["oop", "reflective"],
        "tier": 2,
        "description": "Legacy Apple development"
    },
    
    # === FUNCTIONAL PROGRAMMING ===
    "haskell": {
        "name": "Haskell",
        "version": "GHC 9.8",
        "category": "functional",
        "icon": "infinite",
        "color": "#5D4F85",
        "features": ["pure_functional", "lazy_evaluation", "type_classes", "monads"],
        "file_extensions": [".hs", ".lhs"],
        "compiler": "ghc",
        "paradigms": ["pure_functional", "lazy"],
        "tier": 1,
        "description": "Pure functional programming"
    },
    "ocaml": {
        "name": "OCaml",
        "version": "5.1+",
        "category": "functional",
        "icon": "git-branch",
        "color": "#EC6813",
        "features": ["type_inference", "pattern_matching", "modules", "multicore"],
        "file_extensions": [".ml", ".mli"],
        "compiler": "ocaml",
        "paradigms": ["functional", "imperative", "oop"],
        "tier": 1,
        "description": "Industrial-strength functional programming"
    },
    "f_sharp": {
        "name": "F#",
        "version": "8.0",
        "category": "functional",
        "icon": "logo-microsoft",
        "color": "#378BBA",
        "features": ["type_providers", "computation_expressions", "async", "units_of_measure"],
        "file_extensions": [".fs", ".fsx"],
        "compiler": "dotnet",
        "paradigms": ["functional", "oop", "imperative"],
        "tier": 1,
        "description": ".NET functional-first language"
    },
    "elixir": {
        "name": "Elixir",
        "version": "1.16+",
        "category": "functional",
        "icon": "water",
        "color": "#4B275F",
        "features": ["actor_model", "fault_tolerance", "hot_code_swap", "metaprogramming"],
        "file_extensions": [".ex", ".exs"],
        "compiler": "elixir",
        "paradigms": ["functional", "concurrent"],
        "tier": 1,
        "description": "Scalable, fault-tolerant applications"
    },
    "erlang": {
        "name": "Erlang",
        "version": "OTP 26",
        "category": "functional",
        "icon": "pulse",
        "color": "#A90533",
        "features": ["actor_model", "hot_code_swap", "distributed", "fault_tolerant"],
        "file_extensions": [".erl", ".hrl"],
        "compiler": "erlc",
        "paradigms": ["functional", "concurrent"],
        "tier": 2,
        "description": "Telecom-grade distributed systems"
    },
    "clojure": {
        "name": "Clojure",
        "version": "1.11+",
        "category": "functional",
        "icon": "sync",
        "color": "#5881D8",
        "features": ["lisp_syntax", "immutability", "stm", "jvm"],
        "file_extensions": [".clj", ".cljs", ".cljc"],
        "compiler": "clojure",
        "paradigms": ["functional", "lisp"],
        "tier": 2,
        "description": "Dynamic, functional Lisp on JVM"
    },
    "scheme": {
        "name": "Scheme",
        "version": "R7RS",
        "category": "functional",
        "icon": "ellipsis-horizontal",
        "color": "#1E4278",
        "features": ["minimalist", "continuations", "hygienic_macros"],
        "file_extensions": [".scm", ".ss"],
        "compiler": "scheme",
        "paradigms": ["functional", "lisp"],
        "tier": 2,
        "description": "Minimalist Lisp dialect"
    },
    "racket": {
        "name": "Racket",
        "version": "8.11+",
        "category": "functional",
        "icon": "shapes",
        "color": "#9F1D20",
        "features": ["language_oriented", "macros", "contracts", "typed_racket"],
        "file_extensions": [".rkt"],
        "compiler": "racket",
        "paradigms": ["functional", "lisp", "metaprogramming"],
        "tier": 2,
        "description": "Language-oriented programming"
    },
    "common_lisp": {
        "name": "Common Lisp",
        "version": "SBCL 2.4",
        "category": "functional",
        "icon": "ellipsis-vertical",
        "color": "#3FB68B",
        "features": ["clos", "macros", "conditions", "multiple_values"],
        "file_extensions": [".lisp", ".lsp", ".cl"],
        "compiler": "sbcl",
        "paradigms": ["functional", "oop", "metaprogramming"],
        "tier": 2,
        "description": "Powerful, standardized Lisp"
    },
    "purescript": {
        "name": "PureScript",
        "version": "0.15+",
        "category": "functional",
        "icon": "cube-outline",
        "color": "#1D222D",
        "features": ["strict", "row_polymorphism", "effects", "javascript_ffi"],
        "file_extensions": [".purs"],
        "compiler": "purs",
        "paradigms": ["pure_functional"],
        "tier": 3,
        "description": "Strongly-typed functional JS"
    },
    "elm": {
        "name": "Elm",
        "version": "0.19",
        "category": "functional",
        "icon": "leaf",
        "color": "#1293D8",
        "features": ["no_runtime_exceptions", "elm_architecture", "friendly_errors"],
        "file_extensions": [".elm"],
        "compiler": "elm",
        "paradigms": ["pure_functional"],
        "tier": 2,
        "description": "Delightful language for reliable web apps"
    },
    
    # === SCRIPTING & DYNAMIC ===
    "lua": {
        "name": "Lua",
        "version": "5.4+",
        "category": "scripting",
        "icon": "moon",
        "color": "#000080",
        "features": ["embeddable", "coroutines", "metatables", "lightweight"],
        "file_extensions": [".lua"],
        "compiler": "lua",
        "paradigms": ["imperative", "functional", "oop"],
        "tier": 1,
        "description": "Lightweight embeddable scripting"
    },
    "ruby": {
        "name": "Ruby",
        "version": "3.3+",
        "category": "scripting",
        "icon": "diamond",
        "color": "#CC342D",
        "features": ["blocks", "metaprogramming", "duck_typing", "gems"],
        "file_extensions": [".rb", ".rake"],
        "compiler": "ruby",
        "paradigms": ["oop", "functional", "imperative"],
        "tier": 1,
        "description": "Programmer happiness language"
    },
    "perl": {
        "name": "Perl",
        "version": "5.38+",
        "category": "scripting",
        "icon": "text",
        "color": "#39457E",
        "features": ["regex", "cpan", "text_processing", "one_liners"],
        "file_extensions": [".pl", ".pm"],
        "compiler": "perl",
        "paradigms": ["imperative", "functional", "oop"],
        "tier": 2,
        "description": "Practical extraction and reporting"
    },
    "raku": {
        "name": "Raku",
        "version": "2024.01",
        "category": "scripting",
        "icon": "butterfly",
        "color": "#0098FF",
        "features": ["grammars", "concurrency", "unicode", "gradual_typing"],
        "file_extensions": [".raku", ".p6"],
        "compiler": "rakudo",
        "paradigms": ["multi_paradigm"],
        "tier": 3,
        "description": "Expressive multi-paradigm language"
    },
    "php": {
        "name": "PHP",
        "version": "8.3+",
        "category": "scripting",
        "icon": "server",
        "color": "#777BB4",
        "features": ["web_focused", "composer", "type_hints", "attributes"],
        "file_extensions": [".php"],
        "compiler": "php",
        "paradigms": ["oop", "imperative", "functional"],
        "tier": 1,
        "description": "Web development powerhouse"
    },
    "groovy": {
        "name": "Groovy",
        "version": "4.0+",
        "category": "scripting",
        "icon": "musical-note",
        "color": "#4298B8",
        "features": ["dynamic_typing", "closures", "builders", "grape"],
        "file_extensions": [".groovy", ".gvy"],
        "compiler": "groovy",
        "paradigms": ["oop", "functional"],
        "tier": 2,
        "description": "Agile dynamic JVM language"
    },
    "tcl": {
        "name": "Tcl",
        "version": "8.6+",
        "category": "scripting",
        "icon": "terminal",
        "color": "#E5A736",
        "features": ["everything_is_string", "embeddable", "tk_gui"],
        "file_extensions": [".tcl"],
        "compiler": "tclsh",
        "paradigms": ["imperative", "functional"],
        "tier": 3,
        "description": "Tool Command Language"
    },
    
    # === SPECIALIZED & DOMAIN-SPECIFIC ===
    "solidity": {
        "name": "Solidity",
        "version": "0.8+",
        "category": "blockchain",
        "icon": "logo-bitcoin",
        "color": "#363636",
        "features": ["smart_contracts", "evm", "inheritance", "modifiers"],
        "file_extensions": [".sol"],
        "compiler": "solc",
        "paradigms": ["oop", "contract"],
        "tier": 1,
        "description": "Ethereum smart contracts"
    },
    "vyper": {
        "name": "Vyper",
        "version": "0.3+",
        "category": "blockchain",
        "icon": "shield",
        "color": "#333333",
        "features": ["security_focused", "python_like", "evm"],
        "file_extensions": [".vy"],
        "compiler": "vyper",
        "paradigms": ["contract"],
        "tier": 2,
        "description": "Secure smart contract language"
    },
    "move": {
        "name": "Move",
        "version": "1.0",
        "category": "blockchain",
        "icon": "swap-horizontal",
        "color": "#4A90E2",
        "features": ["resource_safety", "linear_types", "formal_verification"],
        "file_extensions": [".move"],
        "compiler": "move",
        "paradigms": ["resource_oriented"],
        "tier": 2,
        "description": "Safe smart contract language"
    },
    "sql": {
        "name": "SQL",
        "version": "SQL:2023",
        "category": "database",
        "icon": "server",
        "color": "#E38C00",
        "features": ["declarative", "relational", "transactions", "views"],
        "file_extensions": [".sql"],
        "paradigms": ["declarative"],
        "tier": 1,
        "description": "Structured Query Language"
    },
    "graphql": {
        "name": "GraphQL",
        "version": "June 2018",
        "category": "api",
        "icon": "git-network",
        "color": "#E10098",
        "features": ["type_system", "queries", "mutations", "subscriptions"],
        "file_extensions": [".graphql", ".gql"],
        "paradigms": ["declarative"],
        "tier": 1,
        "description": "API query language"
    },
    "prolog": {
        "name": "Prolog",
        "version": "SWI 9.0",
        "category": "logic",
        "icon": "help-circle",
        "color": "#E61E14",
        "features": ["unification", "backtracking", "pattern_matching", "constraints"],
        "file_extensions": [".pl", ".pro"],
        "compiler": "swipl",
        "paradigms": ["logic", "declarative"],
        "tier": 2,
        "description": "Logic programming language"
    },
    "coq": {
        "name": "Coq",
        "version": "8.18",
        "category": "proof",
        "icon": "shield-checkmark",
        "color": "#D0B68C",
        "features": ["dependent_types", "proof_assistant", "extraction"],
        "file_extensions": [".v"],
        "compiler": "coqc",
        "paradigms": ["functional", "proof"],
        "tier": 3,
        "description": "Interactive theorem prover"
    },
    "lean": {
        "name": "Lean 4",
        "version": "4.3+",
        "category": "proof",
        "icon": "checkmark-done",
        "color": "#8B5CF6",
        "features": ["dependent_types", "metaprogramming", "mathlib"],
        "file_extensions": [".lean"],
        "compiler": "lean",
        "paradigms": ["functional", "proof"],
        "tier": 2,
        "description": "Theorem prover and programming language"
    },
    "idris": {
        "name": "Idris 2",
        "version": "0.7+",
        "category": "proof",
        "icon": "cube",
        "color": "#B30000",
        "features": ["dependent_types", "linear_types", "totality_checking"],
        "file_extensions": [".idr"],
        "compiler": "idris2",
        "paradigms": ["functional", "dependent"],
        "tier": 3,
        "description": "General-purpose dependently typed"
    },
    "agda": {
        "name": "Agda",
        "version": "2.6+",
        "category": "proof",
        "icon": "infinite",
        "color": "#3D5A80",
        "features": ["dependent_types", "unicode_support", "cubical"],
        "file_extensions": [".agda"],
        "compiler": "agda",
        "paradigms": ["functional", "dependent"],
        "tier": 3,
        "description": "Dependently typed proof assistant"
    },
    
    # === SHELL & CONFIG ===
    "bash": {
        "name": "Bash",
        "version": "5.2+",
        "category": "shell",
        "icon": "terminal",
        "color": "#4EAA25",
        "features": ["scripting", "job_control", "arrays", "functions"],
        "file_extensions": [".sh", ".bash"],
        "compiler": "bash",
        "paradigms": ["imperative"],
        "tier": 1,
        "description": "Bourne Again Shell"
    },
    "powershell": {
        "name": "PowerShell",
        "version": "7.4+",
        "category": "shell",
        "icon": "logo-windows",
        "color": "#012456",
        "features": ["object_pipeline", "cmdlets", "remoting", "dsc"],
        "file_extensions": [".ps1", ".psm1"],
        "compiler": "pwsh",
        "paradigms": ["imperative", "oop"],
        "tier": 1,
        "description": "Task automation and configuration"
    },
    "fish": {
        "name": "Fish",
        "version": "3.7+",
        "category": "shell",
        "icon": "fish",
        "color": "#6B8E23",
        "features": ["autosuggestions", "syntax_highlighting", "web_config"],
        "file_extensions": [".fish"],
        "compiler": "fish",
        "paradigms": ["imperative"],
        "tier": 2,
        "description": "Friendly interactive shell"
    },
    "nushell": {
        "name": "Nushell",
        "version": "0.89+",
        "category": "shell",
        "icon": "git-merge",
        "color": "#4E9A06",
        "features": ["structured_data", "pipelines", "plugins"],
        "file_extensions": [".nu"],
        "compiler": "nu",
        "paradigms": ["functional", "data_oriented"],
        "tier": 2,
        "description": "Modern shell with structured data"
    },
    
    # === MARKUP & CONFIG ===
    "yaml": {
        "name": "YAML",
        "version": "1.2",
        "category": "config",
        "icon": "document-text",
        "color": "#CB171E",
        "features": ["human_readable", "anchors", "multi_document"],
        "file_extensions": [".yaml", ".yml"],
        "paradigms": ["declarative"],
        "tier": 1,
        "description": "Human-readable data serialization"
    },
    "toml": {
        "name": "TOML",
        "version": "1.0",
        "category": "config",
        "icon": "list",
        "color": "#9C4121",
        "features": ["minimal", "unambiguous", "hash_tables"],
        "file_extensions": [".toml"],
        "paradigms": ["declarative"],
        "tier": 1,
        "description": "Tom's Obvious Minimal Language"
    },
    "json": {
        "name": "JSON",
        "version": "ECMA-404",
        "category": "data",
        "icon": "code-slash",
        "color": "#000000",
        "features": ["universal", "lightweight", "self_describing"],
        "file_extensions": [".json", ".jsonc"],
        "paradigms": ["declarative"],
        "tier": 1,
        "description": "JavaScript Object Notation"
    },
    "xml": {
        "name": "XML",
        "version": "1.1",
        "category": "data",
        "icon": "code",
        "color": "#F26522",
        "features": ["hierarchical", "schemas", "namespaces", "xslt"],
        "file_extensions": [".xml", ".xsd", ".xsl"],
        "paradigms": ["declarative"],
        "tier": 1,
        "description": "eXtensible Markup Language"
    },
    "markdown": {
        "name": "Markdown",
        "version": "CommonMark",
        "category": "markup",
        "icon": "document",
        "color": "#000000",
        "features": ["lightweight", "readable", "extensible"],
        "file_extensions": [".md", ".markdown"],
        "paradigms": ["declarative"],
        "tier": 1,
        "description": "Lightweight markup language"
    },
    "latex": {
        "name": "LaTeX",
        "version": "2024",
        "category": "markup",
        "icon": "document-text",
        "color": "#008080",
        "features": ["typesetting", "math", "bibliography", "cross_references"],
        "file_extensions": [".tex", ".sty", ".cls"],
        "compiler": "pdflatex",
        "paradigms": ["declarative"],
        "tier": 2,
        "description": "Professional document typesetting"
    },
    "typst": {
        "name": "Typst",
        "version": "0.10+",
        "category": "markup",
        "icon": "document",
        "color": "#239DAD",
        "features": ["fast_compilation", "scripting", "modern_syntax"],
        "file_extensions": [".typ"],
        "compiler": "typst",
        "paradigms": ["declarative", "scripting"],
        "tier": 2,
        "description": "Modern document preparation"
    },
    
    # === ASSEMBLY & LOW-LEVEL ===
    "assembly_x86": {
        "name": "x86 Assembly",
        "version": "x86-64",
        "category": "assembly",
        "icon": "hardware-chip",
        "color": "#6E6E6E",
        "features": ["direct_hardware", "simd", "system_calls"],
        "file_extensions": [".asm", ".s"],
        "compiler": "nasm",
        "paradigms": ["imperative"],
        "tier": 2,
        "description": "Intel/AMD processor assembly"
    },
    "assembly_arm": {
        "name": "ARM Assembly",
        "version": "ARMv9",
        "category": "assembly",
        "icon": "hardware-chip",
        "color": "#0091BD",
        "features": ["risc", "thumb", "neon"],
        "file_extensions": [".s"],
        "compiler": "as",
        "paradigms": ["imperative"],
        "tier": 2,
        "description": "ARM processor assembly"
    },
    "webassembly": {
        "name": "WebAssembly",
        "version": "2.0",
        "category": "assembly",
        "icon": "globe",
        "color": "#654FF0",
        "features": ["portable", "sandboxed", "fast", "wasi"],
        "file_extensions": [".wat", ".wasm"],
        "compiler": "wat2wasm",
        "paradigms": ["low_level"],
        "tier": 1,
        "description": "Portable binary instruction format"
    },
    "llvm_ir": {
        "name": "LLVM IR",
        "version": "17",
        "category": "assembly",
        "icon": "git-branch",
        "color": "#262D3A",
        "features": ["ssa", "optimization", "portable"],
        "file_extensions": [".ll", ".bc"],
        "compiler": "llc",
        "paradigms": ["low_level"],
        "tier": 2,
        "description": "LLVM Intermediate Representation"
    },
    
    # === HARDWARE DESCRIPTION ===
    "verilog": {
        "name": "Verilog",
        "version": "2005",
        "category": "hardware",
        "icon": "hardware-chip",
        "color": "#4169E1",
        "features": ["hdl", "synthesis", "simulation"],
        "file_extensions": [".v", ".sv"],
        "compiler": "iverilog",
        "paradigms": ["concurrent", "hardware"],
        "tier": 2,
        "description": "Hardware description language"
    },
    "vhdl": {
        "name": "VHDL",
        "version": "2019",
        "category": "hardware",
        "icon": "hardware-chip",
        "color": "#39A845",
        "features": ["strongly_typed", "hdl", "synthesis"],
        "file_extensions": [".vhd", ".vhdl"],
        "compiler": "ghdl",
        "paradigms": ["concurrent", "hardware"],
        "tier": 2,
        "description": "VHSIC Hardware Description Language"
    },
    "chisel": {
        "name": "Chisel",
        "version": "6.0",
        "category": "hardware",
        "icon": "construct",
        "color": "#FF6F00",
        "features": ["scala_embedded", "generators", "firrtl"],
        "file_extensions": [".scala"],
        "paradigms": ["functional", "hardware"],
        "tier": 3,
        "description": "Constructing Hardware in Scala"
    },
    "spinalhdl": {
        "name": "SpinalHDL",
        "version": "1.9+",
        "category": "hardware",
        "icon": "git-network",
        "color": "#E91E63",
        "features": ["scala_based", "simulation", "formal"],
        "file_extensions": [".scala"],
        "paradigms": ["functional", "hardware"],
        "tier": 3,
        "description": "Scala-based HDL"
    },
}


__all__ = ["LANGUAGE_PACK_REGISTRY"]
