/**
 * GalaxyStudioFactoryModal.styles
 * -------------------------------------------------------------------
 * Extracted from GalaxyStudioFactoryModal.tsx on 2026-05-15 to keep
 * the host file under the AST/parser timeout threshold.
 *
 * No behavior change — these are the exact StyleSheet definitions
 * previously inlined at the bottom of the modal component, plus the
 * `T` palette derived from /theme/tokens.
 *
 * NOTE: `subtext` was referenced by `juiceHint` but never declared on
 * the `T` palette in the original file. We add a safe fallback (alias
 * to textMuted) here so the style does not log a "color: undefined"
 * warning at runtime.
 */
import { Platform, StyleSheet } from 'react-native';
import GLOBAL_THEME from '../../theme/tokens';

export const T = {
  bg:           GLOBAL_THEME.colors.bg,
  surface:      GLOBAL_THEME.colors.bgElevated,
  surfaceAlt:   GLOBAL_THEME.colors.bgSubtle,
  surfaceLight: GLOBAL_THEME.colors.bgMuted,
  accent:       GLOBAL_THEME.colors.primary,
  accentLight:  GLOBAL_THEME.palette.brand[400],
  accentDim:    GLOBAL_THEME.palette.brand[700],
  success:      GLOBAL_THEME.colors.success,
  warning:      GLOBAL_THEME.colors.warning,
  danger:       GLOBAL_THEME.colors.danger,
  text:         GLOBAL_THEME.colors.text,
  textDim:      GLOBAL_THEME.colors.textMuted,
  textMuted:    GLOBAL_THEME.colors.textDim,
  subtext:      GLOBAL_THEME.colors.textDim,   // alias — preserves juiceHint behavior
  border:       GLOBAL_THEME.colors.border,
  bgSecondary:  GLOBAL_THEME.colors.bgSubtle,
  gold:         GLOBAL_THEME.colors.accentGold,
  cyan:         GLOBAL_THEME.colors.accentCyan,
  pink:         GLOBAL_THEME.colors.accentPink,
};

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: T.bg },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingTop: Platform.OS === 'ios' ? 56 : 14, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: T.border, backgroundColor: T.surface },
  headerBtn: { padding: 6 },
  headerTitle: { color: T.text, fontSize: 17, fontWeight: '800' },
  headerSub: { color: T.accentLight, fontSize: 10, marginTop: 1 },
  pickContent: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 20 },
  pickPrompt: { color: T.textMuted, fontSize: 14, textAlign: 'center', paddingVertical: 6 },
  selectedBanner: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: T.surface, borderRadius: 10, padding: 10, borderWidth: 1, marginBottom: 8 },
  selectedName: { fontSize: 15, fontWeight: '700' },
  selectedSub: { color: T.textDim, fontSize: 11, marginTop: 1, textTransform: 'capitalize' },
  titleInput: { backgroundColor: T.surface, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, color: T.text, fontSize: 15, borderWidth: 1, borderColor: T.border, marginBottom: 6 },
  buildBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: T.accent, borderRadius: 12, paddingVertical: 14, marginBottom: 10 },
  buildBtnText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  buildBtnSub: { color: '#ffffff88', fontSize: 11, fontWeight: '600' },
  descToggle: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 6, justifyContent: 'center', marginBottom: 4 },
  descToggleText: { color: T.accent, fontSize: 13, fontWeight: '700' },
  descBadge: { backgroundColor: T.accent + '20', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8 },
  descBadgeText: { color: T.accentLight, fontSize: 11, fontWeight: '700' },
  descSection: { gap: 8, marginBottom: 8 },
  descCard: { backgroundColor: T.surfaceAlt, borderRadius: 10, padding: 10, borderWidth: 1, borderColor: T.border },
  descCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 3 },
  descCardTitle: { color: T.text, fontSize: 13, fontWeight: '700', flex: 1 },
  descOk: { fontSize: 12, fontWeight: '700' },
  descCardHint: { color: T.textMuted, fontSize: 10, marginBottom: 5, lineHeight: 14 },
  descInput: { backgroundColor: T.bg, borderRadius: 8, padding: 10, color: T.text, fontSize: 13, minHeight: 56, maxHeight: 120, textAlignVertical: 'top', borderWidth: 1, borderColor: T.border },
  descCount: { color: T.textMuted, fontSize: 9, textAlign: 'right', marginTop: 2 },
  fileTierBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, borderWidth: 1 },
  fileTierBadgeText: { fontSize: 9, fontWeight: '800', letterSpacing: 0.6 },
  fileValueRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 4, marginBottom: 2 },
  fileValueBig: { fontSize: 26, fontWeight: '800', letterSpacing: -0.6 },
  fileValueUnit: { color: T.textMuted, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
  fileScaleRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 0, marginBottom: 8 },
  fileScaleLabel: { color: T.textMuted, fontSize: 9, fontWeight: '700' },
  filePresetRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 },
  filePresetChip: { flexGrow: 1, flexBasis: '18%', minWidth: 56, paddingVertical: 6, paddingHorizontal: 8, borderRadius: 8, backgroundColor: T.bg, borderWidth: 1, borderColor: T.border, alignItems: 'center' },
  filePresetLabel: { color: T.text, fontSize: 12, fontWeight: '800', letterSpacing: -0.2 },
  filePresetTag: { color: T.textMuted, fontSize: 8, fontWeight: '700', letterSpacing: 0.4, marginTop: 1, textTransform: 'uppercase' },
  fileMeter: { height: 3, backgroundColor: T.border, borderRadius: 999, marginTop: 10, overflow: 'hidden' },
  fileMeterFill: { height: '100%', borderRadius: 999 },
  dismissKeyboardBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, marginTop: 4, backgroundColor: T.surface, borderRadius: 8, borderWidth: 1, borderColor: T.border },
  juiceCard: { backgroundColor: T.surface, borderRadius: 12, borderWidth: 1, borderColor: '#F59E0B40', padding: 12, marginTop: 4 },
  juiceLabel: { color: '#F59E0B', fontSize: 13, fontWeight: '700' },
  juiceTier: { color: '#F59E0B', fontSize: 11, fontWeight: '700', textTransform: 'uppercase' },
  juiceHint: { color: T.subtext, fontSize: 10.5, lineHeight: 14, marginBottom: 4 },
  dismissKeyboardText: { color: T.accentLight, fontSize: 12, fontWeight: '600' },
  searchBar: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: T.surface, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: T.border, marginBottom: 8 },
  searchInput: { flex: 1, color: T.text, fontSize: 13, padding: 0 },
  genreCard: { backgroundColor: T.surface, borderRadius: 12, padding: 12, marginBottom: 6, borderWidth: 1, borderColor: T.border },
  genreRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  genreName: { color: T.text, fontSize: 15, fontWeight: '700' },
  genreDesc: { color: T.textMuted, fontSize: 11, marginTop: 1 },
  genreBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  genreBadgeText: { fontSize: 13, fontWeight: '800' },
  genreExpanded: { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: T.border },
  subRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
  subChip: { backgroundColor: T.surfaceLight, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 5, borderWidth: 1, borderColor: T.border },
  subChipText: { color: T.textDim, fontSize: 11, fontWeight: '600', textTransform: 'capitalize' },
  buildHero: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, gap: 12 },
  pulseCradle: { width: 72, height: 72, alignItems: 'center', justifyContent: 'center' },
  pulseRingFar: { position: 'absolute', width: 72, height: 72, borderRadius: 36, borderWidth: 2, borderColor: '#8B5CF6' },
  pulseRingNear: { position: 'absolute', width: 52, height: 52, borderRadius: 26, borderWidth: 2, borderColor: '#a78bfa', backgroundColor: 'rgba(139, 92, 246, 0.18)' },
  liveBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'rgba(239, 68, 68, 0.12)', borderColor: '#EF4444', borderWidth: 1, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10 },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#EF4444' },
  liveBadgeText: { color: '#EF4444', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  animPanel: { backgroundColor: 'rgba(139, 92, 246, 0.08)', borderWidth: 1, borderColor: 'rgba(139, 92, 246, 0.35)', borderRadius: 12, padding: 12, marginBottom: 12 },
  animPanelTitle: { color: T.text, fontSize: 14, fontWeight: '800', marginLeft: 8, flex: 1 },
  animCountPill: { backgroundColor: T.accent + '22', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3 },
  animCountPillText: { color: T.accent, fontSize: 11, fontWeight: '800' },
  animHint: { color: T.textMuted, fontSize: 11, lineHeight: 16 },
  animStyleChip: { paddingHorizontal: 14, paddingVertical: 8, marginRight: 8, borderRadius: 10, backgroundColor: T.surfaceLight, borderWidth: 1, borderColor: 'transparent', minWidth: 96, alignItems: 'center' },
  animStyleChipActive: { backgroundColor: T.accent + '26', borderColor: T.accent },
  animStyleText: { color: T.text, fontSize: 12, fontWeight: '800' },
  animStyleHint: { color: T.textMuted, fontSize: 10, marginTop: 2 },
  animToggle: { flexDirection: 'row', alignItems: 'center', padding: 10, marginTop: 10, borderRadius: 10, backgroundColor: T.surfaceLight, borderWidth: 1, borderColor: 'transparent' },
  animToggleActive: { borderColor: T.accent, backgroundColor: T.accent + '15' },
  animToggleLabel: { color: T.text, fontSize: 13, fontWeight: '700' },
  animToggleHint: { color: T.textMuted, fontSize: 11, marginTop: 2 },
  buildTitle: { color: T.text, fontSize: 20, fontWeight: '900' },
  buildSub: { color: T.accentLight, fontSize: 12, marginTop: 2 },
  timerRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  timerBox: { flex: 1, alignItems: 'center', gap: 4, backgroundColor: T.surface, borderRadius: 10, padding: 10, borderWidth: 1, borderColor: T.cyan + '30' },
  timerText: { color: T.cyan, fontSize: 15, fontWeight: '800' },
  timerLabel: { color: T.textMuted, fontSize: 9 },
  progressWrap: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 6 },
  progressBg: { flex: 1, height: 10, backgroundColor: T.surfaceLight, borderRadius: 5, overflow: 'hidden' },
  progressFill: { height: 10, borderRadius: 5, backgroundColor: T.accent, overflow: 'hidden' },
  progressShimmer: { position: 'absolute', top: 0, bottom: 0, width: 80, backgroundColor: 'rgba(255, 255, 255, 0.35)' },
  progressPct: { color: T.text, fontSize: 14, fontWeight: '800', width: 40, textAlign: 'right' },
  phaseGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginVertical: 8 },
  batchChip: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: T.surface, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: T.border, width: '48%' as any, minWidth: 140 },
  batchChipTitle: { color: T.textDim, fontSize: 11, fontWeight: '700' },
  batchChipSub: { color: T.textMuted, fontSize: 9, marginTop: 1 },
  phaseChip: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: T.surface, borderRadius: 5, paddingHorizontal: 6, paddingVertical: 4, borderWidth: 1, borderColor: T.border },
  phaseChipText: { color: T.textMuted, fontSize: 9, fontWeight: '600', maxWidth: 70 },
  phaseDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: T.border },
  batchIndicator: { backgroundColor: T.surfaceAlt, borderRadius: 10, padding: 10, marginBottom: 6, borderWidth: 1, borderColor: T.accent + '30' },
  batchIndicatorHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  batchIndicatorTitle: { color: T.accent, fontSize: 15, fontWeight: '800' },
  batchIndicatorName: { color: T.accentLight, fontSize: 12, fontWeight: '600', flex: 1 },
  batchIndicatorSub: { color: T.textMuted, fontSize: 11, marginTop: 4 },
  logBox: { flex: 1, backgroundColor: T.surface, borderRadius: 10, padding: 12, marginTop: 6, marginBottom: 10 },
  logRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginBottom: 4 },
  logText: { color: T.textDim, fontSize: 11, flex: 1, lineHeight: 16 },
  previewWrap: { backgroundColor: T.surfaceAlt, borderRadius: 10, padding: 8, marginHorizontal: 4, marginBottom: 8, borderWidth: 1, borderColor: T.accent + '25' },
  previewHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6, paddingHorizontal: 4 },
  previewTitle: { color: T.text, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5, flex: 1 },
  previewCount: { color: T.accent, fontSize: 10, fontWeight: '700' },
  previewChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: T.surface, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 6, borderWidth: 1, gap: 8, minWidth: 140, maxWidth: 220 },
  previewExt: { paddingHorizontal: 5, paddingVertical: 2, borderRadius: 4 },
  previewExtText: { fontSize: 9, fontWeight: '800', textTransform: 'uppercase' },
  previewName: { color: T.text, fontSize: 11, fontWeight: '600' },
  previewSize: { color: T.textDim, fontSize: 9, marginTop: 1 },
  logPulse: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingTop: 6, borderTopWidth: 0.5, borderTopColor: T.border, marginTop: 4 },
  logPulseText: { color: T.textMuted, fontSize: 10 },
  doneHero: { alignItems: 'center', paddingTop: 20, paddingBottom: 8, gap: 4 },
  doneTitle: { color: T.text, fontSize: 24, fontWeight: '900', marginTop: 4 },
  doneSub: { color: T.accentLight, fontSize: 13 },
  statsBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: T.surface, borderRadius: 12, padding: 14, marginVertical: 12, borderWidth: 1, borderColor: T.border },
  statBox: { flex: 1, alignItems: 'center' },
  statNum: { color: T.accent, fontSize: 20, fontWeight: '900' },
  statLabel: { color: T.textMuted, fontSize: 10, marginTop: 2 },
  statDivider: { width: 1, height: 30, backgroundColor: T.border },
  statusBar: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 12, backgroundColor: T.surface, borderRadius: 10, borderWidth: 1, marginBottom: 8 },
  statusText: { fontSize: 12, fontWeight: '600', flex: 1 },
  actionGroup: { gap: 8, marginBottom: 12 },
  actionBtn: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 14, padding: 16 },
  actionBtnTitle: { color: '#fff', fontSize: 15, fontWeight: '700' },
  actionBtnSub: { color: '#ffffff88', fontSize: 11, marginTop: 1 },
  actionRow: { flexDirection: 'row', gap: 8 },
  actionBtnSmall: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 12, borderWidth: 1, backgroundColor: T.surface },
  actionBtnSmallText: { fontSize: 14, fontWeight: '700' },
  expandSection: { backgroundColor: T.surfaceAlt, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: T.border, marginBottom: 12 },
  expandTitle: { color: T.text, fontSize: 15, fontWeight: '800' },
  expandDesc: { color: T.textMuted, fontSize: 12, marginTop: 2 },
  expandGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  expandBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, borderWidth: 1, backgroundColor: T.surface, minHeight: 44, minWidth: 100 },
  expandBtnText: { fontSize: 13, fontWeight: '700' },
  vaultHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 16 },
  vaultTitle: { color: '#34D399', fontSize: 20, fontWeight: '800', flex: 1 },
  vaultSection: { marginBottom: 12 },
  vaultSectionTitle: { color: T.textMuted, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 },
  vaultItem: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, paddingHorizontal: 12, backgroundColor: T.surface, borderRadius: 12, marginBottom: 8, borderWidth: 1, borderColor: T.border, minHeight: 56 },
  vaultItemTitle: { color: T.text, fontSize: 14, fontWeight: '700' },
  vaultItemSub: { color: T.textMuted, fontSize: 12, marginTop: 2 },
  vaultEmpty: { color: T.textMuted, fontSize: 14, textAlign: 'center', paddingVertical: 40 },
  fileSection: { marginTop: 4, marginBottom: 8 },
  fileSectionTitle: { color: T.text, fontSize: 14, fontWeight: '700', marginBottom: 8 },
  fileRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8, borderBottomWidth: 0.5, borderBottomColor: T.border },
  fileName: { flex: 1, color: T.text, fontSize: 12, fontWeight: '600' },
  fileSize: { color: T.textMuted, fontSize: 10 },
  showAllBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12 },
  showAllText: { color: T.accent, fontSize: 13, fontWeight: '700' },
  codeBack: { flexDirection: 'row', alignItems: 'center', gap: 6, padding: 12 },
  codeBackText: { color: T.accentLight, fontSize: 14, fontWeight: '600' },
  codeHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: T.border },
  codePath: { flex: 1, color: T.text, fontSize: 12, fontWeight: '600' },
  codeLineCount: { color: T.textMuted, fontSize: 10 },
  codeScroll: { flex: 1, backgroundColor: '#0a0a12', padding: 12 },
  codeText: { color: '#BFDBFE', fontSize: 11, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', lineHeight: 17 },
  codeStatsRow: { flexDirection: 'row', paddingHorizontal: 14, paddingVertical: 8, gap: 16, borderBottomWidth: 1, borderBottomColor: T.border },
  codeStat: { alignItems: 'center' },
  codeStatVal: { color: T.accent, fontSize: 16, fontWeight: '800' },
  codeStatLabel: { color: T.textMuted, fontSize: 10 },
  newBuildBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, marginTop: 4 },
  newBuildText: { color: T.accent, fontSize: 14, fontWeight: '700' },
  // Wave-3 — Galaxy-build cross-route bridges (Share / Copy / Build Hub / Playground)
  gxBridgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12, paddingHorizontal: 2 },
  gxBridgeBtn: { flex: 1, minWidth: 100, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 9, paddingHorizontal: 8, borderRadius: 8, borderWidth: 1 },
  gxBridgeText: { fontSize: 10, fontWeight: '800' },
});
