"""Transactional workspace observation and recovery for policy-bound shell execution."""

from skeleton.shells.workspace_txn.backup import BackupError, ContentAddressedBackupStore
from skeleton.shells.workspace_txn.batch import BatchItem, BatchPolicy, BatchResult, WorkspaceTransactionBatch
from skeleton.shells.workspace_txn.diff import DiffConfig, WorkspaceDiffer
from skeleton.shells.workspace_txn.journal import JournalEvent, JournalPersistenceError, TransactionJournal
from skeleton.shells.workspace_txn.lease import (
    WorkspaceLease,
    WorkspaceLeaseError,
    WorkspaceLeaseHeartbeat,
    WorkspaceLeaseRegistry,
)
from skeleton.shells.workspace_txn.metrics import TransactionMetricSnapshot, TransactionMetrics
from skeleton.shells.workspace_txn.pathing import (
    PathMatcher,
    PathSet,
    WorkspacePathError,
    collapse_paths,
    lexical_join_under_root,
    normalize_relative_path,
    parent_paths,
    path_depth,
    resolved_join_under_root,
    root_fingerprint,
)
from skeleton.shells.workspace_txn.policy import (
    PolicyCatalog,
    WorkspaceMutationPolicy,
    default_safe_policy,
    generated_output_policy,
    source_edit_policy,
)
from skeleton.shells.workspace_txn.profiles import PROFILE_FACTORIES, build_profile
from skeleton.shells.workspace_txn.recovery import RecoveryCandidate, RecoveryEvidence, TransactionRecoveryInspector
from skeleton.shells.workspace_txn.report import TransactionSummary, format_text, summarize
from skeleton.shells.workspace_txn.rollback import RollbackError, WorkspaceRollback, build_rollback_actions
from skeleton.shells.workspace_txn.rules import (
    DeleteRule,
    ExecutableBitRule,
    ExtensionDenyRule,
    FilenameDenyRule,
    MaxBytesRule,
    MaxChangesRule,
    MaxDepthRule,
    MaxFileSizeRule,
    MaxKindRule,
    MutationRule,
    PathAllowRule,
    PathDenyRule,
    RegexPathDenyRule,
    SymlinkMutationRule,
    evaluate_rules,
)
from skeleton.shells.workspace_txn.scanner import (
    ScannerConfig,
    WorkspaceScanError,
    WorkspaceScanner,
    snapshot_digest,
    snapshot_entry_state,
)
from skeleton.shells.workspace_txn.state_machine import TransactionStateMachine, TransitionDecision
from skeleton.shells.workspace_txn.transaction import TransactionConfig, WorkspaceTransactionManager
from skeleton.shells.workspace_txn.types import (
    BackupManifest,
    BackupRecord,
    ChangeSet,
    ChangeStatistics,
    MutationDecision,
    PolicyViolation,
    RollbackAction,
    RollbackActionKind,
    RollbackActionResult,
    RollbackActionState,
    RollbackReport,
    ScanLimits,
    ScanStatistics,
    SnapshotEntry,
    TransactionReceipt,
    TransactionResult,
    WorkspaceChange,
    WorkspaceChangeKind,
    WorkspaceEntryKind,
    WorkspaceSnapshot,
    WorkspaceTransactionState,
)
from skeleton.shells.workspace_txn.verify import TransactionVerification, TransactionVerifier, VerificationFinding

__all__ = [
    "BackupError",
    "ContentAddressedBackupStore",
    "BatchItem",
    "BatchPolicy",
    "BatchResult",
    "WorkspaceTransactionBatch",
    "DiffConfig",
    "WorkspaceDiffer",
    "JournalEvent",
    "JournalPersistenceError",
    "TransactionJournal",
    "WorkspaceLease",
    "WorkspaceLeaseError",
    "WorkspaceLeaseHeartbeat",
    "WorkspaceLeaseRegistry",
    "TransactionMetricSnapshot",
    "TransactionMetrics",
    "PathMatcher",
    "PathSet",
    "WorkspacePathError",
    "collapse_paths",
    "lexical_join_under_root",
    "normalize_relative_path",
    "parent_paths",
    "path_depth",
    "resolved_join_under_root",
    "root_fingerprint",
    "PolicyCatalog",
    "WorkspaceMutationPolicy",
    "default_safe_policy",
    "generated_output_policy",
    "source_edit_policy",
    "PROFILE_FACTORIES",
    "build_profile",
    "RecoveryCandidate",
    "RecoveryEvidence",
    "TransactionRecoveryInspector",
    "TransactionSummary",
    "format_text",
    "summarize",
    "RollbackError",
    "WorkspaceRollback",
    "build_rollback_actions",
    "DeleteRule",
    "ExecutableBitRule",
    "ExtensionDenyRule",
    "FilenameDenyRule",
    "MaxBytesRule",
    "MaxChangesRule",
    "MaxDepthRule",
    "MaxFileSizeRule",
    "MaxKindRule",
    "MutationRule",
    "PathAllowRule",
    "PathDenyRule",
    "RegexPathDenyRule",
    "SymlinkMutationRule",
    "evaluate_rules",
    "ScannerConfig",
    "WorkspaceScanError",
    "WorkspaceScanner",
    "snapshot_digest",
    "snapshot_entry_state",
    "TransactionStateMachine",
    "TransitionDecision",
    "TransactionConfig",
    "WorkspaceTransactionManager",
    "BackupManifest",
    "BackupRecord",
    "ChangeSet",
    "ChangeStatistics",
    "MutationDecision",
    "PolicyViolation",
    "RollbackAction",
    "RollbackActionKind",
    "RollbackActionResult",
    "RollbackActionState",
    "RollbackReport",
    "ScanLimits",
    "ScanStatistics",
    "SnapshotEntry",
    "TransactionReceipt",
    "TransactionResult",
    "WorkspaceChange",
    "WorkspaceChangeKind",
    "WorkspaceEntryKind",
    "WorkspaceSnapshot",
    "WorkspaceTransactionState",
    "TransactionVerification",
    "TransactionVerifier",
    "VerificationFinding",
]
