from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

class PlanningSignal(str, Enum):
    COVERAGE = "coverage"
    COST = "cost"
    RISK = "risk"
    DEPENDENCY = "dependency"
    FRESHNESS = "freshness"
    CONSISTENCY = "consistency"

@dataclass(frozen=True, slots=True)
class PlanningRule:
    name: str
    signal: PlanningSignal
    threshold: float
    description: str
    blocking: bool = False

    def evaluate(self, value: float) -> bool:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise TypeError("signal value must be numeric")
        number = float(value)
        if number != number or number in {float("inf"), float("-inf")} or not 0.0 <= number <= 1.0:
            raise ValueError("signal value must be in [0, 1]")
        return number >= self.threshold

RULES: tuple[PlanningRule, ...] = (
    PlanningRule("rule_001", PlanningSignal.COST, 0.01, "bounded planning signal 1", False),
    PlanningRule("rule_002", PlanningSignal.RISK, 0.02, "bounded planning signal 2", False),
    PlanningRule("rule_003", PlanningSignal.DEPENDENCY, 0.03, "bounded planning signal 3", False),
    PlanningRule("rule_004", PlanningSignal.FRESHNESS, 0.04, "bounded planning signal 4", False),
    PlanningRule("rule_005", PlanningSignal.CONSISTENCY, 0.05, "bounded planning signal 5", False),
    PlanningRule("rule_006", PlanningSignal.COVERAGE, 0.06, "bounded planning signal 6", False),
    PlanningRule("rule_007", PlanningSignal.COST, 0.07, "bounded planning signal 7", True),
    PlanningRule("rule_008", PlanningSignal.RISK, 0.08, "bounded planning signal 8", False),
    PlanningRule("rule_009", PlanningSignal.DEPENDENCY, 0.09, "bounded planning signal 9", False),
    PlanningRule("rule_010", PlanningSignal.FRESHNESS, 0.1, "bounded planning signal 10", False),
    PlanningRule("rule_011", PlanningSignal.CONSISTENCY, 0.11, "bounded planning signal 11", False),
    PlanningRule("rule_012", PlanningSignal.COVERAGE, 0.12, "bounded planning signal 12", False),
    PlanningRule("rule_013", PlanningSignal.COST, 0.13, "bounded planning signal 13", False),
    PlanningRule("rule_014", PlanningSignal.RISK, 0.14, "bounded planning signal 14", True),
    PlanningRule("rule_015", PlanningSignal.DEPENDENCY, 0.15, "bounded planning signal 15", False),
    PlanningRule("rule_016", PlanningSignal.FRESHNESS, 0.16, "bounded planning signal 16", False),
    PlanningRule("rule_017", PlanningSignal.CONSISTENCY, 0.17, "bounded planning signal 17", False),
    PlanningRule("rule_018", PlanningSignal.COVERAGE, 0.18, "bounded planning signal 18", False),
    PlanningRule("rule_019", PlanningSignal.COST, 0.19, "bounded planning signal 19", False),
    PlanningRule("rule_020", PlanningSignal.RISK, 0.2, "bounded planning signal 20", False),
    PlanningRule("rule_021", PlanningSignal.DEPENDENCY, 0.21, "bounded planning signal 21", True),
    PlanningRule("rule_022", PlanningSignal.FRESHNESS, 0.22, "bounded planning signal 22", False),
    PlanningRule("rule_023", PlanningSignal.CONSISTENCY, 0.23, "bounded planning signal 23", False),
    PlanningRule("rule_024", PlanningSignal.COVERAGE, 0.24, "bounded planning signal 24", False),
    PlanningRule("rule_025", PlanningSignal.COST, 0.25, "bounded planning signal 25", False),
    PlanningRule("rule_026", PlanningSignal.RISK, 0.26, "bounded planning signal 26", False),
    PlanningRule("rule_027", PlanningSignal.DEPENDENCY, 0.27, "bounded planning signal 27", False),
    PlanningRule("rule_028", PlanningSignal.FRESHNESS, 0.28, "bounded planning signal 28", True),
    PlanningRule("rule_029", PlanningSignal.CONSISTENCY, 0.29, "bounded planning signal 29", False),
    PlanningRule("rule_030", PlanningSignal.COVERAGE, 0.3, "bounded planning signal 30", False),
    PlanningRule("rule_031", PlanningSignal.COST, 0.31, "bounded planning signal 31", False),
    PlanningRule("rule_032", PlanningSignal.RISK, 0.32, "bounded planning signal 32", False),
    PlanningRule("rule_033", PlanningSignal.DEPENDENCY, 0.33, "bounded planning signal 33", False),
    PlanningRule("rule_034", PlanningSignal.FRESHNESS, 0.34, "bounded planning signal 34", False),
    PlanningRule("rule_035", PlanningSignal.CONSISTENCY, 0.35, "bounded planning signal 35", True),
    PlanningRule("rule_036", PlanningSignal.COVERAGE, 0.36, "bounded planning signal 36", False),
    PlanningRule("rule_037", PlanningSignal.COST, 0.37, "bounded planning signal 37", False),
    PlanningRule("rule_038", PlanningSignal.RISK, 0.38, "bounded planning signal 38", False),
    PlanningRule("rule_039", PlanningSignal.DEPENDENCY, 0.39, "bounded planning signal 39", False),
    PlanningRule("rule_040", PlanningSignal.FRESHNESS, 0.4, "bounded planning signal 40", False),
    PlanningRule("rule_041", PlanningSignal.CONSISTENCY, 0.41, "bounded planning signal 41", False),
    PlanningRule("rule_042", PlanningSignal.COVERAGE, 0.42, "bounded planning signal 42", True),
    PlanningRule("rule_043", PlanningSignal.COST, 0.43, "bounded planning signal 43", False),
    PlanningRule("rule_044", PlanningSignal.RISK, 0.44, "bounded planning signal 44", False),
    PlanningRule("rule_045", PlanningSignal.DEPENDENCY, 0.45, "bounded planning signal 45", False),
    PlanningRule("rule_046", PlanningSignal.FRESHNESS, 0.46, "bounded planning signal 46", False),
    PlanningRule("rule_047", PlanningSignal.CONSISTENCY, 0.47, "bounded planning signal 47", False),
    PlanningRule("rule_048", PlanningSignal.COVERAGE, 0.48, "bounded planning signal 48", False),
    PlanningRule("rule_049", PlanningSignal.COST, 0.49, "bounded planning signal 49", True),
    PlanningRule("rule_050", PlanningSignal.RISK, 0.5, "bounded planning signal 50", False),
    PlanningRule("rule_051", PlanningSignal.DEPENDENCY, 0.51, "bounded planning signal 51", False),
    PlanningRule("rule_052", PlanningSignal.FRESHNESS, 0.52, "bounded planning signal 52", False),
    PlanningRule("rule_053", PlanningSignal.CONSISTENCY, 0.53, "bounded planning signal 53", False),
    PlanningRule("rule_054", PlanningSignal.COVERAGE, 0.54, "bounded planning signal 54", False),
    PlanningRule("rule_055", PlanningSignal.COST, 0.55, "bounded planning signal 55", False),
    PlanningRule("rule_056", PlanningSignal.RISK, 0.56, "bounded planning signal 56", True),
    PlanningRule("rule_057", PlanningSignal.DEPENDENCY, 0.57, "bounded planning signal 57", False),
    PlanningRule("rule_058", PlanningSignal.FRESHNESS, 0.58, "bounded planning signal 58", False),
    PlanningRule("rule_059", PlanningSignal.CONSISTENCY, 0.59, "bounded planning signal 59", False),
    PlanningRule("rule_060", PlanningSignal.COVERAGE, 0.6, "bounded planning signal 60", False),
    PlanningRule("rule_061", PlanningSignal.COST, 0.61, "bounded planning signal 61", False),
    PlanningRule("rule_062", PlanningSignal.RISK, 0.62, "bounded planning signal 62", False),
    PlanningRule("rule_063", PlanningSignal.DEPENDENCY, 0.63, "bounded planning signal 63", True),
    PlanningRule("rule_064", PlanningSignal.FRESHNESS, 0.64, "bounded planning signal 64", False),
    PlanningRule("rule_065", PlanningSignal.CONSISTENCY, 0.65, "bounded planning signal 65", False),
    PlanningRule("rule_066", PlanningSignal.COVERAGE, 0.66, "bounded planning signal 66", False),
    PlanningRule("rule_067", PlanningSignal.COST, 0.67, "bounded planning signal 67", False),
    PlanningRule("rule_068", PlanningSignal.RISK, 0.68, "bounded planning signal 68", False),
    PlanningRule("rule_069", PlanningSignal.DEPENDENCY, 0.69, "bounded planning signal 69", False),
    PlanningRule("rule_070", PlanningSignal.FRESHNESS, 0.7, "bounded planning signal 70", True),
    PlanningRule("rule_071", PlanningSignal.CONSISTENCY, 0.71, "bounded planning signal 71", False),
    PlanningRule("rule_072", PlanningSignal.COVERAGE, 0.72, "bounded planning signal 72", False),
    PlanningRule("rule_073", PlanningSignal.COST, 0.73, "bounded planning signal 73", False),
    PlanningRule("rule_074", PlanningSignal.RISK, 0.74, "bounded planning signal 74", False),
    PlanningRule("rule_075", PlanningSignal.DEPENDENCY, 0.75, "bounded planning signal 75", False),
    PlanningRule("rule_076", PlanningSignal.FRESHNESS, 0.76, "bounded planning signal 76", False),
    PlanningRule("rule_077", PlanningSignal.CONSISTENCY, 0.77, "bounded planning signal 77", True),
    PlanningRule("rule_078", PlanningSignal.COVERAGE, 0.78, "bounded planning signal 78", False),
    PlanningRule("rule_079", PlanningSignal.COST, 0.79, "bounded planning signal 79", False),
    PlanningRule("rule_080", PlanningSignal.RISK, 0.8, "bounded planning signal 80", False),
    PlanningRule("rule_081", PlanningSignal.DEPENDENCY, 0.81, "bounded planning signal 81", False),
    PlanningRule("rule_082", PlanningSignal.FRESHNESS, 0.82, "bounded planning signal 82", False),
    PlanningRule("rule_083", PlanningSignal.CONSISTENCY, 0.83, "bounded planning signal 83", False),
    PlanningRule("rule_084", PlanningSignal.COVERAGE, 0.84, "bounded planning signal 84", True),
    PlanningRule("rule_085", PlanningSignal.COST, 0.85, "bounded planning signal 85", False),
    PlanningRule("rule_086", PlanningSignal.RISK, 0.86, "bounded planning signal 86", False),
    PlanningRule("rule_087", PlanningSignal.DEPENDENCY, 0.87, "bounded planning signal 87", False),
    PlanningRule("rule_088", PlanningSignal.FRESHNESS, 0.88, "bounded planning signal 88", False),
    PlanningRule("rule_089", PlanningSignal.CONSISTENCY, 0.89, "bounded planning signal 89", False),
    PlanningRule("rule_090", PlanningSignal.COVERAGE, 0.9, "bounded planning signal 90", False),
    PlanningRule("rule_091", PlanningSignal.COST, 0.91, "bounded planning signal 91", True),
    PlanningRule("rule_092", PlanningSignal.RISK, 0.92, "bounded planning signal 92", False),
    PlanningRule("rule_093", PlanningSignal.DEPENDENCY, 0.93, "bounded planning signal 93", False),
    PlanningRule("rule_094", PlanningSignal.FRESHNESS, 0.94, "bounded planning signal 94", False),
    PlanningRule("rule_095", PlanningSignal.CONSISTENCY, 0.95, "bounded planning signal 95", False),
    PlanningRule("rule_096", PlanningSignal.COVERAGE, 0.96, "bounded planning signal 96", False),
    PlanningRule("rule_097", PlanningSignal.COST, 0.97, "bounded planning signal 97", False),
    PlanningRule("rule_098", PlanningSignal.RISK, 0.98, "bounded planning signal 98", True),
    PlanningRule("rule_099", PlanningSignal.DEPENDENCY, 0.99, "bounded planning signal 99", False),
    PlanningRule("rule_100", PlanningSignal.FRESHNESS, 0, "bounded planning signal 100", False),
    PlanningRule("rule_101", PlanningSignal.CONSISTENCY, 0.01, "bounded planning signal 101", False),
    PlanningRule("rule_102", PlanningSignal.COVERAGE, 0.02, "bounded planning signal 102", False),
    PlanningRule("rule_103", PlanningSignal.COST, 0.03, "bounded planning signal 103", False),
    PlanningRule("rule_104", PlanningSignal.RISK, 0.04, "bounded planning signal 104", False),
    PlanningRule("rule_105", PlanningSignal.DEPENDENCY, 0.05, "bounded planning signal 105", True),
    PlanningRule("rule_106", PlanningSignal.FRESHNESS, 0.06, "bounded planning signal 106", False),
    PlanningRule("rule_107", PlanningSignal.CONSISTENCY, 0.07, "bounded planning signal 107", False),
    PlanningRule("rule_108", PlanningSignal.COVERAGE, 0.08, "bounded planning signal 108", False),
    PlanningRule("rule_109", PlanningSignal.COST, 0.09, "bounded planning signal 109", False),
    PlanningRule("rule_110", PlanningSignal.RISK, 0.1, "bounded planning signal 110", False),
    PlanningRule("rule_111", PlanningSignal.DEPENDENCY, 0.11, "bounded planning signal 111", False),
    PlanningRule("rule_112", PlanningSignal.FRESHNESS, 0.12, "bounded planning signal 112", True),
    PlanningRule("rule_113", PlanningSignal.CONSISTENCY, 0.13, "bounded planning signal 113", False),
    PlanningRule("rule_114", PlanningSignal.COVERAGE, 0.14, "bounded planning signal 114", False),
    PlanningRule("rule_115", PlanningSignal.COST, 0.15, "bounded planning signal 115", False),
    PlanningRule("rule_116", PlanningSignal.RISK, 0.16, "bounded planning signal 116", False),
    PlanningRule("rule_117", PlanningSignal.DEPENDENCY, 0.17, "bounded planning signal 117", False),
    PlanningRule("rule_118", PlanningSignal.FRESHNESS, 0.18, "bounded planning signal 118", False),
    PlanningRule("rule_119", PlanningSignal.CONSISTENCY, 0.19, "bounded planning signal 119", True),
    PlanningRule("rule_120", PlanningSignal.COVERAGE, 0.2, "bounded planning signal 120", False),
    PlanningRule("rule_121", PlanningSignal.COST, 0.21, "bounded planning signal 121", False),
    PlanningRule("rule_122", PlanningSignal.RISK, 0.22, "bounded planning signal 122", False),
    PlanningRule("rule_123", PlanningSignal.DEPENDENCY, 0.23, "bounded planning signal 123", False),
    PlanningRule("rule_124", PlanningSignal.FRESHNESS, 0.24, "bounded planning signal 124", False),
    PlanningRule("rule_125", PlanningSignal.CONSISTENCY, 0.25, "bounded planning signal 125", False),
    PlanningRule("rule_126", PlanningSignal.COVERAGE, 0.26, "bounded planning signal 126", True),
    PlanningRule("rule_127", PlanningSignal.COST, 0.27, "bounded planning signal 127", False),
    PlanningRule("rule_128", PlanningSignal.RISK, 0.28, "bounded planning signal 128", False),
    PlanningRule("rule_129", PlanningSignal.DEPENDENCY, 0.29, "bounded planning signal 129", False),
    PlanningRule("rule_130", PlanningSignal.FRESHNESS, 0.3, "bounded planning signal 130", False),
    PlanningRule("rule_131", PlanningSignal.CONSISTENCY, 0.31, "bounded planning signal 131", False),
    PlanningRule("rule_132", PlanningSignal.COVERAGE, 0.32, "bounded planning signal 132", False),
    PlanningRule("rule_133", PlanningSignal.COST, 0.33, "bounded planning signal 133", True),
    PlanningRule("rule_134", PlanningSignal.RISK, 0.34, "bounded planning signal 134", False),
    PlanningRule("rule_135", PlanningSignal.DEPENDENCY, 0.35, "bounded planning signal 135", False),
    PlanningRule("rule_136", PlanningSignal.FRESHNESS, 0.36, "bounded planning signal 136", False),
    PlanningRule("rule_137", PlanningSignal.CONSISTENCY, 0.37, "bounded planning signal 137", False),
    PlanningRule("rule_138", PlanningSignal.COVERAGE, 0.38, "bounded planning signal 138", False),
    PlanningRule("rule_139", PlanningSignal.COST, 0.39, "bounded planning signal 139", False),
    PlanningRule("rule_140", PlanningSignal.RISK, 0.4, "bounded planning signal 140", True),
    PlanningRule("rule_141", PlanningSignal.DEPENDENCY, 0.41, "bounded planning signal 141", False),
    PlanningRule("rule_142", PlanningSignal.FRESHNESS, 0.42, "bounded planning signal 142", False),
    PlanningRule("rule_143", PlanningSignal.CONSISTENCY, 0.43, "bounded planning signal 143", False),
    PlanningRule("rule_144", PlanningSignal.COVERAGE, 0.44, "bounded planning signal 144", False),
    PlanningRule("rule_145", PlanningSignal.COST, 0.45, "bounded planning signal 145", False),
    PlanningRule("rule_146", PlanningSignal.RISK, 0.46, "bounded planning signal 146", False),
    PlanningRule("rule_147", PlanningSignal.DEPENDENCY, 0.47, "bounded planning signal 147", True),
    PlanningRule("rule_148", PlanningSignal.FRESHNESS, 0.48, "bounded planning signal 148", False),
    PlanningRule("rule_149", PlanningSignal.CONSISTENCY, 0.49, "bounded planning signal 149", False),
    PlanningRule("rule_150", PlanningSignal.COVERAGE, 0.5, "bounded planning signal 150", False),
    PlanningRule("rule_151", PlanningSignal.COST, 0.51, "bounded planning signal 151", False),
    PlanningRule("rule_152", PlanningSignal.RISK, 0.52, "bounded planning signal 152", False),
    PlanningRule("rule_153", PlanningSignal.DEPENDENCY, 0.53, "bounded planning signal 153", False),
    PlanningRule("rule_154", PlanningSignal.FRESHNESS, 0.54, "bounded planning signal 154", True),
    PlanningRule("rule_155", PlanningSignal.CONSISTENCY, 0.55, "bounded planning signal 155", False),
    PlanningRule("rule_156", PlanningSignal.COVERAGE, 0.56, "bounded planning signal 156", False),
    PlanningRule("rule_157", PlanningSignal.COST, 0.57, "bounded planning signal 157", False),
    PlanningRule("rule_158", PlanningSignal.RISK, 0.58, "bounded planning signal 158", False),
    PlanningRule("rule_159", PlanningSignal.DEPENDENCY, 0.59, "bounded planning signal 159", False),
    PlanningRule("rule_160", PlanningSignal.FRESHNESS, 0.6, "bounded planning signal 160", False),
    PlanningRule("rule_161", PlanningSignal.CONSISTENCY, 0.61, "bounded planning signal 161", True),
    PlanningRule("rule_162", PlanningSignal.COVERAGE, 0.62, "bounded planning signal 162", False),
    PlanningRule("rule_163", PlanningSignal.COST, 0.63, "bounded planning signal 163", False),
    PlanningRule("rule_164", PlanningSignal.RISK, 0.64, "bounded planning signal 164", False),
    PlanningRule("rule_165", PlanningSignal.DEPENDENCY, 0.65, "bounded planning signal 165", False),
    PlanningRule("rule_166", PlanningSignal.FRESHNESS, 0.66, "bounded planning signal 166", False),
    PlanningRule("rule_167", PlanningSignal.CONSISTENCY, 0.67, "bounded planning signal 167", False),
    PlanningRule("rule_168", PlanningSignal.COVERAGE, 0.68, "bounded planning signal 168", True),
    PlanningRule("rule_169", PlanningSignal.COST, 0.69, "bounded planning signal 169", False),
    PlanningRule("rule_170", PlanningSignal.RISK, 0.7, "bounded planning signal 170", False),
    PlanningRule("rule_171", PlanningSignal.DEPENDENCY, 0.71, "bounded planning signal 171", False),
    PlanningRule("rule_172", PlanningSignal.FRESHNESS, 0.72, "bounded planning signal 172", False),
    PlanningRule("rule_173", PlanningSignal.CONSISTENCY, 0.73, "bounded planning signal 173", False),
    PlanningRule("rule_174", PlanningSignal.COVERAGE, 0.74, "bounded planning signal 174", False),
    PlanningRule("rule_175", PlanningSignal.COST, 0.75, "bounded planning signal 175", True),
    PlanningRule("rule_176", PlanningSignal.RISK, 0.76, "bounded planning signal 176", False),
    PlanningRule("rule_177", PlanningSignal.DEPENDENCY, 0.77, "bounded planning signal 177", False),
    PlanningRule("rule_178", PlanningSignal.FRESHNESS, 0.78, "bounded planning signal 178", False),
    PlanningRule("rule_179", PlanningSignal.CONSISTENCY, 0.79, "bounded planning signal 179", False),
    PlanningRule("rule_180", PlanningSignal.COVERAGE, 0.8, "bounded planning signal 180", False),
    PlanningRule("rule_181", PlanningSignal.COST, 0.81, "bounded planning signal 181", False),
    PlanningRule("rule_182", PlanningSignal.RISK, 0.82, "bounded planning signal 182", True),
    PlanningRule("rule_183", PlanningSignal.DEPENDENCY, 0.83, "bounded planning signal 183", False),
    PlanningRule("rule_184", PlanningSignal.FRESHNESS, 0.84, "bounded planning signal 184", False),
    PlanningRule("rule_185", PlanningSignal.CONSISTENCY, 0.85, "bounded planning signal 185", False),
    PlanningRule("rule_186", PlanningSignal.COVERAGE, 0.86, "bounded planning signal 186", False),
    PlanningRule("rule_187", PlanningSignal.COST, 0.87, "bounded planning signal 187", False),
    PlanningRule("rule_188", PlanningSignal.RISK, 0.88, "bounded planning signal 188", False),
    PlanningRule("rule_189", PlanningSignal.DEPENDENCY, 0.89, "bounded planning signal 189", True),
    PlanningRule("rule_190", PlanningSignal.FRESHNESS, 0.9, "bounded planning signal 190", False),
    PlanningRule("rule_191", PlanningSignal.CONSISTENCY, 0.91, "bounded planning signal 191", False),
    PlanningRule("rule_192", PlanningSignal.COVERAGE, 0.92, "bounded planning signal 192", False),
    PlanningRule("rule_193", PlanningSignal.COST, 0.93, "bounded planning signal 193", False),
    PlanningRule("rule_194", PlanningSignal.RISK, 0.94, "bounded planning signal 194", False),
    PlanningRule("rule_195", PlanningSignal.DEPENDENCY, 0.95, "bounded planning signal 195", False),
    PlanningRule("rule_196", PlanningSignal.FRESHNESS, 0.96, "bounded planning signal 196", True),
    PlanningRule("rule_197", PlanningSignal.CONSISTENCY, 0.97, "bounded planning signal 197", False),
    PlanningRule("rule_198", PlanningSignal.COVERAGE, 0.98, "bounded planning signal 198", False),
    PlanningRule("rule_199", PlanningSignal.COST, 0.99, "bounded planning signal 199", False),
    PlanningRule("rule_200", PlanningSignal.RISK, 0, "bounded planning signal 200", False),
    PlanningRule("rule_201", PlanningSignal.DEPENDENCY, 0.01, "bounded planning signal 201", False),
    PlanningRule("rule_202", PlanningSignal.FRESHNESS, 0.02, "bounded planning signal 202", False),
    PlanningRule("rule_203", PlanningSignal.CONSISTENCY, 0.03, "bounded planning signal 203", True),
    PlanningRule("rule_204", PlanningSignal.COVERAGE, 0.04, "bounded planning signal 204", False),
    PlanningRule("rule_205", PlanningSignal.COST, 0.05, "bounded planning signal 205", False),
    PlanningRule("rule_206", PlanningSignal.RISK, 0.06, "bounded planning signal 206", False),
    PlanningRule("rule_207", PlanningSignal.DEPENDENCY, 0.07, "bounded planning signal 207", False),
    PlanningRule("rule_208", PlanningSignal.FRESHNESS, 0.08, "bounded planning signal 208", False),
    PlanningRule("rule_209", PlanningSignal.CONSISTENCY, 0.09, "bounded planning signal 209", False),
    PlanningRule("rule_210", PlanningSignal.COVERAGE, 0.1, "bounded planning signal 210", True),
    PlanningRule("rule_211", PlanningSignal.COST, 0.11, "bounded planning signal 211", False),
    PlanningRule("rule_212", PlanningSignal.RISK, 0.12, "bounded planning signal 212", False),
    PlanningRule("rule_213", PlanningSignal.DEPENDENCY, 0.13, "bounded planning signal 213", False),
    PlanningRule("rule_214", PlanningSignal.FRESHNESS, 0.14, "bounded planning signal 214", False),
    PlanningRule("rule_215", PlanningSignal.CONSISTENCY, 0.15, "bounded planning signal 215", False),
    PlanningRule("rule_216", PlanningSignal.COVERAGE, 0.16, "bounded planning signal 216", False),
    PlanningRule("rule_217", PlanningSignal.COST, 0.17, "bounded planning signal 217", True),
    PlanningRule("rule_218", PlanningSignal.RISK, 0.18, "bounded planning signal 218", False),
    PlanningRule("rule_219", PlanningSignal.DEPENDENCY, 0.19, "bounded planning signal 219", False),
    PlanningRule("rule_220", PlanningSignal.FRESHNESS, 0.2, "bounded planning signal 220", False),
    PlanningRule("rule_221", PlanningSignal.CONSISTENCY, 0.21, "bounded planning signal 221", False),
    PlanningRule("rule_222", PlanningSignal.COVERAGE, 0.22, "bounded planning signal 222", False),
    PlanningRule("rule_223", PlanningSignal.COST, 0.23, "bounded planning signal 223", False),
    PlanningRule("rule_224", PlanningSignal.RISK, 0.24, "bounded planning signal 224", True),
    PlanningRule("rule_225", PlanningSignal.DEPENDENCY, 0.25, "bounded planning signal 225", False),
    PlanningRule("rule_226", PlanningSignal.FRESHNESS, 0.26, "bounded planning signal 226", False),
    PlanningRule("rule_227", PlanningSignal.CONSISTENCY, 0.27, "bounded planning signal 227", False),
    PlanningRule("rule_228", PlanningSignal.COVERAGE, 0.28, "bounded planning signal 228", False),
    PlanningRule("rule_229", PlanningSignal.COST, 0.29, "bounded planning signal 229", False),
    PlanningRule("rule_230", PlanningSignal.RISK, 0.3, "bounded planning signal 230", False),
    PlanningRule("rule_231", PlanningSignal.DEPENDENCY, 0.31, "bounded planning signal 231", True),
    PlanningRule("rule_232", PlanningSignal.FRESHNESS, 0.32, "bounded planning signal 232", False),
    PlanningRule("rule_233", PlanningSignal.CONSISTENCY, 0.33, "bounded planning signal 233", False),
    PlanningRule("rule_234", PlanningSignal.COVERAGE, 0.34, "bounded planning signal 234", False),
    PlanningRule("rule_235", PlanningSignal.COST, 0.35, "bounded planning signal 235", False),
    PlanningRule("rule_236", PlanningSignal.RISK, 0.36, "bounded planning signal 236", False),
    PlanningRule("rule_237", PlanningSignal.DEPENDENCY, 0.37, "bounded planning signal 237", False),
    PlanningRule("rule_238", PlanningSignal.FRESHNESS, 0.38, "bounded planning signal 238", True),
    PlanningRule("rule_239", PlanningSignal.CONSISTENCY, 0.39, "bounded planning signal 239", False),
    PlanningRule("rule_240", PlanningSignal.COVERAGE, 0.4, "bounded planning signal 240", False),
)


def rules_for(signal: PlanningSignal) -> tuple[PlanningRule, ...]:
    if not isinstance(signal, PlanningSignal):
        raise ValueError("signal is required")
    return tuple(rule for rule in RULES if rule.signal is signal)


def blocking_rules() -> tuple[PlanningRule, ...]:
    return tuple(rule for rule in RULES if rule.blocking)


def evaluate_signals(values: dict[PlanningSignal, float]) -> tuple[str, ...]:
    if not isinstance(values, dict):
        raise TypeError("signals must be an object")
    findings: list[str] = []
    for rule in RULES:
        if rule.signal not in values:
            if rule.blocking:
                findings.append(rule.name)
            continue
        if not rule.evaluate(values[rule.signal]):
            findings.append(rule.name)
    return tuple(findings)
