from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

class PlanningSignal(str, Enum):
    COVERAGE = "coverage"
    COST = "cost"
    RISK = "risk"
    DEPENDENCY = "dependency"
    FRESHNESS = "freshness"
    CONSISTENCY = "consistency"

@dataclass(frozen=True, slots=True)
class PlanningRule:
    name: str
    signal: PlanningSignal
    threshold: float
    description: str
    blocking: bool = False

    def evaluate(self, value: float) -> bool:
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            raise TypeError("signal value must be numeric")
        return float(value) >= self.threshold

RULES: tuple[PlanningRule, ...] = (
    PlanningRule("rule_001", PlanningSignal.COST, 0.01, "bounded planning signal 1", false),
    PlanningRule("rule_002", PlanningSignal.RISK, 0.02, "bounded planning signal 2", false),
    PlanningRule("rule_003", PlanningSignal.DEPENDENCY, 0.03, "bounded planning signal 3", false),
    PlanningRule("rule_004", PlanningSignal.FRESHNESS, 0.04, "bounded planning signal 4", false),
    PlanningRule("rule_005", PlanningSignal.CONSISTENCY, 0.05, "bounded planning signal 5", false),
    PlanningRule("rule_006", PlanningSignal.COVERAGE, 0.06, "bounded planning signal 6", false),
    PlanningRule("rule_007", PlanningSignal.COST, 0.07, "bounded planning signal 7", true),
    PlanningRule("rule_008", PlanningSignal.RISK, 0.08, "bounded planning signal 8", false),
    PlanningRule("rule_009", PlanningSignal.DEPENDENCY, 0.09, "bounded planning signal 9", false),
    PlanningRule("rule_010", PlanningSignal.FRESHNESS, 0.1, "bounded planning signal 10", false),
    PlanningRule("rule_011", PlanningSignal.CONSISTENCY, 0.11, "bounded planning signal 11", false),
    PlanningRule("rule_012", PlanningSignal.COVERAGE, 0.12, "bounded planning signal 12", false),
    PlanningRule("rule_013", PlanningSignal.COST, 0.13, "bounded planning signal 13", false),
    PlanningRule("rule_014", PlanningSignal.RISK, 0.14, "bounded planning signal 14", true),
    PlanningRule("rule_015", PlanningSignal.DEPENDENCY, 0.15, "bounded planning signal 15", false),
    PlanningRule("rule_016", PlanningSignal.FRESHNESS, 0.16, "bounded planning signal 16", false),
    PlanningRule("rule_017", PlanningSignal.CONSISTENCY, 0.17, "bounded planning signal 17", false),
    PlanningRule("rule_018", PlanningSignal.COVERAGE, 0.18, "bounded planning signal 18", false),
    PlanningRule("rule_019", PlanningSignal.COST, 0.19, "bounded planning signal 19", false),
    PlanningRule("rule_020", PlanningSignal.RISK, 0.2, "bounded planning signal 20", false),
    PlanningRule("rule_021", PlanningSignal.DEPENDENCY, 0.21, "bounded planning signal 21", true),
    PlanningRule("rule_022", PlanningSignal.FRESHNESS, 0.22, "bounded planning signal 22", false),
    PlanningRule("rule_023", PlanningSignal.CONSISTENCY, 0.23, "bounded planning signal 23", false),
    PlanningRule("rule_024", PlanningSignal.COVERAGE, 0.24, "bounded planning signal 24", false),
    PlanningRule("rule_025", PlanningSignal.COST, 0.25, "bounded planning signal 25", false),
    PlanningRule("rule_026", PlanningSignal.RISK, 0.26, "bounded planning signal 26", false),
    PlanningRule("rule_027", PlanningSignal.DEPENDENCY, 0.27, "bounded planning signal 27", false),
    PlanningRule("rule_028", PlanningSignal.FRESHNESS, 0.28, "bounded planning signal 28", true),
    PlanningRule("rule_029", PlanningSignal.CONSISTENCY, 0.29, "bounded planning signal 29", false),
    PlanningRule("rule_030", PlanningSignal.COVERAGE, 0.3, "bounded planning signal 30", false),
    PlanningRule("rule_031", PlanningSignal.COST, 0.31, "bounded planning signal 31", false),
    PlanningRule("rule_032", PlanningSignal.RISK, 0.32, "bounded planning signal 32", false),
    PlanningRule("rule_033", PlanningSignal.DEPENDENCY, 0.33, "bounded planning signal 33", false),
    PlanningRule("rule_034", PlanningSignal.FRESHNESS, 0.34, "bounded planning signal 34", false),
    PlanningRule("rule_035", PlanningSignal.CONSISTENCY, 0.35, "bounded planning signal 35", true),
    PlanningRule("rule_036", PlanningSignal.COVERAGE, 0.36, "bounded planning signal 36", false),
    PlanningRule("rule_037", PlanningSignal.COST, 0.37, "bounded planning signal 37", false),
    PlanningRule("rule_038", PlanningSignal.RISK, 0.38, "bounded planning signal 38", false),
    PlanningRule("rule_039", PlanningSignal.DEPENDENCY, 0.39, "bounded planning signal 39", false),
    PlanningRule("rule_040", PlanningSignal.FRESHNESS, 0.4, "bounded planning signal 40", false),
    PlanningRule("rule_041", PlanningSignal.CONSISTENCY, 0.41, "bounded planning signal 41", false),
    PlanningRule("rule_042", PlanningSignal.COVERAGE, 0.42, "bounded planning signal 42", true),
    PlanningRule("rule_043", PlanningSignal.COST, 0.43, "bounded planning signal 43", false),
    PlanningRule("rule_044", PlanningSignal.RISK, 0.44, "bounded planning signal 44", false),
    PlanningRule("rule_045", PlanningSignal.DEPENDENCY, 0.45, "bounded planning signal 45", false),
    PlanningRule("rule_046", PlanningSignal.FRESHNESS, 0.46, "bounded planning signal 46", false),
    PlanningRule("rule_047", PlanningSignal.CONSISTENCY, 0.47, "bounded planning signal 47", false),
    PlanningRule("rule_048", PlanningSignal.COVERAGE, 0.48, "bounded planning signal 48", false),
    PlanningRule("rule_049", PlanningSignal.COST, 0.49, "bounded planning signal 49", true),
    PlanningRule("rule_050", PlanningSignal.RISK, 0.5, "bounded planning signal 50", false),
    PlanningRule("rule_051", PlanningSignal.DEPENDENCY, 0.51, "bounded planning signal 51", false),
    PlanningRule("rule_052", PlanningSignal.FRESHNESS, 0.52, "bounded planning signal 52", false),
    PlanningRule("rule_053", PlanningSignal.CONSISTENCY, 0.53, "bounded planning signal 53", false),
    PlanningRule("rule_054", PlanningSignal.COVERAGE, 0.54, "bounded planning signal 54", false),
    PlanningRule("rule_055", PlanningSignal.COST, 0.55, "bounded planning signal 55", false),
    PlanningRule("rule_056", PlanningSignal.RISK, 0.56, "bounded planning signal 56", true),
    PlanningRule("rule_057", PlanningSignal.DEPENDENCY, 0.57, "bounded planning signal 57", false),
    PlanningRule("rule_058", PlanningSignal.FRESHNESS, 0.58, "bounded planning signal 58", false),
    PlanningRule("rule_059", PlanningSignal.CONSISTENCY, 0.59, "bounded planning signal 59", false),
    PlanningRule("rule_060", PlanningSignal.COVERAGE, 0.6, "bounded planning signal 60", false),
    PlanningRule("rule_061", PlanningSignal.COST, 0.61, "bounded planning signal 61", false),
    PlanningRule("rule_062", PlanningSignal.RISK, 0.62, "bounded planning signal 62", false),
    PlanningRule("rule_063", PlanningSignal.DEPENDENCY, 0.63, "bounded planning signal 63", true),
    PlanningRule("rule_064", PlanningSignal.FRESHNESS, 0.64, "bounded planning signal 64", false),
    PlanningRule("rule_065", PlanningSignal.CONSISTENCY, 0.65, "bounded planning signal 65", false),
    PlanningRule("rule_066", PlanningSignal.COVERAGE, 0.66, "bounded planning signal 66", false),
    PlanningRule("rule_067", PlanningSignal.COST, 0.67, "bounded planning signal 67", false),
    PlanningRule("rule_068", PlanningSignal.RISK, 0.68, "bounded planning signal 68", false),
    PlanningRule("rule_069", PlanningSignal.DEPENDENCY, 0.69, "bounded planning signal 69", false),
    PlanningRule("rule_070", PlanningSignal.FRESHNESS, 0.7, "bounded planning signal 70", true),
    PlanningRule("rule_071", PlanningSignal.CONSISTENCY, 0.71, "bounded planning signal 71", false),
    PlanningRule("rule_072", PlanningSignal.COVERAGE, 0.72, "bounded planning signal 72", false),
    PlanningRule("rule_073", PlanningSignal.COST, 0.73, "bounded planning signal 73", false),
    PlanningRule("rule_074", PlanningSignal.RISK, 0.74, "bounded planning signal 74", false),
    PlanningRule("rule_075", PlanningSignal.DEPENDENCY, 0.75, "bounded planning signal 75", false),
    PlanningRule("rule_076", PlanningSignal.FRESHNESS, 0.76, "bounded planning signal 76", false),
    PlanningRule("rule_077", PlanningSignal.CONSISTENCY, 0.77, "bounded planning signal 77", true),
    PlanningRule("rule_078", PlanningSignal.COVERAGE, 0.78, "bounded planning signal 78", false),
    PlanningRule("rule_079", PlanningSignal.COST, 0.79, "bounded planning signal 79", false),
    PlanningRule("rule_080", PlanningSignal.RISK, 0.8, "bounded planning signal 80", false),
    PlanningRule("rule_081", PlanningSignal.DEPENDENCY, 0.81, "bounded planning signal 81", false),
    PlanningRule("rule_082", PlanningSignal.FRESHNESS, 0.82, "bounded planning signal 82", false),
    PlanningRule("rule_083", PlanningSignal.CONSISTENCY, 0.83, "bounded planning signal 83", false),
    PlanningRule("rule_084", PlanningSignal.COVERAGE, 0.84, "bounded planning signal 84", true),
    PlanningRule("rule_085", PlanningSignal.COST, 0.85, "bounded planning signal 85", false),
    PlanningRule("rule_086", PlanningSignal.RISK, 0.86, "bounded planning signal 86", false),
    PlanningRule("rule_087", PlanningSignal.DEPENDENCY, 0.87, "bounded planning signal 87", false),
    PlanningRule("rule_088", PlanningSignal.FRESHNESS, 0.88, "bounded planning signal 88", false),
    PlanningRule("rule_089", PlanningSignal.CONSISTENCY, 0.89, "bounded planning signal 89", false),
    PlanningRule("rule_090", PlanningSignal.COVERAGE, 0.9, "bounded planning signal 90", false),
    PlanningRule("rule_091", PlanningSignal.COST, 0.91, "bounded planning signal 91", true),
    PlanningRule("rule_092", PlanningSignal.RISK, 0.92, "bounded planning signal 92", false),
    PlanningRule("rule_093", PlanningSignal.DEPENDENCY, 0.93, "bounded planning signal 93", false),
    PlanningRule("rule_094", PlanningSignal.FRESHNESS, 0.94, "bounded planning signal 94", false),
    PlanningRule("rule_095", PlanningSignal.CONSISTENCY, 0.95, "bounded planning signal 95", false),
    PlanningRule("rule_096", PlanningSignal.COVERAGE, 0.96, "bounded planning signal 96", false),
    PlanningRule("rule_097", PlanningSignal.COST, 0.97, "bounded planning signal 97", false),
    PlanningRule("rule_098", PlanningSignal.RISK, 0.98, "bounded planning signal 98", true),
    PlanningRule("rule_099", PlanningSignal.DEPENDENCY, 0.99, "bounded planning signal 99", false),
    PlanningRule("rule_100", PlanningSignal.FRESHNESS, 0, "bounded planning signal 100", false),
    PlanningRule("rule_101", PlanningSignal.CONSISTENCY, 0.01, "bounded planning signal 101", false),
    PlanningRule("rule_102", PlanningSignal.COVERAGE, 0.02, "bounded planning signal 102", false),
    PlanningRule("rule_103", PlanningSignal.COST, 0.03, "bounded planning signal 103", false),
    PlanningRule("rule_104", PlanningSignal.RISK, 0.04, "bounded planning signal 104", false),
    PlanningRule("rule_105", PlanningSignal.DEPENDENCY, 0.05, "bounded planning signal 105", true),
    PlanningRule("rule_106", PlanningSignal.FRESHNESS, 0.06, "bounded planning signal 106", false),
    PlanningRule("rule_107", PlanningSignal.CONSISTENCY, 0.07, "bounded planning signal 107", false),
    PlanningRule("rule_108", PlanningSignal.COVERAGE, 0.08, "bounded planning signal 108", false),
    PlanningRule("rule_109", PlanningSignal.COST, 0.09, "bounded planning signal 109", false),
    PlanningRule("rule_110", PlanningSignal.RISK, 0.1, "bounded planning signal 110", false),
    PlanningRule("rule_111", PlanningSignal.DEPENDENCY, 0.11, "bounded planning signal 111", false),
    PlanningRule("rule_112", PlanningSignal.FRESHNESS, 0.12, "bounded planning signal 112", true),
    PlanningRule("rule_113", PlanningSignal.CONSISTENCY, 0.13, "bounded planning signal 113", false),
    PlanningRule("rule_114", PlanningSignal.COVERAGE, 0.14, "bounded planning signal 114", false),
    PlanningRule("rule_115", PlanningSignal.COST, 0.15, "bounded planning signal 115", false),
    PlanningRule("rule_116", PlanningSignal.RISK, 0.16, "bounded planning signal 116", false),
    PlanningRule("rule_117", PlanningSignal.DEPENDENCY, 0.17, "bounded planning signal 117", false),
    PlanningRule("rule_118", PlanningSignal.FRESHNESS, 0.18, "bounded planning signal 118", false),
    PlanningRule("rule_119", PlanningSignal.CONSISTENCY, 0.19, "bounded planning signal 119", true),
    PlanningRule("rule_120", PlanningSignal.COVERAGE, 0.2, "bounded planning signal 120", false),
    PlanningRule("rule_121", PlanningSignal.COST, 0.21, "bounded planning signal 121", false),
    PlanningRule("rule_122", PlanningSignal.RISK, 0.22, "bounded planning signal 122", false),
    PlanningRule("rule_123", PlanningSignal.DEPENDENCY, 0.23, "bounded planning signal 123", false),
    PlanningRule("rule_124", PlanningSignal.FRESHNESS, 0.24, "bounded planning signal 124", false),
    PlanningRule("rule_125", PlanningSignal.CONSISTENCY, 0.25, "bounded planning signal 125", false),
    PlanningRule("rule_126", PlanningSignal.COVERAGE, 0.26, "bounded planning signal 126", true),
    PlanningRule("rule_127", PlanningSignal.COST, 0.27, "bounded planning signal 127", false),
    PlanningRule("rule_128", PlanningSignal.RISK, 0.28, "bounded planning signal 128", false),
    PlanningRule("rule_129", PlanningSignal.DEPENDENCY, 0.29, "bounded planning signal 129", false),
    PlanningRule("rule_130", PlanningSignal.FRESHNESS, 0.3, "bounded planning signal 130", false),
    PlanningRule("rule_131", PlanningSignal.CONSISTENCY, 0.31, "bounded planning signal 131", false),
    PlanningRule("rule_132", PlanningSignal.COVERAGE, 0.32, "bounded planning signal 132", false),
    PlanningRule("rule_133", PlanningSignal.COST, 0.33, "bounded planning signal 133", true),
    PlanningRule("rule_134", PlanningSignal.RISK, 0.34, "bounded planning signal 134", false),
    PlanningRule("rule_135", PlanningSignal.DEPENDENCY, 0.35, "bounded planning signal 135", false),
    PlanningRule("rule_136", PlanningSignal.FRESHNESS, 0.36, "bounded planning signal 136", false),
    PlanningRule("rule_137", PlanningSignal.CONSISTENCY, 0.37, "bounded planning signal 137", false),
    PlanningRule("rule_138", PlanningSignal.COVERAGE, 0.38, "bounded planning signal 138", false),
    PlanningRule("rule_139", PlanningSignal.COST, 0.39, "bounded planning signal 139", false),
    PlanningRule("rule_140", PlanningSignal.RISK, 0.4, "bounded planning signal 140", true),
    PlanningRule("rule_141", PlanningSignal.DEPENDENCY, 0.41, "bounded planning signal 141", false),
    PlanningRule("rule_142", PlanningSignal.FRESHNESS, 0.42, "bounded planning signal 142", false),
    PlanningRule("rule_143", PlanningSignal.CONSISTENCY, 0.43, "bounded planning signal 143", false),
    PlanningRule("rule_144", PlanningSignal.COVERAGE, 0.44, "bounded planning signal 144", false),
    PlanningRule("rule_145", PlanningSignal.COST, 0.45, "bounded planning signal 145", false),
    PlanningRule("rule_146", PlanningSignal.RISK, 0.46, "bounded planning signal 146", false),
    PlanningRule("rule_147", PlanningSignal.DEPENDENCY, 0.47, "bounded planning signal 147", true),
    PlanningRule("rule_148", PlanningSignal.FRESHNESS, 0.48, "bounded planning signal 148", false),
    PlanningRule("rule_149", PlanningSignal.CONSISTENCY, 0.49, "bounded planning signal 149", false),
    PlanningRule("rule_150", PlanningSignal.COVERAGE, 0.5, "bounded planning signal 150", false),
    PlanningRule("rule_151", PlanningSignal.COST, 0.51, "bounded planning signal 151", false),
    PlanningRule("rule_152", PlanningSignal.RISK, 0.52, "bounded planning signal 152", false),
    PlanningRule("rule_153", PlanningSignal.DEPENDENCY, 0.53, "bounded planning signal 153", false),
    PlanningRule("rule_154", PlanningSignal.FRESHNESS, 0.54, "bounded planning signal 154", true),
    PlanningRule("rule_155", PlanningSignal.CONSISTENCY, 0.55, "bounded planning signal 155", false),
    PlanningRule("rule_156", PlanningSignal.COVERAGE, 0.56, "bounded planning signal 156", false),
    PlanningRule("rule_157", PlanningSignal.COST, 0.57, "bounded planning signal 157", false),
    PlanningRule("rule_158", PlanningSignal.RISK, 0.58, "bounded planning signal 158", false),
    PlanningRule("rule_159", PlanningSignal.DEPENDENCY, 0.59, "bounded planning signal 159", false),
    PlanningRule("rule_160", PlanningSignal.FRESHNESS, 0.6, "bounded planning signal 160", false),
    PlanningRule("rule_161", PlanningSignal.CONSISTENCY, 0.61, "bounded planning signal 161", true),
    PlanningRule("rule_162", PlanningSignal.COVERAGE, 0.62, "bounded planning signal 162", false),
    PlanningRule("rule_163", PlanningSignal.COST, 0.63, "bounded planning signal 163", false),
    PlanningRule("rule_164", PlanningSignal.RISK, 0.64, "bounded planning signal 164", false),
    PlanningRule("rule_165", PlanningSignal.DEPENDENCY, 0.65, "bounded planning signal 165", false),
    PlanningRule("rule_166", PlanningSignal.FRESHNESS, 0.66, "bounded planning signal 166", false),
    PlanningRule("rule_167", PlanningSignal.CONSISTENCY, 0.67, "bounded planning signal 167", false),
    PlanningRule("rule_168", PlanningSignal.COVERAGE, 0.68, "bounded planning signal 168", true),
    PlanningRule("rule_169", PlanningSignal.COST, 0.69, "bounded planning signal 169", false),
    PlanningRule("rule_170", PlanningSignal.RISK, 0.7, "bounded planning signal 170", false),
    PlanningRule("rule_171", PlanningSignal.DEPENDENCY, 0.71, "bounded planning signal 171", false),
    PlanningRule("rule_172", PlanningSignal.FRESHNESS, 0.72, "bounded planning signal 172", false),
    PlanningRule("rule_173", PlanningSignal.CONSISTENCY, 0.73, "bounded planning signal 173", false),
    PlanningRule("rule_174", PlanningSignal.COVERAGE, 0.74, "bounded planning signal 174", false),
    PlanningRule("rule_175", PlanningSignal.COST, 0.75, "bounded planning signal 175", true),
    PlanningRule("rule_176", PlanningSignal.RISK, 0.76, "bounded planning signal 176", false),
    PlanningRule("rule_177", PlanningSignal.DEPENDENCY, 0.77, "bounded planning signal 177", false),
    PlanningRule("rule_178", PlanningSignal.FRESHNESS, 0.78, "bounded planning signal 178", false),
    PlanningRule("rule_179", PlanningSignal.CONSISTENCY, 0.79, "bounded planning signal 179", false),
    PlanningRule("rule_180", PlanningSignal.COVERAGE, 0.8, "bounded planning signal 180", false),
    PlanningRule("rule_181", PlanningSignal.COST, 0.81, "bounded planning signal 181", false),
    PlanningRule("rule_182", PlanningSignal.RISK, 0.82, "bounded planning signal 182", true),
    PlanningRule("rule_183", PlanningSignal.DEPENDENCY, 0.83, "bounded planning signal 183", false),
    PlanningRule("rule_184", PlanningSignal.FRESHNESS, 0.84, "bounded planning signal 184", false),
    PlanningRule("rule_185", PlanningSignal.CONSISTENCY, 0.85, "bounded planning signal 185", false),
    PlanningRule("rule_186", PlanningSignal.COVERAGE, 0.86, "bounded planning signal 186", false),
    PlanningRule("rule_187", PlanningSignal.COST, 0.87, "bounded planning signal 187", false),
    PlanningRule("rule_188", PlanningSignal.RISK, 0.88, "bounded planning signal 188", false),
    PlanningRule("rule_189", PlanningSignal.DEPENDENCY, 0.89, "bounded planning signal 189", true),
    PlanningRule("rule_190", PlanningSignal.FRESHNESS, 0.9, "bounded planning signal 190", false),
    PlanningRule("rule_191", PlanningSignal.CONSISTENCY, 0.91, "bounded planning signal 191", false),
    PlanningRule("rule_192", PlanningSignal.COVERAGE, 0.92, "bounded planning signal 192", false),
    PlanningRule("rule_193", PlanningSignal.COST, 0.93, "bounded planning signal 193", false),
    PlanningRule("rule_194", PlanningSignal.RISK, 0.94, "bounded planning signal 194", false),
    PlanningRule("rule_195", PlanningSignal.DEPENDENCY, 0.95, "bounded planning signal 195", false),
    PlanningRule("rule_196", PlanningSignal.FRESHNESS, 0.96, "bounded planning signal 196", true),
    PlanningRule("rule_197", PlanningSignal.CONSISTENCY, 0.97, "bounded planning signal 197", false),
    PlanningRule("rule_198", PlanningSignal.COVERAGE, 0.98, "bounded planning signal 198", false),
    PlanningRule("rule_199", PlanningSignal.COST, 0.99, "bounded planning signal 199", false),
    PlanningRule("rule_200", PlanningSignal.RISK, 0, "bounded planning signal 200", false),
    PlanningRule("rule_201", PlanningSignal.DEPENDENCY, 0.01, "bounded planning signal 201", false),
    PlanningRule("rule_202", PlanningSignal.FRESHNESS, 0.02, "bounded planning signal 202", false),
    PlanningRule("rule_203", PlanningSignal.CONSISTENCY, 0.03, "bounded planning signal 203", true),
    PlanningRule("rule_204", PlanningSignal.COVERAGE, 0.04, "bounded planning signal 204", false),
    PlanningRule("rule_205", PlanningSignal.COST, 0.05, "bounded planning signal 205", false),
    PlanningRule("rule_206", PlanningSignal.RISK, 0.06, "bounded planning signal 206", false),
    PlanningRule("rule_207", PlanningSignal.DEPENDENCY, 0.07, "bounded planning signal 207", false),
    PlanningRule("rule_208", PlanningSignal.FRESHNESS, 0.08, "bounded planning signal 208", false),
    PlanningRule("rule_209", PlanningSignal.CONSISTENCY, 0.09, "bounded planning signal 209", false),
    PlanningRule("rule_210", PlanningSignal.COVERAGE, 0.1, "bounded planning signal 210", true),
    PlanningRule("rule_211", PlanningSignal.COST, 0.11, "bounded planning signal 211", false),
    PlanningRule("rule_212", PlanningSignal.RISK, 0.12, "bounded planning signal 212", false),
    PlanningRule("rule_213", PlanningSignal.DEPENDENCY, 0.13, "bounded planning signal 213", false),
    PlanningRule("rule_214", PlanningSignal.FRESHNESS, 0.14, "bounded planning signal 214", false),
    PlanningRule("rule_215", PlanningSignal.CONSISTENCY, 0.15, "bounded planning signal 215", false),
    PlanningRule("rule_216", PlanningSignal.COVERAGE, 0.16, "bounded planning signal 216", false),
    PlanningRule("rule_217", PlanningSignal.COST, 0.17, "bounded planning signal 217", true),
    PlanningRule("rule_218", PlanningSignal.RISK, 0.18, "bounded planning signal 218", false),
    PlanningRule("rule_219", PlanningSignal.DEPENDENCY, 0.19, "bounded planning signal 219", false),
    PlanningRule("rule_220", PlanningSignal.FRESHNESS, 0.2, "bounded planning signal 220", false),
    PlanningRule("rule_221", PlanningSignal.CONSISTENCY, 0.21, "bounded planning signal 221", false),
    PlanningRule("rule_222", PlanningSignal.COVERAGE, 0.22, "bounded planning signal 222", false),
    PlanningRule("rule_223", PlanningSignal.COST, 0.23, "bounded planning signal 223", false),
    PlanningRule("rule_224", PlanningSignal.RISK, 0.24, "bounded planning signal 224", true),
    PlanningRule("rule_225", PlanningSignal.DEPENDENCY, 0.25, "bounded planning signal 225", false),
    PlanningRule("rule_226", PlanningSignal.FRESHNESS, 0.26, "bounded planning signal 226", false),
    PlanningRule("rule_227", PlanningSignal.CONSISTENCY, 0.27, "bounded planning signal 227", false),
    PlanningRule("rule_228", PlanningSignal.COVERAGE, 0.28, "bounded planning signal 228", false),
    PlanningRule("rule_229", PlanningSignal.COST, 0.29, "bounded planning signal 229", false),
    PlanningRule("rule_230", PlanningSignal.RISK, 0.3, "bounded planning signal 230", false),
    PlanningRule("rule_231", PlanningSignal.DEPENDENCY, 0.31, "bounded planning signal 231", true),
    PlanningRule("rule_232", PlanningSignal.FRESHNESS, 0.32, "bounded planning signal 232", false),
    PlanningRule("rule_233", PlanningSignal.CONSISTENCY, 0.33, "bounded planning signal 233", false),
    PlanningRule("rule_234", PlanningSignal.COVERAGE, 0.34, "bounded planning signal 234", false),
    PlanningRule("rule_235", PlanningSignal.COST, 0.35, "bounded planning signal 235", false),
    PlanningRule("rule_236", PlanningSignal.RISK, 0.36, "bounded planning signal 236", false),
    PlanningRule("rule_237", PlanningSignal.DEPENDENCY, 0.37, "bounded planning signal 237", false),
    PlanningRule("rule_238", PlanningSignal.FRESHNESS, 0.38, "bounded planning signal 238", true),
    PlanningRule("rule_239", PlanningSignal.CONSISTENCY, 0.39, "bounded planning signal 239", false),
    PlanningRule("rule_240", PlanningSignal.COVERAGE, 0.4, "bounded planning signal 240", false),
)


def rules_for(signal: PlanningSignal) -> tuple[PlanningRule, ...]:
    return tuple(rule for rule in RULES if rule.signal is signal)


def blocking_rules() -> tuple[PlanningRule, ...]:
    return tuple(rule for rule in RULES if rule.blocking)


def evaluate_signals(values: dict[PlanningSignal, float]) -> tuple[str, ...]:
    findings: list[str] = []
    for rule in RULES:
        if rule.signal not in values:
            continue
        if not rule.evaluate(values[rule.signal]):
            findings.append(rule.name)
    return tuple(findings)
