"""Deterministic engine-neutral 3D physics foundation."""

from .body import BodyType, RigidBody
from .ccd import CCDHit, ContinuousCollisionDetector
from .calculations import (
    PhysicsAggregate,
    aggregate_physics,
    angular_momentum,
    gravitational_potential_energy,
    impulse_from_force,
    kinetic_energy,
    linear_momentum,
    world_inertia,
)
from .collision import (
    BroadPhasePair,
    ContactManifold,
    ContactPoint,
    SweepAndPruneBroadPhase,
    detect_collision,
    generate_manifolds,
)
from .constraints import ConstraintSolver, ConstraintStats, DistanceJoint
from .contacts import ContactCache, ContactCacheEntry
from .errors import (
    BodyNotFoundError,
    DegenerateGeometryError,
    DuplicateBodyError,
    DuplicateJointError,
    JointNotFoundError,
    PhysicsError,
    PhysicsReplayDivergenceError,
    PhysicsReplayError,
    PhysicsSnapshotError,
    PhysicsValidationError,
    SolverError,
    UnsupportedCollisionError,
)
from .gameplay import (
    GamePhysicsProfile,
    GameplayScale,
    JumpTuning,
    ProjectileSolution,
)
from .materials import CombineRule, ContactMaterial, PhysicsMaterial, combine_materials
from .math3d import AABB, Mat3, Quat, Transform, Vec3
from .queries import Ray, RayHit, raycast_body, sphere_cast_body
from .shapes import BoxShape, CollisionShape, MassProperties, PlaneShape, ShapeKind, SphereShape
from .snapshots import (
    PhysicsBodyState,
    PhysicsSnapshot,
    build_snapshot,
    verify_snapshot,
)
from .solver import SequentialImpulseSolver, SolverStats
from .world import PhysicsSettings, PhysicsStepReceipt, PhysicsWorld
from .commands import (
    PhysicsCommand,
    PhysicsCommandFrame,
    PhysicsCommandKind,
    PhysicsCommandTape,
    apply_physics_commands,
    step_physics_with_commands,
)
from .rollback import PhysicsRollbackSession, RollbackReceipt
from .replay import (
    PhysicsCommandReplayFrame,
    PhysicsCommandReplayRecorder,
    PhysicsCommandReplayTape,
    PhysicsReplayFrame,
    PhysicsReplayRecorder,
    PhysicsReplayTape,
    PhysicsReplayVerification,
    replay_physics,
    replay_physics_commands,
)

__all__ = [
    "AABB",
    "BodyNotFoundError",
    "CCDHit",
    "ConstraintSolver",
    "ConstraintStats",
    "ContactCache",
    "ContactCacheEntry",
    "ContinuousCollisionDetector",
    "DistanceJoint",
    "DuplicateJointError",
    "JointNotFoundError",
    "BodyType",
    "BoxShape",
    "BroadPhasePair",
    "CollisionShape",
    "CombineRule",
    "ContactManifold",
    "ContactMaterial",
    "ContactPoint",
    "DegenerateGeometryError",
    "DuplicateBodyError",
    "GamePhysicsProfile",
    "GameplayScale",
    "JumpTuning",
    "MassProperties",
    "Mat3",
    "PhysicsAggregate",
    "PhysicsBodyState",
    "PhysicsCommand",
    "PhysicsCommandFrame",
    "PhysicsCommandKind",
    "PhysicsCommandReplayFrame",
    "PhysicsCommandReplayRecorder",
    "PhysicsCommandReplayTape",
    "PhysicsCommandTape",
    "PhysicsReplayDivergenceError",
    "PhysicsReplayError",
    "PhysicsReplayFrame",
    "PhysicsReplayRecorder",
    "PhysicsReplayTape",
    "PhysicsReplayVerification",
    "PhysicsRollbackSession",
    "PhysicsSnapshot",
    "PhysicsSnapshotError",
    "PhysicsError",
    "PhysicsMaterial",
    "PhysicsSettings",
    "PhysicsStepReceipt",
    "PhysicsValidationError",
    "PhysicsWorld",
    "PlaneShape",
    "ProjectileSolution",
    "Quat",
    "Ray",
    "RayHit",
    "RigidBody",
    "RollbackReceipt",
    "SequentialImpulseSolver",
    "ShapeKind",
    "SolverError",
    "SolverStats",
    "SphereShape",
    "SweepAndPruneBroadPhase",
    "Transform",
    "UnsupportedCollisionError",
    "Vec3",
    "aggregate_physics",
    "apply_physics_commands",
    "angular_momentum",
    "build_snapshot",
    "combine_materials",
    "detect_collision",
    "generate_manifolds",
    "gravitational_potential_energy",
    "impulse_from_force",
    "kinetic_energy",
    "linear_momentum",
    "raycast_body",
    "replay_physics",
    "replay_physics_commands",
    "sphere_cast_body",
    "step_physics_with_commands",
    "verify_snapshot",
    "world_inertia",
]
