"""Skeleton Intelligence Package.

Exports orchestration, learning, pedagogy, world governance, narrative,
quest planning and live collaboration primitives for the Jeeves school AI.
"""

from skeleton.intelligence.orchestrator import (
    AdaptiveLearner,
    HandlerPolicy,
    HandlerTelemetry,
    IntelligenceOrchestrator,
    MetaGrid,
    ReasoningResult,
    ReasoningTask,
    default_meta_grid,
)
from skeleton.intelligence.improve_loop import ImproveLoop, ImproveResult, Iteration
from skeleton.intelligence.prompt_improve import (
    PrefixVariant,
    PromptImproveDriver,
    PromptImproveResult,
    answer_quality_score,
    improve_prefix_prompt,
    mutate_prefix,
)
from skeleton.intelligence.jeeves_policy import (
    InteractionMode,
    LearningPolicy,
    LearningStage,
    choose_difficulty,
    interaction_mode,
    stage_for_hours,
)
from skeleton.intelligence.game_context import (
    FactionContext,
    GAMEFORGE_DOCTRINE,
    NoveltyDecision,
    novelty_gate,
    reputation_level,
)
from skeleton.intelligence.jeeves_pedagogy import *
from skeleton.intelligence.collaboration import (
    CollaborationContext,
    CollaborationRole,
    collaboration_prompt,
    suggestion_window,
)
from skeleton.intelligence.narrative import (
    DialogueChoice,
    DialogueGraph,
    DialogueNode,
    DialogueState,
    NpcRelationship,
)
from skeleton.intelligence.admission import (
    AdmissionDecision,
    AdmissionError,
    AdmissionRequest,
    AdmissionStatus,
    ResourceBudget,
    RuntimePressure,
    UsageEstimate,
    evaluate_admission,
    require_admission,
)
from skeleton.intelligence.admission_runtime import (
    AdmissionCompletion,
    AdmissionLease,
    AdmissionRuntime,
    AdmissionRuntimeConflict,
    AdmissionRuntimeError,
)
from skeleton.intelligence.routing_context_receipt import (
    ROUTING_CONTEXT_ACCOUNTABILITY_ID,
    ROUTING_CONTEXT_RECEIPT_SCHEMA_VERSION,
    ROUTING_CONTEXT_TASK_ID,
    RoutingContextReceipt,
    RoutingContextReceiptError,
    bind_route_request_to_context,
    build_routing_context_receipt,
)
from skeleton.intelligence.information_quality import (
    INFORMATION_QUALITY_ACCOUNTABILITY_ID,
    INFORMATION_QUALITY_SCHEMA_VERSION,
    INFORMATION_QUALITY_TASK_ID,
    InformationQualityError,
    InformationQualityPolicy,
    InformationQualityReceipt,
    KnowledgeObservation,
    build_information_quality_receipt,
    observe_knowledge_document,
)
from skeleton.intelligence.strategy_registry import (
    REASONING_STRATEGY_ACCOUNTABILITY_ID,
    REASONING_STRATEGY_SCHEMA_VERSION,
    REASONING_STRATEGY_TASK_ID,
    ReasoningBudget,
    ReasoningRequestProfile,
    ReasoningStrategy,
    ReasoningStrategyError,
    ReasoningStrategyRegistry,
    StopPolicy,
    StrategySelection,
    load_reasoning_strategy_registry,
    registry_from_payload,
    select_reasoning_strategy,
)
from skeleton.intelligence.cognitive_runtime import (
    CognitiveRuntimeError,
    ReasoningPolicyReceipt,
    ReasoningProgress,
    StopAction,
    StopDecision,
    build_reasoning_policy_receipt,
    evaluate_reasoning_progress,
)
from skeleton.intelligence.quota import (
    QuotaCompletion,
    QuotaConflict,
    QuotaError,
    QuotaExceeded,
    QuotaReservation,
    QuotaUsage,
    TenantQuota,
    TenantQuotaLedger,
)
from skeleton.intelligence.quota_sqlite import SqliteTenantQuotaLedger
from skeleton.intelligence.shared_pressure import (
    SharedPressureConflict,
    SharedPressureDecision,
    SharedPressureError,
    SharedPressureExceeded,
    SharedPressureLease,
    SharedPressurePolicy,
    SharedPressureSnapshot,
    SharedQueueTicket,
    SqliteSharedPressureLedger,
)
from skeleton.intelligence.quests import (
    QuestObjective,
    QuestProgress,
    QuestTemplate,
    rank_quest_candidates,
)

__all__ = [
    "IntelligenceOrchestrator",
    "HandlerPolicy",
    "HandlerTelemetry",
    "AdaptiveLearner",
    "MetaGrid",
    "default_meta_grid",
    "ReasoningTask",
    "ReasoningResult",
    "ImproveLoop",
    "ImproveResult",
    "Iteration",
    "PrefixVariant",
    "PromptImproveDriver",
    "PromptImproveResult",
    "answer_quality_score",
    "improve_prefix_prompt",
    "mutate_prefix",
    "InteractionMode",
    "LearningPolicy",
    "LearningStage",
    "choose_difficulty",
    "interaction_mode",
    "stage_for_hours",
    "FactionContext",
    "NoveltyDecision",
    "reputation_level",
    "novelty_gate",
    "GAMEFORGE_DOCTRINE",
    "CollaborationContext",
    "CollaborationRole",
    "collaboration_prompt",
    "suggestion_window",
    "DialogueChoice",
    "DialogueGraph",
    "DialogueNode",
    "DialogueState",
    "NpcRelationship",
    "QuestObjective",
    "QuestProgress",
    "QuestTemplate",
    "rank_quest_candidates",
    "AdmissionDecision",
    "AdmissionError",
    "AdmissionRequest",
    "AdmissionStatus",
    "ResourceBudget",
    "RuntimePressure",
    "UsageEstimate",
    "evaluate_admission",
    "require_admission",
    "AdmissionCompletion",
    "AdmissionLease",
    "AdmissionRuntime",
    "AdmissionRuntimeConflict",
    "AdmissionRuntimeError",
    "ROUTING_CONTEXT_ACCOUNTABILITY_ID",
    "ROUTING_CONTEXT_RECEIPT_SCHEMA_VERSION",
    "ROUTING_CONTEXT_TASK_ID",
    "RoutingContextReceipt",
    "RoutingContextReceiptError",
    "bind_route_request_to_context",
    "build_routing_context_receipt",
    "INFORMATION_QUALITY_ACCOUNTABILITY_ID",
    "INFORMATION_QUALITY_SCHEMA_VERSION",
    "INFORMATION_QUALITY_TASK_ID",
    "InformationQualityError",
    "InformationQualityPolicy",
    "InformationQualityReceipt",
    "KnowledgeObservation",
    "build_information_quality_receipt",
    "observe_knowledge_document",
    "REASONING_STRATEGY_ACCOUNTABILITY_ID",
    "REASONING_STRATEGY_SCHEMA_VERSION",
    "REASONING_STRATEGY_TASK_ID",
    "ReasoningBudget",
    "ReasoningRequestProfile",
    "ReasoningStrategy",
    "ReasoningStrategyError",
    "ReasoningStrategyRegistry",
    "StopPolicy",
    "StrategySelection",
    "load_reasoning_strategy_registry",
    "registry_from_payload",
    "select_reasoning_strategy",
    "CognitiveRuntimeError",
    "ReasoningPolicyReceipt",
    "ReasoningProgress",
    "StopAction",
    "StopDecision",
    "build_reasoning_policy_receipt",
    "evaluate_reasoning_progress",
    "QuotaCompletion",
    "QuotaConflict",
    "QuotaError",
    "QuotaExceeded",
    "QuotaReservation",
    "QuotaUsage",
    "TenantQuota",
    "TenantQuotaLedger",
    "SqliteTenantQuotaLedger",
    "SharedPressureConflict",
    "SharedPressureDecision",
    "SharedPressureError",
    "SharedPressureExceeded",
    "SharedPressureLease",
    "SharedPressurePolicy",
    "SharedPressureSnapshot",
    "SharedQueueTicket",
    "SqliteSharedPressureLedger",
]
