"""Machine manifest of the landed P2 spine seams.

Lists names and laws. It does not dispatch and it does not sign work off.
"""

from __future__ import annotations

from typing import Any


SEAMS = (
    ("inbox", "exactly-once"),
    ("fence", "tenant-epoch-cas"),
    ("projection", "published-outbox-to-fence"),
    ("mongo-inbox", "exactly-once"),
    ("mongo-fence", "tenant-epoch-cas"),
    ("hook", "dispatch-project-cursor"),
    ("worker", "composed-drain"),
    ("batch", "bounded-batch-project"),
    ("witness", "lag-catalog-status"),
    ("drift", "fence-epoch-parity"),
    ("sweep", "bounded-drift-sweep"),
    ("replay", "replay-does-not-advance"),
    ("hold", "hold-does-not-apply"),
    ("export", "quarantine-json"),
    ("digest", "sha256-gap-drift"),
    ("ledger", "append-digest"),
    ("reaccept", "digest-stable-reaccept"),
    ("gate", "held-id-refused"),
    ("watch", "epoch-unchanged"),
    ("poison-ticket", "ticket-requires-hold"),
    ("poison-apply", "hold-digest-stable-epoch-unchanged"),
    ("poison-witness", "tenant-isolated-journal"),
    ("poison-chain", "journal-hash-chain"),
    ("dispatch-guard", "dispatcher-identity-unchanged"),
    ("index-bind", "create-index-only-when-present"),
    ("bind-audit", "bind-does-not-start-dispatcher"),
    ("cut-gate", "switch-refused"),
    ("surface", "surface-not-claimed"),
    ("provider-probe", "provider-surface-unclaimed"),
    ("pr-probe", "pr-automation-unclaimed"),
    ("unread-gap", "tenant-sequence-gap"),
    ("surface-seal", "green-claim-stripped"),
    ("ci-witness", "ci-green-unread"),
    ("merge-gate", "merge-refused"),
    ("probe-replay", "replay-does-not-insert"),
    ("motor-witness", "motor-not-imported"),
    ("dispatch-witness", "dispatcher-not-started"),
    ("dark", "unwired-surfaces-stay-dark"),
    ("epoch-witness", "side-card-epoch-unchanged"),
    ("quiet", "dark-card-not-rewritten"),
    ("quiet-witness", "quiet-row-stays-dark"),
    ("bind-card", "bind-card-stays-dark"),
    ("bind-journal", "bind-card-not-rewritten"),
    ("bind-read", "bind-row-stays-dark"),
    ("bind-chain", "bind-journal-hash-chain"),
    ("bind-tenant", "bind-tenant-isolated"),
    ("bind-replay", "bind-replay-does-not-insert"),
    ("bind-surface", "bind-surface-stays-unread"),
    ("bind-gap", "bind-gap-not-filled"),
    ("bind-snapshot", "bind-snapshot-stays-unactivated"),
    ("bind-recovery", "recovery-plan-does-not-activate"),
    ("bind-checkpoint", "checkpoint-is-immutable-and-unactivated"),
    ("bind-checkpoint-replay", "checkpoint-replay-does-not-insert"),
    ("bind-checkpoint-tenant", "checkpoint-tenant-isolated"),
    ("bind-checkpoint-chain", "checkpoint-hash-chain"),
    ("bind-bundle", "checkpoint-bundle-is-not-activation"),
    ("bind-bundle-verify", "bundle-verification-does-not-activate"),
    ("bind-restore-receipt", "restore-receipt-is-not-activation"),
    ("bind-restore-verify", "restore-verification-does-not-activate"),
    ("bind-restore-journal", "restore-journal-is-append-only"),
    ("bind-restore-replay", "restore-replay-does-not-insert"),
    ("bind-restore-tenant", "restore-journal-tenant-isolated"),
    ("bind-restore-chain", "restore-journal-hash-chain"),
    ("bind-restore-continuity", "restore-continuity-does-not-activate"),
    ("bind-restore-export", "portable-evidence-is-not-activation"),
    ("bind-restore-export-verify", "portable-evidence-verification-does-not-activate"),
    ("motor-plan", "driver-injected-bootstrap-plan"),
    ("motor-bootstrap", "driver-injected-index-bootstrap"),
    ("motor-bootstrap-verify", "bootstrap-verification-does-not-activate"),
    ("motor-bootstrap-replay", "bootstrap-replay-is-equivalent"),
    ("motor-preflight", "deployment-protocol-qualified-without-activation"),
    ("motor-preflight-verify", "preflight-verification-does-not-activate"),
    ("pymongo-async-adapter", "supported-driver-import-is-deployment-only"),
    ("pymongo-async-live-qualification", "live-driver-qualification-is-not-runtime-activation"),
    ("runtime-selection-candidate", "qualified-driver-does-not-self-select"),
    ("runtime-selection-verify", "selection-verification-does-not-authorize"),
    ("cutover-rehearsal", "green-preconditions-do-not-authorize-cutover"),
    ("cutover-rehearsal-verify", "rehearsal-verification-does-not-authorize-cutover"),
    ("pymongo-async-cutover-rehearsal", "live-qualification-does-not-authorize-runtime-cutover"),
    ("cutover-authorization", "authenticated-dual-control-is-not-runtime-activation"),
    ("cutover-authorization-verify", "authorization-verification-does-not-make-authorization-effective"),
    ("cutover-effectiveness", "external-change-control-makes-authorization-effective-not-runtime-active"),
    ("cutover-effectiveness-verify", "effectiveness-verification-does-not-select-runtime"),
    ("selection-permit", "effective-authorization-issues-one-non-activating-selection-permit"),
    ("selection-permit-verify", "permit-verification-does-not-select-runtime"),
    ("selection-consume", "selection-permit-consumed-once-before-driver-selection"),
    ("selection-consume-verify", "consumption-verification-does-not-select-runtime"),
    ("driver-selection", "consumed-permit-selects-driver-state-not-runtime-activation"),
    ("driver-selection-verify", "selection-verification-does-not-activate-runtime"),
    ("runtime-activation-gate", "activation-eligibility-does-not-activate-runtime"),
    ("runtime-activation-gate-verify", "activation-gate-verification-does-not-activate-runtime"),
    ("activation-permit", "activation-eligibility-requires-external-short-lived-permit"),
    ("activation-permit-verify", "activation-permit-verification-does-not-activate-runtime"),
    ("activation-consume", "activation-permit-consumed-once-before-runtime-transition"),
    ("activation-consume-verify", "activation-consumption-verification-does-not-activate-runtime"),
    ("runtime-activation-commit", "consumed-activation-permit-commits-intent-not-runtime-activation"),
    ("runtime-activation-commit-verify", "activation-commitment-verification-does-not-activate-runtime"),
    ("runtime-activation-boundary", "pre-activation-boundary-proves-runtime-and-fence-unchanged"),
    ("runtime-activation-boundary-verify", "boundary-verification-does-not-activate-runtime"),
    ("runtime-activation-handoff", "deployment-handoff-does-not-activate-runtime"),
    ("runtime-activation-handoff-verify", "handoff-verification-does-not-activate-runtime"),
    ("runtime-transition-rehearsal", "deployment-transition-rehearsal-does-not-execute-activation"),
    ("runtime-transition-rehearsal-verify", "transition-rehearsal-verification-does-not-activate-runtime"),
    ("runtime-transition-permit", "transition-rehearsal-requires-external-short-lived-execution-permit"),
    ("runtime-transition-permit-verify", "transition-permit-verification-does-not-execute-runtime"),
    ("runtime-transition-consume", "transition-execution-permit-consumed-once-before-any-attempt"),
    ("runtime-transition-consume-verify", "transition-consumption-verification-does-not-attempt-runtime-transition"),
)


class SpineManifest:
    """Return the seam list. hit stays false because apply is not landed."""

    def card(self) -> dict[str, Any]:
        return {
            "kind": "spine_manifest",
            "hit": False,
            "law": "manifest-is-not-signoff",
            "citation": "VOL-134",
            "seams": [{"name": name, "law": law} for name, law in SEAMS],
            "count": len(SEAMS),
            "apply_landed": False,
            "poison_apply_landed": True,
            "stored_prose": 0,
            "completion_checkbox": False,
            "implementation_signature": False,
            "verification_signature": False,
        }
